import type { ExplainedOverlayChapter } from "../explainedOverlay.js"
import { VT_MAJOR_PROPHETS_FULL } from "../vtFullNarrativesMajorProphets.js"
import { sectionedTextualChapter } from "./textualChapterFactory.js"

const data = VT_MAJOR_PROPHETS_FULL.daniel
const c = (number: number, sections: Parameters<typeof sectionedTextualChapter>[3]) =>
  sectionedTextualChapter("Daniel", data, number, sections)

export const DANIEL_DEEPENED: Readonly<Record<number, ExplainedOverlayChapter>> = {
  8: c(8, [
    { from: 1, to: 8, heading: "Berbecul cu două coarne este zdrobit de țapul care vine din apus cu un corn mare", teaching: "În al treilea an al lui Belșațar, Daniel se vede în Susa lângă râul Ulai. Un berbec cu două coarne împunge spre vest, nord și sud și nimeni nu îi poate sta împotrivă. Apoi un țap vine atât de repede din apus încât pare să nu atingă pământul, lovește berbecul și îi rupe coarnele. Când țapul devine foarte puternic, cornul lui mare este frânt și în locul lui apar patru coarne spre cele patru vânturi." },
    { from: 9, to: 14, heading: "Dintr-unul dintre cele patru coarne apare o putere care atacă sanctuarul și întrerupe jertfa", teaching: "Un corn mic crește spre sud, răsărit și țara cea frumoasă, se înalță până la oștirea cerului și aruncă la pământ unele stele în limbajul viziunii. El se ridică împotriva Căpeteniei oștirii, îndepărtează jertfa continuă și profanează sanctuarul. Două ființe sfinte discută durata până la restaurarea sanctuarului, iar răspunsul este exprimat prin două mii trei sute de seri și dimineți." },
    { from: 15, to: 22, heading: "Gabriel explică berbecul ca Medo-Persia și țapul ca Grecia", teaching: "Daniel caută să înțeleagă, iar Gabriel este trimis să-i explice vedenia. Profetul cade cu fața la pământ și este ridicat. Interpretarea identifică explicit cele două coarne ale berbecului cu regii Mediei și Persiei și țapul cu Grecia; cornul mare este primul rege, iar cele patru coarne reprezintă patru regate care ies din națiune fără aceeași putere." },
    { from: 23, to: 27, heading: "Un rege îndrăzneț distruge prin viclenie, dar este frânt fără mână omenească", teaching: "În etapa târzie a acestor regate apare un rege cu față aspră, priceput în intrigi, a cărui putere produce distrugere și prosperă prin înșelare. El atacă pe cei puternici și pe poporul sfinților și se ridică împotriva Căpeteniei căpeteniilor, dar este zdrobit fără intervenție omenească. Daniel este bolnav câteva zile după vedenie și rămâne uimit. Identificarea istorică obișnuită cu Antioh IV Epifanes explică multe detalii ale contextului, iar aplicările escatologice suplimentare trebuie marcate ca interpretări, nu ca singurul sens explicit." },
  ]),
  11: c(11, [
    { from: 1, to: 4, heading: "Succesiunea persană este urmată de un rege grec puternic al cărui imperiu se împarte", teaching: "Mesagerul continuă revelația începută în capitolul 10 și spune că mai mulți regi se vor ridica în Persia, iar unul foarte bogat va provoca Grecia. Apoi apare un rege viteaz care conduce cu mare putere, dar împărăția lui este frântă și împărțită spre cele patru vânturi, nu urmașilor săi și nu cu aceeași stăpânire. Descrierea corespunde tranziției de la Persia la imperiul lui Alexandru și divizarea ulterioară." },
    { from: 5, to: 20, heading: "Regii sudului și nordului intră într-un ciclu de alianțe matrimoniale, trădări și campanii", teaching: "Textul urmărește o succesiune densă de conflicte între «regele sudului» și «regele nordului». O alianță prin căsătorie eșuează, un descendent al femeii invadează nordul și ia pradă, apoi campaniile se succed cu armate mari și pierderi. Un rege al nordului ajunge și în țara cea frumoasă, încearcă o altă alianță printr-o fiică și apoi se îndreaptă spre coaste. Un succesor trimite un colector de taxe și moare fără luptă publică. În lectura istorică, aceste detalii urmăresc în mare conflictul Ptolemeilor și Seleucizilor care a prins Iudeea între două puteri." },
    { from: 21, to: 28, heading: "Un conducător disprețuit obține regatul prin intrigi și folosește alianțele ca instrumente de înșelare", teaching: "În locul conducătorului anterior apare unul căruia nu îi fusese dată onoarea regală, dar care intră prin lingușire și intrigi. Armate sunt măturate înaintea lui, iar alianțele nu îl împiedică să lucreze înșelător. Cu o forță relativ mică ajunge puternic, distribuie pradă și planifică împotriva fortificațiilor. Campania spre sud produce o confruntare în care planurile interne slăbesc adversarul, iar cei doi regi stau la aceeași masă spunând minciuni." },
    { from: 29, to: 35, heading: "Întoarcerea împotriva legământului culmină cu profanarea sanctuarului și cu rezistența celor care Îl cunosc pe Dumnezeu", teaching: "O nouă expediție spre sud nu are același rezultat deoarece corăbiile Chitimului îl descurajează. Regele își întoarce furia împotriva legământului sfânt, favorizează pe cei care îl abandonează și trimite forțe care profanează sanctuarul, înlătură jertfa continuă și așază urâciunea pustiirii. Cei care cunosc pe Dumnezeul lor rămân tari și lucrează, iar înțelepții îi învață pe mulți chiar când suferă prin sabie, foc, captivitate și jaf. Ajutorul primit este limitat și unii cad pentru curățire până la vremea hotărâtă." },
    { from: 36, to: 39, heading: "Regele se înalță peste orice dumnezeu și își transformă puterea militară în obiect de cult", teaching: "Figura descrisă se mărește peste orice dumnezeu și vorbește lucruri uimitoare împotriva Dumnezeului dumnezeilor până la împlinirea mâniei hotărâte. Nu respectă zeii tradiționali ai părinților, ci onorează un «dumnezeu al fortărețelor» cu aur, argint și lucruri prețioase și distribuie pământ drept recompensă. De aici înainte limbajul a generat interpretări diferite privind cât de mult continuă descrierea lui Antioh IV și cât de mult se proiectează spre o figură escatologică; textul trebuie prezentat fără a transforma o singură schemă în certitudine Emanus." },
    { from: 40, to: 45, heading: "Conflictul final al capitolului descrie o campanie uriașă care se termină fără ajutor pentru conducător", teaching: "La vremea sfârșitului, regele sudului intră în conflict cu el, iar regele nordului vine ca furtuna cu care, călăreți și multe corăbii. El trece prin țări și intră în țara cea frumoasă, în timp ce unele teritorii scapă și altele sunt supuse. Vești din răsărit și nord îl tulbură și își așază corturile între mare și muntele sfânt, dar ajunge la sfârșit fără ca cineva să-l ajute. Capitolul 12 continuă imediat această scenă, de aceea detaliile cronologice și identificările moderne trebuie ținute distincte de afirmația sigură a textului că puterea arogantă are un sfârșit." },
  ]),
}
