import type { ExplainedOverlayChapter, ExplainedOverlayUnit } from "../explainedOverlay.js"
import { VT_MAJOR_PROPHETS_FULL } from "../vtFullNarrativesMajorProphets.js"
import { sectionedTextualChapter } from "./textualChapterFactory.js"

const data = VT_MAJOR_PROPHETS_FULL.ezechiel
const n = { kind: "biblia-emanus" as const, note: "rezumat textual fără doctrină adăugată" as const }
const c = (number: number, sections: Parameters<typeof sectionedTextualChapter>[3]) =>
  sectionedTextualChapter("Ezechiel", data, number, sections)

export const EZECHIEL_DEEPENED_35_48: Readonly<Partial<Record<number, ExplainedOverlayChapter>>> = {
  35: c(35, [
    { from: 1, to: 9, heading: "Muntele Seir este judecat pentru vrăjmășia veche și pentru vărsarea de sânge a lui Israel", teaching: "Ezechiel își îndreaptă fața spre Seir și anunță că cetățile Edomului vor deveni pustii. Motivul este ostilitatea persistentă și faptul că i-a dat pe fiii lui Israel sabiei tocmai în vremea nenorocirii lor. Pentru că Edomul nu s-a ferit de sânge, sângele îl urmărește în limbajul justiției profetice." },
    { from: 10, to: 15, heading: "Pretenția de a lua cele două țări ignoră faptul că DOMNUL era acolo și auzea batjocura", teaching: "Edom spune că Israel și Iuda vor deveni ale lui după devastare, ca și cum absența temporară a poporului ar însemna absența lui Dumnezeu. DOMNUL răspunde că a auzit cuvintele împotriva munților lui Israel și bucuria la vederea moștenirii pustiite. Așa cum Edom s-a bucurat de dezastrul altuia, el însuși devine pustiu înaintea întregului pământ." },
  ]),
  38: c(38, [
    { from: 1, to: 9, heading: "Gog din țara lui Magog este chemat împotriva unui Israel readunat și aparent sigur", teaching: "Ezechiel profețește împotriva lui Gog, conducător asociat cu Magog, Meșec și Tubal, însoțit de Persia, Cuș, Put și alte popoare. Dumnezeu descrie o mare coaliție militară adusă ca un nor peste țara poporului adunat dintre neamuri. Textul folosește geografia și limbajul militar al lumii profetului; identificarea cu state moderne precise rămâne interpretativă și nu trebuie prezentată drept certitudine a textului." },
    { from: 10, to: 13, heading: "Planul lui Gog este prada unei țări fără ziduri, iar alte popoare întreabă dacă a venit pentru jaf", teaching: "Gog concepe un plan rău împotriva unor oameni care locuiesc în siguranță și fără fortificațiile pe care un cuceritor le-ar aștepta. Ținta este argintul, aurul, vitele și bunurile. Șeba, Dedan și negustorii Tarsisului îl întreabă dacă și-a adunat mulțimea tocmai pentru a lua pradă." },
    { from: 14, to: 17, heading: "Invazia devine scena prin care Dumnezeu Își face cunoscut Numele înaintea națiunilor", teaching: "Gog vine din nord cu o armată numeroasă când Israel locuiește în siguranță. Dumnezeu spune că îl aduce împotriva țării pentru ca neamurile să-L cunoască atunci când Își arată sfințenia prin ceea ce face. Profetul leagă evenimentul și de cuvintele rostite înainte prin slujitorii lui Dumnezeu." },
    { from: 18, to: 23, heading: "Cutremurul, sabia și furtuna desfac coaliția fără ca Israel să fie prezentat drept salvatorul propriu", teaching: "Când Gog intră în țară, mânia este descrisă printr-un mare cutremur care atinge oameni, animale, munți și ziduri. Sabia fiecăruia se întoarce împotriva fratelui său, iar ciuma, sângele, ploaia, grindina și focul completează imaginea. Scopul final este mărirea și sfințirea Numelui lui Dumnezeu înaintea multor națiuni." },
  ]),
  39: c(39, [
    { from: 1, to: 8, heading: "Gog este doborât pe munții lui Israel, iar armele invaziei devin combustibil", teaching: "Dumnezeu îl aduce pe Gog din nord și îi doboară arcul și săgețile, lăsând armata pradă păsărilor și fiarelor. Focul ajunge și în Magog și pe coastele sigure. Israel nu mai trebuie să folosească lemn din câmp pentru o perioadă, pentru că arde armele invadatorilor. Ziua este prezentată ca una anunțată de Dumnezeu." },
    { from: 9, to: 16, heading: "Șapte ani de ardere și șapte luni de îngropare exprimă curățarea completă a țării după război", teaching: "Scuturi, arcuri, săgeți, măciuci și sulițe sunt arse, iar cei care jefuiseră devin ei înșiși pradă. O vale este rezervată pentru mormintele mulțimii lui Gog, iar casa lui Israel lucrează luni întregi pentru a curăța țara. Oameni special desemnați marchează chiar oasele rămase pentru îngropare. Imaginile arată proporția dezastrului și grija de a elimina impuritatea morții." },
    { from: 17, to: 20, heading: "Păsările și animalele sunt chemate la un ospăț macabru pe trupurile războinicilor", teaching: "Ezechiel trebuie să cheme păsările și fiarele la o mare jertfă pe munții lui Israel, unde mănâncă trupurile și beau sângele conducătorilor și războinicilor. Limbajul intenționat șocant inversează banchetul victoriei militare: armata care venea să consume țara devine ea însăși masa. Nu este instrucțiune pentru tratarea morților în conflicte umane." },
    { from: 21, to: 29, heading: "După judecată, Israel înțelege exilul, iar Dumnezeu promite adunare și revărsarea Duhului", teaching: "Neamurile văd judecata, iar casa lui Israel înțelege că exilul nu fusese dovada neputinței lui Dumnezeu, ci răspuns la necredincioșie. Dumnezeu spune că îi adună dintre dușmani, nu mai lasă niciunul acolo și nu-Și mai ascunde fața. Ultimul verset leagă restaurarea de revărsarea Duhului Său peste casa lui Israel." },
  ]),
  40: c(40, [
    { from: 1, to: 4, heading: "La douăzeci și cinci de ani de exil, Ezechiel este dus pe un munte înalt și întâlnește un om cu instrumente de măsurat", teaching: "Viziunea templului începe la o dată precisă, după căderea cetății. Profetul vede o construcție ca o cetate și un om cu aspect de bronz, șnur de in și trestie de măsurat. Ezechiel trebuie să privească, să asculte și să pună la inimă fiecare detaliu pentru a-l spune casei lui Israel." },
    { from: 5, to: 16, heading: "Poarta de răsărit este măsurată cu praguri, camere pentru paznici și pridvor", teaching: "Zidul exterior și poarta de răsărit sunt măsurate în coți, inclusiv pragul, camerele laterale, spațiile dintre ele și pridvorul. Ferestrele și palmierii sculptați apar în structură. Repetarea dimensiunilor arată un spațiu ordonat și delimitat, nu un templu improvizat." },
    { from: 17, to: 27, heading: "Curtea exterioară și porțile de nord și sud repetă aceeași ordine arhitecturală", teaching: "Profetul vede treizeci de camere și un pavaj în jurul curții exterioare. Distanța până la curtea interioară este măsurată, apoi porțile de nord și sud sunt verificate după același model: camere, ferestre, pridvoare și palmieri. Simetria devine o caracteristică a viziunii." },
    { from: 28, to: 43, heading: "Porțile curții interioare și camerele pentru pregătirea jertfelor sunt măsurate", teaching: "Ezechiel intră spre curtea interioară prin sud, est și nord, iar fiecare poartă este măsurată. Apar mese pentru înjunghierea arderilor-de-tot și a jertfelor, cârlige și alte mese pe care se pune carnea. Viziunea descrie funcționarea cultică a spațiului, nu doar estetica lui." },
    { from: 44, to: 49, heading: "Camerele preoților și pridvorul templului încheie prima etapă a măsurătorilor", teaching: "Două camere sunt rezervate preoților care păzesc casa și altarul, în special fiilor lui Țadoc. Curtea este măsurată ca pătrat, altarul se află înaintea casei, iar omul îl conduce pe Ezechiel la pridvorul templului, măsurând stâlpii, intrarea și treptele." },
  ]),
  41: c(41, [
    { from: 1, to: 11, heading: "Sanctuarul și Sfânta Sfintelor sunt măsurate împreună cu camerele laterale", teaching: "Omul măsoară stâlpii, intrările și lungimea sanctuarului, apoi intră în încăperea interioară pe care o numește Sfânta Sfintelor. Zidul casei și camerele laterale pe trei niveluri sunt descrise tehnic, inclusiv felul în care se lărgesc spre etajele superioare fără a intra în zidul principal." },
    { from: 12, to: 15, heading: "Clădirea dinspre apus și dimensiunile totale ale templului formează un ansamblu măsurat", teaching: "O clădire separată din partea vestică primește dimensiuni precise, iar apoi templul, curtea și clădirea sunt măsurate la o sută de coți în diferite direcții. Viziunea insistă asupra proporțiilor și limitelor spațiului sacru." },
    { from: 16, to: 26, heading: "Interiorul este acoperit cu lemn și sculpturi de heruvimi și palmieri", teaching: "Pragurile, ferestrele și galeriile sunt acoperite cu lemn, iar pereții sunt sculptați cu heruvimi și palmieri alternanți. Fiecare heruvim are două fețe orientate spre palmieri. Altarul de lemn este numit masa care stă înaintea DOMNULUI, iar ușile sanctuarului și ale Sfântei Sfintelor au câte două canaturi și aceleași motive sculptate." },
  ]),
  42: c(42, [
    { from: 1, to: 12, heading: "Camerele preoțești din nord și sud sunt măsurate în raport cu curțile templului", teaching: "Ezechiel este dus în curtea exterioară și vede o clădire de camere pe trei niveluri, cu galerii și dimensiuni diferite. Pasajele și intrările sunt descrise în detaliu, iar un complex asemănător se află și în sud. Arhitectura separă spațiile destinate slujirii preoțești de circulația obișnuită." },
    { from: 13, to: 14, heading: "Camerele sunt sfinte pentru consumarea jertfelor și păstrarea veșmintelor preoțești", teaching: "Omul explică funcția camerelor: preoții care se apropie de DOMNUL mănâncă acolo lucrurile preasfinte și păstrează darurile, jertfele pentru păcat și vină. Când ies spre curtea exterioară, nu poartă automat veșmintele sacre în spațiul comun, ci le lasă acolo și se schimbă." },
    { from: 15, to: 20, heading: "Întregul complex este măsurat pe cele patru laturi și separat printr-un zid", teaching: "După măsurătorile interioare, omul măsoară partea de est, nord, sud și vest, fiecare la cinci sute de trestii. Zidul înconjurător are o funcție declarată: separă ceea ce este sfânt de ceea ce este comun." },
  ]),
  43: c(43, [
    { from: 1, to: 9, heading: "Slava Dumnezeului lui Israel se întoarce prin poarta de răsărit și umple templul", teaching: "Ezechiel vede dinspre răsărit slava pe care o cunoscuse lângă Chebar și în vedenia distrugerii cetății. Sunetul este ca vuietul apelor, iar pământul strălucește. Profetul cade cu fața la pământ, Duhul îl ridică și îl duce în curtea interioară. Dumnezeu spune că acesta este locul tronului Său și că Israel nu va mai întina Numele prin idolatrie și monumentele regilor." },
    { from: 10, to: 12, heading: "Casa lui Israel trebuie să privească planul templului și să se rușineze de fărădelegile ei", teaching: "Ezechiel este chemat să descrie templul, astfel încât poporul să își vadă rușinea și să măsoare modelul. Dacă se rușinează, profetul le arată forma, ieșirile, intrările, regulile și legile. Legea fundamentală a casei este că întregul vârf al muntelui este preasfânt." },
    { from: 13, to: 17, heading: "Altarul este măsurat de la bază până la vatra cu patru coarne", teaching: "Dimensiunile altarului sunt date în coți, inclusiv baza, treptele intermediare, vatra și coarnele. Forma pătrată și măsurătorile pregătesc ritualul consacrării care urmează." },
    { from: 18, to: 27, heading: "Șapte zile de jertfe consacră altarul, iar din ziua a opta slujirea este primită", teaching: "Preoții leviți din familia lui Țadoc primesc animale pentru jertfa pentru păcat, iar sângele este pus pe coarnele și marginile altarului. În zile succesive sunt aduse animale fără cusur pentru curățire și consacrare. După șapte zile, din ziua a opta preoții pot aduce arderile-de-tot și jertfele de pace, iar Dumnezeu spune că îi va primi." },
  ]),
  44: c(44, [
    { from: 1, to: 3, heading: "Poarta exterioară de răsărit rămâne închisă pentru că slava DOMNULUI a intrat pe acolo", teaching: "Ezechiel este dus la poarta de est și o găsește închisă. Dumnezeu explică faptul că nimeni nu o mai deschide pentru trecere obișnuită pentru că El a intrat prin ea. Prințul poate sta în pridvor pentru a mânca înaintea DOMNULUI, dar intrarea și ieșirea lui urmează traseul stabilit." },
    { from: 4, to: 9, heading: "Accesul la sanctuar este legat de sfințenie după ce casa lui Israel permisese străinilor neconsacrați să slujească", teaching: "Slava umple casa, iar Ezechiel cade înaintea ei. Dumnezeu îi cere să observe regulile intrărilor și ieșirilor și confruntă Israelul pentru că adusese în sanctuar oameni necircumciși în inimă și trup, încălcând legământul. Slujirea sfântă nu poate fi tratată ca funcție delegată oricui fără raportare la legământ." },
    { from: 10, to: 14, heading: "Leviții care s-au depărtat cu idolii poartă consecințe, dar primesc încă slujiri limitate", teaching: "Leviții care au rătăcit când Israel mergea după idoli poartă nelegiuirea și nu se mai apropie de Dumnezeu în slujirea preoțească cea mai apropiată. Totuși ei rămân slujitori ai casei, păzesc porțile și ajută la jertfe. Consecința nu înseamnă eliminarea oricărei responsabilități, ci limitarea rolului." },
    { from: 15, to: 27, heading: "Fiii lui Țadoc primesc reguli stricte pentru apropierea de altar și distingerea sfântului de comun", teaching: "Preoții care au păzit sanctuarul când Israel rătăcea se apropie de Dumnezeu. Veșmintele lor sunt din in, fără lână care produce transpirație, iar hainele sacre nu sunt purtate în curtea poporului. Regulile privesc părul, vinul în timpul slujirii, căsătoria și responsabilitatea de a învăța poporul diferența dintre sfânt și comun și dintre curat și necurat." },
    { from: 28, to: 31, heading: "Moștenirea preoților este Dumnezeu, iar hrana lor vine din darurile sfinte, nu din proprietate tribală", teaching: "Preoții nu primesc o moștenire funciară obișnuită în Israel pentru că Dumnezeu este moștenirea lor. Darurile, jertfele, întâile roade și lucrurile consacrate le asigură hrana. Totuși nu pot consuma animale moarte de la sine sau sfâșiate, menținând regulile de curăție." },
  ]),
  45: c(45, [
    { from: 1, to: 8, heading: "Țara este împărțită cu o porțiune sfântă pentru sanctuar, preoți, leviți și cetate, iar prințul primește limite", teaching: "La împărțirea țării, o fâșie este oferită DOMNULUI pentru sanctuar și slujitori, iar o parte separată aparține cetății. Prințul primește teren pe ambele părți ale porțiunii sfinte, dar scopul explicit este ca el să nu mai asuprească poporul și să lase casele lui Israel în moștenirile lor." },
    { from: 9, to: 12, heading: "Conducătorii sunt chemați să renunțe la violență și să folosească măsuri comerciale drepte", teaching: "Prinții lui Israel aud «destul!» și sunt chemați să îndepărteze violența și jaful, să practice dreptatea și să nu mai evacueze poporul din proprietăți. Cântarul, efa și batul trebuie să fie drepte, iar unitățile monetare sunt stabilite. Reforma cultică începe aici și cu economie corectă." },
    { from: 13, to: 20, heading: "Darurile poporului și ale prințului susțin jertfele și curățirea sanctuarului", teaching: "Grâu, orz, ulei și oi sunt stabilite ca daruri pentru arderi-de-tot, jertfe de pace și ispășire. Prințul are responsabilitatea să ofere animale și daruri la sărbători. În prima și a șaptea zi a lunii întâi, sanctuarul este curățit pentru greșelile neintenționate sau ale celui nepriceput." },
    { from: 21, to: 25, heading: "Paștele și sărbătoarea lunii a șaptea primesc rânduieli pentru jertfele prințului", teaching: "În ziua a paisprezecea a lunii întâi se ține Paștele șapte zile cu azime, iar prințul aduce animale pentru păcat, ardere-de-tot și dar de mâncare. O structură asemănătoare apare în luna a șaptea. Viziunea reconstruiește astfel calendarul cultic în spațiul restaurat." },
  ]),
  46: c(46, [
    { from: 1, to: 8, heading: "Poarta interioară de răsărit se deschide în Sabat și lună nouă pentru închinarea prințului și poporului", teaching: "Poarta rămâne închisă în cele șase zile de lucru, dar se deschide în Sabat și la lună nouă. Prințul intră până la pragul porții, preoții îi aduc jertfele și el se închină, în timp ce poporul se închină la intrare. Numărul animalelor și darurile sunt stabilite pentru aceste zile." },
    { from: 9, to: 15, heading: "La sărbători, oamenii traversează curtea fără să se întoarcă pe aceeași poartă, iar jertfa zilnică menține ritmul continuu", teaching: "Cine intră pe poarta de nord iese pe sud și invers, continuând înainte, iar prințul merge împreună cu poporul. Darurile la sărbători sunt proporționate cu animalele, iar când prințul aduce voluntar o jertfă poarta se deschide pentru el și apoi se închide. În fiecare dimineață este adus un miel împreună cu făină și ulei ca rânduială permanentă." },
    { from: 16, to: 18, heading: "Prințul nu poate folosi darurile pentru a deposeda poporul de moștenirea lui", teaching: "Dacă prințul dă unui fiu din propria moștenire, darul rămâne în familie. Dacă îl dă unui slujitor, proprietatea revine prințului în anul eliberării. Mai important, el nu are voie să ia din moștenirea poporului pentru a-și înzestra fiii; trebuie să dea din proprietatea lui, astfel încât nimeni să nu fie împrăștiat din moștenirea sa." },
    { from: 19, to: 24, heading: "Bucătăriile pentru jertfe separă prepararea lucrurilor sfinte de spațiile comune", teaching: "Ezechiel este dus la camerele preoților unde sunt fierte jertfele pentru vină și păcat și coapte darurile, pentru ca lucrurile sfinte să nu fie scoase în curtea exterioară fără discernământ. În cele patru colțuri ale curții exterioare există și bucătării unde slujitorii casei fierb jertfele poporului." },
  ]),
  48: c(48, [
    { from: 1, to: 8, heading: "Triburile din nord primesc fâșii paralele de la est la vest până la porțiunea sfântă", teaching: "Dan, Așer, Neftali, Manase, Efraim, Ruben și Iuda primesc fiecare o parte întinsă de la marginea de est la mare. După Iuda urmează darul sfânt de douăzeci și cinci de mii de coți, cu sanctuarul în mijloc. Împărțirea ordonată pune fiecare trib într-o relație clară cu centrul sacru." },
    { from: 9, to: 14, heading: "Preoții și leviții primesc porțiuni care nu pot fi vândute sau schimbate", teaching: "Partea preoților, mai ales a fiilor lui Țadoc care au rămas credincioși, este preasfântă lângă porțiunea leviților. Leviții au și ei o fâșie egală ca lungime, iar terenul nu poate fi vândut, schimbat sau înstrăinat pentru că este sfânt pentru DOMNUL." },
    { from: 15, to: 22, heading: "Cetatea, terenul comun și proprietatea prințului sunt integrate în porțiunea centrală", teaching: "O fâșie de cinci mii de coți este comună și aparține cetății, cu dimensiuni și spații deschise măsurate. Lucrătorii din toate triburile cultivă terenul care îi furnizează hrană. Ce rămâne la est și vest aparține prințului, astfel că porțiunea sfântă și cetatea se află între proprietățile lui fără a fi absorbite de ele." },
    { from: 23, to: 29, heading: "Triburile din sud primesc moșteniri până la granița de miazăzi", teaching: "Beniamin, Simeon, Isahar, Zabulon și Gad primesc la rândul lor fâșii paralele. Hotarul lui Gad ajunge spre Tamar, apele Meriba-Cadeș și pârâul Egiptului până la Marea cea Mare. Dumnezeu spune că aceasta este țara care trebuie împărțită prin sorți ca moștenire triburilor." },
    { from: 30, to: 35, heading: "Cele douăsprezece porți poartă numele triburilor, iar numele final al cetății este «DOMNUL este acolo»", teaching: "Cetatea are câte trei porți pe fiecare latură, purtând numele celor douăsprezece triburi ale lui Israel. Perimetrul total este măsurat la optsprezece mii de coți. Ultimele cuvinte ale cărții nu sunt o dimensiune, ci un nume: «DOMNUL este acolo». După plecarea slavei din capitolele timpurii, prezența lui Dumnezeu devine concluzia viziunii restaurării." },
  ]),
}

export const EZECHIEL_FOCUSED_COMPLEMENTS: Readonly<Record<number, readonly ExplainedOverlayUnit[]>> = {
  33: [
    { from: 21, to: 29, heading: "După vestea căderii Ierusalimului, cei rămași în ruine revendică țara pe baza lui Avraam", teaching: "Fugarul ajunge cu vestea «cetatea a fost lovită», iar gura lui Ezechiel se deschide. Locuitorii ruinelor spun că Avraam era unul și a primit țara, deci ei, fiind mulți, au cu atât mai mult drept asupra ei. Dumnezeu răspunde că revendicarea moștenirii nu poate fi separată de idolatrie, sânge și adulter; ruinele și câmpurile vor rămâne sub sabie și fiare până când țara devine pustie.", source: n },
    { from: 30, to: 33, heading: "Oamenii vin să-l asculte pe Ezechiel ca pe un cântăreț plăcut, dar nu fac ceea ce aud", teaching: "Exilații vorbesc între ei despre profet și vin în număr mare să îi audă cuvintele. Dumnezeu spune însă că gura lor exprimă iubire în timp ce inima urmărește câștigul. Ezechiel devine pentru ei ca un cântec frumos interpretat de cineva talentat: ascultă, dar nu practică. Când cuvântul se împlinește, vor ști că a fost un profet între ei.", source: n },
  ],
  36: [
    { from: 1, to: 7, heading: "Munții lui Israel aud o promisiune după ce dușmanul a revendicat înălțimile ca proprietate", teaching: "Ezechiel profețește munților pe care dușmanii îi declaraseră moștenire. Edomul și celelalte națiuni s-au bucurat de pustiire și au luat țara cu dispreț. Dumnezeu spune că tocmai această pradă și batjocură intră sub jurământul judecății Sale.", source: n },
    { from: 8, to: 15, heading: "Munții vor produce din nou ramuri și rod pentru Israelul care se întoarce", teaching: "În locul pustiirii, munții sunt chemați să dea ramuri și fructe pentru poporul care se apropie. Oamenii și animalele se înmulțesc, cetățile sunt locuite și ruinele reconstruite. Țara nu mai este acuzată că își devorează locuitorii și nu mai poartă aceeași batjocură între neamuri.", source: n },
    { from: 16, to: 21, heading: "Exilul a profanat Numele lui Dumnezeu între neamuri, deși judecata venise pentru sânge și idoli", teaching: "Casa lui Israel și-a întinat țara prin căi și fapte, iar Dumnezeu a revărsat mânia pentru sângele vărsat și idolii slujiți. Risipiți între națiuni, ei au făcut ca oamenii să spună că acesta este poporul DOMNULUI și totuși a trebuit să iasă din țara Lui. Dumnezeu spune că Îi pasă de Numele Său sfânt, pregătind promisiunea din versetul 22 înainte.", source: n },
  ],
  37: [
    { from: 15, to: 23, heading: "Două bețe, pentru Iuda și Iosif, devin unul singur în mâna profetului", teaching: "După oasele uscate, Dumnezeu îi cere lui Ezechiel să scrie pe două bețe numele lui Iuda și al lui Iosif/Efraim și să le unească. Când oamenii întreabă, semnul este explicat prin reunirea copiilor lui Israel din națiuni într-un singur popor și sub un singur rege. Idolatria și fărădelegile nu îi mai întinează, iar Dumnezeu îi curăță și reînnoiește formula legământului.", source: n },
    { from: 24, to: 28, heading: "Robul David păstorește poporul unit, iar legământul păcii și sanctuarul rămân între ei", teaching: "Un singur rege, numit robul Meu David, devine păstor peste poporul care umblă în hotărârile lui Dumnezeu. Ei locuiesc în țară, iar legământul păcii este numit veșnic. Sanctuarul și locuința lui Dumnezeu sunt în mijlocul lor, astfel încât neamurile cunosc că DOMNUL este Cel care sfințește Israelul.", source: n },
  ],
  47: [
    { from: 13, to: 20, heading: "După râul vindecător, hotarele țării sunt trasate pentru cele douăsprezece triburi", teaching: "Dumnezeu descrie limitele moștenirii de la nord, est, sud și vest și precizează că Iosif primește două părți. Țara este împărțită pentru triburile lui Israel potrivit hotarelor viziunii, legând restaurarea apei din templu de o comunitate concret așezată într-un teritoriu.", source: n },
    { from: 21, to: 23, heading: "Străinii stabiliți între Israel primesc moștenire împreună cu tribul în care locuiesc", teaching: "Împărțirea nu îi exclude pe străinii care locuiesc între popor și au copii acolo. Ei trebuie considerați ca nativi între fiii lui Israel și primesc moștenire în tribul unde s-au stabilit. Este o lărgire remarcabilă a participării la țară în cadrul viziunii restaurate.", source: n },
  ],
}
