import type { ExplainedOverlayChapter } from "../explainedOverlay.js"
import { VT_MAJOR_PROPHETS_FULL } from "../vtFullNarrativesMajorProphets.js"
import { sectionedTextualChapter } from "./textualChapterFactory.js"

const data = VT_MAJOR_PROPHETS_FULL.ezechiel
const c = (number: number, sections: Parameters<typeof sectionedTextualChapter>[3]) =>
  sectionedTextualChapter("Ezechiel", data, number, sections)

export const EZECHIEL_DEEPENED_04_16: Readonly<Record<number, ExplainedOverlayChapter>> = {
  4: c(4, [
    { from: 1, to: 8, heading: "O cărămidă, un asediu miniatural și trupul profetului devin semne pentru Ierusalim", teaching: "Ezechiel desenează Ierusalimul pe o cărămidă și construiește în jurul ei imaginea unui asediu, apoi pune o placă de fier între el și cetate. Este chemat să stea culcat pe o parte pentru zile simbolice legate de nelegiuirea lui Israel și Iuda. Acțiunile profetice fac vizibil un mesaj pe care exilații îl puteau altfel trata ca abstract." },
    { from: 9, to: 13, heading: "Hrana cântărită și apa măsurată descriu viața sub asediu", teaching: "Grâne și leguminoase diferite sunt amestecate într-o pâine consumată în porții mici, iar apa este măsurată. Hrana nu este prezentată ca rețetă spirituală sau dietă ideală, ci ca semn al penuriei. Porunca inițială privind combustibilul exprimă și impuritatea pe care exilații o vor experimenta între neamuri." },
    { from: 14, to: 17, heading: "Dumnezeu răspunde obiecției lui Ezechiel, dar semnul foametei rămâne", teaching: "Profetul protestează că nu s-a întinat prin hrana interzisă, iar Dumnezeu îi permite balegă de vită în locul celei omenești pentru coacere. Concesia arată că ascultarea profetică nu cere anularea oricărei conștiințe. Totuși mesajul principal rămâne: pâinea și apa vor fi atât de puține încât oamenii le vor consuma cu teamă și se vor topi în nelegiuirea lor." },
  ]),
  5: c(5, [
    { from: 1, to: 4, heading: "Părul ras și împărțit în trei devine o hartă simbolică a sorții cetății", teaching: "Ezechiel își rade capul și barba cu o sabie și împarte părul cântărit în trei: o parte este arsă, una lovită cu sabia și una împrăștiată în vânt. Câteva fire sunt păstrate în poala hainei, iar chiar dintre ele unele intră în foc. Semnul anunță judecată severă, dar păstrează și imaginea unei rămășițe mici." },
    { from: 5, to: 12, heading: "Ierusalimul, așezat între neamuri, este judecat pentru o răzvrătire mai mare decât a vecinilor", teaching: "Dumnezeu spune că cetatea fusese pusă în mijlocul națiunilor, dar a respins hotărârile Lui. Judecata este descrisă prin foamete, ciumă, sabie și risipire, inclusiv imagini cumplite ale canibalismului din asediu. Acestea descriu degradarea extremă a unei cetăți înfometate și nu sunt prezentate drept comportament legitim." },
    { from: 13, to: 17, heading: "Ruina devine avertisment pentru națiunile din jur", teaching: "Mânia ajunge la capăt, iar Ierusalimul devine reproș, batjocură și avertisment. Foametea este numită săgeată nimicitoare, iar fiarele, ciuma și sabia completează imaginea. Repetarea formulei «Eu, DOMNUL, am vorbit» accentuează seriozitatea cuvântului profetic." },
  ]),
  6: c(6, [
    { from: 1, to: 7, heading: "Munții lui Israel sunt chemați să audă judecata asupra locurilor înalte și idolilor", teaching: "Ezechiel profețește împotriva munților, dealurilor, văilor și râpelor tocmai pentru că acestea deveniseră locuri ale altarelor și stâlpilor idolatri. Altarele sunt dărâmate, imaginile solare sfărâmate și morții cad înaintea idolilor. Locurile cultice pe care poporul le considera surse de protecție devin martori ai neputinței lor." },
    { from: 8, to: 10, heading: "O rămășiță împrăștiată își va aminti de Dumnezeu și va vedea urâțenia idolatriei", teaching: "Dumnezeu spune că va lăsa câțiva să scape de sabie între națiuni. În exil, ei își vor aminti de El și vor înțelege cât de mult L-a rănit inima lor adulteră și privirea lor orientată spre idoli. Pocăința este descrisă ca o schimbare a felului în care își văd propriul rău, nu doar ca dorință de a scăpa de consecințe." },
    { from: 11, to: 14, heading: "Sabia, foametea și ciuma închid cercul judecății până când țara devine pustie", teaching: "Profetul bate din palme și din picior ca semn al groazei pentru fărădelegile casei lui Israel. Cel departe moare prin ciumă, cel aproape prin sabie și cel rămas prin foamete. Cadavrele lângă altare arată din nou eșecul idolilor, iar țara este făcută pustie până când oamenii cunosc că DOMNUL a vorbit." },
  ]),
  7: c(7, [
    { from: 1, to: 9, heading: "«Sfârșitul a venit» repetă că timpul amânării pentru țară se încheie", teaching: "Cuvântul anunță sfârșitul celor patru colțuri ale țării și spune că judecata vine după căile și urâciunile poporului. Ochii nu vor cruța, iar nenorocirea este descrisă ca unică. Repetarea «vine» și «a sosit» comprimă timpul: mesajul nu mai privește o posibilitate îndepărtată, ci o criză ajunsă la ușă." },
    { from: 10, to: 13, heading: "Mândria înflorește ca o nuia, dar comerțul și proprietatea își pierd sensul în ziua răsturnării", teaching: "Ziua a venit, violența s-a ridicat și mândria a înmugurit. Cumpărătorul nu are motiv de bucurie și vânzătorul nu trebuie să jelească în logica obișnuită, fiindcă judecata atinge întreaga mulțime și nimeni nu se întoarce la proprietatea vândută. Economia normală se destramă când ordinea socială cade." },
    { from: 14, to: 22, heading: "Sabia afară, foametea înăuntru și aurul inutil expun falsele siguranțe", teaching: "Trâmbița sună, dar nimeni nu pornește la luptă. Cei din câmp întâlnesc sabia, iar cei din cetate ciuma și foametea. Supraviețuitorii gem pe munți ca porumbeii. Argintul este aruncat pe străzi și aurul devine impur pentru că nu poate salva viața sau umple stomacul. Chiar sanctuarul este profanat când Dumnezeu își întoarce fața." },
    { from: 23, to: 27, heading: "Violența, conducerea paralizată și lipsa unui cuvânt transformă lanțul într-un simbol al cetății", teaching: "Țara este plină de crime și cetatea de violență, iar cei mai răi dintre neamuri vin să ocupe casele. Oamenii caută pace fără să o găsească, nenorocire după nenorocire și zvon după zvon. Profetul, preotul, bătrânul, regele și prințul își pierd fiecare capacitatea obișnuită de a conduce. Dumnezeu spune că îi va judeca după propriile căi." },
  ]),
  8: c(8, [
    { from: 1, to: 6, heading: "Ezechiel este dus în vedenie la Ierusalim și vede imaginea geloziei la intrarea templului", teaching: "În timp ce bătrânii lui Iuda stau înaintea profetului în exil, mâna DOMNULUI vine peste el și este dus în viziune la templu. Acolo vede o imagine idolatră care provoacă gelozia și este întrebat dacă observă urâciunile care împing prezența lui Dumnezeu departe de sanctuar." },
    { from: 7, to: 13, heading: "Într-o cameră ascunsă, bătrânii ard tămâie înaintea imaginilor de animale și idoli", teaching: "Profetul sapă prin zid și găsește o încăpere acoperită cu imagini idolatre. Șaptezeci de bătrâni, inclusiv Iaazania, stau cu cădelnițe și spun că DOMNUL nu îi vede și a părăsit țara. Practica secretă contrazice rolul public al conducătorilor; ascunderea față de comunitate nu înseamnă ascundere față de Dumnezeu." },
    { from: 14, to: 15, heading: "La poarta templului, femeile îl plâng pe Tamuz", teaching: "Ezechiel vede femei participând la un ritual de doliu pentru Tamuz. Scena este prezentată ca încă un strat al sincretismului religios care a intrat în spațiul templului. Textul condamnă actul cultic concret, nu femeile ca grup." },
    { from: 16, to: 18, heading: "Douăzeci și cinci de bărbați se pleacă spre soare cu spatele la templu", teaching: "În curtea interioară, oamenii stau între pridvor și altar, întorc spatele Casei DOMNULUI și se închină soarelui spre răsărit. Dumnezeu leagă aceste urâciuni religioase de violența care umple țara. Ritualul și nedreptatea socială nu sunt probleme separate, iar strigătul din ziua judecății nu poate transforma automat refuzul persistent în ascultare." },
  ]),
  9: c(9, [
    { from: 1, to: 4, heading: "Executanții judecății sunt chemați, iar un om îmbrăcat în in primește sarcina de a marca pe cei care gem pentru urâciuni", teaching: "Șase oameni cu arme apar împreună cu unul care are o călimară de scrib. Slava lui Dumnezeu se ridică de pe heruvim spre prag, iar scribul este trimis prin Ierusalim să pună un semn pe fruntea celor care suspină și gem din cauza răului practicat. Distincția nu este între cei care pretind identitate religioasă și ceilalți, ci între cei care participă la rău și cei care îl deplâng." },
    { from: 5, to: 7, heading: "Judecata începe de la sanctuar și nu cruță pe baza vârstei sau poziției", teaching: "Ceilalți primesc porunca să treacă prin cetate după scrib și să lovească, începând de la Casa lui Dumnezeu. Limbajul este de o severitate extremă și aparține viziunii profetice de judecată; nu constituie mandat pentru violență religioasă umană împotriva persoanelor considerate păcătoase." },
    { from: 8, to: 11, heading: "Ezechiel cade cu fața la pământ și întreabă dacă rămășița va fi nimicită complet", teaching: "Profetul nu privește execuția rece, ci strigă către Dumnezeu pentru rămășița lui Israel. Răspunsul spune că nelegiuirea, sângele și nedreptatea sunt foarte mari și că oamenii presupun că Dumnezeu nu vede. Capitolul se încheie cu scribul întorcându-se și raportând că a făcut ceea ce i s-a poruncit." },
  ]),
  10: c(10, [
    { from: 1, to: 8, heading: "Cărbunii dintre heruvimi sunt luați pentru a fi împrăștiați peste cetate", teaching: "Deasupra întinderii apare din nou asemănarea tronului, iar omul îmbrăcat în in primește porunca să intre între roți și heruvimi, să ia cărbuni aprinși și să-i împrăștie peste Ierusalim. Norul umple curtea și slava DOMNULUI se ridică la prag, în timp ce sunetul aripilor heruvimilor se aude până în curtea exterioară." },
    { from: 9, to: 17, heading: "Roțile pline de ochi și făpturile vii se mișcă împreună fără să se întoarcă din drum", teaching: "Ezechiel descrie patru roți, aspectul lor ca piatra de crisolit și structura unei roți în interiorul alteia. Trupurile și roțile sunt pline de ochi, iar toate se mișcă în direcția în care se îndreaptă făpturile pentru că duhul lor este în roți. Viziunea repetă și dezvoltă imaginile din capitolul 1 despre mobilitatea slavei divine." },
    { from: 18, to: 22, heading: "Slava DOMNULUI părăsește pragul și se oprește deasupra heruvimilor", teaching: "Slava se mută de la prag și se ridică deasupra heruvimilor, care pleacă împreună cu roțile spre poarta de răsărit. Ezechiel îi recunoaște ca făpturile văzute lângă Chebar. Plecarea treptată a slavei face vizibilă gravitatea profanării templului înainte de distrugerea clădirii." },
  ]),
  11: c(11, [
    { from: 1, to: 13, heading: "Conducătorii care dau sfat rău sunt confruntați, iar moartea lui Pelatia îl face pe Ezechiel să strige pentru rămășiță", teaching: "Duhul îl duce la poarta de răsărit unde vede douăzeci și cinci de oameni, inclusiv Iaazania și Pelatia, care sunt acuzați că plănuiesc răul și oferă sfaturi stricate. Proverbul lor despre cetate ca oală de gătit este întors împotriva lor: morții pe care i-au produs sunt carnea, iar ei vor fi scoși din cetate și dați sabiei. Când Pelatia moare în timpul profeției, Ezechiel cade și întreabă dacă Dumnezeu va nimici complet rămășița." },
    { from: 14, to: 21, heading: "Exilații disprețuiți de cei rămași primesc promisiunea unui sanctuar, a întoarcerii și a unei inimi noi", teaching: "Locuitorii Ierusalimului le spun exilaților să stea departe de DOMNUL și pretind țara pentru ei. Dumnezeu răspunde că, deși i-a împrăștiat, El Însuși le-a fost un mic sanctuar în țările lor. Îi va aduna, iar ei vor îndepărta idolii. Promisiunea centrală este o inimă unită și un duh nou, o inimă de carne în locul celei de piatră, pentru o viață de ascultare." },
    { from: 22, to: 25, heading: "Slava părăsește cetatea și se oprește pe muntele de la răsărit, iar profetul revine la exilați", teaching: "Heruvimii își ridică aripile, roțile merg cu ei, iar slava Dumnezeului lui Israel se ridică deasupra și pleacă din mijlocul cetății spre muntele din est. Duhul îl aduce pe Ezechiel înapoi în Caldeea, iar el povestește exilaților tot ce i-a arătat DOMNUL." },
  ]),
  12: c(12, [
    { from: 1, to: 7, heading: "Bagajul de exil și ieșirea prin zid sunt jucate în public înaintea unei case răzvrătite", teaching: "Ezechiel locuiește între oameni care au ochi dar nu văd și urechi dar nu aud. Ziua își pregătește bagajul de captiv, iar seara sapă prin zid și iese cu fața acoperită, purtând lucrurile pe umăr. Acțiunea este făcută înaintea lor în speranța că vor înțelege semnul." },
    { from: 8, to: 16, heading: "Semnul este explicat prin soarta prințului Ierusalimului și a oamenilor care vor fi risipiți", teaching: "Când oamenii întreabă ce face, Dumnezeu explică faptul că povara privește prințul și casa lui Israel. Conducătorul își va purta bagajul, va ieși prin zid și va fi prins în plasa lui Dumnezeu și dus la Babilon fără să îl vadă, referire la orbirea lui Zedechia. O mică rămășiță este păstrată ca să povestească între neamuri urâciunile care au dus la risipire." },
    { from: 17, to: 20, heading: "Mâncarea tremurândă și apa băută cu teamă descriu anxietatea din timpul devastării", teaching: "Profetul trebuie să mănânce pâinea cu cutremur și să bea apa cu neliniște. Semnul privește locuitorii Ierusalimului care își consumă hrana în teamă în timp ce țara este golită din cauza violenței. Cetățile locuite devin ruine și țara pustie." },
    { from: 21, to: 28, heading: "Proverbul «zilele trec și orice vedenie rămâne neîmplinită» este declarat încheiat", teaching: "Israel dezvoltase un proverb prin care amânarea devenise argument că profețiile nu se vor împlini. Dumnezeu spune că acest proverb încetează: cuvintele Lui se vor împlini fără altă amânare. Oamenii încearcă apoi o variantă mai subtilă — Ezechiel profețește pentru vremuri foarte îndepărtate — dar răspunsul este din nou că niciun cuvânt nu mai este amânat." },
  ]),
  13: c(13, [
    { from: 1, to: 9, heading: "Profeții care urmează propriul duh văd nimic și totuși spun «DOMNUL zice»", teaching: "Ezechiel este trimis împotriva profeților care profețesc din propria inimă și sunt comparați cu vulpile printre ruine. Ei nu au reparat spărturile și nu au stat în breșă pentru popor, dar declară vedenii false și divinații mincinoase. Dumnezeu întreabă de ce spun «DOMNUL a zis» când El nu i-a trimis și îi exclude din registrul comunității restaurate." },
    { from: 10, to: 16, heading: "Zidul fragil acoperit cu tencuială albă se prăbușește în furtună", teaching: "Profeții induc poporul în eroare spunând «pace» când nu este pace. Poporul construiește un zid slab, iar ei îl acoperă cu tencuială ca să pară solid. Dumnezeu trimite ploaie, grindină și vânt care îl dărâmă, expunând lipsa temeliei. Mesajul religios care cosmetizează o structură nesigură nu o face mai rezistentă." },
    { from: 17, to: 23, heading: "Femeile care folosesc practici magice pentru a controla vieți sunt confruntate și victimele sunt eliberate", teaching: "Ezechiel profețește împotriva femeilor care coasă benzi și fac văluri pentru practici magice prin care pretind putere asupra oamenilor. Ele profanează Numele lui Dumnezeu pentru câștig și întristează pe cel drept cu minciuna, în timp ce întăresc mâna celui rău. Dumnezeu spune că rupe obiectele lor și eliberează oamenii prinși ca păsările." },
  ]),
  14: c(14, [
    { from: 1, to: 8, heading: "Bătrânii vin la profet cu idoli instalați în inimă, iar Dumnezeu confruntă întrebarea înainte să ofere răspuns", teaching: "Unii bătrâni ai lui Israel stau înaintea lui Ezechiel, dar Dumnezeu spune că și-au ridicat idolii în inimă și au pus înaintea lor piatra care îi face să cadă. Problema nu este doar cultul vizibil, ci loialitatea interioară. Profetul este chemat să spună fiecăruia să se întoarcă și să îndepărteze urâciunile; altfel Dumnezeu Însuși îi răspunde potrivit idolatriei lui." },
    { from: 9, to: 11, heading: "Profetul care se lasă atras să dea un răspuns fals nu scapă de responsabilitate", teaching: "Dacă un profet este amăgit și rostește un mesaj care nu vine de la Dumnezeu, el poartă vina împreună cu cel care îl consultă. Scopul judecății este ca Israel să nu mai rătăcească și să nu se mai întineze, ci să revină la formula legământului: ei sunt poporul Lui și El este Dumnezeul lor." },
    { from: 12, to: 20, heading: "Noe, Daniel și Iov ar salva prin dreptatea lor doar propria viață într-o țară ajunsă la judecată", teaching: "Patru scenarii sunt prezentate: foamete, fiare, sabie și ciumă. Chiar dacă Noe, Daniel și Iov ar fi în țară, dreptatea lor nu ar salva fiii și fiicele comunității, ci doar propriile lor vieți. Textul respinge ideea că prestigiul câtorva oameni drepți poate funcționa ca talisman când o societate persistă în rău." },
    { from: 21, to: 23, heading: "O rămășiță care supraviețuiește Ierusalimului îi va face pe exilați să înțeleagă judecata", teaching: "Dumnezeu spune că, deși trimite cele patru judecăți severe asupra Ierusalimului, unii fii și fiice vor fi scoși și vor ajunge la exilați. Când aceștia le vor vedea căile și faptele, vor primi o formă de mângâiere prin înțelegerea faptului că dezastrul nu a venit fără cauză." },
  ]),
  15: c(15, [
    { from: 1, to: 5, heading: "Lemnul viței nu este valoros pentru construcție dacă nu produce rod", teaching: "Dumnezeu întreabă ce avantaj are lemnul viței față de lemnul altor copaci. Nu este folosit pentru obiecte trainice și nici măcar pentru un cui de care să atârni un vas. Valoarea imaginii viei stă în rodul ei; dacă lemnul este ars la ambele capete, devine cu atât mai inutil." },
    { from: 6, to: 8, heading: "Ierusalimul este comparat cu lemnul de viță dat focului pentru necredincioșie", teaching: "Așa cum lemnul viței este dat focului, locuitorii Ierusalimului sunt puși sub judecată. Chiar dacă scapă dintr-un foc, un alt foc îi consumă. Scopul repetat este ca ei să cunoască pe DOMNUL când țara devine pustie din cauza necredincioșiei." },
  ]),
  16: c(16, [
    { from: 1, to: 14, heading: "Ierusalimul este descris ca un copil abandonat pe care Dumnezeu îl salvează, îl crește și îl împodobește", teaching: "Alegoria începe brutal: copilul nou-născut nu este îngrijit, spălat sau înfășat, ci aruncat pe câmp. Dumnezeu trece pe lângă el și spune «trăiește», apoi îl face să crească. Mai târziu intră într-un legământ cu cetatea, o spală, o îmbracă și o împodobește până când frumusețea ei devine cunoscută. Originea și darurile Sionului sunt astfel atribuite harului primit, nu meritului propriu." },
    { from: 15, to: 34, heading: "Frumusețea și darurile primite sunt folosite în idolatrie, descrisă prin metafora infidelității sexuale", teaching: "Cetatea se încrede în frumusețea ei și folosește hainele, bijuteriile, uleiul, tămâia și hrana primite pentru altare și idoli. Alegoria folosește limbaj sexual foarte explicit despre prostituție și amanți pentru a descrie încălcarea legământului și alianțele idolatre. Metafora nu justifică disprețul față de femeile exploatate sexual și nu trebuie transformată într-o etichetă pentru victime; subiectul este infidelitatea spiritual-politică a cetății personificate." },
    { from: 35, to: 43, heading: "Amanții alegoriei devin instrumente ale rușinii și violenței împotriva cetății", teaching: "Dumnezeu anunță că adună popoarele cu care Ierusalimul făcuse alianțe și le lasă să dezbrace, să jefuiască și să distrugă cetatea. Limbajul include expunere publică și violență sexualizată, caracteristice rușinării războiului antic. Textul descrie judecata în metafora unei soții infidele; nu oferă niciodată agresorilor moderni justificare pentru abuz sau pedepsirea sexuală a unei persoane." },
    { from: 44, to: 52, heading: "Samaria și Sodoma sunt numite surori pentru a expune gravitatea comportamentului Ierusalimului", teaching: "Proverbul «cum este mama, așa și fiica» introduce comparația cu Samaria și Sodoma. Păcatele Sodomei sunt enumerate aici prin mândrie, belșug, nepăsare și refuzul de a întări mâna săracului și nevoiașului, alături de urâciuni. Ierusalimul ajunge descris ca mai corupt și îi face pe celelalte cetăți să pară drepte prin comparație." },
    { from: 53, to: 63, heading: "După rușine, Dumnezeu spune că Își va aminti legământul și va întemeia un legământ veșnic", teaching: "Textul vorbește surprinzător despre restaurarea sorții Sodomei și Samariei împreună cu cea a Ierusalimului. Cetatea trebuie să-și poarte rușinea și să nu mai aibă motiv de mândrie. Dumnezeu Își amintește legământul din tinerețe și promite un legământ veșnic, astfel încât poporul să-și amintească, să se rușineze și să nu mai deschidă gura în autojustificare când Dumnezeu face ispășire pentru tot ce a făcut." },
  ]),
}
