import type { ExplainedOverlayChapter } from "../explainedOverlay.js"
import { VT_MAJOR_PROPHETS_FULL } from "../vtFullNarrativesMajorProphets.js"
import { sectionedTextualChapter } from "./textualChapterFactory.js"

const data = VT_MAJOR_PROPHETS_FULL.ezechiel
const c = (number: number, sections: Parameters<typeof sectionedTextualChapter>[3]) =>
  sectionedTextualChapter("Ezechiel", data, number, sections)

export const EZECHIEL_DEEPENED_17_32: Readonly<Record<number, ExplainedOverlayChapter>> = {
  17: c(17, [
    { from: 1, to: 10, heading: "Vulturul, cedrul și vița reprezintă o istorie politică spusă ca parabolă", teaching: "Un vultur mare ia vârful cedrului și îl duce într-o țară de negustori, apoi plantează sămânță care devine viță joasă orientată spre el. Un al doilea vultur apare, iar vița își întinde rădăcinile și ramurile spre el. Întrebarea este dacă va prospera după această schimbare de loialitate sau dacă va fi smulsă și uscată." },
    { from: 11, to: 21, heading: "Parabola este explicată prin deportarea regelui și încălcarea jurământului făcut Babilonului", teaching: "Primul vultur este regele Babilonului, care ia regele și conducătorii Ierusalimului și pune un alt descendent regal sub legământ. Acesta se răzvrătește și trimite soli în Egipt după cai și armată. Dumnezeu spune că fuga spre faraon nu îl va salva, deoarece a disprețuit jurământul și legământul. Zedechia este prins în plasa divină și dus la Babilon." },
    { from: 22, to: 24, heading: "Dumnezeu Însuși plantează o mlădiță fragedă care devine cedru înalt pentru toate păsările", teaching: "După eșecul politic al viței, Dumnezeu spune că ia din vârful cedrului o mlădiță fragedă și o plantează pe muntele înalt al lui Israel. Ea devine cedru măreț în care păsările locuiesc. Toți copacii cunosc astfel că DOMNUL coboară copacul înalt și îl înalță pe cel smerit, usucă pe cel verde și face să înflorească pe cel uscat." },
  ]),
  18: c(18, [
    { from: 1, to: 4, heading: "Proverbul despre părinții care mănâncă aguridă este oprit: fiecare viață aparține lui Dumnezeu", teaching: "Israel repetă că părinții au mâncat aguridă și dinții copiilor s-au strepezit, sugerând că generația actuală nu poate face nimic fiindcă poartă vina altora. Dumnezeu spune că proverbul nu va mai fi folosit astfel. Toate sufletele Îi aparțin, al tatălui și al fiului, iar persoana care păcătuiește este cea care răspunde pentru păcat." },
    { from: 5, to: 18, heading: "Un tată drept, un fiu violent și un nepot drept sunt evaluați după propriile căi", teaching: "Capitolul construiește trei generații. Omul drept evită idolatria, adulterul, asuprirea și jaful și practică restituirea, generozitatea și judecata dreaptă. Fiul lui violent face opusul și moare pentru propria vină. Dacă acel fiu are la rândul lui un copil care vede răul tatălui și nu îl repetă, acesta nu moare pentru nelegiuirea părintelui." },
    { from: 19, to: 24, heading: "Fiul nu poartă vina tatălui, iar trecutul omului nu anulează posibilitatea reală de schimbare", teaching: "Dreptatea celui drept este asupra lui, iar răutatea celui rău asupra lui. Dacă cel rău se întoarce de la păcate, păzește hotărârile și face dreptate, va trăi și fărădelegile nu îi sunt ținute împotrivă. Dumnezeu întreabă dacă are vreo plăcere în moartea celui rău. În sens invers, cel drept care abandonează dreptatea și practică răul nu se poate baza pe trecut ca permis pentru prezent." },
    { from: 25, to: 32, heading: "Acuzația că drumul lui Dumnezeu nu este drept este întoarsă spre căile poporului", teaching: "Israel spune că drumul Domnului nu este echitabil, iar Dumnezeu îi cheamă să compare principiul: omul care se întoarce de la dreptate moare pentru răul său, iar cel care se întoarce de la rău trăiește. Chemarea finală este la pocăință, la aruncarea fărădelegilor și la dobândirea unei inimi și a unui duh noi. Dumnezeu repetă că nu găsește plăcere în moarte, de aceea spune: întoarceți-vă și trăiți." },
  ]),
  19: c(19, [
    { from: 1, to: 9, heading: "Leoaica și puii ei devin lamentație pentru conducătorii lui Israel capturați de națiuni", teaching: "Prinții lui Israel sunt descriși ca pui de leu crescuți de o leoaică. Primul învață să sfâșie prada și este prins într-o groapă și dus cu cârlige în Egipt. Al doilea devine și el leu violent, distruge cetăți și este prins de națiuni și dus în cușcă la regele Babilonului. Puterea regală care devorează nu produce libertate durabilă." },
    { from: 10, to: 14, heading: "Vița roditoare este smulsă, uscată și ajunge fără sceptru pentru conducere", teaching: "Mama este apoi comparată cu o viță plantată lângă apă, plină de ramuri puternice potrivite pentru sceptre. În mânie, vița este smulsă și aruncată la pământ, vântul de răsărit îi usucă rodul și focul îi consumă ramurile. Replantată în pustiu, nu mai are ramură puternică pentru sceptru. Textul se autodefinește ca lamentație." },
  ]),
  20: c(20, [
    { from: 1, to: 12, heading: "Bătrânii vin să-L consulte pe Dumnezeu, iar răspunsul începe cu rebeliunea Israelului încă din Egipt", teaching: "În anul al șaptelea, bătrânii se așază înaintea lui Ezechiel, dar Dumnezeu spune că nu Se va lăsa consultat fără confruntarea istoriei lor. În Egipt, El S-a revelat, a jurat să-i scoată într-o țară bună și le-a cerut să arunce idolii. Ei s-au răzvrătit, dar Dumnezeu a acționat pentru Numele Său și i-a scos. În pustiu le-a dat hotărâri și Sabate ca semn între El și ei." },
    { from: 13, to: 26, heading: "Generațiile din pustiu repetă refuzul, iar Dumnezeu își limitează mânia pentru Numele Său", teaching: "Israel se răzvrătește în pustiu și profanează Sabatele, iar Dumnezeu anunță că generația nu va intra în țara promisă. Copiii sunt avertizați să nu repete idolatria părinților, dar și ei se răzvrătesc. Judecata și îndurarea alternează, iar afirmația dificilă că i-a lăsat în hotărâri care nu erau bune descrie consecința predării lor unei practici corupte, inclusiv trecerea întâilor născuți prin foc, nu faptul că Dumnezeu ar fi poruncit moral sacrificiul copiilor." },
    { from: 27, to: 32, heading: "Ajunși în țară, oamenii mută idolatria pe fiecare deal și continuă practicile care îi întinau", teaching: "Părinții L-au insultat din nou când au intrat în țară: au văzut orice deal înalt și copac des și au adus acolo jertfe și tămâie. Dumnezeu întreabă de ce locul înalt continuă până în ziua profetului. Bătrânii care vor să consulte pe DOMNUL în timp ce își oferă copiii idolilor primesc din nou răspunsul că El nu va valida o asemenea dublă loialitate." },
    { from: 33, to: 44, heading: "Dumnezeu promite să scoată poporul dintre neamuri și să-l treacă din nou sub toiagul legământului", teaching: "Cu mână puternică, Dumnezeu spune că va împărăți peste popor, îl va aduna dintre țări și îl va aduce în «pustiul popoarelor» pentru judecată față în față. Rebelii sunt separați, iar cei primiți slujesc pe muntele sfânt. Acolo Israel își va aminti căile și se va rușina, cunoscând pe Dumnezeu prin modul în care El lucrează pentru Numele Său, nu după răutatea lor." },
    { from: 45, to: 49, heading: "O parabolă a focului în pădurea de sud este atât de figurativă încât oamenii spun că profetul vorbește numai în pilde", teaching: "Ezechiel își îndreaptă fața spre sud și anunță un foc care va consuma copacul verde și uscat, imposibil de stins. Toate fețele vor fi arse de la sud la nord. Profetul răspunde că oamenii îl acuză tocmai de vorbire în pilde, pregătind explicația mai directă a sabiei în capitolul următor." },
  ]),
  21: c(21, [
    { from: 1, to: 7, heading: "Focul din parabola precedentă este explicat ca sabia scoasă împotriva Ierusalimului", teaching: "Ezechiel trebuie să-și îndrepte fața spre Ierusalim, sanctuare și țara lui Israel. Sabia scoasă din teacă lovește pe cel drept și pe cel rău în sensul de calamitate colectivă a războiului, iar profetul geme cu coapsele zdrobite pentru vestea care vine. Nu este o celebrare a indiscriminării morale, ci descrierea felului în care războiul afectează întreaga societate." },
    { from: 8, to: 17, heading: "Sabia este ascuțită și lustruită pentru o judecată pe care poporul nu o poate trata ca pe un joc", teaching: "Poemul repetă imaginea sabiei gata de măcel, pusă în mâna ucigașului. Ezechiel este chemat să strige și să lovească din palme, pentru că arma ajunge la popor și la conducători. Bucuria superficială este exclusă de caracterul sever al momentului." },
    { from: 18, to: 27, heading: "La răscruce, regele Babilonului folosește divinația și drumul ales duce la Ierusalim", teaching: "Profetul desenează două drumuri pentru sabia regelui Babilonului: unul spre Raba amoniților, altul spre Ierusalim. Nebucadnețar scutură săgeți, consultă terafimii și examinează ficatul, iar sorțul îi indică Ierusalimul. Locuitorii îl consideră o divinație falsă, dar Dumnezeu spune că propria lor vină îi aduce în memorie. Prințul nelegiuit își pierde coroana, iar ordinea este răsturnată până la venirea celui căruia îi aparține dreptul." },
    { from: 28, to: 32, heading: "Amonului i se spune că sabia scoasă împotriva lui nu va fi retrasă prin profeții mincinoase", teaching: "Oracolul se întoarce spre Amon, care batjocorise. Vedenii false și divinații mincinoase încearcă să așeze sabia departe, dar ziua finală a fărădelegii a venit. Amonul este judecat în țara de origine și nu mai este amintit ca putere." },
  ]),
  22: c(22, [
    { from: 1, to: 12, heading: "Cetatea sângelui este judecată printr-un catalog de abuzuri sociale, familiale și religioase", teaching: "Ezechiel enumeră idolatria și sângele vărsat, apoi lipsa de respect pentru părinți, asuprirea străinului, nedreptatea față de orfan și văduvă, profanarea lucrurilor sfinte și Sabatelor, calomnia care ucide, sexualitatea abuzivă, mita și extorcarea. Ultima problemă leagă toate acestea: «M-ai uitat», spune DOMNUL." },
    { from: 13, to: 22, heading: "Dumnezeu bate din palme pentru câștigul nedrept și adună casa lui Israel ca zgură într-un cuptor", teaching: "Câștigul și sângele provoacă reacția divină, iar poporul este întrebat dacă inima și mâinile vor rămâne puternice în ziua judecății. Răspândirea între națiuni are scopul de a curăța întinarea. Israel este comparat cu zgură de argint — aramă, cositor, fier și plumb — adunată în cuptor pentru topire." },
    { from: 23, to: 31, heading: "Profeți, preoți, prinți și popor contribuie fiecare la lipsa dreptății, iar nimeni nu stă în spărtură", teaching: "Profeții conspiră ca lei care devorează, preoții confundă sfântul cu profanul și ascund Sabatele, prinții varsă sânge pentru câștig, iar profeții acoperă răul cu vedenii false. Poporul practică extorcarea și asuprește săracul și străinul. Dumnezeu caută un om care să zidească zidul și să stea în spărtură pentru țară, dar spune că nu găsește." },
  ]),
  23: c(23, [
    { from: 1, to: 10, heading: "Ohola, imaginea Samariei, caută alianțe și idoli ai Asiriei până când aceiași aliați o distrug", teaching: "Două surori, Ohola și Oholiba, reprezintă Samaria și Ierusalimul într-o alegorie conjugală. Ohola este descrisă prin dorința după războinicii asirieni și prin idolatrie, iar în final este dată în mâna amanților ei, care o dezbracă și o omoară. Limbajul este sexual și violent pentru a reprezenta infidelitatea politică și religioasă a cetății; nu justifică abuzul sexual sau violența împotriva femeilor reale." },
    { from: 11, to: 21, heading: "Oholiba, Ierusalimul, vede soarta surorii și totuși își extinde alianțele spre Asiria și Babilon", teaching: "Ierusalimul este descris ca și mai corupt, atras de ofițerii asirieni și apoi de imaginile caldeenilor. Trimite soli spre Babilon și intră în alianță, apoi se dezgustă de cei pe care îi căutase. Memoria Egiptului și a relațiilor vechi reapare în limbajul explicit al alegoriei, arătând persistența tiparului de dependență idolatră." },
    { from: 22, to: 35, heading: "Aliații Babilonului devin instrumentele rușinii și judecății Ierusalimului", teaching: "Babilonieni, caldeeni și alte grupuri vin cu arme și care, iar cetatea este dată judecății lor. Textul folosește imagini de mutilare, dezbrăcare și expunere care aparțin metaforei unei soții infidele pedepsite. Aceste imagini trebuie citite ca limbaj profetic despre căderea cetății, nu ca model etic pentru tratarea unui partener necredincios sau a vreunei persoane." },
    { from: 36, to: 49, heading: "Alegoria este explicată prin adulter spiritual, sânge, sacrificarea copiilor și profanarea sanctuarului", teaching: "Dumnezeu îi cere profetului să judece surorile și enumeră faptele: idolatrie, sânge, trecerea copiilor prin foc și intrarea în sanctuar în aceeași zi. Mesageri cheamă bărbați de departe la ospețe împodobite, iar cetățile continuă infidelitatea. Adunarea care le judecă pune capăt desfrâului metaforic, iar scopul declarat este ca femeile-cetăți să poarte consecința idolatriei și să cunoască pe DOMNUL." },
  ]),
  24: c(24, [
    { from: 1, to: 5, heading: "În ziua în care începe asediul Ierusalimului, cazanul pus pe foc devine semnul cetății", teaching: "Data este fixată exact, iar Dumnezeu spune că regele Babilonului a început asediul în acea zi. Ezechiel pune cazanul, toarnă apă, adună bucăți bune de carne și oase și le fierbe. Cetatea care se considera recipient protector devine vasul în care judecata se concentrează." },
    { from: 6, to: 14, heading: "Rugina cazanului și sângele lăsat pe stâncă arată o vină care nu a fost curățată", teaching: "Cazanul are rugină groasă care nu iese bucată cu bucată, iar sângele cetății fusese vărsat pe stâncă, fără să fie acoperit cu pământ. Dumnezeu mărește focul până când carnea și oasele sunt consumate și vasul gol este încins pentru a topi murdăria. Eforturile anterioare de curățire nu au schimbat refuzul persistent." },
    { from: 15, to: 24, heading: "Moartea soției lui Ezechiel devine un semn profetic dureros al pierderii sanctuarului", teaching: "Dumnezeu îi spune că îi va lua «desfătarea ochilor» printr-o lovitură, iar profetul nu trebuie să practice ritualurile publice obișnuite de doliu. Soția lui moare seara, iar dimineața el face ce i s-a poruncit. Când oamenii întreabă sensul, Ezechiel explică faptul că sanctuarul, desfătarea ochilor lor, va fi profanat și familiile lor vor suferi. Chemarea specifică a profetului nu este o regulă că oamenii credincioși trebuie să își reprime doliul personal." },
    { from: 25, to: 27, heading: "Când fugarul aduce vestea căderii cetății, tăcerea profetului se încheie", teaching: "În ziua în care sanctuarul și copiii poporului sunt luați, un fugar ajunge la Ezechiel cu vestea. Atunci gura profetului se deschide și el nu mai este mut. Evenimentul însuși confirmă semnul, iar oamenii cunosc că DOMNUL a vorbit." },
  ]),
  25: c(25, [
    { from: 1, to: 7, heading: "Amon este judecat pentru bucuria batjocoritoare față de profanarea sanctuarului și exil", teaching: "Amon spune «aha» când sanctuarul este profanat, țara lui Israel devastată și casa lui Iuda dusă în captivitate. Dumnezeu îl dă fiilor răsăritului, care își așază taberele și consumă roadele. Raba devine pășune pentru că Amon a bătut din palme și s-a bucurat cu dispreț de nenorocirea altuia." },
    { from: 8, to: 11, heading: "Moab este confruntat pentru reducerea lui Iuda la nivelul oricărei alte națiuni", teaching: "Moabul și Seirul spun că Iuda este asemenea tuturor neamurilor, ignorând relația de legământ și lucrarea lui Dumnezeu. Cetățile de frontieră sunt deschise atacului, iar Moabul este dat fiilor răsăritului împreună cu Amon. Scopul este cunoașterea lui Dumnezeu prin judecată." },
    { from: 12, to: 14, heading: "Edomul care s-a răzbunat pe Iuda primește răsplătirea faptelor sale", teaching: "Edomul este acuzat că a acționat prin răzbunare și s-a făcut foarte vinovat. Țara este întinsă sub judecată de la Teman la Dedan. Dumnezeu spune că Își pune răzbunarea în mâna poporului Său în cadrul acestei profeții istorice; textul nu autorizează indivizii moderni să revendice violența ca răzbunare divină privată." },
    { from: 15, to: 17, heading: "Filistenii sunt judecați pentru o răzbunare veche purtată cu dispreț", teaching: "Filistenii sunt acuzați că au lucrat din răzbunare și ostilitate veche pentru a distruge. Dumnezeu spune că Își întinde mâna împotriva cheretiților și restului coastei și face judecăți mari asupra lor. Repetiția între Amon, Moab, Edom și Filistia arată că modul în care popoarele răspund la căderea aproapelui intră și el sub evaluare." },
  ]),
  26: c(26, [
    { from: 1, to: 6, heading: "Tirul se bucură că «poarta popoarelor» Ierusalimului este ruptă și speră să preia comerțul", teaching: "Tirul vede căderea Ierusalimului ca oportunitate economică: dacă poarta comercială este distrusă, prosperitatea ei poate trece spre cetatea feniciană. Dumnezeu răspunde că aduce multe națiuni ca valurile mării, zidurile sunt dărâmate, iar Tirul devine stâncă goală pentru întins plasele de pescuit." },
    { from: 7, to: 14, heading: "Nebucadnețar și armata lui sunt descriși metodic dărâmând fortificațiile cetății", teaching: "Regele Babilonului vine din nord cu cai, care și mulți oameni, ridică terasamente și folosește berbeci împotriva zidurilor. Praful cailor acoperă cetatea, iar zgomotul intrării seamănă cu cel al unei cetăți cucerite. Pietrele, lemnul și țărâna sunt aruncate în apă, muzica încetează și locul rămâne stâncă goală." },
    { from: 15, to: 21, heading: "Prinții mării coboară de pe tron și cântă o lamentație pentru cetatea care înspăimânta coastele", teaching: "Insulele se cutremură de zgomotul căderii, iar conducătorii maritimi își lasă hainele brodate și stau tremurând pe pământ. Ei întreabă cum a pierit cetatea locuită de oameni ai mării. Dumnezeu spune că Tirul este coborât simbolic în adânc împreună cu cei din vechime și nu mai revine la splendoarea de altădată." },
  ]),
  27: c(27, [
    { from: 1, to: 11, heading: "Tirul este descris ca o corabie perfect echipată de popoare diferite", teaching: "Lamentația începe cu afirmația Tirului că este desăvârșit în frumusețe. Scândurile vin din Senir, catargul din Liban, vâslele din Basan, puntea din fildeș și pânzele din Egipt. Sidonul și Arvadul dau vâslași, iar meșteșugarii și soldații multor popoare completează vasul. Puterea comercială depinde de o vastă rețea internațională." },
    { from: 12, to: 25, heading: "Catalogul partenerilor comerciali arată amploarea economiei Tirului", teaching: "Tarsis aduce argint, fier, cositor și plumb; Iavan, Tubal și Meșec schimbă oameni și bronz; alte regiuni aduc cai, fildeș, abanos, textile, grâu, miere, ulei, balsam, vin, lână, mirodenii și animale. Lista nu celebrează moral fiecare marfă — inclusiv comerțul cu oameni este menționat ca realitate a economiei antice — ci arată cât de multe sisteme depindeau de port." },
    { from: 26, to: 36, heading: "Vântul de răsărit sparge corabia încărcată, iar întregul sistem comercial plânge", teaching: "Vâslașii duc vasul în ape mari, dar vântul de răsărit îl sfărâmă. Bogățiile, mărfurile, marinarii, soldații și echipajul cad în mare în ziua ruinării. Oamenii de pe țărm strigă, își pun țărână pe cap și întreabă cine a fost ca Tirul. Negustorii sunt îngroziți, iar cetatea bogată ajunge motiv de spaimă și dispare ca putere." },
  ]),
  28: c(28, [
    { from: 1, to: 10, heading: "Prințul Tirului spune «sunt dumnezeu», iar succesul și bogăția îi umflă inima", teaching: "Conducătorul își așază inima ca inima unui dumnezeu și pretinde un loc divin în mijlocul mărilor. Textul admite că este înțelept și că prin pricepere a acumulat aur și argint, dar tocmai succesul a produs mândrie. Dumnezeu îi amintește că este om, nu Dumnezeu, și îl dă în mâna unor străini care îi arată limita mortală." },
    { from: 11, to: 19, heading: "Lamentația regelui Tirului folosește imagini de Eden, heruvim și muntele lui Dumnezeu pentru o cădere din splendoare", teaching: "Regele este descris poetic ca pecete a desăvârșirii, plin de înțelepciune și frumusețe, în Eden și acoperit cu pietre prețioase. Un heruvim ocrotitor și muntele lui Dumnezeu fac imaginea mai înaltă decât biografia obișnuită a unui rege. Textul imediat rămâne o lamentație pentru regele Tirului și mândria produsă de comerț și violență; tradițiile care văd aici și o analogie cu o cădere satanică nu trebuie să șteargă referentul istoric." },
    { from: 20, to: 24, heading: "Sidonul primește un oracol separat de judecată", teaching: "Ezechiel își îndreaptă fața spre Sidon și spune că Dumnezeu Își arată gloria prin judecăți și sfințenie. Ciuma și sabia sunt imagini ale loviturii, iar vecinii care disprețuiseră pe Israel nu mai sunt ca un spin dureros în coasta lui." },
    { from: 25, to: 26, heading: "Oracolele împotriva vecinilor se încheie cu promisiunea adunării și siguranței lui Israel", teaching: "Dumnezeu spune că îi adună pe cei din casa lui Israel dintre popoarele unde au fost împrăștiați și Își arată sfințenia prin ei. Ei locuiesc în țara dată lui Iacov, construiesc case și plantează vii în siguranță, în timp ce judecata vecinilor ostili îi face să cunoască pe DOMNUL." },
  ]),
  29: c(29, [
    { from: 1, to: 7, heading: "Faraonul este comparat cu un crocodil uriaș care pretinde că Nilul îi aparține", teaching: "Regele Egiptului stă în mijlocul râurilor și spune că Nilul este al lui și el l-a făcut. Dumnezeu îi pune cârlige în fălci și îl scoate împreună cu peștii râului, lăsându-l în pustiu. Motivul judecății este și faptul că Egiptul a fost pentru Israel un toiag de trestie: când s-au sprijinit pe el, s-a rupt și i-a rănit." },
    { from: 8, to: 16, heading: "Egiptul este pustiit pentru patruzeci de ani și apoi restaurat ca regat modest, nu ca obiect al încrederii lui Israel", teaching: "Sabia vine asupra oamenilor și animalelor, iar țara de la Migdol la Asuan devine pustie. După patruzeci de ani, egiptenii sunt adunați din nou și întorși în Patros, dar regatul rămâne mai smerit decât celelalte și nu mai domină națiunile. Pentru Israel, aceasta înseamnă că Egiptul nu mai trebuie să fie amintirea păcătoasă a unei alianțe în care își puneau încrederea." },
    { from: 17, to: 21, heading: "Nebucadnețar primește Egiptul ca plată după o campanie grea împotriva Tirului", teaching: "Armata Babilonului muncise atât de greu împotriva Tirului încât capetele se pleșuviseră și umerii se juliseră, dar prada nu acoperise efortul. Dumnezeu spune că Egiptul va deveni plata armatei pentru munca făcută în slujba judecății. În aceeași perioadă, un corn începe să crească pentru casa lui Israel și gura lui Ezechiel este deschisă între exilați." },
  ]),
  30: c(30, [
    { from: 1, to: 9, heading: "Ziua DOMNULUI asupra Egiptului se extinde la aliații și vecinii lui", teaching: "Profetul cere plâns pentru o zi apropiată, zi de nori și vreme a națiunilor. Sabia vine peste Egipt, Cuș tremură, iar bogăția și temeliile politice ale țării sunt dărâmate. Cuș, Put, Lud și alte popoare aliate cad împreună. Mesagerii pleacă pe corăbii să înspăimânte Cușul liniștit când nenorocirea Egiptului ajunge." },
    { from: 10, to: 19, heading: "Nebucadnețar este instrumentul prin care orașele, idolii și economia Nilului sunt lovite", teaching: "Dumnezeu spune că pune capăt mulțimii Egiptului prin regele Babilonului și armata lui. Râurile sunt secate, țara vândută în mâna răului, idolii distruși și cetățile de la Nof la Sin și Teba lovite. Fiecare nume geografic transformă judecata într-o hartă a colapsului național." },
    { from: 20, to: 26, heading: "Brațul faraonului este frânt de două ori, iar sabia este pusă în mâna regelui Babilonului", teaching: "Dumnezeu spune că a frânt deja un braț al faraonului fără ca acesta să fie bandajat pentru vindecare. Apoi ambele brațe sunt frânte, iar sabia cade din mână. Egiptenii sunt împrăștiați între națiuni, în timp ce brațele regelui Babilonului sunt întărite. Imaginea arată transferul puterii geopolitice sub suveranitatea lui Dumnezeu." },
  ]),
  31: c(31, [
    { from: 1, to: 9, heading: "Faraonul este invitat să se compare cu cedrul Asiriei, înalt și splendid prin abundența apelor", teaching: "Asiria este descrisă ca un cedru din Liban cu ramuri frumoase și vârful în nori. Apele adâncului îl hrănesc, păsările cuibăresc în ramuri, animalele nasc sub umbră și națiunile locuiesc la adăpost. Nici copacii din grădina lui Dumnezeu nu îl întrec în frumusețe, iar Dumnezeu spune că El îl făcuse frumos." },
    { from: 10, to: 14, heading: "Înălțimea inimii transformă privilegiul în motivul căderii", teaching: "Pentru că cedrul s-a înălțat până la nori și inima lui s-a mândrit, Dumnezeu îl dă în mâna conducătorului națiunilor. Străinii cei mai cruzi îl taie, iar popoarele îi părăsesc umbra. Păsările și fiarele se așază acum pe trunchiul căzut, iar lecția este ca niciun copac bine udat să nu se mai înalțe în mândrie." },
    { from: 15, to: 18, heading: "Coborârea Asiriei în locuința morților devine avertisment direct pentru faraon", teaching: "Ziua coborârii în Șeol este descrisă prin doliu cosmic: adâncul este acoperit, râurile oprite și Libanul întunecat. Națiunile tremură la zgomotul căderii, iar copacii Edenului primesc o formă de consolare în adânc. Întrebarea finală îi spune faraonului că, oricât de mare s-ar considera, va fi culcat împreună cu cei netăiați împrejur și uciși de sabie." },
  ]),
  32: c(32, [
    { from: 1, to: 10, heading: "Faraonul, leul și monstrul apelor, este prins în plasa națiunilor", teaching: "Lamentația îl compară pe faraon cu un leu între națiuni și cu un monstru care tulbură apele cu picioarele. Dumnezeu întinde peste el o plasă prin multe popoare, îl scoate și îl lasă pe câmp. Păsările și fiarele se satură, iar căderea lui este descrisă prin întunecarea luminătorilor și uimirea regilor care tremură pentru propria viață." },
    { from: 11, to: 16, heading: "Sabia Babilonului goleşte țara, iar apele Egiptului devin liniștite după dispariția mulțimii", teaching: "Regele Babilonului vine cu săbiile celor mai cruzi dintre națiuni și distruge mândria Egiptului. Oamenii și animalele dispar de lângă ape, astfel încât nici picior omenesc, nici copită nu le mai tulbură. Dumnezeu spune că face apele limpezi și râurile să curgă ca uleiul când țara este pustiită." },
    { from: 17, to: 21, heading: "O a doua lamentație coboară mulțimea Egiptului în groapă între cei uciși de sabie", teaching: "Ezechiel trebuie să plângă și să trimită simbolic Egiptul în adâncuri alături de fiicele națiunilor puternice. Întrebarea «pe cine întreci în frumusețe?» primește răspunsul morții comune. Cei puternici vorbesc din Șeol despre faraon și aliații lui culcați între cei uciși." },
    { from: 22, to: 32, heading: "Asiria, Elam, Meșec-Tubal, Edom și alți războinici formează o galerie a puterilor ajunse în mormânt", teaching: "Națiunile sunt enumerate una după alta cu mormintele lor în jur. Cândva răspândeau teroare în țara celor vii, dar acum poartă rușinea în groapă. Faraon îi vede și primește o formă întunecată de consolare că nu este singurul imperiu căzut. Capitolul încheie oracolele egiptene prin imaginea egalizatoare a morții." },
  ]),
}
