import type { ExplainedOverlayChapter } from "../explainedOverlay.js"
import { VT_MAJOR_PROPHETS_FULL } from "../vtFullNarrativesMajorProphets.js"
import { sectionedTextualChapter } from "./textualChapterFactory.js"

const data = VT_MAJOR_PROPHETS_FULL.ieremia
const c = (number: number, sections: Parameters<typeof sectionedTextualChapter>[3]) =>
  sectionedTextualChapter("Ieremia", data, number, sections)

export const IEREMIA_DEEPENED_24_40: Readonly<Partial<Record<number, ExplainedOverlayChapter>>> = {
  24: c(24, [
    { from: 1, to: 3, heading: "Două coșuri cu smochine sunt așezate înaintea templului după deportarea lui Ieconia", teaching: "După ce o parte a elitei și meșteșugarilor a fost dusă la Babilon, Ieremia vede smochine foarte bune și smochine atât de rele încât nu pot fi mâncate. Dumnezeu pornește de la această diferență vizibilă pentru a interpreta două grupuri care, la suprafață, ar fi putut fi judecate invers." },
    { from: 4, to: 7, heading: "Exilații considerați pierduți sunt numiți smochine bune și primesc promisiunea unei inimi care Îl cunoaște pe Dumnezeu", teaching: "Dumnezeu spune că îi privește cu bunătate pe cei trimiși în țara caldeenilor, îi va aduce înapoi, îi va zidi și le va da o inimă ca să-L cunoască. Exilul lor nu înseamnă abandon definitiv. Relația restaurată este descrisă prin formula legământului: ei vor fi poporul Lui și El va fi Dumnezeul lor, pentru că se vor întoarce din toată inima." },
    { from: 8, to: 10, heading: "Cei rămași sub Zedechia și cei refugiați în Egipt sunt comparați cu smochinele rele", teaching: "A rămâne fizic în țară nu este dovadă automată de favor divin. Zedechia, conducătorii și cei care s-au stabilit în Egipt sunt puși sub imaginea smochinelor rele și anunțați ca obiect de groază, batjocură și risipire. Sabia, foametea și ciuma continuă până la îndepărtarea lor din țară." },
  ]),
  25: c(25, [
    { from: 1, to: 7, heading: "Douăzeci și trei de ani de avertismente au fost întâmpinați prin refuz repetat", teaching: "În al patrulea an al lui Ioiachim, Ieremia își rezumă lunga slujire: de la al treisprezecelea an al lui Iosia a vorbit devreme și neîncetat, iar Dumnezeu a trimis și alți profeți. Mesajul repetat era întoarcerea de la calea rea și abandonarea idolilor, dar poporul nu și-a plecat urechea." },
    { from: 8, to: 14, heading: "Nebucadnețar este numit slujitor al judecății, iar cei șaptezeci de ani au o limită stabilită", teaching: "Pentru că poporul nu a ascultat, Dumnezeu cheamă neamurile din nord și pe Nebucadnețar împotriva țării. Vocea bucuriei, mirelui, miresei și pietrelor de moară dispare, iar țara ajunge pustie. Totuși robia are un termen: după șaptezeci de ani, Babilonul însuși este cercetat pentru fărădelege. Instrumentul judecății nu devine astfel moralmente imun." },
    { from: 15, to: 29, heading: "Cupa mâniei trece de la Ierusalim la o listă largă de națiuni", teaching: "Ieremia primește imaginea unei cupe pe care popoarele trebuie să o bea până se clatină. Lista pornește de la Ierusalim și regii lui Iuda, apoi include Egiptul, Uț, filistenii, Edomul, Moabul, Amonul, Tirul, Sidonul, Arabia și multe alte regate. Dacă cetatea care poartă Numele lui Dumnezeu nu este scutită de judecată, neamurile nu pot presupune că vor rămâne nepedepsite." },
    { from: 30, to: 38, heading: "Judecata este descrisă ca vuiet, proces împotriva națiunilor și furtună care ajunge la marginile pământului", teaching: "DOMNUL răcnește din înălțime și intră la judecată cu orice făptură. Cei uciși sunt descriși de la un capăt al pământului la altul, fără funeralii normale, iar păstorii sunt chemați să plângă pentru turma pierdută. Leul care își părăsește desișul și furtuna mâniei închid imaginea unei ordini internaționale zdruncinate." },
  ]),
  26: c(26, [
    { from: 1, to: 6, heading: "Ieremia este trimis în curtea templului să spună tot cuvântul, fără să scadă nimic", teaching: "La începutul domniei lui Ioiachim, profetul trebuie să stea unde vin oamenii din cetățile lui Iuda la închinare și să transmită mesajul complet. Posibilitatea pocăinței rămâne reală: dacă ascultă și se întorc, Dumnezeu Se poate îndura de nenorocirea anunțată. Dacă nu, templul va ajunge ca Șilo și cetatea va deveni blestem între națiuni." },
    { from: 7, to: 15, heading: "Preoții și profeții cer moartea lui Ieremia, iar el răspunde că mesajul vine de la DOMNUL", teaching: "După predică, liderii religioși și poporul îl apucă și spun că trebuie să moară pentru că a profețit împotriva templului și cetății. În fața dregătorilor, Ieremia nu retrage avertismentul: Dumnezeu l-a trimis. Totuși repetă oferta de schimbare a căilor și spune că viața lui este în mâinile lor; dacă îl ucid, vor aduce sânge nevinovat asupra lor și cetății." },
    { from: 16, to: 24, heading: "Un precedent din vremea lui Mica îl protejează pe profet, în timp ce soarta lui Urie arată riscul real al slujirii", teaching: "Dregătorii și o parte din popor concluzionează că Ieremia nu merită moartea. Bătrânii amintesc că Mica profețise că Sionul va fi arat ca un ogor, iar regele Ezechia nu l-a ucis, ci s-a temut de DOMNUL. În contrast, profetul Urie fugise în Egipt, fusese adus înapoi și ucis de Ioiachim. Ahicam îl protejează pe Ieremia, dar capitolul nu ascunde că profeția fidelă putea costa viața." },
  ]),
  27: c(27, [
    { from: 1, to: 7, heading: "Jugurile trimise regilor vecini spun că Dumnezeu a dat temporar țările în mâna Babilonului", teaching: "Ieremia își pune legături și jug și trimite mesajul către Edom, Moab, Amon, Tir și Sidon prin solii veniți la Ierusalim. Creatorul pământului spune că îl dă cui voiește și că, pentru această perioadă, Nebucadnețar primește autoritate. Chiar și fiarele câmpului sunt incluse în limbajul suveranității, iar după timpul stabilit Babilonul va ajunge și el sub alte națiuni." },
    { from: 8, to: 11, heading: "Națiunile sunt avertizate să nu creadă profeții care le promit că pot evita jugul babilonian", teaching: "Profet, ghicitor, visător, vrăjitor și descântător apar în aceeași listă când promit că poporul nu va sluji Babilonului. Ieremia spune că asemenea mesaje îi împing spre expulzare și ruină. Acceptarea jugului în această situație istorică este prezentată drept calea prin care un popor poate rămâne în țara lui." },
    { from: 12, to: 15, heading: "Zedechia primește aceeași chemare: supune-te Babilonului și nu asculta mesajele false despre salvare rapidă", teaching: "Regele lui Iuda este îndemnat direct să-și pună gâtul sub jugul Babilonului. Alternativa este sabia, foametea și ciuma. Ieremia întreabă de ce ar alege regele moartea pe baza unor profeți care spun că nu va sluji Babilonului, când Dumnezeu spune că nu i-a trimis." },
    { from: 16, to: 22, heading: "Profeția că vasele templului se vor întoarce imediat este testată prin rugăciune și realitatea obiectelor rămase", teaching: "Preoții și poporul aud că profeții promit întoarcerea rapidă a vaselor Casei DOMNULUI. Ieremia spune că, dacă sunt profeți adevărați, să mijlocească pentru ca obiectele încă rămase să nu ajungă și ele în Babilon. Dumnezeu anunță însă că acestea vor fi luate și vor rămâne acolo până în ziua în care El le va aduce înapoi." },
  ]),
  28: c(28, [
    { from: 1, to: 4, heading: "Hanania profețește în templu o restaurare completă în doi ani", teaching: "În fața preoților și poporului, Hanania spune că DOMNUL a rupt jugul Babilonului și că în doi ani vor reveni vasele templului, regele Ieconia și toți exilații. Mesajul este precis, optimist și rostit în Numele lui Dumnezeu, ceea ce îl face cu atât mai necesar de testat." },
    { from: 5, to: 9, heading: "Ieremia ar dori ca vestea bună să fie adevărată, dar amintește testul împlinirii pentru profeția de pace", teaching: "Ieremia răspunde «Amin! Așa să facă DOMNUL», arătând că nu iubește dezastrul de dragul dezastrului. Totuși amintește că profeții vechi au vestit război și nenorocire multor țări, iar profetul care anunță pace este recunoscut ca trimis de Dumnezeu atunci când cuvântul lui se împlinește." },
    { from: 10, to: 11, heading: "Hanania rupe jugul de pe gâtul lui Ieremia și transformă disputa într-un semn public", teaching: "Hanania ia jugul și îl rupe înaintea tuturor, spunând că tot astfel Dumnezeu va rupe jugul lui Nebucadnețar în doi ani. Ieremia pleacă. Tăcerea lui imediată nu înseamnă aprobarea semnului; conflictul va fi decis de un nou cuvânt profetic, nu de cine produce gestul public mai spectaculos." },
    { from: 12, to: 17, heading: "Jugul de lemn devine jug de fier, iar moartea lui Hanania confirmă falsitatea mesajului", teaching: "Dumnezeu îi spune lui Ieremia că ruperea jugurilor de lemn nu a eliminat realitatea, ci este urmată de juguri de fier peste națiuni. Profetul îl confruntă pe Hanania: Dumnezeu nu l-a trimis, iar el a făcut poporul să creadă o minciună și a învățat răzvrătire. Ieremia îi anunță moartea în acel an, iar Hanania moare în luna a șaptea." },
  ]),
  30: c(30, [
    { from: 1, to: 3, heading: "Ieremia trebuie să scrie cuvintele restaurării lui Israel și Iuda", teaching: "Mesajul este pus în scris pentru o vreme în care Dumnezeu va întoarce captivitatea poporului și îl va aduce înapoi în țara dată părinților. Restaurarea nu este prezentată ca zvon optimist, ci ca promisiune pe care profetul trebuie să o păstreze textual." },
    { from: 4, to: 11, heading: "Ziua necazului lui Iacov este severă, dar jugul străin este rupt și poporul nu este nimicit", teaching: "Glasurile auzite sunt de tremur și nu de pace, iar bărbații sunt comparați cu femei în durerile nașterii. Ziua este mare și fără asemănare, dar Iacov este salvat din ea. Jugul este rupt, poporul va sluji DOMNULUI și lui David, regele lui, iar exilații sunt chemați să nu se teamă. Dumnezeu disciplinează cu dreptate, dar spune că nu îi va nimici complet." },
    { from: 12, to: 17, heading: "Rana este numită incurabilă, iar aliații care au fost iubiți nu oferă vindecare", teaching: "Dumnezeu descrie rana Sionului ca gravă și fără medicament omenesc. Iubiții politici au uitat cetatea, iar lovitura este legată de mulțimea fărădelegilor. Totuși logica se întoarce: cei care au devorat vor fi devorați, iar Dumnezeu promite să aducă sănătate și vindecare celei numite «alungată, de care nimănui nu-i pasă»." },
    { from: 18, to: 24, heading: "Corturile sunt restaurate, cetatea reconstruită și conducătorul se apropie de Dumnezeu", teaching: "Dumnezeu promite refacerea locuințelor lui Iacov, reconstruirea cetății și revenirea mulțumirii. Poporul se înmulțește și comunitatea este stabilită înaintea Lui. Conducătorul va ieși din mijlocul lor și va fi adus aproape, iar formula legământului reapare: voi veți fi poporul Meu și Eu voi fi Dumnezeul vostru. Ultimele versete reamintesc totuși furtuna mâniei împotriva răului." },
  ]),
  33: c(33, [
    { from: 1, to: 3, heading: "În timp ce Ieremia este încă închis, Dumnezeu îl cheamă să strige și promite răspuns", teaching: "Al doilea cuvânt vine în curtea închisorii, în timp ce situația politică pare fără ieșire. Creatorul și Cel care stabilește lucrurile îi spune profetului să-L cheme și promite să-i arate lucruri mari și ascunse pe care nu le cunoaște. Promisiunea aparține dialogului profetic concret, nu unei formule prin care orice întrebare personală primește revelație secretă." },
    { from: 4, to: 9, heading: "Casele distruse de asediu vor fi urmate de vindecare, curățire și un nume de bucurie între națiuni", teaching: "Casele Ierusalimului sunt dărâmate pentru apărare și umplute cu morți din cauza judecății. Totuși Dumnezeu promite sănătate, vindecare, pace, întoarcerea captivității și reconstruirea ca la început. Fărădelegile sunt curățite, iar cetatea devine pentru Dumnezeu nume de bucurie și laudă înaintea neamurilor care vor auzi binele făcut ei." },
    { from: 10, to: 13, heading: "Locul numit pustiu va auzi din nou glasul mirelui, miresei și păstorilor", teaching: "În cetățile fără oameni și animale va reveni vocea bucuriei și a nunții, alături de mulțumirea adusă în Casa DOMNULUI. În câmpiile și regiunile țării, păstorii își vor număra din nou oile. Restaurarea este descrisă prin viață domestică, cult și economie pastorală normală." },
    { from: 14, to: 18, heading: "Odrasla dreaptă a lui David este legată de dreptate și continuitatea slujirii", teaching: "Zilele vin când Dumnezeu va împlini cuvântul bun pentru Israel și Iuda. O Odraslă dreaptă răsare lui David și face judecată și dreptate, iar Iuda și Ierusalimul locuiesc în siguranță. Promisiunea continuă apoi prin limbajul tronului davidic și al preoților leviți care aduc jertfe." },
    { from: 19, to: 26, heading: "Stabilitatea promisiunii este comparată cu legământul zilei și al nopții", teaching: "Dumnezeu spune că dacă oamenii ar putea rupe ordinea zilei și nopții, abia atunci ar putea fi ruptă promisiunea referitoare la David și la slujirea levitică. Mulțimea urmașilor este comparată cu stelele și nisipul. Disprețul celor care spun că Dumnezeu și-a lepădat cele două familii este confruntat prin fidelitatea legământului și promisiunea de restaurare." },
  ]),
  34: c(34, [
    { from: 1, to: 7, heading: "Zedechia află că Ierusalimul va cădea, dar el nu va muri prin sabie", teaching: "În timp ce armata Babilonului luptă împotriva Ierusalimului și a ultimelor cetăți întărite, Ieremia îi spune regelui că cetatea va fi dată în mâna lui Nebucadnețar și arsă. Zedechia va fi prins și dus la Babilon, însă primește și un cuvânt personal că va muri în pace și va avea parte de ritualul de doliu rezervat regilor." },
    { from: 8, to: 16, heading: "Eliberarea sclavilor este jurată înaintea lui Dumnezeu și apoi anulată când pericolul pare să se retragă", teaching: "Regele și poporul fac un legământ să elibereze robii evrei, potrivit poruncii ca fratele să nu rămână sclav permanent. Ei ascultă inițial și îi lasă liberi, dar apoi se răzgândesc și îi aduc din nou în robie. Dumnezeu interpretează aceasta ca profanare a Numelui Său, pentru că jurământul fusese făcut înaintea Lui." },
    { from: 17, to: 22, heading: "Cei care au refuzat libertatea aproapelui primesc o «libertate» spre sabie, ciumă și foamete", teaching: "Dumnezeu folosește ironia cuvântului libertate: pentru că nu au proclamat eliberarea fraților, El proclamă pentru ei libertate spre formele judecății. Conducătorii care au trecut între bucățile vițelului la încheierea legământului vor suporta consecințele încălcării lui. Armata Babilonului, retrasă temporar, se va întoarce, va cuceri și va arde cetatea." },
  ]),
  35: c(35, [
    { from: 1, to: 11, heading: "Recabiții refuză vinul pentru a păzi porunca strămoșului lor", teaching: "Ieremia îi aduce pe recabiți într-o cameră a templului și le pune înainte cupe de vin. Ei refuză, explicând porunca lui Ionadab: să nu bea vin, să nu construiască case, să nu planteze vii și să locuiască în corturi. Ascultarea lor a continuat de-a lungul generațiilor, iar prezența temporară în Ierusalim este explicată de amenințarea armatelor." },
    { from: 12, to: 17, heading: "Ascultarea recabiților devine contrast pentru Iuda, care nu ascultă glasul repetat al lui Dumnezeu", teaching: "Dumnezeu nu transformă regulile recabite într-o lege pentru toți israeliții. El folosește însă consecvența lor ca martor împotriva lui Iuda: o familie ascultă cuvântul strămoșului ei, dar poporul nu ascultă pe Dumnezeu, deși El vorbește devreme și trimite repetat profeți. De aceea nenorocirea anunțată rămâne." },
    { from: 18, to: 19, heading: "Familia lui Ionadab primește o promisiune pentru fidelitatea ei", teaching: "Ieremia le transmite recabiților că, pentru că au păzit porunca tatălui lor și au făcut ceea ce le-a cerut, nu va lipsi din familia lui Ionadab un om care să stea înaintea lui Dumnezeu. Lauda este pentru ascultarea lor concretă, nu pentru ideea că abstinența de la vin sau viața în corturi ar fi o chemare universală." },
  ]),
  36: c(36, [
    { from: 1, to: 8, heading: "Cuvântul este dictat lui Baruc pentru ca poporul să audă și poate să se întoarcă", teaching: "În al patrulea an al lui Ioiachim, Dumnezeu îi poruncește lui Ieremia să scrie într-un sul toate cuvintele rostite din zilele lui Iosia. Scopul declarat este ca Iuda să audă tot răul anunțat și poate să se întoarcă, astfel încât Dumnezeu să ierte. Pentru că Ieremia este împiedicat să intre în templu, Baruc citește sulul în locul lui." },
    { from: 9, to: 19, heading: "Citirea publică ajunge la dregători, care se tem și decid să informeze regele", teaching: "În timpul unui post, Baruc citește poporului, iar Mica îi transmite dregătorilor mesajul. Ei îl cheamă pe Baruc să citească din nou și, auzind cuvintele, se uită unii la alții cu teamă. Întreabă cum a fost scris sulul, iar Baruc spune că Ieremia a dictat. Dregătorii îi sfătuiesc pe Ieremia și Baruc să se ascundă înainte ca sulul să ajungă la rege." },
    { from: 20, to: 26, heading: "Ioiachim taie și arde sulul bucată cu bucată fără să se teamă", teaching: "Sulul este adus înaintea regelui în casa de iarnă. Pe măsură ce Iehudi citește câteva coloane, Ioiachim le taie cu cuțitul scribului și le aruncă în foc până când întregul sul este ars. Regele și slujitorii lui nu se tem și nu își rup hainele, deși unii dregători îl roagă să nu ardă. El poruncește arestarea lui Baruc și Ieremia, dar Dumnezeu îi ascunde." },
    { from: 27, to: 32, heading: "Arderea manuscrisului nu distruge cuvântul: un al doilea sul este scris și extins", teaching: "După ardere, Dumnezeu îi spune lui Ieremia să ia alt sul și să scrie din nou toate cuvintele. Profetul anunță și judecata lui Ioiachim, care pretinsese că regele Babilonului nu va veni. Baruc rescrie sub dictare conținutul sulului ars și sunt adăugate multe cuvinte asemănătoare. Puterea regelui asupra documentului nu devine putere asupra mesajului." },
  ]),
  37: c(37, [
    { from: 1, to: 10, heading: "Retragerea temporară a Babilonului nu schimbă cuvântul că cetatea va cădea", teaching: "Zedechia domnește în locul lui Ieconia, dar el, slujitorii și poporul nu ascultă cuvintele DOMNULUI. Totuși regele îi cere lui Ieremia rugăciune. Când armata faraonului iese din Egipt, caldeenii se retrag de la Ierusalim. Dumnezeu avertizează însă să nu se lase înșelați: egiptenii se vor întoarce, iar caldeenii vor reveni și vor arde cetatea; chiar o armată aproape distrusă ar putea împlini acest verdict." },
    { from: 11, to: 16, heading: "Ieremia încearcă să meargă în ținutul lui Beniamin și este acuzat fals că dezertează", teaching: "În timpul retragerii caldeenilor, profetul pleacă din Ierusalim pentru o chestiune de proprietate în Beniamin. La poarta cetății, Ireia îl acuză că trece de partea caldeenilor. Ieremia neagă acuzația, dar nu este ascultat: este bătut și închis în casa scribului Ionatan, unde rămâne mult timp într-o temniță subterană." },
    { from: 17, to: 21, heading: "Zedechia îl consultă în secret, iar Ieremia repetă mesajul și cere să nu fie trimis înapoi în temnița mortală", teaching: "Regele îl scoate pe ascuns și întreabă dacă există vreun cuvânt de la DOMNUL. Ieremia răspunde că da: Zedechia va fi dat în mâna regelui Babilonului. Apoi întreabă ce crimă a comis față de rege și unde sunt profeții care promiseseră că Babilonul nu va veni. Cere să nu fie întors la casa lui Ionatan ca să nu moară, iar regele îl mută în curtea gărzii și îi asigură pâine cât timp există în cetate." },
  ]),
  38: c(38, [
    { from: 1, to: 6, heading: "Conducătorii îl acuză pe Ieremia că slăbește moralul și îl aruncă într-o cisternă cu noroi", teaching: "Ieremia continuă să spună că cel care rămâne în cetate moare, iar cel care se predă caldeenilor trăiește. Dregătorii interpretează mesajul drept demoralizare și cer moartea lui. Zedechia cedează, iar profetul este coborât cu funii într-o cisternă fără apă, unde se afundă în noroi." },
    { from: 7, to: 13, heading: "Ebed-Melec, un etiopian de la curte, intervine pentru profet și organizează o salvare atentă", teaching: "Ebed-Melec aude ce s-a întâmplat și îl confruntă pe rege: oamenii au făcut rău și Ieremia va muri de foame. Primește treizeci de oameni pentru operațiunea de salvare, ia cârpe vechi ca să protejeze subsuorile profetului de funii și îl scoate din cisternă. Un străin de origine africană devine aici omul care practică dreptatea când liderii lui Iuda abandonează profetul." },
    { from: 14, to: 23, heading: "Zedechia cere din nou adevărul în secret, dar frica de oameni îl împiedică să asculte", teaching: "Regele îl întâlnește pe Ieremia la intrarea templului și promite că nu îl va ucide. Profetul îi spune că predarea către conducătorii Babilonului îi va păstra viața și cetatea; refuzul va aduce ardere și capturare. Zedechia mărturisește că se teme de iudeii care au trecut deja la caldeeni. Ieremia îl asigură că nu va fi dat în mâna lor și îl cheamă să asculte pentru binele propriei vieți." },
    { from: 24, to: 28, heading: "Regele păstrează discuția secretă, iar Ieremia rămâne în curtea gărzii până la căderea cetății", teaching: "Zedechia îi cere profetului să nu dezvăluie conținutul conversației dregătorilor și îi oferă un răspuns de acoperire legat de cererea de a nu reveni în casa lui Ionatan. Când dregătorii întreabă, Ieremia răspunde astfel și cazul rămâne închis. El locuiește în curtea gărzii până când Ierusalimul este cucerit." },
  ]),
  39: c(39, [
    { from: 1, to: 3, heading: "După un asediu îndelungat, zidul Ierusalimului este străpuns și dregătorii Babilonului intră în cetate", teaching: "Asediul început în anul al nouălea al lui Zedechia ajunge la breșă în anul al unsprezecelea. Conducătorii babilonieni intră și se așază la Poarta de Mijloc. Momentul pe care profeții falși îl negaseră devine realitate politică și militară." },
    { from: 4, to: 10, heading: "Zedechia fuge, este prins, își vede fiii uciși și este dus orb în Babilon", teaching: "Regele și soldații încearcă să fugă noaptea, dar sunt urmăriți până în câmpiile Ierihonului. Nebucadnețar pronunță sentința la Ribla: fiii lui Zedechia și nobilii sunt uciși înaintea lui, apoi ochii regelui sunt scoși și el este legat pentru Babilon. Cetatea și casele sunt arse, zidurile dărâmate, populația deportată, iar o parte dintre săraci primesc vii și ogoare." },
    { from: 11, to: 14, heading: "Nebucadnețar dă ordin ca Ieremia să fie protejat și lăsat să aleagă ce i se pare bine", teaching: "Regele Babilonului îi poruncește lui Nebuzaradan să aibă grijă de Ieremia, să nu-i facă rău și să facă pentru el ceea ce cere. Dregătorii îl scot din curtea gărzii și îl încredințează lui Ghedalia ca să locuiască între oamenii rămași. Profetul persecutat de conducătorii propriei cetăți primește protecție de la puterea cuceritoare." },
    { from: 15, to: 18, heading: "Ebed-Melec primește promisiunea vieții pentru că s-a încrezut în Dumnezeu", teaching: "Înainte de căderea cetății, Ieremia primise un cuvânt pentru etiopianul care îl salvase. Nenorocirea va veni asupra Ierusalimului, dar Ebed-Melec nu va fi dat în mâna oamenilor de care se teme. Viața îi va fi ca pradă, iar motivul declarat este încrederea lui în DOMNUL." },
  ]),
  40: c(40, [
    { from: 1, to: 6, heading: "Ieremia este eliberat la Rama și alege să rămână cu Ghedalia între oamenii din țară", teaching: "Nebuzaradan îl găsește pe Ieremia legat între deportați și recunoaște că dezastrul împlinise cuvântul Dumnezeului lui Iuda. Îi scoate lanțurile și îi oferă libertatea să meargă la Babilon sub protecție sau oriunde dorește. Ieremia alege să se ducă la Ghedalia, numit guvernator peste cetățile lui Iuda, și să locuiască între rămășiță." },
    { from: 7, to: 12, heading: "Căpeteniile și refugiații se adună la Ghedalia, care îi îndeamnă să slujească Babilonului și să lucreze pământul", teaching: "Comandanții rămași află că Ghedalia a primit responsabilitate peste săraci și peste cei nedeportați. El jură că nu trebuie să se teamă de slujirea caldeenilor și îi îndeamnă să strângă vin, fructe și untdelemn și să locuiască în cetățile ocupate. Iudeii refugiați în Moab, Amon, Edom și alte țări se întorc și strâng o recoltă mare." },
    { from: 13, to: 16, heading: "Ghedalia refuză să creadă avertismentul că Ismael a fost trimis să-l ucidă", teaching: "Iohanan și căpeteniile îi spun lui Ghedalia că Baalis, regele amoniților, l-a trimis pe Ismael să-l asasineze. Ghedalia nu crede informația. Iohanan îi propune în secret să-l ucidă preventiv pe Ismael pentru a evita risipirea rămășiței, dar guvernatorul îi interzice și numește acuzația o minciună. Capitolul se încheie cu pericolul încă nerezolvat." },
  ]),
}
