import type { ExplainedOverlayChapter } from "../explainedOverlay.js"
import { VT_MAJOR_PROPHETS_FULL } from "../vtFullNarrativesMajorProphets.js"
import { sectionedTextualChapter } from "./textualChapterFactory.js"

const data = VT_MAJOR_PROPHETS_FULL.ieremia
const c = (number: number, sections: Parameters<typeof sectionedTextualChapter>[3]) =>
  sectionedTextualChapter("Ieremia", data, number, sections)

export const IEREMIA_DEEPENED_41_52: Readonly<Record<number, ExplainedOverlayChapter>> = {
  41: c(41, [
    { from: 1, to: 10, heading: "Ismael îl ucide pe Ghedalia și transformă fragila ordine de după cucerire într-un nou masacru", teaching: "Ismael vine la Mițpa cu zece oameni și mănâncă la masa lui Ghedalia, apoi îl ucide pe guvernatorul pus de Babilon și pe iudeii și soldații caldeeni aflați cu el. A doua zi, optzeci de pelerini vin în doliu spre locul templului distrus; Ismael îi atrage în cetate și îi ucide aproape pe toți, cruțând zece pentru rezervele lor de hrană. Violența politică se hrănește aici din înșelarea ospitalității și din exploatarea vulnerabilității." },
    { from: 11, to: 15, heading: "Iohanan îl urmărește pe Ismael și eliberează captivii luați din Mițpa", teaching: "Când Iohanan și căpeteniile aud atrocitățile, pornesc după Ismael și îl întâlnesc lângă apele Gabaonului. Captivii se bucură când îi văd și trec de partea lor. Ismael scapă cu opt oameni spre Amon, astfel că salvarea ostaticilor nu înseamnă și aducerea imediată a criminalului la judecată." },
    { from: 16, to: 18, heading: "Teama de represaliile Babilonului îi împinge pe supraviețuitori spre drumul Egiptului", teaching: "Iohanan adună bărbații, femeile, copiii, soldații și oficialii salvați și se oprește lângă Betleem cu intenția de a merge în Egipt. Motivul este frica de caldeeni după uciderea guvernatorului numit de Nebucadnețar. Capitolul se încheie cu o comunitate care a scăpat de un atac, dar riscă să ia următoarea decizie majoră din frică." },
  ]),
  42: c(42, [
    { from: 1, to: 6, heading: "Rămășița îi cere lui Ieremia să afle de la Dumnezeu calea și promite să asculte indiferent de răspuns", teaching: "Căpeteniile și poporul, de la cel mic la cel mare, vin la profet și cer rugăciune pentru rămășița redusă. Ei spun că vor ca DOMNUL să le arate drumul și ce trebuie să facă. Ieremia acceptă să se roage și promite să nu ascundă nimic, iar oamenii Îl cheamă pe Dumnezeu ca martor că vor asculta fie că mesajul le place, fie că nu." },
    { from: 7, to: 12, heading: "După zece zile, răspunsul este să rămână în țară și să nu se teamă de regele Babilonului", teaching: "Cuvântul nu vine instantaneu, ci după zece zile. Dumnezeu spune că, dacă rămân în țară, îi va zidi și planta și Se îndură de nenorocirea adusă. Frica de Nebucadnețar nu trebuie să decidă viitorul lor, pentru că Dumnezeu promite să fie cu ei și să le dea milă înaintea regelui." },
    { from: 13, to: 18, heading: "Alegerea Egiptului pentru a evita războiul, foametea și nesiguranța va aduce tocmai lucrurile de care fug", teaching: "Dacă oamenii spun că nu vor rămâne în Iuda și aleg Egiptul fiindcă acolo cred că nu vor vedea război și nu vor duce lipsă de pâine, sabia și foametea îi vor urma. Egiptul nu devine un spațiu în afara judecății. Cei care își fixează hotărârea să plece sunt avertizați că vor ajunge obiect de groază și nu vor mai vedea țara." },
    { from: 19, to: 22, heading: "Ieremia expune diferența dintre cererea de călăuzire și dorința de confirmare a unei decizii deja luate", teaching: "Profetul spune direct: nu mergeți în Egipt. Apoi le amintește că s-au înșelat pe ei înșiși când l-au trimis să se roage, pentru că promisiunea lor de ascultare nu era sinceră dacă răspunsul nu corespundea planului deja ales. Ei au primit avertismentul complet și știu acum consecința refuzului." },
  ]),
  43: c(43, [
    { from: 1, to: 7, heading: "Azaria și Iohanan îl acuză pe Ieremia de minciună și duc întreaga rămășiță în Egipt", teaching: "Când Ieremia termină mesajul, liderii îl numesc arogant și spun că Baruc îl influențează ca să-i dea în mâna caldeenilor. Promisiunea din capitolul anterior de a asculta orice răspuns este abandonată. Iohanan și căpeteniile iau rămășița, inclusiv pe Ieremia și Baruc, și ajung la Tahpanhes, încălcând cuvântul primit." },
    { from: 8, to: 13, heading: "Pietre ascunse la Tahpanhes devin semn că Nebucadnețar își va întinde tronul chiar peste refugiul ales", teaching: "Dumnezeu îi spune lui Ieremia să ascundă pietre mari în pavajul de la intrarea palatului faraonului, înaintea iudeilor. Peste ele Nebucadnețar își va așeza tronul când vine asupra Egiptului. Templele și obeliscurile sunt lovite, iar regele Babilonului pleacă după ce își împlinește misiunea. Locul ales pentru a scăpa de Babilon ajunge sub puterea Babilonului." },
  ]),
  44: c(44, [
    { from: 1, to: 10, heading: "Iudeii din Egipt sunt chemați să-și amintească de ce Ierusalimul a ajuns ruină", teaching: "Mesajul se adresează comunităților din Migdol, Tahpanhes, Nof și Patros. Dumnezeu amintește răul care a transformat cetățile lui Iuda în pustiu: tămâia oferită altor dumnezei și refuzul repetat al profeților care cereau abandonarea idolatriei. Exilații nu s-au smerit și nu umblă în Lege, deși au înainte consecințele istoriei recente." },
    { from: 11, to: 14, heading: "Rămășița care și-a fixat fața spre Egipt este avertizată că aproape nimeni nu se va întoarce în Iuda", teaching: "Dumnezeu spune că Își întoarce fața împotriva celor care au ales Egiptul. Sabia și foametea îi vor atinge de la mic la mare, iar comunitatea devine exemplu de groază și batjocură. Doar câțiva fugari vor reveni, astfel că planul unei colonii sigure din care să se întoarcă mai târziu este destrămat." },
    { from: 15, to: 19, heading: "Poporul răspunde că va continua cultul «reginei cerului» fiindcă îl asociază cu vremurile de prosperitate", teaching: "Bărbații care știau că soțiile lor aduceau tămâie și femeile prezente resping explicit cuvântul lui Ieremia. Ei susțin că atunci când ofereau jertfe reginei cerului aveau pâine, prosperitate și siguranță, iar după încetarea cultului au venit lipsurile. Femeile precizează că soții știau de prăjiturile și libațiile lor. Experiența economică este folosită astfel ca argument pentru idolatrie." },
    { from: 20, to: 30, heading: "Ieremia inversează interpretarea: tocmai idolatria acumulată a adus dezastrul, iar faraonul Hofra devine semn", teaching: "Profetul spune că Dumnezeu nu a uitat tămâia adusă în cetăți și că tocmai acumularea răului a făcut țara pustie. Oamenii care jură să continue cultul primesc verdictul că Numele DOMNULUI nu va mai fi rostit de ei ca formulă goală. Un mic număr va scăpa ca să vadă al cui cuvânt rămâne. Semnul este că faraonul Hofra va fi dat în mâna dușmanilor, așa cum Zedechia fusese dat lui Nebucadnețar." },
  ]),
  45: c(45, [
    { from: 1, to: 3, heading: "Baruc, obosit de scrierea mesajelor grele, spune că durerea i-a fost adăugată peste durere", teaching: "Cuvântul personal pentru Baruc este dat în al patrulea an al lui Ioiachim, când scria după dictarea lui Ieremia. Scribul spune că DOMNUL i-a adăugat durere, că este obosit de gemete și nu găsește odihnă. Biblia păstrează astfel și costul interior al omului care sprijină lucrarea profetică fără a fi figura principală a narațiunii." },
    { from: 4, to: 5, heading: "Dumnezeu îi spune să nu caute lucruri mari pentru sine într-o vreme în care întreaga țară este smulsă", teaching: "Dumnezeu spune că dărâmă ceea ce zidise și smulge ceea ce plantase. Într-un asemenea moment, Baruc este întrebat dacă își caută o poziție mare pentru sine și primește porunca să nu o facă. Nenorocirea vine peste orice făptură, dar viața lui îi va fi dată ca pradă oriunde merge. Promisiunea este conservarea vieții, nu succesul de statut." },
  ]),
  46: c(46, [
    { from: 1, to: 12, heading: "Armata Egiptului merge cu încredere spre Carchemiș și este împinsă înapoi până la Eufrat", teaching: "Oracolul este dat în contextul înfrângerii lui Neco de către Nebucadnețar. Scuturile, coifurile, sulițele și caii sunt chemați la luptă, dar profetul vede soldații întorcându-se în panică. Egiptul se ridică asemenea Nilului și spune că va acoperi pământul, însă ziua este descrisă ca zi a DOMNULUI împotriva dușmanilor Lui, iar Galaadul nu are balsam suficient pentru rana militară a Egiptului." },
    { from: 13, to: 19, heading: "Nebucadnețar este anunțat venind în Egipt, iar cetățile sunt chemate să se pregătească pentru captivitate", teaching: "Mesajul privește invazia directă a Egiptului. Migdol, Nof și Tahpanhes sunt chemate să stea în ordine, dar războinicii cad pentru că nu pot rezista. Faraon este batjocorit ca unul care a lăsat să treacă timpul potrivit, iar cuceritorul vine sigur ca Taborul între munți și Carmelul lângă mare. Fiica Egiptului trebuie să-și pregătească bagajul de exil." },
    { from: 20, to: 26, heading: "Egiptul, vițea frumoasă, este înțepat de atacul din nord și dat temporar în mâna dușmanilor", teaching: "Țara este comparată cu o vițea frumoasă peste care vine un tăun din nord. Mercenarii ei, asemenea vițeilor îngrășați, fug împreună. Lemnarii vin ca o mulțime de lăcuste și taie pădurea imposibil de cercetat. Amon din No, faraonul, Egiptul și cei care se încred în rege sunt dați lui Nebucadnețar, dar profeția lasă și perspectiva că țara va fi locuită din nou după aceea." },
    { from: 27, to: 28, heading: "În mijlocul oracolului împotriva Egiptului, Iacov primește chemarea să nu se teamă", teaching: "Israel este asigurat că Dumnezeu îl va salva din depărtare și pe urmașii lui din captivitate. Iacov se va întoarce la odihnă și nu va fi nimicit complet. Totuși disciplina rămâne: Dumnezeu îl corectează cu măsură și nu îl declară pur și simplu nevinovat." },
  ]),
  47: c(47, [
    { from: 1, to: 4, heading: "Apa din nord inundă simbolic Filistia înainte ca faraonul să lovească Gaza", teaching: "Oracolul vine înainte de atacul faraonului asupra Gazei. O apă se ridică din nord și devine torent peste țară, cetăți și locuitori. Oamenii strigă, iar părinții nu se mai întorc spre copii din cauza slăbirii mâinilor. Ziua nimicirii filistenilor ajunge și la Tir și Sidon, iar DOMNUL este prezentat ca Cel care rupe sprijinul lor." },
    { from: 5, to: 7, heading: "Sabia este întrebată când se va odihni, dar răspunsul este că are o misiune stabilită", teaching: "Gaza își rade capul și Așchelonul tace, iar profetul întreabă cât va continua tăierea. El cheamă sabia să intre în teacă și să se odihnească, apoi răspunde că nu poate încă, pentru că DOMNUL i-a poruncit o lucrare împotriva Așchelonului și coastei mării. Lamentația și recunoașterea judecății stau una lângă alta." },
  ]),
  48: c(48, [
    { from: 1, to: 10, heading: "Cetățile Moabului cad, iar încrederea în lucrări și comori se dovedește incapabilă să salveze", teaching: "Nebo, Chiriataim, Heșbon și alte cetăți intră în ruină. Moabul este făcut de rușine, iar planurile împotriva lui se formează chiar la Heșbon. Fuga și strigătul ajung din loc în loc. Motivul include încrederea în propriile lucrări și comori. Chemoș, zeul național, merge în captivitate împreună cu preoții și prinții lui." },
    { from: 11, to: 17, heading: "Moabul care a stat liniștit «pe drojdii» este turnat din vas și își pierde aroma sigură de sine", teaching: "Moabul este comparat cu vinul care nu a fost mutat din vas în vas și de aceea și-a păstrat gustul. Stabilitatea lungă a produs o identitate sigură de sine, dar vin zile când este turnat și vasele sunt sparte. Atunci rușinea lui Chemoș va semăna cu rușinea pe care Israel a cunoscut-o când s-a încrezut în Betel. Războinicii nu mai pot spune cu aceeași siguranță că sunt viteji." },
    { from: 18, to: 28, heading: "O listă de cetăți transformă judecata într-o hartă a fugii și a pierderii", teaching: "Dibon coboară din glorie și stă în sete, Aroer privește fugarii, iar cetățile câmpiei sunt enumerate una după alta. Cornul și brațul Moabului sunt frânte. Poporul este chemat să se comporte ca un om beat și să ajungă de batjocură pentru că s-a mărit împotriva DOMNULUI, apoi să fugă spre stânci ca porumbelul." },
    { from: 29, to: 39, heading: "Mândria Moabului este numită repetat, dar Dumnezeu și profetul plâng pentru țară", teaching: "Orgoliul, aroganța și înălțarea inimii sunt expuse, iar lăudăroșenia este declarată fără rezultat. Totuși judecata nu este relatată rece: Dumnezeu spune că va plânge și va geme pentru Moab și pentru oamenii Chir-Heresului. Viile și recolta sunt distruse, bucuria dispare din teascuri, iar strigătul se întinde din cetate în cetate." },
    { from: 40, to: 47, heading: "Vulturul întins peste Moab aduce teroare, dar ultimul verset păstrează o promisiune de restaurare", teaching: "Cuceritorul este comparat cu un vultur care își întinde aripile, cetățile sunt luate și inimile războinicilor slăbesc. Groaza, groapa și lațul îi urmăresc pe locuitori, iar focul iese din Heșbon. Cu toate acestea, oracolul nu se termină în ruină absolută: Dumnezeu spune că în zilele de pe urmă va aduce înapoi captivitatea Moabului." },
  ]),
  49: c(49, [
    { from: 1, to: 6, heading: "Amon este confruntat pentru ocuparea moștenirii lui Gad, apoi primește și el o promisiune de restaurare", teaching: "Profetul întreabă dacă Israel nu are fii și de ce Malcam a moștenit cetățile lui Gad. Raba și cetățile ei sunt chemate la jale, iar poporul care se laudă cu văile și comorile este avertizat că teroarea vine din toate părțile. Totuși, ca în cazul Moabului, ultimul verset spune că Dumnezeu va aduce înapoi captivitatea fiilor lui Amon." },
    { from: 7, to: 22, heading: "Înțelepciunea Edomului nu poate împiedica golirea Boțrei și căderea celui care locuiește în stânci", teaching: "Temanul, renumit pentru înțelepciune, este întrebat dacă sfatul a pierit. Edom ar vrea să se ascundă adânc, dar Dumnezeu îl dezbracă până când nu mai are ascunzătoare. Orfanii și văduvele apar surprinzător sub promisiunea grijii divine. Boțra devine pustie, iar mândria celui care locuiește în crăpăturile stâncii este coborâtă chiar dacă și-ar face cuibul ca vulturul." },
    { from: 23, to: 27, heading: "Damascul se topește de frică, iar focul ajunge pe zidurile lui", teaching: "Hamat și Arpad sunt rușinate de veștile rele, iar Damascul devine neliniștit ca marea. Cetatea lăudată nu reușește să fugă, tinerii cad pe străzi și războinicii sunt reduși la tăcere. Focul consumă zidurile și palatele lui Ben-Hadad." },
    { from: 28, to: 33, heading: "Chedar și regatele Hațorului sunt atacate tocmai în locul în care se credeau fără ziduri și în siguranță", teaching: "Nebucadnețar primește chemarea împotriva triburilor și regatelor din pustiu. Corturile, turmele și cămilele sunt luate, iar strigătul «groază din toate părțile» îi împrăștie. Hațor este descris ca popor care locuiește fără porți și zăvoare, izolat și sigur; tocmai această siguranță este spulberată, iar locul devine pustiu." },
    { from: 34, to: 39, heading: "Arcul Elamului este frânt și poporul este împrăștiat, dar finalul vorbește despre întoarcere", teaching: "La începutul domniei lui Zedechia, Ieremia primește cuvânt despre Elam. Dumnezeu îi frânge arcul, principala putere militară, și aduce cele patru vânturi asupra poporului, împrăștiindu-l. Tronul divin este pus simbolic în Elam pentru judecata regelui și conducătorilor, însă ultimul verset deschide din nou perspectiva restaurării în zilele de pe urmă." },
  ]),
  50: c(50, [
    { from: 1, to: 10, heading: "Căderea Babilonului este vestită public, iar Israel și Iuda se întorc plângând spre Sion", teaching: "Națiunile trebuie să audă că Babilonul este capturat și că Bel și Merodac sunt făcuți de rușine. O putere din nord transformă țara în pustiu. În același timp, Israel și Iuda caută împreună pe DOMNUL și întreabă de drumul spre Sion ca să intre într-un legământ de neuitat. Poporul fusese o turmă pierdută, condusă greșit de păstori, iar cei care îl devorau își justificau acțiunea prin vinovăția lui." },
    { from: 11, to: 20, heading: "Babilonul care s-a bucurat de prada lui Dumnezeu ajunge ultimul între națiuni, iar Israel este adus înapoi la pășune", teaching: "Cuceritorii moștenirii lui Dumnezeu sunt comparați cu animale care zburdă și nechează de satisfacție, dar mama lor ajunge rușinată și țara pustie. Atacatorii Babilonului sunt chemați să tragă fără să cruțe săgeți, pentru că el a păcătuit împotriva DOMNULUI. Asiria și Babilonul sunt puse în aceeași istorie a devorării lui Israel, iar Dumnezeu promite să-l readucă pe Carmel și Basan și să ierte rămășița." },
    { from: 21, to: 32, heading: "Campania împotriva Babilonului este numită răzbunarea DOMNULUI asupra mândriei lui", teaching: "Merataim și Pecod sunt chemate simbolic în oracol, iar Babilonul devine ciocanul lumii care este el însuși zdrobit. Dumnezeu spune că a întins o cursă și cetatea a fost prinsă fără să știe. Hambarele sunt deschise, iar armata este nimicită. Motivul repetat este mândria împotriva DOMNULUI, Sfântul lui Israel; cel arogant se poticnește și nu are cine să-l ridice." },
    { from: 33, to: 40, heading: "Răscumpărătorul lui Israel este puternic și pledează cauza poporului, în timp ce sabia lovește structurile Babilonului", teaching: "Israel și Iuda sunt apăsați și captivatorii refuză să-i lase, dar Răscumpărătorul lor este numit DOMNUL oștirilor și spune că le va apăra cauza ca să dea odihnă pământului. Sabia este chemată asupra caldeenilor, dregătorilor, înțelepților, profeților falși, războinicilor, cailor și comorilor. Babilonul ajunge comparat cu Sodoma și Gomora, nelocuit și pustiu." },
    { from: 41, to: 46, heading: "Un popor din nord vine ca marea, iar regele Babilonului își pierde curajul", teaching: "O armată mare se ridică de la marginile pământului, cu arcuri și sulițe și fără milă în imaginea războiului antic. Vuietul ei este ca marea. Regele Babilonului aude vestea, îi slăbesc mâinile și îl apucă durerea ca pe o femeie la naștere. Dumnezeu întreabă cine este asemenea Lui și ce păstor ar putea sta înaintea Lui; planul Său face pământul să se cutremure la căderea Babilonului." },
  ]),
  51: c(51, [
    { from: 1, to: 14, heading: "Un vânt nimicitor și secerători sunt ridicați împotriva Babilonului, dar Israel nu este părăsit", teaching: "Dumnezeu trimite împotriva Babilonului un duh distrugător și străini care îl vântură. Arcașii sunt chemați să nu cruțe armata caldeeană. În mijlocul limbajului sever apare afirmația că Israel și Iuda nu sunt părăsiți de Dumnezeul lor, deși țara lor fusese plină de vinovăție. Poporul este chemat să fugă pentru a nu fi prins în pedeapsa Babilonului, cupa care îmbătase națiunile." },
    { from: 15, to: 19, heading: "Creatorul pământului este pus din nou în contrast cu idolul fără suflare", teaching: "Dumnezeu a făcut pământul prin putere, a întemeiat lumea prin înțelepciune și conduce apele, norii, fulgerele și vântul. Făuritorul idolului este făcut de rușine, fiindcă imaginea turnată este minciună și nu are suflare. Partea lui Iacov nu este asemenea lor: El este Creatorul tuturor lucrurilor și Israel este seminția moștenirii Lui." },
    { from: 20, to: 26, heading: "Babilonul, ciocan folosit pentru a zdrobi națiuni, ajunge muntele nimicitor coborât de Dumnezeu", teaching: "Textul enumeră oameni și structuri pe care Babilonul le zdrobise: națiuni, regi, cai, care, bărbați, femei, bătrâni, tineri, păstori și conducători. Apoi Dumnezeu spune că îi răsplătește în Sion tot răul făcut. Muntele nimicitor este rostogolit de pe stânci și ajunge munte ars, incapabil să mai ofere piatră de temelie." },
    { from: 27, to: 33, heading: "Națiunile sunt chemate împotriva Babilonului, iar fiica lui este comparată cu o arie gata de treierat", teaching: "Steagul se ridică și Ararat, Mini, Așchenaz și regii mezilor sunt mobilizați. Pământul tremură pentru că planurile DOMNULUI împotriva Babilonului stau. Războinicii cetății încetează să lupte și puterea lor devine ca a femeilor în imaginea militară antică. Babilonul este comparat cu o arie bătătorită, iar timpul secerișului se apropie." },
    { from: 34, to: 40, heading: "Sionul își formulează plângerea împotriva lui Nebucadnețar, iar Dumnezeu spune că îi va apăra cauza", teaching: "Ierusalimul spune că regele Babilonului l-a devorat, l-a golit și l-a aruncat ca pe un vas. Violența făcută Sionului este cerută înapoi asupra Caldeii. Dumnezeu răspunde că va pleda cauza poporului, va seca marea Babilonului și va transforma cetățile în grămezi de ruine. Conducătorii și oamenii puterii sunt comparați cu miei duși la măcel în ziua judecății lor." },
    { from: 41, to: 48, heading: "Șeșac este luat, marea acoperă Babilonul, iar poporul lui Dumnezeu este chemat să iasă", teaching: "Cetatea lăudată a întregului pământ devine obiect de groază, iar valurile dușmanului o acoperă. Dumnezeu îl judecă pe Bel și scoate din gura lui ceea ce înghițise, iar zidurile cad. Chemarea pastorală pentru Israel este clară: ieșiți din mijlocul ei și fiecare să-și salveze viața, fără să se lase paralizat de zvonurile succesive despre violență." },
    { from: 49, to: 58, heading: "Căderea celor uciși din Israel este pusă în balanță cu cei uciși ai Babilonului, iar zidurile mari sunt nivelate", teaching: "Așa cum Babilonul a făcut să cadă oameni din Israel, tot astfel cad oameni din întreaga țară a Babilonului. Supraviețuitorii sunt chemați să-și amintească de DOMNUL și de Ierusalim din depărtare. Oricât de sus s-ar ridica cetatea și oricât și-ar întări fortificațiile, distrugătorii vin. Prinții, înțelepții și războinicii sunt îmbătați simbolic și adormiți, iar zidul lat al Babilonului este nivelat." },
    { from: 59, to: 64, heading: "Seraia citește profeția la Babilon și aruncă sulul în Eufrat ca semn al scufundării cetății", teaching: "În al patrulea an al lui Zedechia, Ieremia îi dă lui Seraia un sul cu toate nenorocirile scrise împotriva Babilonului. Ajuns acolo, el trebuie să citească mesajul și să recunoască faptul că Dumnezeu a anunțat pustiirea. Apoi leagă o piatră de sul și îl aruncă în Eufrat, spunând că tot astfel Babilonul se va scufunda și nu se va mai ridica din cauza nenorocirii. Capitolul marchează și încheierea cuvintelor lui Ieremia." },
  ]),
  52: c(52, [
    { from: 1, to: 11, heading: "Epilogul reia căderea Ierusalimului și sfârșitul domniei lui Zedechia", teaching: "Zedechia face rău înaintea DOMNULUI, iar răzvrătirea lui împotriva Babilonului conduce la asediu. Foametea devine severă, zidul este străpuns și armata fuge noaptea. Regele este prins în câmpiile Ierihonului, judecat la Ribla, își vede fiii uciși, apoi este orbit și dus în lanțuri la Babilon, unde rămâne până la moarte." },
    { from: 12, to: 23, heading: "Templul, palatul și zidurile sunt distruse, iar obiectele de bronz, aur și argint sunt duse la Babilon", teaching: "Nebuzaradan arde Casa DOMNULUI, casa regelui și clădirile importante și dărâmă zidurile. O parte din populație este deportată, în timp ce săracii sunt lăsați să lucreze viile și câmpurile. Stâlpii de bronz, Marea, suporturile și instrumentele templului sunt desfăcute și transportate; textul inventariază chiar dimensiunile și ornamentele stâlpilor, subliniind pierderea concretă a sanctuarului." },
    { from: 24, to: 30, heading: "Liderii sunt executați la Ribla, iar deportările sunt numărate în valuri", teaching: "Căpetenia gărzii îi ia pe marele preot Seraia, pe al doilea preot Țefania, pe păzitorii templului, oficiali militari și reprezentanți ai poporului și îi duce la regele Babilonului, care îi ucide la Ribla. Apoi sunt oferite numere pentru deportările din anii al șaptelea, al optsprezecelea și al douăzeci și treilea al lui Nebucadnețar, ancorând tragedia în evidența istorică a exilului." },
    { from: 31, to: 34, heading: "Cartea se încheie cu Ieconia scos din închisoare, așezat la masa regelui și întreținut până la moarte", teaching: "La treizeci și șapte de ani după deportarea lui Ieconia, Evil-Merodac îl eliberează din închisoare, îi vorbește cu bunătate și îi ridică scaunul deasupra altor regi captivi. Ieconia își schimbă hainele de închisoare și mănâncă permanent la masa regelui, primind o rație zilnică până la moarte. După distrugerea templului și a dinastiei, epilogul lasă astfel o mică fereastră de continuitate pentru linia davidică." },
  ]),
}
