import type { ExplainedOverlayChapter } from "../explainedOverlay.js"
import { VT_MAJOR_PROPHETS_FULL } from "../vtFullNarrativesMajorProphets.js"
import { sectionedTextualChapter } from "./textualChapterFactory.js"

const data = VT_MAJOR_PROPHETS_FULL.ieremia
const c = (number: number, sections: Parameters<typeof sectionedTextualChapter>[3]) =>
  sectionedTextualChapter("Ieremia", data, number, sections)

export const IEREMIA_DEEPENED_08_22: Readonly<Partial<Record<number, ExplainedOverlayChapter>>> = {
  8: c(8, [
    { from: 1, to: 7, heading: "Judecata ajunge până la morminte, iar poporul refuză întoarcerea pe care chiar păsările o cunosc", teaching: "Oasele regilor, conducătorilor, preoților și profeților sunt scoase înaintea corpurilor cerești pe care le iubiseră și slujiseră. Apoi Dumnezeu întreabă de ce Ierusalimul se întoarce mereu în direcția greșită. Calul se avântă în luptă, iar păsările își cunosc anotimpurile, dar poporul nu recunoaște timpul întoarcerii la DOMNUL." },
    { from: 8, to: 13, heading: "Pretenția de înțelepciune este demascată când scribii răstălmăcesc Legea și liderii spun «pace» fără vindecare", teaching: "Oamenii spun că sunt înțelepți pentru că au Legea, dar condeiul mincinos al scribilor a lucrat fals, iar cei care au respins cuvântul nu pot revendica înțelepciunea doar prin statut. De la profet până la preot, câștigul nedrept și tratarea superficială a rănii poporului sunt condamnate. «Pace, pace» nu vindecă o rană pe care nimeni nu o tratează în adevăr." },
    { from: 14, to: 17, heading: "Poporul vede că pacea așteptată nu vine și că invazia se apropie din nord", teaching: "Cetățile fortificate sunt privite ca ultim refugiu, dar comunitatea recunoaște că așteptarea păcii a produs teroare. Caii dușmanului se aud din Dan, iar șerpii trimiși în imaginea profetică nu pot fi fermecați. Judecata nu mai este o amenințare abstractă, ci o realitate apropiată." },
    { from: 18, to: 22, heading: "Durerea poporului devine durerea profetului: «nu este balsam în Galaad?»", teaching: "Ieremia aude strigătul fiicei poporului și îl poartă în propria inimă. Întrebarea dacă DOMNUL nu mai este în Sion este pusă lângă idolatria care L-a provocat. Recolta a trecut și salvarea nu a venit, iar profetul spune că este zdrobit odată cu poporul. Balsamul și medicul din Galaad devin imaginea vindecării care lipsește unei răni spirituale netratate." },
  ]),
  9: c(9, [
    { from: 1, to: 6, heading: "Ieremia ar vrea ochi ca un izvor pentru un popor în care minciuna a devenit mediul zilnic", teaching: "Profetul dorește să plângă fără oprire pentru cei uciși și, simultan, să se poată îndepărta de o societate plină de adulter și trădare. Limba este întinsă ca un arc pentru minciună, prietenii și frații nu mai sunt siguri, iar oamenii s-au obișnuit atât de mult cu înșelarea încât refuză să-L cunoască pe Dumnezeu." },
    { from: 7, to: 16, heading: "Dumnezeu testează un popor al cărui discurs este pașnic la suprafață și periculos în interior", teaching: "DOMNUL întreabă cum ar putea să nu judece o astfel de comunitate. Limba devine săgeată ucigătoare: omul vorbește pașnic cu aproapele, dar îi pregătește cursă. Ieremia plânge munții și pășunile pustii, iar cauza distrugerii este explicată prin părăsirea Legii și urmarea încăpățânării inimii și a baalilor." },
    { from: 17, to: 22, heading: "Femeile bocitoare sunt chemate pentru că moartea a intrat în ferestre și pe străzi", teaching: "Jalea devine atât de mare încât sunt chemate bocitoare pricepute să învețe următoarea generație plângerea. Moartea este personificată ca intrând prin ferestre și luând copiii și tinerii. Trupurile rămân ca gunoiul pe câmp sau ca snopii pe care nimeni nu îi adună, imagine a proporției dezastrului." },
    { from: 23, to: 26, heading: "Lauda legitimă nu este în înțelepciune, putere sau bogăție, ci în cunoașterea caracterului lui Dumnezeu", teaching: "Înțeleptul, puternicul și bogatul sunt opriți să-și facă din aceste avantaje motivul suprem al identității. Cine se laudă este chemat să se laude că Îl înțelege și Îl cunoaște pe DOMNUL ca Dumnezeu al bunătății, dreptății și judecății. Finalul avertizează că circumcizia exterioară nu este suficientă când inima rămâne necircumcisă." },
  ]),
  10: c(10, [
    { from: 1, to: 5, heading: "Semnele cerului și idolii făcuți de meșteșugar nu trebuie să devină obiecte de teamă", teaching: "Israel este avertizat să nu învețe căile neamurilor și să nu se îngrozească de semnele cerești. Un copac este tăiat, lucrat de meșteșugar, împodobit și fixat cu cuie ca să nu cadă. Idolul nu poate vorbi și trebuie purtat pentru că nu poate merge; tocmai această dependență arată că nu are puterea atribuită lui." },
    { from: 6, to: 10, heading: "DOMNUL este mare, viu și Împărat veșnic în contrast cu lucrurile fabricate", teaching: "Nimeni nu este asemenea DOMNULUI, iar Numele Lui este mare în putere. Înțelepciunea popoarelor și materialele scumpe nu schimbă natura idolilor. Dumnezeu este numit adevărat, viu și Împărat veșnic; pământul tremură înaintea mâniei Lui, în timp ce idolii depind de creatorii lor umani." },
    { from: 11, to: 16, heading: "Creatorul a făcut pământul prin putere și Israel este partea Lui", teaching: "Dumnezeii care nu au făcut cerul și pământul sunt destinați dispariției. În contrast, DOMNUL a întemeiat lumea prin înțelepciune și conduce apele, norii, fulgerele și vântul. Omul care face un idol se dovedește fără cunoaștere, iar imaginea turnată este minciună fără suflare. Partea lui Iacov este diferită: Creatorul tuturor lucrurilor este Dumnezeul lui." },
    { from: 17, to: 25, heading: "Exilul este anunțat, iar Ieremia transformă pierderea într-o rugăciune pentru corectare și dreptate", teaching: "Locuitorii sunt chemați să-și strângă lucrurile pentru plecare, iar cetatea este descrisă ca lovită. Ieremia recunoaște rana și deplânge cortul distrus și păstorii fără înțelepciune. Apoi se roagă: drumul omului nu este în puterea lui, de aceea cere corectare cu măsură, nu nimicire, și cere ca mânia să se îndrepte împotriva neamurilor care au devorat pe Iacov." },
  ]),
  11: c(11, [
    { from: 1, to: 8, heading: "Legământul cere ascultare, nu doar apartenență istorică", teaching: "Ieremia primește porunca să proclame cuvintele legământului în Iuda și Ierusalim. Blestemul este legat de refuzul ascultării, iar promisiunea țării de lapte și miere este amintită împreună cu chemarea «ascultați glasul Meu». Istoria arată însă că părinții au urmat încăpățânarea inimii lor și au adus asupra lor cuvintele legământului încălcat." },
    { from: 9, to: 13, heading: "Conspirația spirituală a poporului este întoarcerea la idolii pe care criza îi va expune", teaching: "Dumnezeu spune că în Iuda există o conspirație: poporul s-a întors la fărădelegile strămoșilor și a mers după alți dumnezei. Când vine nenorocirea, strigătele către acești zei nu aduc salvare. Numărul idolilor a devenit comparabil cu numărul cetăților, iar altarele rușinii s-au multiplicat în Ierusalim." },
    { from: 14, to: 17, heading: "Ritualul nu poate neutraliza răul persistent, iar măslinul frumos ajunge sub foc", teaching: "Ieremia primește din nou interdicția de a mijloci ca și cum un ritual ar putea șterge automat situația. Dumnezeu întreabă ce caută iubita Lui în Casa Sa când practică planuri rele, iar carnea jertfelor nu poate îndepărta răul. Israel fusese numit măslin verde și frumos, dar focul judecății ajunge la ramuri pentru răul făcut prin Baal." },
    { from: 18, to: 23, heading: "Ieremia descoperă complotul din Anatot și își încredințează cauza Judecătorului drept", teaching: "DOMNUL îi arată profetului că oamenii din propria cetate plănuiesc să-l distrugă ca pe un miel dus la tăiere și să-i șteargă numele. Ieremia nu își prezintă nevinovăția ca drept de răzbunare personală, ci își încredințează cauza Celui care cercetează inima. Răspunsul divin anunță judecata asupra complotiștilor din Anatot." },
  ]),
  12: c(12, [
    { from: 1, to: 4, heading: "Ieremia Îl întreabă pe Dumnezeu de ce prosperă cei răi", teaching: "Profetul începe recunoscând dreptatea lui Dumnezeu, dar cere voie să vorbească despre lucrurile care îl tulbură: cei răi prosperă, trădătorii sunt liniștiți și vorbesc despre Dumnezeu fără ca El să fie aproape de inima lor. Ieremia își pune propria cunoaștere de către Dumnezeu în contrast cu ipocrizia lor și întreabă cât va suferi țara din cauza răului locuitorilor." },
    { from: 5, to: 6, heading: "Răspunsul îl pregătește pe profet pentru o cursă mai grea și pentru trădare chiar din familie", teaching: "Dumnezeu folosește două comparații: dacă alergarea cu oamenii te obosește, cum vei concura cu caii; dacă ești nesigur într-un ținut liniștit, ce vei face în desișul Iordanului. Profetul trebuie să știe că până și frații și casa tatălui său îl pot trăda și că strigătele lor prietenoase nu sunt suficiente pentru încredere." },
    { from: 7, to: 13, heading: "Moștenirea iubită este lăsată pradă pentru că s-a întors împotriva Stăpânului", teaching: "Dumnezeu descrie casa și moștenirea Lui ca pe ceva iubit pe care este constrâns să îl lase. Poporul a devenit ca un leu care răcnește împotriva Lui, iar păstorii strică via. Semănatul grâului produce spini și munca nu aduce rod, pentru că mânia DOMNULUI se află asupra țării." },
    { from: 14, to: 17, heading: "Judecata neamurilor vecine este urmată de posibilitatea restaurării și a învățării căilor lui Dumnezeu", teaching: "Dumnezeu vorbește și despre vecinii răi care ating moștenirea lui Israel. Ei vor fi smulși, dar după judecată pot fi aduși înapoi fiecare la moștenirea lui. Dacă vor învăța cu adevărat căile poporului și vor jura pe Numele DOMNULUI, pot fi zidiți în mijlocul lui; refuzul ascultării aduce însă smulgere finală." },
  ]),
  13: c(13, [
    { from: 1, to: 11, heading: "Brâul de in stricat devine imaginea unui popor care trebuia să stea lipit de Dumnezeu", teaching: "Ieremia cumpără un brâu de in, îl poartă și apoi îl ascunde lângă Eufrat până când se strică și nu mai este bun de nimic. Dumnezeu explică semnul: așa cum brâul se lipește de coapsele omului, El făcuse casa lui Israel și Iuda să se lipească de El pentru nume, laudă și glorie, dar ei au refuzat să asculte și au urmat alți dumnezei." },
    { from: 12, to: 14, heading: "Burdufurile pline cu vin devin imaginea unei amețiri care duce la ciocnire și ruină", teaching: "Proverbul evident că orice burduf se umple cu vin primește un sens profetic neașteptat: Dumnezeu spune că locuitorii, regii, preoții și profeții vor fi umpluți de beție și se vor lovi unii de alții. Imaginea descrie dezorientarea și judecata, nu o celebrare a intoxicației." },
    { from: 15, to: 21, heading: "Mândria trebuie coborâtă înainte ca lumina să se transforme în întuneric și turma să fie luată", teaching: "Poporul este chemat să asculte și să nu se înalțe. Înainte ca întunericul să acopere munții, trebuie dată glorie DOMNULUI. Ieremia spune că va plânge în ascuns pentru mândrie și pentru turma dusă captivă. Regele și regina mamă sunt chemați să coboare din poziție, iar cetățile din sud se închid." },
    { from: 22, to: 27, heading: "Întrebarea despre schimbarea pielii arată adâncimea unui obicei al răului, nu imposibilitatea harului", teaching: "Ierusalimul întreabă de ce i se întâmplă acestea și primește răspunsul că multitudinea nelegiuirilor a produs rușinea. Etiopianul nu își poate schimba pielea și leopardul petele; tot așa, oamenii obișnuiți cu răul nu pot pur și simplu să înceapă binele printr-un gest superficial. Imaginea descrie înrădăcinarea obiceiului păcătos în această generație, nu o doctrină despre rasă și nici o negare a puterii lui Dumnezeu de a transforma omul." },
  ]),
  14: c(14, [
    { from: 1, to: 6, heading: "Seceta atinge cetatea, ogorul și animalele", teaching: "Iuda jelește, porțile se ofilesc și oamenii trimit după apă fără să găsească. Pământul este crăpat, agricultorii își acoperă capetele, iar căprioara își abandonează puiul pentru că nu există iarbă. Măgarii sălbatici gâfâie cu ochii stinși. Criza este descrisă prin efectele ei concrete asupra întregii țări." },
    { from: 7, to: 9, heading: "Comunitatea își mărturisește nelegiuirea și cere ajutor pentru Numele lui Dumnezeu", teaching: "Poporul nu pretinde că merită ploaia. Fărădelegile mărturisesc împotriva lui, iar abaterile sunt multe. Rugăciunea îl numește pe DOMNUL speranța și Salvatorul lui Israel și Îl întreabă de ce pare străin sau călător, deși Numele Lui este peste popor." },
    { from: 10, to: 16, heading: "Dumnezeu respinge falsa asigurare a profeților care promit pace când El nu i-a trimis", teaching: "Judecata este menținută, iar Ieremia primește din nou porunca să nu transforme mijlocirea într-o negare a verdictului. Profetul răspunde că alți profeți spun poporului că nu va vedea sabie sau foamete. Dumnezeu afirmă că nu i-a trimis: ei profețesc vedenii mincinoase și înșelarea propriei inimi, iar sabia și foametea pe care le neagă îi vor ajunge." },
    { from: 17, to: 22, heading: "Ieremia plânge fără oprire și cere ca Dumnezeu să-Și amintească de legământ", teaching: "Profetul vede fecioara poporului zdrobită și descrie atât morții de sabie în câmp, cât și foametea din cetate. Întrebările rugăciunii nu ascund confuzia: de ce așteptarea păcii a adus teroare? Comunitatea își recunoaște răutatea și păcatele părinților și mărturisește că idolii neamurilor nu pot da ploaie; speranța rămâne în DOMNUL." },
  ]),
  15: c(15, [
    { from: 1, to: 4, heading: "Nici mijlocirea lui Moise și Samuel nu ar schimba verdictul acestei generații", teaching: "Dumnezeu folosește numele a doi mari mijlocitori ai istoriei lui Israel pentru a exprima cât de decisivă a devenit judecata. Poporul este trimis spre diferite forme de moarte și captivitate, iar cauza este legată de răul lui Manase în Ierusalim. Textul nu micșorează valoarea rugăciunii în general, ci descrie un verdict istoric ajuns la maturitate." },
    { from: 5, to: 9, heading: "Ierusalimul care a refuzat întoarcerea rămâne fără mângâietor", teaching: "Profetul întreabă cine va avea milă și cine se va opri să întrebe de pacea cetății. Dumnezeu spune că poporul L-a părăsit și a mers înapoi, iar repetatele amânări ale judecății nu au produs pocăință. Văduvele și mamele își pierd fiii, iar lumina zilei se transformă simbolic în întuneric." },
    { from: 10, to: 18, heading: "Ieremia își varsă durerea personală: cuvintele lui Dumnezeu i-au fost bucurie, dar singurătatea și rana îl apasă", teaching: "Profetul își blestemă ziua în care s-a născut și se vede ca om al conflictului, deși nu este creditor sau datornic. Dumnezeu îi promite că rămășița va avea bine, dar anunță și pierderea averilor. Ieremia amintește că a mâncat cuvintele lui Dumnezeu cu bucurie și poartă Numele Lui, dar nu poate sta în adunarea celor care petrec. Durerea îl face să întrebe dacă Dumnezeu va fi pentru el ca un izvor nesigur." },
    { from: 19, to: 21, heading: "Răspunsul îl cheamă pe profet să se întoarcă și să separe ce este prețios de ce este fără valoare", teaching: "Dumnezeu nu validează tot ce spune Ieremia în amărăciune. Îl cheamă la întoarcere și spune că dacă scoate lucrul prețios din cel fără valoare va rămâne gura Lui. Poporul trebuie să se întoarcă la profet, nu profetul la standardul poporului. El este făcut din nou zid de aramă și primește promisiunea izbăvirii." },
  ]),
  16: c(16, [
    { from: 1, to: 9, heading: "Viața personală a profetului devine semn: fără căsătorie, funeralii și ospețe într-o generație care intră în dezastru", teaching: "Ieremia primește porunca să nu se căsătorească și să nu aibă copii în acel loc, pentru că familiile vor fi lovite de moarte. Nu trebuie nici să intre în casa de doliu sau în casa ospățului, deoarece pacea, bunătatea, bucuria și vocea mirelui vor dispărea. Aceste restricții sunt o chemare profetică specifică lui Ieremia în contextul judecății, nu o regulă generală împotriva căsătoriei sau compasiunii." },
    { from: 10, to: 13, heading: "Exilul este explicat prin acumularea idolatriei și încăpățânării peste păcatele părinților", teaching: "Când oamenii întreabă de ce vine o asemenea nenorocire, răspunsul începe cu părinții care L-au părăsit pe Dumnezeu și au slujit altor dumnezei. Generația actuală a mers însă și mai departe, fiecare urmând încăpățânarea inimii. De aceea vor fi aruncați într-o țară pe care nu o cunosc și vor sluji acolo dumnezeilor străini." },
    { from: 14, to: 18, heading: "O nouă adunare din țara de nord va deveni o memorie de eliberare alături de Exod", teaching: "În mijlocul judecății apare o promisiune atât de mare încât formula jurământului nu se va mai referi numai la ieșirea din Egipt, ci și la scoaterea copiilor lui Israel din nord și din țările unde au fost izgoniți. Pescarii și vânătorii apar însă înainte ca instrumente ale găsirii păcatului ascuns: restaurarea nu este construită pe negarea vinovăției." },
    { from: 19, to: 21, heading: "Neamurile ajung să recunoască inutilitatea idolilor moșteniți", teaching: "Ieremia Îl numește pe DOMNUL puterea și refugiul lui, iar neamurile vin de la marginile pământului mărturisind că părinții lor au moștenit minciună și lucruri fără folos. Întrebarea centrală este dacă omul își poate face singur dumnezei; tocmai faptul că sunt făcuți de om arată că nu sunt Dumnezeu." },
  ]),
  17: c(17, [
    { from: 1, to: 4, heading: "Păcatul lui Iuda este gravat în inimă și lasă urme până la altare și moștenire", teaching: "Păcatul este comparat cu o inscripție făcută cu condei de fier și vârf de diamant pe tabla inimii și coarnele altarelor. Copiii își amintesc altarele și Așerele, iar bogățiile și moștenirea ajung pradă. Exilul apare ca pierdere a moștenirii încredințate." },
    { from: 5, to: 8, heading: "Încrederea ultimă în om usucă, iar încrederea în DOMNUL este ca un pom lângă apă", teaching: "Blestemat este omul care își face din carne braț și își îndepărtează inima de DOMNUL; el este comparat cu un arbust în pustiu. Omul care se încrede în Dumnezeu este ca un pom plantat lângă apă, cu rădăcini spre râu, care nu trăiește în panică la venirea căldurii și nu încetează să aducă rod." },
    { from: 9, to: 13, heading: "Inima este înșelătoare, iar Dumnezeu o cercetează și răsplătește după căi", teaching: "Inima omului este numită înșelătoare și bolnavă, ceea ce pune sub semnul întrebării autosuficiența introspecției. DOMNUL cercetează inima și încearcă adâncul omului. Bogăția dobândită nedrept este comparată cu o pasăre care clocește ouă pe care nu le-a făcut, iar cei care Îl părăsesc pe Izvorul apelor vii ajung scriși în țărână." },
    { from: 14, to: 18, heading: "Profetul cere vindecare și izbăvire când oamenii batjocoresc împlinirea cuvântului", teaching: "Ieremia Îl cheamă pe Dumnezeu să-l vindece și să-l salveze și spune că El este lauda lui. Oamenii îl întreabă ironic unde este cuvântul DOMNULUI și cer să vină. Profetul afirmă că nu a fugit de responsabilitatea de păstor și nu a dorit ziua nenorocirii, apoi cere ca Dumnezeu să fie refugiul lui." },
    { from: 19, to: 27, heading: "Poarta cetății devine locul unei confruntări despre Sabat și economia Ierusalimului", teaching: "Ieremia este trimis la porți să le spună regilor și locuitorilor să nu transporte poveri și să nu transforme Sabatul într-o zi obișnuită de comerț. Ascultarea ar permite continuitatea cetății și a închinării, iar refuzul ar aduce foc asupra porților. Sabatul este tratat ca expresie concretă a legământului, nu ca simplu simbol interior." },
  ]),
  18: c(18, [
    { from: 1, to: 10, heading: "La casa olarului, lutul refăcut arată libertatea lui Dumnezeu de a răspunde pocăinței sau răului", teaching: "Ieremia vede un vas care se strică în mâna olarului și este refăcut într-o altă formă. Dumnezeu aplică imaginea popoarelor: poate smulge și distruge, dar dacă un neam se întoarce de la rău, El Se poate îndura de nenorocirea anunțată; poate și zidi un neam, dar dacă acesta face rău, binele promis poate fi retras. Profeția este morală și relațională, nu fatalism mecanic." },
    { from: 11, to: 17, heading: "Iuda este chemat să se întoarcă, dar răspunde că își va urma propriile planuri", teaching: "Ieremia trebuie să anunțe că Dumnezeu pregătește un rău împotriva lor și să ceară fiecăruia să-și îndrepte calea. Răspunsul este explicit: «degeaba», vom umbla după planurile noastre. Profetul compară această abandonare a căilor vechi cu ceva nefiresc, precum zăpada care ar dispărea de pe munții înalți sau apele reci care s-ar seca fără motiv." },
    { from: 18, to: 23, heading: "Adversarii vor să-l lovească pe Ieremia cu limba, iar el își varsă înaintea lui Dumnezeu mânia și memoria mijlocirii sale", teaching: "Oamenii spun că preotul, înțeleptul și profetul nu vor dispărea dacă Ieremia este redus la tăcere și plănuiesc să-l lovească prin acuzații. Profetul amintește că a stat înaintea lui Dumnezeu ca să mijlocească pentru ei, apoi rostește o rugăciune severă de judecată. Textul păstrează fără cosmetizare mânia omului persecutat; nu o transformă într-o poruncă pentru răzbunarea personală a cititorului." },
  ]),
  19: c(19, [
    { from: 1, to: 5, heading: "Ieremia merge la Tofet cu bătrânii și denunță sângele nevinovat și sacrificarea copiilor", teaching: "Profetul cumpără un vas de lut și îi duce pe lideri la valea Ben-Hinom. Acolo anunță o nenorocire pentru că locul a fost umplut cu sânge nevinovat și au fost ridicate altare lui Baal pentru arderea copiilor. Dumnezeu spune explicit că asemenea practici nu au fost poruncite și nu au urcat în inima Lui." },
    { from: 6, to: 9, heading: "Valea Tofetului primește numele de Valea Măcelului", teaching: "Locul cultului violent va deveni loc al judecății. Planurile lui Iuda sunt golite, oamenii cad înaintea dușmanilor, iar asediul ajunge descris prin extrema canibalismului. Aceste imagini sunt avertismente despre oroarea războiului și a foametei, nu normalizare a violenței." },
    { from: 10, to: 13, heading: "Vasul spart în fața martorilor arată o ruină care nu mai poate fi reparată prin simplă cosmetizare", teaching: "Ieremia sparge vasul și spune că tot astfel poporul și cetatea vor fi zdrobite. Tofetul devine loc de îngropare din lipsă de spațiu, iar casele Ierusalimului sunt contaminate de cultul astrelor practicat pe acoperișuri. Semnul vizibil transformă mesajul într-o acțiune memorabilă." },
    { from: 14, to: 15, heading: "Mesajul din vale este repetat în curtea templului", teaching: "Profetul nu lasă avertismentul într-un loc periferic. Se întoarce în curtea Casei DOMNULUI și spune întregului popor că nenorocirea vine pentru că și-au înțepenit gâtul și au refuzat să asculte cuvintele lui Dumnezeu." },
  ]),
  20: c(20, [
    { from: 1, to: 6, heading: "Pașhur îl lovește și îl pune în butuci pe profet, dar primește numele «Groază din toate părțile»", teaching: "Preotul și supraveghetorul templului reacționează la profeție prin violență și îl pune pe Ieremia în butuci. A doua zi, profetul nu își retrage mesajul, ci îi schimbă simbolic numele lui Pașhur și anunță că el, prietenii și Iuda vor vedea teroarea, captivitatea și jefuirea cetății." },
    { from: 7, to: 10, heading: "Ieremia se simte copleșit de chemare, dar cuvântul devine foc în oase când încearcă să tacă", teaching: "Profetul vorbește extrem de sincer despre tensiunea chemării: mesajul îi aduce batjocură toată ziua, iar când decide să nu mai vorbească în Numele lui Dumnezeu, cuvântul devine ca un foc închis în oase. Nu poate suporta tăcerea, deși aude «Groază din toate părțile» și știe că oamenii pândesc să îl denunțe." },
    { from: 11, to: 13, heading: "În mijlocul urmăririi, Ieremia Îl numește pe DOMNUL războinic puternic și cântă pentru izbăvirea săracului", teaching: "Schimbarea de ton este bruscă: Dumnezeu este cu profetul, iar persecutorii nu vor birui. Ieremia cere Judecătorului drept să cerceteze inima și apoi cheamă la cântare pentru că DOMNUL izbăvește viața celui sărac din mâna celor răi." },
    { from: 14, to: 18, heading: "După laudă, profetul cade din nou în lamentația extremă a zilei nașterii", teaching: "Ieremia își blestemă ziua nașterii și pe omul care i-a adus tatălui vestea că s-a născut un fiu. El întreabă de ce a ieșit din pântece ca să vadă trudă și durere. Biblia păstrează astfel oscilația reală a unui om zdrobit de misiunea lui; lamentația nu este prezentată ca poruncă de autovătămare, ci ca exprimare a disperării înaintea lui Dumnezeu." },
  ]),
  21: c(21, [
    { from: 1, to: 7, heading: "Zedechia cere ajutor împotriva Babilonului, dar primește vestea că Dumnezeu luptă împotriva cetății", teaching: "Regele trimite la Ieremia când Nebucadnețar atacă și speră într-o intervenție minunată. Răspunsul inversează așteptarea: armele din mâna lui Iuda se întorc în interior, iar Dumnezeu Însuși spune că va lupta împotriva cetății din cauza judecății hotărâte. Locuitorii, regele și slujitorii sunt dați în mâna Babilonului." },
    { from: 8, to: 10, heading: "Calea vieții în acest moment istoric este predarea, nu apărarea simbolică a cetății", teaching: "Ieremia pune înaintea poporului calea vieții și calea morții. Cel care rămâne în cetate va muri de sabie, foamete sau ciumă, iar cel care iese și se predă caldeenilor își va păstra viața ca pradă. Aceasta este o instrucțiune profetică specifică asediului babilonian, nu o regulă universală că predarea militară este întotdeauna voia lui Dumnezeu." },
    { from: 11, to: 14, heading: "Casa lui David este încă chemată să facă dreptate în fiecare dimineață", teaching: "Chiar în pragul căderii, regele lui Iuda primește chemarea să judece drept și să salveze pe cel jefuit din mâna asupritorului. Furia divină este legată de faptele lor. Ierusalimul se vede sigur ca o cetate a văii și a stâncii, dar Dumnezeu spune că va cerceta după rodul faptelor și va aprinde un foc în pădurea ei." },
  ]),
  22: c(22, [
    { from: 1, to: 9, heading: "Casa lui David este chemată să lege conducerea de dreptate, protecția străinului, orfanului și văduvei", teaching: "Ieremia trebuie să meargă la palatul regelui și să ceară judecată dreaptă, salvarea celui jefuit și refuzul violenței împotriva străinului, orfanului și văduvei. Ascultarea ar permite continuitatea tronului și a cetății; refuzul transformă casa regală într-o pustietate. Neamurile care trec vor întreba de ce a făcut DOMNUL aceasta, iar răspunsul este abandonarea legământului și idolatria." },
    { from: 10, to: 12, heading: "Șalum nu se va întoarce din exil", teaching: "Poporul este chemat să nu plângă atât pentru mort, cât pentru regele dus departe, pentru că acesta nu își va mai vedea țara. Șalum, fiul lui Iosia, pleacă și moare în locul captivității. Schimbarea conducătorului nu inversează automat direcția istoriei." },
    { from: 13, to: 19, heading: "Ioiachim construiește lux pe muncă neplătită și este comparat cu dreptatea tatălui său Iosia", teaching: "Vaiul cade asupra celui care își zidește casa prin nedreptate și îl pune pe aproapele să muncească fără plată. Lemnul de cedru și camerele mari nu fac un rege. Ieremia amintește că Iosia mânca și bea, dar făcea dreptate și apăra cauza săracului; aceasta este numită cunoașterea lui Dumnezeu. Ioiachim, în schimb, își îndreaptă ochii spre câștig, sânge și asuprire, iar moartea lui este descrisă fără onoare." },
    { from: 20, to: 23, heading: "Ierusalimul este chemat să strige după iubiții politici pe care vântul îi va lua", teaching: "Cetatea este personificată urcând pe munți și strigând după aliații ei, dar acești «iubiți» sunt zdrobiți. Dumnezeu spune că a vorbit în vremea prosperității, iar răspunsul fusese refuzul ascultării încă din tinerețe. Păstorii sunt luați de vânt și cetatea ajunge rușinată." },
    { from: 24, to: 30, heading: "Conia este scos ca un inel de pecetluire și linia lui regală nu va mai prospera pe tronul lui David", teaching: "Chiar dacă Ieconia/Conia ar fi ca inelul de pe mâna dreaptă a lui Dumnezeu, este smuls și dat în mâna celor de care se teme. El și mama lui sunt aruncați într-o țară străină și nu se întorc. Profetul întreabă de ce este tratat ca un vas disprețuit și încheie spunând că niciunul dintre urmașii lui nu va prospera șezând pe tronul lui David și conducând din nou Iuda." },
  ]),
}
