import type { ExplainedOverlayChapter } from "../explainedOverlay.js"
import { VT_MAJOR_PROPHETS_FULL } from "../vtFullNarrativesMajorProphets.js"
import { sectionedTextualChapter } from "./textualChapterFactory.js"

const data = VT_MAJOR_PROPHETS_FULL.isaia
const c = (number: number, sections: Parameters<typeof sectionedTextualChapter>[3]) =>
  sectionedTextualChapter("Isaia", data, number, sections)

export const ISAIA_DEEPENED_02_20: Readonly<Partial<Record<number, ExplainedOverlayChapter>>> = {
  2: c(2, [
    { from: 1, to: 5, heading: "Sionul este văzut ca loc spre care popoarele vin să învețe căile DOMNULUI", teaching: "Viziunea privește spre o zi în care muntele Casei DOMNULUI este înălțat, iar neamurile vin să primească învățătură. Din Sion iese cuvântul, iar judecata lui Dumnezeu transformă uneltele războiului în unelte pentru viață. Chemarea imediată pentru casa lui Iacov este să umble în lumina DOMNULUI." },
    { from: 6, to: 9, heading: "Bogăția, puterea militară și idolii au umplut țara, dar nu au ridicat omul", teaching: "Isaia descrie o societate plină de argint, aur, cai, care și idoli făcuți de mâini. Abundența nu este condamnată izolată de context, ci alăturarea ei cu autosuficiența și închinarea la lucrul mâinilor arată o ordine în care omul se pleacă înaintea propriei creații." },
    { from: 10, to: 22, heading: "Ziua DOMNULUI coboară tot ce se înalță împotriva Lui", teaching: "Peșterile, stâncile, cedrii, munții, turnurile și corăbiile devin imagini ale lucrurilor înalte în care omul își caută siguranța. Ziua DOMNULUI smerește mândria și face idolii inutili. Finalul cere încetarea încrederii ultime în om, a cărui viață este numai o suflare." },
  ]),
  3: c(3, [
    { from: 1, to: 12, heading: "Ierusalimul pierde sprijinul, conducerea și ordinea socială", teaching: "Judecata este descrisă prin retragerea hranei, apei, războinicilor, judecătorilor și conducătorilor capabili. Lipsa maturității în conducere produce haos, iar oamenii ajung să caute pe oricine pare să aibă resurse pentru a conduce. Isaia leagă această dezordine de vorbirea și faptele poporului împotriva DOMNULUI." },
    { from: 13, to: 15, heading: "DOMNUL intră la judecată împotriva liderilor care au zdrobit pe săraci", teaching: "Dumnezeu nu judecă numai poporul în general, ci îi confruntă pe bătrâni și prinți pentru felul în care au administrat ceea ce li s-a încredințat. Via poporului a fost consumată, iar bunurile luate de la săraci se găsesc în casele lor. Puterea este evaluată prin modul în care tratează pe cei vulnerabili." },
    { from: 16, to: 26, heading: "Luxul fiicelor Sionului este pus sub imaginea pierderii și rușinii cetății", teaching: "Textul enumeră podoabe, parfumuri și haine pentru a descrie o cultură a afișării în momentul în care cetatea merge spre judecată. Nu este o condamnare universală a ornamentelor sau a femeilor, ci o profeție adresată unei elite a Sionului în contextul mândriei și colapsului. Finalul mută atenția spre porțile cetății care jelesc după pierderi." },
  ]),
  4: c(4, [
    { from: 1, to: 1, heading: "Criza lăsată de capitolul anterior produce o societate dezechilibrată", teaching: "Versetul continuă scena pierderilor din capitolul 3 și descrie mai multe femei căutând un singur bărbat pentru a îndepărta rușinea socială. Imaginea aparține unei lumi lovite de război și pierdere demografică, nu stabilește valoarea femeii prin statutul marital." },
    { from: 2, to: 4, heading: "Mlădița DOMNULUI și rămășița curățită deschid din nou speranța", teaching: "După judecată apare limbajul frumuseții și rodului. Cei rămași în Sion sunt numiți sfinți după ce DOMNUL spală murdăria și curăță vina prin duh de judecată și ardere. Speranța nu sare peste curățire, ci vine prin ea." },
    { from: 5, to: 6, heading: "Norul și focul evocă prezența protectoare a lui Dumnezeu peste Sion", teaching: "Norul ziua și focul noaptea trimit la memoria exodului și descriu prezența lui Dumnezeu peste adunarea Sionului. Acoperământul oferă umbră, refugiu și protecție. Textul promite prezență și adăpost în cadrul viziunii profetice, nu invulnerabilitate fizică automată pentru orice comunitate religioasă." },
  ]),
  5: c(5, [
    { from: 1, to: 7, heading: "Cântarea viei arată diferența dintre grija proprietarului și rodul rău al viei", teaching: "Via este plantată pe un deal roditor, curățată, sădită cu viță bună și echipată pentru rod. Totuși produce struguri răi. Isaia explică imaginea: via este casa lui Israel, iar rodul așteptat era dreptatea; în locul ei apar vărsarea de sânge și strigătul celor nedreptățiți." },
    { from: 8, to: 17, heading: "Acumularea fără limită și petrecerea fără atenție la lucrarea lui Dumnezeu duc la gol", teaching: "Primul val de «vai» atacă alipirea casă de casă și ogor de ogor până când ceilalți nu mai au loc. Urmează banchetele dominate de băutură și muzică în care lucrarea DOMNULUI nu este luată în seamă. Rezultatul este exil, foame și coborâre, în timp ce Dumnezeu este înălțat prin dreptate." },
    { from: 18, to: 23, heading: "Răul este tras ca o povară, iar valorile morale sunt inversate", teaching: "Oamenii sunt descriși trăgând nelegiuirea după ei și provocând ironic intervenția lui Dumnezeu. Vaiul cade asupra celor care numesc răul bine și binele rău, întunericul lumină și lumina întuneric. Autoproclamata înțelepciune, eroismul în băutură și achitarea vinovatului pentru mită sunt puse în aceeași criză morală." },
    { from: 24, to: 30, heading: "Refuzul învățăturii duce la judecată și la venirea unei puteri militare", teaching: "Așa cum focul consumă paiele, rădăcina celor care au respins Legea se usucă. Mânia este descrisă prin cutremur și prin ridicarea unui steag pentru un neam îndepărtat care vine rapid și disciplinat. Finalul capitolului lasă țara sub imaginea întunericului și a furtunii." },
  ]),
  7: c(7, [
    { from: 1, to: 9, heading: "În criza alianței Siria–Israel, Ahaz este chemat să nu se lase condus de frică", teaching: "Iuda tremură când află că Siria și Israel s-au unit împotriva lui. Isaia îl întâlnește pe Ahaz și îi spune să rămână liniștit: cei doi regi sunt descriși ca două capete de tăciuni fumegători. Planul lor nu va sta, iar chemarea centrală este la credință și stabilitate în cuvântul lui Dumnezeu." },
    { from: 10, to: 17, heading: "Semnul Emanuel vine în contextul refuzului lui Ahaz de a cere un semn", teaching: "DOMNUL îi oferă lui Ahaz libertatea de a cere un semn, dar regele răspunde într-o formă aparent pioasă. Isaia îl confruntă și anunță semnul copilului numit Emanuel. În contextul imediat, semnul privește criza politică apropiată; lectura creștină vede în formularea lui o împlinire mai deplină în nașterea lui Iisus, așa cum o citează Matei." },
    { from: 18, to: 25, heading: "Asiria chemată ca instrument va transforma țara într-un loc al pierderii", teaching: "Muștele Egiptului și albinele Asiriei sunt imagini ale puterilor chemate asupra țării. Briciul închiriat rade capul și barba, iar agricultura bogată este înlocuită de lapte, miere, spini și mărăcini. Ceea ce Ahaz caută ca soluție politică devine parte din judecata asupra lui Iuda." },
  ]),
  8: c(8, [
    { from: 1, to: 10, heading: "Maher-Șalal-Haș-Baz devine un semn viu despre prada apropiată și revărsarea Asiriei", teaching: "Numele copilului anunță rapiditatea cu care bogățiile Damascului și Samariei vor fi luate. Pentru că poporul respinge apele liniștite ale Siloamului, râul puternic al Asiriei se revarsă peste țară până aproape de gât. Totuși strigătul «Emanuel» amintește că planurile popoarelor nu au ultimul cuvânt." },
    { from: 11, to: 18, heading: "Isaia este chemat să se teamă de DOMNUL, nu de conspirațiile de care se teme poporul", teaching: "Profetul primește o avertizare să nu numească conspirație tot ce numește poporul astfel și să nu împărtășească fricile lui. DOMNUL trebuie sfințit ca obiect al fricii. El este sanctuar pentru unii și piatră de poticnire pentru alții. Isaia păstrează mărturia și așteaptă pe Dumnezeu împreună cu copiii care i-au fost dați ca semne." },
    { from: 19, to: 22, heading: "Căutarea morților în locul lui Dumnezeu duce la întuneric, nu la lumină", teaching: "Poporul este avertizat să nu caute mediumuri și spiritiști care șoptesc. Întrebarea profetului este directă: un popor trebuie să-L caute pe Dumnezeul său, nu pe cei morți pentru cei vii. Standardul este mărturia și învățătura; fără această lumină, oamenii ajung flămânzi, mânioși și împinși spre întuneric." },
  ]),
  10: c(10, [
    { from: 1, to: 4, heading: "Legile nedrepte care îi deposedează pe vulnerabili intră sub judecată", teaching: "Vaiul cade asupra celor care scriu hotărâri nedrepte și îi împiedică pe săraci să primească dreptate. Văduvele și orfanii devin pradă. Isaia întreabă ce vor face autorii acestor legi în ziua cercetării, când bogăția și puterea administrativă nu îi mai pot apăra." },
    { from: 5, to: 19, heading: "Asiria este nuiaua folosită de Dumnezeu, dar mândria ei este și ea judecată", teaching: "Asiria este numită toiagul mâniei, trimisă împotriva unui popor nelegiuit. Însă împăratul Asiriei nu își înțelege rolul și atribuie victoriile propriei puteri și înțelepciuni. Profetul întreabă dacă securea se poate lăuda împotriva celui care o mânuiește. Instrumentul judecății nu este scutit de judecată atunci când se înalță pe sine." },
    { from: 20, to: 27, heading: "O rămășiță se întoarce și nu se mai sprijină pe cel care a lovit-o", teaching: "Rămășița lui Israel este descrisă întorcându-se la Dumnezeul puternic și renunțând la sprijinul în puterea care o rănea. Judecata hotărâtă nu este negată, dar în interiorul ei rămâne promisiunea unei întoarceri. Iuda este chemat să nu se teamă definitiv de Asiria, pentru că povara ei va fi înlăturată." },
    { from: 28, to: 34, heading: "Marșul asirian spre Ierusalim este descris pas cu pas până când DOMNUL taie pădurea", teaching: "Orașele de pe traseu apar într-o succesiune rapidă, făcând amenințarea concretă și apropiată. Dușmanul ajunge să își scuture pumnul spre muntele Sionului, dar ultima imagine schimbă perspectiva: DOMNUL taie ramurile înalte și doboară pădurea. Mândria militară nu este de neatins." },
  ]),
  11: c(11, [
    { from: 1, to: 5, heading: "Din tulpina tăiată a lui Isai iese un vlăstar peste care odihnește Duhul DOMNULUI", teaching: "După imaginea pădurii doborâte din capitolul anterior, speranța apare dintr-o tulpină aparent redusă la nimic. Duhul înțelepciunii, priceperii, sfatului, puterii, cunoașterii și fricii de DOMNUL îl caracterizează pe conducător. El nu judecă după aparență, ci apără drept cauza celor săraci și vulnerabili." },
    { from: 6, to: 9, heading: "Pacea este descrisă prin reconcilierea unor făpturi care în mod normal se atacă", teaching: "Lupul, mielul, leopardul, iedul, vițelul și leul apar împreună, iar un copil îi conduce. Imaginile prezintă o ordine în care violența nu mai domină. Motivul este că pământul este plin de cunoașterea DOMNULUI precum apele acoperă marea." },
    { from: 10, to: 16, heading: "Rădăcina lui Isai devine steag pentru popoare, iar rămășița este adunată", teaching: "Neamurile caută rădăcina lui Isai, iar odihna lui este glorioasă. Dumnezeu adună din nou rămășița lui Israel din multe regiuni și îndepărtează rivalitatea dintre Efraim și Iuda. Imaginile despre drum și mare amintesc exodul și descriu o nouă adunare a poporului." },
  ]),
  12: c(12, [
    { from: 1, to: 3, heading: "Mânia se schimbă în mângâiere, iar mântuirea devine apă scoasă cu bucurie", teaching: "Cântarea începe recunoscând mânia lui Dumnezeu, dar continuă cu întoarcerea ei și cu mângâiere. Dumnezeu este numit mântuire, tărie și cântare. Imaginea izvoarelor mântuirii transformă salvarea într-un dar din care poporul scoate apă cu bucurie." },
    { from: 4, to: 6, heading: "Mulțumirea este făcută publică între popoare", teaching: "Numele DOMNULUI și faptele Lui trebuie făcute cunoscute între neamuri. Cântarea nu rămâne în interiorul comunității, ci proclamă măreția Lui pe tot pământul. Locuitorii Sionului sunt chemați să strige de bucurie pentru că Sfântul lui Israel este mare în mijlocul lor." },
  ]),
  13: c(13, [
    { from: 1, to: 5, heading: "Oracolul împotriva Babilonului începe cu adunarea unei armate pentru ziua mâniei", teaching: "Isaia vede un steag ridicat și războinici chemați pentru împlinirea judecății. Zgomotul mulțimilor și al împărățiilor este descris ca o armată pe care DOMNUL o strânge. Imperiul care pare de neclintit este așezat sub autoritatea lui Dumnezeu." },
    { from: 6, to: 16, heading: "Ziua DOMNULUI este descrisă prin groază cosmică și prăbușirea mândriei", teaching: "Oamenii își pierd puterea, iar soarele, luna și stelele intră în limbajul profetic al întunecării. Dumnezeu spune că va pedepsi răul și va opri mândria celor aroganți. Urmează imagini dure ale unui oraș cucerit; ele descriu violența războiului antic și judecata imperiului, nu dau permisiune cititorului să comită asemenea atrocități." },
    { from: 17, to: 22, heading: "Mezii sunt ridicați împotriva Babilonului, iar cetatea glorioasă devine pustie", teaching: "Puterea care nu poate fi cumpărată cu argint sau aur vine împotriva Babilonului. Cetatea numită gloria împărățiilor ajunge fără locuitori și este descrisă prin animale sălbatice și ruine. Contrastul dintre splendoarea imperială și pustiire subliniază cât de trecătoare este mândria politică." },
  ]),
  14: c(14, [
    { from: 1, to: 8, heading: "Eliberarea lui Iacov este urmată de odihnă și de cântecul împotriva asupritorului", teaching: "DOMNUL are din nou milă de Iacov și îi așază în țară. Cei care îi țineau robi își pierd puterea, iar asuprirea se oprește. Pământul este personificat ca intrând în odihnă, iar până și cedrii se bucură că tăietorul nu mai vine." },
    { from: 9, to: 23, heading: "Împăratul Babilonului coboară de la pretenția de a se înălța până la ruina comună a morții", teaching: "Șeolul este personificat întâmpinând regele care îi făcea pe alții să tremure. Tauntul despre «luceafărul dimineții» descrie mândria unui conducător care voia să se ridice deasupra stelelor și să fie asemenea Celui Preaînalt, dar ajunge în adânc. În lectura imediată este o batjocură profetică împotriva regelui Babilonului; tradițiile ulterioare au văzut și o analogie cu mândria satanică, dar aceasta nu trebuie să șteargă referentul istoric al textului." },
    { from: 24, to: 27, heading: "Planul DOMNULUI împotriva Asiriei nu poate fi anulat", teaching: "Oracolul se mută la Asiria și afirmă că ceea ce DOMNUL a hotărât va sta. Jugul ei va fi zdrobit în țară. Întrebarea finală accentuează suveranitatea: dacă mâna Lui este întinsă, cine o poate întoarce?" },
    { from: 28, to: 32, heading: "Filistia nu trebuie să se bucure prea repede de căderea unei puteri", teaching: "Moartea unui împărat al lui Iuda nu înseamnă că amenințarea a dispărut. Din rădăcina șarpelui vine o amenințare nouă. În contrast, săracii găsesc hrană și siguranță în lucrarea DOMNULUI, iar răspunsul pentru solii neamurilor este că El a întemeiat Sionul ca refugiu pentru cei asupriți ai poporului." },
  ]),
  15: c(15, [
    { from: 1, to: 4, heading: "Căderea Moabului este plânsă din cetate în cetate", teaching: "Ar și Chir sunt devastate, iar populația urcă la temple și locuri înalte ca să plângă. Tăierea părului, barba rasă și sacul sunt semne de doliu. Numele mai multor cetăți creează o hartă a lamentației în care strigătul nu rămâne local." },
    { from: 5, to: 9, heading: "Profetul însuși plânge pentru Moab în timp ce refugiații fug cu puținele bunuri rămase", teaching: "Isaia spune că inima lui strigă pentru Moab, ceea ce arată că anunțarea judecății nu cere bucurie rece în fața suferinței. Apele se usucă, iar oamenii își poartă bunurile peste pârâul sălciilor. Chiar încercarea de fugă este urmărită de noi pericole." },
  ]),
  16: c(16, [
    { from: 1, to: 5, heading: "Moab este chemat să caute adăpost și dreptate sub un tron întemeiat în bunătate", teaching: "Mielul trimis spre muntele Sionului și femeile fugare ale Moabului introduc o cerere de protecție. Textul cere sfat, dreptate și ascunderea fugarilor. În mijlocul crizei apare imaginea unui tron întemeiat în bunătate, ocupat de unul care caută dreptatea și este grabnic să facă ce este drept." },
    { from: 6, to: 12, heading: "Mândria Moabului este pusă lângă pierderea viilor și a cântecelor de recoltă", teaching: "Moabul este cunoscut pentru mândrie și aroganță, dar lăudăroșenia nu îl poate salva. Viile Hesbonului și Sibmei sunt lovite, iar bucuria recoltării dispare. Profetul își compară interiorul cu o harpă ce geme pentru Moab. Chiar urcarea la sanctuar nu produce izbăvirea pe care o caută." },
    { from: 13, to: 14, heading: "Judecata este fixată într-un termen apropiat", teaching: "Isaia spune că acesta este cuvântul deja rostit despre Moab, iar apoi adaugă un termen de trei ani. Gloria Moabului va fi disprețuită și rămășița va fi mică. Specificarea timpului face profeția concretă și verificabilă în lumea sa istorică." },
  ]),
  17: c(17, [
    { from: 1, to: 6, heading: "Damascul și gloria lui Israel sunt reduse la o rămășiță", teaching: "Damascul încetează să mai fie cetate, iar fortăreața lui Efraim este îndepărtată. Slava lui Iacov se subțiază ca un trup care pierde grăsime. Totuși imaginea recoltei lasă câteva spice și câteva măsline pe ramurile de sus: judecata nu șterge complet tema rămășiței." },
    { from: 7, to: 11, heading: "În ziua pierderii, omul privește din nou spre Creator și vede inutilitatea altarelor făcute de mâini", teaching: "Omul își întoarce privirea spre Făcător și nu mai privește cu aceeași încredere spre altarele și stâlpii sacri făcuți de mâini. Problema centrală este uitarea Dumnezeului mântuirii și a Stâncii refugiului. Chiar plantațiile frumoase și culturile atent lucrate ajung fără recoltă durabilă." },
    { from: 12, to: 14, heading: "Mulțimile popoarelor vuiesc ca marea, dar sunt alungate într-o singură seară", teaching: "Neamurile sunt comparate cu ape puternice și zgomotoase. Totuși Dumnezeu le mustră, iar ele fug ca pleava înaintea vântului. Seara este teroare, iar dimineața amenințarea a dispărut. Așa este descrisă partea celor care pradă poporul." },
  ]),
  18: c(18, [
    { from: 1, to: 3, heading: "Solii unei țări de dincolo de râurile Cușului sunt chemați să observe semnul ridicat", teaching: "Capitolul vorbește unei țări de aripi zumzăitoare și de soli trimiși pe ape. Descrierea geografică este dificilă, dar mesajul pentru locuitorii lumii este clar: când se ridică steagul și sună trâmbița, trebuie privit și ascultat." },
    { from: 4, to: 6, heading: "DOMNUL privește liniștit până la momentul exact în care taie ceea ce părea gata de rod", teaching: "Dumnezeu este comparat cu căldura senină și norul de rouă în timpul secerișului. Chiar înainte ca rodul să se coacă pe deplin, El taie lăstarii și ramurile. Imaginea descrie judecata venită la momentul stabilit de Dumnezeu, nu pasivitate sau lipsă de atenție." },
    { from: 7, to: 7, heading: "Poporul îndepărtat ajunge să aducă un dar la muntele Sionului", teaching: "Finalul inversează perspectiva: oamenii descriși la început prin distanță și putere ajung să aducă un dar DOMNULUI oștirilor la muntele Sionului. Oracolul se încheie astfel nu numai cu tăiere, ci și cu recunoașterea lui Dumnezeu." },
  ]),
  19: c(19, [
    { from: 1, to: 10, heading: "Egiptul este zguduit în religie, politică, natură și economie", teaching: "DOMNUL vine simbolic pe un nor, iar idolii Egiptului tremură. Conflictul intern, sfatul confuz, mediumurile și conducerea aspră se combină cu secarea Nilului. Pescarii, lucrătorii inului și cei care depind de apă pierd baza economică. Judecata atinge sistemul întreg, nu un singur sector." },
    { from: 11, to: 15, heading: "Înțelepciunea conducătorilor Egiptului este expusă ca neputincioasă", teaching: "Prinții Țoanului și sfetnicii faraonului se laudă cu moștenirea lor de înțelepciune, dar nu pot spune ce a hotărât DOMNUL. Conducătorii rătăcesc Egiptul și îl fac să se clatine ca un om amețit. Nici capul, nici coada, nici ramura, nici papura nu pot produce soluția." },
    { from: 16, to: 22, heading: "Frica se transformă treptat în cunoașterea și închinarea față de DOMNUL", teaching: "Egiptul ajunge să se teamă de lucrarea lui Dumnezeu și chiar de numele lui Iuda. Apoi viziunea merge mai departe: cetăți vorbesc limba Canaanului, apare un altar pentru DOMNUL, iar egiptenii strigă către El. Dumnezeu îi lovește și îi vindecă, iar ei se întorc la El. Judecata nu este ultimul cuvânt al oracolului." },
    { from: 23, to: 25, heading: "Egiptul, Asiria și Israel sunt așezate într-o imagine surprinzătoare de binecuvântare comună", teaching: "O șosea leagă Egiptul și Asiria, foști adversari imperiali, iar cele două popoare se închină împreună. Israel este al treilea alături de ele, ca binecuvântare în mijlocul pământului. Formulele finale sunt remarcabile: Egipt este numit poporul Meu, Asiria lucrarea mâinilor Mele și Israel moștenirea Mea." },
  ]),
  20: c(20, [
    { from: 1, to: 2, heading: "Căderea Așdodului introduce un semn profetic trăit de Isaia", teaching: "În timpul campaniei asiriene împotriva Așdodului, Isaia primește porunca să umble fără haina exterioară și desculț. Semnul profetic este public și costisitor pentru profet, făcând vizibil mesajul despre rușinea care urmează să vină asupra puterilor în care Iuda ar putea fi tentată să se încreadă." },
    { from: 3, to: 4, heading: "Trei ani de semn prevestesc captivitatea Egiptului și Cușului", teaching: "Isaia devine semn și prevestire pentru Egipt și Cuș. Regele Asiriei îi va duce captivi pe tineri și bătrâni în stare de rușine. Textul descrie practica umilitoare a captivității antice; nu o aprobă ca tratament legitim al prizonierilor." },
    { from: 5, to: 6, heading: "Cei care și-au pus speranța geopolitică în Egipt și Cuș rămân fără refugiu", teaching: "Locuitorii coastei sunt cuprinși de teamă când văd că puterea în care sperau este ea însăși capturată. Întrebarea finală — «cum vom scăpa noi?» — expune fragilitatea unei strategii construite pe un aliat pe care îl tratezi ca salvator ultim." },
  ]),
}
