import type { ExplainedOverlayChapter } from "../explainedOverlay.js"
import { VT_MAJOR_PROPHETS_FULL } from "../vtFullNarrativesMajorProphets.js"
import { sectionedTextualChapter } from "./textualChapterFactory.js"

const data = VT_MAJOR_PROPHETS_FULL.isaia
const c = (number: number, sections: Parameters<typeof sectionedTextualChapter>[3]) =>
  sectionedTextualChapter("Isaia", data, number, sections)

export const ISAIA_DEEPENED_21_39: Readonly<Partial<Record<number, ExplainedOverlayChapter>>> = {
  21: c(21, [
    { from: 1, to: 10, heading: "Vedenia despre pustiul mării anunță căderea Babilonului", teaching: "Isaia descrie o furtună venind din pustiu și este el însuși copleșit de ceea ce vede. O masă pregătită pentru ospăț este întreruptă de chemarea la arme. Străjerul privește până când vine mesajul decisiv: Babilonul a căzut, iar idolii lui sunt zdrobiți. Profetul transmite apoi poporului treierat ceea ce a auzit de la DOMNUL." },
    { from: 11, to: 12, heading: "Duma întreabă cât mai este din noapte, iar răspunsul rămâne deschis", teaching: "Un glas din Seir întreabă străjerul cât mai durează noaptea. Răspunsul spune că dimineața vine, dar și noaptea, apoi invită la o nouă întrebare și la întoarcere. Oracolul nu oferă o cronologie simplă, ci păstrează tensiunea dintre apropierea unei schimbări și persistența pericolului." },
    { from: 13, to: 17, heading: "Arabia este văzută prin fugari, apă oferită și gloria lui Chedar redusă", teaching: "Caravanele și fugarii din Arabia apar în pustiu, iar locuitorii Tema sunt chemați să aducă apă și pâine celor care fug de sabie. Într-un an, gloria lui Chedar va scădea, iar puținii arcași rămași vor fi numărați. Oracolul combină judecata cu responsabilitatea concretă față de refugiat." },
  ]),
  22: c(22, [
    { from: 1, to: 14, heading: "Valea vedeniei petrece în timp ce cetatea este chemată la plâns și pocăință", teaching: "Ierusalimul urcă pe acoperișuri și face zgomot, dar profetul vede conducători fugind și poporul prins fără luptă. Zidurile sunt cercetate, casele demolate pentru fortificații și apa este strânsă, însă oamenii nu privesc la Cel care a pregătit istoria cetății. Chemarea la plâns este întâmpinată cu ospăț și sloganul «să mâncăm și să bem, căci mâine vom muri», iar această împietrire este condamnată." },
    { from: 15, to: 19, heading: "Șebna este confruntat pentru folosirea funcției publice în construirea propriei glorii", teaching: "Dregătorul Șebna își pregătește un mormânt impunător într-un loc înalt, ca și cum poziția lui ar garanta o memorie durabilă. Isaia anunță că va fi aruncat din funcție și dus departe. Puterea administrativă nu este proprietate personală, iar prestigiul construit prin funcție poate fi pierdut." },
    { from: 20, to: 25, heading: "Eliakim primește responsabilitatea, dar chiar și un «țăruș sigur» are limite", teaching: "Eliakim este îmbrăcat cu haina și brâul funcției și primește cheia casei lui David, imagine a autorității administrative. El este descris ca tată pentru locuitorii Ierusalimului și ca un țăruș într-un loc sigur. Totuși finalul spune că țărușul poate fi tăiat când asupra lui este agățată o greutate excesivă. Niciun administrator omenesc nu este infinit." },
  ]),
  23: c(23, [
    { from: 1, to: 7, heading: "Tirul, centrul comerțului maritim, este chemat la jale", teaching: "Corăbiile din Tarsis aud că portul și casele Tirului au fost distruse. Sidonul, marea și negustorii sunt incluși în plângere, iar Egiptul este afectat de veste. Cetatea veche și cosmopolită, ale cărei picioare o purtau în țări îndepărtate, descoperă că rețeaua comercială nu o face invulnerabilă." },
    { from: 8, to: 14, heading: "Judecata asupra Tirului este legată de coborârea mândriei comerțului", teaching: "Isaia întreabă cine a hotărât aceasta împotriva cetății care dădea coroane și ai cărei negustori erau onorați. Răspunsul este că DOMNUL a hotărât să pângărească mândria și să coboare onoarea. Chiar fortăreața maritimă este expusă, iar Caldeea este amintită ca putere care transformă cetăți în ruine." },
    { from: 15, to: 18, heading: "După șaptezeci de ani, comerțul Tirului revine, dar câștigul este reorientat", teaching: "Tirul este uitat pentru o perioadă comparată cu zilele unui rege, apoi revine la activitatea comercială. Profetul folosește imaginea unei prostituate care își reia cântecul pentru a descrie recâștigarea clienților. Totuși profitul final este declarat consacrat DOMNULUI și folosit pentru hrană și îmbrăcăminte, nu pentru acumulare fără sfârșit." },
  ]),
  24: c(24, [
    { from: 1, to: 6, heading: "Pământul este golit, iar statutul social nu oferă excepții de la judecată", teaching: "Preot și popor, stăpân și slujitor, cumpărător și vânzător, creditor și datornic sunt puși pe același plan. Pământul se ofilește pentru că locuitorii au încălcat legile, au schimbat hotărârile și au rupt legământul. Judecata este prezentată ca răspuns moral, nu ca simplu accident natural." },
    { from: 7, to: 13, heading: "Vinul, muzica și orașul vesel își pierd puterea de a ascunde golul", teaching: "Vița se usucă, bucuria inimii dispare și instrumentele tac. Băutura nu mai produce aceeași plăcere, iar cetatea este numită pustie. Porțile sunt zdrobite și rămâne doar o imagine de cules după recoltă: puține măsline și câțiva struguri rămași." },
    { from: 14, to: 16, heading: "În mijlocul judecății se aud cântece despre gloria Celui Drept", teaching: "Dinspre mare și marginile pământului se aud glasuri care Îl slăvesc pe DOMNUL și vorbesc despre gloria Celui Drept. Totuși profetul însuși răspunde cu slăbiciune și durere pentru trădarea care continuă. Lauda și lamentația coexistă în aceeași viziune." },
    { from: 17, to: 23, heading: "Groaza, groapa și lațul culminează cu domnia DOMNULUI pe Sion", teaching: "Cel care scapă de o teamă cade în alta, iar pământul se clatină ca un om beat. Puterile de sus și regii pământului sunt adunați pentru judecată. Soarele și luna pălesc înaintea imaginii finale: DOMNUL oștirilor împărățește pe muntele Sion și în Ierusalim, în glorie înaintea bătrânilor Săi." },
  ]),
  25: c(25, [
    { from: 1, to: 5, heading: "Isaia laudă pe Dumnezeu pentru planuri vechi și pentru refugiu oferit celui sărac", teaching: "Profetul Îl laudă pentru lucrări minunate și planuri credincioase. Cetatea fortificată a celor puternici este redusă la ruină, iar popoarele ajung să-L onoreze. În contrast cu brutalitatea tiranilor, Dumnezeu este refugiu pentru sărac, adăpost în furtună și umbră împotriva arșiței." },
    { from: 6, to: 9, heading: "Ospățul pentru popoare este legat de îndepărtarea vălului, a morții și a lacrimilor", teaching: "Pe munte, DOMNUL pregătește un ospăț bogat pentru toate popoarele. El îndepărtează acoperământul care stă peste neamuri, înghite moartea și șterge lacrimile. Poporul răspunde: acesta este Dumnezeul în care am așteptat. Viziunea mută speranța de la simpla supraviețuire politică la înlăturarea dușmanului ultim al vieții." },
    { from: 10, to: 12, heading: "Moabul este coborât împreună cu fortificațiile și mândria lui", teaching: "Mâna DOMNULUI se odihnește pe munte, dar Moabul este călcat în imaginea paielor într-o groapă de gunoi. Orice încercare de a înota afară nu elimină mândria care este coborâtă. Zidurile înalte sunt aduse până la pământ." },
  ]),
  26: c(26, [
    { from: 1, to: 6, heading: "Cetatea tare are ziduri de mântuire și porți deschise pentru poporul credincios", teaching: "Cântarea lui Iuda vorbește despre o cetate a cărei siguranță vine din mântuire. Porțile se deschid pentru neamul drept care păstrează credincioșia. Mintea statornică este păzită în pace când se încrede în DOMNUL, Stânca veșnică, în timp ce cetatea înălțată a mândriei este coborâtă." },
    { from: 7, to: 10, heading: "Calea celui drept este nivelată, iar sufletul Îl dorește pe Dumnezeu chiar când răul primește har", teaching: "Profetul spune că drumul celui drept este drept și că numele și amintirea lui Dumnezeu sunt dorința inimii. Chiar dacă cel rău primește îndurare, el poate refuza să învețe dreptatea. Harul primit nu produce automat transformare când omul persistă în rău." },
    { from: 11, to: 15, heading: "Mâna ridicată a DOMNULUI va fi văzută, iar stăpânii străini nu au ultimul cuvânt", teaching: "Cei care nu văd lucrarea lui Dumnezeu vor fi confruntați cu ea. Poporul recunoaște că alți stăpâni l-au dominat, dar numai Numele DOMNULUI este mărturisit ca sursă a păcii. Puterile trecătoare dispar, în timp ce Dumnezeu mărește neamul și își extinde lucrarea." },
    { from: 16, to: 19, heading: "Necazul produce o rugăciune neputincioasă, dar apare speranța învierii", teaching: "Iuda este comparat cu o femeie în durerile nașterii care a produs doar vânt și nu a adus salvarea așteptată. După această recunoaștere a neputinței apare una dintre cele mai puternice afirmații ale capitolului: morții Tăi vor trăi, trupurile lor se vor ridica. Praful este chemat să se trezească și să cânte." },
    { from: 20, to: 21, heading: "Poporul este chemat să se ascundă până trece indignarea", teaching: "Imaginea finală cere intrarea în camere și închiderea ușilor pentru o vreme scurtă, deoarece DOMNUL iese să pedepsească nelegiuirea. Pământul nu va mai acoperi sângele vărsat, ci îl va descoperi. Răul ascuns este adus la lumină." },
  ]),
  27: c(27, [
    { from: 1, to: 1, heading: "Leviatanul, simbol al puterii haotice, este învins de sabia DOMNULUI", teaching: "Șarpele fugar și răsucit și balaurul din mare folosesc limbajul poetic al haosului și al dușmanului imposibil de stăpânit de om. DOMNUL îl pedepsește cu sabia Sa puternică. Textul afirmă dominația lui Dumnezeu asupra puterilor care par monstruoase." },
    { from: 2, to: 6, heading: "Via plăcută este păzită, udată și chemată să umple lumea cu rod", teaching: "Spre deosebire de via din Isaia 5, aici DOMNUL spune că păzește via, o udă și o apără zi și noapte. Mânia nu mai este accentul central; chiar spinii pot veni la El pentru pace. Iacov va prinde rădăcină, Israel va înflori și va umple lumea cu rod." },
    { from: 7, to: 11, heading: "Lovirea lui Israel este măsurată și orientată spre îndepărtarea idolatriei", teaching: "Profetul întreabă dacă Dumnezeu l-a lovit pe Israel la fel ca pe cei care l-au lovit. Judecata este descrisă ca măsurată și legată de înlăturarea vinovăției, concretizată prin zdrobirea pietrelor altarelor. Cetatea fortificată devine singuratică, iar lipsa de pricepere a poporului are consecințe." },
    { from: 12, to: 13, heading: "Un cules unul câte unul și o trâmbiță mare adună pe cei risipiți", teaching: "DOMNUL treieră de la Eufrat până la pârâul Egiptului și îi adună pe fiii lui Israel unul câte unul. Cei pierduți în Asiria și risipiți în Egipt aud o trâmbiță mare și vin să se închine pe muntele sfânt la Ierusalim." },
  ]),
  28: c(28, [
    { from: 1, to: 6, heading: "Cununa mândriei lui Efraim se ofilește, dar DOMNUL devine cunună pentru rămășiță", teaching: "Conducătorii și oamenii beți ai Efraimului sunt comparați cu o floare trecătoare pe capul unei văi roditoare. O furtună puternică o doboară. În contrast, pentru rămășița poporului DOMNUL devine cunună de frumusețe, duh de judecată și putere pentru cei care apără cetatea." },
    { from: 7, to: 13, heading: "Preoții și profeții amețiți batjocoresc învățătura simplă și ajung să nu o poată auzi", teaching: "Vinul a afectat până și conducerea religioasă, iar mesele sunt pline de vărsături. Oamenii ironizează mesajul profetului ca și cum ar fi lecții repetitive pentru copii. Răspunsul este că Dumnezeu le va vorbi prin buze străine, iar cuvântul simplu pe care l-au disprețuit va deveni pentru ei prilej de cădere." },
    { from: 14, to: 22, heading: "Conducătorii care cred că au făcut legământ cu moartea aud despre piatra de temelie și măsura dreptății", teaching: "Batjocoritorii din Ierusalim își imaginează că minciuna și alianțele îi vor proteja când vine urgia. DOMNUL răspunde așezând în Sion o piatră încercată și o temelie sigură, iar dreptatea devine linie de măsură. Refugiul minciunii este măturat, iar legământul cu moartea este anulat." },
    { from: 23, to: 29, heading: "Agricultorul nu ară și nu treieră la nesfârșit; fiecare lucrare are măsura ei", teaching: "Isaia cheamă ascultătorul să observe munca agricultorului. Pământul nu este arat continuu, iar semințele diferite sunt puse în locuri potrivite și treierate prin metode diferite. Înțelepciunea aceasta vine de la DOMNUL și ilustrează faptul că lucrarea Lui are scop, ordine și măsură, nu violență fără discernământ." },
  ]),
  29: c(29, [
    { from: 1, to: 8, heading: "Ariel este asediat, dar mulțimea atacatorilor dispare ca un vis", teaching: "Ierusalimul, numit Ariel, continuă ciclul sărbătorilor, dar este pus sub presiune și coborât până când glasul pare să vină din țărână. Armatele neamurilor îl înconjoară, însă la momentul intervenției ele devin ca praf și pleavă. Dușmanul care visează că mănâncă și se satură se trezește flămând: victoria lui aparentă nu devine realitate." },
    { from: 9, to: 12, heading: "Orbirea spirituală transformă revelația într-o carte sigilată", teaching: "Poporul este amețit fără vin, iar profeții și văzătorii nu mai oferă lumină. Vedenia devine ca o carte sigilată: cel care știe să citească spune că nu o poate deschide, iar cel care nu știe spune că nu poate citi. Problema nu este lipsa textului, ci incapacitatea de a-l primi." },
    { from: 13, to: 16, heading: "Buzele pot onora pe Dumnezeu în timp ce inima rămâne departe", teaching: "Poporul se apropie prin gură și Îl cinstește cu buzele, dar inima este departe, iar frica lui este redusă la porunci omenești învățate mecanic. Dumnezeu promite o lucrare care va face să piară înțelepciunea autosuficientă. Cei care își ascund planurile spun că nimeni nu îi vede, dar profetul compară această inversare cu lutul care pretinde că olarul nu l-a făcut." },
    { from: 17, to: 24, heading: "Ordinea este răsturnată din nou: surzii aud, orbii văd, iar cei smeriți se bucură", teaching: "Libanul devine câmp roditor, iar câmpul roditor pare pădure. Surzii aud cuvintele cărții și ochii orbilor ies din întuneric. Cei smeriți se bucură, în timp ce tiranul și batjocoritorul dispar. Cei care transformă procesul juridic într-o cursă și îl lipsesc pe cel drept de dreptate sunt confruntați. Casa lui Iacov ajunge să sfințească Numele lui Dumnezeu și cei rătăciți în duh dobândesc pricepere." },
  ]),
  30: c(30, [
    { from: 1, to: 7, heading: "Alianța cu Egiptul este numită plan făcut fără Dumnezeu", teaching: "Iuda coboară în Egipt pentru protecție fără să întrebe pe DOMNUL. Puterea faraonului va deveni rușine, iar solii care duc daruri prin deșert descoperă că poporul de la care așteaptă ajutor este inutil. Egiptul primește numele batjocoritor Rahab care stă nemișcat: multă reputație, puțin ajutor real." },
    { from: 8, to: 17, heading: "Poporul cere mesaje plăcute și refuză calea liniștii și a încrederii", teaching: "Isaia trebuie să scrie mărturia pentru un popor răzvrătit care nu vrea să audă Legea și le spune văzătorilor să nu vadă adevărul. Ei cer lucruri plăcute și iluzii. Dumnezeu spune că în întoarcere și odihnă ar fi salvarea, iar în liniște și încredere puterea, dar ei aleg fuga pe cai și ajung ei înșiși urmăriți." },
    { from: 18, to: 26, heading: "DOMNUL așteaptă să arate har, iar după disciplină vine vindecare și lumină", teaching: "Dumnezeu este descris așteptând să aibă milă, iar cei care Îl așteaptă sunt numiți fericiți. Poporul din Sion nu va plânge pentru totdeauna; învățătorul nu mai este ascuns și urechile aud calea de urmat. Idolii sunt aruncați, ploaia vine peste sămânță, animalele au pășune, iar lumina este intensificată în ziua vindecării." },
    { from: 27, to: 33, heading: "Venirea DOMNULUI este descrisă ca foc și furtună împotriva Asiriei", teaching: "Numele DOMNULUI vine de departe cu mânie, fum și foc, iar popoarele sunt cernute. Pentru popor, aceeași intervenție este însoțită de cântec și bucurie ca într-o sărbătoare. Asiria este lovită de glasul DOMNULUI, iar Tofetul este pregătit prin imaginea unui foc larg și adânc." },
  ]),
  31: c(31, [
    { from: 1, to: 3, heading: "Caii Egiptului sunt mulți, dar rămân carne, nu Dumnezeu", teaching: "Vaiul cade asupra celor care coboară în Egipt pentru cai, care și călăreți, dar nu privesc spre Sfântul lui Israel. Egiptul este om, nu Dumnezeu, iar caii lui sunt carne, nu duh. Când DOMNUL Își întinde mâna, atât ajutorul, cât și cel ajutat descoperă limita alianței." },
    { from: 4, to: 5, heading: "DOMNUL este comparat atât cu un leu care nu se teme, cât și cu păsări care protejează cuibul", teaching: "Două imagini diferite descriu hotărârea și protecția Lui. Leul nu este intimidat de mulțimea păstorilor chemați împotriva lui, iar păsările care zboară peste cuib exprimă apărare și trecere protectoare peste Ierusalim." },
    { from: 6, to: 9, heading: "Întoarcerea la Dumnezeu înseamnă și aruncarea idolilor, iar Asiria cade printr-o sabie care nu este omenească", teaching: "Fiii lui Israel sunt chemați să se întoarcă de la răzvrătire și să își arunce idolii de argint și aur. Asiria va cădea, dar textul subliniază că sabia decisivă nu este a unui simplu om. Stânca ei va trece de frică, iar Sionul rămâne locul focului DOMNULUI." },
  ]),
  32: c(32, [
    { from: 1, to: 8, heading: "Un rege drept și conducători drepți schimbă felul în care oamenii văd, aud și vorbesc", teaching: "Regele și prinții sunt descriși conducând cu dreptate, iar omul drept devine adăpost de vânt și apă într-un loc uscat. Ochii și urechile nu mai sunt închise, iar cei pripiți capătă pricepere. Nebunul nu mai este numit nobil doar prin convenție socială; caracterul lui este recunoscut prin vorbirea și acțiunile care rănesc pe sărac." },
    { from: 9, to: 14, heading: "Femeile nepăsătoare sunt chemate să tremure înaintea pierderii recoltei și a cetății", teaching: "Femeile care trăiesc în siguranță și nepăsare sunt avertizate că într-un an recolta și culesul vor eșua. Bucuria caselor și a cetății se transformă în doliu, iar palatul și orașul devin pustii. Ca și în Isaia 3, avertismentul este adresat unei elite complacente într-un moment de criză, nu femeilor ca grup universal." },
    { from: 15, to: 20, heading: "Turnarea Duhului schimbă pustiul în câmp roditor și produce dreptate, pace și siguranță", teaching: "Pustiul devine câmp, iar câmpul pare pădure când Duhul este turnat de sus. Dreptatea locuiește în ținut, iar lucrarea ei este pace și siguranță. Poporul locuiește în locuri liniștite chiar dacă pădurea și cetatea trec prin coborâre. Finalul îi numește fericiți pe cei care seamănă lângă ape." },
  ]),
  33: c(33, [
    { from: 1, to: 6, heading: "Distrugătorul va fi distrus, iar poporul cere har în fiecare dimineață", teaching: "Vaiul cade asupra celui care distruge fără să fi fost distrus și trădează fără să fi fost trădat: ceea ce face se va întoarce asupra lui. Comunitatea cere har și numește pe Dumnezeu brațul ei dimineața și salvarea în necaz. DOMNUL este înălțat, iar stabilitatea vremurilor vine din dreptate și din frica de El." },
    { from: 7, to: 9, heading: "Solii păcii plâng pentru un legământ rupt și pentru o țară care se ofilește", teaching: "Eroii și solii plâng, drumurile rămân pustii și călătorul dispare. Legământul este rupt și cetățile disprețuite. Libanul, Șaronul, Basanul și Carmelul sunt personificate ca ofilindu-se, arătând că violența politică atinge și economia, drumurile și peisajul." },
    { from: 10, to: 16, heading: "DOMNUL Se ridică, iar păcătosul întreabă cine poate locui lângă focul mistuitor", teaching: "Planurile dușmanilor produc paie și pleavă, iar propria lor suflare devine foc. Păcătoșii din Sion tremură și întreabă cine poate locui cu focul. Răspunsul descrie caracter: umblare dreaptă, vorbire sinceră, refuzul câștigului din asuprire și al mitei, închiderea urechii la planuri sângeroase și a ochilor la rău." },
    { from: 17, to: 24, heading: "Privirea spre Împărat și spre Sionul sigur se încheie cu vindecare și iertare", teaching: "Ochii îl vor vedea pe rege în frumusețea lui și o țară întinsă, iar frica de vechii inspectori și colectori dispare. Sionul este descris ca un cort care nu va fi mutat, iar DOMNUL este Judecător, Legiuitor și Împărat. Chiar dacă cetatea nu are râuri mari ca alte capitale, prezența Lui este apărare. Finalul spune că locuitorul nu va mai spune «sunt bolnav», iar nelegiuirea poporului este iertată." },
  ]),
  34: c(34, [
    { from: 1, to: 4, heading: "Națiunile sunt chemate să audă o judecată descrisă în limbaj cosmic", teaching: "Pământul și tot ce îl umple sunt chemate să asculte. Mânia DOMNULUI este împotriva neamurilor, iar căderea lor este descrisă prin trupuri, sânge și munți topiți. Cerurile se strâng ca un sul și oștirea lor cade ca frunzele. Limbajul profetic amplifică dimensiunea judecății dincolo de un singur război local." },
    { from: 5, to: 10, heading: "Edomul devine exemplul concret al zilei răzbunării pentru cauza Sionului", teaching: "Sabia coboară asupra Edomului, iar Boțra este locul unei mari jertfe simbolice. Animalele de jertfă și sângele descriu severitatea judecății. Ziua este numită ziua răzbunării DOMNULUI și anul răsplătirii pentru cauza Sionului. Acest limbaj lasă judecata în mâna lui Dumnezeu și nu autorizează răzbunarea privată." },
    { from: 11, to: 15, heading: "Cetatea devine locuită de animale sălbatice în locul elitei omenești", teaching: "Pelicanul, ariciul, bufnița și corbul ocupă spațiul unde fusese puterea. Linia de măsură a pustietății este întinsă peste cetate, nobilii dispar și palatele sunt umplute de spini. Șacalii și alte animale își găsesc loc acolo, accentuând inversarea completă a ordinii urbane." },
    { from: 16, to: 17, heading: "Cartea DOMNULUI este chemată ca martor al împlinirii", teaching: "Cititorii sunt invitați să caute în carte și să vadă că nimic din cele anunțate nu lipsește. Gura DOMNULUI a poruncit, iar Duhul Lui a adunat. El a împărțit locurile animalelor prin sorț, iar pustietatea este descrisă ca o stare stabilă în cadrul oracolului." },
  ]),
  35: c(35, [
    { from: 1, to: 2, heading: "Pustiul înflorește și primește gloria Libanului, Carmelului și Șaronului", teaching: "Deșertul și ținutul uscat sunt personificate ca bucurându-se și înflorind. Locul lipsei primește frumusețea celor mai roditoare regiuni și vede gloria și măreția DOMNULUI. Restaurarea este descrisă nu numai prin revenirea oamenilor, ci prin transformarea mediului lor." },
    { from: 3, to: 4, heading: "Mâinile slabe și genunchii tremurători sunt întăriți prin vestea venirii lui Dumnezeu", teaching: "Cei puternici sunt chemați să întărească pe cei slabi și să spună inimilor temătoare să fie tari. Motivul nu este negarea pericolului, ci promisiunea că Dumnezeu vine cu judecată și salvare. Curajul este ancorat în intervenția Lui." },
    { from: 5, to: 7, heading: "Orbii văd, surzii aud, șchiopii sar, iar pustiul primește apă", teaching: "Vindecarea oamenilor și restaurarea creației sunt puse împreună. Ochii și urechile se deschid, șchiopul sare și limba mutului cântă. În pustiu izbucnesc ape, nisipul fierbinte devine iaz și locul șacalilor produce vegetație." },
    { from: 8, to: 10, heading: "Calea sfințeniei este un drum sigur pentru cei răscumpărați care se întorc în Sion", teaching: "Un drum este numit Calea Sfințeniei și este separat de necurăție și de primejdia fiarelor. Chiar cel nepriceput nu se rătăcește pe el când aparține călătorilor răscumpărați. Cei eliberați se întorc în Sion cu cântări, iar bucuria veșnică înlocuiește durerea și suspinul." },
  ]),
  36: c(36, [
    { from: 1, to: 10, heading: "Rabșache atacă încrederea lui Iuda și reinterpretează religios invazia asiriană", teaching: "În anul al paisprezecelea al lui Ezechia, Asiria cucerește cetățile întărite și trimite un reprezentant la Ierusalim. El întreabă pe ce se bazează încrederea regelui: strategie, Egipt sau DOMNUL. Rabșache folosește chiar reforma religioasă a lui Ezechia împotriva lui și pretinde că DOMNUL i-a spus să distrugă țara. Propaganda amestecă fapte reale, intimidare și pretenții teologice." },
    { from: 11, to: 12, heading: "Solii lui Ezechia cer aramaica, dar Rabșache vrea ca mesajul de frică să ajungă la populație", teaching: "Oficialii cer ca discuția să continue într-o limbă diplomatică pe care oamenii de pe zid nu o înțeleg. Rabșache refuză tocmai pentru că publicul este ținta lui. El folosește o imagine vulgară despre foamea și setea unui asediu pentru a intensifica frica și a rupe încrederea dintre cetățeni și conducerea lor." },
    { from: 13, to: 20, heading: "Asiria promite confort în schimbul capitulării și compară pe DOMNUL cu zeii cetăților deja învinse", teaching: "Rabșache strigă în limba poporului să nu creadă promisiunea lui Ezechia că DOMNUL îi va salva. El oferă pace temporară, hrană și apoi deportare într-o țară asemănătoare cu a lor. Argumentul final este lista zeilor care nu și-au salvat țările. Eroarea lui este să trateze pe DOMNUL ca încă un zeu local măsurat prin succesele militare precedente." },
    { from: 21, to: 22, heading: "Poporul păstrează tăcerea la porunca regelui, iar solii se întorc cu hainele sfâșiate", teaching: "Nimeni nu răspunde propagandei publice, pentru că Ezechia le poruncise să tacă. Eliachim, Șebna și Ioah se întorc cu hainele rupte și îi transmit regelui cuvintele. Capitolul se încheie înaintea răspunsului, lăsând criza deschisă." },
  ]),
  37: c(37, [
    { from: 1, to: 4, heading: "Ezechia răspunde blasfemiei prin doliu, templu și cerere de rugăciune", teaching: "Când aude cuvintele, regele își sfâșie hainele, se îmbracă în sac și intră în Casa DOMNULUI. Trimite conducători și preoți la Isaia și descrie ziua ca necaz și rușine. El cere ca profetul să se roage pentru rămășița care mai există, în loc să răspundă doar prin propagandă politică." },
    { from: 5, to: 7, heading: "Isaia spune să nu se teamă de cuvintele slujitorilor Asiriei", teaching: "Răspunsul profetic este scurt: cuvintele de hulă nu trebuie să devină autoritatea care definește situația. Dumnezeu va pune un duh în regele Asiriei, acesta va auzi o veste, se va întoarce în țara lui și va cădea acolo prin sabie." },
    { from: 8, to: 20, heading: "O nouă scrisoare de intimidare este dusă de Ezechia înaintea DOMNULUI", teaching: "Asiria reia argumentul că niciun zeu al popoarelor nu și-a salvat țara. Ezechia primește scrisoarea, o citește și o întinde înaintea DOMNULUI. Rugăciunea lui recunoaște că zeii aruncați în foc nu erau dumnezei, ci lucrări ale mâinilor. Cererea lui este ca salvarea să facă toate împărățiile să cunoască faptul că DOMNUL singur este Dumnezeu." },
    { from: 21, to: 35, heading: "Răspunsul lui Dumnezeu confruntă mândria lui Sanherib și promite apărarea Ierusalimului", teaching: "Isaia transmite un oracol în care fiica Sionului îl disprețuiește pe invadator. Sanherib se laudă cu munți urcați, păduri tăiate și ape secate, dar Dumnezeu spune că aceste lucruri au stat în planul Lui și că știe când împăratul se ridică și se așază. Un semn agricol este dat lui Ezechia, rămășița va prinde rădăcină, iar Asiria nu va intra în cetate și nu va ridica rampă împotriva ei." },
    { from: 36, to: 38, heading: "Armata asiriană este lovită, iar Sanherib moare mai târziu în templul propriului zeu", teaching: "Îngerul DOMNULUI lovește tabăra asiriană, iar dimineața sunt găsite multe trupuri. Sanherib se întoarce la Ninive. Mai târziu, în timp ce se închină în templul lui Nisroc, este ucis de doi dintre fiii săi, iar un alt fiu îi urmează la tron. Regele care îl comparase pe DOMNUL cu zeii învinși moare în casa propriului zeu." },
  ]),
  38: c(38, [
    { from: 1, to: 8, heading: "Boala lui Ezechia, rugăciunea și semnul umbrei care se întoarce", teaching: "Isaia îi spune regelui să își pună casa în ordine pentru că va muri. Ezechia se întoarce spre perete și plânge, amintindu-și umblarea sa înaintea lui Dumnezeu. Înainte ca narațiunea să continue, vine răspunsul: încă cincisprezece ani de viață și izbăvire de Asiria. Semnul este întoarcerea umbrei pe treptele lui Ahaz." },
    { from: 9, to: 14, heading: "Cântarea regelui descrie moartea ca tăiere a vieții și rugăciunea ca geamăt", teaching: "Ezechia își amintește starea din timpul bolii: credea că va fi lipsit de restul anilor, că locuința lui va fi strânsă ca un cort de păstor și viața tăiată ca țesătura unui țesător. Glasul lui devine ca al unei rândunici și geme ca un porumbel. Psalmul personal nu minimalizează frica de moarte." },
    { from: 15, to: 20, heading: "Vindecarea îl face pe Ezechia să interpreteze amărăciunea în lumina iertării și a laudei", teaching: "Regele spune că Dumnezeu i-a vorbit și a lucrat, iar el va umbla smerit după amărăciunea sufletului. Viața este legată de cuvintele și lucrarea lui Dumnezeu, iar păcatele sunt descrise ca aruncate înapoia Lui. Cei vii pot lăuda și transmite fidelitatea lui Dumnezeu copiilor, de aceea Ezechia promite cântări în Casa DOMNULUI." },
    { from: 21, to: 22, heading: "Tratamentul cu smochine și întrebarea despre semn rămân parte din relatarea vindecării", teaching: "Isaia poruncește să se pună o turtă de smochine pe bubă, iar regele se vindecă. Ezechia întrebase ce semn va confirma că va urca din nou la Casa DOMNULUI. Textul ține împreună mijlocul concret folosit și semnul divin fără a transforma turta de smochine într-un tratament universal pentru boli moderne." },
  ]),
  39: c(39, [
    { from: 1, to: 2, heading: "Ezechia primește solii Babilonului și le arată întreaga lui avere", teaching: "Merodac-Baladan trimite scrisori și un dar după ce aude de boala și vindecarea regelui. Ezechia se bucură de soli și le arată argintul, aurul, mirodeniile, uleiul, arsenalul și tot ce se afla în tezaure. Nimic nu rămâne ascuns de delegație." },
    { from: 3, to: 4, heading: "Întrebările lui Isaia îl obligă pe rege să recunoască exact ce a expus", teaching: "Profetul întreabă cine erau oamenii, de unde au venit și ce au văzut. Ezechia răspunde că au venit din Babilon și că au văzut totul. Dialogul scoate la lumină nu doar vizita diplomatică, ci lipsa de prudență a regelui." },
    { from: 5, to: 8, heading: "Bogățiile și urmașii vor ajunge în Babilon, iar Ezechia se gândește la pacea din timpul său", teaching: "Isaia anunță că tot ce se află în casă și ce au strâns părinții va fi dus în Babilon, iar unii dintre fiii regelui vor sluji în palatul babilonian. Ezechia spune că cuvântul DOMNULUI este bun și se gândește la pace și adevăr în zilele lui. Finalul pregătește exilul care va domina partea următoare a istoriei lui Iuda." },
  ]),
}
