import type { ExplainedOverlayChapter } from "../explainedOverlay.js"
import { VT_MAJOR_PROPHETS_FULL } from "../vtFullNarrativesMajorProphets.js"
import { sectionedTextualChapter } from "./textualChapterFactory.js"

const data = VT_MAJOR_PROPHETS_FULL.isaia
const c = (number: number, sections: Parameters<typeof sectionedTextualChapter>[3]) =>
  sectionedTextualChapter("Isaia", data, number, sections)

export const ISAIA_DEEPENED_41_65: Readonly<Partial<Record<number, ExplainedOverlayChapter>>> = {
  41: c(41, [
    { from: 1, to: 7, heading: "Insulele sunt chemate la judecată, iar națiunile își întăresc idolii una pe alta", teaching: "DOMNUL cheamă popoarele să tacă și să-și prezinte cauza. El întreabă cine a ridicat cuceritorul din răsărit și cine conduce generațiile. Răspunsul este Dumnezeu, Cel dintâi și Cel de pe urmă. În contrast, popoarele se încurajează reciproc și își fixează idolii cu cuie ca să nu se clatine." },
    { from: 8, to: 16, heading: "Israel este numit rob ales și primește porunca repetată să nu se teamă", teaching: "Iacov este ales, urmaș al lui Avraam și chemat de la marginile pământului. Dumnezeu spune că nu l-a lepădat și repetă: nu te teme, Eu sunt cu tine. Vrăjmașii care se ridică împotriva lui vor fi făcuți de nimic, iar poporul slab este comparat cu o unealtă de treierat nouă, în timp ce bucuria lui rămâne în DOMNUL." },
    { from: 17, to: 20, heading: "Săracii care caută apă primesc râuri, izvoare și copaci în pustiu", teaching: "Cei săraci și nevoiași își caută apa cu limba uscată, iar Dumnezeu promite că îi va asculta. Înălțimile goale primesc râuri, valea izvoare și pustiul o diversitate de copaci. Scopul declarat este ca oamenii să vadă și să înțeleagă că mâna DOMNULUI a făcut aceasta." },
    { from: 21, to: 29, heading: "Idolii sunt chemați să prezică și să explice, dar nu pot răspunde", teaching: "DOMNUL îi cheamă pe dumnezeii neamurilor să își aducă argumentele, să spună ce s-a întâmplat înainte și ce va veni. Incapacitatea lor de a vorbi sau lucra arată că sunt nimic. În contrast, Dumnezeu ridică un conducător din nord și trimite Sionului vestea. Sfetnicii idolilor nu au niciun răspuns real." },
  ]),
  43: c(43, [
    { from: 1, to: 7, heading: "Creatorul și Răscumpărătorul îl cheamă pe Israel pe nume și îl adună din toate direcțiile", teaching: "Israel nu trebuie să se teamă pentru că aparține Celui care l-a creat și răscumpărat. Apele și focul nu sunt negate, dar nu au ultimul cuvânt asupra poporului. Egipt, Cuș și Seba sunt menționate în limbajul răscumpărării istorice, iar fiii și fiicele sunt adunați de la răsărit, apus, nord și sud pentru gloria lui Dumnezeu." },
    { from: 8, to: 13, heading: "Israel este chemat ca martor că înainte și după DOMNUL nu există alt salvator", teaching: "Poporul cu ochi și urechi este adus împreună cu neamurile într-un cadru de mărturie. Dumnezeu întreabă cine poate anunța lucrurile dinainte. Israel este martorul ales ca să cunoască și să creadă că El este Dumnezeu. Nu există alt salvator, iar nimeni nu poate smulge din mâna Lui." },
    { from: 14, to: 21, heading: "Exodul vechi pregătește imaginea unei lucrări noi în pustiu", teaching: "Răscumpărătorul anunță că Babilonul va fi coborât și își amintește de drumul prin mare în care carele și caii au fost stinși. Totuși poporul este chemat să nu rămână blocat în trecut: Dumnezeu face un lucru nou, deschide drum în pustiu și râuri în deșert pentru poporul format să vestească lauda Lui." },
    { from: 22, to: 28, heading: "Israel L-a obosit pe Dumnezeu prin păcat, dar El spune că șterge fărădelegile pentru Numele Său", teaching: "Poporul nu L-a chemat cu adevărat și a transformat cultul într-o povară de păcat. Dumnezeu subliniază că nu avea nevoie de darurile lor ca să fie satisfăcut. Totuși El este Cel care șterge fărădelegile și nu își amintește păcatele. În același timp, istoria de vinovăție a părinților și conducătorilor explică judecata asupra lui Iacov." },
  ]),
  44: c(44, [
    { from: 1, to: 5, heading: "Iacov ales primește promisiunea apei și a Duhului peste urmași", teaching: "Robul Israel este chemat din nou să nu se teamă. Dumnezeu, Cel care l-a format din pântece, promite apă peste pământul însetat și Duhul Său peste urmași. Ei vor crește ca sălciile lângă apă și își vor declara apartenența la DOMNUL în mod deschis." },
    { from: 6, to: 8, heading: "Împăratul și Răscumpărătorul lui Israel declară că nu există alt Dumnezeu", teaching: "DOMNUL se numește Cel dintâi și Cel de pe urmă și provoacă orice rival să anunțe istoria și viitorul. Poporul nu trebuie să se teamă pentru că a auzit și a fost făcut martor. Întrebarea «este altă Stâncă?» primește răspunsul negativ al textului." },
    { from: 9, to: 20, heading: "Satira idolatriei arată omul folosind același lemn pentru foc și pentru un zeu", teaching: "Meșteșugarul lucrează până obosește, tâmplarul măsoară și modelează o figură omenească, iar copacul crescut cu ploaia devine material. Dintr-o parte omul face foc, își coace pâinea și se încălzește; din rest face un idol și i se închină. Absurditatea este că omul nu își pune întrebarea dacă lucrul format de mâna lui poate fi Dumnezeu." },
    { from: 21, to: 23, heading: "Israel este chemat să-și amintească de Creatorul care îi șterge păcatele ca un nor", teaching: "După satira idolilor, Dumnezeu îi spune lui Iacov să își amintească cine l-a format și să se întoarcă la El. Fărădelegile sunt șterse ca norul și ceața. Cerul, pământul, munții și pădurile sunt chemate să cânte pentru răscumpărarea lui Iacov." },
    { from: 24, to: 28, heading: "Creatorul care zădărnicește semnele mincinoase îl numește pe Cirus ca păstor pentru restaurarea Ierusalimului", teaching: "DOMNUL se prezintă ca Răscumpărător și Creator, Cel care întinde cerurile și face de rușine prezicerile mincinoase. El confirmă cuvântul slujitorilor Săi despre reconstruirea cetăților lui Iuda și secarea adâncului. Cirus este numit explicit păstorul care va împlini plăcerea Lui și va spune Ierusalimului și templului să fie reconstruite." },
  ]),
  45: c(45, [
    { from: 1, to: 7, heading: "Cirus este numit uns pentru o misiune istorică, deși nu Îl cunoaște pe DOMNUL", teaching: "Dumnezeu îl numește pe Cirus «unsul Meu» și spune că îi supune neamuri, deschide porți și îi dă comori ascunse. Scopul este ca el și lumea să cunoască faptul că DOMNUL, Dumnezeul lui Israel, este Cel care îl cheamă pe nume. Textul spune explicit că Cirus nu Îl cunoaște, deci titlul descrie rolul în planul istoric, nu sfințenia personală a regelui persan." },
    { from: 8, to: 13, heading: "Creatorul nu poate fi pus la judecată de lutul care Îl întreabă de ce lucrează astfel", teaching: "Cerul și pământul sunt chemate să producă dreptate și mântuire. Apoi profetul avertizează împotriva celui care se ceartă cu Făcătorul său ca un ciob între cioburi. Lutul nu poate pretinde olarului că nu știe ce face. Dumnezeu spune că El a făcut pământul și omul și că tot El l-a ridicat pe Cirus pentru reconstruirea cetății și eliberarea captivilor." },
    { from: 14, to: 17, heading: "Bogățiile și popoarele se pleacă, iar idolii sunt rușinați în fața Dumnezeului care Se ascunde și mântuiește", teaching: "Egiptul, Cușul și sabeenii apar venind și recunoscând că Dumnezeu este cu Israel și că nu există altul. Profetul numește pe Dumnezeu unul care Se ascunde, în timp ce făuritorii idolilor pleacă rușinați. Israel primește promisiunea unei mântuiri care nu se termină în rușine." },
    { from: 18, to: 25, heading: "Creatorul pământului cheamă marginile lumii să se întoarcă la El pentru salvare", teaching: "Dumnezeu spune că a creat pământul ca să fie locuit și că nu a vorbit în ascuns despre căutarea Lui. Supraviețuitorii neamurilor sunt chemați să compare idolii purtați cu Dumnezeul care poate salva. Invitația devine universală: întoarceți-vă la Mine și fiți salvați, toate marginile pământului. Jurământul final spune că orice genunchi se va pleca și orice limbă va mărturisi dreptatea și puterea Lui." },
  ]),
  46: c(46, [
    { from: 1, to: 2, heading: "Bel și Nebo sunt purtați ca poveri de animalele care nu mai pot duce greutatea lor", teaching: "Zeii Babilonului se pleacă și sunt încărcați pe animale în timpul fugii. În loc să salveze pe cei care îi poartă, ei înșiși devin povară și merg în captivitate. Imaginea răstoarnă ideea unui zeu protector: idolul trebuie transportat de om și animal." },
    { from: 3, to: 7, heading: "Dumnezeu contrastează idolii purtați cu El Însuși, Cel care poartă pe Israel de la pântece până la bătrânețe", teaching: "Casa lui Iacov este chemată să asculte: Dumnezeu spune că a purtat-o din pântece și o va purta până la căruntețe. El a făcut-o și o va salva. În contrast, oamenii scot aur din pungă, plătesc un meșteșugar și apoi poartă statuia pe umăr până la locul ei, unde rămâne nemișcată și nu răspunde când este strigată." },
    { from: 8, to: 13, heading: "Cel care spune sfârșitul de la început aduce aproape dreptatea și mântuirea", teaching: "Răzvrătiții sunt chemați să își amintească lucrurile vechi și unicitatea lui Dumnezeu. El declară de la început ce va fi la sfârșit și cheamă din răsărit omul care împlinește planul Său. Ce a spus va aduce la îndeplinire, iar dreptatea și mântuirea nu sunt lăsate la o distanță nedefinită." },
  ]),
  47: c(47, [
    { from: 1, to: 7, heading: "Fiica Babilonului coboară de pe tron și descoperă vulnerabilitatea pe care puterea o ascundea", teaching: "Cetatea este personificată ca o fecioară regală chemată să stea în țărână fără tron. Munca servilă, rușinea și pierderea titlurilor înlocuiesc confortul. Dumnezeu spune că a dat poporul Său în mâna Babilonului, dar cetatea nu a arătat milă și a pus jug greu chiar pe bătrâni. Puterea primită pentru o vreme nu îi oferea dreptul la cruzime." },
    { from: 8, to: 11, heading: "Siguranța arogantă «eu și nimeni altul» este confruntată prin pierdere neașteptată", teaching: "Babilonul se vede ca stăpână a plăcerilor, sigură că nu va deveni văduvă și nu își va pierde copiii. Înțelepciunea și cunoașterea au devenit motive de autosuficiență. Tocmai aceste pierderi vin într-o zi, iar răul apare fără ca vrăjitoriile și calculele cetății să îl poată evita." },
    { from: 12, to: 15, heading: "Vrăjitoriile, astrologii și sfetnicii nu pot salva cetatea de focul judecății", teaching: "Babilonul este invitat ironic să continue cu descântecele practicate din tinerețe și cu mulțimea sfetnicilor. Cei care împart cerul și prezic după stele sunt chemați să salveze, dar devin ca paiele arse. Nu rămâne nici măcar focul util la care să te încălzești; fiecare merge pe drumul lui și nimeni nu salvează." },
  ]),
  48: c(48, [
    { from: 1, to: 8, heading: "Israel folosește Numele lui Dumnezeu, dar este descris ca încăpățânat și incapabil să pretindă idolilor meritul profeției", teaching: "Casa lui Iacov jură pe Numele DOMNULUI și se sprijină verbal pe Dumnezeul lui Israel, dar nu în adevăr și dreptate. Dumnezeu spune că a anunțat lucrurile dinainte tocmai pentru ca poporul cu grumaz de fier să nu poată spune că idolul lui le-a făcut. Lucruri noi sunt anunțate înainte ca Israel să le cunoască, expunând pretenția că știa deja." },
    { from: 9, to: 11, heading: "Judecata este limitată pentru Numele lui Dumnezeu, iar Israel este rafinat în cuptorul suferinței", teaching: "Dumnezeu spune că Își amână mânia de dragul Numelui Său și nu nimicește complet poporul. Israel este curățat nu ca argintul într-un proces comod, ci în cuptorul suferinței. Motivul repetat este gloria lui Dumnezeu: Numele Lui nu va fi profanat și gloria Lui nu este dată altuia." },
    { from: 12, to: 16, heading: "Cel dintâi și Cel de pe urmă, Creatorul cerului și pământului, îl cheamă pe omul care va acționa împotriva Babilonului", teaching: "Iacov este chemat să asculte pe Cel care a pus temelia pământului și a întins cerurile. Neamurile și idolii sunt întrebați cine a anunțat lucrurile, iar omul iubit pentru împlinirea planului împotriva Babilonului este chemat de Dumnezeu. Profetul spune că nu a vorbit în secret și că Domnul l-a trimis împreună cu Duhul Său." },
    { from: 17, to: 22, heading: "Răscumpărătorul învață calea folositoare, iar ascultarea ar fi produs pace ca un râu", teaching: "Dumnezeu se prezintă ca Învățătorul care îl conduce pe Israel pe drumul pe care trebuie să meargă. Dacă poruncile ar fi fost ascultate, pacea ar fi fost ca un râu și dreptatea ca valurile mării. Totuși chemarea din exil rămâne: ieșiți din Babilon și vestiți răscumpărarea. Capitolul se încheie cu contrastul: nu este pace pentru cei răi." },
  ]),
  49: c(49, [
    { from: 1, to: 6, heading: "Robul este chemat din pântece și primește o misiune care depășește restaurarea lui Israel", teaching: "Insulele și popoarele îndepărtate sunt chemate să asculte. Robul spune că Dumnezeu i-a numit numele din pântece, i-a făcut gura ca o sabie și l-a ascuns ca o săgeată. Deși își exprimă sentimentul că a lucrat în zadar, cauza lui rămâne la Dumnezeu. Misiunea este apoi lărgită: este prea puțin doar să ridice triburile lui Iacov; Robul devine lumină pentru neamuri până la marginile pământului." },
    { from: 7, to: 13, heading: "Cel disprețuit este onorat, iar legământul aduce eliberare, hrană și drumuri pentru cei care se întorc", teaching: "Robul disprețuit de oameni este văzut de regi care se ridică și prinți care se pleacă datorită credincioșiei DOMNULUI. În timpul favorii, el este păstrat ca legământ pentru popor, ca să ridice țara și să spună prizonierilor să iasă. Cei întorși găsesc pășune și izvoare, iar munții devin drum. Cerul și pământul sunt chemate la cântare pentru mângâierea poporului." },
    { from: 14, to: 21, heading: "Sionul spune «DOMNUL m-a uitat», iar Dumnezeu răspunde prin imaginea mamei și a numelui gravat pe palme", teaching: "Zion interpretează exilul ca abandon. Dumnezeu răspunde întrebând dacă o mamă își poate uita copilul; chiar dacă ar face-o, El nu uită. Zidurile Sionului sunt înaintea Lui, iar cei care o zideau se grăbesc înapoi. Cetatea care se credea fără copii va fi surprinsă de mulțimea celor care se întorc și va întreba cine i-a născut." },
    { from: 22, to: 26, heading: "Națiunile sunt chemate să poarte înapoi copiii Sionului, iar prada este smulsă din mâna celui puternic", teaching: "Dumnezeu ridică mâna spre neamuri, iar regii și reginele devin slujitori ai întoarcerii copiilor Sionului. Apoi vine întrebarea dacă prada poate fi luată de la cel puternic. Răspunsul este da: capturii sunt eliberați, iar cei care se luptă cu poporul sunt confruntați. Scopul final este ca orice făptură să știe că DOMNUL este Salvator și Răscumpărător." },
  ]),
  50: c(50, [
    { from: 1, to: 3, heading: "Exilul nu este explicat printr-un divorț arbitrar al lui Dumnezeu sau printr-o datorie a Lui", teaching: "Dumnezeu întreabă unde este certificatul de divorț sau creditorul căruia ar fi fost vânduți copiii. Răspunsul este că fărădelegile lor au dus la vânzare și păcatele la îndepărtare. Când El a venit, nimeni nu a răspuns, deși puterea Lui nu s-a micșorat: marea poate fi uscată și cerul îmbrăcat în întuneric." },
    { from: 4, to: 9, heading: "Robul primește limba celui învățat, ascultă dimineața și nu se întoarce din fața suferinței", teaching: "Domnul îi dă Robului o limbă capabilă să întărească pe cel obosit și îi trezește urechea în fiecare dimineață. Robul nu este răzvrătit și nu se retrage, chiar când își oferă spatele loviturilor și fața scuipatului. El își întărește fața pentru că Dumnezeu îl ajută și întreabă cine îl poate condamna dacă Cel care îl justifică este aproape." },
    { from: 10, to: 11, heading: "Cel care se teme de DOMNUL este chemat să se încreadă chiar în întuneric, nu să-și aprindă propria lumină ca substitut", teaching: "Omul care umblă în întuneric fără lumină, dar ascultă glasul Robului, este chemat să se încreadă în Numele DOMNULUI. În contrast, cei care își aprind singuri focuri și umblă în lumina torțelor lor primesc avertismentul că această autosalvare îi va duce la durere." },
  ]),
  51: c(51, [
    { from: 1, to: 3, heading: "Cei care caută dreptatea sunt chemați să privească spre Avraam și spre puterea lui Dumnezeu de a face din puțin un popor", teaching: "Poporul este invitat să privească stânca din care a fost tăiat și pe Avraam și Sara. Avraam era unul singur când Dumnezeu l-a chemat și l-a înmulțit. Aceeași putere poate mângâia Sionul și transforma pustiul lui într-un Eden plin de bucurie și cântare." },
    { from: 4, to: 8, heading: "Învățătura și dreptatea lui Dumnezeu devin lumină pentru popoare, în timp ce cerul și pământul trec", teaching: "Neamurile sunt chemate să asculte pentru că Legea și judecata lui Dumnezeu ies ca lumină. Brațul Lui va judeca popoarele, iar insulele Îl așteaptă. Cerul se poate risipi ca fumul și pământul se poate învechi ca o haină, dar salvarea și dreptatea Lui rămân. De aceea cei care cunosc dreptatea nu trebuie să se teamă definitiv de batjocura oamenilor." },
    { from: 9, to: 11, heading: "Rugăciunea «trezește-te, braț al DOMNULUI» își amintește marea despicată și cere o nouă întoarcere", teaching: "Comunitatea cheamă brațul DOMNULUI să se trezească precum în zilele vechi, folosind imagini ale Rahabului și balaurului pentru puterea Egiptului și haosului. Marea uscată devine drum pentru cei răscumpărați. Apoi viziunea se mută spre întoarcerea în Sion cu bucurie veșnică și dispariția durerii." },
    { from: 12, to: 16, heading: "Dumnezeu întreabă de ce omul se teme de muritori și uită de Creator", teaching: "Cel care mângâie poporul îi confruntă frica permanentă de asupritor. Omul moare ca iarba, dar Creatorul a întins cerurile și a pus temeliile pământului. Captivul nu va muri în groapă și nu îi va lipsi pâinea. Dumnezeu, Cel care stârnește marea, pune cuvintele Sale în gura poporului și îl acoperă cu umbra mâinii." },
    { from: 17, to: 23, heading: "Ierusalimul care a băut cupa mâniei este chemat să se trezească pentru că potirul trece la asupritori", teaching: "Cetatea este personificată ca o femeie amețită de cupa judecății, fără fii care să o călăuzească între ruină și foamete. Dumnezeu spune că ia din mâna ei cupa clătinării și nu o va mai bea. Aceeași cupă ajunge la cei care au forțat-o să se plece și i-au folosit trupul ca drum." },
  ]),
  52: c(52, [
    { from: 1, to: 6, heading: "Sionul este chemat să se trezească, să-și scuture țărâna și să rupă legăturile captivității", teaching: "Ierusalimul își pune hainele frumoase și se ridică din praf. Poporul fusese vândut fără bani și va fi răscumpărat fără plată. Egiptul și Asiria sunt amintite ca experiențe anterioare de asuprire, iar în Babilon Numele lui Dumnezeu este batjocorit. Tocmai de aceea poporul va cunoaște Numele Celui care spune «Iată-Mă»." },
    { from: 7, to: 10, heading: "Picioarele mesagerului sunt numite frumoase pentru că aduc vestea că Dumnezeu împărățește", teaching: "Străjerii ridică glasul și văd întoarcerea DOMNULUI în Sion. Ruinele Ierusalimului sunt chemate la cântare pentru mângâiere și răscumpărare. Brațul sfânt al lui Dumnezeu este descoperit înaintea neamurilor, iar toate marginile pământului văd salvarea Lui." },
    { from: 11, to: 12, heading: "Ieșirea din Babilon cere curăție, dar nu panică", teaching: "Cei care poartă vasele DOMNULUI sunt chemați să iasă și să nu atingă necurăția. Totuși ieșirea nu va fi ca o fugă haotică: DOMNUL merge înaintea lor și Dumnezeul lui Israel le este ariergardă." },
    { from: 13, to: 15, heading: "Robul trece de la desfigurare și uimirea multora la înălțare și impact asupra națiunilor", teaching: "Secțiunea care conduce direct spre Isaia 53 începe spunând că Robul va lucra cu înțelepciune și va fi înălțat. Mulți sunt îngroziți de aspectul lui desfigurat, dar el ajunge să uimească sau să stropească multe națiuni, iar regii își închid gura. Cei care nu primiseră vestea ajung să vadă și să înțeleagă." },
  ]),
  54: c(54, [
    { from: 1, to: 3, heading: "Femeia stearpă este chemată să cânte și să lărgească cortul pentru o familie neașteptat de mare", teaching: "Zionul este comparat cu o femeie fără copii care primește vestea unei rodiri mai mari decât a celei căsătorite. Cortul trebuie lărgit, frânghiile întinse și țărușii întăriți, pentru că urmașii se vor răspândi în dreapta și stânga și vor repopula cetăți pustiite." },
    { from: 4, to: 8, heading: "Rușinea văduviei și părăsirii este înlocuită de compasiunea Răscumpărătorului", teaching: "Sionul nu trebuie să se teamă de rușinea tinereții sau a văduviei, pentru că Făcătorul este numit soț și Răscumpărător. Dumnezeu vorbește despre un moment scurt de părăsire și despre o strângere înapoi cu mare compasiune. Mânia de o clipă este pusă în contrast cu bunătatea durabilă." },
    { from: 9, to: 10, heading: "Legământul păcii este comparat cu promisiunea după apele lui Noe", teaching: "Dumnezeu amintește jurământul că apele lui Noe nu vor mai acoperi pământul și folosește analogia pentru a vorbi despre angajamentul Său față de Sion. Munții se pot muta și dealurile se pot clătina, dar bunătatea și legământul păcii sunt prezentate ca mai stabile." },
    { from: 11, to: 17, heading: "Cetatea chinuită este reconstruită în pietre prețioase, iar moștenirea slujitorilor este apărarea împotriva acuzației", teaching: "Femeia lovită de furtună și nemângâiată primește o cetate refăcută în culori și pietre prețioase. Fiii ei sunt învățați de DOMNUL și au pace, iar teroarea este îndepărtată. Armele făurite și acuzațiile juridice nu vor avea ultimul cuvânt; aceasta este numită moștenirea slujitorilor DOMNULUI și dreptatea lor de la El." },
  ]),
  56: c(56, [
    { from: 1, to: 2, heading: "Dreptatea și păzirea Sabatului sunt legate de apropierea mântuirii", teaching: "Poporul este chemat să păzească judecata și să facă dreptate pentru că salvarea se apropie. Fericit este omul care ține Sabatul fără să îl profaneze și își păzește mâna de rău. Practica cultică și conduita morală sunt din nou așezate împreună." },
    { from: 3, to: 8, heading: "Străinul și eunucul nu trebuie să se creadă excluși din poporul care se atașează de DOMNUL", teaching: "Străinul nu trebuie să spună că va fi separat, iar eunucul nu trebuie să se numească pom uscat. Cei care aleg ceea ce Îi place lui Dumnezeu primesc un nume mai bun decât fii și fiice, iar străinii care Îl iubesc sunt aduși pe muntele sfânt. Casa Lui este numită casă de rugăciune pentru toate popoarele, iar Dumnezeu spune că va aduna și alții pe lângă cei deja adunați." },
    { from: 9, to: 12, heading: "După imaginea includerii, conducătorii orbi și lacomi sunt expuși", teaching: "Fiarele câmpului sunt chemate să mănânce pentru că străjerii poporului sunt orbi, fără cunoaștere și incapabili să latre. Păstorii își urmăresc propriul câștig și sunt dedicați băuturii, presupunând că mâine va fi și mai mult ca astăzi. Liderii care trebuiau să protejeze devin astfel parte din pericol." },
  ]),
  57: c(57, [
    { from: 1, to: 2, heading: "Moartea celui drept poate fi o luare din fața răului, nu dovada că viața lui a fost lipsită de sens", teaching: "Cel drept piere și oamenii nu pun la inimă, iar oamenii evlavioși sunt luați fără ca societatea să înțeleagă. Textul spune că cel drept este luat din fața răului și intră în pace. Judecata asupra societății nu trebuie măsurată numai prin durata vieții celor buni." },
    { from: 3, to: 13, heading: "Idolatria este descrisă prin adulter spiritual, ritualuri sexuale și alianțe care nu pot salva", teaching: "Profetul confruntă o generație de idolatri prin limbaj sever despre infidelitate, sacrificarea copiilor, pietrele din vale, paturi rituale și călătorii la regi. Poporul s-a obosit pe multe drumuri, dar nu a spus că nu mai există speranță. Când vine criza, Dumnezeu îi provoacă să își cheme colecția de idoli; vântul îi poate lua, dar cel care se refugiază în DOMNUL moștenește țara." },
    { from: 14, to: 19, heading: "Cel înalt și sfânt locuiește și cu omul zdrobit, vindecând pe cel pe care l-a disciplinat", teaching: "Drumul este curățat de obstacole, iar Dumnezeu se descrie ca Cel înalt care locuiește în veșnicie și al cărui Nume este sfânt. În același timp, El locuiește cu cel zdrobit și smerit ca să-i învioreze duhul. El nu Se mânie pentru totdeauna, vede căile omului și promite să-l vindece și să-i dea mângâiere și pace." },
    { from: 20, to: 21, heading: "Răul neliniștit este ca marea agitată care aruncă noroi", teaching: "Cei răi sunt comparați cu o mare care nu se poate liniști și ale cărei ape aruncă noroi și murdărie. Capitolul încheie cu afirmația repetată din această secțiune a lui Isaia: nu este pace pentru cei răi." },
  ]),
  58: c(58, [
    { from: 1, to: 5, heading: "Postul poate arăta religios și totuși să coexiste cu exploatarea și cearta", teaching: "Poporul pare că Îl caută zilnic pe Dumnezeu și întreabă de ce nu vede postul lor. Răspunsul este că în ziua postului își urmăresc interesele, își asupresc lucrătorii și ajung la ceartă și lovire. Sacul, capul plecat și abstinența nu sunt suficiente când relațiile rămân nedrepte." },
    { from: 6, to: 7, heading: "Postul ales de Dumnezeu este descris prin eliberare, hrană, adăpost și îmbrăcăminte", teaching: "Lanțurile nedreptății trebuie desfăcute, jugurile rupte și cei asupriți eliberați. Pâinea este împărțită cu cel flămând, săracul fără casă este primit, iar cel gol este îmbrăcat. Spiritualitatea postului este legată direct de responsabilitatea față de trupul și demnitatea aproapelui." },
    { from: 8, to: 12, heading: "Lumina și vindecarea urmează unei vieți care îndepărtează jugul și se dă celui flămând", teaching: "Când dreptatea este practicată, lumina răsare și vindecarea apare. DOMNUL răspunde strigătului, dar condiția textuală include îndepărtarea jugului, a arătării cu degetul și a vorbirii rele. Cel care se dă celui flămând devine ca o grădină udată și participă la reconstruirea ruinelor și refacerea drumurilor." },
    { from: 13, to: 14, heading: "Sabatul este păzit prin încetarea folosirii zilei sfinte numai pentru propriile interese", teaching: "Poporul este chemat să își oprească piciorul de la folosirea Sabatului exclusiv pentru plăcerea și afacerile proprii și să numească ziua sfântă o desfătare. Promisiunea este bucuria în DOMNUL și moștenirea lui Iacov. Textul nu separă astfel odihna sfântă de dreptatea socială descrisă în restul capitolului." },
  ]),
  59: c(59, [
    { from: 1, to: 8, heading: "Problema nu este că mâna lui Dumnezeu ar fi prea scurtă, ci că nelegiuirea a separat poporul de El", teaching: "Capitolul începe respingând ideea că Dumnezeu nu poate salva sau auzi. Mâinile, degetele, buzele și limba poporului sunt implicate în sânge, nelegiuire și minciună. Procesele nu sunt drepte, planurile sunt ca ouă de șarpe și pânze de păianjen, iar picioarele aleargă spre rău. Drumul păcii nu este cunoscut." },
    { from: 9, to: 15, heading: "Comunitatea recunoaște că așteaptă lumină și găsește întuneric pentru că adevărul și dreptatea au căzut", teaching: "Pronumele se schimbă spre «noi»: oamenii recunosc că judecata este departe, bâjbâie ca orbii și gem. Fărădelegile sunt multe, păcatele mărturisesc împotriva lor, iar rebeliunea și minciuna sunt numite direct. Adevărul lipsește din piață, iar cel care se îndepărtează de rău devine pradă." },
    { from: 16, to: 20, heading: "Dumnezeu vede că nu există mijlocitor și Se îmbracă El Însuși ca războinic al dreptății", teaching: "DOMNUL este uimit că nimeni nu intervine și propriul braț aduce salvare. Dreptatea este platoșă, mântuirea coif, iar răzbunarea și zelul sunt hainele Lui. El răsplătește faptele și vine ca un râu împins de Duhul DOMNULUI. Răscumpărătorul vine în Sion la cei care se întorc de la fărădelege." },
    { from: 21, to: 21, heading: "Legământul final leagă Duhul și cuvintele lui Dumnezeu de generațiile poporului", teaching: "Dumnezeu spune că Duhul pus peste popor și cuvintele puse în gura lui nu se vor depărta din gura lui, a copiilor și a urmașilor lor. Capitolul care a început cu tăcerea produsă de păcat se încheie cu promisiunea unei mărturii transmise prin generații." },
  ]),
  60: c(60, [
    { from: 1, to: 7, heading: "Sionul este chemat să se ridice pentru că lumina DOMNULUI răsare peste el și atrage națiunile", teaching: "Întunericul acoperă pământul, dar gloria DOMNULUI apare peste Sion. Neamurile și regii vin spre lumină, fiii și fiicele se întorc, iar bogățiile mării și caravanele din Madian, Efa și Șeba sosesc. Darurile și turmele sunt legate de lauda DOMNULUI și de frumusețea Casei Sale." },
    { from: 8, to: 14, heading: "Corăbiile aduc copiii și resursele înapoi, iar cei care au disprețuit Sionul ajung să recunoască lucrarea lui Dumnezeu", teaching: "Corăbiile din Tarsis aduc de departe fiii, argintul și aurul. Străinii reconstruiesc zidurile, iar porțile rămân deschise pentru fluxul neamurilor și regilor. Puterile care refuză această ordine sunt confruntate, iar descendenții celor care au asuprit Sionul vin și recunosc cetatea DOMNULUI." },
    { from: 15, to: 18, heading: "Cetatea părăsită este transformată într-un loc de onoare, pace și dreptate", teaching: "În loc să fie abandonată și urâtă, Sionul primește onoare între generații. Bogăția neamurilor și resursele regilor sunt descrise ca hrană, iar materialele inferioare sunt înlocuite cu unele mai valoroase. Dumnezeu spune că va pune pacea ca administrator și dreptatea ca stăpân, iar violența nu se mai aude în țară." },
    { from: 19, to: 22, heading: "Lumina ultimă a cetății nu mai depinde de soare și lună, ci de DOMNUL", teaching: "Soarele și luna nu mai sunt lumina finală, pentru că DOMNUL este lumină veșnică și gloria poporului. Zilele de doliu se termină, poporul este numit drept și este comparat cu mlădița plantată de Dumnezeu. Cel mic devine o mie, iar Dumnezeu promite să grăbească împlinirea la timpul ei." },
  ]),
  62: c(62, [
    { from: 1, to: 5, heading: "Isaia refuză să tacă până când dreptatea Sionului strălucește și cetatea primește un nume nou", teaching: "Profetul nu va tăcea până când salvarea Ierusalimului arde ca o torță și neamurile văd dreptatea lui. Sionul primește un nume nou din gura DOMNULUI și devine cunună în mâna Lui. Numele «Părăsită» și «Pustie» sunt înlocuite de «Plăcerea Mea este în ea» și «Căsătorită», iar bucuria mirelui devine imagine a bucuriei lui Dumnezeu pentru popor." },
    { from: 6, to: 9, heading: "Străjerii nu trebuie să tacă, iar roadele muncii nu mai sunt date dușmanilor", teaching: "Pe ziduri sunt puși străjeri care Îi amintesc DOMNULUI zi și noapte și nu își iau odihnă până când Ierusalimul devine laudă pe pământ. Dumnezeu jură că grâul și vinul nu vor mai hrăni vrăjmașii, ci cei care au muncit le vor consuma cu mulțumire în curțile sanctuarului." },
    { from: 10, to: 12, heading: "Drumul este curățat pentru poporul răscumpărat, iar Sionul primește nume care răspund abandonului trecut", teaching: "Porțile se deschid, drumul este pregătit, pietrele sunt îndepărtate și steagul este ridicat pentru popoare. Vestea merge până la marginile pământului că salvarea vine și răsplata este cu Dumnezeu. Locuitorii sunt numiți Popor Sfânt și Răscumpărații DOMNULUI, iar cetatea devine Căutată, Nu Părăsită." },
  ]),
  65: c(65, [
    { from: 1, to: 7, heading: "Dumnezeu Se lasă găsit de cei care nu Îl căutau, în timp ce poporul răzvrătit persistă în idolatrie", teaching: "DOMNUL spune că a răspuns celor care nu întrebau și S-a făcut cunoscut celor care nu Îl căutau, în timp ce și-a întins mâinile toată ziua spre un popor răzvrătit. Ritualurile din grădini, jertfele pe cărămizi, consultarea mormintelor și mâncărurile necurate sunt unite cu o atitudine de superioritate religioasă. Dumnezeu spune că nu va tăcea, ci va răsplăti nelegiuirea." },
    { from: 8, to: 12, heading: "Un ciorchine cu suc este păstrat pentru binele lui, iar Dumnezeu promite o rămășiță în mijlocul judecății", teaching: "Așa cum un ciorchine nu este distrus dacă încă are rod, Dumnezeu spune că nu îi va nimici pe toți. Din Iacov iese o sămânță care moștenește munții, iar Șaronul și valea Acor devin pășuni. În contrast, cei care Îl părăsesc și pregătesc mese pentru zeii Norocului și Destinului sunt destinați sabiei pentru că nu au răspuns când au fost chemați." },
    { from: 13, to: 16, heading: "Slujitorii și cei care abandonează pe Dumnezeu ajung la rezultate opuse", teaching: "Slujitorii mănâncă, beau și se bucură, în timp ce ceilalți sunt flămânzi, însetați și rușinați. Numele celor răzvrătiți devine formulă de blestem, iar slujitorii primesc un alt nume. Cel care se binecuvântează pe pământ o face în Dumnezeul adevărului, pentru că necazurile vechi sunt ascunse dinaintea Lui." },
    { from: 17, to: 25, heading: "Cerurile noi și pământul nou sunt descrise prin bucurie, viață, muncă nerisipită și pace în creație", teaching: "Dumnezeu anunță o creație nouă în care lucrurile vechi nu mai domină memoria. Ierusalimul devine bucurie, plânsul și strigătul dispar, iar moartea prematură este descrisă ca excepție îndepărtată. Oamenii își construiesc casele și le locuiesc, plantează și mănâncă rodul, iar munca nu mai este pentru ca altul să profite. Răspunsul lui Dumnezeu vine chiar înainte de chemare, iar lupul și mielul se hrănesc împreună fără rău pe muntele sfânt." },
  ]),
}
