import type { ExplainedOverlayChapter } from "../explainedOverlay.js"
import { VT_MAJOR_PROPHETS_FULL } from "../vtFullNarrativesMajorProphets.js"
import { sectionedTextualChapter } from "./textualChapterFactory.js"

const data = VT_MAJOR_PROPHETS_FULL.plangerile
const c = (number: number, sections: Parameters<typeof sectionedTextualChapter>[3]) =>
  sectionedTextualChapter("Plângerile", data, number, sections)

export const PLANGERILE_DEEPENED: Readonly<Record<number, ExplainedOverlayChapter>> = {
  2: c(2, [
    { from: 1, to: 8, heading: "Mânia este descrisă ca o demolare a structurilor în care Sionul își găsea siguranța", teaching: "Capitolul începe spunând că DOMNUL a acoperit fiica Sionului cu un nor și a aruncat gloria lui Israel din cer pe pământ. Locuințe, fortificații, împărăție, preoție, altar, sanctuar și ziduri apar unul după altul sub imaginea dărâmării. Lamentația nu îndulcește responsabilitatea lui Iuda, dar nici nu tratează distrugerea ca simplă întâmplare militară fără semnificație morală." },
    { from: 9, to: 12, heading: "Porțile, Legea și vedeniile dispar, iar bătrânii și copiii împărtășesc aceeași ruină", teaching: "Porțile sunt scufundate în pământ, regele și prinții sunt între neamuri, iar profeții nu mai primesc vedenie. Bătrânii stau în tăcere cu țărână pe cap, iar tinerele își pleacă fețele. Naratorul își consumă ochii de plâns când copiii leșină de foame și întreabă mamele unde sunt grâul și vinul." },
    { from: 13, to: 17, heading: "Profeții falși au acoperit nelegiuirea cu vedenii goale, iar dușmanii batjocoresc cetatea căzută", teaching: "Profetul caută o comparație suficientă pentru rana Ierusalimului și nu găsește. Un motiv al adâncirii crizei este că profeții au văzut lucruri false și seducătoare și nu au descoperit fărădelegea care trebuia confruntată. Trecătorii și vrăjmașii bat din palme și întreabă dacă aceasta este cetatea numită desăvârșirea frumuseții, iar lamentația recunoaște că DOMNUL a împlinit avertismentele vechi." },
    { from: 18, to: 22, heading: "Durerea este transformată într-un strigăt continuu înaintea lui Dumnezeu", teaching: "Inima poporului este chemată să strige către DOMNUL, iar lacrimile să curgă zi și noapte. Rugăciunea îi aduce înainte pe copiii care leșină de foame și pe victimele violenței din sanctuar și străzi. Întrebările despre mame, preoți și tineri nu justifică atrocitățile; tocmai le expun înaintea lui Dumnezeu ca parte a groazei judecății și războiului." },
  ]),
  4: c(4, [
    { from: 1, to: 6, heading: "Aurul întunecat și copiii flămânzi arată inversarea completă a vieții Ierusalimului", teaching: "Aurul și pietrele sanctuarului sunt împrăștiate, iar fiii Sionului, cândva comparați cu aur fin, sunt tratați ca vase de lut. Copiii cer pâine fără să le fie dată, iar cei crescuți în lux ajung pe grămezi de gunoi. Vinovăția cetății este descrisă ca mai mare decât a Sodomei tocmai pentru că ruina se prelungește sub ochii comunității." },
    { from: 7, to: 10, heading: "Nobilii nu mai pot fi recunoscuți, iar foametea produce imagini de o cruzime extremă", teaching: "Oamenii odinioară curați și viguroși devin mai întunecați decât funinginea și pielea li se lipește de oase. Moartea rapidă de sabie pare mai suportabilă decât moartea lentă prin foame. Ultima imagine, a mamelor care își fierb propriii copii, este una dintre cele mai cumplite din carte și descrie colapsul uman produs de asediu; nu este prezentată ca moralmente acceptabilă." },
    { from: 11, to: 16, heading: "Căderea cetății îi surprinde pe regi, iar sângele vărsat de liderii religioși este numit direct", teaching: "Mânia este descrisă ca foc care consumă temeliile Sionului. Regii pământului nu credeau că dușmanul poate intra în porțile Ierusalimului. Textul leagă însă dezastrul de păcatele profeților și preoților care au vărsat sânge nevinovat. Ei ajung să rătăcească orbi pe străzi, contaminați de sânge și respinși între neamuri." },
    { from: 17, to: 20, heading: "Așteptarea unui aliat care nu putea salva și căderea unsului distrug ultimele iluzii politice", teaching: "Ochii poporului au obosit privind după ajutorul unui neam care nu putea salva. Urmăritorii îi prind pe munți și în pustiu, iar sfârșitul se apropie. Regele, numit unsul DOMNULUI și «suflarea nărilor noastre», este capturat; speranța că poporul va trăi sub umbra lui între neamuri se destramă." },
    { from: 21, to: 22, heading: "Edom este avertizat că bucuria lui nu va dura, iar Sionului i se spune că pedeapsa ajunge la capăt", teaching: "Fiica Edomului este ironizată pentru bucuria ei și i se spune că va bea și ea cupa rușinii. În contrast, fiica Sionului primește afirmația că pedeapsa ei se încheie și că nu va continua aceeași deportare la nesfârșit. Lamentația se termină astfel cu judecata mutată spre cel care s-a bucurat de căderea altuia." },
  ]),
  5: c(5, [
    { from: 1, to: 6, heading: "Comunitatea Îi cere lui Dumnezeu să privească rușinea: moștenirea, casele și autonomia au fost pierdute", teaching: "Rugăciunea începe cu «adu-Ți aminte» și enumeră pierderea moștenirii și a caselor, situația de orfani și văduve și chiar faptul că apa și lemnul trebuie cumpărate. Urmăritorii nu dau odihnă, iar poporul întinde mâna spre Egipt și Asiria pentru pâine. Nenorocirea nu este abstractă, ci se vede în resursele de bază ale vieții." },
    { from: 7, to: 10, heading: "Generația actuală poartă consecințe istorice și trăiește sub foamete și nesiguranță", teaching: "Oamenii spun că părinții au păcătuit și nu mai sunt, iar ei poartă consecințele. Slujitori ajung să stăpânească fără ca cineva să-i elibereze, iar aducerea pâinii devine risc de sabie. Pielea arde de febra foametei. Textul nu spune că urmașii sunt moral vinovați automat de fiecare faptă a părinților, ci descrie realitatea consecințelor colective care traversează generațiile." },
    { from: 11, to: 14, heading: "Violența sexuală, executarea conducătorilor și pierderea bătrânilor arată degradarea ordinii sociale", teaching: "Femeile din Sion și fecioarele cetăților lui Iuda sunt violate, iar prinții sunt spânzurați fără respect pentru bătrâni. Tinerii sunt obligați să macine și copiii se clatină sub lemne. Bătrânii dispar de la poarta cetății și muzica tinerilor încetează. Lamentația numește aceste acte ca suferință și rușine, nu le justifică prin contextul războiului." },
    { from: 15, to: 18, heading: "Bucuria se transformă în doliu, iar comunitatea își mărturisește păcatul fără să ascundă ruina Sionului", teaching: "Bucuria inimii a încetat, dansul s-a transformat în plâns și cununa a căzut de pe cap. Poporul spune «vai de noi, căci am păcătuit», legând responsabilitatea morală de slăbirea inimii și ochilor. Muntele Sionului este pustiu și șacalii umblă pe el, imaginea fizică a pierderii centrului comunității." },
    { from: 19, to: 22, heading: "Tronul lui Dumnezeu rămâne când cetatea cade, iar ultima rugăciune cere întoarcere și restaurare", teaching: "După toate lucrurile care au fost pierdute, DOMNUL este declarat ca rămânând pe tron din generație în generație. Tocmai această stabilitate permite întrebarea de ce pare să uite și să părăsească poporul. Rugăciunea finală cere: «întoarce-ne la Tine și ne vom întoarce; înnoiește zilele noastre ca odinioară». Ultimul verset păstrează tensiunea durerii și nu închide artificial lamentația cu optimism ușor." },
  ]),
}
