import type { ExplainedOverlayChapter } from "../explainedOverlay.js"

const n = {
  kind: "biblia-emanus" as const,
  note: "rezumat textual fără doctrină adăugată" as const,
}

export const PROVERBE_DEEPENED_11_20: Readonly<Record<number, ExplainedOverlayChapter>> = {
  11: {
    number: 11,
    title: "Integritate, generozitate și viață comunitară",
    summary: "Cântarul fals, mândria și câștigul nedrept sunt puse în contrast cu integritatea și dreptatea. Generozitatea este descrisă ca aducând bine atât celui care dă, cât și comunității, în timp ce încrederea în bogăție nu poate salva.",
    units: [
      { from: 1, to: 8, heading: "Cântarul drept, smerenia și integritatea", teaching: "Capitolul pornește de la comerț: DOMNUL urăște cântarul fals și aprobă greutatea dreaptă. Apoi aceeași logică este mutată în caracter: mândria aduce rușine, smerenia merge cu înțelepciunea, iar integritatea îl călăuzește pe omul drept. Bogăția nu poate cumpăra scăparea în ziua mâniei, iar răul pregătit de cel necredincios se poate întoarce asupra lui.", source: n },
      { from: 9, to: 15, heading: "Cuvintele și conducerea pot ridica sau ruina comunitatea", teaching: "Omul lipsit de Dumnezeu poate răni pe aproapele său prin gură, în timp ce cunoașterea poate salva. O cetate se bucură când celor drepți le merge bine, iar prin binecuvântarea lor este înălțată; prin gura celor răi poate fi dărâmată. Disprețul, bârfa și divulgarea secretelor rup încrederea, iar lipsa sfatului poate duce un popor la cădere. A intra nechibzuit garant pentru altul este prezentat ca risc, nu ca virtute obligatorie.", source: n },
      { from: 16, to: 23, heading: "Bunătatea și dreptatea lucrează mai adânc decât avantajul imediat", teaching: "Bunătatea făcută altuia se întoarce și asupra celui care o practică, în timp ce cruzimea îl rănește pe cel crud. Câștigul răului este numit înșelător, dar semănarea dreptății are un rezultat trainic. Dorința celui drept tinde spre bine, pe când urmărirea răului îl aduce pe om sub consecințele lui.", source: n },
      { from: 24, to: 31, heading: "Generozitatea, încrederea în bogăție și rodul unei vieți", teaching: "Un paradox al înțelepciunii este că omul care împarte cu generozitate poate avea parte de înviorare, iar cel care reține egoist poate ajunge în lipsă. Comunitatea reacționează și la felul în care cineva administrează resursele de care ceilalți au nevoie. Încrederea în bogăție este instabilă; dreptul este comparat cu frunzișul care rămâne. Finalul privește viața ca pe un pom care produce rod și afirmă că faptele oamenilor au consecințe chiar în această lume.", source: n },
    ],
  },
  12: {
    number: 12,
    title: "Cuvintele și munca dezvăluie caracterul",
    summary: "Proverbele vorbesc despre iubirea disciplinei, hărnicie, grijă față de animale și stabilitatea celui drept. Cuvintele pot fi sabie sau vindecare, iar minciuna și lenevia nu au aceeași durată ca adevărul și munca serioasă.",
    units: [
      { from: 1, to: 7, heading: "Corectarea primită și rădăcina care nu poate fi smulsă", teaching: "A iubi disciplina înseamnă a iubi cunoașterea, în timp ce refuzul oricărei corectări este numit nebunie. Bunătatea și dreptatea sunt legate de stabilitate, iar planurile răului de înșelare. Casa celui drept are rădăcină, pe când cuvintele celor răi pot deveni o ambuscadă pentru sânge.", source: n },
      { from: 8, to: 14, heading: "Valoarea reală, munca și grija față de ceea ce depinde de tine", teaching: "Omul este evaluat după pricepere, nu după imaginea umflată despre sine. Este mai bine să ai o poziție modestă și resurse reale decât să mimezi importanța și să nu ai hrană. Grija omului drept ajunge chiar la animalele sale, iar munca pământului produce hrană. Dorința de câștig prin căile celor răi este pusă în contrast cu stabilitatea muncii și cu rodul cuvintelor și faptelor proprii.", source: n },
      { from: 15, to: 22, heading: "Înțeleptul ascultă, nu reacționează imediat și spune adevărul", teaching: "Nebunul este convins că drumul lui este corect, în timp ce omul înțelept poate primi sfat. El nu transformă fiecare ofensă într-o explozie imediată. Martorul adevărat și limba care vindecă sunt opuse minciunii și cuvintelor pripite care taie ca sabia. Adevărul este descris ca durabil, iar minciuna ca temporară.", source: n },
      { from: 23, to: 28, heading: "Prudența, hărnicia și calea dreptății", teaching: "Omul prudent nu își expune ostentativ toată cunoașterea, iar inima nebunilor își face publică nebunia. Hărnicia conduce spre responsabilitate, în timp ce lenevia ajunge sub povară. Neliniștea apasă inima, dar un cuvânt bun o poate înveseli. Finalul prezintă calea dreptății ca drum al vieții, nu ca promisiune că omul drept nu va muri fizic.", source: n },
    ],
  },
  13: {
    number: 13,
    title: "Disciplina, dorințele și anturajul",
    summary: "Capitolul leagă ascultarea de corectare de înțelepciune și arată că speranța amânată poate îmbolnăvi inima. Cel care umblă cu înțelepții devine înțelept, iar disciplina responsabilă este legată de iubire.",
    units: [
      { from: 1, to: 6, heading: "Corectarea, paza gurii și diferența dintre dorință și muncă", teaching: "Fiul înțelept poate asculta disciplina, în timp ce batjocoritorul refuză mustrarea. Cuvintele produc consecințe, iar paza gurii este legată de paza vieții. Leneșul poate avea dorințe intense fără rezultat, pe când hărnicia este asociată cu împlinirea nevoilor. Dreptatea păzește drumul omului integru.", source: n },
      { from: 7, to: 12, heading: "Aparența bogăției, mândria și speranța amânată", teaching: "Unii par bogați fără să aibă nimic, iar alții au mult fără să trăiască pentru afișare. Bogăția poate deveni și răscumpărare într-un pericol, în timp ce săracul poate să nu fie ținta aceleiași amenințări. Mândria produce ceartă, dar sfatul aduce înțelepciune. Averea câștigată repede se micșorează, iar speranța amânată este descrisă cu realism ca boală a inimii.", source: n },
      { from: 13, to: 19, heading: "Respectul pentru cuvânt și învățătura care devine izvor de viață", teaching: "Disprețuirea unei instrucțiuni are cost, iar respectarea poruncii are răsplată. Învățătura înțeleptului este comparată cu un izvor care ajută omul să evite cursele morții. Mesagerul necredincios provoacă necaz, iar cel credincios aduce vindecare. Sărăcia și rușinea pot urma refuzului disciplinei, în timp ce dorința împlinită este dulce sufletului.", source: n },
      { from: 20, to: 25, heading: "Anturajul formează, iar responsabilitatea se întinde spre generația următoare", teaching: "Cel care umblă cu oameni înțelepți este format de această companie, iar tovărășia nebunilor aduce consecințe. Textul privește apoi moștenirea, dreptatea, hrana și disciplina copiilor. Afirmația despre nuiaua disciplinei aparține limbajului antic al formării și nu autorizează abuzul fizic; centrul proverbului este că iubirea nu abandonează copilul fără îndrumare și limite.", source: n },
    ],
  },
  14: {
    number: 14,
    title: "Calea care pare dreaptă",
    summary: "Înțelepciunea construiește casa, iar nebunia o dărâmă, în timp ce frica de DOMNUL aduce siguranță. Capitolul vorbește despre mânie, compasiune față de sărac, martor adevărat și drumul care pare drept omului dar poate sfârși în moarte.",
    units: [
      { from: 1, to: 9, heading: "Înțelepciunea zidește; nebunia poate distruge chiar propria casă", teaching: "Capitolul începe cu o imagine domestică: femeia înțeleaptă zidește casa, cea nebună o dărâmă cu propriile mâini. Frica de DOMNUL se vede în felul de a umbla, iar cuvintele nebunului îl pot răni. Lipsa boilor păstrează ieslea curată, dar elimină și puterea de lucru: ordinea fără rod nu este scopul final. Martorul credincios și relația omului cu propria vinovăție continuă tema adevărului.", source: n },
      { from: 10, to: 18, heading: "Inima are dureri pe care ceilalți nu le pot măsura, iar aparența de drum drept poate înșela", teaching: "Proverbele recunosc o zonă interioară a durerii și bucuriei pe care alt om nu o poate ocupa complet. Casa răului și cortul dreptului nu au aceeași stabilitate. Avertismentul central spune că există o cale care pare dreaptă unui om și totuși duce la moarte; convingerea subiectivă nu poate fi singurul criteriu. Cel prudent își examinează pașii, în timp ce omul naiv crede orice cuvânt.", source: n },
      { from: 19, to: 27, heading: "Felul în care tratezi pe cel sărac și felul în care te raportezi la DOMNUL sunt legate", teaching: "Textul observă fără să aprobe că săracul poate fi respins, iar bogatul poate atrage mulți prieteni. A disprețui pe aproapele este păcat, iar bunătatea față de cei lipsiți este numită fericire. Munca aduce folos, simpla vorbire poate aduce lipsă. Frica de DOMNUL este prezentată ca încredere puternică și izvor de viață care ajută omul să se îndepărteze de cursele morții.", source: n },
      { from: 28, to: 35, heading: "Conducerea, răbdarea și dreptatea unei comunități", teaching: "Puterea unui rege este legată de existența poporului, ceea ce amintește că autoritatea nu este un spectacol izolat de cei conduși. Răbdarea este asociată cu priceperea, iar mânia rapidă cu nebunia. Invidia roade interiorul omului. Asuprirea săracului Îl insultă pe Creator, iar bunătatea față de cel lipsit Îl onorează. Dreptatea înalță o comunitate, în timp ce păcatul o rușinează.", source: n },
    ],
  },
  15: {
    number: 15,
    title: "Răspunsul blând și ochii DOMNULUI",
    summary: "Un răspuns blând poate opri mânia, în timp ce vorbirea aspră o aprinde. Dumnezeu vede pretutindeni, primește rugăciunea celor drepți și prețuiește mai mult o masă simplă cu dragoste decât belșugul cu ură.",
    units: [
      { from: 1, to: 7, heading: "Răspunsul blând și limba care poate vindeca sau zdrobi", teaching: "Un răspuns blând poate dezamorsa mânia, pe când cuvântul aspru o intensifică. Limba înțeleptului folosește bine cunoașterea, iar gura nebunului revarsă prostie. Ochii DOMNULUI sunt pretutindeni, astfel că vorbirea nu este evaluată numai după reacția publicului. O limbă vindecătoare este comparată cu un pom al vieții, iar una stricată poate zdrobi duhul.", source: n },
      { from: 8, to: 17, heading: "Dumnezeu privește la inimă, iar pacea valorează mai mult decât belșugul", teaching: "Jertfa celui rău este respinsă, în timp ce rugăciunea celui drept este primită; ritualul nu poate compensa o cale rea. Corectarea este grea pentru cel care urăște disciplina, dar necesară pentru viață. DOMNUL vede chiar adâncul morții, cu atât mai mult inimile oamenilor. Finalul secțiunii compară o masă modestă cu dragoste cu un ospăț bogat plin de ură și alege pacea relației.", source: n },
      { from: 18, to: 24, heading: "Mânia produce conflict, iar sfatul și cuvântul potrivit construiesc", teaching: "Omul mânios provoacă ceartă, cel răbdător o poate liniști. Drumul leneșului devine ca un gard de spini, în timp ce calea celui drept este netezită. Planurile eșuează fără sfat și se întăresc prin consiliere. Un răspuns potrivit la momentul potrivit este motiv de bucurie, iar calea vieții îl cheamă pe omul înțelept în sus, departe de ruină.", source: n },
      { from: 25, to: 33, heading: "DOMNUL apără pe cel vulnerabil și pune smerenia înaintea onoarei", teaching: "Casa celui mândru poate fi dărâmată, dar hotarul văduvei este apărat. Planurile răului și câștigul necinstit sunt condamnate. Omul drept își cântărește răspunsul, iar cel rău varsă cuvinte fără discernământ. DOMNUL este departe de răul persistat și ascultă rugăciunea celui drept. Ultimele versete leagă disciplina, frica de DOMNUL și smerenia: onoarea nu este sănătoasă când este căutată înaintea formării caracterului.", source: n },
    ],
  },
  16: {
    number: 16,
    title: "Planurile omului și suveranitatea lui Dumnezeu",
    summary: "Omul își pregătește planurile, dar DOMNUL cântărește duhurile și îndrumă pașii. Mândria precede căderea, cuvintele bune au putere, iar stăpânirea de sine este pusă mai presus de cucerirea unei cetăți.",
    units: [
      { from: 1, to: 9, heading: "Planificarea este reală, dar motivele și pașii rămân sub Dumnezeu", teaching: "Omul își face planuri și pregătește răspunsuri, însă DOMNUL cântărește duhurile și poate hotărî rezultatul. A-ți încredința lucrările lui Dumnezeu nu înseamnă să refuzi gândirea, ci să refuzi autonomia. Mândria este urâtă de Dumnezeu, iar bunătatea și adevărul sunt legate de îndepărtarea de rău. Omul își poate planifica drumul, dar nu controlează absolut fiecare pas.", source: n },
      { from: 10, to: 16, heading: "Puterea și comerțul sunt chemate la dreptate, iar înțelepciunea valorează mai mult decât aurul", teaching: "Proverbele despre rege presupun responsabilitatea unei judecăți drepte și avertizează că răul slăbește tronul. Cântarele și greutățile drepte apar din nou sub autoritatea DOMNULUI, legând credința de economia reală. Favoarea conducătorului poate avea efecte mari, dar înțelepciunea și priceperea sunt declarate mai valoroase decât aurul și argintul.", source: n },
      { from: 17, to: 24, heading: "Mândria precede căderea, iar cuvintele înțelepte pot hrăni și vindeca", teaching: "Calea celor drepți se depărtează de rău, iar păzirea drumului este legată de păzirea vieții. Mândria și duhul îngâmfat preced prăbușirea; smerenia cu cei asupriți este preferată împărțirii prăzii cu cei mândri. Inima înțeleaptă influențează vorbirea, iar cuvintele plăcute sunt comparate cu mierea prin dulceața și efectul lor vindecător.", source: n },
      { from: 25, to: 33, heading: "Drumul aparent corect, conflictul și stăpânirea de sine", teaching: "Avertismentul despre calea care pare dreaptă și totuși duce la moarte reapare. Foamea îl poate împinge pe muncitor la lucru, dar omul lipsit de caracter poate săpa răul prin cuvinte, bârfă și violență. Bătrânețea este onorată când este găsită pe calea dreptății. Stăpânirea propriei mânii este pusă mai presus de cucerirea unei cetăți, iar până și sorțul este așezat sub stăpânirea DOMNULUI.", source: n },
    ],
  },
  17: {
    number: 17,
    title: "Pacea casei și folosirea cuvintelor",
    summary: "O bucată uscată cu pace este preferabilă unei case pline de carne și ceartă. Capitolul vorbește despre prietenie în necaz, pericolul disputei, mita, inima veselă și înțelepciunea de a-ți ține limba.",
    units: [
      { from: 1, to: 7, heading: "Pacea este mai valoroasă decât belșugul unei case sfâșiate", teaching: "O bucată uscată cu liniște este preferată unei case pline de carne și ceartă. Un slujitor înțelept poate ajunge deasupra unui fiu care aduce rușine, ceea ce arată că statutul nu garantează caracter. Așa cum metalul este încercat în foc, DOMNUL încearcă inimile. Ascultarea minciunii și batjocorirea săracului sunt tratate ca probleme morale, iar relația dintre generații poate deveni motiv de onoare.", source: n },
      { from: 8, to: 14, heading: "Mita, acoperirea greșelilor și cearta oprită înainte să izbucnească", teaching: "Darul sau mita poate părea în ochii celui care o folosește o cheie care deschide toate ușile, dar proverbul descrie puterea ei socială fără a o transforma în virtute. Cel care caută dragostea nu repetă continuu greșeala altuia, în timp ce divulgarea ei poate despărți prieteni. Mustrarea pătrunde mai adânc într-un om priceput decât multe lovituri într-un nebun. Începerea unei certe este comparată cu eliberarea apei printr-o breșă: oprirea timpurie este mai înțeleaptă decât escaladarea.", source: n },
      { from: 15, to: 21, heading: "Nu inversa binele și răul; prietenia adevărată rămâne în necaz", teaching: "A declara drept pe cel vinovat și vinovat pe cel drept sunt amândouă condamnate. Banii nu pot cumpăra înțelepciunea dacă lipsește inima care o caută. Prietenul iubește în orice vreme, iar fratele este născut pentru necaz. Garanțiile financiare nechibzuite, iubirea de ceartă și înălțarea propriei porți sunt prezentate ca drumuri spre problemă, iar bucuria unui părinte este legată de înțelepciunea copilului.", source: n },
      { from: 22, to: 28, heading: "Inima veselă, judecata dreaptă și puterea de a tăcea", teaching: "Inima veselă este asociată cu binele trupului, iar duhul zdrobit cu uscarea puterii. Mita ascunsă pentru pervertirea judecății este condamnată direct. Omul priceput își ține privirea spre înțelepciune, în timp ce nebunul rătăcește după lucruri îndepărtate. Finalul elogiază reținerea verbală: chiar un nebun poate părea înțelept când tace, ceea ce arată cât de mult poate dezvălui sau ascunde vorbirea.", source: n },
    ],
  },
  18: {
    number: 18,
    title: "Izolare, vorbire și puterea limbii",
    summary: "Cel care se izolează pentru propriile dorințe respinge sfatul, iar nebunul preferă să-și spună părerea decât să înțeleagă. Viața și moartea sunt puse în puterea limbii, iar prietenia adevărată poate fi mai apropiată decât rudenia.",
    units: [
      { from: 1, to: 8, heading: "Izolarea egoistă și cuvintele care coboară adânc", teaching: "Cel care se separă pentru a-și urma propria dorință se rupe și de înțelepciunea comună. Nebunul nu caută să înțeleagă, ci să își expună opinia. Cuvintele pot fi apă adâncă și izvor de înțelepciune, dar pot deveni și rușine, ceartă sau cursă. Bârfa este descrisă ca o hrană care pătrunde adânc, tocmai pentru a arăta cât de ușor este absorbită și cât de mult poate răni.", source: n },
      { from: 9, to: 12, heading: "Neglijența distruge, bogăția oferă o siguranță imaginară, iar Numele DOMNULUI este turn tare", teaching: "Cel neglijent în muncă este apropiat de cel care distruge. În contrast cu fortăreața imaginară pe care bogatul o vede în averea sa, Numele DOMNULUI este descris ca turn puternic în care cel drept găsește adăpost. Înaintea prăbușirii inima se înalță, iar smerenia precede adevărata onoare.", source: n },
      { from: 13, to: 18, heading: "Ascultă înainte să răspunzi și cercetează ambele părți ale unei cauze", teaching: "A răspunde înainte să asculți este nebunie și rușine. Duhul omului îl poate susține în boală, dar un duh zdrobit este greu de purtat. Omul priceput caută cunoaștere. Într-un conflict, primul vorbitor poate părea convingător până când vine celălalt și îl cercetează; proverbul este un avertisment direct împotriva verdictelor date după o singură versiune.", source: n },
      { from: 19, to: 24, heading: "Conflictul, rodul gurii și prietenul mai apropiat decât un frate", teaching: "Un frate ofensat poate deveni greu de recâștigat, iar certurile pot ajunge ca zăvoarele unei cetăți. Omul mănâncă din rodul gurii lui: vorbirea produce consecințe care se întorc în viața relațională. Afirmația că moartea și viața sunt în puterea limbii descrie această forță reală, nu o magie prin care orice cuvânt rostit creează automat realitatea. Finalul amintește că există prietenii superficiale, dar și un prieten care se ține mai aproape decât un frate.", source: n },
    ],
  },
  19: {
    number: 19,
    title: "Caracterul valorează mai mult decât averea",
    summary: "Integritatea săracului este preferată limbii stricate, iar graba fără cunoaștere duce la greșeală. Capitolul discută prietenia interesată, disciplina copiilor, mila față de sărac și planurile care trebuie așezate sub sfatul DOMNULUI.",
    units: [
      { from: 1, to: 7, heading: "Integritatea este mai valoroasă decât statutul, iar averea poate distorsiona relațiile", teaching: "Sărăcia trăită cu integritate este preferată vorbirii strâmbe și nebuniei. Entuziasmul fără cunoaștere și graba pot duce omul pe un drum greșit, după care el poate ajunge să Îl învinovățească pe Dumnezeu pentru consecințe. Textul observă realist că averea atrage oameni și că săracul poate fi abandonat chiar de apropiați; descrierea nu aprobă oportunismul, ci îl expune.", source: n },
      { from: 8, to: 15, heading: "Înțelepciunea, răbdarea și casa care nu poate fi construită numai din resurse", teaching: "A dobândi înțelepciune este bine pentru propria viață, iar martorul mincinos nu scapă la nesfârșit. Luxul nu se potrivește nebuniei, iar puterea fără caracter este și mai nepotrivită. Priceperea încetinește mânia și poate trece peste o ofensă fără a transforma fiecare greșeală într-un război. Casa și averea pot veni prin moștenire, dar un partener înțelept este prezentat ca dar al lui Dumnezeu. Lenea adâncă duce la lipsă.", source: n },
      { from: 16, to: 23, heading: "Porunca, compasiunea și disciplina orientată spre viață", teaching: "Păzirea poruncii este legată de păzirea vieții, iar nepăsarea față de propriile căi are consecințe. Mila față de sărac este descrisă ca un împrumut făcut DOMNULUI, accentuând valoarea persoanei vulnerabile. Părintele este chemat să își disciplineze copilul cât există speranță, dar nu să transforme corectarea în distrugere. Omul mânios va purta consecințele repetate ale mâniei sale. Frica de DOMNUL este asociată cu viața și odihna.", source: n },
      { from: 24, to: 29, heading: "Lenea caricaturală și corectarea celui care încă poate învăța", teaching: "Leneșul este descris într-o imagine intenționat exagerată: își bagă mâna în vas și nu o mai duce la gură. Lovirea batjocoritorului îl poate avertiza pe cel naiv, iar mustrarea omului priceput îl ajută să înțeleagă. Rușinea familială, disprețul pentru învățătură și martorii batjocoritori pregătesc judecata; înțelepciunea cere ca avertismentul să fie auzit înainte de consecința finală.", source: n },
    ],
  },
  20: {
    number: 20,
    title: "Autocontrol, muncă, sfat și măsuri drepte",
    summary: "Vinul, mânia regelui, lenevia, planurile inimii și greutățile comerciale apar într-o serie de proverbe despre autocontrol și integritate. Omul este avertizat împotriva răzbunării și chemat să-și așeze pașii sub DOMNUL.",
    units: [
      { from: 1, to: 7, heading: "Intoxicarea, conflictul și integritatea care ajunge la generația următoare", teaching: "Vinul și băutura tare sunt personificate ca batjocoritor și gălăgios atunci când îl stăpânesc pe om; cel care este dus în rătăcire de ele nu este înțelept. Mânia regelui poate fi periculoasă, iar provocarea inutilă nu este curaj. Onoarea poate consta tocmai în oprirea unei certe. Leneșul găsește motive să nu lucreze și apoi caută rodul pe care nu l-a pregătit. Planul din inima omului poate fi adânc, dar priceperea îl scoate la suprafață. Integritatea unui drept devine binecuvântare și pentru copiii lui.", source: n },
      { from: 8, to: 15, heading: "Judecata, conștiința propriei imperfecțiuni și comerțul cinstit", teaching: "Regele care judecă este chemat să discearnă răul, dar imediat apare întrebarea care limitează autojustificarea: cine poate spune că și-a curățit inima și este fără păcat? Greutățile și măsurile diferite pentru avantaj comercial sunt urâte de DOMNUL. Chiar copilul își arată caracterul prin fapte. Urechea și ochiul sunt daruri ale Creatorului, iar iubirea somnului în locul muncii duce spre lipsă. Cumpărătorul care denigrează marfa și apoi se laudă cu afacerea arată o altă formă de lipsă de integritate.", source: n },
      { from: 16, to: 23, heading: "Garanțiile, bârfa, moștenirea grăbită și refuzul răzbunării", teaching: "A garanta pentru un străin este tratat ca risc financiar serios. Câștigul obținut prin înșelăciune poate părea dulce la început și amar după aceea. Planurile importante cer sfat, iar războiul are nevoie de strategie. Bârfitorul divulgă taine și nu este un om sigur pentru confidențe. Moștenirea obținută prea repede nu este neapărat binecuvântată la final. În locul răzbunării personale, omul este chemat să aștepte ajutorul DOMNULUI, iar măsurile comerciale false sunt condamnate din nou.", source: n },
      { from: 24, to: 30, heading: "Pașii omului, jurămintele pripite și corectarea răului", teaching: "Pașii omului sunt sub DOMNUL, de aceea capacitatea lui de a-și înțelege complet drumul este limitată. A dedica impulsiv ceva lui Dumnezeu și a calcula abia după aceea este o cursă; zelul religios nu înlocuiește discernământul. Regele drept caută să îndepărteze răul, iar duhul omului este descris ca o lampă prin care adâncurile interioare pot fi cercetate. Bunătatea și adevărul susțin conducerea. Ultimul proverb folosește limbajul antic al loviturii care curăță răul; nu este o licență pentru abuz, ci o imagine severă despre faptul că răul persistent cere corectare reală, nu cosmetizare.", source: n },
    ],
  },
}
