import type { ExplainedOverlayChapter } from "../explainedOverlay.js"

const n = {
  kind: "biblia-emanus" as const,
  note: "rezumat textual fără doctrină adăugată" as const,
}

export const PROVERBE_DEEPENED_21_30: Readonly<Record<number, ExplainedOverlayChapter>> = {
  21: {
    number: 21,
    title: "Dreptatea cântărește mai mult decât aparența religioasă",
    summary: "Capitolul leagă suveranitatea lui Dumnezeu de motivele inimii și pune dreptatea mai presus de jertfa folosită ca mască. Munca, vorbirea, relațiile și atitudinea față de sărac arată caracterul real.",
    units: [
      { from: 1, to: 8, heading: "Inima conducătorului, motivele omului și dreptatea mai presus de ritual", teaching: "Inima regelui este comparată cu un curs de apă pe care DOMNUL îl poate îndrepta. Omului i se poate părea corect propriul drum, dar Dumnezeu cântărește inima. A face dreptate și judecată este pus mai presus de jertfă, ceea ce refuză folosirea religiei ca înlocuitor pentru caracter. Mândria, planurile grăbite și câștigul prin minciună sunt prezentate ca drumuri instabile.", source: n },
      { from: 9, to: 16, heading: "Pacea casei, răul dorit și consecința refuzului de a învăța", teaching: "Este preferată viața într-un colț modest unei case spațioase dominate de ceartă. Dorința celui rău caută răul, iar mila față de aproapele dispare când inima se întărește. Omul simplu poate învăța văzând consecința batjocoritorului, iar cel înțelept învață prin instruire. Dumnezeu răstoarnă casa răului, iar cel care se abate de la calea priceperii ajunge între cei morți.", source: n },
      { from: 17, to: 23, heading: "Plăcerea fără măsură, generozitatea și paza gurii", teaching: "Viața consumată numai pentru plăcere, vin și lux este asociată cu sărăcia. Textul observă și costul conflictelor casnice repetate. Urmărirea dreptății și bunătății este pusă în contrast cu această risipire, iar omul înțelept poate cuceri chiar fortăreața celui puternic. Paza gurii și a limbii este din nou legată de paza sufletului din necazuri.", source: n },
      { from: 24, to: 31, heading: "Mândria, lenevia și limita pregătirii omenești", teaching: "Batjocoritorul este definit prin mândrie, iar dorința leneșului îl consumă tocmai pentru că refuză munca. Omul drept poate dărui fără zgârcenie, în timp ce jertfa celui rău devine și mai respingătoare când este adusă cu intenție rea. Martorul mincinos piere. Finalul spune că omul poate pregăti calul pentru ziua luptei, dar victoria finală aparține DOMNULUI; pregătirea este reală, controlul absolut nu este.", source: n },
    ],
  },
  23: {
    number: 23,
    title: "Autocontrol la masă, față de bani și în dorințe",
    summary: "Capitolul avertizează împotriva lăcomiei, a obsesiei pentru bogăție, a companiei invidioase, a neglijării disciplinei și a intoxicației. Înțelepciunea este cerută în dorințe foarte concrete.",
    units: [
      { from: 1, to: 8, heading: "Masa celui puternic și hrana omului zgârcit cer discernământ", teaching: "În fața unui conducător, omul este chemat la autocontrol și la atenție asupra contextului, nu la abandonarea judecății pentru plăcerea mesei. Apoi bogăția este descrisă ca având aripi: efortul obsesiv pentru avere nu poate oferi siguranță stabilă. Masa omului zgârcit poate ascunde calcule pe care cuvintele lui ospitaliere nu le exprimă.", source: n },
      { from: 9, to: 14, heading: "Nu risipi înțelepciunea unde este disprețuită și nu exploata vulnerabilitatea", teaching: "Nebunul nu prețuiește cuvintele înțelepte, iar mutarea hotarului vechi sau intrarea pe ogorul orfanului reprezintă profit din vulnerabilitatea altuia. Textul afirmă că Apărătorul lor este puternic. Disciplina inimii și a copilului este prezentată ca orientată spre salvarea de nebunie; limbajul antic al nuielei nu autorizează cruzimea sau abuzul.", source: n },
      { from: 15, to: 25, heading: "Inima formată în adevăr nu invidiază păcatul și aduce bucurie părinților", teaching: "Înțelepciunea copilului bucură inima părintelui, iar vorbirea dreaptă aduce aceeași bucurie. Omul este avertizat să nu invidieze pe păcătoși, ci să rămână în frica de DOMNUL, deoarece există un viitor. Compania celor dominați de beție și îmbuibare este prezentată ca drum spre lipsă. Ascultarea părinților și dobândirea adevărului, înțelepciunii și priceperii sunt puse în centrul formării.", source: n },
      { from: 26, to: 35, heading: "Dorința sexuală și intoxicația pot captura inima și percepția", teaching: "Fiul este chemat să își dea inima și să își păzească ochii, deoarece seducția poate deveni o groapă adâncă. Ultima parte descrie foarte concret efectele consumului excesiv de alcool: ceartă, răni, vedere tulburată, vorbire stricată, pierderea simțului pericolului și dorința de a relua consumul după trezire. Textul nu romantizează intoxicația, ci îi arată ciclul distructiv.", source: n },
    ],
  },
  24: {
    number: 24,
    title: "Înțelepciunea zidește, iar răul nu trebuie imitat sau răzbunat",
    summary: "Casa se construiește prin înțelepciune, iar puterea adevărată cere cunoaștere și sfat. Textul cere să nu te bucuri de căderea vrăjmașului, să salvezi pe cel dus la moarte și să nu răspunzi cu răzbunare; finalul arată ogorul leneșului.",
    units: [
      { from: 1, to: 7, heading: "Nu invidia oamenii răi; casa și biruința cer înțelepciune și sfat", teaching: "Capitolul începe interzicând invidia față de oamenii răi și dorința de a fi în compania lor. Casa se zidește prin înțelepciune, se întărește prin pricepere și se umple prin cunoaștere. Puterea reală nu este numai forță brută: sfatul și strategia sunt necesare. Pentru nebun, înțelepciunea rămâne prea înaltă, iar la poarta cetății nu are un cuvânt competent.", source: n },
      { from: 8, to: 14, heading: "Planificarea răului și slăbirea în criză arată ce este în inimă", teaching: "Cel care planifică răul este cunoscut prin această orientare, iar batjocoritorul devine respingător pentru oameni. Dacă puterea se prăbușește în ziua necazului, ea era mică. Imediat urmează porunca de a salva pe cei duși la moarte și de a nu folosi ignoranța simulată ca scuză. Dumnezeu cântărește inima. Înțelepciunea este comparată cu mierea: bună și legată de existența unui viitor și a unei speranțe.", source: n },
      { from: 15, to: 22, heading: "Nu transforma căderea aproapelui în bucurie sau răzbunare", teaching: "Omul rău este avertizat să nu pândească locuința celui drept. Dreptul poate cădea de multe ori și totuși se ridică, în timp ce răul poate rămâne zdrobit de nenorocire. Când vrăjmașul cade, bucuria răzbunătoare este oprită. Omul nu trebuie nici să se consume de invidia celor răi, pentru că viitorul lor nu este sigur. Frica de DOMNUL și respectul pentru autoritate sunt puse lângă evitarea răzvrătirii nechibzuite.", source: n },
      { from: 23, to: 34, heading: "Judecata imparțială, adevărul și ogorul neglijat", teaching: "A favoriza vinovatul în judecată este condamnat, iar mustrarea dreaptă și răspunsul sincer sunt prețuite. Omul este chemat să își pregătească munca înainte să își construiască confortul și să nu depună mărturie falsă sau să răspundă cu răzbunare simetrică. Finalul transformă ogorul leneșului într-o lecție vizuală: spinii, buruienile și zidul căzut nu apar într-o clipă, ci prin neglijență repetată.", source: n },
    ],
  },
  25: {
    number: 25,
    title: "Proverbele lui Solomon copiate de oamenii lui Ezechia",
    summary: "Colecția vorbește despre limite, cuvinte potrivite, relația cu conducătorii și autocontrol. Gloria lucrurilor ascunse este pusă lângă responsabilitatea de a cerceta, iar lipsa stăpânirii de sine este comparată cu o cetate fără ziduri.",
    units: [
      { from: 1, to: 7, heading: "Cercetarea lucrurilor și smerenia înaintea autorității", teaching: "Introducerea leagă colecția de oamenii regelui Ezechia care au copiat proverbele lui Solomon. Dumnezeu este asociat cu taina, iar regii cu cercetarea responsabilă. Îndepărtarea răului din jurul conducerii este comparată cu curățarea zgurii din argint. Omul este sfătuit să nu își revendice singur locul de onoare înaintea regelui; este mai bine să fie chemat mai sus decât coborât public.", source: n },
      { from: 8, to: 14, heading: "Conflictul privat, cuvântul potrivit și mustrarea credincioasă", teaching: "Graba de a transforma o dispută în proces public poate aduce rușine când apar toate faptele. Conflictul trebuie tratat fără divulgarea secretelor altuia. Cuvântul spus la vreme este comparat cu un obiect prețios, iar mustrarea înțeleaptă primită de o ureche care ascultă este la fel de valoroasă. Mesagerul credincios aduce înviorare, în timp ce promisiunea fără faptă seamănă cu nori fără ploaie.", source: n },
      { from: 15, to: 22, heading: "Răbdarea, măsura și binele făcut vrăjmașului", teaching: "Răbdarea și limba blândă pot învinge rezistența. Chiar mierea, lucru bun, devine rea fără măsură. Vizitele excesive pot uza relațiile, iar mărturia falsă este comparată cu arme care rănesc. Încrederea într-un om necredincios în ziua necazului este instabilă. Când vrăjmașul este flămând sau însetat, textul cere hrană și apă, mutând răspunsul de la răzbunare spre bine concret.", source: n },
      { from: 23, to: 28, heading: "Bârfa, conflictul casnic și cetatea fără ziduri a omului fără autocontrol", teaching: "Vântul aduce ploaie, iar vorbirea pe ascuns produce reacții relaționale la fel de reale. Din nou este preferat un colț de acoperiș unei case mari dominate de ceartă. Vestea bună dintr-o țară îndepărtată înviorează ca apa rece. Când omul drept cedează moral înaintea răului, influența lui se tulbură. Căutarea propriei glorii și consumul fără măsură sunt avertizate, iar lipsa stăpânirii de sine este comparată cu o cetate ale cărei ziduri au fost sparte.", source: n },
    ],
  },
  26: {
    number: 26,
    title: "Nebunia, lenevia și bârfa se întrețin singure",
    summary: "Capitolul descrie nepotrivirea onoarei pentru nebun, dificultatea de a răspunde nebuniei și autoînșelarea leneșului. A doua parte urmărește felul în care bârfa și vorbirea prefăcută alimentează certurile.",
    units: [
      { from: 1, to: 5, heading: "Onoarea nepotrivită și discernământul necesar când răspunzi nebuniei", teaching: "Onoarea acordată nebunului este comparată cu zăpada vara: nu se potrivește și poate produce rău. Blestemul fără cauză nu trebuie tratat ca putere inevitabilă. Versetele 4 și 5 stau intenționat unul lângă altul: uneori nu trebuie să răspunzi nebunului în logica lui, alteori trebuie să îi răspunzi ca să nu se creadă înțelept. Înțelepciunea constă în discernerea situației, nu într-o formulă rigidă.", source: n },
      { from: 6, to: 12, heading: "Proverbul în gura nebunului și încrederea în propria înțelepciune", teaching: "A trimite un mesaj printr-un nebun este autovătămare, iar un proverb în gura lui poate deveni inutil sau periculos pentru că nu este înțeles. A-i oferi onoare fără discernământ îl poate întări în nebunie. Revenirea repetată la aceeași eroare este descrisă printr-o imagine dezgustătoare tocmai pentru a arăta caracterul ei autodistructiv. Totuși există ceva și mai greu decât nebunia: omul care este înțelept în propriii lui ochi.", source: n },
      { from: 13, to: 19, heading: "Leneșul inventează pericole, iar omul nechibzuit transformă răul în glumă", teaching: "Leneșul vede un leu imaginar pe drum și folosește pericolul ca justificare pentru inacțiune. Se întoarce în pat ca o ușă în balamale și ajunge atât de pasiv încât gesturile simple devin povară, deși se consideră mai înțelept decât alții. A intra într-o ceartă străină este comparat cu apucarea unui câine de urechi. Omul care rănește și apoi spune «glumeam» este asemănat cu unul care aruncă foc și săgeți fără control.", source: n },
      { from: 20, to: 28, heading: "Bârfa și vorbirea prefăcută țin focul conflictului aprins", teaching: "Fără lemne focul se stinge; fără bârfitor, cearta se liniștește. Omul certăreț funcționează ca un combustibil suplimentar. Cuvintele bârfei pătrund adânc, iar vorbirea frumoasă peste o inimă rea este comparată cu o glazură strălucitoare peste un vas ieftin. Ura poate fi ascunsă prin cuvinte, dar înșelăciunea iese în cele din urmă la lumină. Groapa săpată altuia și piatra rostogolită asupra lui se pot întoarce asupra celui care le-a pregătit.", source: n },
    ],
  },
  27: {
    number: 27,
    title: "Ziua de mâine, mustrarea unui prieten și administrarea atentă",
    summary: "Capitolul avertizează împotriva laudei de sine și a presupunerii că ziua de mâine este garantată. Prietenia sinceră poate răni pentru bine, iar finalul cere cunoașterea stării turmelor și administrarea atentă a resurselor.",
    units: [
      { from: 1, to: 6, heading: "Nu controla ziua de mâine și nu confunda lingușirea cu prietenia", teaching: "Omul nu știe ce aduce ziua următoare, de aceea lauda cu viitorul este o iluzie de control. Lauda de sine este înlocuită cu evaluarea venită din afară. Mânia este grea, dar gelozia poate fi și mai greu de purtat. Mustrarea deschisă poate fi mai bună decât o iubire care nu se exprimă, iar rănile unui prieten credincios sunt puse în contrast cu sărutările înșelătoare ale unui dușman.", source: n },
      { from: 7, to: 14, heading: "Foamea schimbă gustul, iar prietenia și sfatul apropiat au greutate", teaching: "Omul sătul poate disprețui mierea, iar celui flămând chiar amarul îi poate părea dulce; nevoia schimbă percepția. Omul care își părăsește locul fără direcție este comparat cu pasărea departe de cuib. Parfumul și sfatul sincer al unui prieten înveselesc inima. Prietenia veche este prețuită, iar ajutorul apropiat în ziua necazului poate fi mai practic decât o rudă îndepărtată. Chiar binecuvântarea rostită prea zgomotos și prea devreme poate fi primită ca insultă.", source: n },
      { from: 15, to: 22, heading: "Conflictul repetat, influența reciprocă și testul laudei", teaching: "Cearta repetată din casă este comparată cu picurarea continuă. A încerca să o controlezi fără schimbarea inimii poate fi la fel de greu ca prinderea vântului. Fierul ascute fierul, iar oamenii se formează reciproc. Cel care îngrijește un smochin mănâncă din rodul lui, iar slujirea credincioasă aduce onoare. Inima reflectă omul așa cum apa reflectă fața. Dorința umană poate rămâne nesătulă, iar lauda devine un creuzet care arată ce face omul cu aprecierea primită.", source: n },
      { from: 23, to: 27, heading: "Cunoaște starea resurselor tale, pentru că averea nu este permanentă", teaching: "Finalul trece de la observații relaționale la administrare foarte concretă: turmele trebuie cunoscute și îngrijite atent. Averea și coroana nu durează pentru totdeauna. Ciclurile câmpului, fânului și animalelor furnizează hrană și resurse pentru casă. Înțelepciunea nu este numai idee morală, ci și atenție constantă la realitatea bunurilor aflate în grijă.", source: n },
    ],
  },
  28: {
    number: 28,
    title: "Curajul celui drept și pericolul câștigului nedrept",
    summary: "Capitolul contrastează omul rău care fuge fără urmăritor cu cel drept care are curaj. Legea, mărturisirea păcatului, conducerea dreaptă, munca și generozitatea sunt legate de stabilitatea vieții.",
    units: [
      { from: 1, to: 7, heading: "Curajul, conducerea și înțelegerea dreptății", teaching: "Cel rău fuge chiar fără urmăritor, în timp ce cel drept este comparat cu un leu curajos. Instabilitatea unei țări poate produce mulți conducători, dar omul priceput poate aduce continuitate. Un sărac care îi asuprește pe alți săraci este comparat cu o ploaie distrugătoare care nu lasă hrană. Relația cu Legea separă aprobarea răului de împotrivirea față de el, iar cei care caută pe DOMNUL pot înțelege dreptatea mai bine decât cei orientați spre rău.", source: n },
      { from: 8, to: 14, heading: "Câștigul prin exploatare, rugăciunea și mărturisirea păcatului", teaching: "Averea mărită prin dobândă exploatatoare poate ajunge în mâna celui care are milă de săraci. Rugăciunea omului care își întoarce urechea de la Lege este prezentată ca respingătoare, ceea ce leagă spiritualitatea de ascultare. Cel care îi rătăcește pe cei drepți cade în propria groapă. Bogatul se poate crede înțelept, dar omul sărac și priceput îl poate cerceta. Centrul secțiunii este mărturisirea: ascunderea păcatului nu prosperă, iar mărturisirea și părăsirea lui sunt legate de milă.", source: n },
      { from: 15, to: 22, heading: "Conducerea prădătoare și graba după bogăție", teaching: "Un conducător rău peste un popor sărac este comparat cu un leu sau urs care atacă. Lipsa priceperii produce asuprire, iar ura față de câștigul nedrept prelungește stabilitatea. Omul vinovat de sânge trăiește sub povara fugii. Integritatea este mai sigură decât căile strâmbe, iar munca pământului este opusă urmăririi lucrurilor deșarte. Omul credincios poate primi multe binecuvântări, dar cel care se grăbește să se îmbogățească nu rămâne fără vină.", source: n },
      { from: 23, to: 28, heading: "Mustrarea sinceră, lăcomia și generozitatea față de sărac", teaching: "Părtinirea este greșită chiar când prețul compromisului pare mic. Mustrarea sinceră poate aduce în final mai multă bunăvoință decât lingușirea. A lua de la părinți și a numi aceasta nevinovăție este apropiat de distrugere. Omul lacom provoacă ceartă, în timp ce încrederea în DOMNUL este legată de siguranță. Cel care se încrede numai în propria inimă este numit nebun. Generozitatea față de sărac este opusă închiderii ochilor la nevoie.", source: n },
    ],
  },
  29: {
    number: 29,
    title: "Corectarea, conducerea și frica de oameni",
    summary: "Refuzul repetat al mustrării duce la o rupere greu de reparat. Conducerea dreaptă aduce bucurie, disciplina formează, iar frica de oameni este numită cursă în contrast cu încrederea în DOMNUL.",
    units: [
      { from: 1, to: 7, heading: "Mustrarea repetat refuzată și efectul conducerii asupra comunității", teaching: "Omul care își înțepenește gâtul după multe corectări poate ajunge la o prăbușire bruscă. Când cei drepți cresc, poporul se bucură; când răul conduce, oamenii gem. Iubirea înțelepciunii bucură familia, în timp ce risipa legată de imoralitate distruge averea. Dreptatea întărește țara, iar mita o corupe. Lingușirea întinde o plasă, iar omul drept este atent la cauza săracului.", source: n },
      { from: 8, to: 14, heading: "Batjocura aprinde cetatea, iar conducătorul este format de adevărul pe care îl ascultă", teaching: "Batjocoritorii pot incendia social o cetate, în timp ce oamenii înțelepți pot întoarce mânia. Disputa cu nebunul poate continua fără odihnă, iar omul violent urăște integritatea. Nebunul își varsă tot duhul, în timp ce înțeleptul îl ține sub control. Dacă un conducător ascultă minciuna, slujitorii lui se formează în jurul aceleiași corupții. Săracul și asupritorul depind amândoi de același Creator, iar regele care judecă drept pe săraci își întărește tronul.", source: n },
      { from: 15, to: 21, heading: "Disciplina, lipsa revelației și limitele formării prin simplă vorbire", teaching: "Corectarea și disciplina sunt prezentate ca instrumente ale formării copilului, în timp ce abandonarea lui fără limite aduce rușine; aceasta nu autorizează violența abuzivă. Când răul se multiplică, cresc și consecințele lui. Unde nu există viziune sau revelație, poporul se destramă, dar păzirea Legii este numită fericire. Un slujitor nu este format întotdeauna numai prin cuvinte, ceea ce arată limita instrucțiunii care nu produce responsabilitate. Răsfățul fără formare poate produce pretenții distructive.", source: n },
      { from: 22, to: 27, heading: "Mânia, mândria și cursa fricii de oameni", teaching: "Omul mânios provoacă ceartă și înmulțește greșelile. Mândria îl coboară pe om, iar smerenia este legată de onoare. Complicitatea cu hoțul îl pune pe om într-o capcană morală. Frica de oameni este numită direct o cursă, pe când încrederea în DOMNUL este asociată cu siguranță. Mulți caută favoarea conducătorului, dar judecata finală este pusă în mâna DOMNULUI. Conflictul dintre drept și nedrept rămâne profund, nu doar o diferență de stil.", source: n },
    ],
  },
  30: {
    number: 30,
    title: "Cuvintele lui Agur: limitele omului, Cuvântul curat și observația atentă a lumii",
    summary: "Agur își mărturisește limitele și pune întrebări despre Creator, apoi afirmă curăția Cuvântului lui Dumnezeu. Rugăciunea pentru nici sărăcie, nici bogăție este urmată de serii numerice care observă lăcomia, creația și comportamentul uman.",
    units: [
      { from: 1, to: 6, heading: "Smerenia înaintea Creatorului și Cuvântul care nu trebuie completat arbitrar", teaching: "Agur începe nu cu pretenția de superioritate, ci cu recunoașterea limitelor propriei cunoașteri. Întrebările despre urcarea la cer, vânt, ape și hotarele pământului ridică privirea spre Creator. Întrebarea despre numele Lui și numele Fiului Lui apare în acest cadru de uimire. Cuvântul lui Dumnezeu este declarat curat și sigur pentru cel care se refugiază în El, iar omul este avertizat să nu adauge propriile afirmații ca și cum ar avea aceeași autoritate.", source: n },
      { from: 7, to: 14, heading: "Rugăciunea pentru adevăr și suficiență stă între două pericole economice", teaching: "Agur cere două lucruri înainte de moarte: îndepărtarea minciunii și o viață fără extremele sărăciei și bogăției. Motivul nu este comoditatea, ci riscul moral: belșugul îl poate face să uite de Dumnezeu, iar lipsa îl poate împinge spre furt și dezonorarea Numelui Lui. Urmează avertismente despre calomnierea slujitorului, lipsa de respect față de părinți, autojustificare, mândrie și exploatarea săracilor.", source: n },
      { from: 15, to: 23, heading: "Dorința nesătulă și lucrurile pe care Agur le observă ca prea minunate sau greu de purtat", teaching: "Lipitoarea devine imaginea unei dorințe care spune mereu «dă». Mormântul, pântecele fără copii, pământul uscat și focul sunt prezentate ca lucruri care nu spun că este suficient. Disprețul față de părinți primește o imagine severă de judecată. Apoi Agur enumeră patru căi greu de urmărit — vulturul, șarpele, corabia și relația dintre bărbat și femeie — înainte de a arăta cinismul adulterului și patru situații sociale care devin greu de suportat când ordinea și caracterul sunt răsturnate.", source: n },
      { from: 24, to: 33, heading: "Făpturi mici cu înțelepciune și avertismentul final împotriva mândriei care produce ceartă", teaching: "Furnicile, viezurii de stâncă, lăcustele și șopârla arată că mărimea nu este același lucru cu înțelepciunea practică. Urmează imagini ale mersului impunător — leul, cocoșul sau animalul de război în funcție de traducere, țapul și regele cu armata lui. Finalul îl readuce pe om la sine: dacă s-a înălțat nebunește sau a planificat răul, trebuie să își oprească gura. Așa cum presiunea produce unt, sânge sau alte rezultate concrete, provocarea mâniei produce ceartă.", source: n },
    ],
  },
}
