import type { ExplainedOverlayChapter } from "../explainedOverlay.js"
import { textualPsalm } from "./psalmTextualFactory.js"

export const PSALMI_TEXTUAL_51_75: Readonly<Record<number, ExplainedOverlayChapter>> = {
  52: textualPsalm(52, "Limba care se laudă cu răul nu este mai tare decât bunătatea lui Dumnezeu", "Psalmul este legat în titlu de Doeg și contrastează omul puternic care se încrede în bogăție și folosește limba ca pe un brici cu omul care se încrede în bunătatea lui Dumnezeu. Răul poate părea strategic și eficient, dar finalul vede rădăcina lui smulsă, în timp ce psalmistul se compară cu un măslin verde în Casa lui Dumnezeu."),
  53: textualPsalm(53, "Corupția omului fără Dumnezeu și speranța izbăvirii lui Israel", "Psalmul repetă aproape integral tema Psalmului 14: nebunia este trăirea fără recunoașterea lui Dumnezeu, iar privirea Lui asupra oamenilor nu găsește o categorie autosuficientă de oameni care fac binele. Cei care devorează poporul ca pe pâine ajung în frică, iar finalul așteaptă mântuirea venită din Sion."),
  54: textualPsalm(54, "Când străinii se ridică împotriva lui, David Îl numește pe Dumnezeu ajutorul sufletului", "Titlul leagă psalmul de zifiții care îl denunță pe David lui Saul. Rugăciunea este scurtă: Dumnezeu să audă și să judece pe cei violenți; apoi tonul se schimbă prin declarația că Dumnezeu este ajutorul și susținătorul vieții, astfel încât jertfa și lauda apar înaintea rezolvării complete a urmăririi."),
  55: textualPsalm(55, "Mai dureroasă decât violența cetății este trădarea unui prieten apropiat", "David descrie o cetate plină de violență, înșelăciune și apăsare și dorește aripi ca de porumbel pentru a fugi de furtună. Dar rana centrală vine de la un egal și tovarăș cu care mergea la Casa lui Dumnezeu; în acest context apare chemarea de a arunca povara asupra DOMNULUI, care poate susține omul când relația apropiată îl trădează."),
  56: textualPsalm(56, "«Când mă tem, mă încred în Tine» — frica recunoscută și adusă înaintea lui Dumnezeu", "Prins de filisteni la Gat, David nu pretinde că nu simte teamă; formula lui este tocmai transformarea momentului de frică într-un act de încredere. El crede că Dumnezeu îi cunoaște pribegiile și lacrimile și repetă că, dacă Dumnezeu este pentru el, nu trebuie să dea omului ultimul cuvânt asupra vieții."),
  57: textualPsalm(57, "Din peșteră, sub umbra aripilor, inima se trezește pentru laudă", "David cere milă și se ascunde simbolic sub aripile lui Dumnezeu până trece nenorocirea, în timp ce se simte între lei și limbi ca niște săbii. Capcana pregătită de vrăjmași se întoarce asupra lor, iar psalmul se ridică spre refrenul «inima mea este tare» și spre o laudă care vrea să trezească zorile."),
  58: textualPsalm(58, "Judecătorii nedrepți sunt confruntați de Judecătorul care nu poate fi cumpărat", "Psalmul se adresează celor care ar trebui să facă dreptate, dar cântăresc violența în inimă și sunt comparați cu veninul șarpelui. Limbajul de judecată este foarte aspru și aparține rugăciunii împotriva nedreptății instituționalizate; finalul urmărește recunoașterea publică a faptului că există un Dumnezeu care judecă pe pământ, nu autorizarea răzbunării private."),
  59: textualPsalm(59, "Casa este supravegheată de oameni trimiși să-l omoare, dar Dumnezeu rămâne cetatea lui David", "Titlul așază psalmul în noaptea în care oamenii lui Saul păzesc casa lui David. El îi descrie revenind ca niște câini prin cetate și cere ca Dumnezeu să intervină împotriva violenței; între refrene apare însă mărturisirea că Dumnezeu este puterea, fortăreața și Dumnezeul bunătății lui, iar dimineața va deveni timp de cântare."),
  60: textualPsalm(60, "După înfrângere, Israel cere restaurare și refuză să considere ajutorul omenesc suficient", "Psalmul începe cu sentimentul că Dumnezeu a rupt și a făcut țara să se cutremure, apoi cere repararea crăpăturilor și amintește steagul dat celor care se tem de El. Teritoriile și vrăjmașii sunt așezați sub stăpânirea lui Dumnezeu, iar finalul spune că ajutorul omului este zadarnic dacă este tratat ca sursă ultimă de izbăvire."),
  61: textualPsalm(61, "De la marginea pământului, David cere să fie condus la Stânca mai înaltă decât el", "Când inima îi este copleșită, psalmistul nu cere să devină el însuși mai mare, ci să fie condus la stânca pe care nu o poate atinge prin propria înălțime. Imaginea refugiului trece la cort, aripi și apoi la rugăciunea pentru rege, iar finalul leagă protecția de împlinirea zilnică a jurămintelor de laudă."),
  62: textualPsalm(62, "Sufletul așteaptă în tăcere numai de la Dumnezeu, iar bogăția nu trebuie să primească inima", "Refrenul afirmă că Dumnezeu este stâncă, salvare și fortăreață, în timp ce oamenii pot fi ca o suflare indiferent de rang. Psalmul avertizează împotriva încrederii în asuprire, jaf sau creșterea averii și încheie ținând împreună două lucruri: puterea aparține lui Dumnezeu și tot Lui Îi aparține bunătatea."),
  63: textualPsalm(63, "În pustiu, setea după Dumnezeu este mai adâncă decât lipsa apei", "David se află într-un pământ uscat și folosește setea trupului pentru a descrie dorința după Dumnezeu și după puterea văzută în sanctuar. Bunătatea Lui este numită mai bună decât viața, iar sufletul se satură ca de hrană bogată când Îl laudă și Își amintește de El noaptea sub umbra aripilor."),
  64: textualPsalm(64, "Comploturile ascunse și săgețile cuvintelor nu sunt ascunse de Dumnezeu", "Psalmul cere protecție de sfatul secret al celor răi, care își ascut limba și își pregătesc cuvintele ca săgeți trase din ascuns. Ei cred că planul este imposibil de descoperit, dar narațiunea rugăciunii inversează imaginea: Dumnezeu trage propria săgeată, iar limba lor ajunge să lucreze împotriva lor; dreptul se bucură în DOMNUL, nu în propria capacitate de contra-complot."),
  65: textualPsalm(65, "Iertarea, puterea Creatorului și ploaia care pregătește recolta", "Psalmul pornește din Sion, unde Dumnezeu aude rugăciunea și acoperă fărădelegile care îl copleșesc pe om. Privirea se lărgește apoi spre mări, munți și neamuri și ajunge la pământul vizitat cu apă: brazdele sunt înmuiate, anul este încununat cu bunătate, iar pășunile și văile par să strige de bucurie."),
  66: textualPsalm(66, "«Veniți și vedeți» lucrările lui Dumnezeu, apoi «veniți și ascultați» ce a făcut pentru sufletul meu", "Comunitatea este chemată să laude puterea lui Dumnezeu manifestată în istoria izbăvirii și să recunoască faptul că a trecut prin foc și apă ca argintul încercat. În partea finală, vocea devine personală: psalmistul spune ce a făcut Dumnezeu pentru sufletul lui și afirmă că rugăciunea a fost auzită, în timp ce refuză să păstreze nelegiuirea ca alegere iubită în inimă."),
  67: textualPsalm(67, "Binecuvântarea cerută pentru Israel are în vedere cunoașterea căilor lui Dumnezeu între toate neamurile", "Psalmul preia limbajul binecuvântării preoțești — Dumnezeu să lumineze fața peste noi — dar scopul nu se oprește la bunăstarea comunității. Calea și mântuirea Lui trebuie cunoscute pe pământ, popoarele trebuie să se bucure de judecata dreaptă, iar rodirea pământului devine încă un motiv ca marginile lumii să se teamă de Dumnezeu."),
  68: textualPsalm(68, "Dumnezeul care împrăștie vrăjmașii este și Tatăl orfanilor și Apărătorul văduvelor", "Psalmul amplu combină imagini de procesiune, Sinai, pustiu, muntele Sionului și biruință. În centrul acestei puteri, Dumnezeu este descris prin grija pentru orfan, văduvă, singur și captiv; Pavel va folosi imaginea urcării și darurilor în Efeseni 4, iar finalul cheamă împărățiile să cânte Dumnezeului care dă putere poporului."),
  69: textualPsalm(69, "Apele ajung la suflet, râvna pentru Casa lui Dumnezeu aduce reproș și rugăciunea devine foarte aspră", "David descrie scufundarea în noroi, epuizarea strigătului și ura fără motiv, apoi spune că râvna pentru Casa lui Dumnezeu l-a mistuit; Noul Testament citează mai multe expresii ale psalmului în legătură cu Iisus. Secțiunile de imprecație cer judecată într-un limbaj de lamentație vechi-testamentară și nu devin permisiune pentru violență personală; finalul revine la lauda care Îl onorează pe Dumnezeu și la grija Lui pentru cei săraci."),
  70: textualPsalm(70, "O rugăciune de urgență care nu ascunde faptul că omul este sărac și nevoiaș", "Psalmul este aproape în întregime un strigăt: grăbește-Te să mă izbăvești, cei care caută viața mea să fie rușinați, iar cei care Te caută să se bucure. David nu încheie pretinzând autosuficiență, ci spunând că este sărac și nevoiaș și cerând ca Ajutorul și Izbăvitorul să nu întârzie."),
  71: textualPsalm(71, "De la pântecele mamei până la bătrânețe, aceeași gură vrea să vestească dreptatea lui Dumnezeu", "Psalmistul privește o viață întreagă de dependență și cere să nu fie lepădat când puterea îi slăbește. Vrăjmașii interpretează bătrânețea și necazul ca moment potrivit pentru atac, dar rugăciunea cere timp suficient pentru ca generația următoare să audă puterea și dreptatea lui Dumnezeu; bătrânețea nu este tratată ca inutilitate spirituală."),
  72: textualPsalm(72, "Rugăciune pentru un rege a cărui măreție se măsoară prin dreptatea făcută săracului", "Psalmul asociat lui Solomon cere ca regele să judece poporul cu dreptate, să apere copiii săracului și să zdrobească asupritorul. Domnia se lărgește poetic până la marginile pământului și toate neamurile sunt binecuvântate prin el, ceea ce a făcut ca tradiția biblică să citească psalmul în orizont mesianic; centrul rămâne regele care scapă pe săracul fără ajutor."),
  74: textualPsalm(74, "Sanctuarul este devastat, semnele par dispărute, iar comunitatea Îi cere lui Dumnezeu să-Și amintească legământul", "Psalmul privește o ruină în care vrăjmașii au ars și profanat locul sfânt, iar poporul spune că nu mai vede semne și nu știe până când va dura batjocura. Rugăciunea nu își bazează speranța pe clădirea rămasă, ci pe Dumnezeul care este Împărat din vechime și Stăpân peste mare, lumină, soare și anotimpuri; finalul cere apărarea cauzei legământului și a celui apăsat."),
  75: textualPsalm(75, "Dumnezeu stabilește timpul judecății și ridică sau coboară, nu autopromovarea omului", "Comunitatea mulțumește pentru apropierea Numelui lui Dumnezeu, iar El declară că la timpul hotărât judecă drept și susține stâlpii pământului. Psalmul avertizează împotriva ridicării cornului cu mândrie: înălțarea nu vine din punctele cardinale, ci de la Dumnezeu, care coboară pe unul și ridică pe altul."),
}
