import type { ExplainedOverlayChapter } from "../explainedOverlay.js"
import { textualPsalm } from "./psalmTextualFactory.js"

export const PSALMI_TEXTUAL_1_25: Readonly<Record<number, ExplainedOverlayChapter>> = {
  2: textualPsalm(2, "Neamurile se răzvrătesc, dar Împăratul uns de Dumnezeu nu este detronat", "Psalmul privește agitația popoarelor din perspectiva tronului lui Dumnezeu: conspirația lor nu anulează hotărârea Lui privind Împăratul uns. Finalul cheamă conducătorii la înțelepciune, teamă și refugiu în Cel rânduit de Dumnezeu; Noul Testament citează acest psalm în legătură cu Hristos, fără a-l transforma într-o legitimare a dominației politice creștine."),
  3: textualPsalm(3, "Înconjurat de vrăjmași, David Îl numește pe DOMNUL scut și sprijin al capului său", "Titlul așază psalmul în fuga lui David dinaintea lui Absalom. Mulțimea adversarilor și afirmația lor că nu mai există salvare sunt contrazise de rugăciunea omului care poate dormi pentru că DOMNUL îl susține; izbăvirea este cerută de la Dumnezeu, nu extrasă din numărul aliaților."),
  4: textualPsalm(4, "Rugăciune de seară: dreptatea, liniștea inimii și somnul în siguranță", "David răspunde celor care transformă slava în rușine și aleargă după minciună, dar îi cheamă să tremure fără să păcătuiască și să-și cerceteze inima în liniște. Bucuria pe care o primește de la Dumnezeu este pusă deasupra belșugului de grâu și vin, iar somnul devine expresia încrederii în protecția Lui."),
  5: textualPsalm(5, "Dimineața, David își așază cererea înaintea Dumnezeului care iubește dreptatea", "Psalmul unește rugăciunea de dimineață cu o viziune morală clară: răul nu este indiferent înaintea lui Dumnezeu, iar minciuna și violența nu pot fi tratate ca simple stiluri de viață. David cere să fie condus pe calea dreaptă și încheie mutând atenția de la propria teamă spre bucuria celor care se adăpostesc în Dumnezeu."),
  6: textualPsalm(6, "Un om epuizat cere milă și refuză să-și ascundă lacrimile", "David vorbește despre slăbiciune, oase tulburate, nopți udate cu lacrimi și întrebarea «până când?». Psalmul nu rușinează epuizarea; el o transformă în rugăciune și se încheie cu convingerea că DOMNUL a auzit plânsul și cererea, chiar înainte ca împrejurarea exterioară să fie descrisă ca rezolvată."),
  7: textualPsalm(7, "În fața unei acuzații, David cere ca Judecătorul drept să cerceteze cazul", "Psalmul nu se mulțumește cu autojustificare: David este gata să suporte consecințe dacă a făcut răul de care este acuzat și Îl cheamă pe Dumnezeu să judece drept. Răul este descris apoi ca o groapă pe care făptuitorul o sapă și în care poate cădea el însuși, iar finalul Îl laudă pe DOMNUL pentru dreptatea Lui."),
  8: textualPsalm(8, "Măreția Creatorului și demnitatea surprinzătoare dată omului", "Privind cerurile, luna și stelele, psalmistul întreabă de ce omul fragil primește atenția lui Dumnezeu. Răspunsul nu micșorează creația, ci arată rolul primit de om: încununat cu slavă și responsabilitate asupra lucrărilor mâinilor lui Dumnezeu; psalmul începe și se încheie cu măreția Numelui DOMNULUI, nu cu autosuficiența umană."),
  9: textualPsalm(9, "Mulțumire pentru Judecătorul care nu uită strigătul celor apăsați", "David Îl laudă pe Dumnezeu pentru judecarea neamurilor și pentru faptul că tronul Lui este întemeiat pentru dreptate. În centrul psalmului stă speranța celui asuprit: DOMNUL este refugiu în vremuri de necaz și nu uită strigătul celui nenorocit, în timp ce puterea omului este chemată să-și amintească propria mortalitate."),
  10: textualPsalm(10, "Când Dumnezeu pare departe, psalmistul descrie fără cosmetizare aroganța asupritorului", "Psalmul observă cum omul rău urmărește pe cel sărac, se laudă cu poftele lui și își imaginează că Dumnezeu nu vede. Rugăciunea finală răspunde tocmai acestei impresii: Dumnezeu vede necazul, ascultă dorința celor smeriți și face dreptate orfanului și celui apăsat, astfel încât omul din țărână să nu mai inspire teroare."),
  11: textualPsalm(11, "Când temeliile par distruse, David refuză fuga dictată numai de panică", "Cei din jur îi spun lui David să fugă ca o pasăre deoarece cei răi trag din ascuns și temeliile se surpă. El răspunde privind spre templul și tronul ceresc al DOMNULUI: Dumnezeu vede și cercetează pe oameni, iubește dreptatea și nu este evacuat din guvernarea lumii atunci când ordinea umană se clatină."),
  12: textualPsalm(12, "Când minciuna și lingușirea domină conversația publică, cuvintele DOMNULUI rămân curate", "David deplânge dispariția oamenilor credincioși și descrie o societate în care buzele lingușitoare și inima dublă cred că vor domina prin vorbire. În contrast, promisiunile DOMNULUI sunt comparate cu argint curățit, iar Dumnezeu declară că Se ridică pentru cel sărac și pentru omul care suspină sub apăsare."),
  13: textualPsalm(13, "«Până când?» poate sta în aceeași rugăciune cu «mă încred în bunătatea Ta»", "Psalmul începe cu patru întrebări de tip «până când?» și cu sentimentul că Dumnezeu Și-a ascuns fața. David cere lumină ca să nu fie biruit de moarte și vrăjmași, apoi ajunge fără tranziție artificială la încrederea în bunătatea lui Dumnezeu și la cântare pentru binele primit de la El."),
  14: textualPsalm(14, "Corupția universală și speranța unei izbăviri venite din Sion", "«Nebunul» psalmului nu este omul cu capacitate intelectuală mică, ci cel care trăiește ca și cum Dumnezeu nu ar conta. Privirea divină nu găsește un grup autosuficient de oameni curați, iar Pavel va folosi aceste versete în Romani pentru universalitatea păcatului; finalul așteaptă totuși izbăvirea și restaurarea poporului."),
  15: textualPsalm(15, "Cine poate locui în cortul lui Dumnezeu? Viața de închinare este descrisă prin caracter", "Răspunsul la întrebarea despre apropierea de locul sfânt nu enumeră ritualuri spectaculoase, ci integritate, adevăr, refuzul calomniei, respectarea celui ce se teme de DOMNUL și corectitudine financiară. Psalmul nu prezintă aceste fapte ca preț pentru cumpărarea harului, ci descrie caracterul care corespunde vieții înaintea Dumnezeului sfânt."),
  16: textualPsalm(16, "Dumnezeu este partea de moștenire, iar calea vieții se termină în bucuria prezenței Lui", "David cere păzire și declară că binele lui este legat de DOMNUL, nu de alergarea după alți dumnezei. Limitele moștenirii lui sunt descrise ca plăcute, inima se bucură și trupul locuiește în siguranță, iar finalul despre Cel care nu este lăsat în Locuința morților este aplicat în Faptele Apostolilor în mod mesianic lui Iisus."),
  17: textualPsalm(17, "David cere cercetare, protecție și izbăvire de oameni care își primesc partea numai în viața aceasta", "Rugăciunea începe cu cererea ca Dumnezeu să audă o cauză dreaptă și să cerceteze inima, apoi trece la imaginea sensibilă a păzirii ca lumina ochiului și sub umbra aripilor. Finalul contrastează oamenii mulțumiți cu partea lor pământească cu speranța psalmistului de a vedea fața lui Dumnezeu și de a fi săturat de asemănarea Lui."),
  18: textualPsalm(18, "O viață de izbăviri este povestită ca intervenție a Dumnezeului care coboară în furtună", "Psalmul amplu privește retrospectiv eliberarea lui David din mâna vrăjmașilor și a lui Saul. Imaginile cosmice arată cât de mare îi pare intervenția lui Dumnezeu, apoi David vorbește despre felul în care Dumnezeu îl echipează pentru luptă; în cadrul creștin aceste războaie istorice nu devin mandat pentru violență religioasă, iar finalul leagă bunătatea de regele uns și sămânța lui."),
  19: textualPsalm(19, "Cerurile vorbesc fără cuvinte, iar Legea luminează inima și descoperă greșelile ascunse", "Prima jumătate vede creația ca mărturie continuă a slavei lui Dumnezeu, cu soarele parcurgând cerul. A doua trece la revelația verbală: Legea, mărturia, poruncile și frica DOMNULUI sunt curate și prețioase, iar psalmistul răspunde cerând curățire de greșeli ascunse și ca vorbele gurii și meditația inimii să fie primite."),
  20: textualPsalm(20, "Rugăciune pentru rege înaintea luptei: unii se bizuie pe care, noi pomenim Numele DOMNULUI", "Comunitatea se roagă ca regele să fie auzit în ziua necazului, ajutat din sanctuar și susținut în planurile lui. Punctul de contrast este sursa încrederii: carele și caii pot impresiona, dar poporul își amintește Numele DOMNULUI; victoria militară din contextul lui Israel nu devine o teologie a superiorității armelor creștine."),
  21: textualPsalm(21, "Mulțumire după victorie: coroana regelui este dar, nu autosuficiență", "Psalmul răspunde rugăciunii din Psalmul 20 prin bucuria regelui în puterea și mântuirea DOMNULUI. Viața, slava și binecuvântarea sunt descrise ca lucruri primite, iar judecata asupra vrăjmașilor aparține cadrului regal al lui Israel; finalul cheamă adunarea să înalțe puterea lui Dumnezeu, nu ego-ul regelui."),
  22: textualPsalm(22, "De la «Dumnezeul meu, de ce m-ai părăsit?» la laudă înaintea tuturor neamurilor", "Psalmul începe în sentimentul abandonului, trece prin batjocură, vulnerabilitate fizică și vrăjmași care împart hainele, apoi ajunge la răspuns, laudă și o viziune în care toate marginile pământului se întorc la DOMNUL. Evangheliile folosesc mai multe detalii ale psalmului în relatarea crucificării lui Iisus; lamentația și speranța trebuie citite împreună."),
  24: textualPsalm(24, "Pământul aparține DOMNULUI, iar Împăratul slavei intră pe porți", "Psalmul începe cu stăpânirea lui Dumnezeu asupra întregului pământ, apoi întreabă cine poate urca la muntele Lui și răspunde prin mâini curate, inimă curată și refuzul falsității. Finalul personifică porțile chemate să se ridice pentru Împăratul slavei, identificat ca DOMNUL tare și puternic."),
  25: textualPsalm(25, "O rugăciune pentru călăuzire, iertare și prietenia legământului", "David își ridică sufletul spre Dumnezeu și cere să fie învățat căile și adevărul Lui, nu doar scos din probleme. El își amintește păcatele tinereții, cere iertare pentru Numele lui Dumnezeu și afirmă că DOMNUL îi călăuzește pe cei smeriți, în timp ce finalul adună singurătatea, vrăjmașii și nevoia de răscumpărare într-o singură rugăciune."),
}
