import {
  assertCompleteOverlay,
  transcriptFocusedChapters,
  type ExplainedBookOverlay,
  type ExplainedOverlayChapter,
} from "../explainedOverlay.js"

const transcript = ".research/poonen-through-the-bible-OT/transcripts/psalms.txt"
const p = (anchor: string) => ({ kind: "poonen" as const, transcript, anchor })

const focused: Record<number, ExplainedOverlayChapter> = {
  1: {
    number: 1,
    title: "Omul care nu doar evită răul, ci își umple mintea cu Cuvântul",
    summary: "Psalmul 1 contrastează două drumuri. Poonen insistă că viața evlavioasă nu este doar absența răului, ci meditație continuă asupra Cuvântului lui Dumnezeu.",
    units: [{
      from: 1, to: 6,
      heading: "De la evitare la meditație",
      teaching: "Poonen observă că versetul 1 spune ce nu face omul drept, iar versetul 2 spune ce face: își găsește plăcerea în Legea DOMNULUI și meditează la ea zi și noapte. El compară meditația cu digestia: timpul efectiv de citire poate fi scurt, dar adevărul trebuie purtat în minte până devine parte din felul de a trăi. «Tot ce începe duce la bun sfârșit» nu este transformat într-o promisiune de succes financiar pentru orice proiect; prosperitatea psalmului este legată de drumul omului plantat în Cuvânt.",
      source: p("Psalm one ... meditate on the word of God ... tree planted by the rivers"),
      words: [{
        original: "אַשְׁרֵי",
        transliteration: "așrei",
        language: "ebraica",
        meaning: "fericit, binecuvântat în sensul stării de bine a celui aflat pe drumul drept; deschide psalmul ca o declarație despre omul care alege calea lui Dumnezeu.",
        verseRef: "Psalmul 1:1",
        lexicalSource: "WLC-OSHB",
      }],
      forYourHeart: "Nu lăsa sufletul doar golit de lucrurile rele. Cu ce adevăr al lui Dumnezeu îl umpli în mod repetat?",
    }],
  },
  2: {
    number: 2,
    title: "Împărații se ridică împotriva Unsului, dar tronul lui Dumnezeu nu este amenințat",
    summary: "Poonen citește Psalmul 2 ca psalm mesianic și urmărește felul în care Noul Testament îl aplică lui Hristos.",
    units: [{
      from: 1, to: 12,
      heading: "Unsul respins și Fiul căruia Îi aparțin neamurile",
      teaching: "Poonen se oprește la opoziția împăraților față de DOMNUL și Unsul Lui, la declarația «Tu ești Fiul Meu» și la chemarea finală de a te adăposti în El. Lectura lui este mesianică și este susținută de citările Noului Testament. Imaginile judecății aparțin domniei Mesiei și nu sunt mandat pentru creștini de a exercita violență politică în numele Lui.",
      source: p("Psalm 2 ... Messianic Psalm ... thou art my son"),
    }],
  },
  3: {
    number: 3,
    title: "«Tu ești slava mea» spus în fugă de Absalom",
    summary: "Psalmul este legat de fuga lui David de Absalom. Poonen subliniază că unele dintre cele mai puternice cântări biblice au fost scrise sub presiune.",
    units: [{
      from: 1, to: 8,
      heading: "Lauda născută sub presiune",
      teaching: "Poonen pune versetul «Tu ești slava mea și Cel ce-mi înalță capul» în contextul real al fugii lui David. Pentru el, valoarea psalmului stă și în faptul că nu a fost scris din confort. Presiunea nu este bună în sine și nu orice traumă trebuie romanticizată, dar Dumnezeu poate scoate slujire și adevăr matur dintr-o viață care Îl caută în mijlocul presiunii.",
      source: p("Psalm 3 ... running away from Absalom ... my glory and the lifter of my head"),
      forYourHeart: "Cuvintele pe care le spui despre Dumnezeu în ziua grea cântăresc altfel decât cele rostite numai când totul este sigur.",
    }],
  },
  4: {
    number: 4,
    title: "Mânia nu trebuie lăsată să devină păcat",
    summary: "Poonen folosește Psalmul 4:4 ca sfat foarte practic pentru omul mânios: oprește reacția, stai înaintea lui Dumnezeu și liniștește-te.",
    units: [{
      from: 1, to: 8,
      heading: "Oprește-te înainte să vorbești sau să acționezi din mânie",
      teaching: "Poonen leagă Psalmul 4:4 de Efeseni 4 și subliniază: mânia nu trebuie să devină păcat. El citește restul versetului foarte practic — retrage-te, stai liniștit și vorbește cu Dumnezeu înainte să reacționezi. Aceasta nu este o tehnică suficientă pentru situații de violență domestică sau pericol; acolo prioritatea este siguranța. Pentru mânia obișnuită, însă, pauza poate împiedica răul făcut prin cuvinte și impuls.",
      source: p("Psalm 4, verse 4 ... when you're angry ... be still"),
      forYourHeart: "Nu considera fiecare impuls de mânie un mesaj care trebuie transmis imediat. Uneori cea mai spirituală reacție este să taci până când inima se liniștește.",
    }],
  },
  5: {
    number: 5,
    title: "Dimineața, rugăciunea este îndreptată spre Dumnezeu și privirea rămâne în sus",
    summary: "Psalmul 5 devine pentru Poonen un model simplu de a începe ziua cu Dumnezeu.",
    units: [{
      from: 1, to: 12,
      heading: "«Dimineața vei auzi glasul meu»",
      teaching: "Poonen evidențiază versetul 3: rugăciunea este așezată înaintea DOMNULUI dimineața, iar psalmistul așteaptă. El aplică aceasta ca ritm de viață, nu ca regulă legalistă privind ora exactă. Ideea este orientarea zilei spre Dumnezeu înainte ca privirea să fie capturată de toate celelalte lucruri.",
      source: p("Psalm 5 ... My voice shall thou hear in the morning"),
    }],
  },
  7: {
    number: 7,
    title: "Psalmistul își lasă faptele să fie cercetate",
    summary: "Psalmul 7 pune înaintea lui Dumnezeu acuzația și conștiința psalmistului. Poonen folosește textul pentru a sublinia gravitatea păcatelor care îi rănesc pe ceilalți.",
    units: [{
      from: 1, to: 17,
      heading: "Răul făcut altuia nu este mai mic decât păcatul care te rănește numai pe tine",
      teaching: "Poonen se oprește la disponibilitatea psalmistului de a fi cercetat: dacă a răsplătit răul celui pașnic, să fie judecat. El contrastează păcatele care afectează propriul trup cu vorbirea rea care poate distruge și reputația altuia. Comparația lui este pastorală, nu o scară matematică universală a tuturor păcatelor; punctul sigur este că bârfa și defăimarea nu trebuie minimalizate doar fiindcă nu lasă o rană vizibilă.",
      source: p("Psalm 7 ... serious thing to do evil to others ... gossiping"),
      forYourHeart: "Înainte să întrebi numai ce ți-a făcut altul, întreabă curajos dacă tu ai făcut rău prin cuvinte, insinuări sau răzbunare.",
    }],
  },
  8: {
    number: 8,
    title: "Omul sub măreția creației și Fiul Omului în lectura Noului Testament",
    summary: "Poonen urmărește felul în care Psalmul 8 este citat în Evrei și de Iisus.",
    units: [{
      from: 1, to: 9,
      heading: "Măreția lui Dumnezeu, micimea omului și împlinirea în Hristos",
      teaching: "Poonen observă că Psalmul 8 vorbește despre om făcut pentru o vreme mai prejos decât îngerii și despre toate lucrurile puse sub picioarele lui. Evrei aplică pasajul lui Iisus, Care a gustat moartea și este încununat cu slavă. El amintește și citarea despre lauda copiilor. Overlay-ul păstrează această lectură neotestamentară fără a concluziona că fiecare promisiune despre stăpânire înseamnă succes personal nelimitat.",
      source: p("Psalm 8 ... quoted in Hebrews ... Jesus"),
    }],
  },
  15: {
    number: 15,
    title: "Cine poate locui pe muntele sfânt?",
    summary: "Psalmul 15 descrie caracterul celui care umblă în apropierea lui Dumnezeu.",
    units: [{
      from: 1, to: 5,
      heading: "Închinarea și caracterul nu pot fi separate",
      teaching: "Poonen contrastează Psalmul 15 cu descrierea omului rău din psalmul precedent. A locui în cortul DOMNULUI este legat de umblare curată, adevăr în inimă, controlul limbii, dreptate în relații și promisiuni ținute chiar când costă. Psalmul nu descrie o cale de a câștiga mântuirea prin merite, ci caracterul omului care trăiește înaintea lui Dumnezeu.",
      source: p("Psalm 15 ... godly remnant ... who shall abide"),
    }],
  },
  16: {
    number: 16,
    title: "DOMNUL înaintea mea și plinătatea bucuriei în prezența Lui",
    summary: "Poonen citește Psalmul 16 ca mesianic și urmărește atât orientarea inimii spre Dumnezeu, cât și folosirea lui în Noul Testament.",
    units: [{
      from: 1, to: 11,
      heading: "Siguranță, prezență și speranța învierii",
      teaching: "Poonen evidențiază «Îl am necurmat pe DOMNUL înaintea mea» și finalul despre plinătatea bucuriei în prezența lui Dumnezeu. Psalmul este folosit mesianic în Faptele Apostolilor cu privire la înviere. Aplicarea personală rămâne orientarea inimii spre Dumnezeu, nu însușirea directă a fiecărui detaliu mesianic despre Hristos.",
      source: p("Psalm 16 ... messianic ... Lord always before me ... fullness of joy"),
    }],
  },
  19: {
    number: 19,
    title: "Cerurile vorbesc, apoi Legea luminează inima",
    summary: "Psalmul 19 trece de la mărturia creației la mărturia Cuvântului și apoi la rugăciunea personală pentru curăție.",
    units: [{
      from: 1, to: 14,
      heading: "Două mărturii care duc spre cercetarea inimii",
      teaching: "Poonen introduce Psalmul 19 prin ceruri, soare și creație. Psalmul însuși continuă cu desăvârșirea Legii și ajunge la păcatele ascunse și cuvintele gurii. Overlay-ul păstrează această mișcare a textului fără să construiască o teorie suplimentară despre știință și revelație dincolo de ce dezvoltă transcriptul.",
      source: p("Psalm 19 ... heavens creation"),
    }],
  },
  22: {
    number: 22,
    title: "Crucea în Psalmul 22",
    summary: "Poonen grupează Psalmii 22–24 ca trecut, prezent și viitor: crucea, Păstorul de azi și Împăratul slavei.",
    units: [{
      from: 1, to: 31,
      heading: "«Dumnezeul Meu, Dumnezeul Meu, pentru ce M-ai părăsit?»",
      teaching: "Poonen citește Psalmul 22 ca psalm mesianic despre cruce și pornește de la cuvintele rostite de Iisus. Detaliile psalmului sunt legate în Noul Testament de patimile lui Hristos. Suferința psalmistului are propria situație poetică, dar lectura creștină vede împlinirea culminantă în Hristos.",
      source: p("Psalm 22 ... speaks of the cross ... My God, my God"),
    }],
  },
  23: {
    number: 23,
    title: "Păstorul pentru prezent",
    summary: "În schema lui Poonen, după crucea din Psalmul 22 vine viața prezentă sub păstorirea DOMNULUI.",
    units: [{
      from: 1, to: 6,
      heading: "«DOMNUL este Păstorul meu»",
      teaching: "Poonen rezumă Psalmul 23 prin prezent: Păstorul conduce acum. «Nu voi duce lipsă de nimic» nu înseamnă că orice dorință materială este garantată, ci încrederea că Păstorul știe de ce are nevoie oaia pe drumul pe care o conduce. Psalmul trece prin ape liniștite și prin valea umbrei morții fără să schimbe Păstorul.",
      source: p("Psalm 23 ... Lord is my shepherd today ... I shall lack nothing"),
      words: [{
        original: "חֶסֶד",
        transliteration: "hesed",
        language: "ebraica",
        meaning: "bunătate statornică, loialitate iubitoare; în finalul Psalmului 23, bunătatea lui Dumnezeu îl urmărește pe psalmist de-a lungul vieții.",
        verseRef: "Psalmul 23:6",
        lexicalSource: "WLC-OSHB",
      }],
    }],
  },
  24: {
    number: 24,
    title: "Împăratul slavei și intrarea pe muntele DOMNULUI",
    summary: "Poonen leagă Psalmul 24 de viitorul Împăratului slavei și de condiția inimii curate.",
    units: [{
      from: 1, to: 10,
      heading: "Mâini curate înaintea porților deschise pentru Împărat",
      teaching: "Psalmul întreabă cine se poate sui pe muntele DOMNULUI și răspunde prin mâini curate și inimă curată, apoi cheamă porțile să se deschidă pentru Împăratul slavei. Poonen îl așază după Psalmii 22 și 23 ca dimensiunea viitoare a domniei lui Hristos.",
      source: p("Psalm 22, 23 and 24 together ... past present and future"),
    }],
  },
  27: {
    number: 27,
    title: "Un singur lucru cerut: să locuiești înaintea DOMNULUI",
    summary: "Poonen se oprește la dorința centrală a lui David din versetul 4.",
    units: [{
      from: 1, to: 14,
      heading: "Prioritatea care organizează celelalte dorințe",
      teaching: "În mijlocul vrăjmașilor și al fricii, David spune că un singur lucru cere: să locuiască în Casa DOMNULUI, să privească frumusețea Lui și să-L caute. Poonen folosește versetul ca imagine a unei vieți în care prezența lui Dumnezeu este mai importantă decât simpla ieșire din necaz.",
      source: p("Psalm 27, verse 4, one thing I have desired"),
    }],
  },
  32: {
    number: 32,
    title: "Fericirea omului al cărui păcat este iertat și nu mai este ascuns",
    summary: "Psalmul 32 descrie povara tăcerii, mărturisirea și bucuria iertării.",
    units: [{
      from: 1, to: 11,
      heading: "Acoperirea lui Dumnezeu vine după renunțarea la acoperirea proprie",
      teaching: "Poonen introduce Psalmul 32 ca psalm al omului al cărui păcat este acoperit. Psalmistul descrie apoi cum tăcerea l-a uscat și cum mărturisirea a deschis calea iertării. «Fericit» nu înseamnă că păcatul nu a contat, ci că vina nu mai trebuie ascunsă sau purtată ca sentință finală.",
      source: p("Psalm 32 ... person whose sin is covered"),
    }],
  },
  34: {
    number: 34,
    title: "«Voi binecuvânta pe DOMNUL în orice vreme»",
    summary: "Psalmul este legat de o perioadă de primejdie din viața lui David. Poonen accentuează lauda continuă și experiența personală a bunătății lui Dumnezeu.",
    units: [{
      from: 1, to: 22,
      heading: "Lauda care nu depinde de împrejurare",
      teaching: "Poonen pornește de la versetul 1: nu din când în când, ci «în orice vreme». Contextul titlului amintește că David nu scrie dintr-o situație lipsită de pericol. Psalmul cheamă apoi: «Gustați și vedeți ce bun este DOMNUL». Credința nu este numai informație auzită, ci încredere trăită.",
      source: p("Psalm 34 ... I will bless the Lord, not once in a while"),
    }],
  },
  37: {
    number: 37,
    title: "Nu te aprinde din cauza celui rău; încrede-te și fă binele",
    summary: "Psalmul 37 răspunde neliniștii produse de succesul temporar al celor răi.",
    units: [{
      from: 1, to: 40,
      heading: "Plăcerea în DOMNUL, încrederea și răbdarea",
      teaching: "Poonen îl numește un psalm deosebit și se oprește la «desfată-te în DOMNUL», la promisiunea că cei blânzi vor moșteni pământul și la etica banilor. Dorințele inimii nu sunt o listă pe care Dumnezeu este obligat să o satisfacă independent de transformarea inimii; psalmul le leagă de desfătarea în DOMNUL și de încredințarea drumului către El.",
      source: p("Psalm 37 ... delight yourself ... meek will inherit the earth"),
      forYourHeart: "Nu lăsa succesul temporar al altuia să-ți stabilească valorile. Psalmul te cheamă să faci binele în timp ce aștepți dreptatea lui Dumnezeu.",
    }],
  },
  40: {
    number: 40,
    title: "Ascultarea mai adâncă decât simpla jertfă",
    summary: "Poonen citește Psalmul 40 mesianic, iar Evrei folosește pasajul despre venirea Celui care face voia lui Dumnezeu.",
    units: [{
      from: 1, to: 17,
      heading: "«Iată-mă, vin să fac voia Ta»",
      teaching: "Poonen numește Psalmul 40 un psalm despre Iisus. Evrei citează secțiunea despre jertfă și ascultare pentru a vorbi despre Hristos. Aplicarea creștină nu este abolirea arbitrară a tuturor formelor de închinare, ci recunoașterea că Dumnezeu urmărește ascultarea reală, nu ritualul folosit ca înlocuitor al voii Sale.",
      source: p("Psalm 40 ... wonderful Psalm about Jesus"),
    }],
  },
  42: {
    number: 42,
    title: "Sufletul însetat și chemarea repetată de a nădăjdui în Dumnezeu",
    summary: "Poonen deschide a doua carte a Psalmilor cu dorul după Dumnezeu și strigătul unui om apăsat.",
    units: [{
      from: 1, to: 11,
      heading: "Vorbește sufletului tău când el se prăbușește",
      teaching: "Poonen descrie Psalmii 42–44 ca strigăt al unui popor apăsat după izbăvire. Psalmul 42 pune însă și o întrebare interioară: «Pentru ce te mâhnești, suflete al meu?» și îi răspunde: «Nădăjduiește în Dumnezeu». Aceasta nu înseamnă negarea depresiei clinice sau refuzul ajutorului medical; este limbajul spiritual al psalmistului care își îndreaptă speranța spre Dumnezeu în mijlocul apăsării.",
      source: p("book 2 ... Psalm 42 ... remnant longing for deliverance"),
    }],
  },
  45: {
    number: 45,
    title: "Împăratul și mireasa în psalmul mesianic",
    summary: "Poonen citește Psalmul 45 ca psalm mesianic despre Împărat și mireasă, în linia citării din Evrei.",
    units: [{
      from: 1, to: 17,
      heading: "Tronul Împăratului și frumusețea miresei",
      teaching: "Poonen plasează Psalmul 45 între psalmii de izbăvire și îl numește mesianic. Evrei aplică limbajul tronului Fiului. Imaginea miresei este citită creștin în lumina relației lui Hristos cu poporul Lui, fără a transforma fiecare detaliu poetic într-o regulă literală despre căsătorie.",
      source: p("Psalm 45 ... another messianic psalm"),
    }],
  },
  46: {
    number: 46,
    title: "Dumnezeu este adăpost în mijlocul cutremurării",
    summary: "Psalmul fiilor lui Core descrie un refugiu care rămâne când pământul, munții și neamurile se clatină.",
    units: [{
      from: 1, to: 11,
      heading: "«Opriți-vă și să știți că Eu sunt Dumnezeu»",
      teaching: "Poonen introduce Psalmul 46 ca psalm al fiilor lui Core. Firul central al textului este stabilitatea lui Dumnezeu în mijlocul haosului și chemarea de a înceta agitația și a recunoaște domnia Lui. «Dumnezeu este adăpostul nostru» nu promite că oamenii credincioși nu vor trece prin dezastre; psalmul tocmai Îl mărturisește ca refugiu în mijlocul lor.",
      source: p("Psalm 46 ... sons of Korah"),
    }],
  },
  63: {
    number: 63,
    title: "Setea după Dumnezeu în pustiu",
    summary: "David Îl caută pe Dumnezeu într-un pământ uscat. Poonen evidențiază prioritatea acestei căutări.",
    units: [{
      from: 1, to: 11,
      heading: "Mai întâi Dumnezeu, nu numai ieșirea din pustiu",
      teaching: "Poonen citează începutul: «Dumnezeule, Tu ești Dumnezeul meu, pe Tine Te caut dis-de-dimineață». Psalmul nu cere doar schimbarea mediului, ci exprimă setea după Dumnezeu Însuși. Dorul spiritual nu neagă nevoile fizice; imaginea pustiei le face chiar mai reale, dar pune prezența lui Dumnezeu în centrul dorinței.",
      source: p("Psalm 63 ... O God my God early will I seek thee"),
    }],
  },
  72: {
    number: 72,
    title: "Împăratul care judecă drept și apără pe cel sărac",
    summary: "Poonen încheie a doua carte cu Psalmul 72, un psalm al lui Solomon orientat spre domnia dreaptă și, în lectura creștină, spre Împăratul desăvârșit.",
    units: [{
      from: 1, to: 20,
      heading: "Puterea este măsurată prin dreptatea făcută celor vulnerabili",
      teaching: "Psalmul cere ca împăratul să judece poporul cu dreptate, să apere pe sărac și să zdrobească asupritorul. Poonen îl așază în linia izbăvirii prin împărat. Lectura mesianică nu anulează etica vizibilă a psalmului: domnia dreaptă se vede în felul în care tratează oamenii vulnerabili.",
      source: p("Psalm 72 ... psalm of Solomon"),
    }],
  },
  73: {
    number: 73,
    title: "Când prosperitatea celor răi tulbură credința",
    summary: "Asaf aproape alunecă privind viața celor răi, până intră în sanctuar și vede finalul drumului lor. Poonen evidențiază vârful psalmului în versetul 25.",
    units: [{
      from: 1, to: 28,
      heading: "«Pe cine am eu în cer afară de Tine?»",
      teaching: "Poonen numește Psalmul 73:25 unul dintre cele mai frumoase versete: Dumnezeu Însuși devine dorința centrală, dincolo de avantajele pământești. Psalmistul nu rezolvă problema prosperității răului prin negarea faptelor, ci prin schimbarea perspectivei asupra finalului și prin apropierea de Dumnezeu.",
      source: p("Psalm 73 25 ... whom have I in heaven ... nothing on earth I desire beside thee"),
      forYourHeart: "Maturizarea credinței se vede când Dumnezeu nu este doar Cel care îți dă ceea ce dorești, ci devine El Însuși dorința ta.",
    }],
  },
  84: {
    number: 84,
    title: "Până și vrabia găsește un loc lângă altarele DOMNULUI",
    summary: "Psalmul exprimă dorul după curțile lui Dumnezeu și fericirea celui a cărui putere este în El.",
    units: [{
      from: 1, to: 12,
      heading: "Acasă în apropierea lui Dumnezeu",
      teaching: "Poonen se oprește la imaginea vrabiei și rândunicii care găsesc loc lângă altar. Pentru el aceasta exprimă dorința de a locui în apropierea lui Dumnezeu. Psalmul nu declară că o clădire religioasă este singurul loc al prezenței lui Dumnezeu; imaginea templului aparține legământului și devine limbaj al dorului după Dumnezeu.",
      source: p("Psalm 84 ... sparrow has found a house"),
    }],
  },
  91: {
    number: 91,
    title: "Locuința în ascunsul Celui Preaînalt",
    summary: "Poonen spune că ar putea dedica o sesiune întreagă Psalmului 91 și se concentrează pe a locui sub ocrotirea lui Dumnezeu.",
    units: [{
      from: 1, to: 16,
      heading: "Adăpost, nu talisman",
      teaching: "Poonen pune în centru expresia «cel ce locuiește în locul ascuns al Celui Preaînalt». Psalmul folosește promisiuni puternice de ocrotire, dar chiar Satan citează din el în ispitirea lui Iisus; răspunsul lui Iisus arată că promisiunea nu trebuie folosită pentru a-L testa pe Dumnezeu sau pentru a refuza prudența. Psalmul este încredere, nu talisman împotriva oricărui risc.",
      source: p("Psalm 91 ... dwell in the secret place of the most high"),
      forYourHeart: "Încrederea în protecția lui Dumnezeu nu înseamnă să creezi pericole ca să dovedești că El te va salva.",
    }],
  },
  110: {
    number: 110,
    title: "Împărat și preot după rânduiala lui Melhisedec",
    summary: "Poonen evidențiază Psalmul 110:4 și folosirea lui în Evrei pentru preoția lui Hristos.",
    units: [{
      from: 1, to: 7,
      heading: "Preoția mesianică pe care Evrei o explică",
      teaching: "Psalmul 110 este unul dintre textele mesianice cel mai des folosite în Noul Testament. Poonen se oprește la jurământul despre preotul «după rânduiala lui Melhisedec», pe care Evrei îl dezvoltă cu privire la Hristos. Overlay-ul urmează această explicație neotestamentară și nu construiește speculații despre identitatea lui Melhisedec dincolo de Scriptură.",
      source: p("Psalm 110 ... priesthood of Melchizedek ... quoted in Hebrews 7"),
    }],
  },
  119: {
    number: 119,
    title: "Un alfabet întreg al iubirii pentru Cuvânt",
    summary: "Cel mai lung psalm este organizat alfabetic și aproape fiecare verset vorbește într-un fel despre Cuvântul lui Dumnezeu.",
    units: [{
      from: 1, to: 176,
      heading: "Cuvântul ca drum, lumină, hrană și obiect al iubirii",
      teaching: "Poonen subliniază caracterul extraordinar al Psalmului 119: aproape fiecare dintre cele 176 de versete se referă la Lege, porunci, mărturii, judecăți sau alte denumiri ale Cuvântului. În structura celor cinci cărți ale Psalmilor, el îl leagă de accentul deuteronomic asupra Legii. Lungimea nu cere o lectură grăbită, ci arată cât de multe unghiuri are o viață formată de Cuvânt.",
      source: p("Psalm 119 ... every single one of these 176 verses"),
      words: [{
        original: "תּוֹרָה",
        transliteration: "torah",
        language: "ebraica",
        meaning: "învățătură, instrucțiune, Lege; în Psalmul 119 este unul dintre termenii centrali pentru revelația lui Dumnezeu care formează drumul omului.",
        verseRef: "Psalmul 119:1",
        lexicalSource: "WLC-OSHB",
      }],
    }],
  },
  121: {
    number: 121,
    title: "Ajutorul nu vine de dincolo de dealuri, ci de la Creator",
    summary: "În cântarea treptelor, psalmistul își ridică ochii și întreabă de unde îi vine ajutorul.",
    units: [{
      from: 1, to: 8,
      heading: "Sursa ajutorului",
      teaching: "Poonen pune întrebarea într-un cadru concret: ajutorul nu vine de la puterile politice de dincolo de dealuri, ci de la DOMNUL care a făcut cerurile și pământul. Psalmul vorbește despre Păzitorul care nu dormitează și despre drumul omului. Aceasta nu exclude folosirea ajutorului omenesc; mută însă încrederea ultimă din instrument în Dumnezeu.",
      source: p("Psalm 121 ... where shall my help come from ... from the hills? ... No"),
    }],
  },
  127: {
    number: 127,
    title: "Casa, munca și copiii sub darul lui Dumnezeu",
    summary: "Psalmul lui Solomon declară inutilitatea construcției și vegherii independente de DOMNUL și descrie copiii ca moștenire.",
    units: [{
      from: 1, to: 5,
      heading: "Munca este reală, dar nu este suverană",
      teaching: "Poonen întreabă cine a scris psalmul despre casă și copii și răspunde: Solomon. Textul nu condamnă munca — zidarii construiesc și străjerii veghează — ci autonomia care presupune că rezultatul depinde numai de efortul lor. Copiii sunt dar, nu proiect de statut sau garanție că părinții evlavioși vor avea o familie fără suferință.",
      source: p("Psalm 127 ... house and children ... Solomon"),
    }],
  },
  130: {
    number: 130,
    title: "Așteptarea DOMNULUI ca străjerul dimineții",
    summary: "Din adâncuri, psalmistul strigă după iertare și Îl așteaptă pe DOMNUL cu intensitatea unui străjer care așteaptă zorii.",
    units: [{
      from: 1, to: 8,
      heading: "Așteptare legată de iertare și Cuvânt",
      teaching: "Poonen se oprește la versetul 6: sufletul așteaptă mai mult decât străjerii dimineața. Nu este o așteptare goală; psalmistul spune că nădăjduiește în Cuvânt și că la DOMNUL este iertarea și răscumpărarea. Imaginea străjerului descrie certitudinea orientată spre ceea ce încă nu se vede.",
      source: p("Psalm 130 verse 6 ... my soul waits for the Lord more than the watchman"),
    }],
  },
  133: {
    number: 133,
    title: "Unitatea în care este poruncită binecuvântarea",
    summary: "Psalmul descrie frumusețea fraților care locuiesc împreună și o compară cu untdelemnul care curge de pe capul lui Aaron.",
    units: [{
      from: 1, to: 3,
      heading: "Unitate care nu este simplă uniformitate",
      teaching: "Poonen accentuează legătura dintre unitate, ungere și binecuvântare. Imaginea untdelemnului curgând de la cap spre trup îi oferă limbaj pentru o comunitate în care Duhul lucrează în unitate. Unitatea biblică nu înseamnă ascunderea abuzului sau renunțarea la adevăr pentru liniște; psalmul celebrează părtășia fraților, nu protejarea răului.",
      source: p("Psalm 133 ... brothers dwell together in unity ... anointing flows down"),
      words: [{
        original: "יָחַד",
        transliteration: "yachad",
        language: "ebraica",
        meaning: "împreună, în unitate; accentuează locuirea comună a fraților, nu identitatea absolută de opinii sau personalitate.",
        verseRef: "Psalmul 133:1",
        lexicalSource: "WLC-OSHB",
      }],
    }],
  },
  139: {
    number: 139,
    title: "Dumnezeu mă cunoaște, mă vede și îmi cunoaște zilele",
    summary: "Psalmul 139 explorează cunoașterea deplină a omului de către Dumnezeu, imposibilitatea de a fugi de prezența Lui și rugăciunea finală de cercetare.",
    units: [{
      from: 1, to: 24,
      heading: "Cunoscut complet și totuși chemat să fii cercetat",
      teaching: "Poonen spune că s-ar putea petrece mult timp în acest psalm și se oprește la faptul că Dumnezeu cunoaște omul și zilele lui. Psalmul nu este o licență pentru fatalism pasiv; finalul îl face pe psalmist să ceară: «Cercetează-mă... vezi dacă sunt pe o cale rea și du-mă pe calea veșniciei». Cunoașterea lui Dumnezeu produce transparență, nu resemnare.",
      source: p("Psalm 139 ... God knows us ... all the days ... written down"),
      forYourHeart: "Dumnezeu nu descoperă în tine ceva ce Îl surprinde. Tocmai de aceea poți cere fără mască: cercetează-mă și condu-mă.",
    }],
  },
}

const PSALMI_OVERLAY: ExplainedBookOverlay = {
  bookId: "psalmi",
  bibleEmanusBookId: "PSA",
  name: "Psalmii",
  testament: "vt",
  order: 19,
  transcript,
  status: "in_review",
  coverageMode: "transcript-focused",
  chapters: transcriptFocusedChapters("Psalmul", 150, focused),
}

export const PSALMI_EXPLAINED = assertCompleteOverlay(PSALMI_OVERLAY, 150)
