import type { ExplainedOverlayChapter } from "../explainedOverlay.js"
import { textualPsalm } from "./psalmTextualFactory.js"

export const PSALMI_TEXTUAL_76_100: Readonly<Record<number, ExplainedOverlayChapter>> = {
  76: textualPsalm(76, "Dumnezeu este cunoscut în Iuda ca Cel care frânge armele și oprește mânia omului", "Psalmul privește spre Sion ca loc în care Dumnezeu Și-a făcut cunoscut Numele și a rupt săgeți, scut, sabie și război. Puternicii sunt dezarmați înaintea judecății Lui, iar chiar mânia omului este pusă sub limitele stăpânirii divine; finalul cheamă popoarele să se teamă de Cel care poate tăia duhul conducătorilor."),
  77: textualPsalm(77, "Noaptea întrebărilor se schimbă când psalmistul își amintește lucrările lui Dumnezeu", "Asaf strigă fără să găsească mângâiere și întreabă dacă bunătatea și promisiunea lui Dumnezeu s-au sfârșit. Punctul de cotitură nu este negarea durerii, ci hotărârea de a-și aminti minunile, iar memoria ajunge la Exod: apele Îl văd pe Dumnezeu și se cutremură, dar poporul este condus ca o turmă prin Moise și Aaron."),
  78: textualPsalm(78, "Istoria este spusă copiilor ca generația următoare să nu repete o inimă nestatornică", "Psalmul transformă istoria Israelului într-o lecție transmisă copiilor: minunile nu trebuie ascunse, ci povestite pentru ca speranța să fie pusă în Dumnezeu. El urmărește repetatele răzvrătiri din pustiu, mana, plăgile Egiptului, necredincioșia din țară și ajunge la alegerea lui David ca păstor, arătând că memoria harului și a eșecurilor are rol formativ."),
  79: textualPsalm(79, "Templul profanat și Ierusalimul în ruine devin o rugăciune pentru iertare și onoarea Numelui", "Comunitatea plânge peste invazia care a profanat templul, a transformat Ierusalimul în dărâmături și a lăsat morții fără îngropare. Rugăciunea cere ca păcatele generațiilor trecute să nu fie aduse împotriva lor și leagă izbăvirea de slava Numelui lui Dumnezeu, încheind cu poporul care se numește turma pășunii Lui."),
  80: textualPsalm(80, "«Fă să strălucească fața Ta și vom fi salvați» — rugăciunea viei smulse din Egipt", "Refrenul cere restaurarea prin lumina feței lui Dumnezeu, în timp ce poporul este descris hrănit cu pâinea lacrimilor. Imaginea centrală este via scoasă din Egipt și plantată în țară, acum cu gardurile rupte; rugăciunea cere cercetarea viei și întărirea omului de la dreapta lui Dumnezeu pentru ca poporul să nu se mai depărteze."),
  81: textualPsalm(81, "Sărbătoarea și muzica sunt urmate de cuvântul dureros: «poporul Meu nu a ascultat»", "Psalmul începe cu strigăte de bucurie, instrumente și luna nouă, amintind izbăvirea din Egipt și porunca de a nu avea un dumnezeu străin. Apoi Dumnezeu spune că poporul nu a ascultat și a fost lăsat în încăpățânarea inimii; dorința Lui exprimată este ca Israel să asculte, pentru a fi hrănit cu grâul cel mai bun și miere din stâncă."),
  82: textualPsalm(82, "Dumnezeu îi judecă pe cei ce exercită autoritate pentru că nu apără pe cel slab", "Psalmul prezintă pe Dumnezeu stând în adunare și confruntând «dumnezeii» sau conducătorii pentru judecată părtinitoare. Criteriul este foarte concret: apărați pe sărac, orfan și nenorocit și scăpați pe cel lipsit de putere; cei care poartă autoritate rămân muritori, iar rugăciunea finală cere ca Dumnezeu să judece pământul și să moștenească toate neamurile."),
  83: textualPsalm(83, "O coaliție dorește ștergerea numelui lui Israel, iar Asaf cere ca oamenii să caute Numele DOMNULUI", "Psalmul enumeră popoare care se sfătuiesc împreună împotriva lui Israel și cere intervenții asemănătoare izbăvirilor din trecut. Limbajul judecății este puternic, dar chiar în mijlocul lui apare scopul ca oamenii să caute Numele DOMNULUI și să cunoască faptul că El singur este Cel Preaînalt peste pământ."),
  84: textualPsalm(84, "Dorul după curțile DOMNULUI și fericirea omului a cărui putere este în Dumnezeu", "Psalmistul tânjește după locuințele lui Dumnezeu până când sufletul și trupul strigă, observând că până și pasărea găsește un cuib lângă altare. Fericirea aparține celor care locuiesc în Casă și celor care găsesc în Dumnezeu puterea pentru drum, iar o singură zi în curțile Lui este preferată unei mii în altă parte."),
  85: textualPsalm(85, "Restaurarea trecută devine rugăciune pentru o nouă înviorare și pentru întâlnirea dintre bunătate și adevăr", "Psalmul începe amintind că Dumnezeu a întors captivitatea și a iertat vina, dar prezentul încă are nevoie de restaurare: «nu ne vei înviora iarăși?». Așteptarea răspunsului se concentrează pe pace pentru popor și pe imaginea poetică în care bunătatea și adevărul se întâlnesc, dreptatea și pacea se sărută, iar pământul dă rod."),
  86: textualPsalm(86, "«Învață-mă calea Ta și unește-mi inima ca să mă tem de Numele Tău»", "David se prezintă ca sărac și nevoiaș și își sprijină cererea pe bunătatea și iertarea lui Dumnezeu, nu pe importanța lui. În mijlocul vrăjmașilor cere o inimă unită, nu împărțită, pentru a umbla în adevăr și a se teme de Numele Lui, apoi Îl laudă ca Dumnezeu milos, îndurător, încet la mânie și bogat în bunătate."),
  87: textualPsalm(87, "Sionul este descris ca loc în care oameni din neamuri diferite sunt numărați ca născuți acolo", "Psalmul iubește porțile Sionului și apoi surprinde prin enumerarea Rahabului, Babilonului, Filistiei, Tirului și Etiopiei între cei despre care se spune «acesta s-a născut acolo». Registrul final este ținut de DOMNUL, iar cântăreții spun că toate izvoarele lor sunt în cetatea pe care El o întemeiază."),
  88: textualPsalm(88, "Rugăciunea care se termină în întuneric și nu este obligată să producă un final luminos", "Heman strigă zi și noapte, se simte socotit printre cei coborâți în groapă și descrie prietenii îndepărtați și mânia care îl copleșește. Spre deosebire de multe lamentații, psalmul nu face o întoarcere vizibilă spre rezolvare; Scriptura păstrează astfel și rugăciunea omului care continuă să vorbească lui Dumnezeu chiar când ultimul cuvânt resimțit este întunericul."),
  89: textualPsalm(89, "Legământul cu David este cântat cu încredere, apoi pus lângă experiența dureroasă a unui tron aparent lepădat", "Etan începe proclamând bunătatea și credincioșia lui Dumnezeu și dezvoltă promisiunea făcută lui David și seminței lui. Dar a doua jumătate spune că unsul pare lepădat, coroana profanată și zidurile rupte; rugăciunea nu abandonează legământul, ci Îi cere lui Dumnezeu să-Și amintească bunătatea și reproșul purtat de slujitorii Lui."),
  90: textualPsalm(90, "Dumnezeul veșnic și omul care se întoarce în țărână: «învață-ne să ne numărăm zilele»", "Rugăciunea lui Moise pune veșnicia lui Dumnezeu lângă fragilitatea generațiilor care sunt ca iarba și ca un vis de dimineață. Conștiența mâniei și a vieții scurte produce cererea de înțelepciune, saturare cu bunătate, bucurie după zilele de necaz și stabilirea lucrării mâinilor noastre de către Dumnezeu."),
  92: textualPsalm(92, "Cântare pentru Sabat: lucrările lui Dumnezeu sunt adânci, iar cel drept înflorește și la bătrânețe", "Psalmul spune că este bine să vestești dimineața bunătatea și noaptea credincioșia lui Dumnezeu și se bucură de lucrările Lui. Cei răi pot înflori ca iarba pentru o vreme, dar nu au aceeași rădăcină; omul drept este comparat cu palmierul și cedrul plantat în Casa DOMNULUI, care aduce rod chiar la bătrânețe."),
  93: textualPsalm(93, "DOMNUL domnește mai presus de vuietul apelor, iar sfințenia se potrivește Casei Lui", "Psalmul începe nu cu o cerere, ci cu proclamarea domniei: Dumnezeu este îmbrăcat în măreție, iar lumea este stabilită sub stăpânirea Lui. Râurile și valurile își ridică glasul, dar DOMNUL din înălțime este mai puternic, iar mărturiile Lui sunt foarte sigure și sfințenia caracterizează Casa Lui."),
  94: textualPsalm(94, "Dumnezeul răzbunărilor este chemat să judece pe cei care zdrobesc văduva, străinul și orfanul", "Psalmul nu cere individului să-și ia răzbunarea în propriile mâini, ci o duce înaintea Judecătorului pământului. Cei răi cred că Dumnezeu nu vede, dar Cel care a făcut urechea și ochiul cunoaște gândurile omului; disciplina Lui poate ferici omul pe care îl învață, iar când piciorul alunecă bunătatea Lui îl susține."),
  95: textualPsalm(95, "Închinarea înaintea Creatorului și Păstorului este urmată de avertismentul: «astăzi, dacă auziți glasul Lui»", "Prima parte cheamă la cântare, mulțumire și plecare înaintea Dumnezeului care a făcut adâncurile, munții și marea și al Cărui popor este turma mâinii Lui. A doua trece brusc la pustiu: inima nu trebuie împietrită ca la Meriba, iar Evrei va folosi acest «astăzi» pentru chemarea la credință și ascultare."),
  96: textualPsalm(96, "Cântați DOMNULUI o cântare nouă și vestiți zilnic mântuirea între neamuri", "Lauda nu este închisă în Israel: toate familiile popoarelor sunt chemate să dea DOMNULUI slavă și să spună între neamuri că El domnește. Idolii sunt contrastați cu Creatorul cerurilor, iar cerul, pământul, marea, câmpul și copacii se bucură pentru venirea Judecătorului care va judeca lumea cu dreptate și adevăr."),
  97: textualPsalm(97, "DOMNUL domnește în foc și nor, iar idolii se pleacă înaintea Lui", "Psalmul descrie domnia prin nori, întuneric, foc și fulgere care fac pământul să tremure, în timp ce dreptatea și judecata sunt temelia tronului. Închinarea la chipuri este rușinată, Sionul se bucură, iar celor ce iubesc pe DOMNUL li se spune să urască răul, cu promisiunea luminii semănate pentru cel drept."),
  98: textualPsalm(98, "Mântuirea este făcută cunoscută înaintea neamurilor, iar creația întreagă cântă", "Cântarea nouă răspunde lucrurilor minunate făcute de Dumnezeu și faptului că dreptatea și salvarea Lui sunt descoperite înaintea națiunilor. Marea, râurile și munții sunt personificați ca participanți la laudă deoarece DOMNUL vine să judece pământul cu dreptate și popoarele cu echitate."),
  99: textualPsalm(99, "Împăratul sfânt iubește dreptatea și a răspuns unor slujitori reali care au avut nevoie și de iertare", "Dumnezeu domnește peste heruvimi și este înălțat în Sion, iar sfințenia Lui este repetată ca refren. Moise, Aaron și Samuel sunt amintiți ca oameni care chemau Numele și primeau răspuns; Dumnezeu îi ierta, dar textul spune și că pedepsea faptele lor, arătând că relația cu El nu transformă conducătorii spirituali în oameni dincolo de responsabilitate."),
  100: textualPsalm(100, "Tot pământul este chemat să slujească cu bucurie Dumnezeului care ne-a făcut și ne păstorește", "Psalmul foarte scurt cheamă la strigăt de bucurie, slujire și intrare cu mulțumire în porțile lui Dumnezeu. Motivul este identitatea: El este Dumnezeu, El ne-a făcut, iar noi suntem poporul și oile pășunii Lui; bunătatea și credincioșia Lui continuă din generație în generație."),
}
