import type { ExplainedOverlayChapter } from "../explainedOverlay.js"
import { textualPsalm } from "./psalmTextualFactory.js"

export const PSALMI_TEXTUAL_101_125: Readonly<Record<number, ExplainedOverlayChapter>> = {
  101: textualPsalm(101, "Un rege își propune să înceapă dreptatea în propria casă și în oamenii pe care îi apropie", "David cântă despre bunătate și judecată și cere înțelepciune pentru a umbla cu inimă integră în casa lui. El refuză lucrul rău, calomnia, privirea trufașă și înșelăciunea și spune că ochii lui vor fi asupra credincioșilor țării; idealul regal începe cu caracterul curții, nu doar cu legi pentru ceilalți."),
  102: textualPsalm(102, "Rugăciunea celui copleșit trece de la zile care se sting la Dumnezeul care rămâne din generație în generație", "Psalmistul descrie zile ca fumul, oase arse, singurătate și puterea pierdută sub necaz. Apoi perspectiva se mută spre DOMNUL care rămâne în veci, spre restaurarea Sionului și spre generații încă nenăscute care vor auzi lucrarea Lui; finalul pune cerul și pământul schimbător lângă Creatorul neschimbat, limbaj preluat în Evrei despre Fiul."),
  103: textualPsalm(103, "«Binecuvântează, suflete, pe DOMNUL și nu uita niciuna din binefacerile Lui»", "David își cheamă propriul suflet să-și amintească iertarea, vindecarea, răscumpărarea și bunătatea lui Dumnezeu. DOMNUL este milos și încet la mânie, nu ne răsplătește după păcate, îndepărtează fărădelegile ca răsăritul de apus și are milă ca un tată, cunoscând că omul este țărână și iarba trecătoare."),
  104: textualPsalm(104, "O cântare a creației în care lumina, apele, animalele, anotimpurile și marea depind de Creator", "Psalmul Îl descrie pe Dumnezeu îmbrăcat cu lumină și întinzând cerurile, apoi urmărește apele, munții, izvoarele, păsările, animalele, luna și soarele în ritmurile lor. Marea este plină de făpturi, inclusiv Leviatanul, iar toate așteaptă hrana și suflarea de la Dumnezeu; creația nu este autonomă, ci trăiește prin continua Lui purtare de grijă."),
  105: textualPsalm(105, "Covenantul este povestit prin Avraam, Iosif, Moise și Exod pentru ca poporul să-și amintească", "Psalmul cheamă la mulțumire și la povestirea lucrărilor lui Dumnezeu, apoi urmărește legământul cu patriarhii, foametea, trimiterea lui Iosif înaintea familiei și ridicarea lui în Egipt. Istoria continuă cu Moise, plăgile, ieșirea cu argint și aur, norul, focul, mana și țara promisă, încheindu-se cu scopul ascultării de rânduielile Lui."),
  106: textualPsalm(106, "Mărturisirea păcatelor naționale stă lângă memoria bunătății lui Dumnezeu", "Comunitatea spune «am păcătuit împreună cu părinții noștri» și trece prin Marea Roșie, poftele din pustiu, vițelul de aur, refuzul țării, Baal-Peor și amestecul cu popoarele. Repetiția nu urmărește rușinarea fără speranță, ci contrastul dintre răzvrătire și mila repetată; finalul cere ca Dumnezeu să adune din nou poporul pentru a-I mulțumi."),
  107: textualPsalm(107, "Patru feluri de oameni ajung la capătul puterii și strigă către DOMNUL", "Cei rătăciți în pustiu, prizonierii în întuneric, bolnavii ajunși aproape de moarte și marinarii prinși în furtună repetă același tipar: strigă în necaz, Dumnezeu îi scoate, iar ei sunt chemați să-I mulțumească pentru bunătate. Finalul cere omului înțelept să observe aceste lucruri și să înțeleagă bunătățile DOMNULUI în schimbările istoriei."),
  108: textualPsalm(108, "Inima hotărâtă pentru laudă și cererea de ajutor pe care omul nu îl poate produce", "Psalmul combină secțiuni cunoscute din Psalmii 57 și 60: inima este tare, instrumentele sunt trezite, iar bunătatea lui Dumnezeu este mai înaltă decât cerurile. Apoi comunitatea cere izbăvire și privește teritoriile și vrăjmașii sub stăpânirea Lui, încheind cu aceeași mărturisire că ajutorul omului este zadarnic ca sursă ultimă."),
  109: textualPsalm(109, "Acuzat și răsplătit cu ură pentru dragoste, David duce înaintea lui Dumnezeu o rugăciune foarte aspră", "Psalmul începe cu minciuni, acuzații și oameni care răsplătesc binele cu rău, iar secțiunea de imprecație cere consecințe severe asupra acuzatorului. Acest limbaj aparține rugăciunii vechi-testamentare de judecată și nu autorizează vătămarea familiei unui adversar; finalul revine la omul sărac și nevoiaș care cere ca Dumnezeu să-l salveze și să stea la dreapta lui împotriva celor ce îl condamnă."),
  110: textualPsalm(110, "Regele la dreapta DOMNULUI și preotul după rânduiala lui Melhisedec", "Psalmul regal spune «DOMNUL a zis Domnului meu: șezi la dreapta Mea» și leagă domnia de o preoție care nu vine din linia obișnuită a lui Aaron. Noul Testament îl citează frecvent cu referire la Iisus, iar Evrei dezvoltă în mod special imaginea preotului după rânduiala lui Melhisedec; conflictul regal din psalm nu devine program de violență pentru biserică."),
  111: textualPsalm(111, "Lucrările lui Dumnezeu merită cercetate, iar frica de DOMNUL este începutul înțelepciunii", "Psalmistul laudă din toată inima în adunare și descrie lucrările lui Dumnezeu ca mari, vrednice de cercetare, pline de slavă și dreptate. El amintește legământul, hrana și puterea arătată poporului și încheie legând adevărata pricepere de frica de DOMNUL și de practicarea poruncilor Lui."),
  112: textualPsalm(112, "Omul care se teme de DOMNUL poate primi vești rele fără ca inima să-i fie mutată din încredere", "Psalmul descrie binecuvântarea omului care găsește plăcere în poruncile lui Dumnezeu și este caracterizat prin îndurare, dreptate și generozitate. El nu este promis ca scutit de vești rele, ci ca om cu inimă stabilă care se încrede în DOMNUL și împrăștie daruri săracilor, în timp ce dorința celui rău se stinge."),
  113: textualPsalm(113, "Dumnezeul înălțat peste ceruri Se apleacă să ridice pe sărac din țărână", "Slujitorii sunt chemați să laude Numele DOMNULUI de la răsărit până la apus, deoarece slava Lui este mai presus de ceruri. Tocmai Dumnezeul atât de înalt Se pleacă să privească, ridică pe cel sărac din praf și pe cel lipsit din gunoi și dă o casă femeii fără copii; măreția Lui nu produce distanță față de vulnerabili."),
  114: textualPsalm(114, "Exodul este cântat ca moment în care marea fuge, Iordanul se întoarce și munții sar", "Psalmul foarte scurt descrie ieșirea din Egipt și devenirea lui Iuda ca sanctuar și a lui Israel ca domeniu al lui Dumnezeu. Natura este personificată în fața prezenței Lui: marea, Iordanul, munții și dealurile reacționează, iar Cel care transformă stânca în apă este motivul pentru care pământul trebuie să tremure."),
  115: textualPsalm(115, "«Nu nouă, ci Numelui Tău dă slavă» — Dumnezeul viu și idolii făcuți de mâini", "Psalmul răspunde întrebării neamurilor «unde este Dumnezeul lor?» spunând că Dumnezeul nostru este în ceruri și face ce voiește. Idolii au gură, ochi, urechi și mâini fără viață, iar cei care îi fac devin asemenea lor; Israel, casa lui Aaron și cei ce se tem de DOMNUL sunt chemați în schimb să se încreadă în Ajutorul și Scutul lor."),
  116: textualPsalm(116, "«Iubesc pe DOMNUL pentru că a auzit glasul meu» — recunoștință după apropierea morții", "Psalmistul își amintește lațurile morții și necazul în care a chemat Numele DOMNULUI, apoi spune că Dumnezeu i-a izbăvit sufletul, ochii de lacrimi și picioarele de cădere. El întreabă ce poate întoarce pentru binefaceri și răspunde prin paharul mântuirii, chemarea Numelui și împlinirea jurămintelor, afirmând că moartea celor credincioși este prețioasă înaintea lui Dumnezeu."),
  117: textualPsalm(117, "Cel mai scurt psalm lărgește lauda la toate neamurile", "Doar două versete sunt suficiente pentru a chema toate națiunile și toate popoarele să-L laude pe DOMNUL. Motivul nu este superioritatea unui popor asupra altuia, ci bunătatea puternică și credincioșia veșnică a lui Dumnezeu; Pavel citează această chemare în Romani 15 în contextul includerii neamurilor în laudă."),
  118: textualPsalm(118, "Din strâmtorare spre piatra lepădată care ajunge capul unghiului", "Psalmul repetă că bunătatea DOMNULUI ține în veci și povestește cum strigătul din strâmtorare a primit răspuns, astfel încât frica de om este relativizată. Imaginea pietrei respinse de zidari, ziua făcută de DOMNUL și strigătul «salvează, Te rugăm» sunt reluate în Noul Testament în jurul lui Iisus și intrării Lui în Ierusalim."),
  120: textualPsalm(120, "Prima cântare a treptelor începe între buze mincinoase și oameni care urăsc pacea", "Psalmistul spune că în necaz a strigat și a fost auzit, apoi cere izbăvire de limba înșelătoare. Viața printre Meșec și corturile Chedarului este descrisă ca exil printre oameni ai conflictului: el este pentru pace, dar când vorbește, ceilalți sunt pentru război."),
  121: textualPsalm(121, "Ajutorul nu vine din munți, ci de la Făcătorul cerului și al pământului care păzește", "Pelerinul își ridică ochii spre munți și răspunde propriei întrebări: ajutorul vine de la DOMNUL, Creatorul. Repetiția verbului «a păzi» domină psalmul: Păzitorul lui Israel nu dormitează, umbrește călătorul și îi păzește ieșirea și intrarea, viața fiind așezată sub o grijă care nu adoarme."),
  122: textualPsalm(122, "Bucuria drumului spre Casa DOMNULUI se transformă în rugăciune pentru pacea Ierusalimului", "David se bucură la invitația de a merge la Casa DOMNULUI și descrie Ierusalimul ca cetate în care semințiile se adună pentru mulțumire și unde sunt așezate scaunele de judecată. Iubirea pentru cetate nu este doar entuziasm civic: psalmul cere pace pentru frați și caută binele locului pentru Casa lui Dumnezeu."),
  123: textualPsalm(123, "Ochii slujitorului rămân spre mâna stăpânului până vine mila", "Pelerinul își ridică ochii spre Dumnezeul care locuiește în ceruri și folosește imaginea slujitorilor care urmăresc mâna stăpânului pentru direcție și ajutor. Comunitatea este sătulă de disprețul celor liniștiți și mândri, dar răspunsul ei repetat este cererea de milă, nu încercarea de a obține valoare prin aprobarea batjocoritorilor."),
  124: textualPsalm(124, "«Dacă n-ar fi fost DOMNUL pentru noi» — recunoașterea izbăvirii după ce pericolul a trecut", "Israel este invitat să repete că, fără DOMNUL, oamenii care s-au ridicat împotrivă i-ar fi înghițit ca ape revărsate. Imaginile se schimbă de la torent la dinți și la pasărea scăpată din laț, iar finalul numește sursa ajutorului: Numele DOMNULUI, Făcătorul cerului și pământului."),
  125: textualPsalm(125, "Cei ce se încred în DOMNUL sunt comparați cu Sionul înconjurat de munți", "Psalmul folosește geografia Ierusalimului pentru o imagine a stabilității și protecției: munții înconjoară cetatea, iar DOMNUL înconjoară poporul. Totuși textul recunoaște existența sceptrului răutății și avertizează că cei ce se abat spre căi strâmbe merg cu făcătorii de rele, încheind cu pace asupra lui Israel."),
}
