// Generated by scripts/generate-content-manifest.mjs. Do not edit manually.
export const GENERATED_CONTENT_MANIFEST = {
  "schemaVersion": 1,
  "rooms": [
    {
      "id": "c1",
      "title": "Nu mă vrea așa cum sunt",
      "lie": "Sunt prea murdar pentru El.",
      "pathId": "path_acasa"
    },
    {
      "id": "c2",
      "title": "Nu e bun / m-a lăsat",
      "lie": "Dacă era bun, nu s-ar fi întâmplat.",
      "pathId": "path_neiertare"
    },
    {
      "id": "c3",
      "title": "Nu e real / nu se poate ști",
      "lie": "Poate e doar o poveste.",
      "pathId": "path_temelie"
    },
    {
      "id": "c4",
      "title": "E departe, nu mă aude",
      "lie": "Am rămas singur pe drum.",
      "pathId": "path_aproape"
    },
    {
      "id": "c5",
      "title": "Nu mă pot schimba",
      "lie": "Sunt defect, asta sunt.",
      "pathId": "path_schimbare"
    },
    {
      "id": "c6",
      "title": "Trebuie să merit",
      "lie": "Mă iubește cât de bun sunt.",
      "pathId": "path_har"
    },
    {
      "id": "c7",
      "title": "Sunt singur în asta",
      "lie": "Nimeni nu înțelege și nimănui nu-i pasă.",
      "pathId": "path_impreuna"
    }
  ],
  "doors": [
    {
      "id": "rusine",
      "label": "Am făcut lucruri de care mi-e rușine",
      "roomId": "c1",
      "common": true
    },
    {
      "id": "neiertare",
      "label": "Mi s-a făcut ceva și nu pot ierta",
      "roomId": "c2",
      "common": true
    },
    {
      "id": "indoiala",
      "label": "Nu știu dacă există Dumnezeu",
      "roomId": "c3",
      "common": true
    },
    {
      "id": "perete",
      "label": "Mă rog și parcă vorbesc în perete",
      "roomId": "c4",
      "common": true
    },
    {
      "id": "dependenta",
      "label": "Nu mă pot lăsa de un lucru",
      "roomId": "c5",
      "common": true
    },
    {
      "id": "anxietate",
      "label": "Trăiesc cu anxietate",
      "roomId": "c5",
      "common": true
    },
    {
      "id": "doliu",
      "label": "Am pierdut pe cineva",
      "roomId": "c2",
      "common": true
    },
    {
      "id": "merit",
      "label": "Fac tot ce trebuie și tot nu-mi ajunge",
      "roomId": "c6",
      "common": true
    },
    {
      "id": "singuratate",
      "label": "Nu am pe nimeni",
      "roomId": "c7",
      "common": true
    },
    {
      "id": "nu_inteleg",
      "label": "Sunt creștin, dar nu înțeleg ce citesc",
      "roomId": "c3",
      "common": true
    },
    {
      "id": "obisnuinta",
      "label": "Merg la biserică din obișnuință",
      "roomId": "c6"
    },
    {
      "id": "avort",
      "label": "Am făcut un avort",
      "roomId": "c1"
    },
    {
      "id": "biblia_inventata",
      "label": "Cred că Biblia e inventată de oameni",
      "roomId": "c3"
    },
    {
      "id": "recadere",
      "label": "Am promis de o sută de ori și tot cad",
      "roomId": "c5"
    },
    {
      "id": "uscaciune",
      "label": "Nu mai simt nimic când mă rog",
      "roomId": "c4"
    },
    {
      "id": "familie_respinge",
      "label": "Familia mea nu mă înțelege",
      "roomId": "c7"
    },
    {
      "id": "boala",
      "label": "Sunt bolnav sau e bolnav cineva drag",
      "roomId": "c2"
    },
    {
      "id": "infidelitate",
      "label": "Mi-am înșelat soțul sau soția",
      "roomId": "c1"
    },
    {
      "id": "flacara",
      "label": "Am fost aproape de Dumnezeu cândva",
      "roomId": "c4"
    },
    {
      "id": "frica_pedeapsa",
      "label": "Mi-e frică să nu mă pedepsească",
      "roomId": "c6"
    },
    {
      "id": "respins_biserica",
      "label": "M-am simțit respins în biserică",
      "roomId": "c7"
    },
    {
      "id": "de_ce_permis",
      "label": "Nu înțeleg de ce a permis Dumnezeu asta",
      "roomId": "c2"
    },
    {
      "id": "pornografie",
      "label": "Mă lupt cu pornografia",
      "roomId": "c1"
    },
    {
      "id": "tristete",
      "label": "Nu mai am chef de nimic",
      "roomId": "c5"
    },
    {
      "id": "alte_credinte",
      "label": "Am crezut alte lucruri înainte (energii, karma, univers)",
      "roomId": "c3"
    },
    {
      "id": "cum_citesc",
      "label": "Nu știu cum să citesc Biblia",
      "roomId": "c4"
    },
    {
      "id": "epuizat_slujire",
      "label": "Sunt obosit de slujire",
      "roomId": "c6"
    },
    {
      "id": "nou_venit",
      "label": "Sunt nou și nu cunosc pe nimeni",
      "roomId": "c7"
    },
    {
      "id": "divort",
      "label": "Am trecut printr-un divorț",
      "roomId": "c2"
    },
    {
      "id": "prea_departe",
      "label": "Cred că sunt prea departe ca să mă mai întorc",
      "roomId": "c1"
    },
    {
      "id": "furie",
      "label": "Mă enervez și rănesc oamenii din jur",
      "roomId": "c5"
    }
  ],
  "exploreDoors": [
    {
      "id": "inceput",
      "label": "Vreau doar să-L cunosc",
      "roomId": null,
      "pathId": "path_temelie"
    },
    {
      "id": "umblare",
      "label": "Merg cu El, dar vreau mai aproape",
      "roomId": null,
      "pathId": "path_umblare"
    },
    {
      "id": "nu_stiu",
      "label": "Nu știu. Arată-mi tu.",
      "roomId": null,
      "pathId": "path_temelie"
    }
  ],
  "paths": [
    {
      "id": "path_acasa",
      "roomId": "c1",
      "title": "Drumul înapoi",
      "promise": "Șapte lecții, una la două zile. Nu îți cerem să povestești nimănui ce ai făcut și nu îți cerem să promiți nimic.",
      "lessons": [
        {
          "id": "rusine_l1",
          "courseId": "path_acasa",
          "order": 1,
          "title": "El S-a miscat primul",
          "estMinutes": 10,
          "memoryVerse": {
            "text": "Pe cand eram noi inca pacatosi, Hristos a murit pentru noi.",
            "ref": "Romani 5:8"
          }
        },
        {
          "id": "rusine_l2",
          "courseId": "path_acasa",
          "order": 2,
          "title": "Rusinea nu e de la El",
          "estMinutes": 11,
          "memoryVerse": {
            "text": "N-a trimis pe Fiul Sau in lume ca sa judece lumea, ci ca lumea sa fie mantuita prin El.",
            "ref": "Ioan 3:17"
          }
        },
        {
          "id": "rusine_l3",
          "courseId": "path_acasa",
          "order": 3,
          "title": "S-a ispravit",
          "estMinutes": 11,
          "memoryVerse": {
            "text": "A sters zapisul care sta impotriva noastra si l-a nimicit pironindu-l pe cruce.",
            "ref": "Coloseni 2:14"
          }
        },
        {
          "id": "rusine_l4",
          "courseId": "path_acasa",
          "order": 4,
          "title": "Nu esti ce ai facut",
          "estMinutes": 11,
          "memoryVerse": {
            "text": "Daca este cineva in Hristos, este o făptura noua.",
            "ref": "2 Corinteni 5:17"
          }
        },
        {
          "id": "rusine_l5",
          "courseId": "path_acasa",
          "order": 5,
          "title": "Sa nu mai ascunzi",
          "estMinutes": 12,
          "memoryVerse": {
            "text": "Daca ne marturisim pacatele, El este credincios si drept ca sa ne ierte.",
            "ref": "1 Ioan 1:9"
          }
        },
        {
          "id": "rusine_l6",
          "courseId": "path_acasa",
          "order": 6,
          "title": "Cand nu te poti ierta pe tine",
          "estMinutes": 12,
          "memoryVerse": {
            "text": "Acum dar nu este nicio osandire pentru cei ce sunt in Hristos Iisus.",
            "ref": "Romani 8:1"
          }
        },
        {
          "id": "rusine_l7",
          "courseId": "path_acasa",
          "order": 7,
          "title": "De aici incolo",
          "estMinutes": 11,
          "memoryVerse": {
            "text": "Harul lui Dumnezeu ne invața sa trăim in veacul de acum cu cumpătare, dreptate si evlavie.",
            "ref": "Tit 2:11-12"
          }
        }
      ],
      "practices": [
        "Azi nu adaugă nimic. Când te prinzi că vrei să te cureți înainte să vii, spune o dată: «El a alergat primul».",
        "Azi doar observă: de câte ori spui «sunt» în loc de «am făcut». Nu te certa cu gândul — tradu-l într-o faptă anume.",
        "Azi, când îți revine fapta în minte, spune cu voce tare, o singură dată: «s-a plătit». Nu de zece ori.",
        "Azi ascultă cum te numești tu pe tine. Când vine eticheta, răspunde-i: «asta am făcut, nu asta sunt».",
        "Ieri ai spus cu voce tare ce ascundeai. Azi nu adaugă nimic. Dacă vrei să spui și unui om, gândește-te o zi — nu e obligatoriu și nu e o condiție.",
        "Azi citește singur Romani 8, primele patru versete. Încet. Dacă gândul te ține treaz nopțile, sună 116 123 — nu e lipsă de credință.",
        "Ai terminat drumul. Azi caută omul căruia îi poți spune «m-am întors» când se întâmplă. Și scrie undeva o rugăciune la care aștepți răspuns."
      ]
    },
    {
      "id": "path_neiertare",
      "roomId": "c2",
      "title": "Când nu poți ierta",
      "promise": "Nouă lecții, una la două zile. Nu îți cerem să uiți și nu îți cerem să spui că n-a fost grav.",
      "lessons": [
        {
          "id": "neiertare_o1",
          "courseId": "path_neiertare",
          "order": 1,
          "title": "Nu El ti-a facut asta",
          "estMinutes": 10,
          "memoryVerse": {
            "text": "La Tatăl luminilor nu este nici schimbare, nici umbră de mutare.",
            "ref": "Iacov 1:17"
          }
        },
        {
          "id": "neiertare_o2",
          "courseId": "path_neiertare",
          "order": 2,
          "title": "N-a privit de departe",
          "estMinutes": 11,
          "memoryVerse": {
            "text": "Să ne apropiem cu deplină încredere de scaunul harului, ca să fim ajutați la vreme de nevoie.",
            "ref": "Evrei 4:16"
          }
        },
        {
          "id": "neiertare_l1",
          "courseId": "path_neiertare",
          "order": 1,
          "title": "Ce ti s-a facut a fost real",
          "estMinutes": 9,
          "memoryVerse": {
            "text": "Domnul este aproape de cei cu inima zădrobită.",
            "ref": "Psalm 34:18"
          }
        },
        {
          "id": "neiertare_l2",
          "courseId": "path_neiertare",
          "order": 2,
          "title": "Dumnezeu n-a fost de partea lui",
          "estMinutes": 10,
          "memoryVerse": {
            "text": "Eu am venit ca oile să aibă viață, și s-o aibă din belșug.",
            "ref": "Ioan 10:10"
          }
        },
        {
          "id": "neiertare_l3",
          "courseId": "path_neiertare",
          "order": 3,
          "title": "De ce te tine si acum",
          "estMinutes": 10,
          "memoryVerse": {
            "text": "Luați seama ca nu cumva să răsară vreo rădăcină de amărăciune.",
            "ref": "Evrei 12:15"
          }
        },
        {
          "id": "neiertare_l4",
          "courseId": "path_neiertare",
          "order": 4,
          "title": "Nu știau ce fac",
          "estMinutes": 11,
          "memoryVerse": {
            "text": "Tată, iartă-i, căci nu știu ce fac.",
            "ref": "Luca 23:34"
          }
        },
        {
          "id": "neiertare_l5",
          "courseId": "path_neiertare",
          "order": 5,
          "title": "Datoria pe care n-o mai poți plăti",
          "estMinutes": 12,
          "memoryVerse": {
            "text": "Pe când eram noi încă păcătoși, Hristos a murit pentru noi.",
            "ref": "Romani 5:8"
          }
        },
        {
          "id": "neiertare_l6",
          "courseId": "path_neiertare",
          "order": 6,
          "title": "Iertarea nu e un sentiment",
          "estMinutes": 11,
          "memoryVerse": {
            "text": "Iertați-vă unul pe altul, cum v-a iertat și Dumnezeu pe voi în Hristos.",
            "ref": "Efeseni 4:32"
          }
        },
        {
          "id": "neiertare_l7",
          "courseId": "path_neiertare",
          "order": 7,
          "title": "Ce fac când revine",
          "estMinutes": 10,
          "memoryVerse": {
            "text": "Acela care a început în voi această bună lucrare o va isprvi.",
            "ref": "Filipeni 1:6"
          }
        }
      ],
      "practices": [
        "Azi nu adăuga nimic. Când te prinzi că Îl bănuiești, spune o dată: «nu Tu mi-ai făcut asta». Atât.",
        "Azi citește singur Ioan 11, de la versetul 17 la 44. Încet. Uită-te doar la ce face Iisus cu oamenii rămași în urmă.",
        "Ieri I-ai spus ce ți s-a făcut. Azi nu adăuga nimic. Citește versetul de două ori și stai un minut în liniște.",
        "Azi observă doar: de câte ori Îl bănuiești pe Dumnezeu că nu-ți vrea binele. Nu te certa cu gândul. Doar numără-l.",
        "Ai cerut iertare cuiva peste care s-a scurs amărăciunea? Dacă nu, azi e ziua. Două propoziții, fără explicații.",
        "Spune încă o dată, cu voce tare: numele lui, și «nu știa ce face». A doua oară sună altfel.",
        "Hârtia cu ce îți datorează — mai e la tine? Citește-o o dată și pune-o la loc. Mâine facem ceva cu ea.",
        "Azi roagă-te pentru el o dată. O propoziție. Dacă nu-ți iese, spune-I lui Dumnezeu că nu-ți iese.",
        "Ai terminat drumul. Azi doar mulțumește. Și scrie undeva o rugăciune la care aștepți răspuns."
      ]
    },
    {
      "id": "path_temelie",
      "roomId": "c3",
      "title": "De la zero",
      "promise": "Trei lecții, una la două zile. Fără presupunerea că știi ceva dinainte și fără să te facă nimeni să te simți prost că întrebi.",
      "lessons": [
        {
          "id": "doctrina_l1",
          "courseId": "course_doctrina",
          "order": 1,
          "title": "De unde știm că Biblia nu e inventată",
          "estMinutes": 8,
          "memoryVerse": {
            "text": "Toată Scriptura este insuflată de Dumnezeu și de folos ca să învețe, să mustre, să îndrepte.",
            "ref": "2 Timotei 3:16"
          }
        },
        {
          "id": "doctrina_l2",
          "courseId": "course_doctrina",
          "order": 2,
          "title": "Ce înseamnă, de fapt, har",
          "estMinutes": 8,
          "memoryVerse": {
            "text": "Prin har ați fost mântuiți, prin credință. Nu prin fapte, ca să nu se laude nimeni.",
            "ref": "Efeseni 2:8-9"
          }
        },
        {
          "id": "doctrina_l3",
          "courseId": "course_doctrina",
          "order": 3,
          "title": "Cine spune Iisus că este",
          "estMinutes": 9,
          "memoryVerse": {
            "text": "Eu sunt Calea, Adevărul și Viața. Nimeni nu vine la Tatăl decât prin Mine.",
            "ref": "Ioan 14:6"
          }
        }
      ],
      "practices": [
        "Azi citește singur zece versete din Evanghelia după Ioan, capitolul 1. Nu trebuie să înțelegi tot. Doar citește-le.",
        "Azi observă de câte ori încerci să meriți ceva: la muncă, acasă, în cap. Nu schimba nimic. Doar observă.",
        "Ai terminat. Azi spune-I, cu cuvintele tale, ce crezi și ce încă nu crezi. Nu Se supără de partea a doua."
      ]
    },
    {
      "id": "path_aproape",
      "roomId": "c4",
      "title": "Când pare departe",
      "promise": "Șapte lecții, una la două zile. Fără să îți promitem că de mâine simți și fără să îți spunem că e vina ta.",
      "lessons": [
        {
          "id": "aproape_l1",
          "courseId": "path_aproape",
          "order": 1,
          "title": "N-a plecat El",
          "estMinutes": 10,
          "memoryVerse": {
            "text": "Nicidecum nu te voi lasa si cu niciun chip nu te voi parasi.",
            "ref": "Evrei 13:5"
          }
        },
        {
          "id": "aproape_l2",
          "courseId": "path_aproape",
          "order": 2,
          "title": "Cand tace",
          "estMinutes": 11,
          "memoryVerse": {
            "text": "Eu mă increed in bunatatea Ta.",
            "ref": "Psalmul 13:5"
          }
        },
        {
          "id": "aproape_l3",
          "courseId": "path_aproape",
          "order": 3,
          "title": "Daca e ceva de pus in ordine",
          "estMinutes": 11,
          "memoryVerse": {
            "text": "Cerceteaza-ma, Dumnezeule, si cunoaste-mi inima!",
            "ref": "Psalmul 139:23"
          }
        },
        {
          "id": "aproape_l4",
          "courseId": "path_aproape",
          "order": 4,
          "title": "Cum se aude, de fapt",
          "estMinutes": 11,
          "memoryVerse": {
            "text": "Oile Mele ascultă glasul Meu.",
            "ref": "Ioan 10:27"
          }
        },
        {
          "id": "aproape_l5",
          "courseId": "path_aproape",
          "order": 5,
          "title": "Cum citesc, ca sa nu fie degeaba",
          "estMinutes": 12,
          "memoryVerse": {
            "text": "Cuvantul Tau este o candela pentru picioarele mele.",
            "ref": "Psalmul 119:105"
          }
        },
        {
          "id": "aproape_l6",
          "courseId": "path_aproape",
          "order": 6,
          "title": "Flacara care s-a stins",
          "estMinutes": 11,
          "memoryVerse": {
            "text": "Intoarce-te la faptele tale de la inceput.",
            "ref": "Apocalipsa 2:5"
          }
        },
        {
          "id": "aproape_l7",
          "courseId": "path_aproape",
          "order": 7,
          "title": "Statornicia",
          "estMinutes": 11,
          "memoryVerse": {
            "text": "Sa nu obosim in facerea binelui; la vremea potrivita, vom culege.",
            "ref": "Galateni 6:9"
          }
        }
      ],
      "practices": [
        "Azi spune-I o dată, cu voce tare: «nu Te simt, dar ai spus că ești aici». Amândouă părțile, în aceeași propoziție.",
        "Citește-ți psalmul pe care l-ai scris ieri. Cu voce tare, o dată. Și nu-l corecta.",
        "Lucrul care a ieșit la cercetare — dacă a ieșit — rezolvă-l azi. Dacă nu a ieșit nimic, azi nu te mai căuta. Chiar nu.",
        "Din nou cele trei minute de liniște, la aceeași oră. Telefonul în altă cameră.",
        "Un paragraf, patru întrebări, în scris. Zece minute. Dacă s-a terminat Ioan 1, mergi mai departe cu Ioan 2.",
        "Lucrul de la început pe care l-ai reluat ieri — fă-l și azi. A doua zi e mai greu decât prima.",
        "Ai terminat drumul. Azi ține întâlnirea de zece minute la ora pe care ai scris-o. Și scrie undeva o rugăciune la care aștepți răspuns."
      ]
    },
    {
      "id": "path_schimbare",
      "roomId": "c5",
      "title": "Când nu te poți schimba",
      "promise": "Șapte lecții, una la două zile. Fără «strânge din dinți» și fără să îți cerem să promiți că nu mai faci.",
      "lessons": [
        {
          "id": "schimbare_l1",
          "courseId": "path_schimbare",
          "order": 1,
          "title": "Nu esti defect",
          "estMinutes": 11,
          "memoryVerse": {
            "text": "Te laud ca sunt o făptura atat de minunata.",
            "ref": "Psalmul 139:14"
          }
        },
        {
          "id": "schimbare_l2",
          "courseId": "path_schimbare",
          "order": 2,
          "title": "De ce nu tine voința",
          "estMinutes": 11,
          "memoryVerse": {
            "text": "Dacă Fiul va va face slobozi, veti fi in adevar slobozi.",
            "ref": "Ioan 8:36"
          }
        },
        {
          "id": "schimbare_l3",
          "courseId": "path_schimbare",
          "order": 3,
          "title": "Ce hranesti, creste",
          "estMinutes": 11,
          "memoryVerse": {
            "text": "Nu purtati grija de firea pamanteasca, ca sa nu-i treziti poftele.",
            "ref": "Romani 13:14"
          }
        },
        {
          "id": "schimbare_l4",
          "courseId": "path_schimbare",
          "order": 4,
          "title": "Casa goala",
          "estMinutes": 11,
          "memoryVerse": {
            "text": "Despartiti de Mine nu puteti face nimic.",
            "ref": "Ioan 15:5"
          }
        },
        {
          "id": "schimbare_l5",
          "courseId": "path_schimbare",
          "order": 5,
          "title": "Cand cazi din nou",
          "estMinutes": 12,
          "memoryVerse": {
            "text": "Cel neprihanit de sapte ori cade si se ridica.",
            "ref": "Proverbe 24:16"
          }
        },
        {
          "id": "schimbare_l6",
          "courseId": "path_schimbare",
          "order": 6,
          "title": "Cand frica si tristetea nu se opresc",
          "estMinutes": 12,
          "memoryVerse": {
            "text": "Nadajduiește in Dumnezeu, caci iar Îl voi lauda.",
            "ref": "Psalmul 42:5"
          }
        },
        {
          "id": "schimbare_l7",
          "courseId": "path_schimbare",
          "order": 7,
          "title": "Cum se schimba cineva, de fapt",
          "estMinutes": 11,
          "memoryVerse": {
            "text": "Acela care a inceput in voi aceasta buna lucrare o va ispravî.",
            "ref": "Filipeni 1:6"
          }
        }
      ],
      "practices": [
        "Azi nu încerca să te lași de nimic. Doar observă când îți spui «asa sunt eu» și taci la propoziția aia.",
        "Azi, când vine impulsul, scrie un singur cuvânt: ce simțeai în minutul dinainte.",
        "Lucrul pe care l-ai scos ieri — verifică dacă e chiar scos. Și vezi ce faci azi la ora aia.",
        "Azi ține programarea pe care ai scris-o. Zece minute cu El, la ora la care cădeai.",
        "Citește-ți protocolul de trei rânduri o dată, cu voce tare. Ca să ți-l amintești la ora două noaptea.",
        "Azi un lucru pentru corp, nu pentru suflet: somn, mâncare, o plimbare. Și, dacă durează, sună la medic — nu e lipsă de credință.",
        "Ai terminat drumul. Azi spune UNUI om că te lupți cu ceva. Nu detalii — doar atât."
      ]
    },
    {
      "id": "path_har",
      "roomId": "c6",
      "title": "Nu se cumpără",
      "promise": "Șapte lecții, una la două zile. Fără să îți cerem să faci mai mult și fără să îți spună nimeni că nu ești destul.",
      "lessons": [
        {
          "id": "har_l1",
          "courseId": "path_har",
          "order": 1,
          "title": "Nu se cumpara",
          "estMinutes": 11,
          "memoryVerse": {
            "text": "Prin har ati fost mantuiti... este darul lui Dumnezeu.",
            "ref": "Efeseni 2:8"
          }
        },
        {
          "id": "har_l2",
          "courseId": "path_har",
          "order": 2,
          "title": "Fiul care a rams acasa",
          "estMinutes": 11,
          "memoryVerse": {
            "text": "Fiule, tu intotdeauna esti cu mine si tot ce am eu este al tau.",
            "ref": "Luca 15:31"
          }
        },
        {
          "id": "har_l3",
          "courseId": "path_har",
          "order": 3,
          "title": "Frica nu vine de la El",
          "estMinutes": 11,
          "memoryVerse": {
            "text": "In dragoste nu este frica; dragostea desavarsita izgonS frica.",
            "ref": "1 Ioan 4:18"
          }
        },
        {
          "id": "har_l4",
          "courseId": "path_har",
          "order": 4,
          "title": "Atunci de ce sa mai fac ceva?",
          "estMinutes": 11,
          "memoryVerse": {
            "text": "Dragostea lui Hristos ne strange.",
            "ref": "2 Corinteni 5:14"
          }
        },
        {
          "id": "har_l5",
          "courseId": "path_har",
          "order": 5,
          "title": "Cand slujirea te-a golit",
          "estMinutes": 11,
          "memoryVerse": {
            "text": "Jugul Meu este blând si povara Mea este usoara.",
            "ref": "Matei 11:30"
          }
        },
        {
          "id": "har_l6",
          "courseId": "path_har",
          "order": 6,
          "title": "Cand forma inlocuieste relația",
          "estMinutes": 11,
          "memoryVerse": {
            "text": "Nu vreți sa veniti la Mine, ca sa aveti viața!",
            "ref": "Ioan 5:40"
          }
        },
        {
          "id": "har_l7",
          "courseId": "path_har",
          "order": 7,
          "title": "Cum trăiesc ca un fiu",
          "estMinutes": 11,
          "memoryVerse": {
            "text": "Nu mai esti rob, ci fiu.",
            "ref": "Galateni 4:7"
          }
        }
      ],
      "practices": [
        "Azi roagă-te încă o dată fără să pomenești nici ce ai făcut, nici ce n-ai făcut. Doar «ai milă de mine» și mulțumește.",
        "Azi spune-I «Tata» la începutul rugăciunii. Dacă te blochează, spune-I și asta.",
        "Azi cere încă un lucru pentru tine. Cine se teme de pedeapsă nu cere niciodată pentru el.",
        "Azi fă din nou un bine despre care nu află nimeni. Alții nu au ce să pună la punctaj.",
        "Ziua de odihnă: nu adaugă nimic pe listă. Zece minute jos, ca Maria, și atât.",
        "Lucrul pe care l-ai umplut ieri — fă-l și azi la fel, încet, uitându-te la El.",
        "Ai terminat drumul. Azi primește ceva fără să dai nimic în schimb. Și scrie undeva o rugăciune la care aștepți răspuns."
      ]
    },
    {
      "id": "path_impreuna",
      "roomId": "c7",
      "title": "Să nu rămâi singur",
      "promise": "Șapte lecții, una la două zile. Nu îți cerem să te întorci nicăieri și nu îți promitem că fabricăm oameni în șapte lecții.",
      "lessons": [
        {
          "id": "impreuna_l1",
          "courseId": "path_impreuna",
          "order": 1,
          "title": "El stie cum e",
          "estMinutes": 11,
          "memoryVerse": {
            "text": "Chiar dacă tatal meu si mama mea m-ar parasi, Domnul mă va primi.",
            "ref": "Psalmul 27:10"
          }
        },
        {
          "id": "impreuna_l2",
          "courseId": "path_impreuna",
          "order": 2,
          "title": "Nu esti orfan",
          "estMinutes": 11,
          "memoryVerse": {
            "text": "Nu va voi lasa orfani.",
            "ref": "Ioan 14:18"
          }
        },
        {
          "id": "impreuna_l3",
          "courseId": "path_impreuna",
          "order": 3,
          "title": "Cand familia nu te ințelege",
          "estMinutes": 12,
          "memoryVerse": {
            "text": "Va primi de o suta de ori mai mult acum, in vremea de acum.",
            "ref": "Marcu 10:30"
          }
        },
        {
          "id": "impreuna_l4",
          "courseId": "path_impreuna",
          "order": 4,
          "title": "Cand ai fost ranit acolo",
          "estMinutes": 12,
          "memoryVerse": {
            "text": "Iisus a auzit ca fusese dat afara si, cand l-a intalnit, i-a zis...",
            "ref": "Ioan 9:35"
          }
        },
        {
          "id": "impreuna_l5",
          "courseId": "path_impreuna",
          "order": 5,
          "title": "Ce e biserica, de fapt",
          "estMinutes": 11,
          "memoryVerse": {
            "text": "Acolo unde sunt doi sau trei adunati in numele Meu, sunt si Eu in mijlocul lor.",
            "ref": "Matei 18:20"
          }
        },
        {
          "id": "impreuna_l6",
          "courseId": "path_impreuna",
          "order": 6,
          "title": "Cum se gasesc oamenii",
          "estMinutes": 11,
          "memoryVerse": {
            "text": "Funia impletita in trei nu se rupe ușor.",
            "ref": "Eclesiastul 4:12"
          }
        },
        {
          "id": "impreuna_l7",
          "courseId": "path_impreuna",
          "order": 7,
          "title": "De la singur, la al cuiva",
          "estMinutes": 11,
          "memoryVerse": {
            "text": "Purtați-va poverile unii altora.",
            "ref": "Galateni 6:2"
          }
        }
      ],
      "practices": [
        "Azi spune-I încă o dată, fără să înfrumusețezi: «mi-e singur». Nu e o plângere nepotrivită.",
        "Azi cere încă un lucru mic unui om. Un orfan nu cere — tu nu ești orfan.",
        "Azi roagă-te pe nume pentru omul din casă care te înțelege cel mai puțin. Și nu-i explica nimic.",
        "Azi nu adăuga nimic la ce ai scris ieri. Dacă te ține treaz, sună 116 123 — nu e lipsă de credință.",
        "Cele două nume — mai sunt bune la lumina zilei? Dacă nu, caută azi un grup mic aproape de tine.",
        "Dacă ai trimis mesajul și ți-a răspuns, propune ceva concret: o cafea, o plimbare, o oră. Dacă nu ți-a răspuns, nu înseamnă nimic despre tine.",
        "Ai terminat drumul. Azi fă un lucru pentru cineva mai singur decât tine. Și scrie undeva o rugăciune la care aștepți răspuns."
      ]
    },
    {
      "id": "path_umblare",
      "roomId": null,
      "title": "Umblarea",
      "promise": "Șapte lecții pentru cine merge deja cu El: cum se ascultă, cum se citește, ce faci când nu simți nimic.",
      "lessons": [
        {
          "id": "umblare_l1",
          "courseId": "path_umblare",
          "order": 1,
          "title": "Rugaciunea nu e monolog",
          "estMinutes": 11,
          "memoryVerse": {
            "text": "Oile Mele ascultă glasul Meu; Eu le cunosc, și ele vin după Mine.",
            "ref": "Ioan 10:27"
          }
        },
        {
          "id": "umblare_l2",
          "courseId": "path_umblare",
          "order": 2,
          "title": "Cum citesc Biblia ca sa aud, nu ca sa bifez",
          "estMinutes": 12,
          "memoryVerse": {
            "text": "Cugetă asupra ei zi și noapte, căutand să faci tot ce este scris în ea.",
            "ref": "Iosua 1:8"
          }
        },
        {
          "id": "umblare_l3",
          "courseId": "path_umblare",
          "order": 3,
          "title": "Ascultarea in lucruri mici",
          "estMinutes": 11,
          "memoryVerse": {
            "text": "Cine are poruncile Mele și le păzește, acela Mă iubește.",
            "ref": "Ioan 14:21"
          }
        },
        {
          "id": "umblare_l4",
          "courseId": "path_umblare",
          "order": 4,
          "title": "Timpul cu El, nu raportul de la job",
          "estMinutes": 11,
          "memoryVerse": {
            "text": "Cine rămane în Mine și în cine răman Eu aduce multă roadă.",
            "ref": "Ioan 15:5"
          }
        },
        {
          "id": "umblare_l5",
          "courseId": "path_umblare",
          "order": 5,
          "title": "Linistea si postul, fara performanta",
          "estMinutes": 11,
          "memoryVerse": {
            "text": "Roagă-te Tatălui tău, care este în ascuns.",
            "ref": "Matei 6:6"
          }
        },
        {
          "id": "umblare_l6",
          "courseId": "path_umblare",
          "order": 6,
          "title": "Cand nu simt nimic si merg oricum",
          "estMinutes": 12,
          "memoryVerse": {
            "text": "Eu însă mă voi bucura în Domnul, mă voi bucura în Dumnezeul mantuirii mele.",
            "ref": "Habacuc 3:18"
          }
        },
        {
          "id": "umblare_l7",
          "courseId": "path_umblare",
          "order": 7,
          "title": "Ce fac cu ce am primit",
          "estMinutes": 11,
          "memoryVerse": {
            "text": "Ne mangaie în toate necazurile noastre, pentru ca să putem mangaia pe cei ce se află în vreun necaz.",
            "ref": "2 Corinteni 1:4"
          }
        }
      ],
      "practices": [
        "Azi, după ce termini de vorbit cu El, nu te ridica. Cinci minute fără să ceri nimic.",
        "Un singur paragraf, trecut prin cele patru întrebări, în scris. Nu un capitol.",
        "Lucrul mic pe care îl amâni — fă-l azi. Dacă nu poți singur, spune-I: «vreau, dar nu pot».",
        "Zece minute cu El fără să ceri și fără să citești. Doar spune-I de ce Îl iubești.",
        "O oră fără telefon, treaz, cu El. Când vine lista, scrie-o și taci.",
        "Azi fă exact ce ai face dacă ai simți. Și spune-I: «nu simt nimic și totuși sunt aici».",
        "Ai terminat drumul. Azi caută omul căruia îi spui cele trei propoziții. Întreabă-l ce mai face."
      ]
    }
  ],
  "doctrineLessons": [
    {
      "id": "doctrina_l1",
      "courseId": "course_doctrina",
      "order": 1,
      "title": "De unde știm că Biblia nu e inventată",
      "estMinutes": 8,
      "memoryVerse": {
        "text": "Toată Scriptura este insuflată de Dumnezeu și de folos ca să învețe, să mustre, să îndrepte.",
        "ref": "2 Timotei 3:16"
      }
    },
    {
      "id": "doctrina_l2",
      "courseId": "course_doctrina",
      "order": 2,
      "title": "Ce înseamnă, de fapt, har",
      "estMinutes": 8,
      "memoryVerse": {
        "text": "Prin har ați fost mântuiți, prin credință. Nu prin fapte, ca să nu se laude nimeni.",
        "ref": "Efeseni 2:8-9"
      }
    },
    {
      "id": "doctrina_l3",
      "courseId": "course_doctrina",
      "order": 3,
      "title": "Cine spune Iisus că este",
      "estMinutes": 9,
      "memoryVerse": {
        "text": "Eu sunt Calea, Adevărul și Viața. Nimeni nu vine la Tatăl decât prin Mine.",
        "ref": "Ioan 14:6"
      }
    }
  ],
  "shelves": [
    {
      "id": "lib_temelie",
      "title": "Temelia",
      "blurb": "De la zero: cine e Dumnezeu, ce a făcut Iisus și ce înseamnă asta pentru tine.",
      "gated": false,
      "courses": [
        {
          "id": "lib_fundamentul",
          "title": "Fundamentul",
          "forWhom": "Nu știi de unde să începi, sau vrei să reașezi ce ai auzit pe apucate.",
          "plannedLessons": 7,
          "lessonIds": [
            "doctrina_l1",
            "doctrina_l2",
            "doctrina_l3"
          ],
          "state": "partial",
          "source": "docs/06-curs-fundamentul.md"
        },
        {
          "id": "lib_intoarcerea",
          "title": "Întoarcerea",
          "forWhom": "Ai înțeles că ceva nu e în ordine și vrei să știi ce faci mai departe.",
          "plannedLessons": 5,
          "lessonIds": [],
          "state": "planned",
          "source": "docs/17-modul-intoarcerea.md"
        }
      ]
    },
    {
      "id": "lib_intrebari",
      "title": "Întrebări mari",
      "blurb": "Lucrurile care te opresc să crezi, luate pe rând și cinstit — inclusiv unde nu avem răspuns.",
      "gated": false,
      "courses": [
        {
          "id": "doctrine_c2_har",
          "title": "Religie sau credință — ce mă mântuiește?",
          "forWhom": "Ai crescut cu ideea că ești creștin din naștere, sau că faptele bune se cântăresc la final.",
          "plannedLessons": 6,
          "lessonIds": [
            "har_d_l1",
            "har_d_l2",
            "har_d_l3",
            "har_d_l4",
            "har_d_l5",
            "har_d_l6"
          ],
          "state": "live",
          "source": "docs/15-doctrina-generala.md §Cursul 2"
        },
        {
          "id": "doctrine_c4_vesnicia",
          "title": "Ce urmează după moarte?",
          "forWhom": "Nu știi ce e raiul, ce e iadul, sau dacă poți fi sigur de ceva.",
          "plannedLessons": 5,
          "lessonIds": [
            "vesnicia_l1",
            "vesnicia_l2",
            "vesnicia_l3",
            "vesnicia_l4",
            "vesnicia_l5"
          ],
          "state": "live",
          "source": "docs/15-doctrina-generala.md §Cursul 4"
        },
        {
          "id": "doctrine_c1_biblia",
          "title": "Pot să am încredere în Biblie?",
          "forWhom": "Ți s-a spus că e o carte scrisă de oameni, rescrisă de nu știu câte ori.",
          "plannedLessons": 6,
          "lessonIds": [],
          "state": "planned",
          "source": "docs/15-doctrina-generala.md §Cursul 1"
        },
        {
          "id": "doctrine_c3_biserica",
          "title": "Cine e Biserica lui Iisus?",
          "forWhom": "Dacă fiecare zice altceva, cine are dreptate? Sau ai fost rănit acolo.",
          "plannedLessons": 5,
          "lessonIds": [],
          "state": "planned",
          "source": "docs/15-doctrina-generala.md §Cursul 3"
        },
        {
          "id": "lib_alte_credinte",
          "title": "Energii, horoscop, karma",
          "forWhom": "Ai luat de peste tot câte puțin și nu mai știi ce se bate cap în cap.",
          "plannedLessons": 5,
          "lessonIds": [],
          "state": "planned"
        }
      ]
    },
    {
      "id": "lib_cuvantul",
      "title": "Cuvântul",
      "blurb": "Cum se citește, de unde se începe și ce înseamnă ce citești.",
      "gated": false,
      "courses": [
        {
          "id": "parables_c1_tatal",
          "title": "Pildele — cine e Tatăl",
          "forWhom": "Le-ai auzit de mic și tot nu știi ce cer de la tine.",
          "plannedLessons": 5,
          "lessonIds": [
            "pilda_risipitor",
            "pilda_oaia",
            "pilda_vamesul",
            "pilda_lucratorii",
            "pilda_robul_datornic"
          ],
          "state": "live",
          "source": "docs/16-modul-pilde.md §Cursul 1"
        },
        {
          "id": "parables_c3_fiul",
          "title": "Pildele — cum trăiește un fiu",
          "forWhom": "Înțelegi ce a făcut Iisus și întrebi: bun, și acum concret ce fac?",
          "plannedLessons": 5,
          "lessonIds": [
            "pilda_samariteanul",
            "pilda_talantii",
            "pilda_doi_fii",
            "pilda_casa_stanca",
            "pilda_smochinul"
          ],
          "state": "live",
          "source": "docs/16-modul-pilde.md §Cursul 3"
        },
        {
          "id": "parables_c2_imparatia",
          "title": "Pildele — ce e Împărăția și cine intră",
          "forWhom": "Auzi „Împărăția lui Dumnezeu” și nu știi la ce se referă.",
          "plannedLessons": 5,
          "lessonIds": [
            "pilda_semanatorul",
            "pilda_neghina",
            "pilda_mustarul",
            "pilda_comoara",
            "pilda_fecioarele"
          ],
          "state": "live",
          "source": "docs/16-modul-pilde.md §Cursul 2"
        },
        {
          "id": "parables_c4_vesnicia",
          "title": "Pildele — bani, moarte și ce rămâne",
          "forWhom": "Te întrebi ce rămâne din ce strângi și ce contează la capăt.",
          "plannedLessons": 5,
          "lessonIds": [],
          "state": "planned",
          "source": "docs/16-modul-pilde.md §Cursul 4"
        },
        {
          "id": "lib_carti",
          "title": "Cărțile Bibliei, una câte una",
          "forWhom": "Ai deschis la Geneza, ai ajuns la Levitic și te-ai oprit.",
          "plannedLessons": 12,
          "lessonIds": [],
          "state": "planned"
        },
        {
          "id": "lib_trasee",
          "title": "Trasee scurte de citire",
          "forWhom": "Vrei să citești, dar ai nevoie de un capăt și de un final.",
          "plannedLessons": 4,
          "lessonIds": [],
          "state": "planned"
        }
      ]
    },
    {
      "id": "lib_rugaciune",
      "title": "Rugăciunea",
      "blurb": "Cum se vorbește cu El, mai ales când nu ai cuvinte și când nu primești răspuns.",
      "gated": false,
      "courses": [
        {
          "id": "lib_rug_inceput",
          "title": "Când nu știi ce să spui",
          "forWhom": "Te blochezi după „Doamne” și îți pare că spui prostii.",
          "plannedLessons": 5,
          "lessonIds": [],
          "state": "planned",
          "source": "docs/Emanus — Ritmul zilnic & Rugăciunea"
        },
        {
          "id": "lib_rug_psalmi",
          "title": "Psalmii ca școală de rugăciune",
          "forWhom": "Vrei să te rogi cinstit, inclusiv când ești supărat pe El.",
          "plannedLessons": 5,
          "lessonIds": [],
          "state": "planned"
        },
        {
          "id": "lib_rug_mijlocire",
          "title": "Postul și mijlocirea",
          "forWhom": "Te rogi pentru cineva de mult și nu se schimbă nimic.",
          "plannedLessons": 4,
          "lessonIds": [],
          "state": "planned"
        }
      ]
    },
    {
      "id": "lib_casa",
      "title": "Casa",
      "blurb": "Ce se întâmplă cu credința acolo unde te vede lumea cel mai puțin.",
      "gated": false,
      "courses": [
        {
          "id": "lib_casnicie",
          "title": "Căsnicia",
          "forWhom": "Sunteți doi oameni obosiți care nu mai vorbesc despre nimic important.",
          "plannedLessons": 6,
          "lessonIds": [],
          "state": "planned",
          "source": "docs/12-continut-parinti.md"
        },
        {
          "id": "lib_partener_necredincios",
          "title": "Când partenerul nu crede",
          "forWhom": "Tu ai venit la Iisus, el sau ea nu. Și doare zilnic.",
          "plannedLessons": 4,
          "lessonIds": [],
          "state": "planned"
        },
        {
          "id": "lib_cresc_copii",
          "title": "Cresc copii de credință",
          "forWhom": "Vrei să le dai ce nu ai avut, fără să le impui nimic.",
          "plannedLessons": 5,
          "lessonIds": [],
          "state": "planned",
          "source": "docs/12-continut-parinti.md"
        },
        {
          "id": "lib_copil_departe",
          "title": "Când copilul se îndepărtează",
          "forWhom": "L-ai crescut în biserică și acum nu vrea să audă.",
          "plannedLessons": 4,
          "lessonIds": [],
          "state": "planned"
        },
        {
          "id": "lib_mostenirea",
          "title": "Moștenirea pe care o las",
          "forWhom": "Ai ajuns la vârsta la care te întrebi ce rămâne după tine.",
          "plannedLessons": 5,
          "lessonIds": [],
          "state": "planned",
          "source": "docs/13-continut-bunici.md",
          "ageHint": "bunici"
        }
      ]
    },
    {
      "id": "lib_viata",
      "title": "Viața de zi cu zi",
      "blurb": "Bani, muncă, timp, cinste — acolo unde Scriptura se aplică sau nu se aplică deloc.",
      "gated": false,
      "courses": [
        {
          "id": "lib_bani",
          "title": "Bani și datorii",
          "forWhom": "Ai rate, ai frică de mâine și ți-e rușine să vorbești despre asta.",
          "plannedLessons": 5,
          "lessonIds": [],
          "state": "planned",
          "source": "docs/11-continut-barbati.md"
        },
        {
          "id": "lib_munca",
          "title": "Muncă și rost",
          "forWhom": "Muncești mult și tot pare că nu însemni nimic.",
          "plannedLessons": 5,
          "lessonIds": [],
          "state": "planned"
        },
        {
          "id": "lib_integritate",
          "title": "Cinstea când nu te vede nimeni",
          "forWhom": "Se fură mărunt în jurul tău și pare normal.",
          "plannedLessons": 4,
          "lessonIds": [],
          "state": "planned"
        },
        {
          "id": "lib_timp",
          "title": "Timpul și oboseala",
          "forWhom": "Nu ai zece minute, dar ai două ore pe telefon.",
          "plannedLessons": 4,
          "lessonIds": [],
          "state": "planned"
        }
      ]
    },
    {
      "id": "lib_cei_mici",
      "title": "Pentru cei mici",
      "blurb": "De parcurs împreună cu copilul. Nu îl lăsăm singur cu întrebările mari.",
      "gated": false,
      "courses": [
        {
          "id": "lib_micii_facut",
          "title": "Dumnezeu m-a făcut",
          "forWhom": "Copil de 2-5 ani, cu tine lângă el.",
          "plannedLessons": 5,
          "lessonIds": [],
          "state": "planned",
          "source": "docs/08-continut-bebelusi.md",
          "ageHint": "0-5"
        },
        {
          "id": "lib_copii_cine_sunt",
          "title": "Cine sunt eu?",
          "forWhom": "Copil de 6-11 ani, singur sau cu tine.",
          "plannedLessons": 5,
          "lessonIds": [],
          "state": "planned",
          "source": "docs/09-continut-copii.md",
          "ageHint": "6-11"
        },
        {
          "id": "lib_copii_emotii",
          "title": "Când mi-e frică sau sunt supărat",
          "forWhom": "Copil care se închide și nu spune ce are.",
          "plannedLessons": 4,
          "lessonIds": [],
          "state": "planned",
          "source": "docs/09-continut-copii.md",
          "ageHint": "6-11"
        },
        {
          "id": "lib_teens_identitate",
          "title": "Cine sunt eu, de fapt?",
          "forWhom": "Adolescent prins între comparație și presiune.",
          "plannedLessons": 5,
          "lessonIds": [],
          "state": "planned",
          "source": "docs/02-programa-curriculum.md",
          "ageHint": "12-18"
        },
        {
          "id": "lib_teens_indoieli",
          "title": "Pot să cred cu adevărat?",
          "forWhom": "Adolescent cu întrebări la care nimeni nu i-a răspuns cinstit.",
          "plannedLessons": 5,
          "lessonIds": [],
          "state": "planned",
          "ageHint": "12-18"
        }
      ]
    },
    {
      "id": "lib_creatori",
      "title": "De la creatori",
      "blurb": "Cursuri scrise de oameni care duc mai departe ce au primit. Fiecare trece prin validare înainte să apară aici.",
      "gated": true,
      "courses": [
        {
          "id": "lib_creator_pilot",
          "title": "Curs-pilot de creator",
          "forWhom": "Ai venit din materialul cuiva și vrei să continui cu el.",
          "plannedLessons": 5,
          "lessonIds": [],
          "state": "planned",
          "source": "docs/07-sablon-curs-creatori.md"
        }
      ]
    }
  ],
  "contentVersion": "c6c230ad847babd2"
} as const
