// Devoțional, luna 7: „Rugăciunea” (docs/27 §2.4, axa living_faith).
//
// Regula lunii: nu se predau tehnici. Rugăciunea e vorbirea unui copil cu Tatăl
// Lui, iar zilele urmează drumul firesc — unde te rogi, cum începi, ce ceri, ce
// faci când nu-ți ies cuvintele și ce faci când răspunsul întârzie. Pașii rămân
// mici: două minute făcute zilnic bat o oră promisă și neonorată.
//
// Conținut ORIGINAL Emanus (docs/27 §1.2). Versete: Cornilescu VDC 1924 (domeniu
// public), colaționate verset cu verset.
import type { DevotionalDay } from "./devotional.js"

const LUNA_7 = "Rugăciunea"

export const DEVOTIONAL_DAYS_LUNA_7: DevotionalDay[] = [
  {
    id: "dev_181",
    dayNumber: 181,
    theme: LUNA_7,
    axis: "living_faith",
    verseRef: "Luca 11:1",
    verseText: "Doamne, învață-ne să ne rugăm, cum a învățat și Ioan pe ucenicii lui.",
    meditation:
      "Ucenicii au stat cu Isus ani de zile și abia asta au cerut să învețe. Nu i-au cerut să-i învețe să predice sau să facă minuni. Cererea lor înseamnă și că e normal să nu știi — rugăciunea se învață, nu se știe din instinct.",
    question: "Ai spus vreodată cinstit: nu știu să mă rog?",
    prayer: "Doamne, învață-mă să mă rog. Încep de aici. Amin.",
    step: "Roagă-te azi două minute. Cronometrate. Atât.",
  },
  {
    id: "dev_182",
    dayNumber: 182,
    theme: LUNA_7,
    axis: "living_faith",
    verseRef: "Matei 6:6",
    verseText: "Ci tu, când te rogi, intră în odăița ta, încuie-ți ușa și roagă-te Tatălui tău, care este în ascuns.",
    meditation:
      "Isus mută rugăciunea din piață în cameră. Motivul nu e rușinea, ci publicul: când te aude cineva, începi să vorbești pentru el. În camera încuiată rămâne doar ce crezi cu adevărat.",
    question: "Ai un loc și o oră în care nu te aude nimeni?",
    prayer: "Tată, aici nu mă aude nimeni. Așa e mai bine. Amin.",
    step: "Alege azi un loc concret din casă în care să te rogi zilele astea.",
  },
  {
    id: "dev_183",
    dayNumber: 183,
    theme: LUNA_7,
    axis: "living_faith",
    verseRef: "Matei 6:7",
    verseText: "Când vă rugați, să nu bolborosiți aceleași vorbe, ca păgânii, cărora li se pare că, dacă spun o mulțime de vorbe, vor fi ascultați.",
    meditation:
      "Dumnezeu nu se lasă impresionat de lungime și nici de limbaj bisericesc. Păgânii credeau că zeii trebuie convinși; Tatăl tău nu trebuie convins să te asculte. De aceea poți vorbi simplu, cum vorbești de obicei.",
    question: "Te rogi cu alte cuvinte decât cele pe care le folosești în viață?",
    prayer: "Doamne, las jos vorbele frumoase. Îți spun pe șleau. Amin.",
    step: "Roagă-te azi fără niciun cuvânt „religios”. Doar românește, normal.",
  },
  {
    id: "dev_184",
    dayNumber: 184,
    theme: LUNA_7,
    axis: "living_faith",
    verseRef: "Matei 6:9",
    verseText: "Iată dar cum trebuie să vă rugați: ‘Tatăl nostru care ești în ceruri! Sfințească-se Numele Tău’",
    meditation:
      "Primul cuvânt e „Tată”, nu „Domn” și nu „Stăpân”. Al doilea e „nostru” — chiar și în camera încuiată nu ești singur înaintea Lui. Din primele patru cuvinte afli cine ești și cine e El.",
    question: "Îi spui Tată sau doar Doamne?",
    prayer: "Tatăl nostru care ești în ceruri, sfințească-se Numele Tău. Amin.",
    step: "Citește azi rar Tatăl nostru și oprește-te la fiecare propoziție.",
  },
  {
    id: "dev_185",
    dayNumber: 185,
    theme: LUNA_7,
    axis: "living_faith",
    verseRef: "Matei 6:10",
    verseText: "Vie Împărăția Ta; facă-se voia Ta, precum în cer și pe pământ.",
    meditation:
      "E cea mai riscantă propoziție din rugăciunea aceasta, pentru că pui voia Lui înaintea planurilor tale. Nu înseamnă resemnare, ci încredere că voia Lui e mai bună decât a ta. Se spune ușor când totul merge și greu când aștepți un răspuns anume.",
    question: "Există un lucru la care nu vrei să spui „facă-se voia Ta”?",
    prayer: "Doamne, facă-se voia Ta și în lucrul acela. Ajută-mă să spun asta serios. Amin.",
    step: "Numește în rugăciune lucrul acela și adaugă propoziția întreagă.",
  },
  {
    id: "dev_186",
    dayNumber: 186,
    theme: LUNA_7,
    axis: "living_faith",
    verseRef: "Luca 18:1",
    verseText: "Isus le-a spus o pildă, ca să le arate că trebuie să se roage necurmat și să nu se lase.",
    meditation:
      "Pilda e despre o văduvă care bate la ușă până obține dreptate. Isus nu spune că Dumnezeu ar fi ca judecătorul nedrept, ci exact invers: dacă stăruința înmoaie un om rău, cu atât mai mult Tatăl bun. Stăruința nu-L convinge; te ține pe tine în legătură.",
    question: "Pentru ce te-ai rugat ultima oară mai mult de o săptămână?",
    prayer: "Doamne, nu mă las. Bat mai departe. Amin.",
    step: "Scrie o cerere pentru care te vei ruga în fiecare zi până la sfârșitul lunii.",
  },
  {
    id: "dev_187",
    dayNumber: 187,
    theme: LUNA_7,
    axis: "living_faith",
    verseRef: "Luca 18:13",
    verseText: "Vameșul stătea departe și nu îndrăznea nici ochii să și-i ridice spre cer, ci se bătea în piept și zicea: ‘Dumnezeule, ai milă de mine, păcătosul!’",
    meditation:
      "E cea mai scurtă rugăciune ascultată din Evanghelii și n-are nimic în ea în afară de adevăr. Fariseul avea material mai bun și a plecat acasă cu mâinile goale. Ce contează nu e cât de bine vorbești, ci cât de sincer stai.",
    question: "Când te rogi, îți prezinți meritele sau nevoia?",
    prayer: "Dumnezeule, ai milă de mine, păcătosul. Amin.",
    step: "Rostește azi doar rugăciunea vameșului și taci un minut după ea.",
  },
  {
    id: "dev_188",
    dayNumber: 188,
    theme: LUNA_7,
    axis: "living_faith",
    verseRef: "Luca 11:9",
    verseText: "Cereți, și vi se va da; căutați, și veți găsi; bateți, și vi se va deschide.",
    meditation:
      "Trei verbe, tot mai insistente: ceri, cauți, bați. Isus vorbește apoi despre un tată care nu dă copilului o piatră când cere pâine. Toată încrederea din rugăciune stă pe cine e Cel căruia Îi ceri.",
    question: "Ce nu ai cerut niciodată, pentru că ți s-a părut prea mult?",
    prayer: "Doamne, cer. Știu că nu-mi dai o piatră. Amin.",
    step: "Cere-I azi exact lucrul pe care nu ai îndrăznit să-l ceri.",
  },
  {
    id: "dev_189",
    dayNumber: 189,
    theme: LUNA_7,
    axis: "living_faith",
    verseRef: "Ioan 15:7",
    verseText: "Dacă rămâneți în Mine și dacă rămân în voi cuvintele Mele, cereți orice veți vrea și vi se va da.",
    meditation:
      "Promisiunea are o condiție și nu e o formalitate. Cine stă aproape de El începe să ceară alte lucruri decât cerea înainte. Rugăciunea nu e un automat de dorințe, ci o relație care îți schimbă dorințele.",
    question: "Cum s-au schimbat cererile tale în ultimul an?",
    prayer: "Doamne, schimbă-mi cererile, nu doar circumstanțele. Amin.",
    step: "Citește un capitol din Evanghelii înainte să te rogi azi.",
  },
  {
    id: "dev_190",
    dayNumber: 190,
    theme: LUNA_7,
    axis: "living_faith",
    verseRef: "Ioan 14:13",
    verseText: "Și orice veți cere în Numele Meu, voi face, pentru ca Tatăl să fie proslăvit în Fiul.",
    meditation:
      "„În Numele Meu” nu e o formulă pusă la sfârșit, ci un temei: vii înaintea Tatălui pe contul Lui, nu pe al tău. Și scopul e spus limpede — ca Tatăl să fie proslăvit. Rugăciunea ta e legată de ceva mai mare decât confortul tău.",
    question: "Ce ai cere dacă scopul ar fi slava Lui, nu liniștea ta?",
    prayer: "Doamne, vin în Numele lui Isus, nu cu numele meu. Amin.",
    step: "Adaugă azi la o cerere veche întrebarea: „la ce bun, pentru Împărăția Ta?”",
  },
  {
    id: "dev_191",
    dayNumber: 191,
    theme: LUNA_7,
    axis: "living_faith",
    verseRef: "Filipeni 4:6",
    verseText: "Nu vă îngrijorați de nimic, ci, în orice lucru, aduceți cererile voastre la cunoștința lui Dumnezeu, prin rugăciuni și cereri, cu mulțumiri.",
    meditation:
      "„În orice lucru” desființează ideea că unele probleme sunt prea mici pentru Dumnezeu. Și „cu mulțumiri” schimbă tonul: nu vii ca la un birou de reclaţii. Grija dusă la El se preface în cerere; grija ținută în tine se preface în frică.",
    question: "Ce lucru ți se pare prea mic ca să-l spui în rugăciune?",
    prayer: "Doamne, Îți spun și lucrurile mici. Mulțumesc că asculți. Amin.",
    step: "Roagă-te azi pentru un lucru banal — o întâlnire, un drum, o factură.",
  },
  {
    id: "dev_192",
    dayNumber: 192,
    theme: LUNA_7,
    axis: "living_faith",
    verseRef: "1 Tesaloniceni 5:17",
    verseText: "Rugați-vă neîncetat.",
    meditation:
      "Nu înseamnă să stai în genunchi toată ziua, ci să ții linia deschisă. Rugăciunea de zece secunde dintre două treburi e la fel de reală ca cea de dimineață. Cine se roagă doar în program se roagă mai puțin decât crede.",
    question: "Când te-ai rugat ultima dată în mijlocul zilei, din mers?",
    prayer: "Doamne, rămâi în gândul meu toată ziua. Amin.",
    step: "Spune azi trei rugăciuni de câte o propoziție, la ore diferite.",
  },
  {
    id: "dev_193",
    dayNumber: 193,
    theme: LUNA_7,
    axis: "living_faith",
    verseRef: "Romani 8:26",
    verseText: "Și tot astfel și Duhul ne ajută în slăbiciunea noastră, căci nu știm cum trebuie să ne rugăm. Dar Însuși Duhul mijlocește pentru noi cu suspine negrăite.",
    meditation:
      "Versetul ăsta e pentru zilele în care nu-ți ies cuvintele. Nu spune că rugăciunea ta e refuzată pentru că e săracă, ci că Altcineva o traduce. Un oftat poate ajunge întreg înaintea lui Dumnezeu.",
    question: "Ai tăcut vreodată pentru că nu știai ce să ceri?",
    prayer: "Doamne, nu știu ce să spun. Duhul Tău să spună pentru mine. Amin.",
    step: "Stai azi trei minute în tăcere înaintea Lui, fără să formulezi nimic.",
  },
  {
    id: "dev_194",
    dayNumber: 194,
    theme: LUNA_7,
    axis: "living_faith",
    verseRef: "Evrei 4:16",
    verseText: "Să ne apropiem dar cu deplină încredere de scaunul harului ca să căpătăm îndurare și să găsim har, pentru ca să fim ajutați la vreme de nevoie.",
    meditation:
      "Se numește scaunul harului, nu al meritelor, și tocmai de aceea poți veni cu încredere. Nu îți trebuie o săptămână bună ca să ai voie să te rogi. „La vreme de nevoie” înseamnă exact la momentul potrivit, nu mai devreme.",
    question: "Amâni rugăciunea până când te simți mai vrednic?",
    prayer: "Doamne, vin așa cum sunt, azi. Amin.",
    step: "Roagă-te azi imediat după ce ai greșit, nu peste trei zile.",
  },
  {
    id: "dev_195",
    dayNumber: 195,
    theme: LUNA_7,
    axis: "living_faith",
    verseRef: "Iacov 1:6",
    verseText: "Dar s-o ceară cu credință, fără să se îndoiască deloc, pentru că cine se îndoiește seamănă cu valul mării, tulburat și împins de vânt încoace și încolo.",
    meditation:
      "Îndoiala de care vorbește Iacov nu e întrebarea sinceră, ci nehotărârea omului care nu știe dacă vrea sau nu ajutorul lui Dumnezeu. Poți veni cu întrebări; nu poți veni cu jumătate de inimă. Cere și rămâi acolo.",
    question: "Ceri cu adevărat sau doar încerci, „să vedem”?",
    prayer: "Doamne, cred; ajută necredinței mele. Amin.",
    step: "Spune-I azi și îndoiala ta, nu doar cererea.",
  },
  {
    id: "dev_196",
    dayNumber: 196,
    theme: LUNA_7,
    axis: "living_faith",
    verseRef: "Iacov 4:3",
    verseText: "Sau cereți și nu căpătați, pentru că cereți rău, cu gând să risipiți în plăcerile voastre.",
    meditation:
      "Uneori răspunsul întârzie pentru că cererea nu e curată. Nu e o acuzație generală — e o invitație să te uiți în spatele cererii tale și să vezi motivul. Un Tată bun refuză uneori exact pentru că te iubește.",
    question: "De ce vrei, de fapt, lucrul pentru care te rogi?",
    prayer: "Doamne, cercetează-mi motivele. Nu vreau să mă mint. Amin.",
    step: "Scrie o cerere și, sub ea, motivul adevărat. Compară-le.",
  },
  {
    id: "dev_197",
    dayNumber: 197,
    theme: LUNA_7,
    axis: "living_faith",
    verseRef: "1 Ioan 5:14",
    verseText: "Îndrăzneala pe care o avem la El este că, dacă cerem ceva după voia Lui, ne ascultă.",
    meditation:
      "Siguranța noastră nu stă în intensitatea rugăciunii, ci în acordul cu voia Lui. De aceea merită să știi ce a spus deja în Scriptură: multe lucruri nu trebuie ghicite. Cine citește Biblia învață să se roage mai bine.",
    question: "Știi ce a spus deja Dumnezeu despre lucrul pentru care te rogi?",
    prayer: "Doamne, aliniază-mi cererile cu voia Ta. Amin.",
    step: "Caută azi un verset care vorbește despre situația ta și roagă-te cu el.",
  },
  {
    id: "dev_198",
    dayNumber: 198,
    theme: LUNA_7,
    axis: "living_faith",
    verseRef: "Psalmul 62:8",
    verseText: "Popoare, în orice vreme, încredeți-vă în El, vărsați-vă inimile înaintea Lui! Dumnezeu este adăpostul nostru.",
    meditation:
      "„Vărsați” e un cuvânt fără eleganță: răstorni tot, nu torni cu grijă. Dumnezeu nu are nevoie de un rezumat ordonat al stării tale. Multe rugăciuni sunt seci pentru că sunt politicoase.",
    question: "Ce n-ai spus încă, pentru că sună urât?",
    prayer: "Doamne, în fața Ta răstorn tot ce am în piept. Amin.",
    step: "Roagă-te azi cu voce tare, singur, exact ce simți.",
  },
  {
    id: "dev_199",
    dayNumber: 199,
    theme: LUNA_7,
    axis: "living_faith",
    verseRef: "Psalmul 5:3",
    verseText: "Doamne, auzi-mi glasul dimineața! Dimineața, eu îmi îndrept rugăciunea spre Tine și aștept.",
    meditation:
      "Ultimul cuvânt e cel mai greu: „aștept”. Rugăciunea nu se termină când taci; urmează partea în care stai cu ochii pe drum. Cine cere și pleacă imediat nu vede răspunsurile când vin.",
    question: "Aștepți răspunsul sau treci imediat la ziua ta?",
    prayer: "Doamne, am cerut. Acum aștept. Amin.",
    step: "După rugăciunea de azi, stai un minut în liniște, ca și cum ai aștepta.",
  },
  {
    id: "dev_200",
    dayNumber: 200,
    theme: LUNA_7,
    axis: "living_faith",
    verseRef: "Marcu 1:35",
    verseText: "A doua zi dimineața, pe când era încă întuneric de tot, Isus S-a sculat, a ieșit și S-a dus într-un loc pustiu. Și Se ruga acolo.",
    meditation:
      "Isus avea cea mai bună legătură posibilă cu Tatăl și totuși Și-a făcut timp și loc. Se sculase după o zi încheiată târziu, cu tot orașul la ușă. Dacă El a avut nevoie de ora aceea, nu e o pierdere de timp pentru tine.",
    question: "Ce ar trebui să muți în program ca să ai un sfert de oră cu El?",
    prayer: "Doamne, Îți dau prima parte a zilei. Amin.",
    step: "Pune azi ceasul cu cincisprezece minute mai devreme pentru mâine.",
  },
  {
    id: "dev_201",
    dayNumber: 201,
    theme: LUNA_7,
    axis: "living_faith",
    verseRef: "Luca 6:12",
    verseText: "În zilele acelea, Isus S-a dus în munte să Se roage și a petrecut toată noaptea în rugăciune către Dumnezeu.",
    meditation:
      "A doua zi Și-a ales cei doisprezece ucenici. Deciziile mari cer rugăciune pe măsură — nu ca să-L convingi, ci ca să vezi limpede. Câte hotărâri ai luat anul ăsta fără să te fi rugat serios pentru ele?",
    question: "Ce decizie ți-ar cere o noapte de rugăciune?",
    prayer: "Doamne, nu vreau să hotărăsc singur. Amin.",
    step: "Amână azi o decizie cu o zi și roagă-te pentru ea înainte.",
  },
  {
    id: "dev_202",
    dayNumber: 202,
    theme: LUNA_7,
    axis: "living_faith",
    verseRef: "Matei 26:39",
    verseText: "Tată, dacă este cu putință, depărtează de la Mine paharul acesta! Totuși nu cum voiesc Eu, ci cum voiești Tu.",
    meditation:
      "Isus a cerut limpede să fie scutit. Deci nu e nelegiuit să ceri să treacă paharul. Rugăciunea Lui are două jumătăți și tocmai a doua o face rugăciune, nu cerere.",
    question: "Care e paharul pe care I-ai cere să-l depărteze?",
    prayer: "Tată, depărtează paharul. Și totuși, facă-se voia Ta. Amin.",
    step: "Rostește azi rugăciunea asta cu ambele jumătăți, pe situația ta.",
  },
  {
    id: "dev_203",
    dayNumber: 203,
    theme: LUNA_7,
    axis: "living_faith",
    verseRef: "Neemia 2:4",
    verseText: "Și împăratul mi-a zis: „Ce ceri?” Eu m-am rugat Dumnezeului cerurilor",
    meditation:
      "Între întrebarea împăratului și răspunsul lui Neemia încape o rugăciune de două secunde. Nimeni din sală n-a observat. Așa se roagă un om care știe că Dumnezeu e la o distanță de un gând.",
    question: "Te rogi înainte să răspunzi la lucrurile importante?",
    prayer: "Doamne, dă-mi cuvintele potrivite acum. Amin.",
    step: "Înainte de următoarea discuție importantă de azi, roagă-te două secunde.",
  },
  {
    id: "dev_204",
    dayNumber: 204,
    theme: LUNA_7,
    axis: "living_faith",
    verseRef: "2 Cronici 20:12",
    verseText: "Căci noi suntem fără putere înaintea acestei mari mulțimi care înaintează împotriva noastră și nu știm ce să facem, dar ochii noștri sunt îndreptați spre Tine!",
    meditation:
      "E rugăciunea unui împărat înaintea unei armate și conține trei recunoașteri: nu avem putere, nu știm ce să facem, ne uităm la Tine. Nu e o rugăciune de învins. Dumnezeu a răspuns că lupta e a Lui.",
    question: "În ce situație ai putea spune exact cuvintele astea?",
    prayer: "Doamne, nu știu ce să fac, dar ochii mei sunt spre Tine. Amin.",
    step: "Scrie versetul ăsta și pune-l acolo unde te lovește nesiguranța.",
  },
  {
    id: "dev_205",
    dayNumber: 205,
    theme: LUNA_7,
    axis: "living_faith",
    verseRef: "1 Samuel 1:15",
    verseText: "Nu, domnul meu, eu sunt o femeie care suferă în inima ei și n-am băut nici vin, nici băutură amețitoare, ci îmi vărsam sufletul înaintea Domnului.",
    meditation:
      "Ana se ruga atât de tulburată încât preotul a crezut că e beată. Se ruga fără glas, doar cu buzele. Dumnezeu a auzit rugăciunea pe care nici omul din templu n-a putut-o auzi.",
    question: "Crezi că El aude și ce nu poți rosti?",
    prayer: "Doamne, îmi vărs sufletul înaintea Ta, chiar dacă nu iese niciun sunet. Amin.",
    step: "Roagă-te azi în gând, într-un loc public, pentru cineva de lângă tine.",
  },
  {
    id: "dev_206",
    dayNumber: 206,
    theme: LUNA_7,
    axis: "living_faith",
    verseRef: "Psalmul 66:18-19",
    verseText: "Dacă aș fi cugetat lucruri nelegiuite în inima mea, nu m-ar fi ascultat Domnul. Dar Dumnezeu m-a ascultat, a luat aminte la glasul rugăciunii mele.",
    meditation:
      "Nu e vorba de a fi perfect, ci de a ascunde intenționat un lucru și a cere binecuvântare peste el. O inimă care refuză să se lase cercetată își închide singură ușa. Mărturisirea deschide iar linia.",
    question: "Ce știi că stă între tine și o rugăciune sinceră?",
    prayer: "Doamne, cercetează-mă și arată-mi ce ascund. Amin.",
    step: "Mărturisește-I azi lucrul acela și lasă-l acolo.",
  },
  {
    id: "dev_207",
    dayNumber: 207,
    theme: LUNA_7,
    axis: "living_faith",
    verseRef: "Coloseni 4:2",
    verseText: "Stăruiți în rugăciune, vegheați în ea cu mulțumiri.",
    meditation:
      "„Vegheați” înseamnă și să fii atent la răspunsuri, nu doar treaz la ore târzii. Cine ține minte ce a cerut vede ce a primit. Mulțumirea e memoria rugăciunii.",
    question: "Ce ai primit și ai uitat să mulțumești?",
    prayer: "Doamne, mulțumesc pentru răspunsurile pe care nici nu le-am observat. Amin.",
    step: "Fă o listă scurtă cu rugăciuni la care s-a răspuns anul ăsta.",
  },
  {
    id: "dev_208",
    dayNumber: 208,
    theme: LUNA_7,
    axis: "living_faith",
    verseRef: "Efeseni 6:18",
    verseText: "Faceți în toată vremea, prin Duhul, tot felul de rugăciuni și cereri. Vegheați la aceasta cu toată stăruința și rugăciune pentru toți sfinții",
    meditation:
      "Pavel așază rugăciunea la capătul armurii, ca lucrul care le ține pe toate în funcțiune. Și o întoarce spre alții: „pentru toți sfinții”. Un om care se roagă doar pentru sine se împuținează.",
    question: "Cât din rugăciunea ta e despre tine?",
    prayer: "Doamne, învață-mă să mă rog și pentru alții. Amin.",
    step: "Fă-ți azi o listă cu cinci oameni și roagă-te pe nume pentru ei.",
  },
  {
    id: "dev_209",
    dayNumber: 209,
    theme: LUNA_7,
    axis: "living_faith",
    verseRef: "Luca 11:13",
    verseText: "Deci, dacă voi, care sunteți răi, știți să dați daruri bune copiilor voștri, cu cât mai mult Tatăl vostru cel din ceruri va da Duhul Sfânt celor ce I-L cer!",
    meditation:
      "Cel mai bun răspuns pe care Îl poate da Dumnezeu nu e un lucru, ci El Însuși. Isus încheie învățătura despre rugăciune arătând care e darul de care ai cea mai mare nevoie. Cere-L pe El, nu doar ce poți obține de la El.",
    question: "L-ai cerut vreodată pe Duhul Sfânt, așa, simplu?",
    prayer: "Tată, dă-mi Duhul Tău. Pe Tine Te vreau. Amin.",
    step: "Cere-I azi pe El, nu un lucru de la El.",
  },
  {
    id: "dev_210",
    dayNumber: 210,
    theme: LUNA_7,
    axis: "living_faith",
    verseRef: "Apocalipsa 8:4",
    verseText: "Fumul de tămâie s-a ridicat din mâna îngerului înaintea lui Dumnezeu, împreună cu rugăciunile sfinților.",
    meditation:
      "Se încheie luna rugăciunii cu o imagine din cer: rugăciunile nu se pierd. Ce ai șoptit într-o bucătărie e păstrat și adus înaintea lui Dumnezeu. Luna viitoare vorbim despre ce faci când El pare că tace — și pornește tocmai de la versetul ăsta.",
    question: "Ce rugăciune a ta pare pierdută?",
    prayer: "Doamne, rugăciunile mele sunt la Tine. Țin minte asta. Amin.",
    step: "Recitește cererea scrisă în ziua 186 și notează ce s-a schimbat.",
  },
]
