// Devoțional, luna 10: „Lucrurile mici” (docs/27 §2.4, axa character).
//
// Regula lunii: după luna în care am văzut că lucrurile cresc pe nevăzut, aici se
// arată din ce anume cresc — din gesturi mici, repetate, pe care nu le vede
// nimeni. Nicio zi nu cere fapte mari; toate cer un singur lucru făcut bine azi.
//
// Conținut ORIGINAL Emanus (docs/27 §1.2). Versete: Cornilescu (domeniu public).
import type { DevotionalDay } from "./devotional.js"

const LUNA_10 = "Lucrurile mici"

export const DEVOTIONAL_DAYS_LUNA_10: DevotionalDay[] = [
  {
    id: "dev_271",
    dayNumber: 271,
    theme: LUNA_10,
    axis: "character",
    verseRef: "Zaharia 4:10",
    verseText: "Căci cine disprețuiește ziua începuturilor slabe?",
    meditation:
      "Întrebarea e pusă unor oameni care rezideau Templul și erau rușinați că iese mai mic decât cel vechi. Dumnezeu nu le spune că e mare, ci că nu e de disprețuit. Ziua începuturilor mici e tot o zi a Lui.",
    question: "Ce început al tău ți se pare prea mic ca să conteze?",
    prayer: "Doamne, nu-mi disprețui începutul și învață-mă să nu-l disprețuiesc nici eu. Amin.",
    step: "Scrie un lucru mic pe care l-ai început și nu l-ai spus nimănui.",
  },
  {
    id: "dev_272",
    dayNumber: 272,
    theme: LUNA_10,
    axis: "character",
    verseRef: "Luca 16:10",
    verseText: "Cine este credincios în cele mai mici lucruri este credincios și în cele mari.",
    meditation:
      "Isus nu spune că lucrurile mici duc la cele mari, ci că ele arată deja cine ești. Nu există două caractere, unul pentru lucrurile importante și altul pentru fleacuri. Cine minte în lucruri mărunte a învățat deja să mintă.",
    question: "În ce lucru mic ești nesincer, pentru că „nu contează”?",
    prayer: "Doamne, fă-mă același om și în lucrurile pe care nu le vede nimeni. Amin.",
    step: "Îndreaptă azi o mică nesinceritate: o scuză, o exagerare, o întârziere ascunsă.",
  },
  {
    id: "dev_273",
    dayNumber: 273,
    theme: LUNA_10,
    axis: "character",
    verseRef: "Matei 25:21",
    verseText: "Bine, rob bun și credincios, ai fost credincios în puține lucruri, te voi pune peste multe lucruri; intră în bucuria stăpânului tău!",
    meditation:
      "Lauda nu e pentru cât a produs, ci pentru că a fost credincios. Cel cu două talanți primește exact aceeași propoziție ca cel cu cinci. Dumnezeu nu compară oamenii între ei.",
    question: "Ce ți-a dat ție în mână, mic și concret?",
    prayer: "Doamne, vreau să fiu credincios cu puținul meu. Amin.",
    step: "Fă azi bine lucrul pe care ți l-a dat de făcut, chiar dacă e neimportant.",
  },
  {
    id: "dev_274",
    dayNumber: 274,
    theme: LUNA_10,
    axis: "character",
    verseRef: "Luca 21:2-3",
    verseText: "A văzut și pe o văduvă săracă aruncând acolo doi bănuți. Și a zis: „Adevărat vă spun că această văduvă săracă a aruncat mai mult decât toți ceilalți.”",
    meditation:
      "Isus stătea și se uita la vistierie — deci se uită și la sumele mici. Contabilitatea Lui nu măsoară cât ai dat, ci cât ți-a rămas. Doi bănuți dați din sărăcie cântăresc mai greu decât o sumă mare dată din prisos.",
    question: "Când ai dat ultima dată ceva care să te coste?",
    prayer: "Doamne, primește și puținul meu. Amin.",
    step: "Dă azi ceva care să se simtă: timp, bani sau un lucru la care ții.",
  },
  {
    id: "dev_275",
    dayNumber: 275,
    theme: LUNA_10,
    axis: "character",
    verseRef: "Marcu 14:8",
    verseText: "Ea a făcut ce a putut.",
    meditation:
      "E apărarea pe care i-o face Isus unei femei criticate pentru un gest „risipitor”. Nu spune că a făcut totul, ci că a făcut ce a putut — și I-a fost de ajuns. Multe zile bune sunt stricate de standarde pe care Dumnezeu nu le-a cerut.",
    question: "Te judeci pentru ce n-ai putut face?",
    prayer: "Doamne, primesc și eu măsura mea de azi. Am făcut ce am putut. Amin.",
    step: "Seara, în loc să-ți enumeri eșecurile, spune: am făcut ce am putut.",
  },
  {
    id: "dev_276",
    dayNumber: 276,
    theme: LUNA_10,
    axis: "character",
    verseRef: "Matei 10:42",
    verseText: "Și oricine va da de băut numai un pahar de apă rece unuia din acești micuți... nu-și va pierde răsplata.",
    meditation:
      "Cel mai ieftin gest posibil în Israelul acela: un pahar de apă. Isus îl așază în categoria faptelor care nu se pierd. Dumnezeu ține socoteala unor lucruri pe care noi nici nu le ținem minte.",
    question: "Ce gest mic ai putea face azi pentru cineva fără importanță socială?",
    prayer: "Doamne, dă-mi ochi pentru gesturile mici. Amin.",
    step: "Fă azi un gest pentru cineva care nu-ți poate întoarce favoarea.",
  },
  {
    id: "dev_277",
    dayNumber: 277,
    theme: LUNA_10,
    axis: "character",
    verseRef: "Ioan 6:9",
    verseText: "Este aici un băiețel care are cinci pâini de orz și doi pești; dar ce sunt acestea la atâția?",
    meditation:
      "Pâinea de orz era mâncarea săracilor, iar cantitatea era ridicolă față de nevoie. Andrei spune și partea bună, și îndoiala, în aceeași propoziție. Isus n-a cerut mai mult; a cerut ce era acolo.",
    question: "Ce ai tu, puțin și real, și nu vrei să dai pentru că pare ridicol?",
    prayer: "Doamne, Îți dau cele cinci pâini ale mele. Amin.",
    step: "Oferă azi lucrul mic pe care îl poți face, chiar dacă nevoia e uriașă.",
  },
  {
    id: "dev_278",
    dayNumber: 278,
    theme: LUNA_10,
    axis: "character",
    verseRef: "2 Împărați 5:13",
    verseText: "Părinte, dacă prorocul ți-ar fi cerut un lucru greu, nu l-ai fi făcut? Cu atât mai mult trebuie să faci ce ți-a spus: „Spală-te și vei fi curat.”",
    meditation:
      "Naaman s-a supărat că vindecarea era prea simplă. Suntem dispuși la eforturi mari și refuzăm ascultarea măruntă, pentru că aceea nu ne face eroi. Slujitorii lui au avut curajul să-i spună asta în față.",
    question: "Ce lucru simplu ți-a spus Dumnezeu și îl ocolești pentru că pare banal?",
    prayer: "Doamne, ascult și în lucrurile care nu mă fac să par mare. Amin.",
    step: "Fă azi acel lucru simplu, exact așa cum ți-a fost spus.",
  },
  {
    id: "dev_279",
    dayNumber: 279,
    theme: LUNA_10,
    axis: "character",
    verseRef: "1 Împărați 18:44",
    verseText: "Și a șaptea oară, slujitorul a zis: „Iată că se ridică un mic nor din mare, de mărimea unei palme de om.”",
    meditation:
      "După trei ani de secetă, semnul a fost cât o palmă — și a fost de ajuns pentru Ilie ca să anunțe ploaia. Slujitorul s-a uitat de șapte ori înainte să vadă ceva. Învățătura e să te mai uiți o dată și să nu ceri semne mari.",
    question: "Ce nor cât o palmă ai văzut și n-ai luat în seamă?",
    prayer: "Doamne, mulțumesc pentru semnele mici. Le iau în serios. Amin.",
    step: "Notează azi trei lucruri mici bune care s-au întâmplat.",
  },
  {
    id: "dev_280",
    dayNumber: 280,
    theme: LUNA_10,
    axis: "character",
    verseRef: "Iacov 3:4-5",
    verseText: "Iată, și corăbiile, măcar că sunt așa de mari și mânate de vânturi puternice, totuși sunt cârmuite de o cârmă foarte mică. Tot așa și limba este un mic mădular.",
    meditation:
      "Lucrurile mici nu sunt doar bune; unele sunt periculoase tocmai pentru că par neimportante. O propoziție spusă în treacăt poate schimba direcția unei zile întregi într-o casă. Cârma e mică, dar hotărăște unde ajunge corabia.",
    question: "Ce propoziție mică spui des și strici cu ea?",
    prayer: "Doamne, pune pază gurii mele, mai ales în lucrurile mici. Amin.",
    step: "Taie azi o vorbă din obișnuința ta: o ironie, un of, o înjurătură.",
  },
  {
    id: "dev_281",
    dayNumber: 281,
    theme: LUNA_10,
    axis: "character",
    verseRef: "Cântarea Cântărilor 2:15",
    verseText: "Prindeți-ne vulpile, vulpile cele mici, care strică viile.",
    meditation:
      "Nu lupii strică via, ci vulpile mici. În căsnicii și în prietenii, rareori distruge o catastrofă — de obicei sunt zeci de lucruri mărunte lăsate nerezolvate. Cine strangă vulpile mici salvează via.",
    question: "Care e vulpea mică din relația ta cea mai apropiată?",
    prayer: "Doamne, ajută-mă să prind vulpile mici înainte să facă pagubă. Amin.",
    step: "Rezolvă azi o mică nemulțumire, înainte să devină mare.",
  },
  {
    id: "dev_282",
    dayNumber: 282,
    theme: LUNA_10,
    axis: "character",
    verseRef: "Neemia 4:6",
    verseText: "Am zidit zidul, care a fost isprvit pretutindeni până la jumătate din înălțimea lui. Și poporul lucra cu inimă.",
    meditation:
      "Zidul Ierusalimului a fost ridicat pentru că fiecare familie a lucrat în dreptul casei ei. Nimeni n-a văzut tot șantierul; fiecare și-a văzut bucata. Așa se ridică lucruri mari: porțiuni mici, făcute simultan de oameni obișnuiți.",
    question: "Care e bucata ta de zid?",
    prayer: "Doamne, dă-mi inimă să lucrez în dreptul casei mele. Amin.",
    step: "Repară azi ceva concret la tine acasă sau în biserica ta.",
  },
  {
    id: "dev_283",
    dayNumber: 283,
    theme: LUNA_10,
    axis: "character",
    verseRef: "Matei 6:3-4",
    verseText: "Ci tu, când faci milostenie, să nu știe stânga ta ce face dreapta, pentru ca milostenia ta să fie făcută în ascuns.",
    meditation:
      "Isus cere o disțiplină ciudată: să faci binele și să-l uiți. Un bine povestit și-a primit deja plata. Ce rămâne în ascuns rămâne între tine și Dumnezeu.",
    question: "Cât din binele tău are nevoie de martori?",
    prayer: "Doamne, vreau să fac bine și să tac. Amin.",
    step: "Fă azi un bine despre care nu vei spune nimănui, niciodată.",
  },
  {
    id: "dev_284",
    dayNumber: 284,
    theme: LUNA_10,
    axis: "character",
    verseRef: "Coloseni 3:23",
    verseText: "Orice faceți, să faceți din toată inima, ca pentru Domnul, nu ca pentru oameni.",
    meditation:
      "Pavel scria asta unor robi, oameni fără nicio poziție și cu munci mărunte. Le spune că munca lor are alt destinatar decât stăpânul pământesc. Asta ridică spălatul vaselor la nivel de închinare.",
    question: "Ce muncă a ta ți se pare umilitoare sau inutilă?",
    prayer: "Doamne, munca mea de azi e pentru Tine. Amin.",
    step: "Fă azi cea mai plictisitoare sarcină cu grijă, ca și cum I-o dai Lui.",
  },
  {
    id: "dev_285",
    dayNumber: 285,
    theme: LUNA_10,
    axis: "character",
    verseRef: "1 Corinteni 10:31",
    verseText: "Deci, fie că mâncați, fie că beți, fie că faceți altceva, să faceți totul pentru slava lui Dumnezeu.",
    meditation:
      "Pavel ia cele mai banale acte omenești — mâncatul și băutul — și le pune sub același scop. Nu există zonă neutră în viața unui om care Îi aparține. Sfințenia nu e o activitate separată de restul zilei.",
    question: "Care parte a zilei tale ți se pare „neutră” din punct de vedere duhovnicesc?",
    prayer: "Doamne, ia și ziua mea obișnuită. Amin.",
    step: "Roagă-te azi înainte de o activitate banală: masa, drumul, curățenia.",
  },
  {
    id: "dev_286",
    dayNumber: 286,
    theme: LUNA_10,
    axis: "character",
    verseRef: "1 Tesaloniceni 4:11",
    verseText: "Să cautăți să trăiți liniștiți, să vă vedeți de treburi și să lucrați cu mâinile voastre.",
    meditation:
      "E o ambiție ciudată pentru creștini: să trăiești liniștit. Într-o lume care cere vizibilitate, Pavel recomandă o viață așezată și o muncă făcută cu mâinile. Nu toată lumea e chemată la scenă; aproape toată lumea e chemată la statornicie.",
    question: "Cauți liniște sau cauți să fii văzut?",
    prayer: "Doamne, dă-mi o viață așezată, chiar dacă nu impresionează pe nimeni. Amin.",
    step: "Renunță azi la o postare sau la o povestire despre tine.",
  },
  {
    id: "dev_287",
    dayNumber: 287,
    theme: LUNA_10,
    axis: "character",
    verseRef: "Proverbe 13:11",
    verseText: "Bogăția câștigată fără trudă scade, dar ce se strânge încetul cu încetul crește.",
    meditation:
      "Proverbul vorbește despre bani, dar legea e mai largă: ce vine repede pleacă repede. Se aplică la sănătate, la prietenii și la cunoașterea Scripturii. Încetul cu încetul nu e o consolare pentru încei, ci calea normală.",
    question: "Ce vrei să obții repede și ar trebui câștigat încet?",
    prayer: "Doamne, învață-mă să strâng încetul cu încetul. Amin.",
    step: "Alege un lucru și pune azi deoparte pentru el: bani, timp sau efort.",
  },
  {
    id: "dev_288",
    dayNumber: 288,
    theme: LUNA_10,
    axis: "character",
    verseRef: "Proverbe 6:6",
    verseText: "Du-te la furnică, leneșule; uită-te cu băgare de seamă la căile ei și înțelepțește-te!",
    meditation:
      "Furnica nu are șef și totuși își strânge hrana la vreme. Înțelepciunea de aici nu e despre talent, ci despre ritm: puțin, în fiecare zi, la timpul potrivit. Cel mai bun lucru pe care îl poți învăța de la o insectă e consecvența.",
    question: "Ce faci doar când te obligă cineva?",
    prayer: "Doamne, dă-mi ritm și statornicie fără să fiu îmins de la spate. Amin.",
    step: "Fă azi, din proprie inițiativă, un lucru pe care nu ți l-a cerut nimeni.",
  },
  {
    id: "dev_289",
    dayNumber: 289,
    theme: LUNA_10,
    axis: "character",
    verseRef: "Proverbe 24:30-31",
    verseText: "Am trecut pe lângă ogorul unui leneș... și era acoperit cu spini, urțicile creșteau peste tot, și zidul de piatră era prăbușit.",
    meditation:
      "Nimeni n-a dărâmat zidul acela; a căzut singur, din nefacere. Paragina nu e un eveniment, ci suma multor zile în care nu s-a făcut nimic. Lucrurile bune nu se strică brusc, ci prin neglijare.",
    question: "Ce zid din viața ta se surpă încet, pentru că nu-l repari?",
    prayer: "Doamne, arată-mi paragina din viața mea. Amin.",
    step: "Alege un lucru neglijat și dă-i azi cincisprezece minute.",
  },
  {
    id: "dev_290",
    dayNumber: 290,
    theme: LUNA_10,
    axis: "character",
    verseRef: "Eclesiastul 9:10",
    verseText: "Tot ce găsește mâna ta să facă, fă cu toată puterea ta!",
    meditation:
      "Nu „tot ce visezi”, ci „tot ce găsește mâna ta” — adică ce e în fața ta acum. Multe vieți trec în așteptarea sarcinii potrivite. Ascultarea începe cu ce ți-a căzut în mână azi.",
    question: "Ce e în mâna ta azi și faci pe jumătate?",
    prayer: "Doamne, ajută-mă să fac întreg lucrul din fața mea. Amin.",
    step: "Termină azi un lucru lăsat pe jumătate.",
  },
  {
    id: "dev_291",
    dayNumber: 291,
    theme: LUNA_10,
    axis: "character",
    verseRef: "Deuteronom 6:7",
    verseText: "Să le întipărești în mintea copiilor tăi și să vorbești de ele când vei fi acasă, când vei pleca în călătorie, când te vei culca și când te vei scula.",
    meditation:
      "Creșterea unui copil în credință nu se face la evenimente, ci în drum, la masă și la culcare. Sunt momente mici, care par pierdute. Din ele se face, în zece ani, o memorie.",
    question: "Care e momentul zilnic în care ai putea vorbi firesc despre Dumnezeu?",
    prayer: "Doamne, fă-mă să vorbesc despre Tine în mersul zilei, nu doar duminica. Amin.",
    step: "Spune azi, la masă sau în mașină, o propoziție despre Dumnezeu.",
  },
  {
    id: "dev_292",
    dayNumber: 292,
    theme: LUNA_10,
    axis: "character",
    verseRef: "Luca 2:51-52",
    verseText: "Apoi S-a coborât împreună cu ei, a venit la Nazaret și le era supus... Și Isus creștea în înțelepciune, în statură și era tot mai plăcut înaintea lui Dumnezeu și înaintea oamenilor.",
    meditation:
      "Isus a petrecut vreo treizeci de ani într-un sat mic, făcând muncă obișnuită, și doar trei în lucrare publică. Cea mai mare parte a vieții Lui n-a fost spectaculoasă. Dacă anii ascunși au fost buni pentru El, nu sunt timp pierdut nici pentru tine.",
    question: "Consideri anii tăi obișnuiți timp pierdut?",
    prayer: "Doamne, sfințește și anii mei ascunși. Amin.",
    step: "Mulțumește-I azi pentru o perioadă banală din viața ta.",
  },
  {
    id: "dev_293",
    dayNumber: 293,
    theme: LUNA_10,
    axis: "character",
    verseRef: "Luca 16:11",
    verseText: "Deci, dacă n-ați fost credincioși în bogățiile nedrepte, cine vă va încredința adevăratele bogății?",
    meditation:
      "Banii sunt, pentru Isus, un lucru mic — iar felul în care îi folosești arată ce ți se poate încredința mai departe. Nu e o predică despre sărăcie, ci despre administrare. Un om corect cu banii mărunți e un om căruia i se pot da suflete.",
    question: "Ce spun cheltuielile tale din ultima lună despre tine?",
    prayer: "Doamne, învață-mă să fiu bun administrator al puținului. Amin.",
    step: "Uiță-te azi peste cheltuielile ultimei luni și taie una.",
  },
  {
    id: "dev_294",
    dayNumber: 294,
    theme: LUNA_10,
    axis: "character",
    verseRef: "Fapte 9:39",
    verseText: "Toate văduvele l-au înconjurat plângând și i-au arătat hainele și cămășile pe care le făcea Dorca pe când era cu ele.",
    meditation:
      "Dorca n-a lăsat predici, ci cămăși. Toată mărturia vieții ei a fost ținută în mâini de niște femei sărace. E cea mai concretă dovadă că lucrurile mici se văd, până la urmă.",
    question: "Ce vor ține oamenii în mână după tine?",
    prayer: "Doamne, dă-mi ceva de făcut cu mâinile mele pentru alții. Amin.",
    step: "Fă azi ceva cu mâinile tale pentru cineva: gătește, repară, coase, cară.",
  },
  {
    id: "dev_295",
    dayNumber: 295,
    theme: LUNA_10,
    axis: "character",
    verseRef: "Rut 2:3",
    verseText: "Ea s-a dus într-un ogor să strângă spice pe urma secerătorilor. Și s-a întâmplat că ogorul acela era al lui Boaz.",
    meditation:
      "Rut s-a dus să facă o muncă umilă ca să aibă ce mânca, iar textul spune sec: „s-a întâmplat”. În povestea aceea, întâmplarea a devenit strămoșii lui David. Providența lucrează cel mai des în timp ce tu îți faci treaba.",
    question: "Ce muncă modestă ai de făcut azi?",
    prayer: "Doamne, îmi fac treaba și las întâmplările în grija Ta. Amin.",
    step: "Fă-ți azi treaba fără să te plângi nici măcar o dată.",
  },
  {
    id: "dev_296",
    dayNumber: 296,
    theme: LUNA_10,
    axis: "character",
    verseRef: "Exod 4:2",
    verseText: "Domnul i-a zis: „Ce ai în mână?” El a răspuns: „Un toiag.”",
    meditation:
      "Moise aștepta putere și Dumnezeu i-a cerut bățul de cioban pe care îl avea deja. Lucrurile mari din Exod s-au făcut cu obiectul lui de muncă. Dumnezeu începe de obicei cu ce ai în mână, nu cu ce ți-ar trebui.",
    question: "Ce ai tu în mână acum?",
    prayer: "Doamne, ia ce am în mână și folosește. Amin.",
    step: "Numește un lucru pe care știi să-l faci și oferă-l săptămâna asta cuiva.",
  },
  {
    id: "dev_297",
    dayNumber: 297,
    theme: LUNA_10,
    axis: "character",
    verseRef: "Matei 13:33",
    verseText: "Împărăția cerurilor se aseamănă cu un aluat pe care l-a luat o femeie și l-a pus în trei măsuri de făină, până s-a dospit toată plămădeala.",
    meditation:
      "Aluatul lucrează fără zgomot și fără să-l vezi, dar schimbă toată plămădeala. Așa se răspândește Împărăția: nu prin cucerire, ci prin pătrundere. Un creștin așezat într-un birou sau într-o familie e aluat.",
    question: "În ce „plămădeală” te-a pus Dumnezeu?",
    prayer: "Doamne, fă-mă aluat acolo unde m-ai pus. Amin.",
    step: "Adu azi ceva bun în locul în care lucrezi, fără să ții predici.",
  },
  {
    id: "dev_298",
    dayNumber: 298,
    theme: LUNA_10,
    axis: "character",
    verseRef: "1 Corinteni 15:58",
    verseText: "Fiți tari, neclintiți, sporiți totdeauna în lucrul Domnului, căci știți că osteneala voastră în Domnul nu este zadarnică.",
    meditation:
      "Pavel spune asta imediat după capitolul despre înviere — deci temeiul e că nimic bun nu se pierde într-o lume în care morții învie. Sentimentul că munca ta e zadarnică e frecvent și fals. Nu ești plătit în aplauze, ci în înviere.",
    question: "Ce muncă a ta ți se pare zadarnică?",
    prayer: "Doamne, cred că osteneala mea nu e zadarnică. Amin.",
    step: "Continuă azi lucrul despre care ai crezut că nu folosește la nimic.",
  },
  {
    id: "dev_299",
    dayNumber: 299,
    theme: LUNA_10,
    axis: "character",
    verseRef: "Evrei 6:10",
    verseText: "Căci Dumnezeu nu este nedrept ca să uite osteneala voastră și dragostea pe care ați arătat-o pentru Numele Lui, voi, care ați ajutorat și ajutorați pe sfinți.",
    meditation:
      "Oamenii uită repede ce ai făcut pentru ei; Dumnezeu nu. Versetul nu promite recunoaștere aici, ci spune că memoria Lui e dreaptă. Multe gesturi din viața ta sunt ținute minte doar de El — și asta e destul.",
    question: "Ce bine ai făcut și n-a fost băgat în seamă?",
    prayer: "Doamne, mulțumesc că Tu nu uiți. Amin.",
    step: "Mulțumește azi cuiva pentru un lucru vechi, pe care nu l-a observat nimeni.",
  },
  {
    id: "dev_300",
    dayNumber: 300,
    theme: LUNA_10,
    axis: "character",
    verseRef: "Luca 19:17",
    verseText: "El i-a zis: „Bine, rob bun; fiindcă ai fost credincios în puține lucruri, primește cârmuirea a zece cetăți.”",
    meditation:
      "E ziua 300 și ai ajuns aici tot printr-un lucru mic, repetat: ai deschis pagina asta. Dumnezeu nu îți cere să fii mare, ci credincios în puțin. Luna viitoare intrăm într-un loc mai greu, rușinea — pentru că tocmai ea îi face pe oameni să creadă că puținul lor nu valorează nimic.",
    question: "Ce lucru mic ai făcut zilnic în luna asta?",
    prayer: "Doamne, rămân credincios în puțin. Amin.",
    step: "Recitește ce ai scris în ziua 271 și vezi ct a crescut acel început.",
  },
]
