// Devoțional, luna 5: „Iertarea” (docs/27 §2.4, axa relationships).
//
// Regula lunii: iertarea nu înseamnă că fapta a fost mică, ci că nu mai ceri tu
// plata pentru ea. Se scrie fără grăbire: cine e rănit nu are nevoie de lecții,
// ci de un drum — de aceea zilele merg de la iertarea primită spre cea dată.
// Nicăieri în luna asta iertarea nu înseamnă întoarcerea într-un loc periculos.
//
// Conținut ORIGINAL Emanus (docs/27 §1.2). Versete: Cornilescu VDC 1924
// (domeniu public), colaționate verset cu verset.
import type { DevotionalDay } from "./devotional.js"

const LUNA_5 = "Iertarea"

export const DEVOTIONAL_DAYS_LUNA_5: DevotionalDay[] = [
  {
    id: "dev_121",
    dayNumber: 121,
    theme: LUNA_5,
    axis: "relationships",
    verseRef: "Efeseni 4:32",
    verseText: "Dimpotrivă, fiți buni unii cu alții, miloși și iertați-vă unul pe altul, cum v-a iertat și Dumnezeu pe voi în Hristos.",
    meditation:
      "Ordinea din verset e totul: întâi ce ți s-a făcut ție, apoi ce ai de făcut tu. Nimeni nu poate scoate din el o iertare pe care n-a primit-o întâi. Luna asta începe cu tine în postura celui iertat, nu a celui care trebuie să ierte.",
    question: "Când te-ai simțit ultima dată cu adevărat iertat?",
    prayer: "Doamne, înainte să-mi ceri să iert, amintește-mi că sunt iertat. Amin.",
    step: "Scrie o propoziție: „Dumnezeu m-a iertat de…” și las-o unde o vezi azi.",
  },
  {
    id: "dev_122",
    dayNumber: 122,
    theme: LUNA_5,
    axis: "relationships",
    verseRef: "Coloseni 3:13",
    verseText: "Încredințați-vă unii pe alții și, dacă unul are pricină să se plângă de altul, iertați-vă unul pe altul. Cum v-a iertat Hristos, așa iertați-vă și voi.",
    meditation:
      "Pavel recunoaște că există „pricină să te plângi”. Nu ți se cere să pretinzi că nu s-a întâmplat nimic și nici că nu te-a durut. Iertarea biblică începe cu recunoașterea faptei, nu cu mușamalizarea ei.",
    question: "Ai spus vreodată „nu-i nimic” când, de fapt, era ceva?",
    prayer: "Doamne, nu vreau o iertare mincinoasă. Ajută-mă să spun întâi adevărul. Amin.",
    step: "Spune-I lui Dumnezeu, pe șleau, ce anume ți s-a făcut. Nu înfrumuseța.",
  },
  {
    id: "dev_123",
    dayNumber: 123,
    theme: LUNA_5,
    axis: "relationships",
    verseRef: "Matei 6:14",
    verseText: "Dacă iertați oamenilor greșelile lor, și Tatăl vostru cel ceresc vă va ierta greșelile voastre.",
    meditation:
      "Versetul sperie mulți oameni. Nu spune că iertarea ta o cumpără pe a Lui, ci că o inimă care refuză total să dea iertare arată că n-a înțeles ce a primit. Nu e o amenințare, e un termometru.",
    question: "Ce arată despre inima ta faptul că nu poți ierta pe cineva anume?",
    prayer: "Doamne, dacă inima mea s-a împietrit, arată-mi — și înmoaie-o Tu. Amin.",
    step: "Numește azi în gând o singură persoană pe care nu ai iertat-o. Atât: numește-o.",
  },
  {
    id: "dev_124",
    dayNumber: 124,
    theme: LUNA_5,
    axis: "relationships",
    verseRef: "Matei 18:21-22",
    verseText: "Atunci, Petru s-a apropiat de El și I-a zis: „Doamne, de câte ori să iert pe fratele meu când va păcătui împotriva mea? Până la șapte ori?” Isus i-a zis: „Eu nu-ți zic până la șapte ori, ci până la șaptezeci de ori câte șapte.”",
    meditation:
      "Petru credea că e generos; rabinii vremii ziceau de trei ori. Isus nu ridică plafonul, îl desființează — cine numără tot n-a iertat. Uneori nu ierți de șaptezeci de ori pe cineva, ci de șaptezeci de ori același lucru, pentru că revine în minte.",
    question: "E ceva ce ai iertat deja, dar îți revine și trebuie iertat din nou?",
    prayer: "Doamne, iar m-am întors la rănirea aceea. Iert încă o dată. Amin.",
    step: "Când îți revine azi în minte, spune scurt: „am ales deja să iert” și mergi mai departe.",
  },
  {
    id: "dev_125",
    dayNumber: 125,
    theme: LUNA_5,
    axis: "relationships",
    verseRef: "Matei 18:27",
    verseText: "Stăpânul robului aceluia, făcându-i-se milă de el, i-a dat drumul și i-a iertat datoria.",
    meditation:
      "Datoria era de zece mii de talanți — o sumă pe care un om n-o putea câștiga în mai multe vieți. Isus a ales intenționat o cifră absurdă, ca să nu-ți treacă prin cap că ai fi putut-o plăti. Iertarea nu înseamnă că datoria a dispărut, ci că a preluat-o altcineva.",
    question: "Cât crezi că ți s-a iertat ție?",
    prayer: "Doamne, datoria mea era imposibilă, și Tu ai șters-o. Nu vreau să uit asta. Amin.",
    step: "Mulțumește-I azi, pe nume, pentru un lucru concret pe care ți l-a iertat.",
  },
  {
    id: "dev_126",
    dayNumber: 126,
    theme: LUNA_5,
    axis: "relationships",
    verseRef: "Matei 18:28",
    verseText: "Robul acela, când a ieșit afară, a întâlnit pe unul din tovarășii lui de slujbă, care-i era dator o sută de lei. A pus mâna pe el și-l strângea de gât, zicând: ‘Plătește-mi ce-mi ești dator.’",
    meditation:
      "O sută de lei nu e nimic, dar nici nu era zero — era o datorie reală. Ce ți s-a făcut ție chiar contează. Doar că, pus lângă ce ți s-a iertat, își schimbă proporția.",
    question: "Dacă pui rănirea ta lângă iertarea pe care ai primit-o, ce vezi?",
    prayer: "Doamne, nu-mi micșora durerea, dar arată-mi proporțiile. Amin.",
    step: "Nu povesti azi nimănui rănirea aceea. O zi de pauză de la repovestit.",
  },
  {
    id: "dev_127",
    dayNumber: 127,
    theme: LUNA_5,
    axis: "relationships",
    verseRef: "Luca 23:34",
    verseText: "Isus zicea: „Tată, iartă-i, căci nu știu ce fac!”",
    meditation:
      "A spus-o în timp ce se băteau cuiele, nu după ani de vindecare. Și n-a spus-o oamenilor, ci Tatălui — iertarea a început ca o rugăciune, nu ca o conversație. Uneori ăsta e singurul loc în care poți începe.",
    question: "Poți să-I ceri lui Dumnezeu să-l ierte, chiar dacă tu încă nu poți?",
    prayer: "Tată, iartă-l. Eu încă nu pot, dar nu vreau să-i doresc răul. Amin.",
    step: "Roagă-te azi zece secunde pentru omul care te-a rănit. Doar bine, nimic altceva.",
  },
  {
    id: "dev_128",
    dayNumber: 128,
    theme: LUNA_5,
    axis: "relationships",
    verseRef: "Luca 6:27-28",
    verseText: "Dar Eu vă spun vouă, care Mă ascultați: Iubiți pe vrăjmașii voștri, faceți bine celor ce vă urăsc, binecuvântați pe cei ce vă blestemă, rugați-vă pentru cei ce se poartă rău cu voi.",
    meditation:
      "Isus nu cere un sentiment, ci patru fapte: iubește, fă bine, binecuvântează, roagă-te. Sunt lucruri pe care le poți face și când inima încă nu e acolo. Adesea inima vine după fapte, nu înaintea lor.",
    question: "Care dintre cele patru ți-e cel mai la îndemână azi?",
    prayer: "Doamne, simțirile mele întârzie. Încep cu fapta. Amin.",
    step: "Fă azi un bine mic și tăcut cuiva cu care ești în răceală.",
  },
  {
    id: "dev_129",
    dayNumber: 129,
    theme: LUNA_5,
    axis: "relationships",
    verseRef: "Romani 12:18",
    verseText: "Dacă este cu putință, întru cât atârnă de voi, trăiți în pace cu toți oamenii.",
    meditation:
      "Două limitări cinstite într-un singur verset: „dacă este cu putință” și „întru cât atârnă de voi”. Sunt împăcări care nu depind de tine, pentru că celălalt nu vrea. Nu ești responsabil pentru jumătatea lui de drum.",
    question: "Cât din partea ta ai făcut, sincer?",
    prayer: "Doamne, ajută-mă să-mi fac partea și să las restul în mâna Ta. Amin.",
    step: "Scrie ce ar însemna, concret, „partea ta” într-un conflict de acum.",
  },
  {
    id: "dev_130",
    dayNumber: 130,
    theme: LUNA_5,
    axis: "relationships",
    verseRef: "Romani 12:19",
    verseText: "Preaiubiților, nu vă răzbunați singuri, ci lăsați să se răzbune mânia lui Dumnezeu, căci este scris: ‘Răzbunarea este a Mea; Eu voi răsplăti’, zice Domnul.",
    meditation:
      "Versetul nu spune că nedreptatea nu contează, ci că nu tu ești judecătorul. Iertarea nu înseamnă că fapta rămâne nepedepsită, ci că predai dosarul cuiva care judecă mai drept decât tine. E, în fond, o ușurare: nu mai trebuie să ții tu socoteala.",
    question: "Ce dosar ții deschis, ca să se facă dreptate cândva?",
    prayer: "Doamne, ți-l dau Ție. Judecă Tu, cum știi Tu. Amin.",
    step: "Spune azi cu voce tare: „nu eu sunt judecătorul lui”.",
  },
  {
    id: "dev_131",
    dayNumber: 131,
    theme: LUNA_5,
    axis: "relationships",
    verseRef: "Geneza 50:20",
    verseText: "Voi, negreșit, v-ați gândit să-mi faceți rău, dar Dumnezeu a schimbat răul în bine, ca să împlinească ceea ce se vede azi, și anume să scape viața unui popor în mare număr.",
    meditation:
      "Iosif nu spune că frații n-au greșit — zice limpede „gândit să-mi faceți rău”. Iertarea lui nu rescrie trecutul, ci vede o mână mai mare peste el. Au trecut însă douăzeci de ani până la propoziția asta.",
    question: "Ai răbdare cu tine într-un proces care poate dura ani?",
    prayer: "Doamne, nu văd încă binele. Dar cred că Tu vezi mai departe. Amin.",
    step: "Notează un lucru bun care a ieșit, cu timpul, dintr-o rănire veche.",
  },
  {
    id: "dev_132",
    dayNumber: 132,
    theme: LUNA_5,
    axis: "relationships",
    verseRef: "Geneza 45:5",
    verseText: "Acum, nu vă întristați și nu fiți mâhniți că m-ați vândut ca să fiu adus aici, căci ca să vă scap viața m-a trimis Dumnezeu înaintea voastră.",
    meditation:
      "Când s-a descoperit fraților, Iosif a plâns atât de tare încât l-au auzit egiptenii. Iertarea nu e răceală și nici stăpânire de sine perfectă. De multe ori trece exact prin locul în care în sfârșit plângi.",
    question: "Ai plâns vreodată pentru ce ți s-a făcut, sau ai sărit direct la „trebuie să iert”?",
    prayer: "Doamne, dă-mi voie să plâng înainte să iert. Amin.",
    step: "Ia-ți azi cinci minute singur, fără să-ți cenzurezi ce simți.",
  },
  {
    id: "dev_133",
    dayNumber: 133,
    theme: LUNA_5,
    axis: "relationships",
    verseRef: "Fapte 7:60",
    verseText: "Apoi, a îngenuncheat și a strigat cu glas tare: „Doamne, nu le ține în seamă păcatul acesta!”",
    meditation:
      "Ștefan a învățat asta de la Isus și a spus-o în aceleași condiții. În mulțime stătea un tânăr pe nume Saul. Nu știm ce a făcut acea rugăciune în el, dar Ștefan n-a apucat să vadă răspunsul — și asta e valabil pentru multe iertări.",
    question: "Ai putea ierta ceva fără să vezi niciodată rezultatul?",
    prayer: "Doamne, iert și fără să văd capătul. Tu vezi. Amin.",
    step: "Roagă-te azi pentru schimbarea cuiva, nu pentru pedepsirea lui.",
  },
  {
    id: "dev_134",
    dayNumber: 134,
    theme: LUNA_5,
    axis: "relationships",
    verseRef: "Proverbe 19:11",
    verseText: "Înțelepciunea face pe om răbdător și este o cinste pentru el să uite greșelile.",
    meditation:
      "Sunt răniri care nu au nevoie de o discuție, ci doar de trecere cu vederea. Nu tot ce te-a deranjat trebuie rezolvat; unele lucruri se lasă pur și simplu jos. Înțelepciunea e să știi care e care.",
    question: "Ce lucru mic ții minte deși n-ar merita niciun minut?",
    prayer: "Doamne, dă-mi înțelepciunea de a trece peste lucrurile mici. Amin.",
    step: "Lasă azi să treacă o remarcă care te-ar fi înțepat. Nu răspunde.",
  },
  {
    id: "dev_135",
    dayNumber: 135,
    theme: LUNA_5,
    axis: "relationships",
    verseRef: "1 Corinteni 13:5",
    verseText: "Dragostea… nu se mânie, nu se gândește la rău.",
    meditation:
      "„Nu se gândește la rău” e, în original, un termen de contabilitate: nu ține registrul. Sunt case în care soții au un registru complet, cu date și citate exacte. Registrul ăsta nu apără pe nimeni, doar hrănește procesul.",
    question: "Ce ții în registrul tău și poți cita pe de rost?",
    prayer: "Doamne, rup registrul. Nu vreau să țin socoteli. Amin.",
    step: "Nu scoate azi la înaintare nicio greșeală veche a nimănui într-o discuție.",
  },
  {
    id: "dev_136",
    dayNumber: 136,
    theme: LUNA_5,
    axis: "relationships",
    verseRef: "Efeseni 4:26-27",
    verseText: "„Mâniați-vă și nu păcătuiți.” Să n-apună soarele peste mânia voastră și să nu dați prilej diavolului.",
    meditation:
      "Mânia nu e interzisă; îmbătrânirea ei este. O supărare lăsată peste noapte capătă argumente, iar peste o săptămână devine convingere. De aceea Pavel pune un termen: apusul soarelui.",
    question: "Cât timp ții, de obicei, o supărare?",
    prayer: "Doamne, nu vreau să dorm cu supărarea asta. O las azi. Amin.",
    step: "Rezolvă azi, înainte de culcare, o tensiune de ieri. Un mesaj e destul.",
  },
  {
    id: "dev_137",
    dayNumber: 137,
    theme: LUNA_5,
    axis: "relationships",
    verseRef: "Evrei 12:15",
    verseText: "Luați seama bine ca nimeni să nu se abată de la harul lui Dumnezeu, pentru ca nu cumva să dea lăstari vreo rădăcină de amărăciune, să vă aducă tulburare și mulți să fie întinați de ea.",
    meditation:
      "Amărăciunea e descrisă ca o rădăcină: crește sub pământ și se vede târziu. Și nu rămâne la tine — „mulți să fie întinați”. Copiii învață să urască oameni pe care nu i-au cunoscut niciodată.",
    question: "Cine mai poartă, în afară de tine, greutatea amărăciunii tale?",
    prayer: "Doamne, taie rădăcina, nu doar frunza. Amin.",
    step: "Nu vorbi azi de rău, în fața nimănui, pe omul care te-a rănit.",
  },
  {
    id: "dev_138",
    dayNumber: 138,
    theme: LUNA_5,
    axis: "relationships",
    verseRef: "Marcu 11:25",
    verseText: "Și, când stați în picioare de vă rugați, să iertați orice aveți împotriva cuiva, pentru ca și Tatăl vostru, care este în ceruri, să vă ierte greșelile voastre.",
    meditation:
      "Isus leagă iertarea de rugăciune, nu de întâlnirea cu omul acela. Poți ierta într-o cameră goală, fără ca el să afle vreodată. Prima mișcare se face între tine și Dumnezeu.",
    question: "Ce te-ar elibera azi, chiar dacă nu vorbești cu nimeni?",
    prayer: "Doamne, aici, în liniște, aleg să iert. Amin.",
    step: "Rostește azi, singur, propoziția: „Aleg să-l iert pe…”.",
  },
  {
    id: "dev_139",
    dayNumber: 139,
    theme: LUNA_5,
    axis: "relationships",
    verseRef: "Matei 5:23-24",
    verseText: "Așa că, dacă îți aduci darul la altar și acolo îți aduci aminte că fratele tău are ceva împotriva ta, lasă-ți darul acolo, înaintea altarului, și du-te întâi de împacă-te cu fratele tău.",
    meditation:
      "Aici nu e vorba de ce ți s-a făcut, ci de ce ai făcut tu. Isus întrerupe închinarea pentru o împăcare — e singurul loc din Evanghelii în care ți se spune să lași darul și să pleci. Cerul nu primește cântarea unui om care refuză să-și ceară iertare.",
    question: "Cine ar avea ceva împotriva ta, pe drept?",
    prayer: "Doamne, arată-mi pe cine am rănit eu. Nu doar cine m-a rănit pe mine. Amin.",
    step: "Cere-ți azi iertare de la cineva, simplu, fără „dar și tu…”.",
  },
  {
    id: "dev_140",
    dayNumber: 140,
    theme: LUNA_5,
    axis: "relationships",
    verseRef: "Psalmul 32:1",
    verseText: "Ferice de cel cu fărădelegea iertată și de cel cu păcatul acoperit!",
    meditation:
      "David începe cu „ferice”, adică fericit, nu „scăpat”. Un om iertat nu e doar unul care a evitat pedeapsa, ci unul căruia i s-a ridicat greutatea din piept. Psalmul descrie mai jos oasele care se topeau cât timp tăcea.",
    question: "Ce nu ai spus încă, nici măcar lui Dumnezeu?",
    prayer: "Doamne, nu mai vreau să tac. Îi spun Ție tot. Amin.",
    step: "Mărturisește-I azi un lucru precis, nu „toate păcatele mele”.",
  },
  {
    id: "dev_141",
    dayNumber: 141,
    theme: LUNA_5,
    axis: "relationships",
    verseRef: "Psalmul 51:1",
    verseText: "Ai milă de mine, Dumnezeule, în bunătatea Ta! După îndurarea Ta cea mare, șterge fărădelegile mele!",
    meditation:
      "David nu își pledează nevinovăția și nu invocă anii lui de slujire. Cere pe temeiul bunătății lui Dumnezeu, singurul temei care nu se surpă. Când ceri iertare, nu-ți mai aduce meritele: nu ele te acoperă.",
    question: "Ce aduci, de obicei, ca argument când Îi ceri iertare?",
    prayer: "Doamne, nu am ce pune pe masă. Cer după îndurarea Ta. Amin.",
    step: "Citește azi tot Psalmul 51, rar. E scurt.",
  },
  {
    id: "dev_142",
    dayNumber: 142,
    theme: LUNA_5,
    axis: "relationships",
    verseRef: "1 Ioan 1:9",
    verseText: "Dacă ne mărturisim păcatele, El este credincios și drept ca să ne ierte păcatele și să ne curățească de orice nelegiuire.",
    meditation:
      "„Credincios și drept”, nu „milostiv și îngăduitor”. Dumnezeu iartă pentru că e drept: prețul a fost deja plătit la cruce, iar El nu cere plata de două ori. De aceea iertarea Lui nu depinde de starea ta de spirit din ziua aceea.",
    question: "Te simți iertat sau știi că ești iertat?",
    prayer: "Doamne, mă sprijin pe dreptatea Ta, nu pe simțirile mele. Amin.",
    step: "Scrie versetul ăsta undeva și citește-l data viitoare când te învinovățești.",
  },
  {
    id: "dev_143",
    dayNumber: 143,
    theme: LUNA_5,
    axis: "relationships",
    verseRef: "Isaia 43:25",
    verseText: "Eu, Eu îți șterg fărădelegile, pentru Mine, și nu-Mi voi mai aduce aminte de păcatele tale.",
    meditation:
      "„Pentru Mine” — Dumnezeu iartă și pentru că așa este El, nu doar pentru că ție îți trebuie. „Nu-Mi voi mai aduce aminte” nu înseamnă că uită, ci că nu mai scoate niciodată subiectul. Dumnezeu nu-ți mai aduce aminte de ce ți-a iertat; tu de ce o faci?",
    question: "Ce păcat iertat încă îți răscolești în fiecare noapte?",
    prayer: "Doamne, Tu nu-mi mai aduci aminte. Învață-mă să nu-mi mai aduc nici eu. Amin.",
    step: "Când îți revine azi în minte, răspunde: „Dumnezeu nu mai discută asta”.",
  },
  {
    id: "dev_144",
    dayNumber: 144,
    theme: LUNA_5,
    axis: "relationships",
    verseRef: "Luca 15:22",
    verseText: "Dar tatăl a zis robilor săi: ‘Aduceți repede haina cea mai bună și îmbrăcați-l cu ea; puneți-i un inel în deget și încălțăminte în picioare.’",
    meditation:
      "Fiul pregătise un discurs și o funcție mai mică: „fă-mă ca pe unul din argații tăi”. Tatăl nu l-a lăsat să termine. Iertarea deplină nu te retrogradează în familie — haina, inelul și încălțămintea sunt semne de fiu, nu de slugă tolerată.",
    question: "Trăiești ca un fiu iertat sau ca un argat tolerat?",
    prayer: "Doamne, primesc haina. Nu mai cer să fiu argat. Amin.",
    step: "Fă azi un lucru pe care un fiu iubit l-ar face fără teamă: cere ceva, intră în vorbă, odihnește-te.",
  },
  {
    id: "dev_145",
    dayNumber: 145,
    theme: LUNA_5,
    axis: "relationships",
    verseRef: "Ioan 21:17",
    verseText: "A treia oară i-a zis Isus: „Simone, fiul lui Iona, Mă iubești?” Petru s-a întristat că-i zisese a treia oară: „Mă iubești?” Și I-a răspuns: „Doamne, Tu toate le știi, știi că Te iubesc.” Isus i-a zis: „Paște oile Mele!”",
    meditation:
      "Petru se lepădase de trei ori lângă un foc; Isus îl întreabă de trei ori lângă alt foc. N-a ținut prelegeri despre trădare: a refăcut legătura și i-a dat înapoi lucrarea. Iertarea completă nu doar șterge, ci redă un rost.",
    question: "Ce ai încetat să mai faci pentru că te simți descalificat?",
    prayer: "Doamne, mă repui în slujbă. Mulțumesc că nu m-ai pus deoparte. Amin.",
    step: "Reia azi un lucru bun pe care l-ai abandonat după o cădere.",
  },
  {
    id: "dev_146",
    dayNumber: 146,
    theme: LUNA_5,
    axis: "relationships",
    verseRef: "Filimon 1:18",
    verseText: "Și dacă ți-a adus vreo vătămare sau îți este dator cu ceva, pune aceasta în socoteala mea.",
    meditation:
      "Pavel scrie pentru un rob fugar și se oferă să plătească el paguba. Așa arată iertarea când coboară din teorie: cineva absoarbe o pierdere reală. De fiecare dată când ierți, plătești tu ceva ce nu ți se cuvenea.",
    question: "Ce ai de pierdut, concret, dacă ierți?",
    prayer: "Doamne, iau eu pierderea, cum ai luat-o Tu pe a mea. Amin.",
    step: "Renunță azi la o pretenție îndreptățită de la cineva. Scrie ce te costă.",
  },
  {
    id: "dev_147",
    dayNumber: 147,
    theme: LUNA_5,
    axis: "relationships",
    verseRef: "2 Corinteni 2:7-8",
    verseText: "Așa că acum este mai bine să-l iertați și să-l mângâiați, ca să nu fie doborât de prea multă mâhnire. De aceea, vă rog să vă arătați iarăși dragostea față de el.",
    meditation:
      "E vorba de un om disciplinat de biserică, care s-a pocăit — iar Pavel se teme că pedeapsa ținută prea mult îl va îngropa. Există o cruzime a celor drepți: păstrezi distanța mult după ce omul s-a îndreptat. Iertarea trebuie și arătată, nu doar declarată.",
    question: "Pe cine ții la distanță deși ai spus că l-ai iertat?",
    prayer: "Doamne, ajută-mă să nu pedepsesc cu răceala. Amin.",
    step: "Arată azi căldură cuiva pe care l-ai iertat doar pe hârtie.",
  },
  {
    id: "dev_148",
    dayNumber: 148,
    theme: LUNA_5,
    axis: "relationships",
    verseRef: "Matei 5:44",
    verseText: "Dar Eu vă spun: Iubiți pe vrăjmașii voștri, binecuvântați pe cei ce vă blestemă, faceți bine celor ce vă urăsc și rugați-vă pentru cei ce vă asupresc și vă prigonesc.",
    meditation:
      "E greu să urăști mult timp pe cineva pentru care te rogi cu adevărat. Rugăciunea îl scoate din categoria „dușman” și îl pune în categoria „om”. Nu-ți cere să-i aprobi faptele, ci să-i vrei mântuirea.",
    question: "Ce s-ar schimba în tine dacă te-ai ruga pentru el o lună?",
    prayer: "Doamne, binecuvântează-l. Știu ce spun și o spun oricum. Amin.",
    step: "Pune-i numele pe lista ta de rugăciune. Chiar acolo, lângă ai tăi.",
  },
  {
    id: "dev_149",
    dayNumber: 149,
    theme: LUNA_5,
    axis: "relationships",
    verseRef: "Romani 12:21",
    verseText: "Nu te lăsa biruit de rău, ci biruiește răul prin bine.",
    meditation:
      "Sunt două feluri de a pierde într-o rănire: să fii rănit și să devii ca cel care te-a rănit. Al doilea e mai grav. Binele făcut deliberat e singura armă care nu te transformă în dușmanul tău.",
    question: "În ce fel ai început să semeni cu omul care te-a rănit?",
    prayer: "Doamne, păzește-mă să nu devin ce urăsc. Amin.",
    step: "Fă azi un bine concret într-un loc unde ai fost tratat nedrept.",
  },
  {
    id: "dev_150",
    dayNumber: 150,
    theme: LUNA_5,
    axis: "relationships",
    verseRef: "Coloseni 3:14",
    verseText: "Dar mai presus de toate acestea, îmbrăcați-vă cu dragostea, care este legătura desăvârșirii.",
    meditation:
      "Se încheie luna iertării și rămâne un cuvânt: legătură. Iertarea nu e un scop în sine, ci ceea ce ține oamenii împreună după ce s-au rănit. Dacă din luna asta ai făcut un singur pas real, e destul; mana e pentru o zi, nu pentru tot anul. Luna viitoare vorbim despre ai tăi și despre singurătate.",
    question: "Ce s-a dezlegat în tine în treizeci de zile?",
    prayer: "Doamne, mulțumesc pentru ce am putut lăsa jos. Ce n-am putut, țin în fața Ta. Amin.",
    step: "Recitește ce ai scris în ziua 123 și vezi dacă numele acela încă te apasă.",
  },
]
