// Devoțional, luna 12 și ultima: „Har la cădere” (docs/27 §2.4, axa freedom).
//
// Regula lunii: după luna despre rușine, aici se răspunde la întrebarea care
// rămâne — ce se întâmplă când cazi din nou. Nicio zi nu banalizează păcatul și
// niciuna nu-l lasă pe om afară. Ultimele zile încheie anul și trimit înapoi la
// ziua 1, pentru că drumul nu se termină la 365.
//
// Conținut ORIGINAL Emanus (docs/27 §1.2). Versete: Cornilescu (domeniu public).
import type { DevotionalDay } from "./devotional.js"

const LUNA_12 = "Har la cădere"

export const DEVOTIONAL_DAYS_LUNA_12: DevotionalDay[] = [
  {
    id: "dev_331",
    dayNumber: 331,
    theme: LUNA_12,
    axis: "freedom",
    verseRef: "Proverbe 24:16",
    verseText: "Căci cel neprihănit de șapte ori cade și se scoală, dar cei răi se prăbușesc în nenorocire.",
    meditation:
      "Proverbul nu spune că omul drept nu cade, ci că se scoală. Diferența între cei doi oameni din verset nu e numărul căderilor, ci ridicarea. Dacă te-ai judecat pentru că ai căzut iar, ai folosit o măsură care nu e a Bibliei.",
    question: "Câte căderi credeai că ai voie să ai?",
    prayer: "Doamne, mă ridic din nou. A șaptea oară, dacă trebuie. Amin.",
    step: "Ridică-te azi într-un lucru în care ai renunțat să mai încerci.",
  },
  {
    id: "dev_332",
    dayNumber: 332,
    theme: LUNA_12,
    axis: "freedom",
    verseRef: "Psalmul 37:24",
    verseText: "Când cade, nu este doborât de tot, căci Domnul îl apucă de mână.",
    meditation:
      "Textul recunoaște căderea ca pe un fapt, nu ca pe o excepție. Ce se schimbă e că cineva te ține de mână în timp ce cazi. Nu ești susținut pentru că ești stabil, ci pentru că ești ținut.",
    question: "Cine te-a ținut de mână ultima dată când ai căzut?",
    prayer: "Doamne, ține-mă de mână. Nu mă pot ține singur. Amin.",
    step: "Cere azi ajutor concret unei persoane, nu doar în rugăciune.",
  },
  {
    id: "dev_333",
    dayNumber: 333,
    theme: LUNA_12,
    axis: "freedom",
    verseRef: "Mica 7:8",
    verseText: "Nu te bucura de mine, vrăjmașă, căci, chiar dacă am căzut, mă voi scula; chiar dacă stau în întuneric, totuși Domnul este Lumina mea.",
    meditation:
      "E o replică spusă din țărână, nu de pe podium. Profetul nu neagă căderea și nici întunericul; le recunoaște și tot spune „mă voi scula”. Credința nu e să pretinzi că stai în picioare.",
    question: "Ce ai putea spune azi din locul în care ești?",
    prayer: "Doamne, chiar dacă am căzut, mă voi scula. Tu ești lumina mea. Amin.",
    step: "Spune versetul ăsta cu voce tare, exact acolo unde te doare.",
  },
  {
    id: "dev_334",
    dayNumber: 334,
    theme: LUNA_12,
    axis: "freedom",
    verseRef: "Luca 22:31-32",
    verseText: "Simone, Simone, Satana v-a cerut să vă cearnă ca grâul. Dar Eu M-am rugat pentru tine, ca să nu se piardă credința ta; și, după ce te vei întoarce la Dumnezeu, să întărești pe frații tăi.",
    meditation:
      "Isus știa că Petru va cădea și s-a rugat dinainte, nu ca să evite căderea, ci ca să nu se piardă credința. Și îi dă o misiune de după: să-și întărească frații. Căderea nu l-a scos din plan.",
    question: "Crezi că ești încă folosibil după ce ai căzut?",
    prayer: "Doamne, Te-ai rugat pentru mine înainte să cad. Mulțumesc. Amin.",
    step: "Întărește azi pe cineva cu ce ai învățat din căderea ta.",
  },
  {
    id: "dev_335",
    dayNumber: 335,
    theme: LUNA_12,
    axis: "freedom",
    verseRef: "Luca 22:61-62",
    verseText: "Domnul S-a întors și S-a uitat țintă la Petru... Și Petru a ieșit afară și a plâns cu amărăciune.",
    meditation:
      "Privirea aceea putea fi de dispreț, dar Petru n-a fugit definitiv, ci a plâns și s-a întors. Sunt priviri care te distrug și priviri care te trezesc. Durerea de după păcat nu e semn că ești pierdut; adesea e semn că ești ținut.",
    question: "Cum Îți imaginezi privirea Lui când cazi?",
    prayer: "Doamne, ajută-mă să văd în privirea Ta chemare, nu dispreț. Amin.",
    step: "Lasă-ți azi durerea să te ducă spre El, nu departe de El.",
  },
  {
    id: "dev_336",
    dayNumber: 336,
    theme: LUNA_12,
    axis: "freedom",
    verseRef: "Ioan 21:15",
    verseText: "Simone, fiul lui Iona, Mă iubești tu mai mult decât aceștia?",
    meditation:
      "După înviere, Isus nu-i cere lui Petru explicații și nici promisiuni mai mari. Îl întreabă de trei ori dacă Îl iubește — de tot atâtea ori de câte ori se lepădase. Restaurarea nu s-a făcut prin rușinare, ci prin dragoste întrebată pe nume.",
    question: "Ce ai răspunde dacă te-ar întreba azi asta?",
    prayer: "Doamne, Tu știi toate lucrurile. Știi că Te iubesc. Amin.",
    step: "Spune-I azi că-L iubești, chiar dacă nu te simți vrednic.",
  },
  {
    id: "dev_337",
    dayNumber: 337,
    theme: LUNA_12,
    axis: "freedom",
    verseRef: "Ioan 21:17",
    verseText: "Paște oile Mele!",
    meditation:
      "Ultimul cuvânt dat lui Petru nu e o mustrare, ci o însărcinare. Cel care se lepădase e pus să aibă grijă de alții. Dumnezeu încredințează lucruri oamenilor care știu că pot cădea.",
    question: "De cine ai tu grijă acum?",
    prayer: "Doamne, dă-mi ceva de făcut, chiar și după ce am căzut. Amin.",
    step: "Fă azi un lucru de grijă pentru cineva mai slab decât tine.",
  },
  {
    id: "dev_338",
    dayNumber: 338,
    theme: LUNA_12,
    axis: "freedom",
    verseRef: "Marcu 16:7",
    verseText: "Dar duceți-vă de spuneți ucenicilor Lui și lui Petru că merge înaintea voastră în Galileea.",
    meditation:
      "„Și lui Petru” sunt două cuvinte pe care le-a pus îngerul special pentru un om care se credea scos din grup. Cel căzut are nevoie să fie numit separat, ca să știe că mesajul e și pentru el. Dumnezeu știe să adauge un nume.",
    question: "Ai crezut că veștile bune sunt pentru alții, nu pentru tine?",
    prayer: "Doamne, mulțumesc că spui și numele meu. Amin.",
    step: "Scrie-ți numele după „și lui” în versetul de azi și citește-l așa.",
  },
  {
    id: "dev_339",
    dayNumber: 339,
    theme: LUNA_12,
    axis: "freedom",
    verseRef: "Psalmul 130:3-4",
    verseText: "Dacă ai păstra, Doamne, aducerea aminte a nelegiuirilor, cine ar putea sta în picioare, Doamne? Dar la Tine este iertare, ca să fii temut.",
    meditation:
      "Psalmistul începe cu o întrebare la care răspunsul e „nimeni”. Apoi spune ceva surprinzător: iertarea Lui nu produce ușurătate, ci teamă sfântă. Cine e iertat mult nu devine neserios, ci respectuos.",
    question: "Iertarea Lui te-a făcut mai ușuratic sau mai serios?",
    prayer: "Doamne, la Tine este iertare. Și de aceea Te cinstesc. Amin.",
    step: "Mulțumește-I azi pentru un păcat concret pe care ți l-a iertat.",
  },
  {
    id: "dev_340",
    dayNumber: 340,
    theme: LUNA_12,
    axis: "freedom",
    verseRef: "Isaia 42:3",
    verseText: "Trestia frântă n-o va zdrobi și mucul care mai arde încă nu-l va stinge.",
    meditation:
      "O trestie frântă nu mai e bună de nimic, iar un fitil care fumegă doar deranjează — orice om normal le-ar arunca. Despre Robul Domnului se spune anume că nu face asta. Dacă din credința ta a mai rămas doar fum, El nu suflă în ea ca s-o stingă.",
    question: "Cât a mai rămas din flacăra ta?",
    prayer: "Doamne, sunt o trestie frântă. Nu mă zdrobi. Amin.",
    step: "Nu te mai judeca azi pentru că arzi mic. Doar rămâi aprins.",
  },
  {
    id: "dev_341",
    dayNumber: 341,
    theme: LUNA_12,
    axis: "freedom",
    verseRef: "Ioan 8:36",
    verseText: "Deci dacă Fiul vă face slobozi, veți fi cu adevărat slobozi.",
    meditation:
      "Isus vorbea unor oameni care susțineau că n-au fost niciodată robi nimănui. Robia cea mai greu de recunoscut e cea din obișnuință. Libertatea nu se obține prin voință mai mare, ci se primește de la Fiul.",
    question: "Ce numeai „obicei” și e de fapt robie?",
    prayer: "Doamne, fă-mă slobod cu adevărat. Amin.",
    step: "Numește în scris lucrul care te stăpânește și cere eliberare pentru el.",
  },
  {
    id: "dev_342",
    dayNumber: 342,
    theme: LUNA_12,
    axis: "freedom",
    verseRef: "Romani 7:19",
    verseText: "Căci binele pe care vreau să-l fac, nu-l fac, ci răul pe care nu vreau să-l fac, iată ce fac!",
    meditation:
      "Cel care scrie asta e Pavel, nu un începător. În Biblie există loc pentru descrierea sinceră a eșecului repetat. Faptul că lupta ta seamănă cu a lui nu înseamnă că nu ești creștin, ci că ești în luptă.",
    question: "Ce bine vrei să faci și tot nu-l faci?",
    prayer: "Doamne, cunosc lupta asta. Nu mă lăsa singur în ea. Amin.",
    step: "Citește azi Romani 7 în întregime, fără să te condamni.",
  },
  {
    id: "dev_343",
    dayNumber: 343,
    theme: LUNA_12,
    axis: "freedom",
    verseRef: "Romani 7:24-25",
    verseText: "O, nenorocitul de mine! Cine mă va izbăvi de acest trup de moarte? Mulțumiri fie aduse lui Dumnezeu, prin Isus Hristos, Domnul nostru!",
    meditation:
      "Întrebarea nu e „ce să fac”, ci „cine mă va izbăvi” — iar răspunsul e o Persoană, nu o metodă. Între strigăt și mulțumire nu e nicio pauză. Așa arată harul: îți taie disperarea la mijloc.",
    question: "Cauți o metodă sau un Izbăvitor?",
    prayer: "Mulțumiri fie aduse lui Dumnezeu, prin Isus Hristos. Amin.",
    step: "Renunță azi la o strategie de autoreparare și cere-I Lui izbăvire.",
  },
  {
    id: "dev_344",
    dayNumber: 344,
    theme: LUNA_12,
    axis: "freedom",
    verseRef: "Romani 6:14",
    verseText: "Căci păcatul nu va mai stăpâni asupra voastră, pentru că nu sunteți sub Lege, ci sub har.",
    meditation:
      "Motivul dat de Pavel e neobișnuit: păcatul își pierde stăpânirea nu prin reguli mai stricte, ci prin har. Regulile pot ține un om în frâu; doar harul îi schimbă stăpânul. Cine se luptă doar cu voința obosește și cade.",
    question: "Te lupți cu păcatul prin reguli sau prin har?",
    prayer: "Doamne, nu mai sunt sub Lege. Sunt al Tău. Amin.",
    step: "Schimbă azi o regulă pe care ți-ai impus-o cu o rugăciune.",
  },
  {
    id: "dev_345",
    dayNumber: 345,
    theme: LUNA_12,
    axis: "freedom",
    verseRef: "Tit 2:11-12",
    verseText: "Căci harul lui Dumnezeu, care aduce mântuire pentru toți oamenii, a fost arătat și ne învață s-o rupem cu păgânătatea și cu poftele lumești și să trăim în veacul de acum cu cumpătare, dreptate și evlavie.",
    meditation:
      "Harul e numit aici învățător, nu doar iertare. Nu te lasă unde te-a găsit și nici nu te bate ca să te miște. Cine spune că harul încurajează păcatul n-a stat suficient sub el.",
    question: "Ce te-a învățat harul în anul ăsta?",
    prayer: "Doamne, învață-mă prin harul Tău, nu prin frică. Amin.",
    step: "Rupe azi cu un lucru mic despre care știi că nu-ți face bine.",
  },
  {
    id: "dev_346",
    dayNumber: 346,
    theme: LUNA_12,
    axis: "freedom",
    verseRef: "Romani 6:1-2",
    verseText: "Ce vom zice dar? Să păcătuim mereu, ca să se înmulțească harul? Nicidecum! Noi, care am murit față de păcat, cum să mai trăim în păcat?",
    meditation:
      "Pavel pune singur întrebarea pe care știa că o va stârni predica lui despre har. Răspunsul nu e o amenințare, ci o mirare: nu se potrivește cu cine ai devenit. Harul nu e permisiune, e înviere.",
    question: "Folosești harul ca scuză undeva?",
    prayer: "Doamne, nu vreau să mă joc cu harul Tău. Amin.",
    step: "Recunoaște azi în fața lui Dumnezeu un loc în care ai abuzat de răbdarea Lui.",
  },
  {
    id: "dev_347",
    dayNumber: 347,
    theme: LUNA_12,
    axis: "freedom",
    verseRef: "1 Timotei 1:15",
    verseText: "O, adevărat și cu totul vrednic de primit este cuvântul care zice: „Hristos Isus a venit în lume ca să mântuiască pe cei păcătoși”, dintre care cel dintâi sunt eu.",
    meditation:
      "Pavel scrie „sunt”, la prezent, după ani de slujire. Nu se lăuda cu trecutul și nu se prefăcea că a ajuns altcineva. Cine ține minte că e păcătos mântuit are mereu loc pentru alții.",
    question: "Ai uitat de unde te-a scos?",
    prayer: "Doamne, sunt un păcătos mântuit de Tine. Nu vreau să uit. Amin.",
    step: "Povestește-I azi lui Dumnezeu, pe scurt, de unde te-a scos.",
  },
  {
    id: "dev_348",
    dayNumber: 348,
    theme: LUNA_12,
    axis: "freedom",
    verseRef: "Filipeni 3:13-14",
    verseText: "Fraților, eu nu cred că l-am apucat încă; dar fac un singur lucru: uitând ce este în urma mea și aruncându-mă spre ce este înainte, alerg spre țintă.",
    meditation:
      "„Uitând” nu înseamnă amnezie, ci refuzul de a mai trăi cu fața întoarsă înapoi. Pavel avea și realizări, și vinovății grele în trecut — le lasă pe amândouă. Alergarea cere privirea înainte.",
    question: "Ce trecut duci cu tine în fiecare zi?",
    prayer: "Doamne, las în urmă ce e în urmă. Alerg mai departe. Amin.",
    step: "Scrie un lucru din trecut și, sub el, un pas de mâine.",
  },
  {
    id: "dev_349",
    dayNumber: 349,
    theme: LUNA_12,
    axis: "freedom",
    verseRef: "Iona 3:1",
    verseText: "Cuvântul Domnului a vorbit a doua oară lui Iona astfel...",
    meditation:
      "Iona fugise în direcția opusă chemării și ajunsese pe fundul mării. Textul spune sec: a doua oară. Dumnezeu are obiceiul să repete chemarea după ce omul a stricat prima ocazie.",
    question: "Ce chemare crezi că ai ratat definitiv?",
    prayer: "Doamne, vorbește-mi și a doua oară. Ascult. Amin.",
    step: "Reia azi un lucru bun pe care l-ai abandonat din vină.",
  },
  {
    id: "dev_350",
    dayNumber: 350,
    theme: LUNA_12,
    axis: "freedom",
    verseRef: "Marcu 9:24",
    verseText: "Cred, Doamne! Ajută necredinței mele!",
    meditation:
      "E rugăciunea unui tată disperat, cu un copil bolnav și cu o credință șubredă. Nu-și ascunde îndoiala și nici nu renunță la cerere. Isus n-a așteptat să aibă o credință mai bună ca să lucreze.",
    question: "Unde ți-e credința amestecată cu îndoială?",
    prayer: "Cred, Doamne! Ajută necredinței mele! Amin.",
    step: "Cere-I azi ceva în care nu ești sigur că mai crezi.",
  },
  {
    id: "dev_351",
    dayNumber: 351,
    theme: LUNA_12,
    axis: "freedom",
    verseRef: "Psalmul 145:14",
    verseText: "Domnul sprijină pe toți cei ce cad și îndreaptă pe cei încovoiați.",
    meditation:
      "Psalmul înalță măreția lui Dumnezeu și, în mijlocul ei, spune că se ocupă de cei căzuți. Măreția Lui nu se vede numai în crearea lumii, ci și în aplecarea spre cineva încovoiat. Cele două Îl arată pe același Dumnezeu.",
    question: "Sub ce greutate mergi încovoiat?",
    prayer: "Doamne, îndreaptă-mă. Nu mă mai pot ridica singur. Amin.",
    step: "Spune cuiva de încredere care e greutatea pe care o duci.",
  },
  {
    id: "dev_352",
    dayNumber: 352,
    theme: LUNA_12,
    axis: "freedom",
    verseRef: "Isaia 40:31",
    verseText: "Dar cei ce se încred în Domnul își înnoiesc puterea; ei zboară ca vulturii; aleargă și nu obosesc; umblă și nu ostenesc.",
    meditation:
      "Ordinea din verset coboară, nu urcă: zbor, alergare, umblet. Ultima e cea mai grea și cea mai des întâlnită — să mergi când nu simți nimic. Promisiunea acoperă și zilele în care nu zbori.",
    question: "În ce etapă ești azi: zbor, alergare sau umblet?",
    prayer: "Doamne, înnoiește-mi puterea pentru mersul obișnuit. Amin.",
    step: "Fă azi lucrul obișnuit, chiar dacă nu simți nimic.",
  },
  {
    id: "dev_353",
    dayNumber: 353,
    theme: LUNA_12,
    axis: "freedom",
    verseRef: "Galateni 6:1",
    verseText: "Fraților, chiar dacă un om ar cădea deodată în vreo greșeală, voi, care sunteți duhovnicești, să-l ridicați cu duhul blândeții. Și ia seama la tine însuți, ca să nu fii ispitit și tu.",
    meditation:
      "Semnul că ești duhovnicesc nu e că vezi căderea altuia, ci că știi să ridici blând. Iar avertismentul din final e pentru cel care ridică, nu pentru cel căzut. Cine judecă aspru e următorul la rând.",
    question: "Cum reacționezi când cade cineva?",
    prayer: "Doamne, fă-mă om care ridică, nu care comentează. Amin.",
    step: "Scrie-i azi cuiva care a căzut și de care s-au depărtat alții.",
  },
  {
    id: "dev_354",
    dayNumber: 354,
    theme: LUNA_12,
    axis: "freedom",
    verseRef: "Iacov 5:19-20",
    verseText: "Fraților, dacă s-a rătăcit vreunul dintre voi de la adevăr și-l întoarce un altul, să știți că cine întoarce pe un păcătos de la rătăcirea căii lui va mântui un suflet de la moarte.",
    meditation:
      "Epistola se încheie nu cu o învățătură înaltă, ci cu o sarcină practică: du-te după cel rătăcit. E o lucrare pe care o poate face oricine, nu doar pastorul. Multe întoarceri au început cu un mesaj trimis la timp.",
    question: "Cine s-a depărtat și nu l-a căutat nimeni?",
    prayer: "Doamne, arată-mi pe cine să caut. Amin.",
    step: "Caută azi un om care a plecat din biserică și întreabă-l ce mai face.",
  },
  {
    id: "dev_355",
    dayNumber: 355,
    theme: LUNA_12,
    axis: "freedom",
    verseRef: "Evrei 4:15",
    verseText: "Căci n-avem un Mare Preot care să n-aibă milă de slăbiciunile noastre, ci Unul care în toate lucrurile a fost ispitit ca și noi, dar fără păcat.",
    meditation:
      "Cel căruia Îi ceri ajutor știe dinăuntru ce e ispita. N-a citit despre ea, a trecut prin ea. De aceea rugăciunea ta în clipa slabă nu cade în gol și nu ajunge la cineva scandalizat.",
    question: "Ce ispită ți se pare prea rușinoasă ca să I-o spui?",
    prayer: "Doamne, Tu înțelegi. Vin la Tine cu ce mă doboră. Amin.",
    step: "Spune-I azi, pe nume, ispita ta cea mai frecventă.",
  },
  {
    id: "dev_356",
    dayNumber: 356,
    theme: LUNA_12,
    axis: "freedom",
    verseRef: "Luca 15:4",
    verseText: "Care om dintre voi, dacă are o sută de oi și pierde pe una din ele, nu lasă pe celelalte nouăzeci și nouă pe islaz și se duce după cea pierdută până când o găsește?",
    meditation:
      "Oaia pierdută nu se întoarce singură; e căutată. „Până când o găsește” e partea cea mai importantă a propoziției. Căutarea Lui nu are termen de expirare.",
    question: "Crezi că a obosit să te caute?",
    prayer: "Doamne, mulțumesc că mă cauți până mă găsești. Amin.",
    step: "Lasă-te azi găsit: întoarce-te la o obișnuință bună pe care ai pierdut-o.",
  },
  {
    id: "dev_357",
    dayNumber: 357,
    theme: LUNA_12,
    axis: "freedom",
    verseRef: "Ieremia 31:3",
    verseText: "Te iubesc cu o iubire veșnică; de aceea îți păstrez bunătatea Mea!",
    meditation:
      "Cuvântul „veșnică” înseamnă că iubirea asta n-a început când te-ai purtat frumos și nu se termină când cazi. E spusă unui popor aflat în exil, deci în plină consecință a păcatului. Dumnezeu iubește și în timpul pedepsei.",
    question: "Crezi că iubirea Lui depinde de ziua ta?",
    prayer: "Doamne, mă iubești cu o iubire veșnică. Mă odihnesc în asta. Amin.",
    step: "Repetă azi versetul ăsta de trei ori, la ore diferite.",
  },
  {
    id: "dev_358",
    dayNumber: 358,
    theme: LUNA_12,
    axis: "freedom",
    verseRef: "Osea 14:4",
    verseText: "Le voi vindeca vătămarea adusă de neascultarea lor, îi voi iubi cu adevărat!",
    meditation:
      "Dumnezeu nu spune doar că iartă, ci că vindecă rănile făcute chiar de neascultare. Sunt urmări pe care iertarea nu le șterge automat și care au nevoie de vindecare în timp. Har înseamnă și îngrijirea cicatricilor.",
    question: "Ce rană ți-ai făcut singur și are nevoie de vindecare?",
    prayer: "Doamne, vindecă ce mi-am stricat singur. Amin.",
    step: "Fă azi un pas de reparație: o scuză, o datorie, un tratament început.",
  },
  {
    id: "dev_359",
    dayNumber: 359,
    theme: LUNA_12,
    axis: "freedom",
    verseRef: "Osea 6:1",
    verseText: "Veniți să ne întoarcem la Domnul! Căci El ne-a sfâșiat, dar tot El ne va vindeca; El ne-a lovit, dar tot El ne va lega rănile.",
    meditation:
      "Chemarea e la plural: „să ne întoarcem”. Întoarcerea nu e o performanță individuală, ci ceva ce faci împreună cu alții. Și te întorci la Același care a îngăduit durerea, pentru că tot El leagă rănile.",
    question: "Cu cine te-ai putea întoarce împreună?",
    prayer: "Doamne, ne întoarcem la Tine. Leagă-ne rănile. Amin.",
    step: "Cheamă azi pe cineva să se roage cu tine, chiar și la telefon.",
  },
  {
    id: "dev_360",
    dayNumber: 360,
    theme: LUNA_12,
    axis: "freedom",
    verseRef: "Ioel 2:25",
    verseText: "Vă voi răsplăti astfel anii pe care i-au mâncat lăcustele.",
    meditation:
      "Nu scrie că anii nu s-au pierdut, ci că vor fi răsplătiți. Dumnezeu nu se preface că paguba n-a existat; dă înapoi. Cine a pierdut zece ani într-o robie are aici o promisiune, nu o consolare.",
    question: "Ce ani aștepți să-ți fie răsplătiți?",
    prayer: "Doamne, Îți încredințez anii mâncați. Amin.",
    step: "Scrie o listă scurtă cu ce ai pierdut și pune-o înaintea Lui.",
  },
  {
    id: "dev_361",
    dayNumber: 361,
    theme: LUNA_12,
    axis: "freedom",
    verseRef: "Psalmul 40:2",
    verseText: "M-a scos din groapa pieirii, din fundul mocirlei; mi-a pus picioarele pe stâncă și mi-a întărit pașii.",
    meditation:
      "Sunt patru mișcări: scos, ridicat, așezat pe stâncă, întărit în pași. Ultima e cea la care se ajunge cel mai greu și cel mai târziu. Nu te descuraja dacă ai fost scos, dar încă mergi nesigur.",
    question: "La care dintre cele patru ești acum?",
    prayer: "Doamne, întărește-mi pașii, nu doar scoate-mă. Amin.",
    step: "Alege un pas mic pe care să-l repeți zilnic în luna care vine.",
  },
  {
    id: "dev_362",
    dayNumber: 362,
    theme: LUNA_12,
    axis: "freedom",
    verseRef: "1 Tesaloniceni 5:24",
    verseText: "Cel ce v-a chemat este credincios și va face lucrul acesta.",
    meditation:
      "Toată greutatea propoziției stă pe El, nu pe tine. Nu spune că tu vei reuși, ci că El va face lucrul acesta. În anul care vine, asta e ancora zilelor în care nu te ții de nimic.",
    question: "Ce lucru din tine crezi că nu se va schimba niciodată?",
    prayer: "Doamne, Tu ești credincios și vei face Tu lucrul acesta. Amin.",
    step: "Scrie versetul ăsta și pune-l unde îl vezi dimineața.",
  },
  {
    id: "dev_363",
    dayNumber: 363,
    theme: LUNA_12,
    axis: "freedom",
    verseRef: "2 Timotei 2:13",
    verseText: "Dacă suntem necredincioși, totuși El rămâne credincios, căci nu Se poate tăgădui singur.",
    meditation:
      "Motivul credincioșiei Lui nu ești tu, ci El Însuși: nu se poate tăgădui. Asta înseamnă că statornicia Lui nu depinde de statornicia ta. E cel mai solid lucru pe care îl poți duce cu tine în anul următor.",
    question: "Pe ce s-a sprijinit relația ta cu Dumnezeu anul ăsta?",
    prayer: "Doamne, rămâi credincios chiar și când eu nu sunt. Amin.",
    step: "Mulțumește-I azi pentru o zi în care ai lipsit tu, nu El.",
  },
  {
    id: "dev_364",
    dayNumber: 364,
    theme: LUNA_12,
    axis: "freedom",
    verseRef: "Apocalipsa 21:5",
    verseText: "Iată că Eu fac toate lucrurile noi.",
    meditation:
      "Nu scrie „Eu fac toate lucrurile altele”, ci noi — aceleași lucruri, reînnoite. Și verbul e la prezent: se întâmplă deja. Ce a fost stricat în viața ta intră în această lucrare, nu la coșul de gunoi.",
    question: "Ce ai vrea să fie făcut nou în tine?",
    prayer: "Doamne, fă nou ce e vechi în mine. Amin.",
    step: "Numește în rugăciune un lucru pe care Îl rogi să-l facă nou anul viitor.",
  },
  {
    id: "dev_365",
    dayNumber: 365,
    theme: LUNA_12,
    axis: "freedom",
    verseRef: "Numeri 6:24-26",
    verseText: "Domnul să te binecuvânteze și să te păzească! Domnul să facă să lumineze Fața Lui peste tine și să Se îndure de tine! Domnul să-Și înalțe Fața peste tine și să-ți dea pacea!",
    meditation:
      "E binecuvântarea cu care preoții trimiteau poporul acasă, și cu ea se încheie și anul ăsta. Ai început în ziua 1 ca orfan și ai mers până aici ca fiu. Mâine poți lua de la capăt drumul — nu pentru că n-ai învățat nimic, ci pentru că aceleași cuvinte ți se vor deschide altfel.",
    question: "Ce s-a schimbat în tine între ziua 1 și ziua 365?",
    prayer: "Doamne, mulțumesc pentru anul ăsta. Mergi cu mine mai departe. Amin.",
    step: "Recitește ziua 1 și scrie, sub ea, cine ești azi.",
  },
]
