// Devoțional, luna 11: „Rușinea” (docs/27 §2.4, axa freedom).
//
// Regula lunii: se face diferența, zi de zi, între vinovăție („am făcut ceva
// rău”) și rușine („sunt ceva rău”). Prima se rezolvă prin iertare, a doua prin
// a fi văzut și totuși primit. Nicio zi nu îi cere omului să-și „ierte singur”
// trecutul și niciuna nu-l grăbește să-și spună povestea cuiva nesigur.
//
// Conținut ORIGINAL Emanus (docs/27 §1.2). Versete: Cornilescu (domeniu public).
import type { DevotionalDay } from "./devotional.js"

const LUNA_11 = "Rușinea"

export const DEVOTIONAL_DAYS_LUNA_11: DevotionalDay[] = [
  {
    id: "dev_301",
    dayNumber: 301,
    theme: LUNA_11,
    axis: "freedom",
    verseRef: "Geneza 2:25",
    verseText: "Omul și nevasta lui erau amândoi goi și nu le era rușine.",
    meditation:
      "Așa a început totul: văzuți în întregime și fără nicio teamă. Rușinea nu face parte din felul în care a fost gândit omul; a intrat mai târziu. Dorul tău de a fi cunoscut fără să fii respins nu e naivitate, ci memorie.",
    question: "Când te-ai simțit ultima dată văzut și în siguranță în același timp?",
    prayer: "Doamne, Îi duc dorul unui loc în care să nu mă ascund. Amin.",
    step: "Scrie ce anume te-ar face să te simți în siguranță dacă ai fi cunoscut pe deplin.",
  },
  {
    id: "dev_302",
    dayNumber: 302,
    theme: LUNA_11,
    axis: "freedom",
    verseRef: "Geneza 3:7",
    verseText: "Atunci li s-au deschis ochii la amândoi; au cunoscut că erau goi, au cusut laolaltă frunze de smochin și și-au făcut șorțuri din ele.",
    meditation:
      "Primul lucru pe care l-a inventat omul căzut a fost acoperirea. Frunzele de smochin se usucă în câteva zile — e o soluție care cere întreținere permanentă. Așa e și imaginea pe care o ții tu în viață: obosește și trebuie mereu reparată.",
    question: "Din ce sunt făcute frunzele tale de smochin?",
    prayer: "Doamne, m-am săturat să-mi repar imaginea. Amin.",
    step: "Numește un lucru pe care îl faci mai ales ca să nu se vadă cine ești.",
  },
  {
    id: "dev_303",
    dayNumber: 303,
    theme: LUNA_11,
    axis: "freedom",
    verseRef: "Geneza 3:9",
    verseText: "Dar Domnul Dumnezeu a chemat pe om și i-a zis: „Unde ești?”",
    meditation:
      "Dumnezeu știa unde e Adam; întrebarea era pentru Adam. Prima mișcare după cădere n-a fost pedeapsa, ci căutarea. Rușinea te împinge în tufișuri, iar El vine și te strigă pe nume.",
    question: "Unde te-ai ascuns în ultima vreme?",
    prayer: "Doamne, ies din tufiș. Sunt aici. Amin.",
    step: "Spune-I azi în rugăciune exact unde te-ai ascuns și de ce.",
  },
  {
    id: "dev_304",
    dayNumber: 304,
    theme: LUNA_11,
    axis: "freedom",
    verseRef: "Geneza 3:21",
    verseText: "Domnul Dumnezeu a făcut lui Adam și nevestei lui haine de piele și i-a îmbrăcat cu ele.",
    meditation:
      "Dumnezeu n-a lăsat frunzele; a făcut o acoperire care a costat viața unui animal. E prima moarte din Biblie și primul semn că acoperirea vine de la El, cu preț. Tu nu trebuie să-ți coași singur haina.",
    question: "Ce încerci să acoperi cu puterile tale?",
    prayer: "Doamne, îmbracă-mă Tu. Nu-mi ajung frunzele. Amin.",
    step: "Renunță azi la o justificare pe care o repeți despre trecutul tău.",
  },
  {
    id: "dev_305",
    dayNumber: 305,
    theme: LUNA_11,
    axis: "freedom",
    verseRef: "Psalmul 25:3",
    verseText: "Da, toți cei ce nădăjduiesc în Tine nu vor fi dați de rușine.",
    meditation:
      "E o promisiune ciudat de concretă pentru un om care trăiește cu fața în pământ. Nu spune că nu vei greși, ci că nu vei rămâne acolo. Nădejdea pusă în El nu se întoarce împotriva ta.",
    question: "Ce te face să-ți ții privirea în pământ?",
    prayer: "Doamne, în Tine nădăjduiesc. Ridică-mi capul. Amin.",
    step: "Când vorbești azi cu cineva, privește-l în ochi.",
  },
  {
    id: "dev_306",
    dayNumber: 306,
    theme: LUNA_11,
    axis: "freedom",
    verseRef: "Isaia 54:4",
    verseText: "Nu te teme, căci nu vei rămâne de rușine; nu roși, căci nu vei fi acoperită de rușine; vei uita și rușinea tinereților.",
    meditation:
      "Dumnezeu vorbește aici unui popor cu un trecut umilitor și îi promite că rușinea tinereții nu va fi ultimul cuvânt. Nu spune că nu s-a întâmplat, ci că nu te va mai defini. Vindecarea nu șterge istoria; îi ia puterea.",
    question: "Ce rușine din tinerețe te definește încă?",
    prayer: "Doamne, ia puterea rușinii din anii aceia. Amin.",
    step: "Scrie anul în care s-a întâmplat și, lângă el, versetul de azi.",
  },
  {
    id: "dev_307",
    dayNumber: 307,
    theme: LUNA_11,
    axis: "freedom",
    verseRef: "Isaia 61:7",
    verseText: "În locul rușinii voastre veți avea îndoită parte; în locul ocarei, se vor bucura de partea lor.",
    meditation:
      "În legea veche, cel nedreptățit primea îndoit — deci Dumnezeu vorbește ca despre o despăgubire. Nu doar șterge rușinea, ci pune ceva în locul ei. Locurile cele mai umilite din viața unui om devin adesea locurile din care ajută pe alții.",
    question: "Ce ai putea da altcuiva tocmai din locul tău rușinos?",
    prayer: "Doamne, pune ceva bun în locul rușinii mele. Amin.",
    step: "Gândește-te la cineva care trece prin ce ai trecut tu și roagă-te pentru el.",
  },
  {
    id: "dev_308",
    dayNumber: 308,
    theme: LUNA_11,
    axis: "freedom",
    verseRef: "Ioel 2:26",
    verseText: "Veți mânca și vă veți sătura și veți lăuda Numele Domnului Dumnezeului vostru... și poporul Meu niciodată nu va mai fi de ocară!",
    meditation:
      "Contextul e o țară mâncată de lăcuste, adică ani pierduți. Dumnezeu promite sătul și sfârșitul ocarei în același loc. Cine a pierdut ani întregi are aici o promisiune anume pentru el.",
    question: "Ce ani ți s-au mâncat și îi plângi încă?",
    prayer: "Doamne, răsplătește-mi anii pierduți. Amin.",
    step: "Numește în rugăciune anii aceia și cere-I să-i folosească.",
  },
  {
    id: "dev_309",
    dayNumber: 309,
    theme: LUNA_11,
    axis: "freedom",
    verseRef: "Romani 10:11",
    verseText: "Fiindcă Scriptura zice: „Oricine crede în El nu va fi dat de rușine.”",
    meditation:
      "Pavel repetă un verset din Isaia și adaugă un cuvânt care schimbă totul: oricine. Nu „cine merită”, nu „cine are un trecut curat”. Rușinea încearcă mereu să te scoată din categoria „oricine”.",
    question: "Te-ai simțit vreodată excepția de la promisiunile lui Dumnezeu?",
    prayer: "Doamne, și eu sunt în „oricine”. Cred în Tine. Amin.",
    step: "Citește versetul cu numele tău în locul lui „oricine”.",
  },
  {
    id: "dev_310",
    dayNumber: 310,
    theme: LUNA_11,
    axis: "freedom",
    verseRef: "1 Petru 2:6",
    verseText: "Iată că pun în Sion o piatră din capul unghiului, aleasă, scumpă; și cine se încrede în El nu va fi dat de rușine.",
    meditation:
      "Siguranța nu stă în cât de tare crezi, ci în cât de tare e piatra pe care stai. O credință mică pe o temelie bună rezistă mai mult decât o convingere mare pe nisip. Rușinea cade când îți muți greutatea de pe tine pe El.",
    question: "Pe ce ți-ai pus greutatea vieții?",
    prayer: "Doamne, mă sprijin pe Tine, nu pe reputația mea. Amin.",
    step: "Renunță azi la o încercare de a-ți apăra imaginea în fața cuiva.",
  },
  {
    id: "dev_311",
    dayNumber: 311,
    theme: LUNA_11,
    axis: "freedom",
    verseRef: "Evrei 12:2",
    verseText: "El, pentru bucuria care-I era pusă înainte, a suferit crucea, a disprețuit rușinea și șade la dreapta scaunului de domnie al lui Dumnezeu.",
    meditation:
      "Crucea era, înainte de toate, o rușine publică: dezbrăcat, atârnat la marginea drumului, batjocorit. Isus a trecut prin exact ce te îngrozește pe tine — să fii văzut în cel mai rău moment. Și a făcut-o în locul tău.",
    question: "Ce schimbă faptul că El a fost expus în locul tău?",
    prayer: "Doamne Isuse, ai purtat rușinea mea. Mulțumesc. Amin.",
    step: "Citește azi despre răstignire și observă cât din ea e umilință publică.",
  },
  {
    id: "dev_312",
    dayNumber: 312,
    theme: LUNA_11,
    axis: "freedom",
    verseRef: "Evrei 2:11",
    verseText: "Căci Cel ce sfințește și cei ce sunt sfințiți sunt dintr-unul. De aceea, Lui nu-I este rușine să-i numească „frați”.",
    meditation:
      "Versetul spune limpede ce ai crede imposibil: Lui nu-I e rușine cu tine. Nu Îl jenești și nu are nevoie să explice nimănui de ce te ține aproape. În fața cerului, te numește frate.",
    question: "Crezi că lui Dumnezeu Îi e rușine cu tine?",
    prayer: "Doamne, mulțumesc că nu ți-e rușine să mă numești al Tău. Amin.",
    step: "Spune azi cu voce tare: „Lui nu-I este rușine cu mine”.",
  },
  {
    id: "dev_313",
    dayNumber: 313,
    theme: LUNA_11,
    axis: "freedom",
    verseRef: "Marcu 8:38",
    verseText: "Pentru că de oricine Îi va fi rușine de Mine și de cuvintele Mele în acest neam preacurvar și păcătos, Îi va fi rușine și Fiului omului.",
    meditation:
      "Rușinea are două sensuri în luna asta: cea care te apasă și cea pe care o alegi. E ușor să taci despre El într-un birou sau într-un grup. Tăcerea aceea e o formă discretă de lepădare.",
    question: "Unde ți-e rușine să fii cunoscut ca creștin?",
    prayer: "Doamne, dă-mi curajul să nu mă rușinez de Tine. Amin.",
    step: "Spune azi, într-un context obișnuit, un lucru adevărat despre credința ta.",
  },
  {
    id: "dev_314",
    dayNumber: 314,
    theme: LUNA_11,
    axis: "freedom",
    verseRef: "2 Timotei 1:8",
    verseText: "Să nu-ți fie rușine dar de mărturisirea Domnului nostru, nici de mine, întemnițatul Lui.",
    meditation:
      "Pavel îi cere lui Timotei să nu se rușineze nici de Domnul, nici de un om ajuns la închisoare. Sunt oameni de care ne e rușine să fim asociați: cei căzuți, cei săraci, cei cu dosar. Cine îi părăsește pe ei începe să-L părăsească pe El.",
    question: "De cine ți-e rușine să fii văzut alături?",
    prayer: "Doamne, iartă-mi rușinea față de oamenii Tăi. Amin.",
    step: "Caută azi, în public, pe cineva de care alții se feresc.",
  },
  {
    id: "dev_315",
    dayNumber: 315,
    theme: LUNA_11,
    axis: "freedom",
    verseRef: "2 Timotei 1:12",
    verseText: "Și din pricina aceasta sufer aceste lucruri; dar nu mi-e rușine, căci știu în cine am crezut.",
    meditation:
      "Pavel scria din închisoare, cu o viață care, după orice standard, arăta a eșec. Nu spune „știu ce cred”, ci „știu în cine am crezut”. Rușinea se stinge în fața unei Persoane, nu în fața unui argument.",
    question: "În cine ai crezut, dincolo de ce crezi?",
    prayer: "Doamne, știu în cine am crezut. Asta îmi ajunge. Amin.",
    step: "Scrie o propoziție despre cine e Dumnezeu pentru tine, nu despre doctrină.",
  },
  {
    id: "dev_316",
    dayNumber: 316,
    theme: LUNA_11,
    axis: "freedom",
    verseRef: "Ioan 8:10-11",
    verseText: "Femeie, unde sunt pârâșii tăi? Nimeni nu te-a osândit? Nici Eu nu te osândesc. Du-te și să nu mai păcătuiești.",
    meditation:
      "Femeia fusese adusă în mijlocul curții Templului, expusă dinadins. Isus a scris în țărână și le-a lăsat timp să plece. A făcut două lucruri odată: n-a osândit-o și n-a numit păcatul „nimic”.",
    question: "Ai fost expus vreodată în fața altora?",
    prayer: "Doamne, Tu nu mă osândești. Și nici nu mă lași unde sunt. Amin.",
    step: "Renunță azi să expui greșeala cuiva în fața altora.",
  },
  {
    id: "dev_317",
    dayNumber: 317,
    theme: LUNA_11,
    axis: "freedom",
    verseRef: "Luca 8:47",
    verseText: "Femeia, când s-a văzut dată de gol, a venit tremurând, s-a aruncat jos înaintea Lui și a spus în fața întregului norod din ce pricină se atinsese de El.",
    meditation:
      "Boala ei o făcea necurată — doisprezece ani în care nu avea voie să atingă pe nimeni. Isus a cerut să iasă la vedere nu ca să o umilească, ci ca să fie reintegrată public în popor. Vindecarea ascunsă ar fi lăsat-o tot singură.",
    question: "Ce vindecare a ta ar trebui să fie știută de cineva?",
    prayer: "Doamne, dă-mi curaj să ies din ascuns. Amin.",
    step: "Spune azi unui om de încredere un lucru pe care Dumnezeu l-a vindecat în tine.",
  },
  {
    id: "dev_318",
    dayNumber: 318,
    theme: LUNA_11,
    axis: "freedom",
    verseRef: "Luca 19:5",
    verseText: "Zacheu, dă-te jos degrabă, căci astăzi trebuie să rămân în casa ta.",
    meditation:
      "Zacheu era disprețuit de tot orașul și se urcase într-un copac ca să vadă fără să fie văzut. Isus l-a strigat pe nume și S-a autoinvitat la el acasă, înaintea oricărei schimbări. Schimbarea a venit după masă, nu înainte.",
    question: "Aștepți să te faci mai bun înainte să-L primești în casă?",
    prayer: "Doamne, intră în casa mea așa cum e ea azi. Amin.",
    step: "Invită-L azi într-o zonă din viața ta în care nu L-ai lăsat să intre.",
  },
  {
    id: "dev_319",
    dayNumber: 319,
    theme: LUNA_11,
    axis: "freedom",
    verseRef: "Ioan 4:29",
    verseText: "Veniți de vedeți un om care mi-a spus tot ce am făcut; nu cumva este Acesta Hristosul?",
    meditation:
      "Femeia venise la fântână la amiază, la ora la care nu era nimeni, tocmai ca să evite privirile. Se întoarce în cetate și spune tuturor exact ce ascundea. Când cineva te cunoaște în întregime și totuși rămâne, secretul își pierde puterea.",
    question: "Ce ți-ar schimba viața dacă nu ar mai fi secret?",
    prayer: "Doamne, Tu știi tot și n-ai plecat. Amin.",
    step: "Alege o oră din zi în care eviți oamenii și nu o mai evita azi.",
  },
  {
    id: "dev_320",
    dayNumber: 320,
    theme: LUNA_11,
    axis: "freedom",
    verseRef: "Luca 7:38",
    verseText: "Și stătea înapoi, lângă picioarele lui Isus, și plângea. Apoi a început să-I stropească picioarele cu lacrimile ei și să le șteargă cu părul capului ei.",
    meditation:
      "A intrat neinvitată într-o casă de fariseu, știind exact ce se spunea despre ea. A ales umilirea sigură în locul rușinii ascunse. Isus a primit-o și a mustrat gazda, nu pe ea.",
    question: "Ce te-ar costa să vii așa la El?",
    prayer: "Doamne, vin cu tot ce sunt, chiar dacă se uită lumea. Amin.",
    step: "Fă azi un gest de închinare pe care nu l-ai face dacă te-ar vedea cineva.",
  },
  {
    id: "dev_321",
    dayNumber: 321,
    theme: LUNA_11,
    axis: "freedom",
    verseRef: "Luca 15:21",
    verseText: "Fiul i-a zis: „Tată, am păcătuit împotriva cerului și împotriva ta, nu mai sunt vrednic să mă chem fiul tău.”",
    meditation:
      "Fiul își pregătise un discurs în care cerea să fie făcut argat. Tatăl nu-l lasă să-l termine și cere haina, inelul și încălțămintea — semnele de fiu. Rușinea ne învață să negociem o poziție mai mică decât cea pe care ne-o dă Dumnezeu.",
    question: "Ce poziție mai mică Îi ceri, ca să fie mai ușor de crezut?",
    prayer: "Tată, primesc să fiu fiu, nu argat. Amin.",
    step: "Nu-ți mai spune azi „sunt un creștin slab”. Spune „sunt copilul Lui”.",
  },
  {
    id: "dev_322",
    dayNumber: 322,
    theme: LUNA_11,
    axis: "freedom",
    verseRef: "Psalmul 51:17",
    verseText: "Jertfele plăcute lui Dumnezeu sunt un duh zdrobit: Dumnezeule, Tu nu disprețuiești o inimă zdrobită și mâhnită.",
    meditation:
      "David scrie asta după cel mai urât episod din viața lui. Descoperă că ce Îi aduce lui Dumnezeu nu e o reparare, ci o inimă sfărâmată. Ce ți se pare că te descalifică e exact ce El nu disprețuiește.",
    question: "Ți-e teamă că ești prea stricat ca să mai fii primit?",
    prayer: "Doamne, Îți aduc o inimă zdrobită. Tu n-o disprețuiești. Amin.",
    step: "Citește azi tot Psalmul 51, rar.",
  },
  {
    id: "dev_323",
    dayNumber: 323,
    theme: LUNA_11,
    axis: "freedom",
    verseRef: "Psalmul 32:3-5",
    verseText: "Câtă vreme am tăcut, mi se topeau oasele... Atunci ți-am mărturisit păcatul meu și nu mi-am ascuns fărădelegea. Și Tu ai iertat vina păcatului meu.",
    meditation:
      "Tăcerea are un preț fizic: David vorbește de oase și de putere secată. Secretul ținut consumă mai multă energie decât mărturisirea. Eliberarea a venit în clipa în care a spus lucrurile pe nume.",
    question: "Ce te obosește să ții ascuns?",
    prayer: "Doamne, nu-mi mai ascund fărădelegea. Ți-o spun. Amin.",
    step: "Mărturisește azi lui Dumnezeu, în cuvinte clare, lucrul acela.",
  },
  {
    id: "dev_324",
    dayNumber: 324,
    theme: LUNA_11,
    axis: "freedom",
    verseRef: "Proverbe 28:13",
    verseText: "Cine își ascunde fărădelegile nu propășește, dar cine le mărturisește și se lasă de ele capătă îndurare.",
    meditation:
      "Sunt două verbe, nu unul: mărturisește și se lasă. Mărturisirea fără părăsire devine un ritual, iar părăsirea fără mărturisire rămâne o luptă singuratică. Îndurarea stă la capătul amândurora.",
    question: "Care dintre cele două verbe îți lipsește?",
    prayer: "Doamne, ajută-mă și să spun, și să las. Amin.",
    step: "Fă azi un pas concret de părăsire: șterge, blochează, înapoiază, refuză.",
  },
  {
    id: "dev_325",
    dayNumber: 325,
    theme: LUNA_11,
    axis: "freedom",
    verseRef: "1 Ioan 3:20",
    verseText: "În orice ne osândește inima noastră; căci Dumnezeu este mai mare decât inima noastră și cunoaște toate lucrurile.",
    meditation:
      "Sunt zile în care propria inimă e cel mai aspru judecător. Ioan nu spune „ascultă-ți inima”, ci exact invers: Dumnezeu e mai mare decât ea. El știe tot — și cunoscând tot, tot te primește.",
    question: "Cine te condamnă mai tare: Dumnezeu sau tu?",
    prayer: "Doamne, Tu ești mai mare decât inima mea care mă acuză. Amin.",
    step: "Când te acuzi azi, spune cu voce tare versetul ăsta.",
  },
  {
    id: "dev_326",
    dayNumber: 326,
    theme: LUNA_11,
    axis: "freedom",
    verseRef: "Romani 8:33",
    verseText: "Cine va ridica pâră împotriva aleșilor lui Dumnezeu? Dumnezeu este Acela care-i socotește neprihăniți!",
    meditation:
      "Pavel folosește limbaj de tribunal: cine e procurorul? Judecătorul te-a declarat deja neprihănit. Rușinea vine mereu îmbrăcată în rechizitoriu, dar n-are mandat.",
    question: "Ce acuzație ți se repetă în minte?",
    prayer: "Doamne, Tu m-ai declarat neprihănit. Cazul e închis. Amin.",
    step: "Scrie acuzația care se întoarce mereu și, sub ea, versetul de azi.",
  },
  {
    id: "dev_327",
    dayNumber: 327,
    theme: LUNA_11,
    axis: "freedom",
    verseRef: "Apocalipsa 12:10",
    verseText: "Pârâșul fraților noștri, care zi și noapte îi pâra înaintea Dumnezeului nostru, a fost aruncat jos.",
    meditation:
      "Vrăjmașul e numit după ocupația lui: pârâș. Lucrează zi și noapte și folosește adesea adevăruri, nu minciuni — dar cu scopul de a te ține culcat. Textul spune ce s-a întâmplat cu el: a fost aruncat jos.",
    question: "Ai crezut că vocea care te acuză zi și noapte e a lui Dumnezeu?",
    prayer: "Doamne, învață-mă să recunosc vocea pârâșului. Amin.",
    step: "Compară azi ce-ți spune vocea aceea cu ce spune Scriptura despre tine.",
  },
  {
    id: "dev_328",
    dayNumber: 328,
    theme: LUNA_11,
    axis: "freedom",
    verseRef: "Zaharia 3:4",
    verseText: "Dezbrăcați-l de hainele murdare de pe el! Apoi a zis lui Iosua: „Iată că îndepărtez de la tine nelegiuirea și te îmbrac cu haine de sărbătoare!”",
    meditation:
      "E o scenă de tribunal în care Satana stă de-a dreapta ca să pârască, iar Dumnezeu nu discută acuzațiile: schimbă hainele. Nu i se cere lui Iosua să-și spele singur veșmintele. Curățirea vine ca dar, în fața martorilor.",
    question: "În ce haine te vezi când te gândești la tine?",
    prayer: "Doamne, ia-mi hainele murdare și îmbracă-mă Tu. Amin.",
    step: "Alege azi o haină curată și, îmbrăcând-o, adu-ți aminte de versetul ăsta.",
  },
  {
    id: "dev_329",
    dayNumber: 329,
    theme: LUNA_11,
    axis: "freedom",
    verseRef: "Isaia 50:7",
    verseText: "Dar Domnul Dumnezeu M-a ajutat; de aceea nu M-am rușinat, de aceea Mi-am făcut fața ca o cremene, știind că nu voi fi dat de rușine.",
    meditation:
      "„Fața ca o cremene” nu înseamnă obrăznicie, ci hotărârea de a merge înainte când știi cine te susține. E o profeție despre Isus mergând spre Ierusalim. Un om care nu-și mai apără imaginea are o tărie ciudată.",
    question: "Ce ai face azi dacă nu ți-ar mai fi frică de părerea nimănui?",
    prayer: "Doamne, întărește-mi fața și moaie-mi inima. Amin.",
    step: "Fă azi lucrul bun pe care îl amâni de teamă că vei părea ciudat.",
  },
  {
    id: "dev_330",
    dayNumber: 330,
    theme: LUNA_11,
    axis: "freedom",
    verseRef: "2 Corinteni 7:10",
    verseText: "În adevăr, când întristarea este după voia lui Dumnezeu, aduce o pocăință care duce la mântuire; pe când întristarea lumii aduce moartea.",
    meditation:
      "Se încheie luna cu criteriul care le desparte pe toate: o întristare te duce spre Dumnezeu, cealaltă te închide în tine. Prima spune „am greșit și pot veni acasă”; a doua spune „sunt o greșeală”. Luna viitoare, ultima, e despre exact ce se întâmplă când cazi — har la cădere.",
    question: "În ce fel de întristare ai trăit în luna asta?",
    prayer: "Doamne, dă-mi o întristare care duce la Tine, nu una care mă îngroapă. Amin.",
    step: "Recitește ce ai scris în ziua 302 și vezi dacă mai porți frunzele acelea.",
  },
]
