// Devoțional, luna 9: „Ce crește pe nevăzut” (docs/27 §2.4, axa character).
//
// Regula lunii: după luna tăcerii, urmează luna în care se arată ce se întâmplă
// în pământul acela tăcut. Caracterul crește ca o sămânță: încet, sub pământ și
// fără martori. Zilele nu cer performanță, ci răbdare și statornicie în lucruri
// mici, repetate.
//
// Conținut ORIGINAL Emanus (docs/27 §1.2). Versete: Cornilescu (domeniu public).
import type { DevotionalDay } from "./devotional.js"

const LUNA_9 = "Ce crește pe nevăzut"

export const DEVOTIONAL_DAYS_LUNA_9: DevotionalDay[] = [
  {
    id: "dev_241",
    dayNumber: 241,
    theme: LUNA_9,
    axis: "character",
    verseRef: "Marcu 4:26-27",
    verseText: "Cu Împărăția lui Dumnezeu este ca atunci când aruncă un om sămânță în pământ; fie că doarme noaptea, fie că se scoală ziua, sămânța încolțește și crește fără să știe el cum.",
    meditation:
      "Omul din pildă doarme și totuși lucrarea merge înainte. Creșterea nu depinde de cât de atent o supraveghezi. E o veste bună pentru cine s-a săturat să se autoevalueze zilnic.",
    question: "Îți verifici creșterea ca pe o sămânță pe care o dezgropi în fiecare zi?",
    prayer: "Doamne, seamăn și las restul la Tine. Amin.",
    step: "Nu te evalua azi. Fă doar ce știi că e bine și culcă-te liniștit.",
  },
  {
    id: "dev_242",
    dayNumber: 242,
    theme: LUNA_9,
    axis: "character",
    verseRef: "Marcu 4:31-32",
    verseText: "Se aseamănă cu un grăunte de muștar care, când este semănat în pământ, este cea mai mică dintre toate semințele de pe pământ; dar, după ce a fost semănat, crește.",
    meditation:
      "Isus alege dinadins cel mai mic exemplu pe care îl aveau la îndemână. Distanța dintre sămânță și copac nu se face într-un salt, ci într-un timp. Ce ai tu acum poate fi mic și real în același timp.",
    question: "Disprețuiești începutul tău pentru că e mic?",
    prayer: "Doamne, ia puținul meu și fă-l să crească. Amin.",
    step: "Numește un lucru bun din viața ta care acum e doar la început.",
  },
  {
    id: "dev_243",
    dayNumber: 243,
    theme: LUNA_9,
    axis: "character",
    verseRef: "Ioan 12:24",
    verseText: "Dacă grăuntele de grâu care a căzut pe pământ nu moare, rămâne singur; dar, dacă moare, aduce multă roadă.",
    meditation:
      "Prima mișcare a creșterii nu e în sus, ci în jos: sămânța se îngroapă și se desface. Isus spunea asta despre El Însuși, cu câteva zile înainte de cruce. Ce simți tu acum ca pierdere poate fi începutul rodului.",
    question: "Ce a trebuit să moară în tine ca să crească altceva?",
    prayer: "Doamne, sunt dispus să pierd ce trebuie pierdut. Amin.",
    step: "Renunță azi la un lucru bun pentru un lucru mai bun.",
  },
  {
    id: "dev_244",
    dayNumber: 244,
    theme: LUNA_9,
    axis: "character",
    verseRef: "Galateni 6:9",
    verseText: "Să nu obosim în facerea binelui, căci, la vremea potrivită, vom secera, dacă nu vom cădea de oboseală.",
    meditation:
      "Pavel presupune că oboseala vine — nu întreabă dacă, ci când. Cel mai mare pericol nu e căderea în păcat, ci abandonul din plictiseală. „La vremea potrivită” înseamnă că recolta are un calendar pe care nu-l faci tu.",
    question: "În ce lucru bun ai obosit în ultimele luni?",
    prayer: "Doamne, dă-mi putere să nu mă opresc. Amin.",
    step: "Reia azi un lucru bun pe care l-ai lăsat baltă din oboseală.",
  },
  {
    id: "dev_245",
    dayNumber: 245,
    theme: LUNA_9,
    axis: "character",
    verseRef: "Galateni 6:7",
    verseText: "Nu vă înșelați: Dumnezeu nu Se lasă să fie batjocorit. Ce seamănă omul, aceea va și secera.",
    meditation:
      "Legea semănatului e nemiloasă și cinstită: nu culegi altceva decât ai pus în pământ. Se aplică și în rău, și în bine. Multe din lucrurile pe care le trăiești azi au fost semănate acum câțiva ani, de tine.",
    question: "Ce semeni acum, fără să-ți dai seama?",
    prayer: "Doamne, arată-mi ce seamăn cu adevărat în zilele mele. Amin.",
    step: "Uiță-te azi la un obicei zilnic și întreabă-te ce recoltă pregătește.",
  },
  {
    id: "dev_246",
    dayNumber: 246,
    theme: LUNA_9,
    axis: "character",
    verseRef: "Iacov 5:7",
    verseText: "Iată că plugarul așteaptă roada scumpă a pământului și o așteaptă cu răbdare, până primește ploaie timpurie și târzie.",
    meditation:
      "Plugarul nu e pasiv și nici agitat. Știe ce depinde de el și ce nu — nu poate face ploaie. Răbdarea nu e resemnare, ci meseria omului care lucrează cu vremea lui Dumnezeu.",
    question: "Ce parte e a ta și ce parte e a Lui, în lucrul care te presează?",
    prayer: "Doamne, îmi fac partea și aștept ploaia de la Tine. Amin.",
    step: "Împarte azi pe hârtie: „depinde de mine” / „nu depinde de mine”.",
  },
  {
    id: "dev_247",
    dayNumber: 247,
    theme: LUNA_9,
    axis: "character",
    verseRef: "Psalmul 1:3",
    verseText: "El este ca un pom sădit lângă un izvor de apă, care își dă rodul la vremea lui și ale cărui frunze nu se veștejesc.",
    meditation:
      "Versetul dinainte spune de unde vine seva: din Legea Domnului, cugetată zi și noapte. Pomul nu se străduiește să rodească, ci stă lângă apă. Cea mai bună decizie de creștere e să te muți lângă izvor.",
    question: "Cu ce îți hrănești mintea zi de zi?",
    prayer: "Doamne, sădește-mă lângă apa Cuvântului Tău. Amin.",
    step: "Citește azi Psalmul 1 dimineața și seara.",
  },
  {
    id: "dev_248",
    dayNumber: 248,
    theme: LUNA_9,
    axis: "character",
    verseRef: "Ieremia 17:8",
    verseText: "Căci el este ca un pom sădit lângă ape care-și întinde rădăcinile spre râu; nu se teme de căldură, când vine, și frunzișul lui rămâne verde.",
    meditation:
      "Ce se vede la un pom în secetă e ce a făcut sub pământ în anii buni. Rădăcinile nu se fac în timpul crizei. De aceea obiceiurile mici din zilele liniștite sunt investiții pentru zilele grele.",
    question: "Ce rădăcină îți faci acum, pentru seceta de mâine?",
    prayer: "Doamne, dă-mi rădăcini adânci, nu doar frunze frumoase. Amin.",
    step: "Alege un obicei duhovnicesc și ține-l zilnic până la sfârșitul lunii.",
  },
  {
    id: "dev_249",
    dayNumber: 249,
    theme: LUNA_9,
    axis: "character",
    verseRef: "Coloseni 2:7",
    verseText: "Fiți înrădăcinați și zidiți în El, întăriți prin credință, după învățăturile care v-au fost date, și sporind în ea cu mulțumiri către Dumnezeu.",
    meditation:
      "Pavel amestecă două imagini: pomul și casa. Una crește singură, cealaltă se zidește cărămidă cu cărămidă. Creșterea duhovnicească le are pe amândouă — lucrare a Lui și alegeri ale tale.",
    question: "Ce cărămidă ai de pus tu azi?",
    prayer: "Doamne, crește-mă și învață-mă să pun cărămizile mele. Amin.",
    step: "Fă azi lucrul mic și plictisitor pe care știi că trebuie să-l faci.",
  },
  {
    id: "dev_250",
    dayNumber: 250,
    theme: LUNA_9,
    axis: "character",
    verseRef: "Efeseni 3:17",
    verseText: "Așa încât Hristos să locuiască în inimile voastre prin credință; pentru ca, având rădăcina și temelia pusă în dragoste...",
    meditation:
      "Rădăcina nu e în reguli, nici în frică, ci în dragoste. Un om care crește din teamă face lucruri corecte cu o inimă uscată. Verifică din când în când nu doar ce faci, ci din ce rădăcină.",
    question: "Din ce rădăcină Î-I slujești: dragoste sau teamă?",
    prayer: "Doamne, mută-mi rădăcina în dragostea Ta. Amin.",
    step: "Fă azi un lucru bun pentru că vrei, nu pentru că trebuie.",
  },
  {
    id: "dev_251",
    dayNumber: 251,
    theme: LUNA_9,
    axis: "character",
    verseRef: "Ioan 15:2",
    verseText: "Pe orice mlădiță care aduce roadă, o curățește, ca să aducă și mai multă roadă.",
    meditation:
      "Tăierea nu e pedeapsă; e semn că mlădița rodește. Vierul taie exact ramurile bune, ca puterea să nu se risipească. Unele pierderi din viața ta sunt lucrare de grădină, nu abandon.",
    question: "Ce ți s-a luat, deși nu era rău?",
    prayer: "Doamne, taie ce trebuie tăiat. Am încredere în mâna Ta. Amin.",
    step: "Renunță azi la o activitate bună care îți mănâncă timpul de familie sau de rugăciune.",
  },
  {
    id: "dev_252",
    dayNumber: 252,
    theme: LUNA_9,
    axis: "character",
    verseRef: "Ioan 15:4",
    verseText: "Rămâneți în Mine și Eu voi rămâne în voi. După cum mlădița nu poate aduce roadă de la sine, dacă nu rămâne în viță, tot așa nici voi nu puteți aduce roadă dacă nu rămâneți în Mine.",
    meditation:
      "Mlădița nu se străduiește să facă struguri; rămâne legată și strugurii vin. Cuvântul cheie al capitolului nu e „rodește”, ci „rămâneți”. Toată lupta ta se poate muta din producție în legătură.",
    question: "Te străduiești să rodești sau te străduiești să rămâi?",
    prayer: "Doamne, nu pot nimic despărțit de Tine. Rămân. Amin.",
    step: "Înlocuiește azi o încercare de a te schimba cu zece minute petrecute cu El.",
  },
  {
    id: "dev_253",
    dayNumber: 253,
    theme: LUNA_9,
    axis: "character",
    verseRef: "Galateni 5:22-23",
    verseText: "Roada Duhului, dimpotrivă, este dragostea, bucuria, pacea, îndelunga răbdare, bunătatea, facerea de bine, credincioșia, blândețea, înfrânarea.",
    meditation:
      "E „roada”, la singular, nu „roadele”: nu îți alegi două și le lași pe restul. Și e roada Duhului, nu realizarea ta — tu doar rămâi în viță. Privește lista ca pe un portret al lui Isus, nu ca pe o fișă de evaluare.",
    question: "Care dintre cele nouă lipsește cel mai tare din viața ta?",
    prayer: "Duhule Sfinte, crește în mine ce lipsește. Amin.",
    step: "Alege una dintre cele nouă și roagă-te pentru ea în fiecare zi din luna asta.",
  },
  {
    id: "dev_254",
    dayNumber: 254,
    theme: LUNA_9,
    axis: "character",
    verseRef: "Matei 7:16",
    verseText: "Îi veți cunoaște după roadele lor. Culeg oamenii struguri din spini sau smochine din mărăcini?",
    meditation:
      "Isus dă un criteriu simplu și încet: roada. Nu vorbe, nu impresie, nu discurs — ce crește în timp. Se aplică și la cei pe care îi asculți, și la tine.",
    question: "Ce roade se văd în tine în ultimii trei ani?",
    prayer: "Doamne, fă-mă un om care se vede după fapte, nu după vorbe. Amin.",
    step: "Întreabă pe cineva apropiat ce schimbare a observat la tine.",
  },
  {
    id: "dev_255",
    dayNumber: 255,
    theme: LUNA_9,
    axis: "character",
    verseRef: "Luca 13:8-9",
    verseText: "Doamne, mai lasă-l și anul acesta; am să-l sap de jur împrejur și am să-i pun gunoi la rădăcină. Poate că de acum înainte va face roadă.",
    meditation:
      "E o pildă despre îngăduință: cineva mijlocește pentru un pom neroditor și cere încă un an. Dumnezeu dă timp, dar timpul dat vine cu săpat și îngrășat. Harul nu înseamnă că nu se întâmplă nimic anul ăsta.",
    question: "Ce an în plus ți-a dat Dumnezeu și cum îl folosești?",
    prayer: "Doamne, mulțumesc pentru răbdarea Ta cu mine. Sapă în jurul meu. Amin.",
    step: "Cere-I azi lui Dumnezeu să-ți arate ce trebuie săpat în viața ta.",
  },
  {
    id: "dev_256",
    dayNumber: 256,
    theme: LUNA_9,
    axis: "character",
    verseRef: "Filipeni 2:13",
    verseText: "Căci Dumnezeu este Acela care lucrează în voi și vă dă, după plăcerea Lui, și voința, și înfăptuirea.",
    meditation:
      "Chiar și dorința de a fi mai bun vine tot de la El. Asta scoate mândria din creștere și scoate și disperarea: nu ești singurul care trage. Când simți că vrei binele, e deja un semn că Cineva lucrează.",
    question: "Ai crezut că schimbarea depinde doar de voința ta?",
    prayer: "Doamne, lucrează în mine și voința, și înfăptuirea. Amin.",
    step: "Mulțumește-I azi pentru o dorință bună pe care o ai și pe care n-ai fabricat-o tu.",
  },
  {
    id: "dev_257",
    dayNumber: 257,
    theme: LUNA_9,
    axis: "character",
    verseRef: "2 Corinteni 4:16",
    verseText: "De aceea, noi nu cădem de oboseală. Ci, chiar dacă omul nostru de afară se trece, totuși omul nostru dinlăuntru se înnoiește din zi în zi.",
    meditation:
      "Sunt două mișcări simultane: una în jos, văzută, alta în sus, nevăzută. Trupul îmbătrânește și toată lumea vede; omul dinlăuntru se înnoiește și nu vede aproape nimeni. „Din zi în zi” înseamnă că se întâmplă și azi.",
    question: "Care dintre cele două mișcări te preocupă mai mult?",
    prayer: "Doamne, înnoiește-mă pe dinăuntru, chiar dacă nu se vede. Amin.",
    step: "Fă azi un lucru pentru omul dinăuntru și unul pentru trupul tău.",
  },
  {
    id: "dev_258",
    dayNumber: 258,
    theme: LUNA_9,
    axis: "character",
    verseRef: "2 Corinteni 3:18",
    verseText: "Noi toți privim cu fața descoperită, ca într-o oglindă, slava Domnului și suntem schimbați în același chip al Lui, din slavă în slavă.",
    meditation:
      "Schimbarea vine din privire, nu din încordare. Devii ca Acela la care te uiți mult — lucru care se vede și în rău, la ce consumi zilnic. „Din slavă în slavă” e o mișcare lentă, cu trepte.",
    question: "La ce te uiți cel mai mult într-o zi?",
    prayer: "Doamne, întoarce-mi privirea spre Tine. Amin.",
    step: "Taie azi treizeci de minute de ecran și pune în loc Scriptura.",
  },
  {
    id: "dev_259",
    dayNumber: 259,
    theme: LUNA_9,
    axis: "character",
    verseRef: "Romani 5:3-4",
    verseText: "Ba mai mult, ne bucurăm chiar și în necazurile noastre; căci știm că necazul aduce răbdare, răbdarea aduce biruință în încercare, iar biruința aceasta aduce nădejdea.",
    meditation:
      "E un lanț, nu un salt: necaz, răbdare, caracter încercat, nădejde. Nimeni nu ajunge la ultima verigă sărind peste primele. Nu înseamnă că necazul e bun, ci că Dumnezeu știe să-l folosească.",
    question: "În ce verigă ești acum?",
    prayer: "Doamne, nu irosi încercarea prin care trec. Amin.",
    step: "Scrie ce te-a învățat cel mai greu an din viața ta.",
  },
  {
    id: "dev_260",
    dayNumber: 260,
    theme: LUNA_9,
    axis: "character",
    verseRef: "Iacov 1:3-4",
    verseText: "Căci știți că încercarea credinței voastre lucrează răbdare. Dar răbdarea trebuie să-și facă desăvârșit lucrarea.",
    meditation:
      "Iacov cere ceva greu: să lași răbdarea să-și termine treaba. Noi vrem să ieșim din încercare cu o zi mai devreme și pierdem exact partea finală. Cine grăbește procesul rămâne cu jumătate din lecție.",
    question: "Ce încerci să grăbești în viața ta?",
    prayer: "Doamne, lasă răbdarea să-și facă lucrarea în mine, până la capăt. Amin.",
    step: "Nu forța azi nicio ieșire rapidă. Fă doar pasul de azi.",
  },
  {
    id: "dev_261",
    dayNumber: 261,
    theme: LUNA_9,
    axis: "character",
    verseRef: "1 Petru 1:7",
    verseText: "Pentru ca încercarea credinței voastre, cu mult mai scumpă decât aurul care piere și care totuși este încercat prin foc, să aibă ca urmare lauda, slava și cinstea.",
    meditation:
      "Aurul se pune în foc nu ca să fie distrus, ci ca să iasă zgura la suprafață. Focul nu adaugă nimic; scoate ce nu e aur. Și Petru spune că credința ta e mai de preț decât metalul pentru care se ucid oamenii.",
    question: "Ce a scos la suprafață, în tine, ultima încercare?",
    prayer: "Doamne, curăță-mă, chiar dacă doare. Amin.",
    step: "Mărturisește un lucru urât pe care presiunea l-a scos din tine.",
  },
  {
    id: "dev_262",
    dayNumber: 262,
    theme: LUNA_9,
    axis: "character",
    verseRef: "Eclesiastul 3:1",
    verseText: "Toate își au vremea lor și fiecare lucru de sub ceruri își are ceasul lui.",
    meditation:
      "Nu tot ce e bun e bun acum. Un pom care înflorește în decembrie își pierde florile. O bună parte din înțelepciune e să recunoști în ce anotimp ești și să trăiești pe măsură.",
    question: "În ce anotimp ești: semănat, creștere, seceriș sau odihnă?",
    prayer: "Doamne, ajută-mă să trăiesc anotimpul în care sunt. Amin.",
    step: "Numește-ți anotimpul și renunță la o așteptare care nu i se potrivește.",
  },
  {
    id: "dev_263",
    dayNumber: 263,
    theme: LUNA_9,
    axis: "character",
    verseRef: "Eclesiastul 11:6",
    verseText: "Dimineața, seamănă-ți sămânța, și până seara nu lăsa mâna să ți se odihnească; fiindcă nu știi ce va izbândi.",
    meditation:
      "Fiindcă nu știi care sămânță prinde, seamănă mai multe. E un antidot pentru perfecționismul care așteaptă condiții ideale. Fă binele care îți stă în mână, chiar dacă nu-i vezi rostul.",
    question: "Ce bine amâni pentru că nu știi dacă folosește la ceva?",
    prayer: "Doamne, seamăn și las rezultatul la Tine. Amin.",
    step: "Fă azi un gest bun despre care nu vei afla niciodată ce a produs.",
  },
  {
    id: "dev_264",
    dayNumber: 264,
    theme: LUNA_9,
    axis: "character",
    verseRef: "Isaia 61:3",
    verseText: "Ca să le dau o cunună împărătească în loc de cenușă... ca să fie numiți terebinți ai neprihănirii, un sad al Domnului, ca să slujească spre slava Lui.",
    meditation:
      "Dumnezeu nu doar consolează; transformă cenușa în copaci. Terebintul e un arbore care trăiește sute de ani și crește încet. Din cele mai arse locuri ale vieții tale poate ieși ceva care să țină umbră altora.",
    question: "Care e cenușa din care ar putea Dumnezeu să facă ceva?",
    prayer: "Doamne, ia cenușa mea și fă din ea un sad al Tău. Amin.",
    step: "Spune-I azi ce zonă arsă din viața ta Îi dai să o folosească.",
  },
  {
    id: "dev_265",
    dayNumber: 265,
    theme: LUNA_9,
    axis: "character",
    verseRef: "Psalmul 92:12-13",
    verseText: "Cel fără prihană înverzește ca finicul și crește ca cedrul din Liban. Cei sădiți în Casa Domnului înverzesc în curțile Dumnezeului nostru.",
    meditation:
      "Observă unde sunt sădiți: nu oriunde, ci în Casa Domnului. Creșterea are și o dimensiune de loc — oamenii care rămân într-o comunitate cresc altfel decât cei care se mută mereu. Statornicia e o condiție de sol.",
    question: "Ești sădit undeva sau doar treci pe la mai multe locuri?",
    prayer: "Doamne, sădește-mă și ține-mă acolo. Amin.",
    step: "Ia azi o decizie de statornicie: o biserică, un grup, un om.",
  },
  {
    id: "dev_266",
    dayNumber: 266,
    theme: LUNA_9,
    axis: "character",
    verseRef: "Psalmul 92:14",
    verseText: "Ei aduc roade și la bătrânețe, sunt plini de suc și verzi.",
    meditation:
      "E o promisiune pentru partea a doua a vieții, când lumea spune că nu mai ai ce da. În Împărăție, anii nu scad valoarea unui om, ci o adaugă. Bătrânii care rodesc sunt cea mai rară și cea mai necesară bogăție a unei biserici.",
    question: "Ce bătrân roditor cunoști și când i-ai mulțumit ultima dată?",
    prayer: "Doamne, vreau să rodesc și la bătrânețe. Amin.",
    step: "Sună azi un om în vârstă și cere-i un sfat, nu doar întreabă-l ce face.",
  },
  {
    id: "dev_267",
    dayNumber: 267,
    theme: LUNA_9,
    axis: "character",
    verseRef: "Osea 10:12",
    verseText: "Semănați potrivit cu neprihănirea și veți secera potrivit cu îndurarea. Desfundați-vă un ogor nou!",
    meditation:
      "Ogorul nedesfundat e pământ bun peste care s-a făcut crustă. Nu-i lipsește sămânța, ci spărtura. Uneori nu ai nevoie de o nouă învățătură, ci să spargi o crustă veche de obișnuință.",
    question: "Unde s-a făcut crustă în viața ta duhovnicească?",
    prayer: "Doamne, sparge crusta din inima mea. Amin.",
    step: "Schimbă azi ceva în rutina ta cu Dumnezeu: altă oră, alt loc, altă carte.",
  },
  {
    id: "dev_268",
    dayNumber: 268,
    theme: LUNA_9,
    axis: "character",
    verseRef: "Matei 13:8",
    verseText: "O altă parte a căzut în pământ bun și a dat roadă: un grăunte a dat o sută, altul șaizeci și altul treizeci.",
    meditation:
      "Chiar și în pământ bun, recolta diferă. Treizeci nu e eșec și o sută nu e merit. Comparația cu alții e cel mai bun mod de a strica o roadă adevărată.",
    question: "Cu cine te compari și ce îți face comparația asta?",
    prayer: "Doamne, dă-mi roada mea, nu roada altuia. Amin.",
    step: "Nu te compara azi cu nimeni. Când începi, oprește-te și mulțumește.",
  },
  {
    id: "dev_269",
    dayNumber: 269,
    theme: LUNA_9,
    axis: "character",
    verseRef: "Matei 13:22",
    verseText: "Sămânța căzută între spini este cel ce aude Cuvântul, dar îngrijorările veacului acestuia și înșelăciunea bogățiilor îneacă acest Cuvânt și îl fac astfel neroditor.",
    meditation:
      "Spinii nu neagă sămânța; o sufocă. Nimeni nu decide să-și înece viața duhovnicească — pur și simplu lasă să crească alături lucruri care cer tot spațiul. Grădinăritul înseamnă și smulgere, nu doar semănat.",
    question: "Ce spin crește acum lângă lucrurile bune din viața ta?",
    prayer: "Doamne, smulge din mine grijile care îneacă tot. Amin.",
    step: "Elimină azi un singur spin: o aplicație, o obligație, o cheltuială.",
  },
  {
    id: "dev_270",
    dayNumber: 270,
    theme: LUNA_9,
    axis: "character",
    verseRef: "1 Corinteni 3:6",
    verseText: "Eu am sădit, Apolo a udat, dar Dumnezeu a făcut să crească.",
    meditation:
      "Se încheie luna cu singura propoziție care așază totul la locul lui: creșterea nu e a ta. Tu ai sădit și ai udat treizeci de zile, poate fără să vezi mare lucru. Luna viitoare mergem și mai jos, la lucrurile mici — pentru că acolo se face, de fapt, toată creșterea asta.",
    question: "Ce ai sădit în luna asta?",
    prayer: "Doamne, eu am sădit și am udat. Tu fă să crească. Amin.",
    step: "Recitește obiceiul ales în ziua 248 și hotărăște dacă îl duci mai departe.",
  },
]
