// Devoțional, luna 8: „Când Dumnezeu tace” (docs/27 §2.4, axa living_faith).
//
// Regula lunii: nu se dau explicații ușoare pentru tăcerea lui Dumnezeu și nu se
// promite că răspunsul vine până la sfârșitul lunii. Zilele stau lângă om în
// așteptare, cu textele care spun exact ce simte el — pentru că Biblia are și
// „până când?”, nu doar „Amin”.
//
// Conținut ORIGINAL Emanus (docs/27 §1.2). Versete: Cornilescu VDC 1924 (domeniu
// public), colaționate verset cu verset.
import type { DevotionalDay } from "./devotional.js"

const LUNA_8 = "Când Dumnezeu tace"

export const DEVOTIONAL_DAYS_LUNA_8: DevotionalDay[] = [
  {
    id: "dev_211",
    dayNumber: 211,
    theme: LUNA_8,
    axis: "living_faith",
    verseRef: "Psalmul 13:1",
    verseText: "Până când, Doamne, mă vei uita neîncetat? Până când Îți vei ascunde Fața de mine?",
    meditation:
      "Dumnezeu a lăsat în cartea Lui întrebarea asta, cu tot cu reproșul din ea. Deci nu e necredință să întrebi „până când?”. Necredința ar fi să nu mai întrebi pe nimeni.",
    question: "Ai voie să-I spui că te simți uitat. Ai făcut-o vreodată?",
    prayer: "Doamne, până când? Îți spun cinstit: nu mai înțeleg. Amin.",
    step: "Scrie azi întrebarea ta către Dumnezeu, exact așa cum sună în tine.",
  },
  {
    id: "dev_212",
    dayNumber: 212,
    theme: LUNA_8,
    axis: "living_faith",
    verseRef: "Psalmul 22:1-2",
    verseText: "Dumnezeule! Dumnezeule! Pentru ce m-ai părăsit și pentru ce Te depărtezi fără să-mi ajuți și fără s-asculți plângerile mele? Strig ziua, Dumnezeule, și nu-mi răspunzi; strig și noaptea, și tot n-am odihnă.",
    meditation:
      "Psalmul ăsta a fost rugăciunea lui Isus pe cruce. Înseamnă că sentimentul de părăsire poate fi trăit de un om care nu e părăsit cu adevărat. Simțirea nu e un raport exact despre unde e Dumnezeu.",
    question: "Ce concluzii ai tras despre Dumnezeu doar din ce ai simțit?",
    prayer: "Doamne, mă simt părăsit, dar aleg să cred că nu sunt. Amin.",
    step: "Citește azi tot Psalmul 22 și vezi cum se termină.",
  },
  {
    id: "dev_213",
    dayNumber: 213,
    theme: LUNA_8,
    axis: "living_faith",
    verseRef: "Iov 23:8-9",
    verseText: "Dar, dacă mă duc la răsărit, nu este acolo; dacă mă duc la apus, nu-L găsesc; dacă are treabă la miazănoapte, nu-L pot vedea; dacă Se ascunde la miazăzi, nu-L pot descoperi.",
    meditation:
      "Iov nu-L nega pe Dumnezeu; Îl căuta și nu-L găsea. E o stare pe care mulți creștini o trăiesc și despre care nu îndrăznesc să vorbească în biserică. Faptul că Îl cauți încă e, în sine, un semn de credință.",
    question: "Ai crezut că ești singurul care trece prin asta?",
    prayer: "Doamne, Te caut și nu Te găsesc. Dar nu încetez să caut. Amin.",
    step: "Spune azi cuiva de încredere că treci printr-o perioadă seacă.",
  },
  {
    id: "dev_214",
    dayNumber: 214,
    theme: LUNA_8,
    axis: "living_faith",
    verseRef: "Iov 23:10",
    verseText: "Dar El știe ce cale am urmat și, dacă m-ar încerca, aș ieși curat ca aurul.",
    meditation:
      "În aceeași respirație în care spune că nu-L găsește, Iov spune că Dumnezeu îl vede. E o credință fără dovezi și fără explicații: „nu știu unde e El, dar El știe unde sunt eu”. Atât e destul pentru o zi.",
    question: "Poți spune și tu propoziția asta azi?",
    prayer: "Doamne, nu Te văd, dar Tu știi calea pe care merg. Amin.",
    step: "Rostește versetul ăsta de trei ori azi, când te lovește nesiguranța.",
  },
  {
    id: "dev_215",
    dayNumber: 215,
    theme: LUNA_8,
    axis: "living_faith",
    verseRef: "Habacuc 1:2",
    verseText: "Până când voi striga către Tine, Doamne, fără s-asculți? Până când mă voi tângui Ție, fără să dai ajutor?",
    meditation:
      "Cartea unui profet începe cu o plângere împotriva tăcerii lui Dumnezeu. Habacuc nu-și cere scuze pentru întrebare și nu primește mustrare. Dumnezeu suportă întrebările oamenilor mai bine decât suportăm noi.",
    question: "Te temi că Dumnezeu se supără dacă Îi reproșezi ceva?",
    prayer: "Doamne, strig și nu aud nimic. Dar strig către Tine, nu împotriva Ta. Amin.",
    step: "Citește azi primul capitol din Habacuc. Are doar 17 versete.",
  },
  {
    id: "dev_216",
    dayNumber: 216,
    theme: LUNA_8,
    axis: "living_faith",
    verseRef: "Habacuc 2:3",
    verseText: "Căci este o prorocie a cărei vreme este hotărâtă, se apropie de împlinire și nu va minți; dacă zăbovește, așteapt-o, căci va veni și se va împlini negreșit.",
    meditation:
      "Răspunsul lui Dumnezeu la „până când?” n-a fost o dată exactă, ci un cuvânt: așteaptă. Întârzierea nu înseamnă anulare. Înseamnă că vremea e hotărâtă de Altcineva.",
    question: "Confunzi întârzierea cu refuzul?",
    prayer: "Doamne, aștept. Vremea e a Ta, nu a mea. Amin.",
    step: "Scrie în jurnal data de azi și lucrul pe care îl aștepți. Lasă loc pentru răspuns.",
  },
  {
    id: "dev_217",
    dayNumber: 217,
    theme: LUNA_8,
    axis: "living_faith",
    verseRef: "Habacuc 3:17-18",
    verseText: "Căci, chiar dacă smochinul nu va înflori, vița nu va da niciun rod, rodul măslinului va lipsi și câmpiile nu vor da hrană, oile vor pieri din staule și nu vor mai fi boi în grajduri, eu tot mă voi bucura în Domnul, mă voi bucura în Dumnezeul mântuirii mele!",
    meditation:
      "E ultimul cuvânt al cărții și nu s-a schimbat nimic în circumstanțe: smochinul tot nu înflorea. S-a schimbat locul în care își pusese bucuria. Asta e credința matură — nu negația, ci mutarea temeliei.",
    question: "Pe ce stă bucuria ta acum: pe circumstanțe sau pe El?",
    prayer: "Doamne, chiar dacă nu se schimbă nimic, mă bucur în Tine. Amin.",
    step: "Numește azi un motiv de bucurie care nu depinde de ce aștepți.",
  },
  {
    id: "dev_218",
    dayNumber: 218,
    theme: LUNA_8,
    axis: "living_faith",
    verseRef: "Plângerile lui Ieremia 3:8",
    verseText: "Să tot strig și să tot cer ajutor, căci El tot nu-mi primește rugăciunea.",
    meditation:
      "Versetul ăsta e în Biblie și nu e cenzurat. Ieremia își spune durerea fără să o îmblânzească, iar Dumnezeu a păstrat-o în Scriptură. Dacă ai gândit vreodată așa, nu ești în afara credinței.",
    question: "Ce nu îndrăznești să spui pentru că ți se pare prea negru?",
    prayer: "Doamne, Îți spun și partea întunecată. Nu vreau să mă prefac înaintea Ta. Amin.",
    step: "Scrie o rugăciune pe care nu ai spune-o cu voce tare într-o adunare.",
  },
  {
    id: "dev_219",
    dayNumber: 219,
    theme: LUNA_8,
    axis: "living_faith",
    verseRef: "Plângerile lui Ieremia 3:22-23",
    verseText: "Bunătățile Domnului nu s-au sfârșit, îndurările Lui nu sunt la capăt, ci se înnoiesc în fiecare dimineață. Și credincioșia Ta este atât de mare!",
    meditation:
      "Sunt la doar câteva rânduri după versetul de ieri, în aceeași carte și în același om. Așa arată credința reală: plângerea și nădejdea stau alături, uneori în aceeași zi. Nu trebuie să alegi doar una.",
    question: "Poți ține împreună durerea și încrederea?",
    prayer: "Doamne, mă doare și totuși cred că îndurările Tale se înnoiesc. Amin.",
    step: "Mâine dimineață, înainte de orice, spune versetul ăsta.",
  },
  {
    id: "dev_220",
    dayNumber: 220,
    theme: LUNA_8,
    axis: "living_faith",
    verseRef: "Isaia 45:15",
    verseText: "Dar Tu ești un Dumnezeu care Te ascunzi, Tu, Dumnezeul lui Israel, Mântuitorule!",
    meditation:
      "Versetul spune două lucruri odată: Te ascunzi și ești Mântuitor. Ascunderea Lui nu e ostilitate. Sunt lucruri pe care Dumnezeu le face fără să le anunțe și pe care le vezi abia după ani.",
    question: "Când ți-ai dat seama, târziu, că El lucra?",
    prayer: "Doamne, chiar și ascuns, tot Mântuitor ești. Amin.",
    step: "Notează un lucru din trecut pe care l-ai înțeles abia după mult timp.",
  },
  {
    id: "dev_221",
    dayNumber: 221,
    theme: LUNA_8,
    axis: "living_faith",
    verseRef: "Isaia 55:8-9",
    verseText: "„Căci gândurile Mele nu sunt gândurile voastre și căile voastre nu sunt căile Mele”, zice Domnul.",
    meditation:
      "Versetul ăsta e folosit adesea ca să închidă gura celui îndurerat. Dar el nu spune că Dumnezeu e capricios, ci că gândește mai sus — iar contextul vorbește despre iertare, nu despre distanță. Un Dumnezeu pe care L-ai putea înțelege complet ar fi de mărimea minții tale.",
    question: "Ai nevoie de un Dumnezeu pe care să-L înțelegi sau de unul în care să te încrezi?",
    prayer: "Doamne, nu înțeleg. Dar nu vreau un Dumnezeu cât mintea mea. Amin.",
    step: "Renunță azi să mai ceri explicația și cere doar puterea de a merge mai departe.",
  },
  {
    id: "dev_222",
    dayNumber: 222,
    theme: LUNA_8,
    axis: "living_faith",
    verseRef: "Deuteronom 29:29",
    verseText: "Lucrurile ascunse sunt ale Domnului Dumnezeului nostru, iar lucrurile descoperite sunt ale noastre și ale copiilor noștri, pe vecie, ca să împlinim toate cuvintele legii acesteia.",
    meditation:
      "Există două categorii și pacea se găsește când nu le amesteci. Multă frământare vine din încercarea de a locui în prima categorie. Ai îndeajuns de lucru cu ce ți-a fost descoperit.",
    question: "Ce încerci să afli, deși nu ți-a fost dat să știi?",
    prayer: "Doamne, las la Tine ce e ascuns. Îmi văd de ce mi-ai spus limpede. Amin.",
    step: "Scrie o întrebare la care nu vei primi răspuns și las-o, pe hârtie, în grija Lui.",
  },
  {
    id: "dev_223",
    dayNumber: 223,
    theme: LUNA_8,
    axis: "living_faith",
    verseRef: "Ioan 11:6",
    verseText: "Deci, când a auzit că Lazăr este bolnav, a mai zăbovit două zile în locul în care era.",
    meditation:
      "Versetul dinainte spune că Isus îi iubea. Deci întârzierea Lui n-a fost lipsă de dragoste — textul le pune intenționat una lângă alta. Cea mai grea lecție a lunii ăsteia e că iubirea Lui și întârzierea Lui pot sta împreună.",
    question: "Ai crezut că, dacă întârzie, înseamnă că nu-I pasă?",
    prayer: "Doamne, mă iubești și totuși întârzii. Ajută-mă să țin amândouă. Amin.",
    step: "Citește azi Ioan 11, primele 16 versete.",
  },
  {
    id: "dev_224",
    dayNumber: 224,
    theme: LUNA_8,
    axis: "living_faith",
    verseRef: "Ioan 11:21",
    verseText: "Marta a zis lui Isus: „Doamne, dacă ai fi fost aici, n-ar fi murit fratele meu!”",
    meditation:
      "Marta Îi spune în față exact reproșul ei, iar Isus n-o ceartă. Sora ei, Maria, spune peste câteva versete același lucru. Se pare că e loc, în prietenia cu El, și pentru propoziția „dacă ai fi fost aici”.",
    question: "Care e „dacă ai fi fost aici” din viața ta?",
    prayer: "Doamne, unde ai fost atunci? Îți spun asta în față. Amin.",
    step: "Spune-I azi reproșul tău și rămâi în liniște după aceea.",
  },
  {
    id: "dev_225",
    dayNumber: 225,
    theme: LUNA_8,
    axis: "living_faith",
    verseRef: "Ioan 11:35",
    verseText: "Isus plângea.",
    meditation:
      "Știa că peste câteva minute îl va învia pe Lazăr și tot a plâns. Deci Dumnezeu nu trece peste durerea ta doar pentru că știe sfârșitul. Nu îți cere să sari peste jale.",
    question: "Te-a grăbit cineva să treci peste o durere?",
    prayer: "Doamne, mulțumesc că plângi cu mine. Amin.",
    step: "Dă-ți azi voie să fii trist, fără să te justifici.",
  },
  {
    id: "dev_226",
    dayNumber: 226,
    theme: LUNA_8,
    axis: "living_faith",
    verseRef: "Ioan 11:40",
    verseText: "Isus i-a zis: „Nu ți-am spus că, dacă vei crede, vei vedea slava lui Dumnezeu?”",
    meditation:
      "Ordinea e invers decât am vrea: întâi crezi, apoi vezi. Marta a trebuit să accepte să fie ridicată piatra înainte să se întâmple ceva. Ascultarea vine adesea înaintea dovezii.",
    question: "Ce piatră ți-a cerut să ridici, înainte să-ți arate ceva?",
    prayer: "Doamne, cred înainte să văd. Amin.",
    step: "Fă azi lucrul pe care știi că ți l-a cerut, chiar dacă încă nu vezi rostul.",
  },
  {
    id: "dev_227",
    dayNumber: 227,
    theme: LUNA_8,
    axis: "living_faith",
    verseRef: "Marcu 15:34",
    verseText: "Și în ceasul al nouălea, Isus a strigat cu glas tare: „Eloi, Eloi, Lama Sabactani?”, care, tălmăcit, înseamnă: „Dumnezeul Meu, Dumnezeul Meu, pentru ce M-ai părăsit?”",
    meditation:
      "A fost o tăcere reală, nu închipuită, și El a suportat-o în locul tău. De aceea, orice ar însemna tăcerea pe care o trăiești tu, nu înseamnă respingere. Cel care a fost respins în locul tău a fost El.",
    question: "Ce schimbă asta în felul în care îți citești tăcerea?",
    prayer: "Doamne Isuse, Tu ai strigat asta ca eu să nu fiu niciodată părăsit. Amin.",
    step: "Citește azi rar Marcu 15 și oprește-te la versetul 34.",
  },
  {
    id: "dev_228",
    dayNumber: 228,
    theme: LUNA_8,
    axis: "living_faith",
    verseRef: "Luca 23:46",
    verseText: "Isus a strigat cu glas tare: „Tată, în mâinile Tale Îmi încredințez duhul!” Și când a zis aceste vorbe, Și-a dat duhul.",
    meditation:
      "După strigătul de părăsire vine predarea. Îi spune iar „Tată”, deși cerul tăcuse ore în șir. E cel mai curat model de încredere: te lași în mâinile Cuiva care nu ți-a răspuns încă.",
    question: "Ce ai putea lăsa azi în mâinile Lui, fără să ai un răspuns?",
    prayer: "Tată, în mâinile Tale îmi las viața și așteptarea. Amin.",
    step: "Spune propoziția asta înainte de culcare, cu numele lucrului tău în ea.",
  },
  {
    id: "dev_229",
    dayNumber: 229,
    theme: LUNA_8,
    axis: "living_faith",
    verseRef: "Matei 27:61",
    verseText: "Maria Magdalena și cealaltă Marie erau acolo și ședeau în fața mormântului.",
    meditation:
      "Între cruce și înviere a fost o zi întreagă în care nu s-a întâmplat nimic. Ele nu știau că e sâmbătă; credeau că e sfârșitul. Poate și tu ești într-o sâmbătă, nu într-un final.",
    question: "Dacă ziua ta de azi ar fi o sâmbătă, ce s-ar schimba?",
    prayer: "Doamne, dacă asta e sâmbăta mea, ajută-mă să rămân lângă mormânt. Amin.",
    step: "Nu lua azi nicio decizie definitivă despre credința ta. Așteaptă dimineața.",
  },
  {
    id: "dev_230",
    dayNumber: 230,
    theme: LUNA_8,
    axis: "living_faith",
    verseRef: "Psalmul 30:5",
    verseText: "Căci mânia Lui ține numai o clipă, dar îndurarea Lui ține toată viața: seara vine plânsul, iar dimineața, veselia.",
    meditation:
      "Psalmul nu spune cât ține noaptea. Spune doar că dimineața există. Pentru un om în așteptare, asta nu e puțin: e diferența dintre o noapte și o veșnicie.",
    question: "Ai început să crezi că noaptea ta nu se mai termină?",
    prayer: "Doamne, nu știu cât mai e. Dar știu că vine dimineața. Amin.",
    step: "Fă azi un lucru care presupune că vei mai fi aici mâine.",
  },
  {
    id: "dev_231",
    dayNumber: 231,
    theme: LUNA_8,
    axis: "living_faith",
    verseRef: "Psalmul 40:1",
    verseText: "Îmi pusesem nădejdea în Domnul, și El S-a plecat spre mine, mi-a ascultat strigătele.",
    meditation:
      "În ebraică, expresia e mai apăsată: am așteptat așteptând. David scrie versetul ăsta după, nu în timpul așteptării. E o mărturie a cuiva care a ieșit din groapă și își amintește cât a durat.",
    question: "Cine ți-ar putea povesti cum a fost așteptarea lui?",
    prayer: "Doamne, aștept așteptând. Pleacă-Te spre mine. Amin.",
    step: "Întreabă azi un creștin mai în vârstă despre o perioadă în care Dumnezeu a tăcut.",
  },
  {
    id: "dev_232",
    dayNumber: 232,
    theme: LUNA_8,
    axis: "living_faith",
    verseRef: "Psalmul 77:19",
    verseText: "Ți-ai croit un drum prin mare, o cărare prin apele cele mari, și nu Ți s-au mai cunoscut urmele.",
    meditation:
      "Dumnezeu a mers înaintea poporului prin mare, dar apa n-a păstrat urmele pașilor. Așa arată uneori lucrarea Lui: e reală, dar nu lasă dovezi vizibile. Faptul că nu vezi urme nu înseamnă că n-a trecut pe acolo.",
    question: "Cauți urme sau Îl cauți pe El?",
    prayer: "Doamne, ai trecut prin apele mele chiar dacă nu văd urme. Amin.",
    step: "Amintește-ți azi o eliberare din trecutul tău pe care n-o poți explica.",
  },
  {
    id: "dev_233",
    dayNumber: 233,
    theme: LUNA_8,
    axis: "living_faith",
    verseRef: "Psalmul 77:11",
    verseText: "Dar tot voi lăuda lucrările Domnului, căci îmi aduc aminte de minunile Tale de odinioară.",
    meditation:
      "Psalmistul iese din disperare printr-un act de memorie, nu printr-o revelație nouă. Când prezentul tace, te întorci la ce a făcut deja. De asta ținem Ebenezerele: 1 Samuel 7:12, piatra care spune „până aici Domnul ne-a ajutat”.",
    question: "Care e piatra ta de aducere aminte?",
    prayer: "Doamne, îmi aduc aminte ce ai făcut. Asta mă ține azi. Amin.",
    step: "Recitește-ți azi însemnările vechi sau spune cuiva o minune din trecutul tău.",
  },
  {
    id: "dev_234",
    dayNumber: 234,
    theme: LUNA_8,
    axis: "living_faith",
    verseRef: "Geneza 15:5-6",
    verseText: "Și după ce l-a dus afară, i-a zis: „Uită-te spre cer și numără stelele, dacă poți să le numeri.” Și i-a zis: „Așa va fi sămânța ta.” Avram a crezut pe Domnul, și Domnul i-a socotit lucrul acesta ca neprihănire.",
    meditation:
      "Între promisiune și împlinire au trecut vreo douăzeci și cinci de ani. Dumnezeu i-a dat un cer plin de stele și nimic altceva. Sunt perioade în care tot ce ai e un cuvânt primit demult.",
    question: "Ce cuvânt ți-a dat Dumnezeu și încă nu s-a împlinit?",
    prayer: "Doamne, mă țin de ce mi-ai spus, chiar dacă a trecut mult. Amin.",
    step: "Ieși azi afară seara și uită-te câteva minute la cer.",
  },
  {
    id: "dev_235",
    dayNumber: 235,
    theme: LUNA_8,
    axis: "living_faith",
    verseRef: "Evrei 11:1",
    verseText: "Și credința este o încredere neclintită în lucrurile nădăjduite, o puternică încredințare despre lucrurile care nu se văd.",
    meditation:
      "Definiția asta presupune că lucrurile nu se văd. Credința nu e pentru zilele în care ai dovezi — atunci n-ai avea nevoie de ea. Tăcerea nu e dușmanul credinței, ci terenul ei.",
    question: "Ți-ai imaginat că o credință sănătoasă nu are perioade oarbe?",
    prayer: "Doamne, cred în ce nu se vede. Întărește-mi încrederea. Amin.",
    step: "Citește azi Evrei 11 și observă câți au așteptat mult.",
  },
  {
    id: "dev_236",
    dayNumber: 236,
    theme: LUNA_8,
    axis: "living_faith",
    verseRef: "Evrei 11:13",
    verseText: "În credință au murit toți aceștia, fără să fi căpătat lucrurile făgăduite, ci doar le-au văzut și le-au urat de bine de departe, mărturisind că sunt străini și călători pe pământ.",
    meditation:
      "E un verset cinstit și greu: unii oameni credincioși nu au primit în viața asta ce li se promisese. Biblia nu ascunde asta ca să ne țină motivați. Și totuși îi numește oameni de credință, nu oameni înșelați.",
    question: "Ai putea rămâne credincios chiar dacă nu primești în viața asta?",
    prayer: "Doamne, chiar dacă nu văd împlinirea, rămân al Tău. Amin.",
    step: "Spune azi lui Dumnezeu că rămâi, indiferent de răspuns.",
  },
  {
    id: "dev_237",
    dayNumber: 237,
    theme: LUNA_8,
    axis: "living_faith",
    verseRef: "1 Împărați 19:12",
    verseText: "Și după cutremurul de pământ, a venit un foc. Domnul nu era în focul acela. Și după foc, a venit un susur blând și subțire.",
    meditation:
      "Dumnezeu nu era în vânt, nici în cutremur, nici în foc — lucruri pe care nu aveai cum să le ratezi. A vorbit într-o șoaptă. Poate nu tace; poate vorbește mai încet decât zăngănitul din jurul tău.",
    question: "Câtă liniște ai într-o zi obișnuită?",
    prayer: "Doamne, fă-mă să aud și șoapta. Amin.",
    step: "Petrece azi zece minute fără sunet: fără muzică, fără telefon, fără voci.",
  },
  {
    id: "dev_238",
    dayNumber: 238,
    theme: LUNA_8,
    axis: "living_faith",
    verseRef: "Ioan 16:12",
    verseText: "Mai am să vă spun multe lucruri, dar acum nu le puteți purta.",
    meditation:
      "Uneori Dumnezeu tace din milă. Sunt adevăruri care, spuse prea devreme, ar strivi un om. Tăcerea Lui poate fi răbdare, nu indiferență.",
    question: "Ai putea purta acum tot răspunsul, dacă ți l-ar da?",
    prayer: "Doamne, spune-mi cât pot duce. Am încredere în măsura Ta. Amin.",
    step: "Mulțumește-I azi pentru un lucru pe care nu ți l-a spus încă.",
  },
  {
    id: "dev_239",
    dayNumber: 239,
    theme: LUNA_8,
    axis: "living_faith",
    verseRef: "2 Corinteni 5:7",
    verseText: "pentru că umblăm prin credință, nu prin vedere.",
    meditation:
      "Cuvântul important e „umblăm”: se merge, nu se stă pe loc până se face lumină. Candela de la Psalmul 119:105 luminează un pas, nu tot drumul. În așteptare, ascultarea înseamnă pur și simplu următorul pas.",
    question: "Care e următorul pas pe care îl știi, chiar dacă restul e întuneric?",
    prayer: "Doamne, merg cu ce văd. Un pas. Amin.",
    step: "Fă azi acel singur pas și nu-ți mai cere ție tot drumul.",
  },
  {
    id: "dev_240",
    dayNumber: 240,
    theme: LUNA_8,
    axis: "living_faith",
    verseRef: "Ioan 20:29",
    verseText: "„Tomo”, i-a zis Isus, „pentru că M-ai văzut, ai crezut. Ferice de cei ce n-au văzut, și au crezut.”",
    meditation:
      "Isus i-a spus asta lui Toma după ce i-a arătat rănile — deci nu e o mustrare, ci o binecuvântare pentru cei ca noi. Se încheie luna cea mai grea a anului și nu ți s-a promis niciun răspuns până azi. Ai rămas, și asta e credință. De luna viitoare vorbim despre ce crește pe nevăzut — exact în pământul ăsta tăcut.",
    question: "Ce ai învățat în treizeci de zile de așteptare?",
    prayer: "Doamne, n-am văzut și totuși cred. Ține-mă așa. Amin.",
    step: "Recitește ce ai scris în ziua 216 și adaugă un rând, orice s-ar fi întâmplat.",
  },
]
