// Devoțional, luna 4: „Odihna” (docs/27 §2.4, axa emotional_peace).
//
// Regula lunii: odihna nu e recompensa de după muncă, ci un dar dat înaintea ei
// (omul a fost făcut în ziua a șasea și prima lui zi întreagă a fost o zi de
// odihnă). Luna 3 a vorbit despre frică; frica și graba sunt aceeași boală.
//
// Conținut ORIGINAL Emanus (docs/27 §1.2). Versete: Cornilescu (domeniu public).
import type { DevotionalDay } from "./devotional.js"

const LUNA_4 = "Odihna"

export const DEVOTIONAL_DAYS_LUNA_4: DevotionalDay[] = [
  {
    id: "dev_091",
    dayNumber: 91,
    theme: LUNA_4,
    axis: "emotional_peace",
    verseRef: "Geneza 2:2",
    verseText: "În ziua a șaptea, Dumnezeu Și-a sfârșit lucrarea pe care o făcuse; și în ziua a șaptea S-a odihnit de toată lucrarea Lui.",
    meditation:
      "Dumnezeu nu Se odihnește pentru că obosește. Se odihnește pentru că lucrarea era terminată — și pune odihna în ritmul lumii înainte ca omul să fi muncit ceva. Prima zi întreagă a lui Adam a fost o zi de odihnă, nu una de producție.",
    question: "Odihna ta e un dar primit sau o pauză pe care crezi că trebuie să ți-o meți?",
    prayer: "Doamne, Tu Te-ai odihnit primul. Învață-mă să nu mă simt vinovat când mă opresc. Amin.",
    step: "Oprește-te azi cincisprezece minute fără să produci nimic și fără să te justifici.",
  },
  {
    id: "dev_092",
    dayNumber: 92,
    theme: LUNA_4,
    axis: "emotional_peace",
    verseRef: "Exod 20:8-9",
    verseText: "Adu-ți aminte de ziua de odihnă, ca s-o sfințești. Să lucrezi șase zile și să-ți faci lucrul tău.",
    meditation:
      "E singura poruncă din zece care începe cu „adu-ți aminte”, pentru că e singura pe care o uiți fără să te simți vinovat. Nimeni nu se laudă că a furat; mulți se laudă că n-au avut o zi liberă de luni de zile.",
    question: "Când ai avut ultima dată o zi în care nu ai lucrat și nu te-ai simțit vinovat?",
    prayer: "Doamne, iartă-mi mândria de a nu mă opri niciodată. Amin.",
    step: "Alege în calendar, azi, o zi din săptămâna care vine și scrie pe ea un singur cuvânt: odihnă.",
  },
  {
    id: "dev_093",
    dayNumber: 93,
    theme: LUNA_4,
    axis: "emotional_peace",
    verseRef: "Marcu 2:27",
    verseText: "Sabatul a fost făcut pentru om, iar nu omul pentru Sabat.",
    meditation:
      "Isus a spus asta unor oameni care făcuseră din odihnă încă o muncă, cu reguli și note de trecere. Se poate obosi și din religie. Odihna ți-a fost dată ție; nu e un examen la care să ieși bine.",
    question: "Ai transformat vreun lucru bun — rugăciune, post, program — într-o obligație care te apasă?",
    prayer: "Doamne, nu vreau să Te slujesc obosit și supărat. Adu-mi înapoi bucuria. Amin.",
    step: "Renunță azi la o regulă pe care ți-ai pus-o singur și pe care Dumnezeu nu ți-a cerut-o.",
  },
  {
    id: "dev_094",
    dayNumber: 94,
    theme: LUNA_4,
    axis: "emotional_peace",
    verseRef: "Matei 11:28",
    verseText: "Veniți la Mine, toți cei trudiți și încărcați, și Eu vă voi da odihnă.",
    meditation:
      "Sunt două feluri de oboseală în verset: „trudiți”, adică cei care muncesc, și „încărcați”, adică cei cărora li s-a pus ceva în spate. Isus nu cere să alegi categoria. Cere doar să vii cu ea.",
    question: "Oboseala ta vine din ce faci sau din ce duci?",
    prayer: "Doamne, vin obosit. Nu vin refacut, ca să-ți fie mai ușor. Amin.",
    step: "Spune-I azi, într-o propoziție, de ce anume ești obosit. Fii exact.",
  },
  {
    id: "dev_095",
    dayNumber: 95,
    theme: LUNA_4,
    axis: "emotional_peace",
    verseRef: "Psalmul 23:2",
    verseText: "El mă paște în pășuni verzi și mă duce la ape de odihnă.",
    meditation:
      "O oaie nu se culcă dacă Îi e foame, dacă se teme sau dacă e învălmășeală în turmă. Faptul că stă jos e dovada că Păstorul și-a făcut treaba. Odihna ta e, de cele mai multe ori, rezultatul încrederii, nu al circumstanțelor.",
    question: "Ce anume te ține în picioare, deși ai putea sta jos?",
    prayer: "Doamne, du-mă la ape liniștite. Nu știu singur drumul spre ele. Amin.",
    step: "Fă azi un lucru care te liniștește și pe care l-ai amânat pentru că „nu e productiv”.",
  },
  {
    id: "dev_096",
    dayNumber: 96,
    theme: LUNA_4,
    axis: "emotional_peace",
    verseRef: "Psalmul 127:2",
    verseText: "Degeaba vă sculați de dimineață și vă culcați târziu, ca să mâncați o pâine câștigată cu durere; căci preaiubiților Lui El le dă pâine ca în somn.",
    meditation:
      "Psalmul nu condamnă munca, ci munca disperată — aceea care crede că totul depinde de câte ore stai treaz. Dumnezeu lucrează și în orele în care tu dormi. Somnul e un act de credință: recunoști că lumea merge și fără tine câteva ore.",
    question: "Cât din programul tău vine din hotea de a nu rămâne în urmă?",
    prayer: "Doamne, nu totul depinde de mine. Pot să dorm. Amin.",
    step: "Culcă-te azi cu treizeci de minute mai devreme, chiar dacă mai era ceva de făcut.",
  },
  {
    id: "dev_097",
    dayNumber: 97,
    theme: LUNA_4,
    axis: "emotional_peace",
    verseRef: "Marcu 6:31",
    verseText: "Veniți singuri la o parte, într-un loc pustiu, și odihniți-vă puțin.",
    meditation:
      "Isus spune asta ucenicilor exact când lucrarea mergea cel mai bine și lumea venea val-vartej. Nu i-a trimis la odihnă când nu mai avea cine să ceară ceva de la ei, pentru că ziua aceea nu vine niciodată.",
    question: "Aștepți să se liniștească lucrurile ca să te odihnești?",
    prayer: "Doamne, mă tragi deoparte. Nu mă lasă să confund folositor cu sănătos. Amin.",
    step: "Ia-ți azi treizeci de minute în care nu ești disponibil pentru nimeni. Spune asta din timp, ca să nu minți.",
  },
  {
    id: "dev_098",
    dayNumber: 98,
    theme: LUNA_4,
    axis: "emotional_peace",
    verseRef: "Evrei 4:9-10",
    verseText: "Rămâne dar o odihnă ca cea de Sabat pentru poporul lui Dumnezeu. Fiindcă cine intră în odihna Lui se odihnește și el de lucrările lui.",
    meditation:
      "Odihna de care vorbește Evrei nu e o zi liberă, ci încetarea efortului de a-ți câștiga locul înaintea lui Dumnezeu. Cine a înțeles că nu are ce adăuga la lucrarea lui Hristos poate lucra mult, dar nu mai lucrează din frică.",
    question: "Mai încerci să adaugi ceva la o lucrare terminată?",
    prayer: "Doamne, intru în odihna Ta. Nu mai am de dovedit nimic. Amin.",
    step: "Fă azi ceva bun și, la final, spune-ți: „nu asta mă ține în fața lui Dumnezeu”.",
  },
  {
    id: "dev_099",
    dayNumber: 99,
    theme: LUNA_4,
    axis: "emotional_peace",
    verseRef: "Exod 33:14",
    verseText: "Domnul a răspuns: „Voi merge Eu Însumi cu tine și îți voi da odihnă.”",
    meditation:
      "Moise ceruse îndrumare și a primit însotire. Observă legătura: odihna vine în același pachet cu prezența. Nu te odihnești pentru că ți s-a explicat drumul, ci pentru că nu mergi singur pe el.",
    question: "Ce ai vrea să-ți explice Dumnezeu înainte să mergi mai departe?",
    prayer: "Doamne, dacă nu-mi explici, dar vii cu mine, e destul. Amin.",
    step: "Începe azi un lucru pentru care nu ai toate răspunsurile.",
  },
  {
    id: "dev_100",
    dayNumber: 100,
    theme: LUNA_4,
    axis: "emotional_peace",
    verseRef: "Psalmul 46:10",
    verseText: "Opriți-vă și să știți că Eu sunt Dumnezeu.",
    meditation:
      "Versetul e spus într-un psalm despre război și prăbușire, nu într-unul despre vacanță. „Opriți-vă” înseamnă, în original, și „lăsați armele jos”. Sunt lupte în care singurul lucru de făcut e să încetezi să te mai zbați.",
    question: "În ce luptă te zbați de prea mult timp?",
    prayer: "Doamne, las armele jos. Tu ești Dumnezeu, nu eu. Amin.",
    step: "Stai azi în liniște trei minute, fără să ceri nimic. Doar atât.",
  },
  {
    id: "dev_101",
    dayNumber: 101,
    theme: LUNA_4,
    axis: "emotional_peace",
    verseRef: "Isaia 30:15",
    verseText: "În liniște și odihnă va fi mântuirea voastră, în liniștire și încredere va fi tăria voastră.",
    meditation:
      "Versetul se încheie trist: „dar n-ați voit”. Israel a preferat să fugă după alianțe și cai egipteni. E mai ușor să alergi decât să aștepți, iar graba trece adesea drept credincioșie.",
    question: "Ce „soluție” cauți acum, doar ca să nu stai liniștit în așteptare?",
    prayer: "Doamne, vreau liniștea Ta, nu încă o alergare. Amin.",
    step: "Amână azi o acțiune pe care ai face-o doar ca să simți că faci ceva.",
  },
  {
    id: "dev_102",
    dayNumber: 102,
    theme: LUNA_4,
    axis: "emotional_peace",
    verseRef: "Luca 10:41-42",
    verseText: "Marto, Marto, pentru multe lucruri te îngrijorezi și te frămânți tu, dar un singur lucru trebuiește.",
    meditation:
      "Marta făcea un lucru bun și necesar: gătea pentru Isus. Nu e o poveste despre leneși și harnici. E despre cum poți fi atât de ocupat cu slujirea cuiva încât să nu mai stai cu El.",
    question: "Ce faci pentru Dumnezeu în loc să stai cu El?",
    prayer: "Doamne, iartă-mă că Te slujesc de la distanță. Stau jos. Amin.",
    step: "Citește azi cinci minute din Evanghelii fără să pregătești nimic pentru nimeni.",
  },
  {
    id: "dev_103",
    dayNumber: 103,
    theme: LUNA_4,
    axis: "emotional_peace",
    verseRef: "Psalmul 131:2",
    verseText: "Dimpotrivă, sufletul îmi este liniștit și potolit, ca un copil înțărcat, care stă lângă mama sa.",
    meditation:
      "Un copil la sân stă liniștit pentru că primește; unul înțărcat stă liniștit pentru că e cu mama lui. E o credință mai matură: nu vii doar ca să iei, vii ca să fii aproape.",
    question: "Te apropii de Dumnezeu doar când ai nevoie de ceva?",
    prayer: "Doamne, azi nu cer nimic. Stau lângă Tine. Amin.",
    step: "Fă azi o rugăciune fără nicio cerere în ea.",
  },
  {
    id: "dev_104",
    dayNumber: 104,
    theme: LUNA_4,
    axis: "emotional_peace",
    verseRef: "Eclesiastul 4:6",
    verseText: "Mai bine o mână plină de odihnă decât amândoi pumnii plini de trudă și goană după vânt.",
    meditation:
      "Solomon nu spune că lenea e bună, ci că există o muncă din care nu rămâne nimic. „Goană după vânt” e imaginea perfectă a omului care aleargă mult și strânge în pumn aer.",
    question: "Ce faci mult și nu rămâne nimic din asta?",
    prayer: "Doamne, arată-mi ce e goană după vânt în viața mea. Am curajul să văd. Amin.",
    step: "Tăie azi de pe listă un lucru care nu contează cu adevărat. Chiar tăie-l.",
  },
  {
    id: "dev_105",
    dayNumber: 105,
    theme: LUNA_4,
    axis: "emotional_peace",
    verseRef: "Ieremia 6:16",
    verseText: "Întrebați care este calea cea bună și umblați pe ea, și veți găsi odihnă pentru sufletele voastre.",
    meditation:
      "Odihna e legată aici de a merge pe drumul potrivit, nu de a te opri. Un om care trăiește împotriva a ceea ce crede nu se odihnește niciodată, oricât doarme. Oboseala are și o cauză morală, nu doar una de program.",
    question: "E vreun lucru în viața ta care te obosește pentru că știi că nu e drept?",
    prayer: "Doamne, arată-mi calea cea bună și dă-mi curaj să mă întorc pe ea. Amin.",
    step: "Îndreaptă azi un lucru mic care te roade de mult. Un mesaj, o scuză, o plată.",
  },
  {
    id: "dev_106",
    dayNumber: 106,
    theme: LUNA_4,
    axis: "emotional_peace",
    verseRef: "Matei 6:11",
    verseText: "Pâinea noastră cea de toate zilele dă-ne-o nouă astăzi.",
    meditation:
      "Isus ne-a învățat să cerem porția unei zile, nu depozitul unui an. Cine cere zilnic rămâne în legătură zilnic. Un om cu hambarele pline uită repede de la cine are pâinea.",
    question: "Ți-ai dori de la Dumnezeu siguranță pe un an, ca să nu mai depinzi?",
    prayer: "Doamne, dă-mi ce îmi trebuie azi. Mâine vin iar. Amin.",
    step: "Cere-I azi un singur lucru, doar pentru ziua asta.",
  },
  {
    id: "dev_107",
    dayNumber: 107,
    theme: LUNA_4,
    axis: "emotional_peace",
    verseRef: "Exod 16:4",
    verseText: "Poporul va ieși și va strânge, zi de zi, cont cât îi trebuie pentru fiecare zi.",
    meditation:
      "Cine strângea mai multă mană „pentru orice eventualitate” o găsea a doua zi stricată. Dumnezeu a legat intenționat hrana de o singură zi, ca să învețe un popor de foști sclavi că nu mai trebuie să se teamă de mâine. Devoționalul acesta funcționează la fel: ziua lipsită nu se recuperează.",
    question: "Ce încerci să depozitezi pentru o zi care poate nu vine?",
    prayer: "Doamne, mana de azi e pentru azi. Nu strâng din frică. Amin.",
    step: "Renunță azi la o „rezervă” pe care o ții doar ca să te simți în siguranță.",
  },
  {
    id: "dev_108",
    dayNumber: 108,
    theme: LUNA_4,
    axis: "emotional_peace",
    verseRef: "Psalmul 4:8",
    verseText: "Eu mă culc și adorm în pace, căci numai Tu, Doamne, îmi dai liniștea.",
    meditation:
      "David a scris asta în fugă, cu oameni care îl vânau. Somnul lui nu venea din siguranța locului, ci din încrederea în Cel care păzește locul. Uneori cea mai curajoasă faptă de credință dintr-o zi grea e să închizi ochii.",
    question: "Ce faci, de obicei, în ultimele minute înainte de somn?",
    prayer: "Doamne, mă culc. Tu rămâi treaz. Amin.",
    step: "Nu duce azi telefonul în pat. Ultimul lucru din zi să fie o propoziție spusă Lui.",
  },
  {
    id: "dev_109",
    dayNumber: 109,
    theme: LUNA_4,
    axis: "emotional_peace",
    verseRef: "1 Împărați 19:5-6",
    verseText: "Un înger l-a atins și i-a zis: „Scoală-te și mănâncă.”... A mâncat și a băut, apoi s-a culcat din nou.",
    meditation:
      "Ilie voia să moară. Dumnezeu nu i-a făcut întâi teologie și nu l-a certat: l-a lăsat să doarmă și i-a dat de mâncare, de două ori. Sunt zile în care lucrul cel mai duhovnicesc pe care îl poți face e să mănânci ceva cald și să dormi.",
    question: "Cât din descurajarea ta de acum e, de fapt, oboseală și foame?",
    prayer: "Doamne, ai grijă și de trupul meu, nu doar de sufletul meu. Amin.",
    step: "Fă azi un lucru simplu pentru corpul tău: o masă ca lumea, un somn, o plimbare.",
  },
  {
    id: "dev_110",
    dayNumber: 110,
    theme: LUNA_4,
    axis: "emotional_peace",
    verseRef: "Marcu 4:38",
    verseText: "Și El dormea la cârmă pe căpătâi.",
    meditation:
      "Isus dormea în furtună. Nu pentru că nu știa ce se întâmplă, ci pentru că Știa unde e Tatăl. Somnul Lui în barcă e cea mai tăcută predică despre încredere din Evanghelii.",
    question: "Ce ar trebui să fie adevărat ca să poți dormi în furtuna ta?",
    prayer: "Doamne, învață-mă să dorm în barcă. Amin.",
    step: "Când te trezești azi noapte cu gânduri, spune o dată: „El e în barcă” și culcă-te la loc.",
  },
  {
    id: "dev_111",
    dayNumber: 111,
    theme: LUNA_4,
    axis: "emotional_peace",
    verseRef: "Psalmul 116:7",
    verseText: "Întoarce-te, suflete, la odihna ta, căci Domnul ți-a făcut bine!",
    meditation:
      "Psalmistul își vorbește lui însuși — își cheamă sufletul înapoi, ca pe un copil plecat de acasă. Uneori nu ai nevoie de o revelație nouă, ci să-ți amintești ce știi deja și să te întorci acolo.",
    question: "De la ce ai plecat și știi că ar trebui să te întorci?",
    prayer: "Doamne, mă întorc. Mi-ai făcut bine și uitasem. Amin.",
    step: "Vorbește-ți azi o dată, cu voce tare, cum i-ai vorbi unui prieten obosit.",
  },
  {
    id: "dev_112",
    dayNumber: 112,
    theme: LUNA_4,
    axis: "emotional_peace",
    verseRef: "Ioan 15:5",
    verseText: "Cine rămâne în Mine și în cine rămân Eu aduce multă roadă; căci despărțiți de Mine nu puteți face nimic.",
    meditation:
      "O ramură nu se străduiește să facă struguri; rămâne legată și rodul vine. Cuvântul cheie nu e „munciți”, ci „rămâneți”. Multe epuizări creștine vin din încercarea de a produce rod prin efort, rămânând rupt de tulpină.",
    question: "Produci sau rămâi?",
    prayer: "Doamne, sunt o ramură, nu o fabrică. Ține-mă legat de Tine. Amin.",
    step: "Înlocuiește azi o jumătate de oră de „treabă pentru Dumnezeu” cu o jumătate de oră cu El.",
  },
  {
    id: "dev_113",
    dayNumber: 113,
    theme: LUNA_4,
    axis: "emotional_peace",
    verseRef: "Psalmul 62:1",
    verseText: "Da, numai în Dumnezeu se încrede sufletul meu; de la El îmi vine ajutorul.",
    meditation:
      "„Numai” e cuvântul greu. Nu e rău să ai un plan de rezervă, dar e obositor să ai zece — pentru că fiecare trebuie ținut în viață. Odihna vine când nu mai întreții, în paralel, toate variantele.",
    question: "Câte planuri de rezervă ții în viață și cât te costă?",
    prayer: "Doamne, las jos variantele. Numai la Tine mă uit azi. Amin.",
    step: "Nu verifica azi de trei ori același lucru. O dată e destul.",
  },
  {
    id: "dev_114",
    dayNumber: 114,
    theme: LUNA_4,
    axis: "emotional_peace",
    verseRef: "Zaharia 4:6",
    verseText: "Lucrul acesta nu se va face nici prin putere, nici prin tărie, ci prin Duhul Meu, zice Domnul oștirilor.",
    meditation:
      "I s-a spus asta unui om care avea de reconstruit un templu cu resurse mizere. Dumnezeu nu i-a promis mai multă putere, ci o altă sursă. Când te uiți la ce ai de făcut și îți vine să renunți, poate calculezi cu puterea greșită.",
    question: "Ce lucru încerci să duci cu propria putere?",
    prayer: "Doamne, nu prin puterea mea. Dă-mi Duhul Tău pentru asta. Amin.",
    step: "Înainte de cel mai greu lucru de azi, oprește-te zece secunde și cere ajutor.",
  },
  {
    id: "dev_115",
    dayNumber: 115,
    theme: LUNA_4,
    axis: "emotional_peace",
    verseRef: "Psalmul 37:7",
    verseText: "Taci înaintea Domnului și nădăjduiește în El.",
    meditation:
      "E o tăcere activă, nu una îmbufnată. Psalmul continuă cu „nu te mânia pe cel ce izbutește” — deci tăcerea aceasta e antidotul pentru comparație. Cine se compară nu se odihnește niciodată, pentru că mereu e cineva mai înainte.",
    question: "Cine ți-a stricat ultima dată liniștea doar prin faptul că lui îi merge bine?",
    prayer: "Doamne, tac și aștept. Nu alerg după cursa altuia. Amin.",
    step: "Nu intra azi pe rețele o jumătate de zi. Comparația se hrănește de acolo.",
  },
  {
    id: "dev_116",
    dayNumber: 116,
    theme: LUNA_4,
    axis: "emotional_peace",
    verseRef: "Isaia 40:29",
    verseText: "El dă tărie celui obosit și mărește puterea celui ce cade în leșin.",
    meditation:
      "Dumnezeu dă putere celui obosit, nu celui odihnit. Deci nu trebuie să te refaci ca să fii de folos; oboseala e chiar condiția în care se dă tăria. Cei tineri se împiedică, spune versetul următor — puterea proprie e cea care se termină.",
    question: "Ceri putere sau înțelegere?",
    prayer: "Doamne, sunt la capăt. Dă-mi tărie, chiar așa obosit cum sunt. Amin.",
    step: "Cere-I azi putere pentru următoarea oră, nu pentru toată săptămâna.",
  },
  {
    id: "dev_117",
    dayNumber: 117,
    theme: LUNA_4,
    axis: "emotional_peace",
    verseRef: "Deuteronom 5:15",
    verseText: "Adu-ți aminte că și tu ai fost rob în țara Egiptului și Domnul Dumnezeul tău te-a scos din ea... de aceea ți-a poruncit Domnul să ții ziua de odihnă.",
    meditation:
      "Motivul odihnei e libertatea. Sclavul nu are voie să se oprească; omul liber, da. De fiecare dată când te oprești, spui cu trupul tău că nu mai ești în Egipt — și că valoarea ta nu se măsoară în producție.",
    question: "Cine sau ce te ține în ritm de sclav, deși nimeni nu te mai obligă?",
    prayer: "Doamne, m-ai scos din Egipt. Învață-mă să trăiesc ca un om liber. Amin.",
    step: "Spune azi nu la o singură cerere pe care ai fi acceptat-o din frică.",
  },
  {
    id: "dev_118",
    dayNumber: 118,
    theme: LUNA_4,
    axis: "emotional_peace",
    verseRef: "Matei 11:30",
    verseText: "Căci jugul Meu este bun și sarcina Mea este ușoară.",
    meditation:
      "„Bun” înseamnă, în original, și „potrivit” — un jug făcut pe măsura animalului, care nu-i roade gâtul. Dacă ceea ce duci în numele lui Dumnezeu te rănește, merită întrebat cine ți-a pus jugul acela.",
    question: "Ce duci acum și nu ți-a cerut El să duci?",
    prayer: "Doamne, ia de pe mine ce nu mi-ai dat Tu. Amin.",
    step: "Scrie tot ce duci acum și pune un semn lângă lucrurile pe care le-ai luat singur.",
  },
  {
    id: "dev_119",
    dayNumber: 119,
    theme: LUNA_4,
    axis: "emotional_peace",
    verseRef: "Evrei 4:11",
    verseText: "Să ne grăbim dar să intrăm în odihna aceasta.",
    meditation:
      "E o formulare ciudată dinadins: singura grabă recomandată în Biblie e graba spre odihnă. Odihna nu vine de la sine; e o ușă prin care trebuie să intri, adică o hotărâre, nu o stare de spirit.",
    question: "Ce decizie concretă ar însemna, pentru tine, „să intri”?",
    prayer: "Doamne, aleg odihna Ta. Nu o mai amân până termin totul. Amin.",
    step: "Pune azi în calendar, negru pe alb, o oră de odihnă săptămâna viitoare.",
  },
  {
    id: "dev_120",
    dayNumber: 120,
    theme: LUNA_4,
    axis: "emotional_peace",
    verseRef: "Isaia 32:18",
    verseText: "Poporul Meu va locui în locuința păcii, în case fără grijă și în adăposturi liniștite.",
    meditation:
      "Se încheie a patra lună și a doua pe axa păcii. Versetul privește înainte: nu tot ce ni s-a promis a venit încă. Dar cine învață acum să se oprească învață, de fapt, limba locului spre care merge. De luna viitoare vorbim despre iertare — nu se poate odihnă adevărată câtă vreme porți ranchiună.",
    question: "Ce s-a schimbat în ritmul tău în lunile astea două?",
    prayer: "Doamne, mulțumesc pentru liniștea pe care am învățat-o. Pregătește-mă pentru ce urmează. Amin.",
    step: "Recitește rândurile scrise în zilele 31, 60 și 90 și adaugă unul pentru luna asta.",
  },
]
