// Devoțional, luna 2: „Cine ești, pentru că El a făcut ce a făcut” (docs/27 §2.4).
//
// Luna 1 a spus CINE ești. Luna 2 spune DE CE e adevărat: nu pentru că te-ai
// schimbat, ci pentru o lucrare terminată în afara ta. De aceea aproape fiecare
// zi de aici stă pe un verb la trecut: a plătit, a șters, a isprăvit.
//
// Conținut ORIGINAL Emanus (docs/27 §1.2). Versete: Cornilescu VDC 1924
// (domeniu public), colaționate verset cu verset.
// Fișier separat de `devotional.ts` ca să nu rescriem luna 1 la fiecare adăugare.
import type { DevotionalDay } from "./devotional.js"

const LUNA_2 = "Cine ești, pentru că El a făcut ce a făcut"

export const DEVOTIONAL_DAYS_LUNA_2: DevotionalDay[] = [
  {
    id: "dev_032",
    dayNumber: 32,
    theme: LUNA_2,
    axis: "identity",
    verseRef: "Coloseni 1:13",
    verseText: "El ne-a izbăvit de sub puterea întunericului și ne-a strămutat în Împărăția Fiului dragostei Lui.",
    meditation:
      "„Strămutat” e un cuvânt de mutare, nu de vizită. Nu ești un om din întuneric care are voie să intre uneori la lumină; ai fost mutat cu acte cu tot. Iar mutarea a făcut-o El, nu tu — motiv pentru care nu poate fi anulată de o zi proastă de-a ta.",
    question: "Trăiești ca un om mutat definitiv sau ca unul venit în vizită, care se teme că va fi dat afară?",
    prayer: "Doamne, m-ai mutat Tu. Ajută-mă să nu mai trăiesc cu bagajul la ușă. Amin.",
    step: "Când te prinzi azi că te porți ca un musafir la Dumnezeu, spune-ți o dată: „locuiesc aici”.",
  },
  {
    id: "dev_033",
    dayNumber: 33,
    theme: LUNA_2,
    axis: "identity",
    verseRef: "Tit 3:5",
    verseText: "El ne-a mântuit nu pentru faptele făcute de noi în neprihănire, ci pentru îndurarea Lui, prin spălarea nașterii din nou și prin înnoirea făcută de Duhul Sfânt.",
    meditation:
      "Versetul taie exact lucrul de care ne agățăm: faptele noastre bune. Nu spune că sunt urâte, spune că nu ele au plătit. Dacă nu ele te-au adus înăuntru, nici lipsa lor nu te scoate afară.",
    question: "Ce faptă bună de-a ta folosești, fără să recunoști, ca dovadă că Dumnezeu ar trebui să te primească?",
    prayer: "Doamne, nu am plătit eu. Iartă-mi facturile pe care Ți le tot arăt. Amin.",
    step: "Fă azi un lucru bun și nu-l spune nimănui. Nici lui Dumnezeu, ca argument.",
  },
  {
    id: "dev_034",
    dayNumber: 34,
    theme: LUNA_2,
    axis: "identity",
    verseRef: "Efeseni 2:8-9",
    verseText: "Căci prin har ați fost mântuiți, prin credință. Și aceasta nu vine de la voi, ci este darul lui Dumnezeu. Nu prin fapte, ca să nu se laude nimeni.",
    meditation:
      "„Ca să nu se laude nimeni” înseamnă că sistemul a fost gândit dinadins să nu-ți lase loc de mândrie. Dar are un efect secundar pe care puțini îl văd: dacă nu ai cu ce te lăuda, nu ai nici cu ce te rușina. Cine n-a plătit nimic nu poate nici să piardă plata.",
    question: "Dacă mântuirea e dar, ce anume mai încerci să câștigi?",
    prayer: "Doamne, e dar. Învață-mă să primesc fără să încerc să plătesc pe urmă. Amin.",
    step: "Primește azi ceva de la cineva fără să dai nimic înapoi și fără să te scuzi.",
  },
  {
    id: "dev_035",
    dayNumber: 35,
    theme: LUNA_2,
    axis: "identity",
    verseRef: "2 Corinteni 5:21",
    verseText: "Pe Cel ce n-a cunoscut niciun păcat, El L-a făcut păcat pentru noi, ca noi să fim neprihănirea lui Dumnezeu în El.",
    meditation:
      "E un schimb, nu o reducere. El a luat ce era al tău, tu ai primit ce era al Lui. Asta înseamnă că, în ziua în care te simți cel mai murdar, statutul tău înaintea lui Dumnezeu e la fel ca în ziua în care te simți cel mai curat — pentru că nu al tău e.",
    question: "Îți măsori starea înaintea lui Dumnezeu după ce ai făcut azi?",
    prayer: "Doamne, ai luat ce era al meu și mi-ai dat ce era al Tău. Nu mai negociez schimbul. Amin.",
    step: "Când te judeci azi, spune o dată: „nu stau pe al meu”.",
  },
  {
    id: "dev_036",
    dayNumber: 36,
    theme: LUNA_2,
    axis: "identity",
    verseRef: "Isaia 53:5",
    verseText: "Dar El era străpuns pentru păcatele noastre, zdrobit pentru fărădelegile noastre. Pedeapsa care ne dă pacea a căzut peste El, și prin rănile Lui suntem tămăduiți.",
    meditation:
      "Isaia scrie asta cu sute de ani înainte. Nu e o explicație inventată după, ca să se împace cineva cu o moarte urâtă; era planul, spus dinainte. Iar cuvântul „noastre” apare de patru ori: nimic din ce a purtat nu era al Lui.",
    question: "Ce parte din tine crezi că a rămas nepurtată de El?",
    prayer: "Doamne, ai purtat ce era al meu. Nu mai car eu ce ai dus Tu. Amin.",
    step: "Numește azi în rugăciune un singur lucru și spune: „asta ai purtat-o Tu”.",
  },
  {
    id: "dev_037",
    dayNumber: 37,
    theme: LUNA_2,
    axis: "identity",
    verseRef: "Ioan 19:30",
    verseText: "Când a luat Isus oțetul, a zis: „S-a isprăvit!” Apoi și-a plecat capul și Și-a dat duhul.",
    meditation:
      "Cuvântul din original se scria pe facturi, cu sensul „plătit integral”. Nu a zis „am rezistat”, nici „am făcut ce am putut”. A zis că s-a terminat. Un lucru terminat nu se mai continuă de tine, oricât de vinovat te-ai simți.",
    question: "Ce încerci să termini tu, din ceea ce El a spus deja că s-a isprăvit?",
    prayer: "Doamne, s-a isprăvit. Iartă-mă că mă port ca și cum ar mai fi ceva de plătit. Amin.",
    step: "Spune azi, o dată, cu voce tare, doar atât: „s-a isprăvit”.",
  },
  {
    id: "dev_038",
    dayNumber: 38,
    theme: LUNA_2,
    axis: "identity",
    verseRef: "Evrei 10:14",
    verseText: "Căci printr-o singură jertfă El a făcut desăvârșiți pentru totdeauna pe cei ce sunt sfințiți.",
    meditation:
      "Sunt două timpuri în verset, și amândouă sunt adevărate deodată: ești deja desăvârșit prin ce a făcut El și abia ești sfințit, adică lucrat, în viața de zi cu zi. Nu te confunda: progresul tău lent nu contrazice statutul tău sigur.",
    question: "Îți amâni pacea până când te vei purta mai bine?",
    prayer: "Doamne, sunt gata în ochii Tăi și în lucru în viața mea. Ajută-mă să trăiesc din primul, nu din al doilea. Amin.",
    step: "Notează un lucru la care încă te lupți și scrie lângă el: „în lucru, nu în pericol”.",
  },
  {
    id: "dev_039",
    dayNumber: 39,
    theme: LUNA_2,
    axis: "identity",
    verseRef: "Coloseni 2:14",
    verseText: "A șters zapisul cu poruncile lui, care stătea împotriva noastră și ne era potrivnic, și l-a nimicit pironindu-l pe cruce.",
    meditation:
      "Zapisul era hârtia cu datoria scrisă, semnată de datornic. Pavel spune că nu a fost micșorată, ci ștearsă și bătută în cuie la vedere. Vinovăția care îți citește azi lista îți citește dintr-o hârtie care nu mai are valoare juridică.",
    question: "Cine îți citește lista, în capul tău, și cu ce voce?",
    prayer: "Doamne, hârtia e ștearsă. Nu mai stau la judecată acolo unde ai plătit Tu. Amin.",
    step: "Când te acuză azi o listă veche, întreabă o dată: „cine ține hârtia asta?”",
  },
  {
    id: "dev_040",
    dayNumber: 40,
    theme: LUNA_2,
    axis: "identity",
    verseRef: "Romani 6:4",
    verseText: "Noi deci, prin botezul în moartea Lui, am fost îngropați împreună cu El, pentru ca, după cum Hristos a înviat din morți prin slava Tatălui, tot așa și noi să trăim o viață nouă.",
    meditation:
      "Un om îngropat nu se mai apără, nu mai are reputație de păzit, nu mai are de dovedit nimic. Asta e libertatea ciudată de care vorbește Pavel. Viața nouă nu e o versiune îmbunătățită a celei vechi; e alta, primită după o înmormântare.",
    question: "Ce parte din viața veche încerci să reînvii, deși a fost îngropată?",
    prayer: "Doamne, cel vechi a fost îngropat. Nu-l mai dezgrop eu. Amin.",
    step: "Renunță azi la o apărare de sine pe care ai fi dat-o automat.",
  },
  {
    id: "dev_041",
    dayNumber: 41,
    theme: LUNA_2,
    axis: "identity",
    verseRef: "Efeseni 2:6",
    verseText: "El ne-a înviat împreună și ne-a pus să ședem împreună în locurile cerești, în Hristos Isus.",
    meditation:
      "„Să ședem” — poziția e de om așezat, nu de om care aleargă. În lumea antică, cine ședea în casa unui împărat era din familie sau invitat de onoare; ceilalți stăteau în picioare. Ție ți s-a dat scaun.",
    question: "Cât din viața ta de credință o trăiești în picioare, gata să pleci?",
    prayer: "Doamne, mi-ai dat loc așezat. Învață-mă să stau jos în prezența Ta. Amin.",
    step: "Stai azi cinci minute fără să ceri și fără să faci nimic. Doar stai.",
  },
  {
    id: "dev_042",
    dayNumber: 42,
    theme: LUNA_2,
    axis: "identity",
    verseRef: "1 Petru 1:3",
    verseText: "Ne-a născut din nou, prin învierea lui Isus Hristos din morți, la o nădejde vie.",
    meditation:
      "Nădejdea creștină nu e optimism. Optimismul spune „poate iese bine”; nădejdea vie se sprijină pe un lucru care s-a întâmplat deja, într-o zi anume, cu martori. Nu speri că Dumnezeu poate învia ceva; te uiți înapoi la ce a înviat.",
    question: "Nădejdea ta stă pe ce simți sau pe ce s-a întâmplat?",
    prayer: "Doamne, nădejdea mea e vie pentru că Tu ești viu. Ține-mă acolo. Amin.",
    step: "Scrie un lucru pe care îl consideri mort în viața ta. Nu adăuga nimic; doar pune-l în fața Lui.",
  },
  {
    id: "dev_043",
    dayNumber: 43,
    theme: LUNA_2,
    axis: "identity",
    verseRef: "Romani 4:5",
    verseText: "Pe când celui ce nu lucrează, ci crede în Cel ce socotește pe păcătos neprihănit, credința pe care o are el îi este socotită ca neprihănire.",
    meditation:
      "E cel mai scandalos verset din Pavel: Dumnezeu îndreptățește pe cel nelegiuit, nu pe cel cumsecade. Dacă ar fi îndreptățit oameni buni, ar fi o afacere corectă și tu ai avea de ce să te temi. Așa, ai o singură problemă: să nu te crezi prea bun ca să ai nevoie.",
    question: "Te crezi prea rău pentru Dumnezeu sau prea bun ca să ai nevoie de El?",
    prayer: "Doamne, nu vin cu munca mea, vin cu încrederea. Amin.",
    step: "Spune-I azi un lucru la care ai eșuat, fără să promiți că îl repari.",
  },
  {
    id: "dev_044",
    dayNumber: 44,
    theme: LUNA_2,
    axis: "identity",
    verseRef: "Galateni 3:26",
    verseText: "Căci toți sunteți fii ai lui Dumnezeu prin credința în Hristos Isus.",
    meditation:
      "„Toți” era un cuvânt exploziv pentru cine îl citea prima dată: și cel din alt neam, și sclavul, și femeia, în aceeași propoziție. Nu există clasa a doua în familia asta. Deci comparația cu alți credincioși e o pierdere de vreme: nu se dau note de fiu.",
    question: "Cu cine te compari și ce crezi că are acela în plus la Dumnezeu?",
    prayer: "Doamne, nu sunt cu un rând mai jos. Vindecă-mi comparațiile. Amin.",
    step: "Când te compari azi cu cineva, roagă-te o dată pentru omul acela.",
  },
  {
    id: "dev_045",
    dayNumber: 45,
    theme: LUNA_2,
    axis: "identity",
    verseRef: "Evrei 4:16",
    verseText: "Să ne apropiem dar cu deplină încredere de scaunul harului ca să căpătăm îndurare și să găsim har, pentru ca să fim ajutați la vreme de nevoie.",
    meditation:
      "Se numește „scaunul harului”, nu scaunul judecății. Iar invitația e „cu deplină încredere”, exact în momentul în care ai greșit — pentru că atunci ai nevoie de îndurare. Instinctul nostru e invers: ne apropiem când ne merge bine și ne ascundem când cădem.",
    question: "Ce faci, de obicei, în prima oră după ce ai greșit?",
    prayer: "Doamne, vin acum, nu după ce mă adun. Amin.",
    step: "Data viitoare când greșești azi, roagă-te în primele două minute. Fără pregătire.",
  },
  {
    id: "dev_046",
    dayNumber: 46,
    theme: LUNA_2,
    axis: "identity",
    verseRef: "Evrei 7:25",
    verseText: "De aceea și poate să mântuiască în chip desăvârșit pe cei ce se apropie de Dumnezeu prin El, pentru că trăiește pururea ca să mijlocească pentru ei.",
    meditation:
      "În timp ce citești rândul acesta, cineva vorbește cu Tatăl despre tine. Nu ocazional, ci „pururea”. Rugăciunea ta slabă de azi nu e singura rugăciune care se face pentru tine azi.",
    question: "Ce s-ar schimba în ziua ta dacă ai crede că se mijlocește pentru tine chiar acum?",
    prayer: "Doamne, Tu Te rogi pentru mine mai bine decât mă rog eu. Mulțumesc. Amin.",
    step: "Când azi nu ai cuvinte de rugăciune, oprește-te și spune: „Tu Te rogi pentru mine”.",
  },
  {
    id: "dev_047",
    dayNumber: 47,
    theme: LUNA_2,
    axis: "identity",
    verseRef: "Romani 8:34",
    verseText: "Cine-i va osândi? Hristos a murit! Ba mai mult, El a și înviat, stă la dreapta lui Dumnezeu și mijlocește pentru noi!",
    meditation:
      "Pavel pune întrebarea ca la tribunal: cine acuză? Și răspunde nu cu o apărare, ci cu o persoană. Singurul care ar avea dreptul să te condamne e Cel care S-a așezat de partea ta.",
    question: "Cine te acuză cel mai des: alții, tu sau o voce pe care o crezi a lui Dumnezeu?",
    prayer: "Doamne, Cel care putea să mă osândească mijlocește pentru mine. Amin.",
    step: "Scrie acuzația care revine cel mai des și, dedesubt: „cine-i va osândi?”",
  },
  {
    id: "dev_048",
    dayNumber: 48,
    theme: LUNA_2,
    axis: "identity",
    verseRef: "1 Ioan 2:1",
    verseText: "Copilașilor, vă scriu aceste lucruri ca să nu păcătuiți. Dar, dacă cineva a păcătuit, avem la Tatăl un Mijlocitor, pe Isus Hristos, Cel neprihănit.",
    meditation:
      "Ioan nu face pace cu păcatul — scrie tocmai ca să nu păcătuiești. Dar știe și ce urmează. „Dar dacă” nu e o portiță; e un loc pregătit dinainte pentru ziua în care cazi, ca să nu fugi de acasă.",
    question: "Când cazi, fugi de Dumnezeu sau la El?",
    prayer: "Doamne, când cad, dă-mi reflexul să vin, nu să mă ascund. Amin.",
    step: "Alege dinainte ce faci azi la prima cădere: te rogi pe loc, o frază.",
  },
  {
    id: "dev_049",
    dayNumber: 49,
    theme: LUNA_2,
    axis: "identity",
    verseRef: "Ioan 6:37",
    verseText: "Pe cel ce vine la Mine, nu-l voi izgoni afară.",
    meditation:
      "Nu spune „pe cel ce vine curat”. Nici „pe cel ce vine a treia oară cu aceeași problemă”. Condiția e una singură: să vii. Iar promisiunea e negativă, adică imposibil de răstălmăcit: nu te dă afară.",
    question: "De câte ori crezi că mai ai voie să vii cu același lucru?",
    prayer: "Doamne, vin iar, cu același lucru. Ai spus că nu mă dai afară. Amin.",
    step: "Adu-I azi exact problema cu care ai venit și data trecută. Fără scuze de început.",
  },
  {
    id: "dev_050",
    dayNumber: 50,
    theme: LUNA_2,
    axis: "identity",
    verseRef: "Ioan 10:28",
    verseText: "Eu le dau viața veșnică, în veac nu vor pieri și nimeni nu le va smulge din mâna Mea.",
    meditation:
      "„Nimeni” include și mâna ta, în zilele în care te zbați. Siguranța nu vine din strânsoarea ta, ci din a Lui. Un copil ținut de tată peste stradă e în siguranță chiar dacă lui i-au obosit degetele.",
    question: "Te ții tu de Dumnezeu sau te ține El?",
    prayer: "Doamne, mâna Ta e mai tare decât a mea. Ține-mă Tu. Amin.",
    step: "Când te sperii azi că nu mai poți, spune: „nu eu mă țin”.",
  },
  {
    id: "dev_051",
    dayNumber: 51,
    theme: LUNA_2,
    axis: "identity",
    verseRef: "Evrei 13:8",
    verseText: "Isus Hristos este același ieri și azi și în veci!",
    meditation:
      "Oamenii se schimbă cu tine după cum te porți. E de ajuns o perioadă mai slabă și te trezești tratat altfel. Isus nu e „același” ca o statuie, ci ca un caracter: nu se răcește, nu Se satură, nu Se plictisește de tine.",
    question: "Te aștepți ca Dumnezeu să se poarte cu tine cum s-a purtat cineva care s-a răcit?",
    prayer: "Doamne, Tu ești același. Nu Te proiecta prin oamenii care s-au schimbat. Amin.",
    step: "Întreabă-te azi o dată: „Îi atribui lui Dumnezeu fața cuiva care m-a rănit?”",
  },
  {
    id: "dev_052",
    dayNumber: 52,
    theme: LUNA_2,
    axis: "identity",
    verseRef: "Psalmul 103:12",
    verseText: "Cât de departe este răsăritul de apus, atât de mult depărtează El fărădelegile noastre de la noi.",
    meditation:
      "David alege dinadins răsăritul și apusul, nu nordul și sudul: nordul și sudul au capăt, răsăritul și apusul nu se întâlnesc niciodată. E singura măsură care nu poate fi parcursă. Păcatul iertat nu e pus deoparte, e pus în neîntâlnire.",
    question: "Ce păcat iertat mai ții tu aproape, ca să nu-l uiți?",
    prayer: "Doamne, Tu l-ai dus departe. Iartă-mă că îl aduc înapoi. Amin.",
    step: "Când îți revine azi în minte un lucru iertat, spune: „e la apus”.",
  },
  {
    id: "dev_053",
    dayNumber: 53,
    theme: LUNA_2,
    axis: "identity",
    verseRef: "Mica 7:19",
    verseText: "El va avea iarăși milă de noi, va călca în picioare nelegiuirile noastre și va arunca în fundul mării toate păcatele lor.",
    meditation:
      "În fundul mării, nu la mal. Adâncul era, pentru omul din vechime, locul din care nimic nu se mai scoate. Dumnezeu nu are un dosar la care se întoarce când te porți urât.",
    question: "Îl bănuiești pe Dumnezeu că ține evidența, chiar dacă spune că nu?",
    prayer: "Doamne, Tu nu pescuiești ce ai aruncat. Ajută-mă să nu pescuiesc nici eu. Amin.",
    step: "Nu-ți mai aminti azi, dinadins, o greșeală veche. Când vine, las-o să treacă.",
  },
  {
    id: "dev_054",
    dayNumber: 54,
    theme: LUNA_2,
    axis: "identity",
    verseRef: "Isaia 1:18",
    verseText: "De vor fi păcatele voastre cum e cârmâzul, se vor face albe ca zăpada; de vor fi roșii ca purpura, se vor face ca lâna.",
    meditation:
      "Cârmâzul era o vopsea care nu ieșea la spălat; alegerea culorii e intenționată. Dumnezeu nu spune că păcatul tău e mai mic decât crezi. Spune că e exact atât de adânc pe cât te temi — și tot iese.",
    question: "Ce pată crezi că nu iese la tine?",
    prayer: "Doamne, nu Te sperii de culoarea ei. Spal-o Tu. Amin.",
    step: "Spune-I azi pe nume lucrului de care crezi că nu te poți curăța.",
  },
  {
    id: "dev_055",
    dayNumber: 55,
    theme: LUNA_2,
    axis: "identity",
    verseRef: "Ezechiel 36:26",
    verseText: "Vă voi da o inimă nouă și voi pune în voi un duh nou; voi scoate din trupul vostru inima de piatră și vă voi da o inimă de carne.",
    meditation:
      "Cine are inimă de piatră nu simte că are; piatra nu doare. De aceea promisiunea nu e „te ajut să simți mai mult”, ci „schimb organul”. Faptul că te doare azi nepăsarea ta e deja semn că lucrarea a început.",
    question: "Unde te-ai împietrit fără să bagi de seamă?",
    prayer: "Doamne, dă-mi o inimă care simte. Chiar dacă doare. Amin.",
    step: "Fă azi un lucru mic pentru cineva de care te-ai săturat.",
  },
  {
    id: "dev_056",
    dayNumber: 56,
    theme: LUNA_2,
    axis: "identity",
    verseRef: "Ioan 3:16",
    verseText: "Fiindcă atât de mult a iubit Dumnezeu lumea, că a dat pe singurul Lui Fiu, pentru ca oricine crede în El să nu piară, ci să aibă viața veșnică.",
    meditation:
      "E versetul pe care îl știi pe de rost, și tocmai de aceea nu îl mai auzi. Citește azi doar două cuvinte: „a dat”. Dragostea lui Dumnezeu nu e o stare de spirit, e un lucru la care a renunțat.",
    question: "Îl crezi pe Dumnezeu că te iubește, sau doar știi versetul?",
    prayer: "Doamne, ai dat. Nu doar ai simțit. Mulțumesc. Amin.",
    step: "Spune versetul azi rar, cu ochii deschiși, ca și cum l-ai auzi prima dată.",
  },
  {
    id: "dev_057",
    dayNumber: 57,
    theme: LUNA_2,
    axis: "identity",
    verseRef: "Romani 10:9",
    verseText: "Dacă mărturisești deci cu gura ta pe Isus ca Domn și dacă crezi în inima ta că Dumnezeu L-a înviat din morți, vei fi mântuit.",
    meditation:
      "Gura și inima, în aceeași propoziție: nu ajunge să crezi pe ascuns, dar nici să spui ce nu crezi. Iar verbul e la viitor sigur, nu la „poate”. Sunt oameni care se roagă de ani de zile să fie primiți, deși au fost primiți din prima zi.",
    question: "Ai spus vreodată cu gura ta, simplu, cine e Isus pentru tine?",
    prayer: "Doamne Isuse, Tu ești Domnul meu. Cred că Dumnezeu Te-a înviat. Amin.",
    step: "Spune azi cuiva, într-o propoziție, de ce ești creștin. Fără predică.",
  },
  {
    id: "dev_058",
    dayNumber: 58,
    theme: LUNA_2,
    axis: "identity",
    verseRef: "Fapte 4:12",
    verseText: "În nimeni altul nu este mântuire, căci nu este sub cer niciun alt Nume dat oamenilor în care trebuie să fim mântuiți.",
    meditation:
      "Versetul sună îngust până înțelegi ce spune de fapt: nu că oamenii sunt puțini, ci că ușa e una și e deschisă la toți. Într-o lume în care fiecare drum cere ceva de la tine, acesta cere doar să intri pe el.",
    question: "Ce alt „nume” — o metodă, un om, o reușită — ai pus, în practică, în locul Lui?",
    prayer: "Doamne, nu am alt nume la care să fug. Amin.",
    step: "Renunță azi la o soluție de rezervă la care alergi înaintea rugăciunii.",
  },
  {
    id: "dev_059",
    dayNumber: 59,
    theme: LUNA_2,
    axis: "identity",
    verseRef: "1 Corinteni 6:11",
    verseText: "Și așa erați unii din voi! Dar ați fost spălați, ați fost sfințiți, ați fost socotiți neprihăniți în Numele Domnului Isus Hristos și prin Duhul Dumnezeului nostru.",
    meditation:
      "„Așa erați” — Pavel tocmai enumerase o listă grea, și scrie unor oameni care fuseseră pe ea. Trei verbe la trecut, toate făcute asupra lor, nu de ei. Trecutul tău e trecutul tău tocmai pentru că cineva a lucrat asupra ta.",
    question: "Ce etichetă veche mai porți, deși versetul o pune la trecut?",
    prayer: "Doamne, „erați” e la trecut. Ajută-mă să vorbesc și eu despre mine la timpul corect. Amin.",
    step: "Spune azi despre un lucru vechi din tine: „așa eram”.",
  },
  {
    id: "dev_060",
    dayNumber: 60,
    theme: LUNA_2,
    axis: "identity",
    verseRef: "Iuda 1:24",
    verseText: "Iar Aceluia care poate să vă păzească de orice cădere și să vă facă să vă înfățișați fără prihană și plini de bucurie înaintea slavei Sale...",
    meditation:
      "Două luni s-au încheiat, și versetul de final nu îți cere nimic: „Aceluia care poate”. Nu tu te păzești și nu tu te înfățișezi. Dacă ai lipsit zile, nu s-a rupt nimic — mana de azi e pentru azi. De luna viitoare vorbim despre frică și grijă, dar de pe temelia asta.",
    question: "Ce s-a schimbat în felul în care te vezi, față de ziua 1?",
    prayer: "Doamne, Tu poți. Eu vin. Mulțumesc pentru cele două luni. Amin.",
    step: "Recitește rândul scris în ziua 31 și adaugă unul singur, pentru luna asta.",
  },
]
