// Devoțional, luna 3: „Frica și grija” (docs/27 §2.4, axa emotional_peace).
//
// Regula lunii: nu se cere nimănui să nu se teamă. Frica nu se scoate cu îndemnuri,
// ci prin mutarea privirii spre Cine este de față. De aceea aici nu veți găsi
// „nu-ți mai face griji”, ci „uite cu Cine treci prin asta”.
//
// Conținut ORIGINAL Emanus (docs/27 §1.2). Versete: Cornilescu VDC 1924
// (domeniu public), colaționate verset cu verset.
import type { DevotionalDay } from "./devotional.js"

const LUNA_3 = "Frica și grija"

export const DEVOTIONAL_DAYS_LUNA_3: DevotionalDay[] = [
  {
    id: "dev_061",
    dayNumber: 61,
    theme: LUNA_3,
    axis: "emotional_peace",
    verseRef: "Isaia 41:10",
    verseText: "Nu te teme, căci Eu sunt cu tine; nu te uita cu îngrijorare, căci Eu sunt Dumnezeul tău; Eu te întăresc, tot Eu îți vin în ajutor.",
    meditation:
      "Observă că motivul nu e „pentru că nu e nimic grav”, ci „pentru că Eu sunt cu tine”. Dumnezeu nu îți contestă problema, își anunță prezența. Curățenia asta de gândire schimbă tot: nu trebuie să te convingi că e bine ca să nu te temi.",
    question: "De ce anume te temi azi, spus în cuvinte simple?",
    prayer: "Doamne, mi-e frică și nu mă prefac. Dar Tu ești aici. Atât îmi trebuie ca să merg mai departe. Amin.",
    step: "Scrie frica ta într-o propoziție și adaugă la capăt: „și Dumnezeu e cu mine în asta”.",
  },
  {
    id: "dev_062",
    dayNumber: 62,
    theme: LUNA_3,
    axis: "emotional_peace",
    verseRef: "Filipeni 4:6-7",
    verseText: "Nu vă îngrijorați de nimic, ci, în orice lucru, aduceți cererile voastre la cunoștința lui Dumnezeu, prin rugăciuni și cereri, cu mulțumiri. Și pacea lui Dumnezeu, care întrece orice pricepere, vă va păzi inimile și gândurile în Hristos Isus.",
    meditation:
      "Pavel nu spune „nu vă îngrijorați” și atât — asta ar fi crud. Spune ce să faci cu grija: s-o muți. Grija are nevoie de o destinație, altfel se învârte în cerc. Iar pacea promisă nu e explicație, e pază: stă la ușă, nu îți răspunde la întrebări.",
    question: "Ce grijă învârti de zile întregi fără să o fi spus vreodată lui Dumnezeu?",
    prayer: "Doamne, o mut la Tine. Nu îți cer explicații, îți cer pacea pe care ai promis-o. Amin.",
    step: "Spune-I azi grija cu voce tare, o dată, și încheie cu un lucru pentru care mulțumești.",
  },
  {
    id: "dev_063",
    dayNumber: 63,
    theme: LUNA_3,
    axis: "emotional_peace",
    verseRef: "Matei 6:26",
    verseText: "Uitați-vă la păsările cerului: ele nici nu seamănă, nici nu seceră și nici nu strâng nimic în grânare, și totuși Tatăl vostru cel ceresc le hrănește. Oare nu sunteți voi cu mult mai de preț decât ele?",
    meditation:
      "Isus nu spune că păsările stau degeaba — o pasăre muncește toată ziua. Spune că nu depozitează. Diferența dintre muncă și grijă e aici: munca ține de azi, grija încearcă să controleze un an care nu a venit.",
    question: "Muncești pentru ziua de azi sau încerci să asiguri un viitor pe care nu-l poți vedea?",
    prayer: "Doamne, Tu hrănești păsările. Sunt în aceeași grijă a Ta. Amin.",
    step: "Ieși azi două minute afară și uită-te, la propriu, la o pasăre. Versetul cere o privire, nu o teorie.",
  },
  {
    id: "dev_064",
    dayNumber: 64,
    theme: LUNA_3,
    axis: "emotional_peace",
    verseRef: "Matei 6:27",
    verseText: "Și apoi, cine dintre voi, chiar îngrijorându-se, poate să adauge măcar un cot la înălțimea lui?",
    meditation:
      "E singura întrebare din Biblie la care toți știm răspunsul și tot facem invers. Grija dă senzația că lucrăm la problemă. În realitate, e singura formă de efort care consumă tot și nu mută nimic.",
    question: "Ce a rezolvat, concret, grija ta din ultima săptămână?",
    prayer: "Doamne, grija mea nu mută nimic. Ia-mi din mână lucrul pe care nu-l pot mișca. Amin.",
    step: "Când te prinzi azi îngrijorat, întreabă-te o dată: „există ceva de făcut acum?” Dacă nu, roagă-te. Dacă da, fă.",
  },
  {
    id: "dev_065",
    dayNumber: 65,
    theme: LUNA_3,
    axis: "emotional_peace",
    verseRef: "Psalmul 56:3",
    verseText: "Ori de câte ori mă tem, eu mă încred în Tine.",
    meditation:
      "David nu scrie „nu mă mai tem”. Scrie ce face când se teme. Încrederea nu e opusul fricii, e ce faci în timp ce ți-e frică. Versetul acesta e scurt tocmai ca să-l poți spune în mijlocul unei nopți grele.",
    question: "Ce faci, de obicei, în primele minute de frică?",
    prayer: "Doamne, mi-e frică și mă încred în Tine în același timp. Amin.",
    step: "Învață azi versetul pe de rost. Are opt cuvinte și îți va folosi într-o noapte.",
  },
  {
    id: "dev_066",
    dayNumber: 66,
    theme: LUNA_3,
    axis: "emotional_peace",
    verseRef: "1 Petru 5:7",
    verseText: "Și aruncați asupra Lui toate îngrijorările voastre, căci El Însuși îngrijește de voi.",
    meditation:
      "„Aruncați” e un verb de descotorosire, nu de împărțire. Iar motivul din a doua parte e cel mai important: nu „pentru că ești slab”, ci „pentru că Lui Îi pasă”. Nu arunci ceva la un birou; îi dai cuiva căruia îi pasă de tine.",
    question: "Ce grijă ai „aruncat” și ai luat înapoi de trei ori?",
    prayer: "Doamne, Ți-o dau iar. Ție Îți pasă de mine, nu doar de rezolvare. Amin.",
    step: "Când îți vine grija înapoi azi, spune simplu: „e la Tine”. Fără să te cerți.",
  },
  {
    id: "dev_067",
    dayNumber: 67,
    theme: LUNA_3,
    axis: "emotional_peace",
    verseRef: "Psalmul 46:1-2",
    verseText: "Dumnezeu este adăpostul și sprijinul nostru, un ajutor care nu lipsește niciodată în nevoi. De aceea nu ne temem chiar dacă s-ar zgudui pământul și s-ar clătina munții în inima mărilor.",
    meditation:
      "Psalmul nu promite că pământul nu se zguduie. Curățenia asta e importantă: credința nu e o asigurare că nu vin cutremure, ci un loc în care stai când vin. Sunt oameni care își pierd credința pentru că li s-a promis, greșit, că nu se va clătina nimic.",
    question: "Ce s-a zguduit în viața ta și încă nu s-a așezat?",
    prayer: "Doamne, nu-ți cer să nu se miște pământul. Îți cer să fii Tu adăpostul. Amin.",
    step: "Numește azi un lucru care s-a zguduit și spune-I unde ai fugit atunci.",
  },
  {
    id: "dev_068",
    dayNumber: 68,
    theme: LUNA_3,
    axis: "emotional_peace",
    verseRef: "Ioan 14:27",
    verseText: "Vă las pacea, vă dau pacea Mea. Nu v-o dau cum o dă lumea. Să nu vi se tulbure inima, nici să nu se înspăimânte.",
    meditation:
      "Pacea lumii vine din circumstanțe bune: când se strică ele, se duce și ea. Isus spune limpede că a Lui e de alt fel — și o spune în seara în care urma să fie arestat. Nu vorbea din confort.",
    question: "Pacea ta de azi depinde de ce s-a întâmplat azi?",
    prayer: "Doamne, dă-mi pacea Ta, nu liniștea care ține până la următorul telefon. Amin.",
    step: "Observă azi ce anume îți strică pacea cel mai repede. Doar observă și notează.",
  },
  {
    id: "dev_069",
    dayNumber: 69,
    theme: LUNA_3,
    axis: "emotional_peace",
    verseRef: "2 Timotei 1:7",
    verseText: "Căci Dumnezeu nu ne-a dat un duh de frică, ci de putere, de dragoste și de chibzuință.",
    meditation:
      "Pavel îi scrie asta unui om tânăr și temperamental, care conducea o biserică grea. Frica nu e semn că ești nepotrivit; e doar un duh care nu vine de la Dumnezeu. Și observă al treilea cuvânt: chibzuință. Frica ne face haotici; Duhul ne face limpezi.",
    question: "Ce decizie ai luat ultima dată din frică, nu din chibzuință?",
    prayer: "Doamne, nu de la Tine vine frica asta. Dă-mi minte limpede azi. Amin.",
    step: "Amână azi cu o oră o decizie pe care ai lua-o din panică.",
  },
  {
    id: "dev_070",
    dayNumber: 70,
    theme: LUNA_3,
    axis: "emotional_peace",
    verseRef: "Psalmul 23:4",
    verseText: "Chiar dacă ar fi să umblu prin valea umbrei morții, nu mă tem de niciun rău, căci Tu ești cu mine. Toiagul și nuiaua Ta mă mângâie.",
    meditation:
      "„Prin”, nu „în”. Valea nu e destinație, e drum. Și mai e ceva: până aici psalmul vorbea despre Dumnezeu la persoana a treia — „El mă paște”. În vale, David Îi vorbește direct: „Tu ești cu mine”. Locurile grele ne apropie limbajul.",
    question: "Prin ce vale treci acum și de cât timp?",
    prayer: "Doamne, trec prin ea, nu rămân în ea. Mergi cu mine. Amin.",
    step: "Vorbește-I azi cu „Tu”, nu despre El la persoana a treia.",
  },
  {
    id: "dev_071",
    dayNumber: 71,
    theme: LUNA_3,
    axis: "emotional_peace",
    verseRef: "Isaia 43:2",
    verseText: "Dacă vei trece prin ape, Eu voi fi cu tine și râurile nu te vor îneca; dacă vei merge prin foc, nu te va arde și flacăra nu te va aprinde.",
    meditation:
      "Dumnezeu nu promite ocolirea apelor. Promite că nu te îneci. Sunt două credințe foarte diferite: una așteaptă ca Dumnezeu să îndepărteze apa și se prăbușește când nu o face, alta învață să Îl recunoască în apă.",
    question: "Te rogi să fie luată apa sau să fie El cu tine în ea?",
    prayer: "Doamne, dacă apa nu se retrage, treci Tu cu mine prin ea. Amin.",
    step: "Schimbă azi o rugăciune din „ia-mi asta” în „fii cu mine în asta”. Spune-le pe amândouă, dacă vrei.",
  },
  {
    id: "dev_072",
    dayNumber: 72,
    theme: LUNA_3,
    axis: "emotional_peace",
    verseRef: "Deuteronom 31:8",
    verseText: "Domnul Însuși va merge înaintea ta, El Însuși va fi cu tine, nu te va părăsi și nu te va lăsa; nu te teme și nu te înspăimânta!",
    meditation:
      "Cuvântul cheie e „înaintea ta”. Dumnezeu nu te împinge de la spate spre ziua de mâine; e deja acolo. Ziua care te sperie a fost vizitată înaintea ta.",
    question: "Ce zi din calendar te sperie și ce crezi că te așteaptă acolo?",
    prayer: "Doamne, Tu ești deja în ziua aceea. Nu intru singur. Amin.",
    step: "Roagă-te azi anume pentru ziua care te sperie, ca și cum ai trimite pe cineva înainte.",
  },
  {
    id: "dev_073",
    dayNumber: 73,
    theme: LUNA_3,
    axis: "emotional_peace",
    verseRef: "Iosua 1:9",
    verseText: "Nu ți-am dat Eu oare porunca aceasta: ‘Întărește-te și îmbărbătează-te’? Nu te înspăimânta și nu te îngrozi, căci Domnul Dumnezeul tău este cu tine în tot ce vei face.",
    meditation:
      "I se spune de trei ori aceluiași om, ceea ce înseamnă că Iosua se temea. Curajul biblic nu e o trăsătură de caracter, e o ascultare: te miști înainte pentru că ți s-a spus și pentru că El e cu tine, nu pentru că ți-a trecut frica.",
    question: "Ce lucru amâni până când îți va trece frica?",
    prayer: "Doamne, nu aștept să-mi treacă frica. Merg cu ea, pentru că Tu ești cu mine. Amin.",
    step: "Fă azi primul pas mărunt din lucrul amânat. Doar primul.",
  },
  {
    id: "dev_074",
    dayNumber: 74,
    theme: LUNA_3,
    axis: "emotional_peace",
    verseRef: "Psalmul 94:19",
    verseText: "Când gânduri negre se frământă cu grămada înăuntrul meu, mângâierile Tale îmi înviorează sufletul.",
    meditation:
      "„Cu grămada” — psalmistul știe cum e când gândurile nu vin unul câte unul. Nu spune că le-a oprit. Spune că a primit mângâiere în timp ce ele se învârteau. Uneori Dumnezeu nu îți liniștește capul, îți ține sufletul.",
    question: "Când ți se adună gândurile, cauți liniște sau mângâiere? Nu e același lucru.",
    prayer: "Doamne, nu-mi pot opri capul. Ține-mi sufletul până se așază. Amin.",
    step: "Când te năpădesc azi gândurile, nu te lupta cu ele. Spune un verset, o dată, și respiră.",
  },
  {
    id: "dev_075",
    dayNumber: 75,
    theme: LUNA_3,
    axis: "emotional_peace",
    verseRef: "Marcu 4:39-40",
    verseText: "El S-a sculat, a certat vântul și a zis mării: „Taci! Fără gură!” Vântul a stat și s-a făcut o liniște mare. Apoi le-a zis: „Pentru ce sunteți așa de fricoși? Tot n-aveți credință?”",
    meditation:
      "Ucenicii nu se temeau că vor muri singuri — se temeau că Lui nu-I pasă: „nu-ți pasă că pierim?” Asta e frica de dedesubt, la toți. Nu că furtuna e mare, ci că poate am rămas singuri în ea.",
    question: "În furtuna ta de acum, te temi de furtună sau că Lui nu-I pasă?",
    prayer: "Doamne, spune-mi că Îți pasă. Nu m-am temut niciodată doar de valuri. Amin.",
    step: "Spune-I azi exact fraza asta: „mă tem că nu-ți pasă”. Sinceritatea nu Te îndepărtează de El.",
  },
  {
    id: "dev_076",
    dayNumber: 76,
    theme: LUNA_3,
    axis: "emotional_peace",
    verseRef: "Matei 14:30-31",
    verseText: "Dar, când a văzut că vântul era tare, s-a temut și, fiindcă începea să se afunde, a strigat: „Doamne, scapă-mă!” Îndată, Isus a întins mâna, l-a apucat și i-a zis: „Puțin credinciosule, pentru ce te-ai îndoit?”",
    meditation:
      "Petru s-a scufundat, dar rugăciunea lui a fost cea mai scurtă din Evanghelii și a funcționat imediat. Nu ai nevoie de cuvinte frumoase când te afunzi. Și observă: Isus l-a prins întâi și l-a întrebat după aceea.",
    question: "Crezi că trebuie să te aduni întâi și abia apoi să strigi?",
    prayer: "Doamne, scapă-mă. Amin.",
    step: "Când te ia panica azi, spune doar două cuvinte: „Doamne, ajută-mă”. Nu mai mult.",
  },
  {
    id: "dev_077",
    dayNumber: 77,
    theme: LUNA_3,
    axis: "emotional_peace",
    verseRef: "Psalmul 34:4",
    verseText: "Eu am căutat pe Domnul și mi-a răspuns: m-a izbăvit din toate temerile mele.",
    meditation:
      "Verbele sunt la trecut: a căutat, a primit răspuns, a fost izbăvit. Psalmii ne învață să ne aducem aminte — memoria e o armă împotriva fricii. Frica vorbește mereu despre viitor; amintirea îți arată că ai mai fost scos și altă dată.",
    question: "Din ce teamă te-a scos Dumnezeu deja, și ai uitat?",
    prayer: "Doamne, m-ai mai scos. Îmi amintesc azi, nu doar cer. Amin.",
    step: "Scrie trei lucruri de care te-ai temut acum un an. Vezi câte s-au întâmplat.",
  },
  {
    id: "dev_078",
    dayNumber: 78,
    theme: LUNA_3,
    axis: "emotional_peace",
    verseRef: "Proverbe 12:25",
    verseText: "Neliniștea din inima omului îl doboară, dar o vorbă bună îl înveselește.",
    meditation:
      "Soluția propusă aici nu e teologică, e omenească: o vorbă bună. Dumnezeu folosește des oameni ca să ridice pe cine s-a îndoit sub greutate. Poate azi tu ești cel ridicat. Poate ești vorba bună a altcuiva.",
    question: "Cine, din jurul tău, duce ceva greu și nu spune?",
    prayer: "Doamne, trimite-mi o vorbă bună și fă-mă una pentru cineva. Amin.",
    step: "Scrie azi un mesaj scurt cuiva care pare obosit. Nu întreba „ce ai”, spune „mă gândesc la tine”.",
  },
  {
    id: "dev_079",
    dayNumber: 79,
    theme: LUNA_3,
    axis: "emotional_peace",
    verseRef: "Luca 12:32",
    verseText: "Nu te teme, turmă mică, pentru că Tatăl vostru vă dă cu plăcere Împărăția.",
    meditation:
      "„Turmă mică” — Isus recunoaște că sunt puțini și slabi. Nu-i minte. Dar leagă liniștea lor nu de mărimea turmei, ci de bucuria Tatălui de a da. Dumnezeu nu dă din obligație, ci „cu plăcere”.",
    question: "Ți-e teamă că ceri prea mult, prea des?",
    prayer: "Doamne, Tu dai cu plăcere. Învață-mă să cer fără să-mi cer scuze. Amin.",
    step: "Cere-I azi un lucru pe care nu îndrăzneai să-l ceri.",
  },
  {
    id: "dev_080",
    dayNumber: 80,
    theme: LUNA_3,
    axis: "emotional_peace",
    verseRef: "Psalmul 121:3-4",
    verseText: "Da, El nu va îngădui să ți se clatine piciorul; Cel ce te păzește nu va dormita. Iată că nu dormitează, nici nu doarme Cel ce păzește pe Israel.",
    meditation:
      "Frica are program de noapte. Psalmul răspunde exact acolo: când tu nu poți dormi, Cineva oricum nu doarme — și nu de grijă, ci de pază. Nu ești singurul treaz în casa asta.",
    question: "Ce te ține treaz noaptea, în ultima vreme?",
    prayer: "Doamne, Tu vei păzi și când eu adorm. Pot să închid ochii. Amin.",
    step: "Astă-seară, înainte să dormi, spune o singură propoziție: „Tu nu dormi, deci eu pot”.",
  },
  {
    id: "dev_081",
    dayNumber: 81,
    theme: LUNA_3,
    axis: "emotional_peace",
    verseRef: "Isaia 26:3",
    verseText: "Celui cu inima tare, Tu-i chezășuiești pacea; da, pacea, căci se încrede în Tine.",
    meditation:
      "„Inimă tare” nu înseamnă dur, ci așezat — un om care nu e purtat de fiecare veste. Iar pacea e legată direct de unde îți ții mintea. Nu te poți hrăni toată ziua cu știri și scenarii și să ceri pace seara.",
    question: "Cu ce îți hrănești mintea în primele și ultimele minute ale zilei?",
    prayer: "Doamne, așază-mi mintea pe Tine. Nu vreau pace la cerere, vreau pace așezată. Amin.",
    step: "Nu deschide azi telefonul în primele zece minute după trezire.",
  },
  {
    id: "dev_082",
    dayNumber: 82,
    theme: LUNA_3,
    axis: "emotional_peace",
    verseRef: "Matei 11:29",
    verseText: "Luați jugul Meu asupra voastră și învățați de la Mine, căci Eu sunt blând și smerit cu inima; și veți găsi odihnă pentru sufletele voastre.",
    meditation:
      "Jugul se punea pe doi boi, iar cel tânăr învăța mergând lângă unul bătrân, care ducea greul. Isus nu îți promite că nu vei mai trage; îți spune lângă Cine vei trage. Și Își descrie caracterul, nu puterea: blând.",
    question: "Tragi singur la ceva la care ai fi putut cere ajutor?",
    prayer: "Doamne, sunt în jug cu Tine, nu în fața Ta. Amin.",
    step: "Cere azi ajutor la un lucru concret, de la un om. Neînțelegerea comună e că asta ar fi slăbiciune.",
  },
  {
    id: "dev_083",
    dayNumber: 83,
    theme: LUNA_3,
    axis: "emotional_peace",
    verseRef: "Psalmul 55:22",
    verseText: "Încredințează-ți soarta în mâna Domnului și El te va sprijini! El nu va lăsa niciodată să se clatine cel neprihănit.",
    meditation:
      "Cuvântul tradus „soarta” înseamnă și „povara ta” — sarcina care ți-a fost dată, nu doar viitorul. Uneori nu ceri să fii scăpat de responsabilitate, ci să fii sprijinit în ea. Asta e promisiunea: sprijin, nu evadare.",
    question: "Ce responsabilitate duci acum și n-o poți lăsa jos?",
    prayer: "Doamne, nu pot lăsa povara asta. Sprijină-mă sub ea. Amin.",
    step: "Numește azi în rugăciune povara pe care nu ai voie să o lași și cere putere, nu scăpare.",
  },
  {
    id: "dev_084",
    dayNumber: 84,
    theme: LUNA_3,
    axis: "emotional_peace",
    verseRef: "Romani 8:31",
    verseText: "Deci ce vom zice noi în fața tuturor acestor lucruri? Dacă Dumnezeu este pentru noi, cine va fi împotriva noastră?",
    meditation:
      "Întrebarea nu neagă că există oameni împotriva ta. Spune doar că nu contează la fel de mult. Iar dovada că Dumnezeu e de partea ta nu e că îți merge bine — e versetul următor, unde scrie că nu Și-a cruțat Fiul.",
    question: "Pe cine simți că ai împotrivă și cât spațiu îi dai în minte?",
    prayer: "Doamne, Tu ești pentru mine. Restul își pierde din greutate. Amin.",
    step: "Când îți vine azi în minte cine e împotriva ta, spune o dată: „Dumnezeu e pentru mine”.",
  },
  {
    id: "dev_085",
    dayNumber: 85,
    theme: LUNA_3,
    axis: "emotional_peace",
    verseRef: "Psalmul 112:7",
    verseText: "El nu se teme de vești rele, ci inima lui este tare, încrezătoare în Domnul.",
    meditation:
      "Nu scrie că nu vin vești rele. Scrie că omul acesta nu trăiește în așteptarea lor. Mulți ducem o frică de fond, ca un telefon care ar putea suna. Inima așezată nu e cea care nu primește vești, ci cea care știe unde fuge când le primește.",
    question: "Ce veste te temi că vei primi?",
    prayer: "Doamne, dacă vine vestea aceea, tot la Tine vin. Știu asta dinainte. Amin.",
    step: "Hotărăște azi, dinainte, ce faci în prima oră după o veste rea: cui suni și ce te rogi.",
  },
  {
    id: "dev_086",
    dayNumber: 86,
    theme: LUNA_3,
    axis: "emotional_peace",
    verseRef: "2 Corinteni 12:9",
    verseText: "Harul Meu îți este de ajuns, căci puterea Mea în slăbiciune este făcută desăvârșită.",
    meditation:
      "Pavel ceruse de trei ori să fie scutit și i s-a spus nu. Răspunsul lui Dumnezeu nu a fost o vindecare, ci o prezență suficientă. Sunt rugăciuni la care primim exact asta: nu scăpare, ci har cât să mai stai o zi.",
    question: "Ce ai cerut de mai multe ori și încă nu s-a schimbat?",
    prayer: "Doamne, dacă nu iei lucrul acesta, dă-mi har cât pentru azi. Atât cer. Amin.",
    step: "Cere azi har pentru următoarele douăsprezece ore, nu pentru tot.",
  },
  {
    id: "dev_087",
    dayNumber: 87,
    theme: LUNA_3,
    axis: "emotional_peace",
    verseRef: "Plângerile lui Ieremia 3:22-23",
    verseText: "Bunătățile Domnului nu s-au sfârșit, îndurările Lui nu sunt la capăt, ci se înnoiesc în fiecare dimineață. Și credincioșia Ta este atât de mare!",
    meditation:
      "Cartea se numește Plângeri — e scrisă după o catastrofă națională, nu într-o zi bună. Iar „în fiecare dimineață” înseamnă că nu se transferă: harul de ieri nu ține azi și nici nu trebuie. Se dă zilnic, ca mana.",
    question: "Te trezești azi cu impresia că ai consumat deja răbdarea lui Dumnezeu?",
    prayer: "Doamne, e dimineață. Îndurările Tale sunt noi, chiar dacă eu sunt același. Amin.",
    step: "Când te trezești mâine, spune versetul înainte să te ridici din pat.",
  },
  {
    id: "dev_088",
    dayNumber: 88,
    theme: LUNA_3,
    axis: "emotional_peace",
    verseRef: "Matei 6:34",
    verseText: "Nu vă îngrijorați dar de ziua de mâine; căci ziua de mâine se va îngrijora de ea însăși. Ajunge zilei necazul ei.",
    meditation:
      "Isus nu spune că mâine nu va fi greu. Spune că ai putere pentru o zi și că puterea nu se poate împrumuta înainte. Când duci azi și povara de mâine, ești singur cu greutatea a două zile într-una.",
    question: "Cât din greutatea ta de azi aparține, de fapt, zilei de mâine?",
    prayer: "Doamne, iau ziua asta. Mâine îți aparține oricum. Amin.",
    step: "Când te prinzi azi în mâine, spune-ți: „aia nu e ziua mea încă”.",
  },
  {
    id: "dev_089",
    dayNumber: 89,
    theme: LUNA_3,
    axis: "emotional_peace",
    verseRef: "Psalmul 62:8",
    verseText: "Popoare, în orice vreme, încredeți-vă în El, vărsați-vă inimile înaintea Lui! Dumnezeu este adăpostul nostru.",
    meditation:
      "„Vărsați” — nu „prezentați ordonat”. Dumnezeu nu are nevoie de o rugăciune structurată, ci de una golită până la fund. Cine își toarnă inima pe jumătate rămâne cu jumătate.",
    question: "Ce nu I-ai spus încă, deși ți-e în cap de săptămâni?",
    prayer: "Doamne, vars pe masa Ta tot ce am adunat. Nu mai aranjez nimic. Amin.",
    step: "Roagă-te azi cinci minute fără să alegi cuvintele. Poți și în gând.",
  },
  {
    id: "dev_090",
    dayNumber: 90,
    theme: LUNA_3,
    axis: "emotional_peace",
    verseRef: "Ioan 16:33",
    verseText: "V-am spus aceste lucruri ca să aveți pace în Mine. În lume veți avea necazuri, dar îndrăzniți, Eu am biruit lumea.",
    meditation:
      "E cea mai cinstită propoziție despre viață din toată Biblia: vor fi necazuri, spuse înainte să vină, ca să nu crezi că s-a stricat ceva când vin. Iar îndemnul nu stă pe optimism, ci pe un rezultat deja obținut. Luna asta se încheie aici: frica nu a dispărut, dar nu mai e singură în cameră.",
    question: "Ce s-a schimbat în felul în care îți vorbești în frică, față de ziua 61?",
    prayer: "Doamne, în lume am necazuri și Tu ai biruit lumea. Am nevoie de amândouă adevărurile. Amin.",
    step: "Scrie un rând despre o frică de acum o lună și unde e ea azi. Păstrează-l.",
  },
]
