// Devoțional, luna 6: „Ai tăi și singurătatea” (docs/27 §2.4, axa relationships).
//
// Regula lunii: singurătatea nu se rezolvă cu îndemnul „ieși mai mult între
// oameni”. Zilele merg pe două fire care se îmletesc: oamenii pe care Dumnezeu
// ți-i dă și prezența Lui în zilele când nu e nimeni. Nicăieri nu se sugerează că
// un om singur ar fi un om mai puțin iubit.
//
// Conținut ORIGINAL Emanus (docs/27 §1.2). Versete: Cornilescu (domeniu public).
import type { DevotionalDay } from "./devotional.js"

const LUNA_6 = "Ai tăi și singurătatea"

export const DEVOTIONAL_DAYS_LUNA_6: DevotionalDay[] = [
  {
    id: "dev_151",
    dayNumber: 151,
    theme: LUNA_6,
    axis: "relationships",
    verseRef: "Geneza 2:18",
    verseText: "Domnul Dumnezeu a zis: „Nu este bine ca omul să fie singur; am să-i fac un ajutor potrivit pentru el.”",
    meditation:
      "E prima dată când, într-o lume perfectă, Dumnezeu spune despre ceva că „nu este bine”. Deci dorul tău de cineva nu e un defect de caracter și nici lipsă de credință. A fost pus în tine înainte să existe păcatul.",
    question: "Te-ai judecat vreodată pentru că ți-e greu să fii singur?",
    prayer: "Doamne, Tu ai spus primul că nu e bine să fiu singur. Mulțumesc că nu ești supărat pe dorul meu. Amin.",
    step: "Spune-I azi, fără rușine, că ți-e singur — dacă așa e.",
  },
  {
    id: "dev_152",
    dayNumber: 152,
    theme: LUNA_6,
    axis: "relationships",
    verseRef: "Psalmul 68:6",
    verseText: "Dumnezeu dă o familie celor părăsiți, El izbăvește pe prinșii de război.",
    meditation:
      "Dumnezeu nu ține doar predici despre singurătate: așază oameni. În Biblie, răspunsul Lui la singurătate e aproape mereu o familie — uneori cea în care te-ai născut, de multe ori una pe care nu o alegi tu.",
    question: "Cine ți-a fost, în ultimii ani, familie fără să-ți fie rudă?",
    prayer: "Doamne, mulțumesc pentru oamenii pe care mi i-ai așezat. Dă-mi ochi să-i văd. Amin.",
    step: "Scrie trei nume de oameni care ți-au fost aproape și mulțumește pentru fiecare.",
  },
  {
    id: "dev_153",
    dayNumber: 153,
    theme: LUNA_6,
    axis: "relationships",
    verseRef: "Eclesiastul 4:9-10",
    verseText: "Mai bine doi decât unul... Căci, dacă se îmtimplă să cadă, se ridică unul pe altul; dar vai de cine este singur și cade, fără să aibă pe altul care să-l ridice!",
    meditation:
      "Textul nu spune că doi nu cad. Spune că unul singur rămâne jos. De aceea oamenii nu-ți trebuie ca să nu greșești, ci pentru ziua în care ai greșit deja.",
    question: "Cine ar ști, în 24 de ore, dacă ai cădea?",
    prayer: "Doamne, nu vreau să cad singur. Dă-mi un om căruia să-i pot spune. Amin.",
    step: "Alege azi o persoană căreia îi dai voie să te întrebe direct ce faci.",
  },
  {
    id: "dev_154",
    dayNumber: 154,
    theme: LUNA_6,
    axis: "relationships",
    verseRef: "Eclesiastul 4:12",
    verseText: "Funia împletită în trei nu se rupe ușor.",
    meditation:
      "Solomon urcă de la unul la doi și apoi la trei. Împletitura nu e o grămadă de oameni, ci câțiva legați bine. Nu ai nevoie de o mulțime; ai nevoie de doi-trei oameni care țin.",
    question: "Ai doi-trei oameni sau ai doar mulți cunoscuți?",
    prayer: "Doamne, dă-mi puțini și adevărați. Amin.",
    step: "Propune azi cuiva o întâlnire cu dată concretă, nu un „ne mai vedem”.",
  },
  {
    id: "dev_155",
    dayNumber: 155,
    theme: LUNA_6,
    axis: "relationships",
    verseRef: "Proverbe 18:24",
    verseText: "Cine își face mulți prieteni îi face spre paguba lui, dar este un prieten care ține mai mult la tine decât un frate.",
    meditation:
      "Proverbul opune cantitatea calității și o face fără menajamente. Astăzi e și mai ușor să aduni oameni și să n-ai pe nimeni. Prietenia adevărată se cunoaște după ce rămâne când nu mai ești de folos.",
    question: "Ai un prieten pe care l-ai putea suna la 3 dimineața?",
    prayer: "Doamne, nu-mi trebuie mulți. Îmi trebuie unul care rămâne. Amin.",
    step: "Scrie-i azi acelui om, fără motiv și fără să ceri nimic.",
  },
  {
    id: "dev_156",
    dayNumber: 156,
    theme: LUNA_6,
    axis: "relationships",
    verseRef: "Proverbe 17:17",
    verseText: "Prietenul adevărat iubește oricând și în nenorocire ajunge ca un frate.",
    meditation:
      "„Oricând” include și perioada în care ești greu de suportat. Multe prietenii se sting nu într-o ceartă, ci într-o iarnă lungă în care unul dintre ei n-a mai avut ce oferi. Fii tu, pentru cineva, prietenul din iarnă.",
    question: "Cine trece acum printr-o iarnă și nu prea mai are ce oferi?",
    prayer: "Doamne, fă-mă om de nenorocire, nu doar de sărbătoare. Amin.",
    step: "Caută azi pe cineva de care s-a cam îndepărtat lumea.",
  },
  {
    id: "dev_157",
    dayNumber: 157,
    theme: LUNA_6,
    axis: "relationships",
    verseRef: "Proverbe 27:6",
    verseText: "Rănile făcute de un prieten dovedesc credincioșia lui, dar sărutările unui vrăjmaș sunt mincinoase.",
    meditation:
      "Un prieten adevărat te poate răni, pentru că îți spune ce nu vrei să auzi. Cine îți dă mereu dreptate nu te iubește neapărat; poate doar nu vrea complicații. Verifică-ți cercul: are cineva voie să te contrazică?",
    question: "Cine te-a contrazis ultima dată din dragoste?",
    prayer: "Doamne, dă-mi oameni care îmi spun adevărul și inimă să-l primesc. Amin.",
    step: "Întreabă azi pe cineva apropiat: „Ce vezi la mine și nu-mi spui?”",
  },
  {
    id: "dev_158",
    dayNumber: 158,
    theme: LUNA_6,
    axis: "relationships",
    verseRef: "Proverbe 27:17",
    verseText: "După cum fierul ascute fierul, tot așa și omul ațâță mânia altui om.",
    meditation:
      "Imaginea e limpede: două bucăți de metal se ating cu scrâșnet, dar ies mai tăioase. Relațiile care te șlefuiesc nu sunt întotdeauna comode. O prietenie fără nicio frecare probabil e prea superficială ca să schimbe pe cineva.",
    question: "Fugi de conflict sau înveți din el?",
    prayer: "Doamne, dă-mi răbdare cu oamenii care mă șlefuiesc. Amin.",
    step: "Nu evita azi o discuție necesară doar ca să fie liniște.",
  },
  {
    id: "dev_159",
    dayNumber: 159,
    theme: LUNA_6,
    axis: "relationships",
    verseRef: "Iov 2:13",
    verseText: "Și au șezut pe pământ lângă el șapte zile și șapte nopți, fără să-i spună o vorbă, căci vedeau cât de mare îi este durerea.",
    meditation:
      "Prietenii lui Iov au fost desavârșiți șapte zile: au tăcut. Necazul a început când au deschis gura ca să explice suferința. Cel mai bun lucru pe care îl poți face pentru un om lovit e să stai jos lângă el.",
    question: "Te grăbești să explici sau poți să stai în tăcere?",
    prayer: "Doamne, învață-mă să tac lângă cei care suferă. Amin.",
    step: "Stai azi cu cineva la greu fără să-i dai niciun sfat.",
  },
  {
    id: "dev_160",
    dayNumber: 160,
    theme: LUNA_6,
    axis: "relationships",
    verseRef: "Rut 1:16",
    verseText: "Unde vei merge tu, voi merge și eu; unde vei locui tu, voi locui și eu; poporul tău va fi poporul meu și Dumnezeul tău va fi Dumnezeul meu.",
    meditation:
      "Rut spune asta unei femei sărace, amărâte și fără nimic de oferit. Nu era o alegere înțeleaptă din niciun punct de vedere practic. Așa arată legământul: rămâi și când nu mai iese nimic din relația aceea.",
    question: "Cui i-ai rămas alături când nu mai era nimic de câștigat?",
    prayer: "Doamne, fă-mă om de legământ, nu de socoteală. Amin.",
    step: "Reia azi legătura cu cineva de care te-ai depărtat pentru că „nu mai aveam ce vorbi”.",
  },
  {
    id: "dev_161",
    dayNumber: 161,
    theme: LUNA_6,
    axis: "relationships",
    verseRef: "1 Samuel 18:1",
    verseText: "Sufletul lui Ionatan s-a alipit de sufletul lui David și Ionatan l-a iubit ca pe sufletul din el.",
    meditation:
      "Ionatan era fiul regelui și moștenitorul de drept; David era cel care îi lua tronul. Prietenia lor a fost posibilă pentru că Ionatan n-a fost gelos. Invidia e cea care omoară cele mai multe prietenii bărbătești și femeiești, nu distanța.",
    question: "Pe cine nu poți iubi din toată inima pentru că îi merge mai bine?",
    prayer: "Doamne, scoate invidia din prieteniile mele. Amin.",
    step: "Bucură-te azi, cu voce tare, de reușita cuiva care te înțeapă puțin.",
  },
  {
    id: "dev_162",
    dayNumber: 162,
    theme: LUNA_6,
    axis: "relationships",
    verseRef: "1 Samuel 23:16",
    verseText: "Atunci Ionatan, fiul lui Saul, s-a sculat și s-a dus la David în pădure. El i-a întărit încrederea în Dumnezeu.",
    meditation:
      "Ionatan s-a dus în pădure, adică acolo unde era David, nu unde îi era lui comod. Și n-a venit să-l încurajeze cu vorbe generale, ci să-i întărească încrederea în Dumnezeu. Cea mai bună prietenie te duce înapoi la El, nu la ea însăși.",
    question: "Prietenia ta cea mai apropiată te apropie de Dumnezeu sau te ține departe?",
    prayer: "Doamne, fă-mă om care întărește credința altora. Amin.",
    step: "Trimite-i azi cuiva un verset potrivit pentru ce trece el, nu unul la întâmplare.",
  },
  {
    id: "dev_163",
    dayNumber: 163,
    theme: LUNA_6,
    axis: "relationships",
    verseRef: "Exod 17:12",
    verseText: "Mâinile lui Moise fiind trudite, ei au luat o piatră... iar Aaron și Hur îi sprijineau mâinile, unul de o parte, iar altul de alta.",
    meditation:
      "Bătălia se câștiga atât timp cât mâinile lui Moise erau ridicate — și mâinile lui au obosit, ca ale oricui. Doi oameni au stat, ore întregi, doar ca să țină brațele altcuiva. Uneori asta e toată slujba ta în viața cuiva.",
    question: "Cui îi ții tu mâinile ridicate?",
    prayer: "Doamne, arată-mi pe cine trebuie să sprijin azi. Amin.",
    step: "Fă pentru cineva un lucru practic — o mâncare, un drum, o oră de ajutor.",
  },
  {
    id: "dev_164",
    dayNumber: 164,
    theme: LUNA_6,
    axis: "relationships",
    verseRef: "Marcu 2:4",
    verseText: "Fiindcă nu puteau să ajungă până la El din pricina norodului, au desfăcut acoperișul casei... și au coborât pe acolo patul în care zăcea slăbănogul.",
    meditation:
      "Omul acela n-a ajuns la Isus pe picioarele lui, ci pe credința a patru prieteni care au stricat un acoperiș. Sunt zile în care cineva trebuie să te ducă. Și sunt zile în care tu ești unul dintre cei patru.",
    question: "Pe cine duci tu, acum, la Dumnezeu în rugăciune?",
    prayer: "Doamne, îl aduc înaintea Ta. Nu poate veni singur. Amin.",
    step: "Roagă-te azi, cu numele, pentru un om care nu se poate ruga pentru el.",
  },
  {
    id: "dev_165",
    dayNumber: 165,
    theme: LUNA_6,
    axis: "relationships",
    verseRef: "Fapte 2:46",
    verseText: "Toti împreună, în fiecare zi, stăruiau în Templu, frângeau pâinea acasă și luau hrana cu bucurie și curăție de inimă.",
    meditation:
      "Biserica de la început a crescut între două locuri: Templul și bucătăria. Nu totul se petrece în adunări mari; mult din viața creștină se întâmplă la o masă, cu oameni care nu se grăbesc.",
    question: "Când ai avut ultima dată pe cineva la masă, fără ocazie specială?",
    prayer: "Doamne, deschide-mi casa, chiar dacă nu e perfectă. Amin.",
    step: "Cheamă azi pe cineva la o masă simplă săptămâna asta.",
  },
  {
    id: "dev_166",
    dayNumber: 166,
    theme: LUNA_6,
    axis: "relationships",
    verseRef: "Evrei 10:24-25",
    verseText: "Să veghem unii asupra altora, ca să ne îndemnăm la dragoste și la fapte bune. Să nu părăsim adunarea noastră, cum au unii obicei.",
    meditation:
      "Motivul dat nu e „că așa se cade”, ci ca să ne îndemnăm unii pe alții. Credința ținută numai în privat se stinge încet, fără dramă, ca un jar scos din foc. Nu ai nevoie de o adunare perfectă, ci de una reală.",
    question: "Ce te ține departe de oamenii credinței: rănirea, rușinea sau comoditatea?",
    prayer: "Doamne, ajută-mă să nu mă izolez. Amin.",
    step: "Fă azi un pas înapoi spre o comunitate: un mesaj, o întrebare, o prezență.",
  },
  {
    id: "dev_167",
    dayNumber: 167,
    theme: LUNA_6,
    axis: "relationships",
    verseRef: "Romani 12:15",
    verseText: "Bucurați-vă cu cei ce se bucură; plângeți cu cei ce plâng.",
    meditation:
      "Amintirea e în două direcții și nu știu care e mai grea. Să plângi cu cineva cere timp; să te bucuri cu cineva cere să nu fii invidios. Cine reușește amândouă e un om rar.",
    question: "Care îți vine mai greu: plânsul cu cineva sau bucuria pentru cineva?",
    prayer: "Doamne, dă-mi o inimă care ține pasul cu inimile altora. Amin.",
    step: "Sună azi pe cineva care sărbătorește ceva și pe cineva care jelește ceva.",
  },
  {
    id: "dev_168",
    dayNumber: 168,
    theme: LUNA_6,
    axis: "relationships",
    verseRef: "Galateni 6:2",
    verseText: "Purtați-vă sarcinile unii altora și veți împlini astfel Legea lui Hristos.",
    meditation:
      "Câteva rânduri mai jos, Pavel spune că fiecare își va purta și propria povară. Nu e o contradicție: sunt greutăți care te strivesc și trebuie împărțite, și responsabilități care rămân ale tale. Înțelepciunea e să știi ce ceri și ce duci.",
    question: "Ce greutate duci singur, deși cineva ar putea-o împărți cu tine?",
    prayer: "Doamne, dă-mi smerenia să cer ajutor. Amin.",
    step: "Cere azi ajutor pentru un lucru concret. Cere, nu sugera.",
  },
  {
    id: "dev_169",
    dayNumber: 169,
    theme: LUNA_6,
    axis: "relationships",
    verseRef: "Iacov 5:16",
    verseText: "Mărturisiți-vă unii altora păcatele și rugați-vă unii pentru alții, ca să fiți vindecați.",
    meditation:
      "Singurătatea cea mai grea nu e să n-ai oameni în jur, ci să nu știe nimeni cine ești cu adevărat. Un secret ținut ani de zile te izolează chiar și într-o casă plină. Vindecarea e legată aici de a fi cunoscut.",
    question: "Există un om care știe și partea aceea din tine?",
    prayer: "Doamne, dă-mi curaj să ies din ascunzătoare, măcar în fața unui om. Amin.",
    step: "Spune azi unui om de încredere un lucru adevărat despre tine, chiar dacă e mic.",
  },
  {
    id: "dev_170",
    dayNumber: 170,
    theme: LUNA_6,
    axis: "relationships",
    verseRef: "Ioan 13:35",
    verseText: "Prin aceasta vor cunoaște toți că sunteți ucenicii Mei, dacă veți avea dragoste unii pentru alții.",
    meditation:
      "Semnul pus de Isus nu e nici cunoștința, nici curajul, nici succesul. E felul în care ne purtăm unii cu alții. Lumea nu citește teologia noastră; se uită la cum vorbim despre frații noștri.",
    question: "Ce ar înțelege cineva despre Hristos privindu-te în relațiile tale?",
    prayer: "Doamne, să se vadă în purtarea mea al cui sunt. Amin.",
    step: "Vorbește azi frumos despre un creștin cu care nu ești de acord.",
  },
  {
    id: "dev_171",
    dayNumber: 171,
    theme: LUNA_6,
    axis: "relationships",
    verseRef: "Psalmul 25:16",
    verseText: "Întoarce-Ti Fața spre mine și ai milă de mine, căci sunt părăsit și nenorocit.",
    meditation:
      "Biblia nu-i cere omului singur să se prefacă bine. David își spune starea pe nume și o pune înaintea lui Dumnezeu. E o rugăciune scurtă, pe care o poți ține minte pentru serile grele.",
    question: "Ai spus vreodată în rugăciune, exact așa: „sunt singur”?",
    prayer: "Doamne, întoarce-Ți fața spre mine. Sunt singur. Amin.",
    step: "Când te lovește azi singurătatea, spune versetul ăsta în loc să deschizi telefonul.",
  },
  {
    id: "dev_172",
    dayNumber: 172,
    theme: LUNA_6,
    axis: "relationships",
    verseRef: "Psalmul 142:4",
    verseText: "Aruncă-ți ochii la dreapta și privește! Nimeni nu mă mai cunoaște, orice scăpare este pierdută pentru mine, nimănui nu-i pasă de sufletul meu.",
    meditation:
      "Psalmul a fost scris într-o peșteră. Faptul că stă în Biblie înseamnă că Dumnezeu a păstrat intenționat, în cartea Lui, propoziția „nimănui nu-i pasă de sufletul meu”. Nu ți se cere să o cenșurezi când o simți.",
    question: "Ce ai spune dacă ai avea voie să fii complet sincer cu Dumnezeu?",
    prayer: "Doamne, Îți spun tot, chiar și partea urâtă. Amin.",
    step: "Scrie azi o rugăciune necenzurată. Nu o citește nimeni în afară de El.",
  },
  {
    id: "dev_173",
    dayNumber: 173,
    theme: LUNA_6,
    axis: "relationships",
    verseRef: "2 Timotei 4:16-17",
    verseText: "La întâiul meu răspuns de apărare, nimeni n-a fost cu mine, ci toți m-au părăsit... Însă Domnul a stătut lângă mine și m-a întărit.",
    meditation:
      "Pavel scrie asta la sfârșitul vieții, după zeci de ani de slujire și sute de oameni ajutați. Chiar și așa, a existat o zi în care n-a venit nimeni. Și tot atunci a învățat că Cineva stă lângă tine exact când nu mai stă nimeni.",
    question: "Unde a fost Dumnezeu în cea mai singură zi a ta?",
    prayer: "Doamne, mulțumesc că ai fost lângă mine când nu Știam. Amin.",
    step: "Amintește-ți o zi grea din trecut și caută un semn că nu ai fost singur.",
  },
  {
    id: "dev_174",
    dayNumber: 174,
    theme: LUNA_6,
    axis: "relationships",
    verseRef: "Ioan 16:32",
    verseText: "Iată că vine ceasul... când veți fi risipiți fiecare la ale lui și pe Mine Mă veți lăsa singur; dar nu sunt singur, căci Tatăl este cu Mine.",
    meditation:
      "Isus a fost lăsat singur de toți prietenii Lui, deci știe exact cum e. Și, chiar în propoziția în care recunoaște asta, spune unde își ține sprijinul. Singurătatea nu e o experiență străină pentru Cel căruia I te rogi.",
    question: "Te ajută să știi că El a trecut prin asta?",
    prayer: "Doamne Isuse, Tu ai fost părăsit. Știi cum e. Stai cu mine. Amin.",
    step: "Citește azi Ioan 16 și subliniază ce spune Isus despre singurătate.",
  },
  {
    id: "dev_175",
    dayNumber: 175,
    theme: LUNA_6,
    axis: "relationships",
    verseRef: "Matei 26:40",
    verseText: "Apoi a venit la ucenici, i-a găsit dormind și a zis lui Petru: „Ce, un ceas n-ați putut să vegheați împreună cu Mine?”",
    meditation:
      "În cea mai grea noapte a Lui, Isus a cerut companie — nu soluții, ci prezență — și prietenii au adormit. Ceruse și El ceva simplu. Data viitoare când cineva îți cere doar să fii acolo, adu-ți aminte de grădina asta.",
    question: "Cine te-a chemat să-i stai alături și tu ai fost prea obosit?",
    prayer: "Doamne, iartă-mă că am dormit când cineva avea nevoie de mine. Amin.",
    step: "Oferă-i azi cuiva o oră din timpul tău, fără să fii cu ochii pe ceas.",
  },
  {
    id: "dev_176",
    dayNumber: 176,
    theme: LUNA_6,
    axis: "relationships",
    verseRef: "Evrei 13:5",
    verseText: "Căci El Însuși a zis: „Nicidecum n-am să te las, cu niciun chip nu te voi părăsi.”",
    meditation:
      "În original, negațiile se îngrămădesc — e cea mai apasată promisiune de acest fel din Noul Testament. Oamenii pleacă, uneori fără vina lor: se mută, se sting, se schimbă. Promisiunea asta e făcută de Cineva care nu are cum să plece.",
    question: "Pe cine ai pierdut și te temi că Și El va pleca la fel?",
    prayer: "Doamne, Tu nu pleci. Îmi lipește inima de promisiunea asta. Amin.",
    step: "Învață azi versetul pe de rost. Are opt cuvinte care țin.",
  },
  {
    id: "dev_177",
    dayNumber: 177,
    theme: LUNA_6,
    axis: "relationships",
    verseRef: "Psalmul 139:7-8",
    verseText: "Unde mă voi duce departe de Duhul Tău și unde voi fugi departe de Fața Ta? Dacă mă voi sui în cer, Tu ești acolo; dacă mă voi culca în locuința morților, iată-Te și acolo.",
    meditation:
      "Psalmul numără locurile în care ai putea fi singur și le taie pe rând. Nu există cameră, spital, celulă sau țară străină în care să fii în afara razei Lui. Nu simți mereu asta — dar simțirea nu schimbă geografia.",
    question: "În ce loc ți-e cel mai greu să crezi că El e de față?",
    prayer: "Doamne, ești și în camera asta. Chiar dacă nu Te simt. Amin.",
    step: "Spune cu voce tare, în locul în care ți-e cel mai singur: „Ești și aici”.",
  },
  {
    id: "dev_178",
    dayNumber: 178,
    theme: LUNA_6,
    axis: "relationships",
    verseRef: "Isaia 41:9",
    verseText: "Tu ești robul Meu, te aleg și nu te lepăd!",
    meditation:
      "Sunt oameni care poartă toată viața senzația că au fost alegăi ultimii. Versetul ăsta răstoarnă ordinea: Dumnezeu alege primul și nu retrage alegerea. Nu ești tolerat în familia Lui; ești dorit.",
    question: "Te-ai simțit vreodată ales ultimul?",
    prayer: "Doamne, mulțumesc că m-ai ales și nu mă lepezi. Amin.",
    step: "Scrie versetul ăsta și pune-l unde te îmbraci dimineața.",
  },
  {
    id: "dev_179",
    dayNumber: 179,
    theme: LUNA_6,
    axis: "relationships",
    verseRef: "1 Petru 4:9",
    verseText: "Fiți primitori de oaspeți între voi, fără cârtire.",
    meditation:
      "Leacul singurătății începe surprinzător de des cu a face tu loc altcuiva. Nu pentru că așa se merită ceva, ci pentru că omul închis în lipsa lui nu mai vede nevoia nimănui. „Fără cârtire” înseamnă și fără să aștepți recunoștință.",
    question: "Cine e mai singur decât tine și stă la doi pași?",
    prayer: "Doamne, scoate-mă din mine și îndreaptă-mă spre cineva. Amin.",
    step: "Vorbește azi cu un vecin sau un om în vârstă pe lângă care treci mereu.",
  },
  {
    id: "dev_180",
    dayNumber: 180,
    theme: LUNA_6,
    axis: "relationships",
    verseRef: "Efeseni 2:19",
    verseText: "Așadar, voi nu mai sunteți nici străini, nici oaspeți ai casei, ci sunteți îmreună-cetățeni cu sfinții, oameni din casa lui Dumnezeu.",
    meditation:
      "S-a încheiat jumătate de an. Versetul spune trei lucruri: nu ești străin, nu ești musafir, ești de-al casei. Un musafir se poartă frumos și pleacă; un om al casei rămâne și când e dezordine. De luna viitoare vorbim despre rugăciune — limba în care se vorbește în casa asta.",
    question: "Te porți ca un musafir sau ca un om de-al casei?",
    prayer: "Doamne, mulțumesc că am unde să aparțin. Amin.",
    step: "Fă azi un lucru pe care îl face un om de-al casei, nu un oaspete: curăță, ajută, rămâi.",
  },
]
