// Carduri pentru casă: neiertare, casa ruptă, copilul depărtat (docs/41 §3).
//
// Aici era și gaura cea mai mare din cele 45 de carduri vechi: axa
// `relationships` avea UN SINGUR card. Omul care intră în aplicație cu o casă
// ruptă primea, de fapt, răspunsuri scrise pentru altceva.
//
// REGULA (docs/00-DIRECTIE §7, D-005): fiecare `body` este parafraza unui
// verset REAL, iar `verseRef` apare pe card, la vedere.
//
// REGULĂ DE TON pentru casa ruptă: nu se scrie niciun card care să-i spună
// omului ce ar fi trebuit să facă. Cine deschide ușa asta e deja acuzat de
// toată lumea din jur.
//
// REGULĂ DE TON pentru neiertare: nu se cere iertarea ca și cum ar fi ușoară,
// și nu se spune nicăieri că omul trebuie să se întoarcă unde e lovit.
//
// `verseText` este fraza-cheie, nu versetul întreg (docs/39).
// DE COLAȚIONAT: versetele nu au trecut încă prin citirea de om (docs/41 §6.6).
import type { MessageCard } from "./messageCards.js"

/** Nu pot să iert în familie. */
export const CARDS_NEIERTARE: MessageCard[] = [
  {
    id: "msg_nu_un_vrajmas",
    title: "Ce îți spune Dumnezeu astăzi, din Cuvântul Său:",
    body: "Nu un dușman te-a rănit, ci unul de-al tău. Știu cât doare asta.",
    verseRef: "Psalmul 55:12-13",
    verseText: "Ci tu, om deopotrivă cu mine, prietenul meu și cunoscutul meu!",
    axis: "relationships",
    needs: ["neiertare", "casa_rupta"],
    background: "pergament-umbra",
  },
  {
    id: "msg_iarta_cum_te_am_iertat",
    title: "Dumnezeu ți-a spus deja:",
    body: "Iartă cum te-am iertat Eu. Aceea e măsura, nu cât merită el.",
    verseRef: "Efeseni 4:32",
    verseText: "Iertați-vă unul pe altul, cum v-a iertat și Dumnezeu pe voi în Hristos.",
    axis: "relationships",
    needs: ["neiertare"],
    background: "pergament",
  },
  {
    id: "msg_de_saptezeci_de_ori",
    title: "Ce îți spune Dumnezeu astăzi, din Cuvântul Său:",
    body: "Nu de șapte ori. De șaptezeci de ori câte șapte.",
    verseRef: "Matei 18:22",
    verseText: "Eu îți zic nu până la șapte ori, ci până la șaptezeci de ori câte șapte.",
    axis: "relationships",
    needs: ["neiertare"],
    background: "pergament",
  },
  {
    id: "msg_cand_stai_sa_te_rogi",
    title: "Ce îți spune Dumnezeu astăzi, din Cuvântul Său:",
    body: "Când stai să te rogi, iartă. Rugăciunea și ura nu încap în aceeași inimă.",
    verseRef: "Marcu 11:25",
    verseText: "Când stați în picioare de vă rugați, să iertați.",
    axis: "living_faith",
    needs: ["neiertare", "rugaciune_fara_raspuns"],
    background: "pergament",
  },
  {
    id: "msg_nu_te_razbuna_singur",
    title: "Dumnezeu ți-a spus deja:",
    body: "Nu te răzbuna singur. Răzbunarea este a Mea.",
    verseRef: "Romani 12:19",
    verseText: "Răzbunarea este a Mea; Eu voi răsplăti, zice Domnul.",
    axis: "character",
    needs: ["neiertare"],
    background: "pergament-umbra",
  },
  {
    id: "msg_sa_nu_apuna_soarele",
    title: "Ce îți spune Dumnezeu astăzi, din Cuvântul Său:",
    body: "Poți să fii mâniat. Dar nu lăsa soarele să apună peste mânia ta.",
    verseRef: "Efeseni 4:26",
    verseText: "Mâniați-vă și nu păcătuiți. Să n-apună soarele peste mânia voastră.",
    axis: "character",
    needs: ["neiertare"],
    background: "pergament",
  },
  {
    id: "msg_radacina_de_amaraciune",
    title: "Ce îți spune Dumnezeu astăzi, din Cuvântul Său:",
    body: "Păzește-te de rădăcina de amărăciune. Crește la întuneric și otrăvește mulți.",
    verseRef: "Evrei 12:15",
    verseText: "Să nu răsară vreo rădăcină de amărăciune.",
    axis: "character",
    needs: ["neiertare"],
    background: "pergament-umbra",
  },
  {
    id: "msg_tata_iarta_i",
    title: "Ce îți spune Dumnezeu astăzi, din Cuvântul Său:",
    body: "De pe cruce am spus: Tată, iartă-i. Știu ce cer de la tine când îți cer să ierți.",
    verseRef: "Luca 23:34",
    verseText: "Tată, iartă-i, căci nu știu ce fac!",
    axis: "relationships",
    needs: ["neiertare"],
    background: "pergament-cald",
  },
  {
    id: "msg_raul_schimbat_in_bine",
    title: "Ce îți spune Dumnezeu astăzi, din Cuvântul Său:",
    body: "Ei ți-au gândit răul. Eu pot să întorc răul acela în bine.",
    verseRef: "Geneza 50:20",
    verseText: "Voi, negreșit, v-ați gândit să-mi faceți rău, dar Dumnezeu a schimbat răul în bine.",
    axis: "living_faith",
    needs: ["neiertare", "de_ce"],
    background: "pergament",
  },
  {
    id: "msg_iubiti_pe_vrajmasi",
    title: "Ce îți spune Dumnezeu astăzi, din Cuvântul Său:",
    body: "Roagă-te pentru cel care te-a asuprit. Ai voie să începi cu atât.",
    verseRef: "Matei 5:44",
    verseText: "Rugați-vă pentru cei ce vă asupresc.",
    axis: "character",
    needs: ["neiertare"],
    background: "pergament",
  },
  {
    id: "msg_ingaduiti_va_unii_pe_altii",
    title: "Dumnezeu ți-a spus deja:",
    body: "Dacă ai să te plângi de cineva, iartă-l. Așa cum te-am iertat Eu.",
    verseRef: "Coloseni 3:13",
    verseText: "Îndurați-vă unii pe alții și iertați-vă unul pe altul.",
    axis: "relationships",
    needs: ["neiertare"],
    background: "pergament",
  },
  {
    id: "msg_daca_iertati_oamenilor",
    title: "Dumnezeu ți-a spus deja:",
    body: "Dacă ierți oamenilor greșelile lor, și Tatăl vostru ceresc vă va ierta.",
    verseRef: "Matei 6:14",
    verseText: "Dacă iertați oamenilor greșelile lor, și Tatăl vostru ceresc vă va ierta greșelile voastre.",
    axis: "relationships",
    needs: ["neiertare", "vinovat"],
    background: "pergament",
  },
]

/** S-a rupt casa mea. */
export const CARDS_CASA_RUPTA: MessageCard[] = [
  {
    id: "msg_tatal_si_mama_ma_parasesc",
    title: "Dumnezeu ți-a spus deja:",
    body: "Chiar dacă te lasă ai tăi, Eu te primesc.",
    verseRef: "Psalmul 27:10",
    verseText: "Căci tatăl meu și mama mea mă părăsesc, dar Domnul mă primește.",
    axis: "identity",
    needs: ["casa_rupta", "singur"],
    background: "pergament-cald",
  },
  {
    id: "msg_facatorul_tau_iti_este_barbat",
    title: "Dumnezeu ți-a spus deja:",
    body: "Făcătorul tău îți este bărbat. Nu rămâi fără apărător.",
    verseRef: "Isaia 54:5",
    verseText: "Căci Făcătorul tău este bărbatul tău.",
    axis: "identity",
    needs: ["casa_rupta"],
    background: "pergament-cald",
  },
  {
    id: "msg_te_chem_ca_pe_o_femeie_parasita",
    title: "Dumnezeu ți-a spus deja:",
    body: "Te chem ca pe unul părăsit și cu inima întristată. Nu te-am dat afară.",
    verseRef: "Isaia 54:6",
    verseText: "Domnul te cheamă înapoi ca pe o femeie părăsită și cu inima întristată.",
    axis: "identity",
    needs: ["casa_rupta", "singur"],
    background: "pergament-umbra",
  },
  {
    id: "msg_ii_vorbesc_pe_placul_inimii",
    title: "Dumnezeu ți-a spus deja:",
    body: "Te duc în pustie și acolo îți vorbesc pe placul inimii tale.",
    verseRef: "Osea 2:14",
    verseText: "O voi duce în pustie și Îi voi vorbi pe placul inimii ei.",
    axis: "relationships",
    needs: ["casa_rupta", "singur"],
    background: "pergament-cald",
  },
  {
    id: "msg_uitat_de_inimi",
    title: "Ce îți spune Dumnezeu astăzi, din Cuvântul Său:",
    body: "Te simți uitat de inimile oamenilor, ca un mort. Eu nu te-am uitat.",
    verseRef: "Psalmul 31:12",
    verseText: "Sunt uitat de inimi ca un mort.",
    axis: "emotional_peace",
    needs: ["casa_rupta", "singur", "departe"],
    background: "pergament-umbra",
  },
  {
    id: "msg_anii_mancati_de_lacuste",
    title: "Dumnezeu ți-a spus deja:",
    body: "Îți dau înapoi anii pe care i-au mâncat lăcustele.",
    verseRef: "Ioel 2:25",
    verseText: "Vă voi răsplăti astfel anii pe care i-au mâncat lăcustele.",
    axis: "freedom",
    needs: ["casa_rupta", "in_asteptare"],
    background: "pergament-cald",
  },
  {
    id: "msg_cununa_in_loc_de_cenusa",
    title: "Dumnezeu ți-a spus deja:",
    body: "Îți dau cunună în loc de cenușă și untdelemn de bucurie în loc de plâns.",
    verseRef: "Isaia 61:3",
    verseText: "Să le dau o cunună împărătească în loc de cenușă.",
    axis: "freedom",
    needs: ["casa_rupta", "doliu"],
    background: "pergament-cald",
  },
  {
    id: "msg_ajutor_care_nu_lipseste",
    title: "Ce îți spune Dumnezeu astăzi, din Cuvântul Său:",
    body: "Sunt adăpostul tău, un ajutor care nu lipsește niciodată la nevoie.",
    verseRef: "Psalmul 46:1",
    verseText: "Dumnezeu este adăpostul și sprijinul nostru, un ajutor care nu lipsește niciodată în nevoi.",
    axis: "emotional_peace",
    needs: ["casa_rupta", "speriat"],
    background: "pergament",
  },
  {
    id: "msg_intrucat_atarna_de_tine",
    title: "Ce îți spune Dumnezeu astăzi, din Cuvântul Său:",
    body: "Întrucât atârnă de tine, trăiește în pace. Restul nu stă în mâna ta.",
    verseRef: "Romani 12:18",
    verseText: "Dacă este cu putință, întrucât atârnă de voi, trăiți în pace cu toți oamenii.",
    axis: "relationships",
    needs: ["casa_rupta", "neiertare"],
    background: "pergament",
  },
  {
    id: "msg_drum_prin_pustie",
    title: "Dumnezeu ți-a spus deja:",
    body: "Fac ceva nou. Fac un drum prin pustie și râuri în locurile secetoase.",
    verseRef: "Isaia 43:19",
    verseText: "Iată că voi face ceva nou și-i gata să se întâmple.",
    axis: "living_faith",
    needs: ["casa_rupta", "fara_directie"],
    background: "pergament-cald",
  },
]

/** Copilul meu s-a depărtat. */
export const CARDS_COPIL_DEPARTAT: MessageCard[] = [
  {
    id: "msg_las_cele_nouazeci_si_noua",
    title: "Dumnezeu ți-a spus deja:",
    body: "Las cele nouăzeci și nouă și Mă duc după cea pierdută până o găsesc.",
    verseRef: "Luca 15:4",
    verseText: "Se duce după cea pierdută până când o găsește.",
    axis: "relationships",
    needs: ["copil_departat"],
    background: "pergament-cald",
  },
  {
    id: "msg_matur_casa",
    title: "Ce îți spune Dumnezeu astăzi, din Cuvântul Său:",
    body: "Aprind lumina și mătur casa până găsesc ce s-a pierdut.",
    verseRef: "Luca 15:8",
    verseText: "Aprinde o lumină, mătură casa și caută cu băgare de seamă.",
    axis: "relationships",
    needs: ["copil_departat"],
    background: "pergament",
  },
  {
    id: "msg_voi_scapa_pe_fiii_tai",
    title: "Dumnezeu ți-a spus deja:",
    body: "Voi lupta împotriva celor ce se ceartă cu tine și voi scăpa pe copiii tăi.",
    verseRef: "Isaia 49:25",
    verseText: "Eu voi lupta împotriva celor ce se ceartă cu tine și voi scăpa pe fiii tăi.",
    axis: "relationships",
    needs: ["copil_departat"],
    background: "pergament",
  },
  {
    id: "msg_toti_fiii_tai_ucenici",
    title: "Dumnezeu ți-a spus deja:",
    body: "Copiii tăi vor fi învățați de Domnul și mare va fi pacea lor.",
    verseRef: "Isaia 54:13",
    verseText: "Toți fiii tăi vor fi ucenici ai Domnului și mare va fi propașirea fiilor tăi.",
    axis: "relationships",
    needs: ["copil_departat", "in_asteptare"],
    background: "pergament-cald",
  },
  {
    id: "msg_opreste_ti_plansul",
    title: "Dumnezeu ți-a spus deja:",
    body: "Oprește-ți plânsul. Este nădejde pentru urmașii tăi.",
    verseRef: "Ieremia 31:16-17",
    verseText: "Oprește-ți plânsul... este nădejde pentru urmașii tăi.",
    axis: "relationships",
    needs: ["copil_departat", "in_asteptare"],
    background: "pergament-umbra",
  },
  {
    id: "msg_invata_pe_copil_calea",
    title: "Ce îți spune Dumnezeu astăzi, din Cuvântul Său:",
    body: "Ce ai semănat în el nu s-a pierdut. Când va îmbătrâni, nu se va abate de la ea.",
    verseRef: "Proverbele 22:6",
    verseText: "Învață pe copil calea pe care trebuie s-o urmeze, și când va îmbătrâni, nu se va abate de la ea.",
    axis: "relationships",
    needs: ["copil_departat"],
    background: "pergament",
  },
  {
    id: "msg_tu_si_casa_ta",
    title: "Dumnezeu ți-a spus deja:",
    body: "Crede în Domnul Isus — tu și casa ta.",
    verseRef: "Faptele Apostolilor 16:31",
    verseText: "Crede în Domnul Isus și vei fi mântuit tu și casa ta.",
    axis: "relationships",
    needs: ["copil_departat", "casa_rupta"],
    background: "pergament-cald",
  },
  {
    id: "msg_din_fundul_marii",
    title: "Ce îți spune Dumnezeu astăzi, din Cuvântul Său:",
    body: "Chiar din fundul mării, dacă strigă la Mine, Îl aud.",
    verseRef: "Iona 2:2",
    verseText: "În strâmtorarea mea am chemat pe Domnul, și m-a ascultat.",
    axis: "living_faith",
    needs: ["copil_departat", "departe"],
    background: "pergament-umbra",
  },
  {
    id: "msg_niciunul_sa_nu_piara",
    title: "Dumnezeu ți-a spus deja:",
    body: "Am răbdare îndelungată. Nu vreau ca vreunul să piară.",
    verseRef: "2 Petru 3:9",
    verseText: "Are o îndelungă răbdare pentru voi și dorește ca niciunul să nu piară.",
    axis: "living_faith",
    needs: ["copil_departat", "in_asteptare"],
    background: "pergament",
  },
  {
    id: "msg_era_pierdut_si_a_fost_gasit",
    title: "Ce îți spune Dumnezeu astăzi, din Cuvântul Său:",
    body: "În ziua când se întoarce se spune: era pierdut și a fost găsit.",
    verseRef: "Luca 15:24",
    verseText: "Căci acest fiu al meu era mort și a înviat; era pierdut și a fost găsit.",
    axis: "relationships",
    needs: ["copil_departat", "in_asteptare"],
    background: "pergament-cald",
  },
]

export const MESSAGE_CARDS_FAMILIE: MessageCard[] = [
  ...CARDS_NEIERTARE,
  ...CARDS_CASA_RUPTA,
  ...CARDS_COPIL_DEPARTAT,
]
