// Carduri pentru pierdere: doliu, boală, frica de moarte (docs/41 §3).
//
// Cele trei stări nu aveau NICIUN card scris anume pentru ele, deși sunt
// tocmai durerile care duc omul la telefon la două noaptea.
//
// REGULA (docs/00-DIRECTIE §7, D-005): fiecare `body` este parafraza unui
// verset REAL, iar `verseRef` apare pe card, la vedere.
//
// REGULA DE TON (docs/41 §6.4): la doliu nu se scrie numai din făgăduințe. Se
// scrie și din Psalmii de plângere. Omul zdrobit simte când e grăbit spre o
// încheiere fericită, și atunci închide aplicația și nu mai revine.
//
// `verseText` este fraza-cheie, nu versetul întreg: textul biblic complet vine
// din stratul RCCV (docs/39), ca să nu-l dublăm în datele cardurilor.
//
// DE COLAȚIONAT: versetele de aici nu au trecut încă prin citirea de om
// (docs/41 §6.6). Până atunci, cardurile stau scrise, dar nu se publică.
import type { MessageCard } from "./messageCards.js"

/** Mi-a murit cineva. */
export const CARDS_DOLIU: MessageCard[] = [
  {
    id: "msg_eu_sunt_invierea",
    title: "Dumnezeu ți-a spus deja:",
    body: "Eu sunt Învierea. Cine crede în Mine trăiește, chiar dacă a murit.",
    verseRef: "Ioan 11:25",
    verseText: "Eu sunt Învierea și Viața.",
    axis: "living_faith",
    needs: ["doliu", "frica_moarte"],
    background: "pergament-cald",
  },
  {
    id: "msg_am_plans_si_Eu",
    title: "Ce îți spune Dumnezeu astăzi, din Cuvântul Său:",
    body: "Am plâns și Eu la un mormânt. Nu-ți cer să nu plângi.",
    verseRef: "Ioan 11:35",
    verseText: "Isus plângea.",
    axis: "emotional_peace",
    needs: ["doliu"],
    background: "pergament-umbra",
  },
  {
    id: "msg_valea_umbrei",
    title: "Dumnezeu ți-a spus deja:",
    body: "Chiar prin valea umbrei morții de ai trece, Eu sunt cu tine.",
    verseRef: "Psalmul 23:4",
    verseText: "Nu mă tem de niciun rău, căci Tu ești cu mine.",
    axis: "emotional_peace",
    needs: ["doliu", "frica_moarte"],
    background: "pergament-umbra",
  },
  {
    id: "msg_leg_ranile",
    title: "Dumnezeu ți-a spus deja:",
    body: "Leg rănile inimii zdrobite. Nu trec pe lângă ele.",
    verseRef: "Psalmul 147:3",
    verseText: "El tămăduiește pe cei cu inima zdrobită și le leagă rănile.",
    axis: "emotional_peace",
    needs: ["doliu", "casa_rupta"],
    background: "pergament-umbra",
  },
  {
    id: "msg_pana_cand",
    title: "Ce îți spune Dumnezeu astăzi, din Cuvântul Său:",
    body: "Poți să Mă întrebi «până când?». Întrebarea asta e scrisă în Cartea Mea.",
    verseRef: "Psalmul 13:1",
    verseText: "Până când, Doamne, mă vei uita neîncetat?",
    axis: "emotional_peace",
    needs: ["doliu", "de_ce", "rugaciune_fara_raspuns"],
    background: "pergament-umbra",
  },
  {
    id: "msg_vreme_de_plans",
    title: "Ce îți spune Dumnezeu astăzi, din Cuvântul Său:",
    body: "Este o vreme de plâns. Nu te grăbi să treci peste ea.",
    verseRef: "Eclesiastul 3:4",
    verseText: "Plânsul își are vremea lui.",
    axis: "emotional_peace",
    needs: ["doliu"],
    background: "pergament-umbra",
  },
  {
    id: "msg_nu_ca_cei_fara_nadejde",
    title: "Ce îți spune Dumnezeu astăzi, din Cuvântul Său:",
    body: "Te întristezi, dar nu ca cei care n-au nădejde. Ai unde să-ți duci durerea.",
    verseRef: "1 Tesaloniceni 4:13",
    verseText: "Ca să nu vă întristați ca ceilalți, care n-au nădejde.",
    axis: "living_faith",
    needs: ["doliu"],
    background: "pergament",
  },
  {
    id: "msg_scump_inaintea_Mea",
    title: "Dumnezeu ți-a spus deja:",
    body: "Moartea celor iubiți de Mine nu trece neluată în seamă. E scumpă înaintea Mea.",
    verseRef: "Psalmul 116:15",
    verseText: "Scumpă este înaintea Domnului moartea celor iubiți de El.",
    axis: "identity",
    needs: ["doliu"],
    background: "pergament",
  },
  {
    id: "msg_stanca_la_care_nu_ajung",
    title: "Dumnezeu ți-a spus deja:",
    body: "Când ți se mâhnește inima, te duc la stânca la care nu ajungi singur.",
    verseRef: "Psalmul 61:2",
    verseText: "Du-mă pe stânca pe care n-o pot ajunge.",
    axis: "emotional_peace",
    needs: ["doliu", "obosit"],
    background: "pergament-umbra",
  },
  {
    id: "msg_mangaiere_care_trece_mai_departe",
    title: "Ce îți spune Dumnezeu astăzi, din Cuvântul Său:",
    body: "Te mângâi în necazul tău. Iar mângâierea primită nu rămâne numai la tine.",
    verseRef: "2 Corinteni 1:4",
    verseText: "El ne mângâie în toate necazurile noastre.",
    axis: "relationships",
    needs: ["doliu"],
    background: "pergament-cald",
  },
  {
    id: "msg_nimicesc_moartea",
    title: "Dumnezeu ți-a spus deja:",
    body: "Voi nimici moartea pe vecie și voi șterge lacrimile de pe toate fețele.",
    verseRef: "Isaia 25:8",
    verseText: "Domnul Dumnezeu șterge lacrimile de pe toate fețele.",
    axis: "living_faith",
    needs: ["doliu", "frica_moarte"],
    background: "pergament-cald",
  },
  {
    id: "msg_orice_lacrima",
    title: "Dumnezeu ți-a spus deja:",
    body: "Vine ziua în care îți șterg orice lacrimă. Moartea nu va mai fi.",
    verseRef: "Apocalipsa 21:4",
    verseText: "El va șterge orice lacrimă din ochii lor.",
    axis: "living_faith",
    needs: ["doliu", "frica_moarte"],
    background: "pergament-cald",
  },
]

/** Boală și spital. */
export const CARDS_BOALA: MessageCard[] = [
  {
    id: "msg_patul_de_suferinta",
    title: "Dumnezeu ți-a spus deja:",
    body: "Te sprijin când ești pe patul de suferință. Nu stau departe de el.",
    verseRef: "Psalmul 41:3",
    verseText: "Domnul îl sprijină când este pe patul de suferință.",
    axis: "emotional_peace",
    needs: ["boala"],
    background: "pergament-umbra",
  },
  {
    id: "msg_vindec_bolile",
    title: "Dumnezeu ți-a spus deja:",
    body: "Eu îți iert fărădelegile și Eu îți vindec bolile.",
    verseRef: "Psalmul 103:3",
    verseText: "El îți iartă toate fărădelegile tale, El îți vindecă toate bolile tale.",
    axis: "living_faith",
    needs: ["boala", "vinovat"],
    background: "pergament",
  },
  {
    id: "msg_stanca_inimii",
    title: "Dumnezeu ți-a spus deja:",
    body: "Trupul tău poate slăbi. Eu rămân tăria inimii tale.",
    verseRef: "Psalmul 73:26",
    verseText: "Dumnezeu va fi pururea Stânca inimii mele.",
    axis: "identity",
    needs: ["boala", "obosit"],
    background: "pergament-umbra",
  },
  {
    id: "msg_omul_dinauntru",
    title: "Ce îți spune Dumnezeu astăzi, din Cuvântul Său:",
    body: "Chiar dacă omul de afară se trece, cel dinăuntru se înnoiește din zi în zi.",
    verseRef: "2 Corinteni 4:16",
    verseText: "Omul nostru dinăuntru se înnoiește din zi în zi.",
    axis: "character",
    needs: ["boala", "obosit"],
    background: "pergament",
  },
  {
    id: "msg_pana_la_batranete",
    title: "Dumnezeu ți-a spus deja:",
    body: "Până la bătrânețea ta Eu sunt Același. Eu te-am făcut și Eu te port.",
    verseRef: "Isaia 46:4",
    verseText: "Eu v-am făcut și Eu vă voi purta.",
    axis: "identity",
    needs: ["boala", "speriat"],
    background: "pergament-cald",
  },
  {
    id: "msg_du_te_in_pace",
    title: "Ce îți spune Dumnezeu astăzi, din Cuvântul Său:",
    body: "Du-te în pace. Credința ta te-a făcut sănătos.",
    verseRef: "Marcu 5:34",
    verseText: "Fiică, credința ta te-a mântuit; du-te în pace.",
    axis: "living_faith",
    needs: ["boala"],
    background: "pergament-cald",
  },
  {
    id: "msg_cheama_pe_batrani",
    title: "Ce îți spune Dumnezeu astăzi, din Cuvântul Său:",
    body: "Cheamă pe bătrânii bisericii să se roage pentru tine. Nu duce boala singur.",
    verseRef: "Iacov 5:14",
    verseText: "Este vreunul printre voi bolnav? Să cheme pe prezbiterii bisericii.",
    axis: "relationships",
    needs: ["boala", "singur"],
    background: "pergament",
  },
  {
    id: "msg_taria_celui_obosit",
    title: "Dumnezeu ți-a spus deja:",
    body: "Dau tărie celui obosit și putere celui care cade.",
    verseRef: "Isaia 40:29",
    verseText: "El dă tărie celui obosit.",
    axis: "emotional_peace",
    needs: ["boala", "obosit"],
    background: "pergament",
  },
  {
    id: "msg_pentru_ce_te_mahnesti",
    title: "Ce îți spune Dumnezeu astăzi, din Cuvântul Său:",
    body: "Poți să-ți întrebi sufletul de ce geme. Și tot în Mine să nădăjduiești.",
    verseRef: "Psalmul 42:11",
    verseText: "Pentru ce te mâhnești, suflete, și gemi înăuntrul meu?",
    axis: "emotional_peace",
    needs: ["boala", "obosit", "de_ce"],
    background: "pergament-umbra",
  },
  {
    id: "msg_zilele_scrise",
    title: "Dumnezeu ți-a spus deja:",
    body: "Zilele tale erau scrise în cartea Mea înainte să fie vreuna din ele.",
    verseRef: "Psalmul 139:16",
    verseText: "Toate zilele erau scrise în cartea Ta.",
    axis: "identity",
    needs: ["boala", "frica_moarte"],
    background: "pergament",
  },
]

/** Mi-e frică de moarte. */
export const CARDS_FRICA_MOARTE: MessageCard[] = [
  {
    id: "msg_robia_fricii_de_moarte",
    title: "Dumnezeu ți-a spus deja:",
    body: "Am luat trup și sânge ca să scap pe cei ținuți toată viața în robia fricii de moarte.",
    verseRef: "Evrei 2:15",
    verseText: "Să izbăvească pe toți aceia care, prin frica morții, erau supuși robiei.",
    axis: "freedom",
    needs: ["frica_moarte"],
    background: "pergament",
  },
  {
    id: "msg_cheile_mortii",
    title: "Dumnezeu ți-a spus deja:",
    body: "Am fost mort și iată că sunt viu. Eu țin cheile morții.",
    verseRef: "Apocalipsa 1:18",
    verseText: "Am cheile morții și ale Locuinței morților.",
    axis: "living_faith",
    needs: ["frica_moarte"],
    background: "pergament",
  },
  {
    id: "msg_boldul_mortii",
    title: "Ce îți spune Dumnezeu astăzi, din Cuvântul Său:",
    body: "Moarte, unde îți este boldul? Biruința a fost dată.",
    verseRef: "1 Corinteni 15:55",
    verseText: "Unde îți este biruința, moarte? Unde îți este boldul, moarte?",
    axis: "freedom",
    needs: ["frica_moarte"],
    background: "pergament-cald",
  },
  {
    id: "msg_multe_locasuri",
    title: "Dumnezeu ți-a spus deja:",
    body: "În casa Tatălui Meu sunt multe locașuri. Mă duc să-ți pregătesc un loc.",
    verseRef: "Ioan 14:2",
    verseText: "În casa Tatălui Meu sunt multe locașuri.",
    axis: "living_faith",
    needs: ["frica_moarte", "singur"],
    background: "pergament-cald",
  },
  {
    id: "msg_astazi_in_rai",
    title: "Ce îți spune Dumnezeu astăzi, din Cuvântul Său:",
    body: "Astăzi vei fi cu Mine în rai. Nu ți-am cerut să fi fost bun mai întâi.",
    verseRef: "Luca 23:43",
    verseText: "Astăzi vei fi cu Mine în rai.",
    axis: "freedom",
    needs: ["frica_moarte", "vinovat"],
    background: "pergament-cald",
  },
  {
    id: "msg_a_nimicit_moartea",
    title: "Dumnezeu ți-a spus deja:",
    body: "Am nimicit moartea și am adus la lumină viața care nu se sfârșește.",
    verseRef: "2 Timotei 1:10",
    verseText: "A nimicit moartea și a adus la lumină viața și neputrezirea.",
    axis: "living_faith",
    needs: ["frica_moarte"],
    background: "pergament",
  },
  {
    id: "msg_cel_dintai_si_cel_de_pe_urma",
    title: "Dumnezeu ți-a spus deja:",
    body: "Nu te teme. Eu sunt Cel dintâi și Cel de pe urmă.",
    verseRef: "Apocalipsa 1:17",
    verseText: "Nu te teme! Eu sunt Cel dintâi și Cel de pe urmă.",
    axis: "identity",
    needs: ["frica_moarte", "speriat"],
    background: "pergament",
  },
  {
    id: "msg_a_trai_este_Hristos",
    title: "Ce îți spune Dumnezeu astăzi, din Cuvântul Său:",
    body: "Pentru tine, a trăi este Hristos și a muri este un câștig.",
    verseRef: "Filipeni 1:21",
    verseText: "Pentru mine a trăi este Hristos și a muri este un câștig.",
    axis: "living_faith",
    needs: ["frica_moarte"],
    background: "pergament",
  },
]

export const MESSAGE_CARDS_PIERDERE: MessageCard[] = [
  ...CARDS_DOLIU,
  ...CARDS_BOALA,
  ...CARDS_FRICA_MOARTE,
]
