import type { Course, Lesson, Module } from "./domain.js"

// Seed partajat (sursa unică de conținut pentru API in-memory și pentru popularea DB).
// Adolescenți → Modul 1 (identity) → Curs 1.1.
// L1–L6 COMPLET, importat din adolescenti/06-adolescenti-curs-1-1.md (12 beat-uri/lecție).
export interface SeedBundle {
  module: Module
  course: Course
  lessons: Lesson[]
}

export const teensM1C1: SeedBundle = {
  module: {
    id: "teens_m1_identity",
    categoryId: "teens12_18",
    order: 1,
    title: "Cine sunt eu?",
    axis: "identity",
    courseIds: ["teens_m1_c1"],
  },
  course: {
    id: "teens_m1_c1",
    moduleId: "teens_m1_identity",
    order: 1,
    title: "Cine sunt eu, de fapt?",
    struggle: "Mă definesc după like-uri, note, ce zic alții.",
    truth: "Identitatea și valoarea vin de la Creator, nu din performanță.",
    lessonIds: [
      "teens_m1_c1_l1",
      "teens_m1_c1_l2",
      "teens_m1_c1_l3",
      "teens_m1_c1_l4",
      "teens_m1_c1_l5",
      "teens_m1_c1_l6",
    ],
  },
  lessons: [
    // ── Lecția 1 — Nu ești ce zic like-urile ──
    {
      id: "teens_m1_c1_l1",
      courseId: "teens_m1_c1",
      order: 1,
      title: "Nu ești ce zic like-urile",
      estMinutes: 6,
      anchorRefs: ["Geneza 1:27"],
      memoryVerseRef: "Psalm 139:14",
      badgeId: "badge_beyond_likes",
      steps: [
        { id: "l1_s1", type: "check_in", order: 1, bubbles: [{ from: "guide", text: "Salut! Sunt Daniel. Înainte de orice — cum ești azi, sincer?" }] },
        { id: "l1_s2", type: "hook", order: 2, bubbles: [{ from: "guide", text: "Fii sincer o secundă: ai șters vreodată o postare fiindcă n-a luat destule aprecieri?" }, { from: "guide", text: "Eu, da. Și m-am simțit ciudat după. Ca și cum valoarea mea scădea cu fiecare like care nu venea." }] },
        { id: "l1_s3", type: "choice", order: 3, choice: { prompt: "Tu?", options: [{ id: "a", label: "Da, mi s-a întâmplat" }, { id: "b", label: "Nu, dar înțeleg senzația" }, { id: "c", label: "Mie nici nu-mi pasă de like-uri", branchStepId: "l1_branch_c" }] } },
        { id: "l1_branch_c", type: "name_struggle", order: 3, bubbles: [{ from: "guide", text: "Frumos, dacă-i adevărat. Dar întreabă-te: dacă mâine ai posta ceva și n-ar reacționa nimeni, chiar 0 — te-ai simți exact la fel? Uneori «nu-mi pasă» e o armă să nu ne doară." }] },
        { id: "l1_s4", type: "name_struggle", order: 4, bubbles: [{ from: "guide", text: "Există o minciună foarte tăcută, care sună așa: «Valorez cât de mult mă plac ceilalți.» O credem fără s-o spunem cu voce tare." }] },
        { id: "l1_s5", type: "world_vs_truth", order: 5, bubbles: [{ from: "guide", text: "Lumea zice: valoarea se câștigă — din aspect, aprecieri, performanță. Dar dacă valoarea se câștigă, înseamnă că se și poate pierde. Și atunci n-ai niciodată liniște." }] },
        { id: "l1_s6", type: "scripture", order: 6, scripture: { text: "Dumnezeu a făcut pe om după chipul Său.", ref: "Geneza 1:27" } },
        { id: "l1_s7", type: "truth_simple", order: 7, bubbles: [{ from: "guide", text: "Valoarea ta nu e un scor. E o amprentă. Ai fost făcut după chipul lui Dumnezeu — înainte să postezi ceva, înainte să iei vreo notă. Un tablou nu-și ia valoarea din câți îl văd, ci din cine l-a pictat." }] },
        { id: "l1_s8", type: "quiz", order: 8, quiz: { question: "Care afirmație e adevărată?", options: [{ text: "Valoarea mea crește cu fiecare like", correct: false }, { text: "Valoarea mea vine de la Cel care m-a făcut", correct: true }], explanation: "Valoarea nu e un scor, e o amprentă." } },
        { id: "l1_s9", type: "how_god_helps", order: 9, bubbles: [{ from: "guide", text: "Când începi să-ți iei valoarea de la El, telefonul nu mai e o instanță care te judecă. Poți posta din bucurie, nu din foame de aprobare. Se schimbă tot raportul cu ecranul." }] },
        { id: "l1_s10", type: "step", order: 10, bubbles: [{ from: "guide", text: "Azi: pune o postare (sau nu) și nu verifica aprecierile 24 de ore. Observă ce simți. Valoarea ta a rămas neschimbată tot timpul ăsta." }] },
        { id: "l1_s11", type: "memory_verse", order: 11, scripture: { text: "Te laud că sunt o făptură așa de minunată.", ref: "Psalm 139:14" } },
        { id: "l1_s12", type: "prayer", order: 12, bubbles: [{ from: "guide", text: "Doamne, învață-mă să-mi iau valoarea de la Tine, nu de la ecran. Mulțumesc că m-ai făcut cu intenție. Amin." }] },
        { id: "l1_s13", type: "journal", order: 13, journalPrompt: "Scrie: un lucru pentru care valorezi, care n-are legătură cu ce văd alții.", reward: { xp: 10, badgeId: "badge_beyond_likes", axisDeltas: { identity: 1 } } },
      ],
    },
    // ── Lecția 2 — Nu sunt de ajuns ──
    {
      id: "teens_m1_c1_l2",
      courseId: "teens_m1_c1",
      order: 2,
      title: "Nu sunt de ajuns",
      estMinutes: 6,
      anchorRefs: ["Ioan 1:12", "Romani 5:8"],
      memoryVerseRef: "Romani 5:8",
      badgeId: "badge_made_on_purpose",
      steps: [
        { id: "l2_s1", type: "check_in", order: 1, bubbles: [{ from: "guide", text: "Mă bucur că ai revenit. Cum ești azi? Și — s-a întâmplat ceva de la ultima dată?" }] },
        { id: "l2_s2", type: "hook", order: 2, bubbles: [{ from: "guide", text: "Ți s-a întâmplat să dai tot ce ai — și tot să simți că nu e de ajuns? La școală, acasă, în oglindă?" }] },
        { id: "l2_s3", type: "choice", order: 3, choice: { prompt: "Tu?", options: [{ id: "a", label: "Da, des" }, { id: "b", label: "Uneori" }, { id: "c", label: "Mai ales față de părinți" }] } },
        { id: "l2_s4", type: "name_struggle", order: 4, bubbles: [{ from: "guide", text: "Minciuna sună așa: «Valoarea se câștigă. Dacă nu sunt destul de bun, nu sunt destul de iubit.» E epuizant să trăiești așa." }] },
        { id: "l2_s5", type: "world_vs_truth", order: 5, bubbles: [{ from: "guide", text: "Lumea: «dovedește că meriți.» Evanghelia spune exact invers: ești iubit înainte să dovedești ceva." }] },
        { id: "l2_s6", type: "scripture", order: 6, scripture: { text: "Tuturor celor ce L-au primit… le-a dat dreptul să se facă copii ai lui Dumnezeu.", ref: "Ioan 1:12" } },
        { id: "l2_s7", type: "scripture", order: 7, scripture: { text: "Pe când eram noi încă păcătoși, Hristos a murit pentru noi.", ref: "Romani 5:8" } },
        { id: "l2_s8", type: "truth_simple", order: 8, bubbles: [{ from: "guide", text: "Dumnezeu nu te-a iubit după ce ai devenit bun. Te-a iubit când erai în cel mai rău punct. Deci valoarea ta nu stă pe performanță — stă pe El." }] },
        { id: "l2_s9", type: "quiz", order: 9, quiz: { question: "Adevărat sau fals: «Trebuie să fiu destul de bun ca Dumnezeu să mă iubească.»", options: [{ text: "Adevărat", correct: false }, { text: "Fals", correct: true }], explanation: "Fals — Romani 5:8: ești iubit înainte să dovedești ceva." } },
        { id: "l2_s10", type: "how_god_helps", order: 10, bubbles: [{ from: "guide", text: "Când știi că ești deja iubit, greșeala nu te mai distruge. Te ridici altfel. Nu mai cerșești valoare — trăiești din ea." }] },
        { id: "l2_s11", type: "step", order: 11, bubbles: [{ from: "guide", text: "Azi, când apare gândul «nu sunt de ajuns», răspunde-i cu voce joasă: «Sunt copil iubit al lui Dumnezeu — asta nu se câștigă și nu se pierde.»" }] },
        { id: "l2_s12", type: "memory_verse", order: 12, scripture: { text: "Pe când eram noi încă păcătoși, Hristos a murit pentru noi.", ref: "Romani 5:8" } },
        { id: "l2_s13", type: "prayer", order: 13, bubbles: [{ from: "guide", text: "Doamne, învață-mă să trăiesc ca un copil iubit, nu ca un candidat care tot dă probe. Mulțumesc că m-ai iubit primul. Amin." }] },
        { id: "l2_s14", type: "journal", order: 14, journalPrompt: "Scrie: unde anume încerci cel mai tare să «dovedești că meriți»? Ce s-ar schimba dacă ai ști că deja meriți?", reward: { xp: 10, badgeId: "badge_made_on_purpose", axisDeltas: { identity: 1 } } },
      ],
    },
    // ── Lecția 3 — Capcana comparației ──
    {
      id: "teens_m1_c1_l3",
      courseId: "teens_m1_c1",
      order: 3,
      title: "Capcana comparației",
      estMinutes: 6,
      anchorRefs: ["2 Corinteni 10:12"],
      memoryVerseRef: "Galateni 6:4",
      badgeId: "badge_free_from_feed",
      steps: [
        { id: "l3_s1", type: "check_in", order: 1, bubbles: [{ from: "guide", text: "Hei. Cât timp ai stat azi pe telefon? Fără vinovăție — doar sincer." }] },
        { id: "l3_s2", type: "hook", order: 2, bubbles: [{ from: "guide", text: "Ți s-a întâmplat să intri pe Instagram/TikTok bine-dispus — și să ieși simțindu-te mai puțin? Mai urât, mai sărac, mai «pe dinafară»?" }] },
        { id: "l3_s3", type: "choice", order: 3, choice: { prompt: "Tu?", options: [{ id: "a", label: "Zilnic" }, { id: "b", label: "Des" }, { id: "c", label: "Nu prea observ" }] } },
        { id: "l3_s4", type: "name_struggle", order: 4, bubbles: [{ from: "guide", text: "Comparația e un joc pe care îl pierzi mereu: îți compari culisele tale cu momentele de glorie montate ale altora. Nu e o luptă dreaptă." }] },
        { id: "l3_s5", type: "world_vs_truth", order: 5, bubbles: [{ from: "guide", text: "Feed-ul spune: «uite cât de împliniți sunt toți, numai tu nu.» Adevărul: vezi un trailer editat, nu filmul întreg al nimănui." }] },
        { id: "l3_s6", type: "scripture", order: 6, scripture: { text: "Când se măsoară pe ei înșiși cu ei înșiși… nu sunt înțelepți.", ref: "2 Corinteni 10:12" } },
        { id: "l3_s7", type: "truth_simple", order: 7, bubbles: [{ from: "guide", text: "Dumnezeu nu te-a chemat să fii o copie mai bună a altcuiva. Te-a chemat să fii tu, viu. Comparația îți fură exact darul care e doar al tău." }] },
        { id: "l3_s8", type: "quiz", order: 8, quiz: { question: "Ce vezi, de fapt, în feed-ul cuiva?", options: [{ text: "Viața lui reală", correct: false }, { text: "Partea aleasă și editată", correct: true }], explanation: "Vezi un trailer editat, nu filmul întreg." } },
        { id: "l3_s9", type: "how_god_helps", order: 9, bubbles: [{ from: "guide", text: "Recunoștința e antidotul. Când Îi mulțumești lui Dumnezeu pentru ce ai, creierul nu mai poate, în același timp, să invidieze. Încearcă — chiar funcționează." }] },
        { id: "l3_s10", type: "step", order: 10, bubbles: [{ from: "guide", text: "Azi: când te prinzi că te compari, oprește-te și spune 3 lucruri pentru care ești recunoscător. Și dă unfollow la 1 cont care te trage în jos." }] },
        { id: "l3_s11", type: "memory_verse", order: 11, scripture: { text: "Fiecare să-și cerceteze fapta lui… și nu se va lăuda față de altul.", ref: "Galateni 6:4" } },
        { id: "l3_s12", type: "prayer", order: 12, bubbles: [{ from: "guide", text: "Doamne, iartă-mă că m-am măsurat cu alții. Învață-mă să văd ce mi-ai dat și să-Ți mulțumesc. Amin." }] },
        { id: "l3_s13", type: "journal", order: 13, journalPrompt: "Scrie: cu cine te compari cel mai des? Ce anume crezi că-ți lipsește — și chiar îți lipsește?", reward: { xp: 10, badgeId: "badge_free_from_feed", axisDeltas: { identity: 1, emotional_peace: 1 } } },
      ],
    },
    // ── Lecția 4 — Oglinda: cum mă văd ──
    {
      id: "teens_m1_c1_l4",
      courseId: "teens_m1_c1",
      order: 4,
      title: "Oglinda: cum mă văd",
      estMinutes: 6,
      anchorRefs: ["1 Corinteni 6:19-20"],
      memoryVerseRef: "Psalm 139:14",
      badgeId: "badge_temple_not_problem",
      steps: [
        { id: "l4_s1", type: "check_in", order: 1, bubbles: [{ from: "guide", text: "O întrebare delicată: când te uiți în oglindă, ce voce auzi — blândă sau critică?" }] },
        { id: "l4_s2", type: "hook", order: 2, bubbles: [{ from: "guide", text: "Mulți tineri se urăsc în fotografii, își schimbă corpul în cap de 100 de ori pe zi. Poate și tu ai un «dacă aș arăta altfel…»." }] },
        { id: "l4_s3", type: "choice", order: 3, choice: { prompt: "Tu?", options: [{ id: "a", label: "Da, mă critic mult" }, { id: "b", label: "Depinde de zi" }, { id: "c", label: "Mă împac cu mine" }] } },
        { id: "l4_s4", type: "name_struggle", order: 4, bubbles: [{ from: "guide", text: "Minciuna: «Valorez cât de bine arăt.» Filtrele și reclamele ne-au vândut un corp care nici nu există cu adevărat." }] },
        { id: "l4_s5", type: "world_vs_truth", order: 5, bubbles: [{ from: "guide", text: "Lumea: «repară-te ca să fii acceptat.» Cuvântul: ești deja lucrare a lui Dumnezeu — trupul tău nu e o problemă de rezolvat, ci un dar de îngrijit." }] },
        { id: "l4_s6", type: "scripture", order: 6, scripture: { text: "Nu știți că trupul vostru este Templul Duhului Sfânt…? Proslăviți dar pe Dumnezeu în trupul vostru.", ref: "1 Corinteni 6:19-20" } },
        { id: "l4_s7", type: "truth_simple", order: 7, bubbles: [{ from: "guide", text: "Demnitatea ta nu depinde de kilograme sau de piele. Ești locuit de Dumnezeu. Asta schimbă cum îți vorbești și cum ai grijă de tine — din respect, nu din ură." }] },
        { id: "l4_s8", type: "quiz", order: 8, quiz: { question: "Corpul meu este…", options: [{ text: "o problemă de reparat pentru alții", correct: false }, { text: "un dar de îngrijit, locuit de Dumnezeu", correct: true }], explanation: "Ești templu al Duhului Sfânt — un dar de îngrijit." } },
        { id: "l4_s9", type: "how_god_helps", order: 9, bubbles: [{ from: "guide", text: "Când încetezi să-ți mai fii dușman, poți începe să-ți porți de grijă: somn, mișcare, ce consumi cu ochii. Nu ca să fii acceptat — ci fiindcă deja ești." }] },
        { id: "l4_s10", type: "step", order: 10, bubbles: [{ from: "guide", text: "Azi: când treci pe lângă o oglindă, în loc de o critică, spune un lucru de mulțumire despre corpul tău («picioarele astea m-au dus azi peste tot»)." }] },
        { id: "l4_s11", type: "memory_verse", order: 11, scripture: { text: "Te laud că sunt o făptură așa de minunată.", ref: "Psalm 139:14" } },
        { id: "l4_s12", type: "prayer", order: 12, bubbles: [{ from: "guide", text: "Doamne, iartă-mă că mi-am vorbit urât. Învață-mă să mă văd cum mă vezi Tu. Amin." }] },
        { id: "l4_s13", type: "journal", order: 13, journalPrompt: "Scrie: o propoziție critică pe care ți-o spui des — și rescrie-o cum ți-ar spune-o Dumnezeu.", reward: { xp: 10, badgeId: "badge_temple_not_problem", axisDeltas: { identity: 1 } } },
      ],
    },
    // ── Lecția 5 — Pentru ce exist? ──
    {
      id: "teens_m1_c1_l5",
      courseId: "teens_m1_c1",
      order: 5,
      title: "Pentru ce exist?",
      estMinutes: 6,
      anchorRefs: ["Efeseni 2:10"],
      memoryVerseRef: "Ieremia 1:5",
      badgeId: "badge_made_with_purpose",
      steps: [
        { id: "l5_s1", type: "check_in", order: 1, bubbles: [{ from: "guide", text: "Ai avut vreodată seara aia în care te întrebi: «care-i rostul, de fapt?» E o întrebare bună, nu una periculoasă." }] },
        { id: "l5_s2", type: "hook", order: 2, bubbles: [{ from: "guide", text: "Mulți tineri simt un gol: fac lucruri, dar nu știu pentru ce. Școală, scroll, repet. Sună cunoscut?" }] },
        { id: "l5_s3", type: "choice", order: 3, choice: { prompt: "Tu?", options: [{ id: "a", label: "Da, des" }, { id: "b", label: "Câteodată" }, { id: "c", label: "Știu ce vreau" }] } },
        { id: "l5_s4", type: "name_struggle", order: 4, bubbles: [{ from: "guide", text: "Minciuna: «Sunt o întâmplare. Nu contez cu adevărat.» Din golul ăsta vin multe nopți grele." }] },
        { id: "l5_s5", type: "world_vs_truth", order: 5, bubbles: [{ from: "guide", text: "Lumea: «ești aici din întâmplare, inventează-ți singur un sens.» Cuvântul: ai fost gândit și chemat, cu un rost pus în tine dinainte." }] },
        { id: "l5_s6", type: "scripture", order: 6, scripture: { text: "Noi suntem lucrarea Lui și am fost zidiți… pentru faptele bune pe care le-a pregătit Dumnezeu mai dinainte.", ref: "Efeseni 2:10" } },
        { id: "l5_s7", type: "truth_simple", order: 7, bubbles: [{ from: "guide", text: "Nu tu îți inventezi valoarea din nimic — o descoperi. Ești o «lucrare» cu semnătură. Rostul tău nu e o carieră, ci o viață trăită cu și pentru El, în felul tău unic." }] },
        { id: "l5_s8", type: "quiz", order: 8, quiz: { question: "Rostul meu…", options: [{ text: "trebuie inventat din nimic", correct: false }, { text: "e descoperit — am fost făcut cu intenție", correct: true }], explanation: "Ești lucrarea Lui, zidit cu un rost pregătit dinainte." } },
        { id: "l5_s9", type: "how_god_helps", order: 9, bubbles: [{ from: "guide", text: "Când știi că ai un rost, ziua de azi are greutate. Nu mai aștepți «să înceapă viața» — poți să faci binele care-ți stă azi în față." }] },
        { id: "l5_s10", type: "step", order: 10, bubbles: [{ from: "guide", text: "Azi: fă un lucru bun pe care doar tu îl poți face acum (un mesaj cald, un ajutor, o vorbă bună). Simte cum e să trăiești «pentru» ceva." }] },
        { id: "l5_s11", type: "memory_verse", order: 11, scripture: { text: "Înainte ca să te fi născut… te cunoșteam.", ref: "Ieremia 1:5" } },
        { id: "l5_s12", type: "prayer", order: 12, bubbles: [{ from: "guide", text: "Doamne, arată-mi pentru ce m-ai făcut. Vreau să trăiesc cu rost, nu doar să exist. Amin." }] },
        { id: "l5_s13", type: "journal", order: 13, journalPrompt: "Scrie: când te-ai simțit ultima dată «pe locul tău», făcând ceva cu sens? Ce spune asta despre tine?", reward: { xp: 10, badgeId: "badge_made_with_purpose", axisDeltas: { character: 1 } } },
      ],
    },
    // ── Lecția 6 — Al cui sunt (recapitulare + certificat modul) ──
    {
      id: "teens_m1_c1_l6",
      courseId: "teens_m1_c1",
      order: 6,
      title: "Al cui sunt",
      estMinutes: 7,
      anchorRefs: ["Isaia 43:1"],
      memoryVerseRef: "Isaia 43:1",
      badgeId: "badge_whose_i_am",
      steps: [
        { id: "l6_s1", type: "check_in", order: 1, bubbles: [{ from: "guide", text: "Am ajuns la ultima lecție din curs. Mândru de tine că ai rămas. Cum ești azi?" }] },
        { id: "l6_s2", type: "hook", order: 2, bubbles: [{ from: "guide", text: "Gândește-te: majoritatea întrebărilor grele («sunt de ajuns?», «contez?») au aceeași rădăcină — al cui sunt eu?" }] },
        { id: "l6_s3", type: "choice", order: 3, choice: { prompt: "Tu?", options: [{ id: "a", label: "Al nimănui, sincer" }, { id: "b", label: "Al familiei" }, { id: "c", label: "Nu m-am gândit" }] } },
        { id: "l6_s4", type: "name_struggle", order: 4, bubbles: [{ from: "guide", text: "Când nu știm al cui suntem, ne lipim de orice ne primește: un grup, o relație, aprecieri. Și ne dărâmăm când acelea pleacă." }] },
        { id: "l6_s5", type: "world_vs_truth", order: 5, bubbles: [{ from: "guide", text: "Lumea: «ești al tău, singur pe lume.» Cuvântul: ești chemat pe nume și ești al Lui — asta e o temelie care nu se clatină." }] },
        { id: "l6_s6", type: "scripture", order: 6, scripture: { text: "Nu te teme… te-am chemat pe nume: ești al Meu.", ref: "Isaia 43:1" } },
        { id: "l6_s7", type: "truth_simple", order: 7, bubbles: [{ from: "guide", text: "Dacă ești al lui Dumnezeu, atunci: valoarea ta e sigură, rostul tău e real, și nu ești niciodată singur. Toate lecțiile de până acum stau pe piatra asta." }] },
        { id: "l6_s8", type: "quiz", order: 8, quiz: { question: "Recapitulare: care e temelia tuturor celor 6 lecții?", options: [{ text: "Ce zic alții despre mine", correct: false }, { text: "Sunt al lui Dumnezeu, chemat pe nume", correct: true }], explanation: "Valoarea (L1), iubit înainte să dovedesc (L2), fără comparație (L3), templu (L4), cu rost (L5) — toate stau pe: sunt al Lui (L6)." } },
        { id: "l6_s9", type: "how_god_helps", order: 9, bubbles: [{ from: "guide", text: "Data viitoare când te lovește «nu sunt de ajuns», ai acum un răspuns care nu vine din tine, ci de la Cel care te-a chemat pe nume." }] },
        { id: "l6_s10", type: "step", order: 10, bubbles: [{ from: "guide", text: "Azi: scrie-ți undeva la vedere (fundal de telefon, bilet) — «Sunt al Lui. Isaia 43:1.» Să-l vezi când te clatini." }] },
        { id: "l6_s11", type: "memory_verse", order: 11, scripture: { text: "Te-am chemat pe nume: ești al Meu.", ref: "Isaia 43:1" } },
        { id: "l6_s12", type: "prayer", order: 12, bubbles: [{ from: "guide", text: "Doamne, mulțumesc că sunt al Tău. Când uit cine sunt, adu-mi aminte că m-ai chemat pe nume. Amin." }] },
        { id: "l6_s13", type: "journal", order: 13, journalPrompt: "Scrie: după cele 6 lecții — cine ești tu, de fapt? Răspunde în 2 rânduri, cu cuvintele tale.", reward: { xp: 10, badgeId: "badge_whose_i_am", axisDeltas: { identity: 1 }, certificateId: "cert_teens_m1", unlocksModuleId: "teens_m2_emotional_peace" } },
      ],
    },
  ],
}
