#!/usr/bin/env python3
import hashlib,json,re,runpy,unicodedata,zipfile
from pathlib import Path
CH=Path('docs/data/biblia-emanus/JAS.2.json'); JR=Path('docs/biblia-emanus/NT-AI-REVIEW-BATCH-2026-08-08-JAS.2.md'); ZIP=Path('docs/data/biblia-emanus/sources/nt-sblgnt-1.2.zip')
SNAP='29b8762199eb87757ec36961097b817cb2b569557d95348a70fac66c0262f424'; RUN='emanus-nt-editorial-2026-08-08-jas-2'
T={1:'Frații mei, să nu țineți credința în Domnul nostru Isus Hristos, Domnul slavei, cu părtinire.',2:'Căci, dacă intră în adunarea voastră un om cu inel de aur, îmbrăcat strălucitor, și intră și un sărac în haine murdare,',3:'iar voi vă uitați cu atenție la cel care poartă hainele strălucitoare și îi spuneți: „Tu așază-te aici, la loc bun”, iar săracului îi spuneți: „Tu stai acolo” sau „Așază-te jos, lângă scăunelul meu”,',4:'oare nu faceți deosebiri între voi și nu deveniți judecători cu gânduri rele?',5:'Ascultați, frații mei iubiți! Nu i-a ales Dumnezeu pe cei săraci în ochii lumii ca să fie bogați în credință și moștenitori ai Împărăției pe care a promis-o celor ce-L iubesc?',6:'Dar voi l-ați dezonorat pe cel sărac. Nu cei bogați vă asupresc și nu ei vă târăsc înaintea tribunalelor?',7:'Nu ei blasfemiază numele cel bun care a fost chemat peste voi?',8:'Dacă împliniți cu adevărat legea împărătească, potrivit Scripturii: „Să-l iubești pe aproapele tău ca pe tine însuți”, bine faceți.',9:'Dar, dacă arătați părtinire, săvârșiți păcat și sunteți dovediți de lege ca niște călcători ai ei.',10:'Căci cine păzește toată legea, dar se poticnește într-o singură poruncă, se face vinovat de toate.',11:'Fiindcă Cel care a spus: „Să nu comiți adulter” a spus și: „Să nu ucizi”. Dacă nu comiți adulter, dar ucizi, ai devenit călcător al legii.',12:'Așa să vorbiți și așa să faceți, ca unii care urmează să fie judecați prin legea libertății.',13:'Căci judecata este fără milă pentru cel care n-a arătat milă; mila triumfă asupra judecății.',14:'Ce folos este, frații mei, dacă cineva spune că are credință, dar nu are fapte? Poate oare credința aceea să-l mântuiască?',15:'Dacă un frate sau o soră nu au haine și duc lipsă de hrana de fiecare zi,',16:'iar unul dintre voi le spune: „Mergeți în pace, încălziți-vă și săturați-vă!”, dar nu le dați cele necesare trupului, ce folos este?',17:'Tot așa și credința, dacă nu are fapte, este moartă în ea însăși.',18:'Dar va spune cineva: „Tu ai credință, iar eu am fapte.” Arată-mi credința ta fără fapte, iar eu îți voi arăta credința mea prin faptele mele.',19:'Tu crezi că Dumnezeu este unul; bine faci. Și demonii cred și se cutremură.',20:'Vrei să înțelegi, om fără minte, că credința fără fapte este neroditoare?',21:'Avraam, tatăl nostru, nu a fost oare socotit drept prin fapte, când l-a adus pe altar pe Isaac, fiul său?',22:'Vezi că credința lucra împreună cu faptele lui și că, prin fapte, credința a ajuns la maturitate.',23:'Și s-a împlinit Scriptura care spune: „Avraam L-a crezut pe Dumnezeu și aceasta i-a fost socotită ca dreptate”, iar el a fost numit prieten al lui Dumnezeu.',24:'Vedeți că omul este socotit drept prin fapte, și nu numai prin credință.',25:'Tot așa, Rahav, prostituata, nu a fost oare socotită dreaptă prin fapte, când i-a primit pe mesageri și i-a trimis pe alt drum?',26:'Căci, după cum trupul fără duh este mort, tot așa și credința fără fapte este moartă.'}
assert hashlib.sha256(ZIP.read_bytes()).hexdigest()==SNAP
with zipfile.ZipFile(ZIP) as z:
 greek=z.read('sblgnt/text/JAS.txt').decode(); app=z.read('sblgnt/apparatus/text/JAS.txt').decode(); aux={k:z.read(f'{k}/JAS.usfm').decode() for k in ['tr','webp','btf','cornilescu1924','biblia-libera']}
for v in range(1,27): assert re.search(rf'Jas 2:{v}\t',greek)
for x in aux.values(): assert x.strip()
def gv(v): return re.search(rf'^Jas 2:{v}\t(.+)$',greek,re.M).group(1).strip()
def anchor(v): return ' '.join(re.sub(r'[⸀⸂⸃\[\]]','',gv(v)).split()[:8])
d=json.loads(CH.read_text()); assert d['status']=='in_review' and d['public'] is False; assert [x['number'] for x in d['verses']]==list(range(1,27))
for x in d['verses']: x['text']=T[x['number']]
for x in d['benchmark']['translationsConsulted']: x['consultedInBatch']=x['id'] in {'CORNILESCU-1924','BTF'}
d['benchmark']['observations']=['Revizie semantică verset-cu-verset din snapshotul fixat SBLGNT 1.2 și aparat; TR a fost numai martor textual.','WEBP, BTF, Cornilescu 1924 și Biblia Liberă au fost auxiliare. NTR nu a fost consultată.']
a=d['audit']; a.update({'completedOn':'2026-08-08','engineVersion':'3.0.0','reviewLevel':'ai-complete','reviewAgent':{'type':'ai','engine':'Codex / GPT-5','runId':RUN,'method':'verse-by-verse-source-and-benchmark'},'sourceSnapshotSha256':SNAP,'verseCoverage':{'expected':26,'reviewed':26,'continuous':True},'sourceLanguage':{'language':'greacă koine','text':'SBLGNT 1.2 + aparat; Textus Receptus ca martor suplimentar','result':'approved','scope':'Toate cele 26 de versete au fost confruntate direct cu snapshotul SBLGNT și aparatul; TR a fost doar martor.'},'romanianLanguage':{'result':'approved','changesApplied':['Au fost reparate calcurile, acordurile și propozițiile corupte din textul anterior.','Distincțiile de număr, persoană și raport sintactic au fost refăcute după greacă.']},'theologicalContext':{'result':'approved','principles':['δικαιόω din 2:21,24,25 este redat consecvent prin „a socoti drept”, fără extinderea sensului prin glosă doctrinară.','În 2:14 articolul din ἡ πίστις este reflectat prin „credința aceea”, pentru a păstra referirea la credința declarată fără fapte.']},'omissionAddition':{'result':'approved','omissions':0,'additions':0},'copyrightDistance':{'result':'approved','method':'redactare proprie din SBLGNT; sursele românești doar pentru verificare'},'criticalIssues':{'result':'approved','open':0}}); a.pop('benchmarkEvidence',None); a.pop('modelEvidence',None)
def note(v,term,decision,alts,reason): return {'verse':v,'term':term,'decision':decision,'alternatives':alts,'reason':reason,'reviewRequired':True,'resolutionStatus':'resolved','resolutionReason':'Verificat direct în SBLGNT 1.2 și aparatul fixat.'}
d['editorialNotes']=[note(1,'τῆς δόξης','„Domnul slavei”',['„al slavei”'],'Genitivul este legat de titulatura lui Isus Hristos; formularea românească evită un genitiv suspendat.'),note(14,'μὴ δύναται ἡ πίστις σῶσαι αὐτόν;','„Poate oare credința aceea să-l mântuiască?”',['„Poate credința să-l mântuiască?”'],'Articolul anaforic indică tipul de credință tocmai descris, fără fapte.'),note(20,'ἡ πίστις χωρὶς τῶν ἔργων ἀργή ἐστιν','„credința fără fapte este neroditoare”',['TR/RP: „moartă”'],'Textul principal SBLGNT are ἀργή; lectura „moartă” nu este importată aici din tradiția alternativă.'),note(21,'ἐξ ἔργων ἐδικαιώθη','„a fost socotit drept prin fapte”',['„a fost justificat prin fapte”'],'Redarea lexicală păstrează termenul fără a introduce explicație confesională.'),note(22,'ἡ πίστις συνήργει τοῖς ἔργοις','„credința lucra împreună cu faptele”',['„credința producea faptele”'],'συνεργέω exprimă cooperarea, nu o relație unilaterală adăugată textului.')]
val=runpy.run_path('scripts/check-biblia-emanus.py'); a['textDigest']=val['chapter_text_digest'](d); a['contentDigest']=val['chapter_content_digest'](d); CH.write_text(unicodedata.normalize('NFC',json.dumps(d,ensure_ascii=False,indent=2)+'\n'))
d2=json.loads(CH.read_text()); assert val['chapter_text_digest'](d2)==d2['audit']['textDigest']; assert val['chapter_content_digest'](d2)==d2['audit']['contentDigest']
lines=['# Revizie AI, lot Iacov 2','','Statut: `in_review` — **nu este aprobare de publicare**.','','Data: `2026-08-08`','','Reviewer: `Codex / GPT-5` (`ai`; rulare: `'+RUN+'`)','','## Surse consultate','','Snapshot local fixat `nt-sblgnt-1.2.zip` SHA-256 `'+SNAP+'`: SBLGNT-JAS și aparatul ca text principal; TR-JAS numai martor; WEBP/BTF/Cornilescu 1924/Biblia Liberă auxiliare. **NTR nu a fost consultată**.','','„0 probleme” automat nu este verdict semantic; fiecare verset a primit decizie editorială.','','## Decizii pe verset','','| Referință BE | Ancoră SBLGNT | Decizie românească |','| --- | --- | --- |']
for v in range(1,27): lines.append(f'| JAS.2.{v} | `{anchor(v)}` | {T[v]} |')
lines += ['','## Variante și termeni materiali','','2:20 păstrează lectura SBLGNT `ἀργή`, redată „neroditoare”, fără importarea automată a lecturii TR/RP „moartă”. 2:14 și 2:21-25 au fost tratate lexical și contextual, cu deciziile documentate în `editorialNotes`.','','## Concluzie','','Toate cele 26 de versete au fost revizuite semantic. Capitolul rămâne `in_review` și `public: false`.','']; JR.write_text(unicodedata.normalize('NFC','\n'.join(lines)))
