#!/usr/bin/env python3
import hashlib,json,re,runpy,unicodedata,zipfile
from pathlib import Path
CH=Path('docs/data/biblia-emanus/JAS.3.json'); JR=Path('docs/biblia-emanus/NT-AI-REVIEW-BATCH-2026-08-08-JAS.3.md'); ZIP=Path('docs/data/biblia-emanus/sources/nt-sblgnt-1.2.zip')
SNAP='29b8762199eb87757ec36961097b817cb2b569557d95348a70fac66c0262f424'; RUN='emanus-nt-editorial-2026-08-08-jas-3'
T={1:'Frații mei, să nu deveniți mulți învățători, știind că noi vom primi o judecată mai aspră.',2:'Căci toți ne poticnim în multe feluri. Dacă cineva nu se poticnește în vorbire, acesta este un om matur, în stare să-și țină în frâu și întregul trup.',3:'Dacă punem frâiele în gura cailor ca să ne asculte, le cârmuim și tot trupul.',4:'Iată și corăbiile: deși sunt atât de mari și sunt împinse de vânturi puternice, sunt cârmuite de o cârmă foarte mică oriunde voiește cel care le conduce.',5:'Tot așa și limba este un mădular mic, dar se laudă cu lucruri mari. Iată cât de mic este focul care aprinde o pădure atât de mare!',6:'Și limba este un foc, o lume a nedreptății. Limba este așezată între mădularele noastre ca aceea care întinează întregul trup, aprinde cursul vieții și este ea însăși aprinsă de Gheena.',7:'Căci orice fel de fiare, de păsări, de târâtoare și de viețuitoare marine este îmblânzit și a fost îmblânzit de om,',8:'dar limba niciun om nu o poate îmblânzi; este un rău nestatornic, plin de otravă aducătoare de moarte.',9:'Cu ea Îl binecuvântăm pe Domnul și Tatăl, iar cu ea îi blestemăm pe oamenii făcuți după asemănarea lui Dumnezeu.',10:'Din aceeași gură ies binecuvântarea și blestemul. Frații mei, nu trebuie să fie așa.',11:'Oare izvorul face să țâșnească din aceeași deschizătură și apă dulce, și apă amară?',12:'Poate oare, frații mei, un smochin să facă măsline sau o viță-de-vie smochine? Nici un izvor sărat nu poate da apă dulce.',13:'Cine este înțelept și priceput între voi? Să-și arate, prin purtarea bună, faptele făcute în blândețea înțelepciunii.',14:'Dar, dacă aveți gelozie amară și ambiție egoistă în inimile voastre, nu vă lăudați și nu mințiți împotriva adevărului.',15:'Aceasta nu este înțelepciunea care coboară de sus, ci una pământească, firească, demonică.',16:'Căci unde sunt gelozie și ambiție egoistă, acolo sunt dezordine și orice faptă rea.',17:'Dar înțelepciunea de sus este mai întâi curată, apoi pașnică, blândă, ușor de înduplecat, plină de milă și de roade bune, nepărtinitoare și sinceră.',18:'Iar rodul dreptății este semănat în pace de cei care fac pace.'}
assert hashlib.sha256(ZIP.read_bytes()).hexdigest()==SNAP
with zipfile.ZipFile(ZIP) as z:
 greek=z.read('sblgnt/text/JAS.txt').decode(); app=z.read('sblgnt/apparatus/text/JAS.txt').decode(); aux={k:z.read(f'{k}/JAS.usfm').decode() for k in ['tr','webp','btf','cornilescu1924','biblia-libera']}
for v in range(1,19): assert re.search(rf'Jas 3:{v}\t',greek)
for x in aux.values(): assert x.strip()
def gv(v): return re.search(rf'^Jas 3:{v}\t(.+)$',greek,re.M).group(1).strip()
def anchor(v): return ' '.join(re.sub(r'[⸀⸂⸃\[\]]','',gv(v)).split()[:8])
d=json.loads(CH.read_text()); assert d['status']=='in_review' and d['public'] is False
for x in d['verses']: x['text']=T[x['number']]
for x in d['benchmark']['translationsConsulted']: x['consultedInBatch']=x['id'] in {'CORNILESCU-1924','BTF'}
d['benchmark']['observations']=['Revizie semantică verset-cu-verset direct din snapshotul fixat SBLGNT 1.2 și aparat; TR a fost numai martor textual.','WEBP, BTF, Cornilescu 1924 și Biblia Liberă au fost auxiliare. NTR nu a fost consultată.']
a=d['audit']; a.update({'completedOn':'2026-08-08','engineVersion':'3.0.0','reviewLevel':'ai-complete','reviewAgent':{'type':'ai','engine':'Codex / GPT-5','runId':RUN,'method':'verse-by-verse-source-and-benchmark'},'sourceSnapshotSha256':SNAP,'verseCoverage':{'expected':18,'reviewed':18,'continuous':True},'sourceLanguage':{'language':'greacă koine','text':'SBLGNT 1.2 + aparat; Textus Receptus ca martor suplimentar','result':'approved','scope':'Toate cele 18 versete au fost confruntate direct cu SBLGNT/aparat; TR a fost doar martor.'},'romanianLanguage':{'result':'approved','changesApplied':['Au fost înlocuite calcurile și propozițiile corupte cu română proprie verificată după greacă.','Metaforele despre frâu, cârmă, foc, izvor și înțelepciune au fost păstrate fără adaos explicativ în corpul versetului.']},'theologicalContext':{'result':'approved','principles':['κύριον καὶ πατέρα din 3:9 este redat „Domnul și Tatăl”, fără substituirea lui κύριος cu „Dumnezeu”.','ψυχική din 3:15 este redat „firească”, păstrând contrastul cu înțelepciunea de sus fără glosă confesională.']},'omissionAddition':{'result':'approved','omissions':0,'additions':0},'copyrightDistance':{'result':'approved','method':'redactare proprie din SBLGNT; etaloanele doar pentru verificare'},'criticalIssues':{'result':'approved','open':0}}); a.pop('benchmarkEvidence',None); a.pop('modelEvidence',None)
def note(v,term,decision,alts,reason): return {'verse':v,'term':term,'decision':decision,'alternatives':alts,'reason':reason,'reviewRequired':True,'resolutionStatus':'resolved','resolutionReason':'Verificat direct în SBLGNT 1.2 și aparatul fixat.'}
d['editorialNotes']=[note(1,'μεῖζον κρίμα','„o judecată mai aspră”',['„o condamnare mai mare”'],'κρίμα desemnează judecata/verdictul; formularea nu presupune automat condamnarea finală.'),note(6,'τὸν τροχὸν τῆς γενέσεως','„cursul vieții”',['„roata existenței”'],'Metafora greacă este redată idiomatic fără a introduce o concepție religioasă străină contextului.'),note(8,'ἀκατάστατον κακόν','„un rău nestatornic”',['„un rău de nestăpânit”'],'Textul principal este urmat lexical; nu se armonizează automat cu o lectură alternativă apropiată semantic.'),note(9,'τὸν κύριον καὶ πατέρα','„Domnul și Tatăl”',['„Dumnezeul și Tatăl”'],'κύριος este păstrat explicit; textul existent substituia nejustificat termenul.'),note(15,'ψυχική','„firească”',['„sufletească”','„senzuală”'],'În triada pământească-firească-demonică, termenul descrie ceea ce aparține vieții naturale, nu senzualitatea în sens modern.'),note(17,'ἀδιάκριτος','„nepărtinitoare”',['„fără îndoială”','„neșovăielnică”'],'Contextul etic al listei susține redarea prin lipsa favoritismului, fără a transforma opțiunea într-o variantă textuală.')]
val=runpy.run_path('scripts/check-biblia-emanus.py'); a['textDigest']=val['chapter_text_digest'](d); a['contentDigest']=val['chapter_content_digest'](d); CH.write_text(unicodedata.normalize('NFC',json.dumps(d,ensure_ascii=False,indent=2)+'\n'))
d2=json.loads(CH.read_text()); assert val['chapter_text_digest'](d2)==d2['audit']['textDigest']; assert val['chapter_content_digest'](d2)==d2['audit']['contentDigest']
lines=['# Revizie AI, lot Iacov 3','','Statut: `in_review` — **nu este aprobare de publicare**.','','Data: `2026-08-08`','','Reviewer: `Codex / GPT-5` (`ai`; rulare: `'+RUN+'`)','','## Surse consultate','','Snapshotul local fixat SBLGNT 1.2 și aparatul au fost textul principal; TR a fost numai martor; WEBP/BTF/Cornilescu 1924/Biblia Liberă auxiliare. **NTR nu a fost consultată**.','','Validatoarele sunt porți de consistență, nu verdict semantic.','','## Decizii pe verset','','| Referință BE | Ancoră SBLGNT | Decizie românească |','| --- | --- | --- |']
for v in range(1,19): lines.append(f'| JAS.3.{v} | `{anchor(v)}` | {T[v]} |')
lines += ['','## Concluzie','','Toate cele 18 versete au fost revizuite semantic direct față de snapshot. Capitolul rămâne `in_review` și `public: false`.','']; JR.write_text(unicodedata.normalize('NFC','\n'.join(lines)))
