#!/usr/bin/env python3
import hashlib,json,re,runpy,unicodedata,zipfile,sys
from pathlib import Path
SNAP='29b8762199eb87757ec36961097b817cb2b569557d95348a70fac66c0262f424'; ZIP=Path('docs/data/biblia-emanus/sources/nt-sblgnt-1.2.zip'); ch=int(sys.argv[1]); assert ch in (4,5)
T4={1:'De unde vin luptele și certurile dintre voi? Nu de aici, din plăcerile voastre care se războiesc în mădularele voastre?',2:'Poftiți și nu aveți; ucideți și invidiați și nu puteți dobândi; vă certați și vă luptați. Nu aveți pentru că nu cereți.',3:'Cereți și nu primiți, pentru că cereți rău, ca să risipiți în plăcerile voastre.',4:'Adulterelor, nu știți că prietenia cu lumea este vrăjmășie față de Dumnezeu? Așadar, cine vrea să fie prieten cu lumea se face vrăjmaș al lui Dumnezeu.',5:'Sau credeți că Scriptura vorbește în zadar? Duhul pe care L-a făcut să locuiască în noi tânjește cu gelozie.',6:'Dar El dă un har și mai mare. De aceea spune: „Dumnezeu Se împotrivește celor mândri, dar celor smeriți le dă har.”',7:'Supuneți-vă deci lui Dumnezeu; împotriviți-vă diavolului, iar el va fugi de la voi.',8:'Apropiați-vă de Dumnezeu și El Se va apropia de voi. Curățați-vă mâinile, păcătoșilor, și curățiți-vă inimile, voi cei cu inima împărțită!',9:'Întristați-vă, jeliți și plângeți! Râsul vostru să se prefacă în jale și bucuria voastră în mâhnire.',10:'Smeriți-vă înaintea Domnului și El vă va înălța.',11:'Nu vă vorbiți de rău unii pe alții, fraților. Cine îl vorbește de rău pe fratele său sau îl judecă pe fratele său vorbește de rău legea și judecă legea. Iar dacă judeci legea, nu ești împlinitor al legii, ci judecător.',12:'Unul singur este Dătătorul Legii și Judecătorul, Cel care poate să mântuiască și să nimicească. Dar cine ești tu, care îl judeci pe aproapele tău?',13:'Veniți acum, voi care spuneți: „Astăzi sau mâine vom merge în cutare cetate, vom petrece acolo un an, vom face negoț și vom câștiga”,',14:'voi, care nu știți ce va fi mâine! Ce este viața voastră? Sunteți un abur care se arată pentru puțin timp și apoi dispare.',15:'În loc să spuneți: „Dacă Domnul va voi, vom trăi și vom face aceasta sau aceea.”',16:'Dar acum vă lăudați în aroganțele voastre. Orice laudă de felul acesta este rea.',17:'Așadar, cine știe să facă binele și nu-l face săvârșește păcat.'}
T5={1:'Veniți acum, bogaților! Plângeți și tânguiți-vă din pricina nenorocirilor care vin peste voi.',2:'Bogățiile voastre au putrezit, iar hainele voastre au fost mâncate de molii.',3:'Aurul și argintul vostru au ruginit; rugina lor va fi mărturie împotriva voastră și vă va mânca trupurile ca focul. Ați strâns comori în zilele din urmă.',4:'Iată, plata lucrătorilor care v-au secerat ogoarele, reținută de voi, strigă, iar strigătele secerătorilor au ajuns la urechile Domnului Oștirilor.',5:'Ați trăit pe pământ în lux și desfătare; v-ați îngrășat inimile într-o zi de măcel.',6:'L-ați condamnat și l-ați ucis pe cel drept; el nu vi se împotrivește.',7:'Fiți deci răbdători, fraților, până la venirea Domnului. Iată, agricultorul așteaptă rodul prețios al pământului și are răbdare pentru el până primește ploaia timpurie și târzie.',8:'Fiți și voi răbdători; întăriți-vă inimile, pentru că venirea Domnului s-a apropiat.',9:'Nu vă plângeți unii împotriva altora, fraților, ca să nu fiți judecați. Iată, Judecătorul stă la uși.',10:'Fraților, luați-i ca exemplu de suferință și răbdare pe profeții care au vorbit în Numele Domnului.',11:'Iată, îi numim fericiți pe cei care au răbdat. Ați auzit de răbdarea lui Iov și ați văzut deznodământul dat de Domnul, pentru că Domnul este plin de compasiune și milostiv.',12:'Mai presus de toate, frații mei, să nu jurați nici pe cer, nici pe pământ, nici cu vreun alt jurământ. Ci „da”-ul vostru să fie „da”, iar „nu”-ul vostru „nu”, ca să nu cădeți sub judecată.',13:'Suferă cineva dintre voi? Să se roage. Este cineva cu inimă bună? Să cânte laude.',14:'Este cineva bolnav între voi? Să-i cheme pe prezbiterii bisericii, iar ei să se roage pentru el, ungându-l cu untdelemn în Numele Domnului.',15:'Rugăciunea credinței îl va izbăvi pe cel bolnav, iar Domnul îl va ridica; și, dacă a săvârșit păcate, îi vor fi iertate.',16:'Mărturisiți-vă deci păcatele unii altora și rugați-vă unii pentru alții, ca să fiți vindecați. Rugăciunea unui om drept are mare putere în lucrarea ei.',17:'Ilie era un om supus acelorași slăbiciuni ca noi și s-a rugat stăruitor să nu plouă; și n-a plouat pe pământ trei ani și șase luni.',18:'Apoi s-a rugat din nou, iar cerul a dat ploaie și pământul și-a produs rodul.',19:'Frații mei, dacă vreunul dintre voi rătăcește de la adevăr și cineva îl întoarce,',20:'să știe că acela care întoarce un păcătos de la rătăcirea căii lui îi va salva sufletul de la moarte și va acoperi o mulțime de păcate.'}
T=T4 if ch==4 else T5; n=len(T); CH=Path(f'docs/data/biblia-emanus/JAS.{ch}.json'); JR=Path(f'docs/biblia-emanus/NT-AI-REVIEW-BATCH-2026-08-08-JAS.{ch}.md'); RUN=f'emanus-nt-editorial-2026-08-08-jas-{ch}'
assert hashlib.sha256(ZIP.read_bytes()).hexdigest()==SNAP
with zipfile.ZipFile(ZIP) as z:
 greek=z.read('sblgnt/text/JAS.txt').decode(); app=z.read('sblgnt/apparatus/text/JAS.txt').decode(); aux={k:z.read(f'{k}/JAS.usfm').decode() for k in ['tr','webp','btf','cornilescu1924','biblia-libera']}
for v in range(1,n+1): assert re.search(rf'Jas {ch}:{v}\t',greek)
def gv(v): return re.search(rf'^Jas {ch}:{v}\t(.+)$',greek,re.M).group(1).strip()
def anc(v): return ' '.join(re.sub(r'[⸀⸂⸃\[\]]','',gv(v)).split()[:8])
d=json.loads(CH.read_text()); assert d['status']=='in_review' and d['public'] is False
for x in d['verses']: x['text']=T[x['number']]
for x in d['benchmark']['translationsConsulted']: x['consultedInBatch']=x['id'] in {'CORNILESCU-1924','BTF'}
d['benchmark']['observations']=['Revizie semantică direct din snapshotul fixat SBLGNT 1.2 și aparat; TR numai martor textual.','WEBP, BTF, Cornilescu 1924 și Biblia Liberă auxiliare. NTR nu a fost consultată.']
a=d['audit']; a.update({'completedOn':'2026-08-08','engineVersion':'3.0.0','reviewLevel':'ai-complete','reviewAgent':{'type':'ai','engine':'Codex / GPT-5','runId':RUN,'method':'verse-by-verse-source-and-benchmark'},'sourceSnapshotSha256':SNAP,'verseCoverage':{'expected':n,'reviewed':n,'continuous':True},'sourceLanguage':{'language':'greacă koine','text':'SBLGNT 1.2 + aparat; Textus Receptus ca martor suplimentar','result':'approved','scope':f'Toate cele {n} versete au fost confruntate direct cu SBLGNT/aparat; TR a fost doar martor.'},'romanianLanguage':{'result':'approved','changesApplied':['Textul a fost refăcut în română firească după greacă, eliminând calcurile și coruperile.']},'theologicalContext':{'result':'approved','principles':['Termenii teologici și metaforele au fost redați lexical și contextual, fără glosare confesională.']},'omissionAddition':{'result':'approved','omissions':0,'additions':0},'copyrightDistance':{'result':'approved','method':'redactare proprie din SBLGNT; etaloanele numai pentru verificare'},'criticalIssues':{'result':'approved','open':0}}); a.pop('benchmarkEvidence',None); a.pop('modelEvidence',None)
def note(v,term,decision,alts,reason): return {'verse':v,'term':term,'decision':decision,'alternatives':alts,'reason':reason,'reviewRequired':True,'resolutionStatus':'resolved','resolutionReason':'Verificat direct în SBLGNT 1.2 și aparatul fixat.'}
if ch==4:
 d['editorialNotes']=[note(4,'μοιχαλίδες','„Adulterelor”',['„oameni necredincioși”'],'Metafora conjugală a textului grec este păstrată, fără neutralizare interpretativă.'),note(5,'πρὸς φθόνον ἐπιποθεῖ τὸ πνεῦμα','„Duhul ... tânjește cu gelozie”',['„duhul ... poftește spre invidie”'],'Sintaxa este dificilă și disputată; formularea păstrează deliberat tensiunea lexicală fără a o transforma într-o afirmație dogmatică suplimentară.'),note(8,'δίψυχοι','„voi cei cu inima împărțită”',['„cei cu suflet dublu”'],'Aceeași decizie lexicală ca în 1:8.'),note(12,'νομοθέτης καὶ κριτής','„Dătătorul Legii și Judecătorul”',['„Dătătorul Legii”'],'Ambele substantive ale textului principal sunt păstrate.')]
else:
 d['editorialNotes']=[note(4,'κύριος σαβαώθ','„Domnul Oștirilor”',['„Domnul Sabaot”'],'Titlul semitic este redat semantic în română, fără pierderea referentului.'),note(11,'τὸ τέλος κυρίου','„deznodământul dat de Domnul”',['„sfârșitul Domnului”'],'Genitivul este redat contextual ca rezultatul/deznodământul lucrării Domnului în istoria lui Iov.'),note(12,'ἵνα μὴ ὑπὸ κρίσιν πέσητε','„ca să nu cădeți sub judecată”',['„sub condamnare”'],'κρίσις este păstrat ca judecată, fără substituirea cu „ipocrizie”.'),note(15,'σώσει τὸν κάμνοντα','„îl va izbăvi pe cel bolnav”',['„îl va mântui pe cel bolnav”'],'σῴζω este redat contextual în cadrul bolii și al ridicării de către Domnul.'),note(20,'σώσει ψυχὴν αὐτοῦ ἐκ θανάτου','„îi va salva sufletul de la moarte”',['„va salva un suflet”'],'Pronumele textului principal este păstrat în relație cu păcătosul întors din rătăcire.')]
val=runpy.run_path('scripts/check-biblia-emanus.py'); a['textDigest']=val['chapter_text_digest'](d); a['contentDigest']=val['chapter_content_digest'](d); CH.write_text(unicodedata.normalize('NFC',json.dumps(d,ensure_ascii=False,indent=2)+'\n'))
d2=json.loads(CH.read_text()); assert val['chapter_text_digest'](d2)==d2['audit']['textDigest']; assert val['chapter_content_digest'](d2)==d2['audit']['contentDigest']
lines=[f'# Revizie AI, lot Iacov {ch}','','Statut: `in_review` — **nu este aprobare de publicare**.','','Data: `2026-08-08`','',f'Reviewer: `Codex / GPT-5` (`ai`; rulare: `{RUN}`)','','## Surse consultate','','Snapshot local fixat SBLGNT 1.2 + aparat; TR numai martor; WEBP/BTF/Cornilescu 1924/Biblia Liberă auxiliare. **NTR nu a fost consultată**.','','Validatoarele sunt porți, nu verdict semantic.','','## Decizii pe verset','','| Referință BE | Ancoră SBLGNT | Decizie românească |','| --- | --- | --- |']
for v in range(1,n+1): lines.append(f'| JAS.{ch}.{v} | `{anc(v)}` | {T[v]} |')
lines += ['','## Concluzie','',f'Toate cele {n} versete au fost revizuite semantic direct față de snapshot. Capitolul rămâne `in_review` și `public: false`.','']; JR.write_text(unicodedata.normalize('NFC','\n'.join(lines)))
