// Generated by scripts/materialize-biblia-emanus-nt-runtime-catalog.py. Do not edit.
// The raw corpus is imported only when the digest-bound editorial gate is approved.
import type { BibliaEmanusNtRuntimeGate, BibleBook } from "./types.js"

export const BIBLIA_EMANUS_NT_RUNTIME_GATE: BibliaEmanusNtRuntimeGate = {"status":"withheld","reason":"Noul Testament este blocat editorial: auditul actual nu oferă dovezi semantice verset-cu-verset şi conţine erori confirmate de limbă şi sens.","approval":null}
export const BIBLIA_EMANUS_NT_BOOKS: BibleBook[] = []
