// Generated by scripts/generate-bible-catalog.mjs. Do not edit manually.
import type { BibleBookSummary } from "./types.js"

export const BIBLE_CATALOG = [
  {
    "id": "geneza",
    "name": "Geneza",
    "testament": "vt",
    "order": 1,
    "blurb": "Cartea inceputurilor. Aici afli de unde vine lumea, de unde vii tu, cum s-a rupt totul si cine a fagaduit cel dintai ca va drege ruptura. Sta in doua parti: capitolele de la unu la unsprezece spun inceputul lumii intregi, iar de la doisprezece pana la cincizeci se spune inceputul unui singur neam, prin care Dumnezeu a hotarat sa binecuvinteze toate neamurile. Cine nu cunoaste cartea aceasta citeste tot restul Scripturii fara temelie sub picioare.",
    "chapters": [
      {
        "id": "geneza-1",
        "bookId": "geneza",
        "number": 1,
        "title": "Geneza 1 — Dumnezeu vorbeste si lumea se face",
        "summary": "Sase zile in care Dumnezeu ia ceea ce este pustiu si gol, ii da hotare, il umple si il numeste bun. La urma il aseaza pe om acolo, purtand chipul Sau.",
        "status": "in_review"
      },
      {
        "id": "geneza-2",
        "bookId": "geneza",
        "number": 2,
        "title": "Geneza 2 — Odihna, tarana si cel dintai „nu este bine\"",
        "summary": "Dupa ce am privit lumea de departe, ne apropiem. Dumnezeu Se odihneste si sfinteste o zi, Se apleaca peste tarana si sufla in ea, sadeste o gradina, da o singura oprire si spune pentru intaia oara ca ceva nu este bine: omul singur.",
        "status": "in_review"
      },
      {
        "id": "geneza-3",
        "bookId": "geneza",
        "number": 3,
        "title": "Geneza 3 — Ruptura, si cea dintai fagaduinta",
        "summary": "Capitolul in care se strica totul. Un glas strain intreaba, femeia se uita, barbatul tace, amandoi mananca. Si tocmai acolo, in mijlocul blestemului, Dumnezeu rosteste cea dintai fagaduinta a mantuirii si Isi imbraca El Insusi copiii.",
        "status": "in_review"
      },
      {
        "id": "geneza-4",
        "bookId": "geneza",
        "number": 4,
        "title": "Geneza 4 — Cel dintai sange varsat",
        "summary": "Doi frati aduc daruri Domnului si numai unul este primit. Din pizma se naste cea dintai ucidere, iar din ucidere se naste un neam care isi zideste cetati si isi canta razbunarea. La capatul capitolului, cateva cuvinte care schimba tot: oamenii au inceput sa cheme Numele Domnului.",
        "status": "in_review"
      },
      {
        "id": "geneza-5",
        "bookId": "geneza",
        "number": 5,
        "title": "Geneza 5 — Cartea neamurilor, si un om care nu a murit",
        "summary": "Un sir de nume si de ani, cu acelasi cuvant la capatul fiecarei vieti: apoi a murit. Se aude de opt ori, ca un clopot. Si o singura data sirul se rupe, la un om despre care nu se spune ca a murit, ci ca a umblat cu Dumnezeu si nu s-a mai vazut.",
        "status": "in_review"
      },
      {
        "id": "geneza-6",
        "bookId": "geneza",
        "number": 6,
        "title": "Geneza 6 — Mahnirea lui Dumnezeu si lemnul corabiei",
        "summary": "Rautatea omului se intinsese peste tot, si Sfanta Scriptura spune un lucru cutremurator: lui Dumnezeu I-a parut rau si S-a mahnit in inima Lui. In mijlocul hotararii de a sterge totul sta un singur cuvant care schimba istoria lumii: dar Noe. Iar dupa el urmeaza masurile unei corabii.",
        "status": "in_review"
      },
      {
        "id": "geneza-7",
        "bookId": "geneza",
        "number": 7,
        "title": "Geneza 7 — Apele, si usa inchisa de Domnul",
        "summary": "Noe intra in corabie, si Domnul Insusi inchide usa dupa el. Se rup izvoarele adancului si se deschid stavilarele cerurilor, iar lumea se intoarce in apa din care fusese scoasa la inceput. La capatul capitolului a ramas un singur rand de nume si o lada purtata pe intinderea apelor.",
        "status": "in_review"
      },
      {
        "id": "geneza-8",
        "bookId": "geneza",
        "number": 8,
        "title": "Geneza 8 — Dumnezeu Si-a adus aminte",
        "summary": "Apele scad incet, si tot capitolul atarna de patru cuvinte asezate la inceputul lui: Dumnezeu Si-a adus aminte de Noe. Un corb, un porumbel, o frunza de maslin, si un om care asteapta porunca chiar dupa ce vede uscatul. La capat, cel dintai altar din Sfanta Scriptura si o fagaduinta pentru toate vremurile.",
        "status": "in_review"
      },
      {
        "id": "geneza-9",
        "bookId": "geneza",
        "number": 9,
        "title": "Geneza 9 — Curcubeul, si rusinea din cort",
        "summary": "Dumnezeu binecuvinteaza lumea cea noua, pune pret pe viata omului si asaza in nori un arc intors spre cer, ca semn al unui legamant fara conditii. Iar la cateva randuri dupa aceea, omul prin care a fost scapata lumea se imbata si zace gol in cortul lui. Capitolul acesta ne invata deodata cat de mare este mila lui Dumnezeu si cat de putin s-a schimbat inima omului.",
        "status": "in_review"
      },
      {
        "id": "geneza-10",
        "bookId": "geneza",
        "number": 10,
        "title": "Geneza 10 — Harta neamurilor",
        "summary": "Un capitol pe care cei mai multi il sar: nume dupa nume, saptezeci de neamuri iesite din trei frati. Si totusi aici sta una din invataturile cele mai mari ale Sfintei Scripturi — ca toate popoarele pamantului sunt o singura familie, si ca Dumnezeu le stie pe toate pe nume. In mijlocul listei se ridica un om, Nimrod, si o cetate care se va numi Babel.",
        "status": "in_review"
      },
      {
        "id": "geneza-11",
        "bookId": "geneza",
        "number": 11,
        "title": "Geneza 11 — Turnul, si drumul care se opreste la jumatate",
        "summary": "Oamenii se aduna intr-o campie si zic sa ne facem un nume. Dumnezeu Se pogoara sa vada turnul care trebuia sa atinga cerul, si incurca limbile. Iar dupa imprastiere, cartea se ingusteaza deodata la o singura familie: un batran care porneste spre Canaan si se opreste la jumatatea drumului, cu o nora stearpa in casa.",
        "status": "in_review"
      },
      {
        "id": "geneza-12",
        "bookId": "geneza",
        "number": 12,
        "title": "Geneza 12 — Iesi din tara ta",
        "summary": "Dumnezeu vorbeste unui om de saptezeci si cinci de ani, dintr-o casa de inchinatori la idoli, si ii cere sa lase tot fara sa i se spuna unde merge. Iar la capatul poruncii sta o fagaduinta care cuprinde toate neamurile pamantului. Avram pleaca, zideste altare — si, la cea dintai foamete, coboara in Egipt si minte.",
        "status": "in_review"
      },
      {
        "id": "geneza-13",
        "bookId": "geneza",
        "number": 13,
        "title": "Geneza 13 — Doi oameni si o alegere",
        "summary": "Avram se intoarce din Egipt si se duce inapoi la altarul cel dintai. Apoi, cand averile ii despart pe el si pe Lot, cel mai mare ii da celui mai mic dreptul de a alege. Lot alege cu ochii si isi intinde corturile pana la Sodoma. Iar Dumnezeu ii spune lui Avram, dupa ce ramane singur: ridica-ti ochii si priveste.",
        "status": "in_review"
      },
      {
        "id": "geneza-14",
        "bookId": "geneza",
        "number": 14,
        "title": "Geneza 14 — Razboiul, painea si vinul",
        "summary": "Patru imparati din rasarit calca cetatile campiei si il duc pe Lot rob. Avram, care nu ceruse nimic si nu se bagase in nimic, isi ia oamenii din casa si il scoate. La intoarcere il intampina doi imparati: unul ii aduce paine si vin si il binecuvinteaza, celalalt ii ofera prada. De la cel dintai primeste; de la cel de al doilea nu ia nici macar un fir de ata.",
        "status": "in_review"
      },
      {
        "id": "geneza-15",
        "bookId": "geneza",
        "number": 15,
        "title": "Geneza 15 — Legamantul prin care trece numai Dumnezeu",
        "summary": "Avram Ii spune lui Dumnezeu, pentru intaia data, ce il doare: mor fara copii. Dumnezeu il scoate afara, ii arata stelele, si omul crede — iar credinta lui i se socoteste ca neprihanire. Apoi, intr-o noapte de groaza si de intuneric adanc, un cuptor de fum si o flacara trec singure printre dobitoacele despicate: legamantul se face fara ca omul sa treaca prin el.",
        "status": "in_review"
      },
      {
        "id": "geneza-16",
        "bookId": "geneza",
        "number": 16,
        "title": "Geneza 16 — Dumnezeul care ma vede",
        "summary": "Dupa zece ani de asteptare, Sarai isi face un plan si i-l da lui Avram, iar el asculta fara sa intrebe pe Dumnezeu. Din planul acela ies dispret, invinuire, asprime si o roaba insarcinata care fuge in pustie. Iar acolo, langa un izvor, Dumnezeu o cauta pe cea de care nu-i pasase nimanui — si ea Ii da un Nume pe care nu-l mai daduse nimeni.",
        "status": "in_review"
      },
      {
        "id": "geneza-17",
        "bookId": "geneza",
        "number": 17,
        "title": "Geneza 17 — Numele schimbate, si semnul pus in carne",
        "summary": "Dupa treisprezece ani de tacere, Dumnezeu i Se arata lui Avram si Se numeste, pentru intaia data, Cel Atotputernic. Ii schimba numele, ii schimba numele nevestei, ii da un semn pe trup si ii spune raspicat prin cine va veni fagaduinta: nu prin Ismael, ci printr-un copil care nu s-a nascut inca. Iar batranul cade cu fata la pamant si rade.",
        "status": "in_review"
      },
      {
        "id": "geneza-18",
        "bookId": "geneza",
        "number": 18,
        "title": "Geneza 18 — Este oare ceva prea greu pentru Domnul?",
        "summary": "Trei calatori se opresc la cortul unui batran in zaduful zilei, si el alearga sa-i primeasca. La masa aceea se rosteste un soroc: la anul, Sara va avea un fiu. Femeia rade pe ascuns, si este auzita. Iar dupa masa, Dumnezeu nu pleaca fara sa-i spuna prietenului Sau ce are de gand sa faca — si Avraam ramane in picioare inaintea Lui, si se roaga, coborand de la cincizeci pana la zece.",
        "status": "in_review"
      },
      {
        "id": "geneza-19",
        "bookId": "geneza",
        "number": 19,
        "title": "Geneza 19 — Focul, si un om scos de mana",
        "summary": "Doi ingeri ajung seara la Sodoma, si il gasesc pe Lot in poarta cetatii. Noaptea aceea da pe fata ce ajunsese locul acela, si ce ajunsese omul care se mutase in el. Cetatea arde, nevasta lui se uita inapoi, iar el iese cu mainile goale — scos afara nu fiindca s-a grabit, ci fiindca Dumnezeu Si-a adus aminte de Avraam.",
        "status": "in_review"
      },
      {
        "id": "geneza-20",
        "bookId": "geneza",
        "number": 20,
        "title": "Geneza 20 — Aceeasi frica, dupa douazeci si cinci de ani",
        "summary": "Avraam se muta in Gherar si spune iarasi ce spusese in Egipt: este sora mea. Imparatul o ia pe Sara, si numai Dumnezeu, venind noaptea in vis la un pagan, opreste lucrul inainte sa fie prea tarziu. Batranul este mustrat pe drept de un imparat, se dezvinovateste stangaci — si totusi este numit prooroc, si se roaga pentru cel care il mustrase.",
        "status": "in_review"
      },
      {
        "id": "geneza-21",
        "bookId": "geneza",
        "number": 21,
        "title": "Geneza 21 — La vremea hotarata",
        "summary": "Dupa douazeci si cinci de ani, fagaduinta se implineste: se naste Isaac, si rasul de neputinta al Sarei se preface in ras de bucurie. Dar bucuria aduce cu ea si o despartire grea: Agar si copilul ei sunt trimisi in pustie, unde apa se ispraveste, si unde Dumnezeu aude glasul unui copil si deschide ochii unei mame. La sfarsit, batranul sadeste un copac si cheama Numele Domnului, Dumnezeul cel vesnic.",
        "status": "in_review"
      },
      {
        "id": "geneza-22",
        "bookId": "geneza",
        "number": 22,
        "title": "Geneza 22 — Domnul va purta de grija",
        "summary": "Dumnezeu ii cere lui Avraam tocmai fiul pe care i-l daduse. Batranul se scoala dis-de-dimineata, merge trei zile, pune lemnele pe umarul copilului si urca muntele. In clipa cutitului ridicat, Cerul striga numele lui de doua ori, si in tufis se gaseste un berbec. Locul acela isi ia numele de la ce a invatat un om acolo: Domnul va purta de grija.",
        "status": "in_review"
      },
      {
        "id": "geneza-23",
        "bookId": "geneza",
        "number": 23,
        "title": "Geneza 23 — Un mormant cumparat cu bani grei",
        "summary": "Sara moare la o suta douazeci si sapte de ani, si Avraam sade langa ea si o plange. Apoi se scoala si face un lucru care pare marunt si este urias: cumpara, platind pretul intreg, o pestera si un ogor. Este cea dintai bucata de pamant pe care o are cu adevarat in tara fagaduita — si o cumpara ca sa aiba unde sa-si ingroape moarta.",
        "status": "in_review"
      },
      {
        "id": "geneza-24",
        "bookId": "geneza",
        "number": 24,
        "title": "Geneza 24 — Domnul m-a calauzit pe drum",
        "summary": "Un batran isi trimite sluga cea mai de incredere sa aduca o nevasta pentru fiul fagaduintei. Sluga pleaca la drum lung, se roaga la o fantana in amurg, si primeste raspunsul inainte de a ispravi de vorbit. Este cel mai lung capitol din Geneza, si cel mai linistit: nu se intampla nici o minune vazuta, ci numai o purtare de grija tacuta, pas cu pas.",
        "status": "in_review"
      },
      {
        "id": "geneza-25",
        "bookId": "geneza",
        "number": 25,
        "title": "Geneza 25 — Un batran satul de zile, si o ciorba de linte",
        "summary": "Avraam moare dupa o batranete fericita, si cei doi fii ai lui, despartiti de ani de zile, stau umar la umar la mormantul lui. Apoi incepe povestea lui Isaac: douazeci de ani de rugaciune pentru o nevasta stearpa, doi copii care se lupta inca din pantece, o casa in care fiecare parinte isi are favoritul, si un tanar care isi vinde dreptul de intai nascut pentru o strachina de linte.",
        "status": "in_review"
      },
      {
        "id": "geneza-26",
        "bookId": "geneza",
        "number": 26,
        "title": "Geneza 26 — Fantanile sapate din nou",
        "summary": "Singurul capitol din toata cartea in care Isaac sta el insusi in mijloc. Vine o foamete, si Dumnezeu ii spune sa nu se pogoare in Egipt. El ramane, si se imbogateste, si tocmai de aceea este alungat. Sapa fantana dupa fantana, si i le iau pe rand, si el se muta mai departe fara sa se certe — pana cand primeste loc larg si o aratare a Domnului la Beer-Seba.",
        "status": "in_review"
      },
      {
        "id": "geneza-27",
        "bookId": "geneza",
        "number": 27,
        "title": "Geneza 27 — Binecuvantarea furata",
        "summary": "Un tata batran si aproape orb vrea sa dea binecuvantarea fiului pe care il iubeste pentru vanatul lui. O mama asculta pe la usa si isi face planul. Un fiu se imbraca in hainele fratelui sau si minte de patru ori in fata tatalui sau. Iar la sfarsit, in casa aceea nu ramane nimeni castigat: unul striga cu strigate mari, altul fuge de acasa, iar mama nu-si va mai vedea niciodata baiatul.",
        "status": "in_review"
      },
      {
        "id": "geneza-28",
        "bookId": "geneza",
        "number": 28,
        "title": "Geneza 28 — O piatra sub cap, si o scara pana la cer",
        "summary": "Un tanar pleaca de acasa fugind, cu un toiag in mana si cu o minciuna in urma. Se culca in camp deschis, cu o piatra sub cap. Si tocmai acolo, in cea mai proasta noapte a vietii lui, Dumnezeu Se pogoara la el, ii deschide cerul si ii fagaduieste ca nu-l va parasi. Iar el se trezeste si zice: Domnul este in locul acesta, si eu n-am stiut.",
        "status": "in_review"
      },
      {
        "id": "geneza-29",
        "bookId": "geneza",
        "number": 29,
        "title": "Geneza 29 — Inselatorul, inselat",
        "summary": "Iacov ajunge la o fantana in Haran si o vede pe Rahela. Slujeste sapte ani pentru ea, si i se par cateva zile. Dar in noaptea nuntii i se pune in brate cealalta sora, si dimineata intelege ca a fost inselat exact asa cum inselase el. Iar la sfarsitul capitolului, Dumnezeu Se apleaca tocmai spre femeia pe care nimeni nu o voia.",
        "status": "in_review"
      },
      {
        "id": "geneza-30",
        "bookId": "geneza",
        "number": 30,
        "title": "Geneza 30 — Casa in care se lupta pentru dragoste",
        "summary": "Doua surori se intrec prin copii, isi trimit roabele in patul aceluiasi barbat si se targuiesc intre ele pentru o noapte. Din vraja aceasta se nasc unsprezece dintre cei doisprezece parinti ai lui Israel. Iar la sfarsit, Dumnezeu Isi aduce aminte de Rahela, si Iacov — care nu mai are ce sa astepte de la socrul lui — se apuca iarasi de siretlicuri, desi binecuvantarea nu vine din ele.",
        "status": "in_review"
      },
      {
        "id": "geneza-31",
        "bookId": "geneza",
        "number": 31,
        "title": "Geneza 31 — Intoarce-te in tara parintilor tai",
        "summary": "Dupa douazeci de ani, Dumnezeu ii spune lui Iacov sa se intoarca acasa. El pleaca pe furis, cu turmele si cu femeile, iar Rahela fura idolii tatalui ei. Laban il ajunge din urma cu gand rau, dar Dumnezeu il opreste printr-un vis. Se cearta, isi spun in fata tot ce au strans in douazeci de ani, si la sfarsit ridica o movila de pietre — nu ca semn de dragoste, ci ca hotar intre doi oameni care nu se mai pot increde unul in altul.",
        "status": "in_review"
      },
      {
        "id": "geneza-32",
        "bookId": "geneza",
        "number": 32,
        "title": "Geneza 32 — Noaptea de la Iaboc",
        "summary": "Iacov se intoarce acasa si afla ca fratele pe care il inselase vine spre el cu patru sute de oameni. Se teme, isi imparte tabara, se roaga cea mai frumoasa rugaciune a vietii lui, trimite daruri inainte — si apoi ramane singur. In noaptea aceea Se lupta un Om cu el pana in revarsatul zorilor, ii scranteste coapsa, il intreaba cum il cheama, si ii schimba numele. Pleaca de acolo binecuvantat si schiop.",
        "status": "in_review"
      },
      {
        "id": "geneza-33",
        "bookId": "geneza",
        "number": 33,
        "title": "Geneza 33 — Fratele care alearga si imbratiseaza",
        "summary": "Dupa douazeci de ani de frica, cei doi frati se intalnesc. Iacov se pleaca de sapte ori pana la pamant, asteptandu-se la sabie — iar Esau alearga, il imbratiseaza si plange cu el. Dumnezeu topise ura aceea fara ca nimeni sa stie. Dar la sfarsit, cel care fusese schimbat la Iaboc nu-si tine cuvantul dat fratelui, se abate din drum si isi cumpara pamant langa o cetate din care va veni multa durere.",
        "status": "in_review"
      },
      {
        "id": "geneza-34",
        "bookId": "geneza",
        "number": 34,
        "title": "Geneza 34 — Ce a costat popasul la Sihem",
        "summary": "Dina, singura fata a lui Iacov, este siluita de fiul stapanitorului cetatii. Tatal ei tace, fratii ei fierb, iar familia legamantului foloseste semnul legamantului ca sa insele o cetate intreaga si sa o macelareasca. Nimeni nu iese curat din capitolul acesta, afara de fata careia nimeni nu-i da cuvantul. Iar la sfarsit, tatal se plange numai de primejdia lui.",
        "status": "in_review"
      },
      {
        "id": "geneza-35",
        "bookId": "geneza",
        "number": 35,
        "title": "Geneza 35 — Scoala-te si suie-te la Betel",
        "summary": "Dupa prapadenia din Sihem, Dumnezeu il cheama pe Iacov inapoi la locul celei dintai intalniri. Casa isi ingroapa idolii, ridica altarul fagaduit cu douazeci de ani in urma, si primeste iarasi numele cel nou. Apoi vine sirul mormintelor: doica, Rahela, si la sfarsit Isaac. Se naste Beniamin, se ingroapa mama lui, se afla pacatul lui Ruben, si totusi la mijloc sta un altar. Capitolul acesta arata cum poate un om sa se intoarca acasa tarziu, si sa fie primit.",
        "status": "in_review"
      },
      {
        "id": "geneza-36",
        "bookId": "geneza",
        "number": 36,
        "title": "Geneza 36 — Neamul lui Esau",
        "summary": "Un capitol intreg dat neamului fratelui care nu a fost ales. Esau ajunge bogat, se aseaza in muntele Seir, are capetenii si imparati cu mult inainte ca Israel sa aiba unul. Sfanta Scriptura ii scrie numele cu grija, si apoi il lasa deoparte, ca sa mearga mai departe cu casa saraca a fagaduintei.",
        "status": "in_review"
      },
      {
        "id": "geneza-37",
        "bookId": "geneza",
        "number": 37,
        "title": "Geneza 37 — Haina, visele si groapa",
        "summary": "Un tata care iubeste pe fata, o haina care spune tuturor cine este cel de pe urma, doi frati care nu mai pot vorbi frumos, si doua vise care aprind totul. Iosif este aruncat intr-o groapa fara apa, vandut cu douazeci de sicli de argint, si plans ca mort de un tata care nu se lasa mangaiat. Iar ultimul rand al capitolului deschide un drum pe care nimeni nu-l vedea.",
        "status": "in_review"
      },
      {
        "id": "geneza-38",
        "bookId": "geneza",
        "number": 38,
        "title": "Geneza 38 — Iuda si Tamar",
        "summary": "In mijlocul povestii lui Iosif se opreste totul, si ni se arata ce facea, in vremea aceea, fratele care il vanduse. Iuda se desparte de ai lui, isi ia nevasta din Canaan, isi ingroapa doi fii si minte pe nora lui, lasand-o vaduva fara nadejde. Tamar isi face singura dreptate, prin viclesug si prin rusine. Iar cand se descopera totul, Iuda spune cea dintai vorba cinstita a vietii lui: ea este mai putin vinovata decat mine. Din femeia aceasta se va naste sirul care duce la Imparat.",
        "status": "in_review"
      },
      {
        "id": "geneza-39",
        "bookId": "geneza",
        "number": 39,
        "title": "Geneza 39 — Domnul a fost cu Iosif",
        "summary": "Un baiat vandut ca rob ajunge in casa unui dregator egiptean, si acolo se scrie cel mai important lucru din tot capitolul: Domnul a fost cu Iosif. Este ridicat peste toata casa, este ispitit zi dupa zi, fuge lasandu-si haina in mana, este parat cu minciuna si aruncat in temnita fara judecata. Iar cel din urma rand spune iarasi acelasi lucru: Domnul a fost cu el. Si in casa, si in inchisoare.",
        "status": "in_review"
      },
      {
        "id": "geneza-40",
        "bookId": "geneza",
        "number": 40,
        "title": "Geneza 40 — Doua visuri in temnita",
        "summary": "Doi slujitori ai lui Faraon ajung in aceeasi temnita cu Iosif, si intr-o noapte viseaza amandoi. El le tal maceste visurile, spunand mai intai ca talmacirile sunt ale lui Dumnezeu. Unul este ridicat, celalalt este pierdut, intocmai cum spusese. Iar omul scapat il uita pe cel care il ajutase. Capitolul se incheie cu cea mai grea vorba: l-a uitat.",
        "status": "in_review"
      },
      {
        "id": "geneza-41",
        "bookId": "geneza",
        "number": 41,
        "title": "Geneza 41 — De la temnita la tronul Egiptului",
        "summary": "Dupa doi ani de tacere, Faraon viseaza doua visuri pe care nimeni nu le poate talmaci. Paharnicul isi aduce aminte, in sfarsit, de omul din temnita. Iosif este scos in graba, se barbiereste, isi schimba hainele si sta inaintea imparatului — si cel dintai cuvant pe care il spune este: nu eu, ci Dumnezeu. In aceeasi zi, robul de treizeci de ani ajunge al doilea in tara. Apoi vin sapte ani de belsug, si dupa ei foametea, care va aduce si zece frati din Canaan la usa lui.",
        "status": "in_review"
      },
      {
        "id": "geneza-42",
        "bookId": "geneza",
        "number": 42,
        "title": "Geneza 42 — Zece frati inaintea celui pe care l-au vandut",
        "summary": "Foametea ajunge in Canaan, si Iacov isi trimite fiii in Egipt dupa grau. Se pleaca cu fata la pamant inaintea unui dregator in haine egiptene, si nu-l cunosc. El ii cunoaste. Nu se descopera indata, ci ii pune la incercare, pana cand, fara sa stie ca-i intelege, isi marturisesc intre ei pacatul de acum douazeci de ani. Iosif se intoarce si plange. Se intorc acasa cu graul si cu argintul pus inapoi in saci, iar batranul tata zice: toate acestea sunt impotriva mea.",
        "status": "in_review"
      },
      {
        "id": "geneza-43",
        "bookId": "geneza",
        "number": 43,
        "title": "Geneza 43 — Chezasul si masa intinsa",
        "summary": "Graul se ispraveste, si casa lui Iacov trebuie sa se pogoare din nou in Egipt. Batranul se impotriveste, pana cand Iuda se pune chezas pentru Beniamin cu insusi sufletul lui. Pleaca cu daruri, cu argint indoit si cu o rugaciune: Dumnezeul cel Atotputernic sa va faca sa capatati trecere. In Egipt sunt dusi in casa dregatorului si tremura de frica, dar in loc de judecata li se intinde masa. Iosif isi vede fratele dupa mama si iese sa planga, iar la sfarsit stau toti unsprezece la masa cu el, uimiti si veseli.",
        "status": "in_review"
      },
      {
        "id": "geneza-44",
        "bookId": "geneza",
        "number": 44,
        "title": "Geneza 44 — Cupa in sacul lui Beniamin",
        "summary": "Iosif pune cupa lui de argint in sacul lui Beniamin si trimite dupa ei. Cupa se gaseste, si toti isi rup hainele. Ar fi putut sa-l lase pe cel mai tanar acolo si sa plece slobozi, cum il lasasera pe Iosif intr-o groapa. Nici unul nu pleaca. Iar Iuda, cel care il vanduse odata, sta inaintea dregatorului si spune cea mai lunga cuvantare din cartea Genezei, incheind cu rugamintea de a ramane el rob in locul fratelui sau.",
        "status": "in_review"
      },
      {
        "id": "geneza-45",
        "bookId": "geneza",
        "number": 45,
        "title": "Geneza 45 — Eu sunt Iosif",
        "summary": "Dupa cuvantarea lui Iuda, Iosif nu se mai poate stapani. Da afara pe toti egiptenii si le spune fratilor sai cine este. Ei amutesc de spaima. Iar el, in loc sa le ceara socoteala, le zice de trei ori ca nu ei l-au trimis acolo, ci Dumnezeu, si ii cheama sa vina cu toata casa in Egipt. Faraon aude si se bucura, si trimite carute dupa batranul tata. Iar Iacov, care nu mai crezuse nimic douazeci si doi de ani, isi vine in fire si zice: destul! fiul meu Iosif tot mai traieste.",
        "status": "in_review"
      },
      {
        "id": "geneza-46",
        "bookId": "geneza",
        "number": 46,
        "title": "Geneza 46 — Nu te teme sa te pogori in Egipt",
        "summary": "Iacov porneste spre Egipt, dar se opreste la Beer-Seba si aduce jertfe Dumnezeului tatalui sau. Acolo Dumnezeu ii vorbeste noaptea si ii spune sa nu se teama, fiindca acolo va face din el un neam mare si Se va pogori impreuna cu el. Se scrie apoi numarul celor saptezeci de suflete care intra in Egipt. Iar la sfarsit, dupa douazeci si doi de ani, batranul isi vede fiul si zice ca poate sa moara.",
        "status": "in_review"
      },
      {
        "id": "geneza-47",
        "bookId": "geneza",
        "number": 47,
        "title": "Geneza 47 — Un batran binecuvinteaza pe imparat",
        "summary": "Iosif isi infatiseaza fratii inaintea lui Faraon, si acestia capata tinutul Gosen. Apoi isi aduce tatal, iar batranul, in loc sa se plece si sa ceara, il binecuvinteaza pe imparatul Egiptului si spune ca zilele lui au fost putine si rele. Foametea se ingreuiaza, si Iosif carmuieste tara pana cand tot Egiptul ajunge al lui Faraon, dar oamenii traiesc. La sfarsit, Israel simte ca i se apropie moartea si pune pe Iosif sa-i jure ca nu-l va ingropa in Egipt.",
        "status": "in_review"
      },
      {
        "id": "geneza-48",
        "bookId": "geneza",
        "number": 48,
        "title": "Geneza 48 — Mainile incrucisate",
        "summary": "Iosif isi aduce cei doi fii la patul tatalui sau bolnav. Batranul se scoala din pat cu greu, ii ia pe amandoi ca pe fiii lui, si povesteste despre Dumnezeul care i S-a aratat la Luz si despre Rahela ingropata pe drum. Apoi isi incruciseaza mainile, punand dreapta peste capul celui mai tanar. Iosif vrea sa-l indrepte, iar tatal ii spune ca stie, si ca cel mic va fi mai mare. Si rosteste cea mai frumoasa binecuvantare a lui: Dumnezeul care m-a hranit ca un pastor de cand sunt.",
        "status": "in_review"
      },
      {
        "id": "geneza-49",
        "bookId": "geneza",
        "number": 49,
        "title": "Geneza 49 — Cuvantul din urma al lui Iacov",
        "summary": "Batranul isi cheama cei doisprezece fii si le spune, unuia cate unuia, ce va fi cu ei in vremurile care vin. Nu este o binecuvantare dulce pentru toti: cei dintai trei primesc mustrare pentru fapte de acum zeci de ani. Asupra lui Iuda se aseaza toiagul de carmuire, pana va veni Silo. Iosif primeste cea mai bogata parte. La sfarsit, batranul le porunceste sa-l ingroape la Macpela, isi trage picioarele in pat si moare.",
        "status": "in_review"
      },
      {
        "id": "geneza-50",
        "bookId": "geneza",
        "number": 50,
        "title": "Geneza 50 — Voi ati avut in gand sa-mi faceti rau",
        "summary": "Iosif se arunca peste fata tatalui sau si plange. Egiptul jeleste saptezeci de zile, si apoi o alaiul urias urca in Canaan si il ingroapa pe Iacov la Macpela. Intorsi in Egipt, fratii se tem ca acum, dupa moartea tatalui, Iosif se va razbuna, si trimit vorba cerand iertare. Iosif plange, si le spune cuvantul care incheie toata cartea: voi ati avut in gand sa-mi faceti rau, dar Dumnezeu a schimbat raul in bine. La sfarsit moare si el, si cere ca oasele lui sa fie duse afara din Egipt.",
        "status": "in_review"
      }
    ]
  }
] satisfies BibleBookSummary[]
