export const DEUTERONOM_TEXT_7: Record<number, readonly string[]> = {
  7: [
    "„Când DOMNUL, Dumnezeul tău, te va duce în țara în care intri s-o iei în stăpânire și va alunga dinaintea ta multe neamuri: pe hetiți, pe ghirgașiți, pe amoriți, pe canaaniți, pe fereziți, pe heviți și pe iebusiți, șapte neamuri mai mari și mai puternice decât tine,",
    "și când DOMNUL, Dumnezeul tău, ți le va da în mână și le vei bate, să le dai spre nimicire cu desăvârșire. Să nu închei legământ cu ele și să nu ai milă de ele.",
    "Să nu te înrudești cu ele: să nu dai pe fiica ta fiului lui și să nu iei pe fiica lui pentru fiul tău;",
    "căci ar abate pe fiul tău de la Mine și ar sluji altor dumnezei; atunci mânia DOMNULUI S-ar aprinde împotriva voastră și te-ar nimici degrabă.",
    "Dimpotrivă, iată cum să vă purtați cu ele: să le dărâmați altarele, să le sfărâmați stâlpii sacri, să le tăiați așerele și să ardeți în foc chipurile lor cioplite.",
    "Căci tu ești un popor sfânt pentru DOMNUL, Dumnezeul tău. DOMNUL, Dumnezeul tău, te-a ales ca să-I fiți un popor deosebit dintre toate popoarele de pe fața pământului.",
    "Nu pentru că ați fi mai numeroși decât toate celelalte popoare S-a alipit DOMNUL de voi și v-a ales, căci voi erați cei mai puțini dintre toate popoarele;",
    "ci pentru că DOMNUL vă iubește și pentru că păzește jurământul pe care l-a făcut părinților voștri, de aceea te-a scos DOMNUL cu mână tare și te-a răscumpărat din casa robiei, din mâna lui Faraon, împăratul Egiptului.",
    "Să știi dar că DOMNUL, Dumnezeul tău, este singurul Dumnezeu, Dumnezeul cel credincios, Care păzește legământul și îndurarea până la a mia generație față de cei ce-L iubesc și păzesc poruncile Lui,",
    "dar Răsplătește în față pe cei ce-L urăsc, pierzându-i. El nu întârzie față de cel ce-L urăște, ci îi răsplătește în față.",
    "Păzește dar poruncile, legile și orânduirile pe care ți le dau astăzi, ca să le împlinesc.",
    "Dacă veți asculta aceste orânduiri, dacă le veți păzi și le veți împlini, DOMNUL, Dumnezeul tău, va păstra față de tine legământul și îndurarea pe care le-a jurat părinților tăi.",
    "El te va iubi, te va binecuvânta și te va înmulți; va binecuvânta rodul pântecelui tău și rodul pământului tău, grâul tău, mustul tău, uleiul tău, rodul vacilor tale și fătarea oilor tale, în țara pe care a jurat părinților tăi că ți-o va da.",
    "Vei fi binecuvântat mai mult decât toate popoarele; nu va fi printre voi nici bărbat, nici femeie neroditoare, nici printre vitele tale.",
    "DOMNUL va îndepărta de la tine orice boală și nu-ți va trimite nicio molimă rea din Egipt, pe care le cunoști, ci le va trimite peste toți cei ce te urăsc.",
    "Vei nimici toate popoarele pe care ți le dă DOMNUL, Dumnezeul tău; ochiul tău să n-aibă milă de ele și să nu slujești dumnezeilor lor, căci aceasta ar fi o cursă pentru tine.",
    "Dacă vei zice în inima ta: «Neamurile acestea sunt mai numeroase decât mine; cum aș putea să le alung?»,",
    "nu te teme de ele! Adu-ți aminte ce a făcut DOMNUL, Dumnezeul tău, lui Faraon și întregului Egipt,",
    "încercările cele mari pe care le-au văzut ochii tăi, semnele și minunile, mâna cea tare și brațul întins prin care te-a scos DOMNUL, Dumnezeul tău. Așa va face DOMNUL, Dumnezeul tău, tuturor popoarelor de care te temi.",
    "DOMNUL, Dumnezeul tău, va trimite chiar și viespile bondărești împotriva lor, până vor pieri cei ce vor fi rămas și se vor fi ascuns dinaintea ta.",
    "Nu te spăimânta din cauza lor, căci DOMNUL, Dumnezeul tău, este în mijlocul tău, un Dumnezeu mare și înfricoșător.",
    "DOMNUL, Dumnezeul tău, va alunga treptat aceste neamuri dinaintea ta; nu le vei putea nimici deodată, ca să nu se înmulțească împotriva ta fiarele câmpului.",
    "Dar DOMNUL, Dumnezeul tău, ți le va da în mână și le va arunca într-o mare învălmășeală, până vor fi nimicite.",
    "El va da pe împărații lor în mâinile tale și le vei șterge numele de sub cer; nimeni nu va putea sta împotriva ta, până îi vei nimici.",
    "Chipurile cioplite ale dumnezeilor lor să le ardeți în foc. Să nu poftești argintul și aurul de pe ele și să nu le iei pentru tine, ca nu cumva să fii prins în cursă de ele, căci sunt o urâciune înaintea DOMNULUI, Dumnezeul tău.",
    "Să nu aduci niciun lucru urâcios în casa ta, ca să nu fii dat spre nimicire ca el; să-ți fie scârbă de el și să-l urăști cu desăvârșire, căci este dat spre nimicire.”",
  ],
}
