export const DEUTERONOM_TEXT_21: Record<number, readonly string[]> = {
  21: [
    "„Dacă se va găsi un om omorât în țara pe care ți-o dă DOMNUL, Dumnezeul tău, s-o stăpânești, căzut pe câmp, fără să se știe cine l-a lovit,",
    "bătrânii tăi și judecătorii tăi să iasă și să măsoare distanța până la cetățile din împrejurul celui omorât.",
    "Bătrânii cetății celei mai apropiate de cel omorât să ia o junică din cireada care n-a fost pusă la muncă și care n-a tras la jug.",
    "Bătrânii acelei cetăți să coboare junica într-o vale cu apă curgătoare, care nu este nici arată, nici semănată, și acolo să-i frângă gâtul junicii în vale.",
    "Atunci să se apropie preoții, fiii lui Levi; căci pe ei i-a ales DOMNUL, Dumnezeul tău, ca să-I slujăească și să binecuvânteze în Numele DOMNULUI, și după cuvântul lor să se rezolve orice neînțelegere și orice rănire.",
    "Toți bătrânii acelei cetăți, cei mai apropiați de cel omorât, să-și spele mâinile peste junica căreia i s-a frânt gâtul în vale.",
    "Și să ia cuvântul și să zică: «Mâinile noastre n-au vărsat sângele acesta și ochii noștri nu l-au văzut vărsându-se.",
    "Iartă, DOMNE, pe poporul Tău Israel, pe care l-ai răscumpărat, și nu încărca pe poporul Tău Israel cu sânge nevinovat!» Și sângele le va fi iertat.",
    "Astfel vei curăți din mijlocul tău sângele nevinovat, făcând ce este drept în ochii DOMNULUI.",
    "Când vei ieși la război împotriva vrăjmașilor tăi și DOMNUL, Dumnezeul tău, ți-i va da în mâini și vei lua prinși de război,",
    "dacă vei vedea printre prinși o femeie frumoasă la chip și te vei alipi de ea și vei voi s-o iei de nevastă,",
    "s-o duci în casa ta. Ea să-și radă capul, să-și taie unghiile,",
    "să-și dezbrace hainele pe care le purta când a fost prinsă, să rămână în casa ta și să-și plângă pe tatăl ei și pe mama ei o lună întreagă. După aceea să intri la ea, să-i fii bărbat și ea să-ți fie nevastă.",
    "Dacă nu-ți va mai plăcea, să-i dai drumul unde va voi, dar nu vei putea s-o vinzi pe argint, nici s-o folosești ca roabă, pentru că ai smerit-o.",
    "Dacă un om va avea două neveste, una iubită și alta neiubită, și dacă atât cea iubită, cât și cea neiubită îi vor naște fii, iar fiul întâi născut va fi al celei neiubite,",
    "când îiși va împărți averea fiilor săi, nu va putea da dreptul de întâi născut fiului celei iubite în locul fiului celei neiubite, care este adevăratul întâi născut;",
    "ci să-l recunoască de întâi născut pe fiul celei neiubite și să-i dea o parte dublă din tot ce va avea; căci el este pârga puterii lui și dreptul de întâi născut este al lui.",
    "Dacă un om are un fiu îndărătnic și răzvrătit, care n-ascultă nici de glasul tatălui său, nici de glasul mamei sale, și care, după ce l-au pedepsit, tot n-ascultă de ei,",
    "tatăl lui și mama lui să-l apuce, să-l ducă la bătrânii cetății lui și la poarta locului unde locuiește,",
    "și să spună bătrânilor cetății lui: «Fiul nostru acesta este îndărătnic și răzvrătit; n-ascultă de glasul nostru, este desfrânat și bețiv.»",
    "Și toți oamenii cetății lui să-l ucidă cu pietre și să moară. Astfel să curăți răul din mijlocul tău, pentru ca tot Israelul să audă și să se teamă.",
    "Dacă un om va fi săvârșit un păcat vrednic de moarte și va fi fost pus la moarte, și l-ai spânzurat pe lemn,",
    "trupul lui să nu rămână peste noapte pe lemn, ci să-l îngropi neapărat în aceeași zi; căci cel spânzurat pe lemn este blestemat de Dumnezeu, ca să nu spurci țara pe care ți-o dă DOMNUL, Dumnezeul tău, ca moștenire.”",
  ],
}
