export const DEUTERONOM_TEXT_6: Record<number, readonly string[]> = {
  6: [
    "„Acestea sunt poruncile, legile și orânduirile pe care a poruncit DOMNUL, Dumnezeul vostru, să vă învăț să le împliniți în țara în care treceți s-o luați în stăpânire,",
    "ca să te temi de DOMNUL, Dumnezeul tău, păzind în toate zilele vieții tale toate legile și poruncile Lui pe care ți le dau, tu, fiul tău și fiul fiului tău, și ca să ți se lungească zilele.",
    "Ascultă-le dar, Israele, și caută să le împlinesc, ca să-ți fie bine și să vă înmulțiți mult, așa cum ți-a promis DOMNUL, Dumnezeul părinților tăi, într-o țară în care curge lapte și miere.",
    "Ascultă, Israele! DOMNUL este Dumnezeul nostru, DOMNUL este unul.",
    "Să-L iubești pe DOMNUL, Dumnezeul tău, din toată inima ta, din tot sufletul tău și din toată puterea ta.",
    "Cuvintele acestea, pe care ți le poruncesc astăzi, să fie în inima ta.",
    "Să le îtipărești în fiii tăi și să vorbești despre ele când vei fi acasă, când vei umbla pe drum, când te vei culca și când te vei scula.",
    "Să le legi ca un semn pe mâna ta și să-ți fie ca niște fruntarii între ochi.",
    "Să le scrii pe ușorii casei tale și pe porțile tale.",
    "Când DOMNUL, Dumnezeul tău, te va duce în țara pe care a jurat părinților tăi, lui Avraam, lui Isaac și lui Iacov, că ți-o va da, cetăți mari și bune pe care nu tu le-ai zidit,",
    "case pline de toate bunătățile pe care nu tu le-ai umplut, fântâni săpate pe care nu tu le-ai săpat, vii și măslini pe care nu tu i-ai sădit, și când vei mânca și te vei sătura,",
    "veghează asupra ta ca nu cumva să-L uiți pe DOMNUL, Care te-a scos din țara Egiptului, din casa robiei.",
    "De DOMNUL, Dumnezeul tău, să te temi, Lui să-I slujești și pe Numele Lui să juri.",
    "Să nu mergeți după alți dumnezei, dintre dumnezeii popoarelor care vă înconjoară,",
    "căci DOMNUL, Dumnezeul tău, Care este în mijlocul tău, este un Dumnezeu gelos; ca nu cumva să Se aprindă mânia DOMNULUI, Dumnezeul tău, împotriva ta și să te nimicească de pe fața pământului.",
    "Să nu-L ispitiți pe DOMNUL, Dumnezeul vostru, așa cum L-ați ispitit la Masa.",
    "Păziți cu grijă poruncile DOMNULUI, Dumnezeul vostru, mărturiile și legile Lui pe care ți le-a poruncit.",
    "Să faci ce este drept și bun în ochii DOMNULUI, ca să-ți fie bine și să intri să iei în stăpânire țara cea bună pe care DOMNUL a jurat părinților tăi că ți-o va da,",
    "alungând pe toți vrăjmașii tăi dinaintea ta, așa cum a vorbit DOMNUL.",
    "Când fiul tău te va întreba într-o zi, zicând: «Ce înseamnă aceste mărturii, legi și orânduiri pe care vi le-a poruncit DOMNUL, Dumnezeul nostru?»,",
    "să-i spui fiului tău: «Noi eram robi ai lui Faraon în Egipt, dar DOMNUL ne-a scos din Egipt cu mână tare.",
    "DOMNUL a făcut sub ochii noștri semne și minuni mari și nimicitoare împotriva Egiptului, împotriva lui Faraon și împotriva întregii lui case,",
    "iar pe noi ne-a scos de acolo ca să ne ducă și să ne dea țara pe care o jurase părinților noștri.",
    "De aceea DOMNUL ne-a poruncit să împlinim toate aceste legi și să ne temem de DOMNUL, Dumnezeul nostru, ca să fim fericitți întotdeauna și să ne țină în viață, așa cum face astăzi.",
    "Și aceasta va fi neprihănirea noastră: să păzim și să împlinim toate aceste porunci înaintea DOMNULUI, Dumnezeul nostru, așa cum ne-a poruncit El.»”",
  ],
}
