export const DEUTERONOM_TEXT_2: Record<number, readonly string[]> = {
  2: [
    "Apoi ne-am întors și am pornit spre pustie, pe drumul spre Marea Roșie, așa cum îmi spusese DOMNUL, și am ocolit muntele Seir multă vreme.",
    "DOMNUL mi-a vorbit, zicând:",
    "„Ați ocolit destul muntele acesta; întoarceți-vă spre nord.",
    "Și dă poporului această poruncă: «Veți trece prin hotarul fraților voștri, urmașii lui Esau, care locuiesc în Seir. Ei se vor teme de voi, dar vegheați asupra voastră.",
    "Nu vă înfruntați cu ei, căci nu vă voi da din țara lor nici măcar lățimea unui picior, pentru că muntele Seir i l-am dat în stăpânire lui Esau.",
    "Să cumpărați de la ei hrană pe argint, ca să mâncați, și să cumpărați de la ei apă pe argint, ca să beți.",
    "Căci DOMNUL, Dumnezeul tău, te-a binecuvântat în toată lucrarea mâinilor tale. El a vegheat asupra călătoriei tale prin această pustie mare. Acești patruzeci de ani, DOMNUL, Dumnezeul tău, a fost cu tine și nu ai dus lipsă de nimic.»”",
    "Trecând pe lângă frații noștri, fiii lui Esau, care locuiau în Seir, pe drumul din Arabah, de la Elat și Ezion-Geber, ne-am întors și am trecut pe drumul spre pustia Moabului.",
    "DOMNUL mi-a zis: „Nu fi dușmănos cu Moabul și nu te angaja în luptă cu el, căci nu-ți voi da nimic din țara lui în stăpânire, pentru că Arul l-am dat în stăpânire urmașilor lui Lot.”",
    "(Mai înainte locuiau acolo emiții, un popor mare, numeros și înalt ca anaciții.",
    "Ei erau socotiți tot refaimiți, ca și anaciții, dar moabiții îi numeau emiți.",
    "În Seir locuiau mai înainte horiții; dar fiii lui Esau i-au alungat, i-au nimicit dinaintea lor și au locuit în locul lor, așa cum a făcut Israel în țara stăpânirii sale, pe care i-a dat-o DOMNUL.)",
    "„Acum sculați-vă și treceți pârâul Zered!” Și am trecut pârâul Zered.",
    "Timpul cât am mers de la Cadeș-Barnea până la trecerea pârâului Zered a fost de treizeci și opt de ani, până când a pierit din mijlocul taberei toată generația oamenilor de război, așa cum le jurase DOMNUL.",
    "Mâna DOMNULUI a fost împotriva lor, ca să-i nimicească din mijlocul taberei până la dispariția lor completă.",
    "După ce au pierit toți oamenii de război prin moarte din mijlocul poporului,",
    "DOMNUL mi-a vorbit, zicând:",
    "„Astăzi vei trece hotarul Moabului la Ar",
    "și te vei apropia de fiii lui Amon. Nu-i dușmăni și nu te certa cu ei, căci nu-ți voi da nimic din țara fiilor lui Amon în stăpânire, pentru că am dat-o în stăpânire urmașilor lui Lot.”",
    "(Și aceasta era socotită țară a refaimiților; refaimiții locuiau acolo mai înainte, iar amoniții îi numeau zamzumimi,",
    "un popor mare, numeros și înalt ca anaciții. Dar DOMNUL i-a nimicit dinaintea amoniților, care i-au alungat și au locuit în locul lor,",
    "așa cum a făcut pentru fiii lui Esau, care locuiesc în Seir, când a nimicit pe horiți dinaintea lor; ei i-au alungat și au locuit în locul lor până în ziua de astăzi.",
    "De asemenea, pe aviții care locuiau în sate până la Gaza, caftoriții, ieșiți din Caftor, i-au nimicit și au locuit în locul lor.)",
    "„Sculați-vă, porniți la drum și treceți pârâul Arnon! Iată că ți-l dau în mână pe Sihon, împăratul Hesbonului, amoritul, și țara lui. Începe să iei în stăpânire și luptă-te cu el!",
    "De astăzi voi începe să răspândesc groaza și frica de tine peste popoarele de sub tot cerul; când vor auzi de tine, se vor cutremura și se vor înfiora din cauza ta.”",
    "Din pustia Chedemot am trimis soli la Sihon, împăratul Hesbonului, cu cuvinte de pace, zicând:",
    "«Lăsați-mă să trec prin țara ta; voi merge numai pe drumul mare, fără să mă abat nici la dreapta, nici la stânga.",
    "Hrana îmi vei vinde-o pe argint, ca să mănânc, și apa îmi vei da-o pe argint, ca să beu; lasă-mă doar să trec cu picioarele,",
    "așa cum mi-au făcut fiii lui Esau, care locuiesc în Seir, și moabiții, care locuiesc în Ar, până voi trece Iordanul în țara pe care ne-o dă DOMNUL, Dumnezeul nostru.»",
    "Dar Sihon, împăratul Hesbonului, n-a vrut să ne lase să trecem pe la el, căci DOMNUL, Dumnezeul tău, îi împietrise duhul și-i îmbolnăvise inima, ca să ți-l dea în mână, așa cum este astăzi.",
    "DOMNUL mi-a zis: «Iată, am început să ți-l dau pe Sihon și țara lui. Începe să iei în stăpânire țara lui!»",
    "Sihon a ieșit în întâmpinarea noastră cu tot poporul lui, ca să lupte la Iahaz.",
    "DOMNUL, Dumnezeul nostru, ni l-a dat în mână și l-am bătut pe el, pe fiii lui și pe tot poporul lui.",
    "Am cucerit atunci toate cetățile lui și am dat spre nimicire orice cetate cu bărbați, femei și copii; n-am lăsat niciun supraviețuitor.",
    "Numai vitele le-am luat ca pradă pentru noi, împreună cu prada din cetățile pe care le cucerisem.",
    "De la Aroer, care este pe marginea văii Arnonului, și de la cetatea din vale până la Galaad, n-a fost nicio cetate prea puternică pentru noi; DOMNUL, Dumnezeul nostru, ne-a dat totul în mână.",
    "Numai de țara fiilor lui Amon nu te-ai apropiat, de toate locurile de pe marginea pârâului Iaboc, de cetățile din munte și de tot ce poruncise DOMNUL, Dumnezeul nostru, să nu atingeți.",
  ],
}
