export const DEUTERONOM_TEXT_10: Record<number, readonly string[]> = {
  10: [
    "„În vremea aceea DOMNUL mi-a zis: «Cioplește două table de piatră ca cele dintâi, suie-te la Mine pe munte și fă-ți un chivot de lemn.",
    "Eu voi scrie pe table cuvintele care erau pe tablele dintâi, pe care le-ai sfărâmat, iar tu să le pui în chivot.»",
    "Am făcut deci un chivot din lemn de salcâm, am cioplit două table de piatră ca cele dintâi și m-am suit pe munte cu cele două table în mâini.",
    "DOMNUL a scris pe table, cum scrisese și prima dată, cele Zece Porunci pe care vi le rostise pe munte, din mijlocul focului, în ziua adunării; și DOMNUL mi le-a dat.",
    "M-am întors, am coborât din munte și am pus tablele în chivotul pe care îl făcusem; și ele au rămas acolo, așa cum îmi poruncise DOMNUL.",
    "(Fiii lui Israel au pornit de la Beerot-Bene-Iaacan la Mosera. Acolo a murit Aaron și a fost îngropat; iar fiul său Eleazar a slujit ca preot în locul lui.",
    "De acolo au pornit la Gudgoda, iar de la Gudgoda la Iotbata, țară cu pârâie de apă.",
    "În vremea aceea DOMNUL a pus deoparte seminția lui Levi ca să poarte chivotul legământului DOMNULUI, să stea înaintea DOMNULUI ca să-I slujăească și să binecuvânteze în Numele Lui, până în ziua de astăzi.",
    "De aceea Levi n-a avut parte nici de moștenire cu frații lui: DOMNUL este moștenirea lui, așa cum i-a spus DOMNUL, Dumnezeul tău.)",
    "Eu am rămas pe munte ca și prima dată, patruzeci de zile și patruzeci de nopți. DOMNUL m-a ascultat și de data aceasta; DOMNUL n-a vrut să te nimicească.",
    "DOMNUL mi-a zis: «Scoală-te, mergi în fruntea poporului, ca să intre și să ia în stăpânire țara pe care am jurat părinților lor că le-o voi da.»",
    "Acum, Israele, ce altceva cere de la tine DOMNUL, Dumnezeul tău, decât să te temi de DOMNUL, Dumnezeul tău, să umbli pe toate căile Lui, să-L iubești și să slujești DOMNULUI, Dumnezeului tău, din toată inima ta și din tot sufletul tău,",
    "să păzești poruncile DOMNULUI și legile Lui pe care ți le dau astăzi, ca să-ți fie bine?",
    "Iată, ale DOMNULUI, Dumnezeului tău, sunt cerurile și cerurile cerurilor, pământul și tot ce este pe el.",
    "Dar numai de părinții tăi S-a alipit DOMNUL ca să-i iubească și a ales urmașii lor după ei, pe voi, dintre toate popoarele, așa cum se vede astăzi.",
    "Tăiați împrejur dar cugetul inimii voastre și nu vă mai înțepeniți gâtul!",
    "Căci DOMNUL, Dumnezeul vostru, este Dumnezeul dumnezeilor și Domnul domnilor, Dumnezeul cel mare, puternic și înfricoșător, Care nu caută la fața oamenilor și nu primește mită;",
    "Care face dreptate orfanului și văduvei, Care îl iubește pe străin și îi dă hrană și îmbrăcăminte.",
    "Să-l iubiți și voi pe străin, căci și voi ați fost străini în țara Egiptului.",
    "De DOMNUL, Dumnezeul tău, să te temi, Lui să-I slujești, de El să te alipești și pe Numele Lui să juri.",
    "El este lauda ta, El este Dumnezeul tău, Care a făcut pentru tine aceste lucruri mari și înfricoșătoare pe care le-au văzut ochii tăi.",
    "Părinții tăi s-au coborat în Egipt în număr de șaptezeci de suflete, iar acum DOMNUL, Dumnezeul tău, te-a făcut numeros ca stelele cerului.”",
  ],
}
