export const DEUTERONOM_TEXT_8: Record<number, readonly string[]> = {
  8: [
    "„Toate poruncile pe care ți le dau astăzi să le păziți și să le împliniți, ca să trăiți, să vă înmulțiți și să intrați să luați în stăpânire țara pe care a jurat-o DOMNUL părinților voștri.",
    "Adu-ți aminte de tot drumul pe care te-a călăuzit DOMNUL, Dumnezeul tău, în acești patruzeci de ani în pustie, ca să te smerească și să te încerce, ca să cunoască ce este în inima ta, dacă vei păzi poruncile Lui sau nu.",
    "Te-a smerit, te-a lăsat să suferi de foame și te-a hrănit cu mană, pe care nu o cunoșteai și pe care nu o cunoșteau nici părinții tăi, ca să te învețe că omul nu trăiește numai cu pâine, ci cu orice cuvânt care iese din gura DOMNULUI trăiește omul.",
    "Haina nu ți s-a învechit pe tine și piciorul nu ți s-a umflat în acești patruzeci de ani.",
    "Recunoaște dar în inima ta că, așa cum își disciplinează un om fiul, așa te disciplinează DOMNUL, Dumnezeul tău.",
    "Păzește poruncile DOMNULUI, Dumnezeul tău, umblând pe căile Lui și temându-te de El.",
    "Căci DOMNUL, Dumnezeul tău, te duce într-o țară bună, o țară cu pârâie de apă, cu izvoare și adâncuri care țâșnesc în văi și pe munți;",
    "o țară cu grâu, orz, viță de vie, smochini și rodii; o țară cu măslini și miere;",
    "o țară în care vei mânca pâine fără lipsă și în care nu vei duce lipsă de nimic; o țară ale cărei pietre sunt fier și din ai cărei munți vei scoate aramă.",
    "Când vei mânca și te vei sătura, să-L binecuvântezi pe DOMNUL, Dumnezeul tău, pentru țara cea bună pe care ți-a dat-o.",
    "Veghează asupra ta ca nu cumva să-L uiți pe DOMNUL, Dumnezeul tău, nepăzind poruncile, orânduirile și legile Lui pe care ți le dau astăzi;",
    "ca nu cumva, după ce vei mânca și te vei sătura, după ce vei zidi case frumoase și vei locui în ele,",
    "după ce se vor înmulți cirezile și turmele tale, după ce se va înmulți argintul și aurul tău și tot ce ai se va înmulți,",
    "inima ta să se înfumureze și să-L uiți pe DOMNUL, Dumnezeul tău, Care te-a scos din țara Egiptului, din casa robiei;",
    "Care te-a călăuzit prin această pustie mare și înfricoșătoare, plină de șerpi arzători și scorpii, un pământ uscat și fără apă; Care a făcut să țâșnească pentru tine apă din stânca de cremene;",
    "Care te-a hrănit în pustie cu mană pe care n-o cunoșteau părinții tăi, ca să te smerească și să te încerce, pentru ca mai pe urmă să-ți facă bine.",
    "Vezi să nu zici în inima ta: «Puterea mea și tăria mâinii mele mi-au adus aceste bogății!»",
    "Ci adu-ți aminte de DOMNUL, Dumnezeul tău, căci El îți dă putere să câștigi bogății, ca să confirme legământul Său pe care l-a jurat părinților tăi, așa cum se vede astăzi.",
    "Dacă Îl vei uita pe DOMNUL, Dumnezeul tău, și vei merge după alți dumnezei, dacă le vei sluji și te vei închina înaintea lor, vă mărturisesc astăzi că veți pieri cu desăvârșire.",
    "Cum au pierit neamurile pe care le pierde DOMNUL dinaintea voastră, așa veți pieri și voi, pentru că nu veți fi ascultat de glasul DOMNULUI, Dumnezeul vostru.”",
  ],
}
