export const DEUTERONOM_TEXT_11: Record<number, readonly string[]> = {
  11: [
    "„Să-L iubești dar pe DOMNUL, Dumnezeul tău, și să păzești întotdeauna ce ți-a dat El de păzit, legile, orânduirile și poruncile Lui.",
    "Recunoașteți astăzi ce n-au cunoscut și ce n-au văzut fiii voștri: disciplina DOMNULUI, Dumnezeul vostru, mărimea Lui, mâna Lui cea tare și brațul Lui cel întins,",
    "semnele și lucrările Lui pe care le-a făcut în mijlocul Egiptului împotriva lui Faraon, împăratul Egiptului, și împotriva întregii lui țări;",
    "ce a făcut El oștirii Egiptului, cailor și carelor lui, peste care a făcut să se reverse apele Mării Roșii când vă urmăreau, și cum i-a nimicit DOMNUL până în ziua de astăzi;",
    "ce v-a făcut în pustie până la sosirea voastră în locul acesta;",
    "și ce le-a făcut lui Datan și lui Abiram, fiii lui Eliab, fiul lui Ruben, cum pământul și-a deschis gura și i-a înghițit cu casele lor, cu corturile lor și cu toate ființele care îi urcau în mijlocul întregului Israel.",
    "Căci ochii voștri au văzut toate lucrările cele mari pe care le-a făcut DOMNUL.",
    "Păziți dar toate poruncile pe care vi le dau astăzi, ca să fiți puternici și să intrați să luați în stăpânire țara în care treceți s-o luați,",
    "și ca să aveți zile multe în țara pe care DOMNUL a jurat părinților voștri că le-o va da lor și urmașilor lor, o țară în care curge lapte și miere.",
    "Căci țara în care intri s-o iei în stăpânire nu este ca țara Egiptului din care ați ieșit, unde îti semănai sămânța și o udai cu piciorul, ca pe o grădină de legume;",
    "ci țara în care treceți s-o luați în stăpânire este o țară cu munți și văi, care se udă din ploaia cerului;",
    "o țară de care Se îngrijește DOMNUL, Dumnezeul tău, și asupra căreia ochii DOMNULUI, Dumnezeul tău, sunt îndreptați neîncetat, de la începutul anului până la sfârșitul anului.",
    "Dacă veți asculta cu grijă de poruncile Mele pe care vi le dau astăzi, iubindu-L pe DOMNUL, Dumnezeul vostru, și slujindu-I din toată inima voastră și din tot sufletul vostru,",
    "Eu voi da țării voastre ploaie la vreme, ploaie timpurie și ploaie târzie, și vei strânge grâul tău, mustul tău și uleiul tău;",
    "voi da și iarbă în câmpul tău pentru vitele tale, și vei mânca și te vei sătura.",
    "Vegheați asupra voastră ca nu cumva să vi se amăgească inima și să vă abateți ca să slujiți altor dumnezei și să vă închinați înaintea lor;",
    "căci atunci mânia DOMNULUI S-ar aprinde împotriva voastră, ar închide cerurile și n-ar mai fi ploaie, pământul nu și-ar mai da roadele și ați pieri degrabă din țara cea bună pe care v-o dă DOMNUL.",
    "Puneți-vă aceste cuvinte ale Mele în inimă și în suflet; legați-le ca un semn pe mâna voastră și să-ți fie ca niște fruntarii între ochi.",
    "Învățați-i pe fiii voștri în ele, vorbind despre ele când vei fi acasă, când vei umbla pe drum, când te vei culca și când te vei scula.",
    "Scrie-le pe ușorii casei tale și pe porțile tale,",
    "ca zilele voastre și zilele fiilor voștri să se înmulțească în țara pe care DOMNUL a jurat părinților voștri că le-o va da, cât vor fi cerurile deasupra pământului.",
    "Căci dacă veți păzi cu grijă toate aceste porunci pe care vi le dau ca să le împliniți, iubindu-L pe DOMNUL, Dumnezeul vostru, umblând pe toate căile Lui și alipindu-vă de El,",
    "DOMNUL va alunga toate aceste neamuri dinaintea voastră și veți pune stăpânire pe neamuri mai mari și mai puternice decât voi.",
    "Orice loc pe care va călca talpa piciorului vostru va fi al vostru: hotarul vostru va fi de la pustie până la Liban, și de la râul cel mare, râul Eufrat, până la Marea de Apus.",
    "Nimeni nu va putea sta împotriva voastră; DOMNUL, Dumnezeul vostru, va răspândi frica și groaza de voi peste toată țara pe care veți călca, așa cum v-a promis.",
    "Iată, pun astăzi înaintea voastră binecuvântarea și blestemul:",
    "binecuvântarea, dacă veți asculta de poruncile DOMNULUI, Dumnezeul vostru, pe care vi le dau astăzi;",
    "și blestemul, dacă nu veți asculta de poruncile DOMNULUI, Dumnezeul vostru, și vă veți abate de la calea pe care v-o poruncesc astăzi, ca să mergeți după alți dumnezei pe care nu i-ați cunoscut.",
    "Când DOMNUL, Dumnezeul tău, te va duce în țara în care intri s-o iei în stăpânire, să pui binecuvântarea pe muntele Garizim și blestemul pe muntele Ebal.",
    "Munții aceștia sunt dincolo de Iordan, spre apus, în țara canaaniților care locuiesc în Arabah, în fața Ghilgalului, lângă stejarii lui More.",
    "Căci voi veți trece Iordanul ca să intrați să luați în stăpânire țara pe care v-o dă DOMNUL, Dumnezeul vostru; o veți stăpâni și veți locui în ea.",
    "Păziți dar și împliniți toate legile și orânduirile pe care vi le pun înainte astăzi.”",
  ],
}
