export const DEUTERONOM_TEXT_9: Record<number, readonly string[]> = {
  9: [
    "„Ascultă, Israele! Astăzi vei trece Iordanul ca să intri și să pui stăpânire pe neamuri mai mari și mai puternice decât tine, cetăți mari și fortificate până la cer,",
    "un popor mare și înalt, fiii anaciților, pe care îi cunoști și despre care ai auzit zicându-se: «Cine va putea sta împotriva fiilor lui Anac?»",
    "Să știi dar astăzi că DOMNUL, Dumnezeul tău, merge El Însuși înaintea ta ca un foc mistuitor; El îi va nimici și îi va supune dinaintea ta, iar tu îi vei alunga și îi vei pierde degrabă, așa cum ți-a spus DOMNUL.",
    "După ce DOMNUL, Dumnezeul tău, îi va alunga dinaintea ta, să nu zici în inima ta: «Pentru neprihănirea mea m-a dus DOMNUL să iau în stăpânire țara aceasta!» Căci din cauza răutății acestor neamuri le alungă DOMNUL dinaintea ta.",
    "Nu pentru neprihănirea ta, nici pentru curăția inimii tale intri tu să le iei țara în stăpânire, ci din cauza răutății acestor neamuri le alungă DOMNUL, Dumnezeul tău, dinaintea ta și ca să împlinească cuvântul pe care DOMNUL l-a jurat părinților tăi, lui Avraam, lui Isaac și lui Iacov.",
    "Să știi dar că nu pentru neprihănirea ta îiți dă DOMNUL, Dumnezeul tău, această țară bună s-o stăpânești, căci ești un popor încăpățânat.",
    "Adu-ți aminte și nu uita cum L-ai mâniat pe DOMNUL, Dumnezeul tău, în pustie. Din ziua în care ai ieșit din țara Egiptului până la sosirea voastră în locul acesta, v-ați răzvrătit mereu împotriva DOMNULUI.",
    "La Horeb L-ați mâniat pe DOMNUL, și DOMNUL S-a mâniat pe voi atât de tare încât voia să vă nimicească.",
    "Când m-am suit pe munte ca să primesc tablele de piatră, tablele legământului pe care îl încheiase DOMNUL cu voi, am rămas pe munte patruzeci de zile și patruzeci de nopți, fără să mănânc pâine și fără să beau apă.",
    "DOMNUL mi-a dat cele două table de piatră scrise cu degetul lui Dumnezeu, pe care erau toate cuvintele pe care vi le rostise DOMNUL pe munte, din mijlocul focului, în ziua adunării.",
    "La sfârșitul celor patruzeci de zile și patruzeci de nopți, DOMNUL mi-a dat cele două table de piatră, tablele legământului.",
    "DOMNUL mi-a zis: «Scoală-te, coboară degrabă de aici, căci poporul tău, pe care l-ai scos din Egipt, s-a stricat; s-au abătut degrabă de la calea pe care le-o poruncisem și și-au făcut un chip turnat.»",
    "DOMNUL mi-a vorbit, zicând: «Văd poporul acesta și iată că este un popor încăpățânat.",
    "Lasă-Mă să-i nimicesc și să le șterg numele de sub cer; iar pe tine te voi face un neam mai puternic și mai numeros decât ei.»",
    "M-am întors și am coborât din munte; iar muntele ardea în foc, și cele două table ale legământului erau în cele două mâini ale mele.",
    "Am privit și iată că păcătuiserăți împotriva DOMNULUI, Dumnezeul vostru: vă făcuserăți un vițel turnat, vă abătuserăți degrabă de la calea pe care v-o poruncise DOMNUL.",
    "Am apucat cele două table, le-am aruncat din amândouă mâinile mele și le-am sfărâmat sub ochii voștri.",
    "M-am aruncat cu fața la pământ înaintea DOMNULUI ca mai înainte, patruzeci de zile și patruzeci de nopți, fără să mănânc pâine și fără să beau apă, din cauza tuturor păcatelor pe care le făcuserăți, făcând ce este rău în ochii DOMNULUI ca să-L mâniați.",
    "Căci mă temeam de mânia și urgia cu care Se aprinsese DOMNUL împotriva voastră, ca să vă nimicească. Dar DOMNUL m-a ascultat și de data aceasta.",
    "DOMNUL S-a mâniat foarte tare și pe Aaron și voia să-l nimicească; dar m-am rugat în vremea aceea și pentru Aaron.",
    "Am luat păcatul vostru, vițelul pe care îl făcuserăți, l-am ars în foc, l-am sfărâmat și l-am pisat până s-a făcut pulbere fină, apoi am aruncat pulberea lui în pârâul care coboară din munte.",
    "Și la Tabera, la Masa și la Chibrot-Hataava L-ați mâniat pe DOMNUL.",
    "Și când v-a trimis DOMNUL de la Cadeș-Barnea, zicând: «Suiți-vă și luați în stăpânire țara pe care v-am dat-o!», v-ați răzvrătit împotriva poruncii DOMNULUI, Dumnezeul vostru; n-ați avut credință în El și n-ați ascultat de glasul Lui.",
    "V-ați răzvrătit împotriva DOMNULUI din ziua în care vă cunosc.",
    "M-am aruncat cu fața la pământ înaintea DOMNULUI cele patruzeci de zile și patruzeci de nopți în care am stat prosternat, pentru că DOMNUL spusese că vrea să vă nimicească.",
    "M-am rugat DOMNULUI și am zis: «Doamne DUMNEZEULE, nu nimici pe poporul Tău și moștenirea Ta pe care ai răscumpărat-o prin mărimea Ta, pe care ai scos-o din Egipt cu mână tare!",
    "Adu-ți aminte de slujitorii Tăi Avraam, Isaac și Iacov! Nu privi la încăpățânarea acestui popor, nici la răutatea lui, nici la păcatul lui,",
    "ca nu cumva țara din care ne-ai scos să zică: „Pentru că DOMNUL nu i-a putut duce în țara pe care le-o făgăduise și pentru că îi ura, de aceea i-a scos ca să-i lase să moară în pustie.”",
    "Totuși ei sunt poporul Tău și moștenirea Ta pe care ai scos-o prin puterea Ta cea mare și cu brațul Tău cel întins.»”",
  ],
}
