export const DEUTERONOM_TEXT_33: Record<number, readonly string[]> = {
  33: [
    "Iată binecuvântarea cu care Moise, omul lui Dumnezeu, i-a binecuvântat pe fiii lui Israel înainte de moartea sa.",
    "El a zis: „DOMNUL a venit din Sinai și le-a răsărit din Seir; A strălucit din muntele Paran și a venit cu zeci de mii de sfinți; din mâna Lui dreaptă le venea o lege de foc.",
    "Da, El iubește popoarele; toți sfinții Lui sunt în mâna Ta! Ei au stat la picioarele Tale și au primit cuvintele Tale.",
    "Moise ne-a dat Legea, moștenirea adunării lui Iacov.",
    "El a fost împărat în Ieșurun, când se adunau căpeteniile poporului, împreună cu semințiile lui Israel.",
    "Trăiască Ruben și să nu moară, și bărbații lui să nu fie puțini la număr!”",
    "Iată ce a zis pentru Iuda: „Ascultă, DOMNE, glasul lui Iuda și adu-l la poporul lui! Mâinile lui să se lupte pentru el și să-i fii ajutor împotriva vrăjmașilor lui!”",
    "Pentru Levi a zis: „Tumim-ul Tău și Urim-ul Tău sunt încredințate omului Tău sfânt, pe care L-ai încercat la Masa și cu care Te-ai certat la apele Meriba;",
    "cel ce zice despre tatăl său și despre mama sa: «Nu i-am văzut!», care nu-și cunoaște frații și nu-și știe fiii. Căci ei păzesc cuvântul Tău și păstrează legământul Tău.",
    "Ei învață pe Iacov orânduirile Tale și pe Israel Legea Ta; ei pun tămâie înaintea Nărilor Tale și ardere de tot pe altarul Tău.",
    "Binecuvântează, DOMNE, puterea lui și primește lucrarea mâinilor lui! Zdrobește coapsele potrivnicilor lui și ale celor ce-l urăsc, ca să nu se mai ridice!”",
    "Pentru Beniamin a zis: „Preaiubitul DOMNULUI va locui în siguranță lângă El. DOMNUL îl va ocroti întotdeauna și va locui între umerii lui.”",
    "Pentru Iosif a zis: „Ȝara lui să fie binecuvântată de DOMNUL cu cele mai bune daruri ale cerului, cu roua și cu apele adâncului care se află jos;",
    "cu cele mai bune roade ale soarelui și cu cele mai bune roade ale fiecărei luni;",
    "cu frunțile munților străvechi și cu ce este mai bun pe dealurile veșnice;",
    "cu ce este mai bun pe pământ și cu tot ce conține el, și cu bunăvoința Celui ce s-a arătat în rug! Această binecuvântare să vină pe capul lui Iosif, pe creștetul frunții prințului fraților săi!",
    "El are măreția primului născut al taurului său, și coarnele lui sunt coarne de bivol; cu ele va împunge popoarele până la marginile pământului. Ele sunt zecile de mii ale lui Efraim și miile lui Manase.”",
    "Pentru Zabulon a zis: „Bucură-te, Zabuloane, în ieșirile tale, și tu, Isahar, în corturile tale!",
    "Ei vor chema popoarele pe munte și acolo vor aduce jertfe de dreptate; căci vor suge belșugul mărilor și comorile ascunse în nisip.”",
    "Pentru Gad a zis: „Binecuvântat să fie cel ce lărgește pe Gad! El locuiește ca o leoaică și sfâșie brațul și creștetul capului.",
    "El și-a ales cea dintâi parte de țară, căci acolo îi era păstrată partea de căpetenie; a venit cu căpeteniile poporului, a îplinit dreptatea DOMNULUI și judecățile Lui cu Israel.”",
    "Pentru Dan a zis: „Dan este un pui de leu, care sare din Basan.”",
    "Pentru Neftali a zis: „Neftali, săturat de bunăvoință și plin de binecuvântarea DOMNULUI, ia în stăpânire apusul și sudul!”",
    "Pentru Așer a zis: „Binecuvântat să fie Așer între fiii lui Israel! Să fie plăcut fraților tăi și să-și moaie piciorul în ulei!",
    "Zăvoarele tale să fie de fier și de aramă, și putere ta să țină cât zilele tale!",
    "Nimeni nu este ca Dumnezeul lui Ieșurun, Care trece pe ceruri ca să-ți vină în ajutor și pe nori în măreția Sa.",
    "Dumnezeul cel veșnic este adăpostul tău și sub tine sunt brațele veșnice. El a alungat pe vrăjmaș dinaintea ta și a zis: «Nimicește!»",
    "Israel locuiește în siguranță, singuratic, izvorul lui Iacov într-o țară cu grâu și must, și cerurile lui picură rouă.",
    "Ferice de tine, Israele! Cine este ca tine, un popor mântuit de DOMNUL, scutul ajutorului tău și sabia măreției tale? Vrăjmașii tăi se vor linguși înaintea ta, iar tu vei călca pe înălțimile lor.”",
  ],
}
