export const DEUTERONOM_TEXT_17: Record<number, readonly string[]> = {
  17: [
    "„Să nu jertfești DOMNULUI, Dumnezeului tău, niciun bou și nicio oaie care să aibă vreun cusur sau vreo meteahnă rea, căci este o urâciune înaintea DOMNULUI, Dumnezeului tău.",
    "Dacă se va găsi în mijlocul tău, într-una din cetățile tale pe care ți le dă DOMNUL, Dumnezeul tău, un bărbat sau o femeie care să facă ce este rău în ochii DOMNULUI, Dumnezeului tău, călcând legământul Său,",
    "și să se ducă să slujăească altor dumnezei și să se închine înaintea lor, înaintea soarelui, lunii sau întregii oștiri a cerului, lucru pe care eu nu l-am poruncit,",
    "și ți se va da de știre și vei auzi, să cercetezi cu de-amănuntul. Dacă este adevărat și sigur că urâciunea aceasta a fost săvârșită în Israel,",
    "atunci să scoți la porțile cetății tale pe bărbatul sau femeia aceea care a făcut această faptă rea, și să-i ucizi cu pietre până vor muri.",
    "Cel vinovat de moarte să fie pus la moarte pe mărturia a doi sau trei martori; să nu fie pus la moarte pe mărturia unui singur martor.",
    "Mâna martorilor să fie cea dintâi asupra lui ca să-l pună la moarte, și apoi mâna întregului popor. Astfel să curăți răul din mijlocul tău.",
    "Dacă o cauză va fi prea grea pentru tine în judecată, între un omor și altul, între o neînțelegere și alta, între o rănire și alta, cauze de judecată în porțile tale, atunci scoală-te și suie-te la locul pe care-l va alege DOMNUL, Dumnezeul tău.",
    "Du-te la preoții leviți și la judecătorul care va fi în vremea aceea; întreabă-i și ei îti vor vesti hotărârea de judecată.",
    "Să faci potrivit cu hotărârea pe care ți-o vor vesti din locul pe care-l va alege DOMNUL, și să veghezi să faci potrivit cu tot ce te vor învăța.",
    "Să faci potrivit cu legea pe care te vor învăța și după judecata pe care ți-o vor rosti; să nu te abați de la hotărârea pe care ți-o vor vesti, nici la dreapta, nici la stânga.",
    "Bărbatul care va lucra cu trufie și nu va asculta de preotul care stă acolo ca să slujăească DOMNULUI, Dumnezeului tău, sau de judecător, bărbatul acela să fie dat la moarte. Astfel să curăți răul din Israel.",
    "Tot poporul va auzi și se va teme, și nu se va mai purta cu trufie.",
    "Când vei intra în țara pe care ți-o dă DOMNUL, Dumnezeul tău, o vei stăpâni și vei locui în ea, dacă vei zice: «Vreau să pun peste mine un împărat, ca toate neamurile care mă înconjoară!»,",
    "să pui peste tine ca împărat pe acela pe care-l va alege DOMNUL, Dumnezeul tău; din mijlocul fraților tăi să pui un împărat peste tine; nu vei putea pune peste tine un om străin, care să nu fie fratele tău.",
    "Numai să nu aibă mulți cai și să nu întoarcă poporul în Egipt ca să aibă mulți cai, căci DOMNUL v-a zis: «Să nu vă mai întoarceți niciodată pe drumul acesta!»",
    "Să nu aibă un mare număr de neveste, ca să nu i se abată inima; și să nu strângă mult argint și aur.",
    "Când se va așeza pe scaunul de domnie al împărăției lui, să scrie pentru sine într-o carte o copie a acestei Legi, luată dinaintea preoților leviți.",
    "S-o aibă cu sine și să citească în ea în toate zilele vieții lui, ca să învețe să Se teamă de DOMNUL, Dumnezeul său, păzind toate cuvintele acestei Legi și aceste orânduiri ca să le împlinească;",
    "pentru ca să nu i se înălțe inima mai presus de frații lui și să nu se abată de la poruncă nici la dreapta, nici la stânga, ca să aibă zile multe în împărăția lui, el și fiii lui, în mijlocul lui Israel.”",
  ],
}
