export const DEUTERONOM_TEXT_22: Record<number, readonly string[]> = {
  22: [
    "„Dacă vei vedea boul fratelui tău sau oaia lui rătăcite, să nu te prefaci că nu le vezi, ci să i le duci neapărat fratelui tău.",
    "Dacă fratele tău nu locuiește aproape de tine și nu-l cunoști, să le aduci în casa ta și să rămână la tine până le va căuta fratele tău; atunci să i le dai înapoi.",
    "La fel să faci cu măgarul lui, la fel să faci cu haina lui și la fel să faci cu orice lucru pierdut de fratele tău și pe care îl vei fi găsit tu; să nu te prefaci că nu-l vezi.",
    "Dacă vei vedea măgarul fratelui tău sau boul lui căzuți pe drum, să nu te prefaci că nu-i vezi, ci să-i ajuți neapărat să se ridice.",
    "O femeie să nu poarte îmbrăcăminte bărbătească și un bărbat să nu se îmbrace în haine femeiești; căci oricine face aceste lucruri este o urâciune înaintea DOMNULUI, Dumnezeului tău.",
    "Dacă găsești pe drum un cuib de pasăre într-un copac sau pe pământ, cu pui sau cu ouă, și mama stă pe pui sau pe ouă, să nu iei pe mamă împreună cu puii;",
    "ci pe mamă s-o lași neapărat să zboare și numai puii să-i iei pentru tine, ca să-ți fie bine și să ai zile multe.",
    "Când îiți vei zidi o casă nouă, să-i faci o balustradă la acoperiș, ca să nu aduci vinovăția sângelui asupra casei tale dacă ar cădea cineva de pe ea.",
    "Să nu semeni în via ta două feluri de semințe, ca nu cumva întregul rod al seminței pe care ai semănat-o și rodul viei să fie confiscate.",
    "Să nu ari cu un bou și cu un măgar înhămați împreună.",
    "Să nu porți-o haină țesută din două feluri de fire, din lână și din in împreună.",
    "Să-ți faci ciucuri la cele patru colțuri ale hainei cu care te acoperi.",
    "Dacă un om îiși ia o nevastă și intră la ea, iar apoi o urăște,",
    "și îi pune pe seamă fapte de rușine și îi scoate nume rău, zicând: «Am luat pe femeia aceasta, m-am apropiat de ea și n-am găsit la ea semnele feciorei!»,",
    "atunci tatăl fetei și mama ei să ia și să ducă bătrânilor cetății, la poartă, semnele feciorei fetei.",
    "Și tatăl fetei să spună bătrânilor: «Am dat pe fiica mea de nevastă acestui om; dar el a urât-o,",
    "și iată că îi pune pe seamă fapte de rușine, zicând: „N-am găsit la fiica ta semnele feciorei!” Dar iată semnele feciorei fiicei mele.» Și să întindă învelitoarea înaintea bătrânilor cetății.",
    "Bătrânii acelei cetăți să-l ia pe omul acela și să-l pedepsească;",
    "să-i pună o amendă de o sută de șecheli de argint, pe care să-i dea tatălui fetei, pentru că a scos nume rău unei fecioare din Israel; ea să-i rămână nevastă și el nu va putea s-o alunge în toate zilele vieții lui.",
    "Dar dacă faptul este adevărat și nu s-au găsit semnele feciorei la fată,",
    "atunci să scoată pe fată la ușa casei tatălui ei și oamenii cetății ei s-o ucidă cu pietre până va muri, pentru că a săvârșit o faptă de rușine în Israel, curvând în casa tatălui ei. Astfel să curăți răul din mijlocul tău.",
    "Dacă se va găsi un om culcat cu o femeie măritată, să moară amândoi, și omul care s-a culcat cu femeia, și femeia. Astfel să curăți răul din Israel.",
    "Dacă o fată fecioară este logodită cu un bărbat, și un alt om o găsește în cetate și se culcă cu ea,",
    "să-i scoateți pe amândoi la poarta acelei cetăți și să-i uci deți cu pietre până vor muri: pe fată, pentru că fiind în cetate n-a strigat, și pe om, pentru că a smerit pe nevasta aproapelui său. Astfel să curăți răul din mijlocul tău.",
    "Dar dacă omul va găsi pe fata logodită pe câmp și omul o va prinde cu forța și se va culca cu ea, să moară numai omul care s-a culcat cu ea;",
    "iar fetei să nu-i faci nimic. Fata n-a săvârșit niciun păcat vrednic de moarte; căci este ca și cum un om s-ar ridica împotriva aproapelui său și l-ar omorî;",
    "căci el a găsit-o pe câmp, iar fata logodită a strigat, dar n-a fost nimeni s-o scape.",
    "Dacă un om va găsi o fată fecioară care nu este logodită, o va apuca și se va culca cu ea, și se vor descoperi,",
    "omul care s-a culcat cu ea să dea tatălui fetei cincizeci de șecheli de argint; ea să-i fie nevastă, pentru că a smerit-o, și nu va putea s-o alunge în toate zilele vieții lui.",
    "Un om să nu ia pe nevasta tatălui său și să nu dea la o parte învelitoarea tatălui său.”",
  ],
}
