export const DEUTERONOM_TEXT_16: Record<number, readonly string[]> = {
  16: [
    "„Păzește luna Aviv și prăznuiește Paștele în cinstea DOMNULUI, Dumnezeului tău; căci în luna Aviv te-a scos DOMNUL, Dumnezeul tău, noaptea din Egipt.",
    "Jertfește Paștele DOMNULUI, Dumnezeului tău, din oile și boii tăi, în locul pe care-l va alege DOMNUL ca să-Și pună Numele acolo.",
    "Să nu mănci pâine dospită cu el, ci șapte zile să mănci turte nedospite, pâinea întristării, căci cu grabă ai ieșit din țara Egiptului; ca să-ți aduci aminte de ziua în care ai ieșit din țara Egiptului în toate zilele vieții tale.",
    "Să nu se vadă aluat la tine în tot hotarul tău timp de șapte zile; și nimic din carnea pe care o vei jertfi în seara zilei întâi să nu rămână peste noapte până dimineața.",
    "Nu vei putea jertfi Paștele în niciuna din porțile pe care ți le dă DOMNUL, Dumnezeul tău;",
    "ci numai în locul pe care-l va alege DOMNUL, Dumnezeul tău, ca să facă să locuiască Numele Lui acolo, acolo să jertfești Paștele seara, la apusul soarelui, în vremea când ai ieșit din Egipt.",
    "Să-l fierbi și să-l mănci în locul pe care-l va alege DOMNUL, Dumnezeul tău; iar dimineața te vei întoarce și te vei duce în corturile tale.",
    "Șase zile să mănci turte nedospite; iar în ziua a șaptea va fi o adunare de sărbătoare pentru DOMNUL, Dumnezeul tău: să nu faci nicio lucrare în ea.",
    "Să numeri șapte săptămâni: de la punerea secerii la grâu să începi să numeri cele șapte săptămâni.",
    "Apoi să prăznuiești Sărbătoarea Săptămânilor în cinstea DOMNULUI, Dumnezeului tău, aducând daruri de bunăvoie din mâna ta, după binecuvântarea pe care ți-o va da DOMNUL, Dumnezeul tău.",
    "Să te bucuri înaintea DOMNULUI, Dumnezeului tău, tu, fiul tău, fiica ta, robul tău, roaba ta, levitul care va fi în porțile tale, străinul, orfanul și văduva care vor fi în mijlocul tău, în locul pe care-l va alege DOMNUL, Dumnezeul tău, ca să facă să locuiască Numele Lui acolo.",
    "Adu-ți aminte că ai fost rob în Egipt și păzește și împlinește aceste legi.",
    "Să prăznuiești Sărbătoarea Corturilor șapte zile, după ce îti vei fi strâns roadele din arie și din teasc.",
    "Să te bucuri la sărbătoarea aceasta, tu, fiul tău, fiica ta, robul tău, roaba ta, levitul, străinul, orfanul și văduva care vor fi în porțile tale.",
    "Șapte zile să prăznuiești sărbătoarea în cinstea DOMNULUI, Dumnezeului tău, în locul pe care-l va alege DOMNUL; căci DOMNUL, Dumnezeul tău, te va binecuvânta în toate roadele tale și în toată lucrarea mâinilor tale, și vei fi plin de bucurie.",
    "De trei ori pe an toți bărbații tăi să se înfățișeze înaintea DOMNULUI, Dumnezeului tău, în locul pe care-l va alege El: la Sărbătoarea Turtelor Nedospite, la Sărbătoarea Săptămânilor și la Sărbătoarea Corturilor. Nimeni să nu se înfățișeze cu mâinile goale înaintea DOMNULUI;",
    "ci fiecare să aducă darul din mâna sa, după binecuvântarea pe care ți-o va fi dat DOMNUL, Dumnezeul tău.",
    "Să pui judecători și supraveghetori în toate porțile tale pe care ți le dă DOMNUL, Dumnezeul tău, după semințiile tale; și ei să judece poporul cu o judecată dreaptă.",
    "Să nu strâmbi judecata, să nu cauți la fața oamenilor și să nu iei mită, căci mita orbește ochii celor înțelepți și răstălmăcește cuvintele celor drepți.",
    "Să urmărești cu strictete dreptatea, ca să trăiești și să intri în stăpânirea țării pe care ți-o dă DOMNUL, Dumnezeul tău.",
    "Să nu-ți sădești niciun stâlp al Așerei lângă altarul DOMNULUI, Dumnezeului tău, pe care ți-l vei zidi.",
    "Să nu-ți ridici niciun stâlp sacru, lucru pe care-l urăște DOMNUL, Dumnezeul tău.”",
  ],
}
