export const DEUTERONOM_TEXT_12: Record<number, readonly string[]> = {
  12: [
    "„Acestea sunt legile și orânduirile pe care să le păziți și să le împliniți în țara pe care ți-a dat-o DOMNUL, Dumnezeul părinților tăi, s-o stăpânești, în toate zilele cât veți trăi pe pământ.",
    "Să distrugeți cu desăvârșire toate locurile în care neamurile pe care le veți alunga au slujit dumnezeilor lor, pe munți înalți, pe dealuri și sub orice copac verde.",
    "Să le dărâmați altarele, să le sfărâmați stâlpii sacri, să le ardeți așerele în foc, să tăiați chipurile cioplite ale dumnezeilor lor și să le ștergeți numele din locul acela.",
    "Voi să nu vă purtați așa cu DOMNUL, Dumnezeul vostru,",
    "ci să căutați locul pe care-l va alege DOMNUL, Dumnezeul vostru, din toate semințiile voastre, ca să-Și pună Numele acolo și să-Și facă locuința, și acolo să te duci.",
    "Acolo să aduceți arderile voastre de tot, jertfele voastre, zeciuielile voastre, prinoasele mâinilor voastre, jertfele voastre de făgăduință, darurile voastre de bunăvoie și primii născuți din cirezile și din turmele voastre.",
    "Acolo să mâncați înaintea DOMNULUI, Dumnezeul vostru, și să vă bucurați, voi și casele voastre, de toate lucrările mâinilor voastre cu care te va fi binecuvântat DOMNUL, Dumnezeul tău.",
    "Să nu vă purtați cum ne purtăm noi astăzi aici, unde fiecare face ce i se pare drept în ochii lui;",
    "căci până acum n-ați ajuns în locul de odihnă și în moștenirea pe care ți-o dă DOMNUL, Dumnezeul tău.",
    "Veți trece Iordanul și veți locui în țara pe care v-o dă ca moștenire DOMNUL, Dumnezeul vostru; El vă va da odihnă de toți vrăjmașii voștri din jur și veți locui în siguranță.",
    "Atunci în locul pe care-l va alege DOMNUL, Dumnezeul vostru, ca să facă să locuiască Numele Lui acolo, să aduceți tot ce vă poruncesc eu: arderile voastre de tot, jertfele voastre, zeciuielile voastre, prinoasele mâinilor voastre și toate alegerile de făgăduințe pe care le veți fi jurat DOMNULUI.",
    "Și să vă bucurați înaintea DOMNULUI, Dumnezeul vostru, voi, fiii voștri, fiicele voastre, robii voștri, roabele voastre și levitul care este în porțile voastre, fiindcă el n-are parte nici de moștenire cu voi.",
    "Vezi să nu aduci arderile tale de tot în orice loc pe care-l vei vedea,",
    "ci numai în locul pe care-l va alege DOMNUL într-una din semințiile tale; acolo să-ți aduci arderile-de-tot și acolo să faci tot ce-ți poruncesc eu.",
    "Totuși, ori de câte ori va dori sufletul tău, vei putea tăia vite și mânca carne în toate porțile tale, după binecuvântarea pe care ți-o va da DOMNUL, Dumnezeul tău; cel necurat și cel curat vor putea mânca din ea, ca din gazelă și din cerb.",
    "Numai sângele să nu-l mâncați, ci să-l vărsați pe pământ ca apa.",
    "Nu vei putea mânca în porțile tale zeciuiala din grâul tău, din mustul tău, din uleiul tău, nici primii născuți din cirezile sau din turmele tale, nici vreo făgăduință de-a ta pe care o vei fi jurat, nici darurile tale de bunăvoie, nici prinoasele mâinilor tale;",
    "ci le vei mânca înaintea DOMNULUI, Dumnezeul tău, în locul pe care-l va alege DOMNUL, Dumnezeul tău, tu, fiul tău, fiica ta, robul tău, roaba ta și levitul care este în porțile tale; și te vei bucura înaintea DOMNULUI, Dumnezeul tău, de tot ce vei face cu mâinile tale.",
    "Veghează asupra ta ca nu cumva să-l părăsești pe levit în toate zilele tale în țara ta.",
    "Când DOMNUL, Dumnezeul tău, îiți va lărgi hotarele, așa cum ți-a promis, și vei zice: «Vreau să mănc carne!», pentru că sufletul tău dorește să mănce carne, vei putea mânca carne după toată dorința sufletului tău.",
    "Dacă locul pe care-l va alege DOMNUL, Dumnezeul tău, ca să-Și pună Numele acolo va fi prea departe de tine, vei putea tăia din cirezile și din turmele tale pe care ți le-a dat DOMNUL, așa cum ți-am poruncit, și vei putea mânca în porțile tale după toată dorința sufletului tău.",
    "Să mănci din ea așa cum se mâncă din gazelă și din cerb: cel necurat și cel curat vor putea mânca deopotrivă.",
    "Numai fii hotărât să nu mănci sângele, căci sângele este viața; să nu mănci viața împreună cu carnea.",
    "Să nu-l mănci, ci să-l verși pe pământ ca apa.",
    "Să nu-l mănci, ca să-ți fie bine ție și fiilor tăi după tine, când vei face ce este drept în ochii DOMNULUI.",
    "Dar lucrurile tale sfinte pe care le vei avea și făgăduințele tale să le iei și să te duci la locul pe care-l va alege DOMNUL.",
    "Vei aduce arderile tale de tot, carnea și sângele, pe altarul DOMNULUI, Dumnezeul tău; sângele celorlalte jertfe ale tale să fie turnat pe altarul DOMNULUI, Dumnezeul tău, iar carnea o vei mânca.",
    "Păzește și ascultă toate aceste cuvinte pe care ți le poruncesc eu, ca să-ți fie bine ție și fiilor tăi după tine pentru totdeauna, când vei face ce este bine și drept în ochii DOMNULUI, Dumnezeul tău.",
    "Când DOMNUL, Dumnezeul tău, va fi nimicit dinaintea ta neamurile spre care mergi ca să le iei în stăpânire, și când le vei fi luat în stăpânire și vei locui în țara lor,",
    "veghează asupra ta ca nu cumva să fii prins în cursă călcând pe urmele lor, după ce vor fi fost nimicite dinaintea ta, și să nu cercetezi despre dumnezeii lor, zicând: «Cum slujeau neamurile acestea dumnezeilor lor? Vreau să fac și eu la fel!»",
    "Să nu te porți astfel cu DOMNUL, Dumnezeul tău, căci ele făceau dumnezeilor lor toate urâciunile pe care le urăște DOMNUL, arzându-și chiar și fiii și fiicele în foc pentru dumnezeii lor.",
    "Toate lucrurile pe care vi le poruncesc eu să le păziți și să le împliniți: să nu adăugați nimic la ele și să nu scădeți nimic din ele.”",
  ],
}
