export const DEUTERONOM_TEXT_29: Record<number, readonly string[]> = {
  29: [
    "Acestea sunt cuvintele legământului pe care a poruncit DOMNUL lui Moise să-l încheie cu fiii lui Israel în țara Moabului, afară de legământul pe care-l încheiase cu ei la Horeb.",
    "Moise a chemat pe tot Israelul și le-a zis: „Ați văzut tot ce a făcut DOMNUL sub ochii voștri, în țara Egiptului, lui Faraon, tuturor slujitorilor lui și întregii lui țări,",
    "încercările cele mari pe care le-au văzut ochii tăi, semnele și minunile acelea mari.",
    "Dar DOMNUL nu v-a dat o inimă ca să pricepeți, nici ochi ca să vedeți, nici urechi ca să auziți, până în ziua de astăzi.",
    "«Eu v-am călăuzit patruzeci de ani în pustie; hainele nu vi s-au învechit pe voi și încălțămintea nu ți s-a învechit în picior.",
    "Pâine n-ați mâncat și vin sau băutură tare n-ați băut, ca să cunoașteți că Eu sunt DOMNUL, Dumnezeul vostru.»",
    "Ați ajuns în locul acesta; Sihon, împăratul Hesbonului, și Og, împăratul Basanului, au ieșit în întâmpinarea noastră ca să se lupte cu noi, și i-am înfrânt.",
    "Am luat țara lor și am dat-o în moștenire rubeniților, gadiților și la jumătate din seminția lui Manase.",
    "Păziți dar cuvintele acestui legământ și îpliniți-le, ca să izbândiți în tot ce veți face.",
    "Voi toți vă înfățișați astăzi înaintea DOMNULUI, Dumnezeului vostru: căpeteniile semințiilor voastre, bătrânii voștri, supraveghetorii voștri, toți bărbații lui Israel,",
    "pruncii voștri, nevestele voastre și străinul care este în mijlocul taberei tale, de la tăietorul tău de lemne până la scoțătorul tău de apă,",
    "ca să intri în legământul DOMNULUI, Dumnezeului tău, și în jurământul pe care DOMNUL, Dumnezeul tău, îl încheie cu tine astăzi,",
    "ca să te confirme astăzi ca popor al Lui și El să-ți fie Dumnezeu, așa cum ți-a spus și cum a jurat părinților tăi, lui Avraam, lui Isaac și lui Iacov.",
    "Și nu numai cu voi închei eu legământul acesta și jurământul acesta,",
    "ci atât cu cel ce este astăzi aici cu noi înaintea DOMNULUI, Dumnezeului nostru, cât și cu cel ce nu este astăzi aici cu noi.",
    "Căci știți cum am locuit în țara Egiptului și cum am trecut prin mijlocul neamurilor pe care le-ați străbătut.",
    "Ați văzut urâciunile lor și idolii lor de lemn, de piatră, de argint și de aur, care erau la ele.",
    "Să nu fie printre voi nici bărbat, nici femeie, nici familie, nici seminție a cărei inimă să se abată astăzi de la DOMNUL, Dumnezeul nostru, ca să meargă să slujeăscă dumnezeilor acestor neamuri; să nu fie printre voi nicio rădăcină care să rodească otravă și pelin.",
    "Dacă cineva, auzind cuvintele acestui jurământ, se va binecuvânta în inima lui, zicând: «Voi avea pace chiar dacă voi umbla în încăpățânarea inimii mele, pierzând astfel cel udat împreună cu cel însetat!»,",
    "DOMNUL nu va voi să-l ierte. Ci mânia DOMNULUI și gelozia Lui se vor aprinde împotriva omului aceluia, toate blestemele scrise în cartea aceasta vor apăsa peste el și DOMNUL îi va șterge numele de sub cer.",
    "DOMNUL îl va separa spre nenorocire din toate semințiile lui Israel, după toate blestemele legământului scris în această carte a Legii.",
    "Generația viitoare, fiii voștri care se vor ridica după voi și străinul care va veni dintr-o țară depașrtată, văzând urgiile acestei țări și bolile cu care va fi lovit-o DOMNUL,",
    "toată țara arsă cu pucioasă și sare, fără să fie semănată, fără să dea rod și fără să crească vreun fir de iarbă în ea, ca la dărâmarea Sodomei, Gomorei, Admei și Ȝeboimului, pe care le-a dărâmat DOMNUL în mânia Lui și în urgia Lui,",
    "toate popoarele vor zice: «Pentru ce a făcut DOMNUL astfel acestei țări? Ce înseamnă mânia aceasta atât de mare?»",
    "Și se va răspunde: «Pentru că au părăsit legământul DOMNULUI, Dumnezeului părinților lor, pe care l-a încheiat cu ei când i-a scos din țara Egiptului;",
    "pentru că s-au dus să slujeăscă altor dumnezei și să se închine înaintea lor, dumnezei pe care nu-i cunoșteau și pe care nu li-i dăduse El.",
    "De aceea S-a aprins mânia DOMNULUI împotriva acestei țări și a adus peste ea toate blestemele scrise în cartea aceasta.",
    "DOMNUL i-a smuls din țara lor în mânie, în urgie și într-o mare supărare, și i-a aruncat într-o altă țară, cum se vede astăzi.»",
    "Lucrurile ascunse sunt ale DOMNULUI, Dumnezeului nostru, iar lucrurile descoperite sunt ale noastre și ale fiilor noștri pentru totdeauna, ca să îplinim toate cuvintele acestei Legi.”",
  ],
}
