export const DEUTERONOM_TEXT_14: Record<number, readonly string[]> = {
  14: [
    "„Voi sunteți fiii DOMNULUI, Dumnezeului vostru. Să nu vă faceți tăieturi în carne și să nu vă radeți părul între ochi pentru un mort;",
    "căci tu ești un popor sfânt pentru DOMNUL, Dumnezeul tău, și DOMNUL te-a ales ca să-I fiți un popor deosebit dintre toate popoarele de pe fața pământului.",
    "Să nu mănci nicio urâciune.",
    "Iată animalele pe care le veți putea mânca: boul, oaia, capra,",
    "cerbul, gazela, căprioara, țapul sălbatic, capra neagră, bivolul și zăganul.",
    "Să mâncați orice animal care are copita despicată, adică despărțită în două gheare, și care rumegă printre animale.",
    "Dar să nu mâncați dintre cele ce rumegă numai sau au numai copita despicată: cămila, iepurele și iepurele de stâncă, care rumegă, dar n-au copita despicată; acestea să vă fie necurate;",
    "de asemenea porcul, care are copita despicată, dar nu rumegă: acesta să vă fie necurat. Să nu măncați din carnea lor și să nu vă atingeți de stărvurile lor.",
    "Iată ce veți mânca din tot ce este în ape: să măncați din tot ce are înotătoare și solzi;",
    "dar să nu măncați din tot ce n-are înotătoare și solzi: acestea să vă fie necurate.",
    "Să măncați din orice pasăre curată.",
    "Dar iată păsările din care să nu măncați: vulturul, zăganul, uliul de mare,",
    "șoimul, gaia și tot ce ține de neamul ei,",
    "orice corb și tot ce ține de neamul lui,",
    "struțul, bufnița, pescărușul, uliul și tot ce ține de neamul lui,",
    "cucuveaua, buha, lebăda,",
    "pelicanul, stârcul, corbul de mare,",
    "barza, bâtlanul și tot ce ține de neamul lui, pupăza și liliacul.",
    "Orice insectă înaripată să vă fie necurată; să nu se mânce.",
    "Din orice pasăre curată veți putea mânca.",
    "Să nu măncați din nicio vită moartă de la sine; o vei putea da străinului care este în porțile tale ca s-o mânce, sau o vei putea vinde unui străin; căci tu ești un popor sfânt pentru DOMNUL, Dumnezeul tău. Să nu fierbi un ied în laptele mamei lui.",
    "Să iei zeciuială din tot rodul seminței tale, din ce va da câmpul tău în fiecare an.",
    "Și să mănci înaintea DOMNULUI, Dumnezeului tău, în locul pe care-l va alege ca să-Și pună Numele acolo, zeciuiala din grâul tău, din mustul tău, din uleiul tău și primii născuți din cirezile și din turmele tale, ca să înveți să te temi de DOMNUL, Dumnezeul tău, întotdeauna.",
    "Dacă drumul va fi prea lung pentru tine și nu vei putea duce zeciuiala, fiindcă locul pe care-l va alege DOMNUL, Dumnezeul tău, ca să-Și pună Numele acolo va fi prea departe de tine, când te va binecuvânta DOMNUL, Dumnezeul tău,",
    "atunci prețuiește-o în argint, leagă argintul în mâna ta și du-te la locul pe care-l va alege DOMNUL, Dumnezeul tău.",
    "Acolo să dai argintul pe tot ce va dori sufletul tău: pe boi, pe oi, pe vin, pe băuturi tari și pe tot ce va dori sufletul tău; să mănci acolo înaintea DOMNULUI, Dumnezeului tău, și să te bucuri, tu și casa ta.",
    "Să nu-l părăsești pe levitul care este în porțile tale, căci el n-are parte nici de moștenire cu tine.",
    "La sfârșitul fiecărui al treilea an, să scoți toată zeciuiala din rodul tău din anul acela și s-o pui în porțile tale.",
    "Atunci va veni levitul, care n-are parte nici de moștenire cu tine, străinul, orfanul și văduva, care sunt în porțile tale, vor mânca și se vor sătura, pentru ca DOMNUL, Dumnezeul tău, să te binecuvânteze în toată lucrarea pe care o vei face cu mâinile tale.”",
  ],
}
