export const DEUTERONOM_TEXT_15: Record<number, readonly string[]> = {
  15: [
    "„La sfârșitul fiecărui al șaptelea an să faci iertare.",
    "Și iată cum se va face iertarea: orice creditor care a împrumutat pe aproapele său să-i ierte împrumutul; să nu mai stoarcă pe aproapele său și pe fratele său, după ce s-a proclamat iertarea DOMNULUI.",
    "Pe străin îl vei putea stoarce; dar ce vei avea la fratele tău, mâna ta să-i ierte.",
    "Totuși la tine să nu fie niciun sărac, căci DOMNUL te va binecuvânta bogat în țara pe care ți-o dă DOMNUL, Dumnezeul tău, ca moștenire s-o stăpânești,",
    "numai dacă vei asculta de glasul DOMNULUI, Dumnezeul tău, păzind și împlinind toate aceste porunci pe care ți le dau astăzi.",
    "DOMNUL, Dumnezeul tău, te va binecuvânta așa cum ți-a promis: vei da cu împrumut multor neamuri, dar tu nu vei lua cu împrumut; vei stăpâni peste multe neamuri, dar ele nu vor stăpâni peste tine.",
    "Dacă va fi la tine vreun sărac dintre frații tăi, într-una din cetățile tale, în țara pe care ți-o dă DOMNUL, Dumnezeul tău, să nu-ți împietrești inima și să nu-ți închizi mâna dinaintea fratelui tău cel sărac;",
    "ci să-i deschizi mâna și să-i dai cu împrumut ce-i lipsește, potrivit cu nevoile lui.",
    "Veghează asupra ta ca nu cumva să ai în inima ta un gând rău și să zici: «Se apropie anul al șaptelea, anul iertării!», și ochiul tău să fie fără îndurare față de fratele tău cel sărac, ca să nu-i dai nimic; căci el ar striga împotriva ta către DOMNUL și ai fi încărcat cu un păcat.",
    "Dă-i bucuros și să nu-ți pară rău în inimă când îi dai; căci pentru aceasta te va binecuvânta DOMNUL, Dumnezeul tău, în toate lucrările tale și în tot ce vei pune mâna.",
    "Căci săracii nu vor lipsi niciodată din țară; de aceea îti dau această poruncă: «Deschide-ți mâna fratelui tău, celui nenorocit și celui sărac din țara ta!»",
    "Dacă fratele tău evreu, bărbat sau femeie, ți se va vinde ție, îti va sluji șase ani; dar în anul al șaptelea să-i dai drumul liber de la tine.",
    "Și când îi vei da drumul liber de la tine, să nu-i dai drumul cu mâinile goale;",
    "ci să-i dai din belșug din turma ta, din aria ta și din teascul tău, dându-i din ce te va fi binecuvântat DOMNUL, Dumnezeul tău.",
    "Adu-ți aminte că ai fost rob în țara Egiptului și că DOMNUL, Dumnezeul tău, te-a răscumpărat; de aceea îti dau astăzi această poruncă.",
    "Dacă însă el îiți va zice: «Nu vreau să plec de la tine!», pentru că te iubește pe tine și casa ta, și pentru că îi este bine la tine,",
    "atunci să iei o sulă și să-i străpungi urechea de ușă, și îiți va fi rob pentru totdeauna. La fel să faci și cu roaba ta.",
    "Să nu-ți pară greu când îi vei da drumul liber de la tine, căci ți-a slujit șase ani îndoit cât un argat plătit; și DOMNUL, Dumnezeul tău, te va binecuvânta în tot ce vei face.",
    "Toți primii născuți de parte bărbătească ce se vor naște din cirezile și din turmele tale să-i închini DOMNULUI, Dumnezeului tău. Să nu lucrezi cu primul născut al vacii tale și să nu nyșil ești primul născut al oaiei tale.",
    "Ci să-l mănci în fiecare an tu și casa ta înaintea DOMNULUI, Dumnezeului tău, în locul pe care-l va alege DOMNUL.",
    "Dacă însă are vreun cusur, dacă este șchiop sau orb, sau are vreun alt cusur urât, să nu-l jertfești DOMNULUI, Dumnezeului tău.",
    "Îll vei mânca în porțile tale: cel necurat și cel curat vor mânca deopotrivă din el, ca din gazelă și din cerb.",
    "Numai sângele să nu-i mânci, ci să-l verși pe pământ ca apa.”",
  ],
}
