export const DEUTERONOM_TEXT_32: Record<number, readonly string[]> = {
  32: [
    "„Ascultați, ceruri, și voi vorbi! Auzi, pământule, cuvintele gurii mele!",
    "Să picure învățătura mea ca ploaia, să curgă cuvântul meu ca roua, ca ploaia măruntă pe verdeață și ca picăturile de ploaie pe iarbă!",
    "Căci voi chema Numele DOMNULUI: dați mărire Dumnezeului nostru!",
    "El este Stânca; lucrările Lui sunt desăvârșite, căci toate căile Lui sunt drepte; un Dumnezeu al credincioșiei, fără nicio nedreptate, El este drept și curat.",
    "Ei s-au stricat față de El; nu sunt fiii Lui, ci defectul lor este al unei generații rele și sucite.",
    "Așa Răsplătiți voi DOMNULUI, popor nebun și fără înțelepciune? Nu este El tatăl tău, Care te-a cumpărat, Care te-a făcut și te-a consolidat?",
    "Adu-ți aminte de zilele străvechi, cugetă la anii generațiilor trecute; întreabă-l pe tatăl tău și-ți va da de știre, pe bătrânii tăi și-ți vor spune!",
    "Când Cel Preainălt a dat neamurilor moștenirea lor, când i-a despărțit pe fiii oamenilor, a stabilit hotarele popoarelor dușa numărul fiilor lui Israel.",
    "Căci partea DOMNULUI este poporul Său, Iacov este partea moștenirii Lui.",
    "El l-a găsit într-o țară pustie, într-un pustiu urlat și gol; l-a înconjurat, l-a îngrijit și l-a păzit ca lumina ochiului Său.",
    "Ca vulturul care îiși scutură cuibul, care pluteste peste puii săi, îiși întinde aripile, îi ia și îi poartă pe penele sale,",
    "așa l-a călăuzit DOMNUL singur, și n-a fost niciun dumnezeu străin cu El.",
    "L-a făcut să meargă pe înălțimile pământului și a mâncat roadele câmpului; l-a hrănit cu miere din stâncă și cu ulei din stânca de cremene,",
    "cu unt de la vaci și lapte de la oi, cu grăsimea mieilor, a berbecilor din Basan și a țapilor, cu cel mai bun grâu, și ai băut vinul spumos, sângele strugurelui.",
    "Dar Ieșurun s-a îngrășat și a zvârlit din picioare; te-ai îngrășat, te-ai îngroșat, te-ai umplut de grăsime! L-a părăsit pe Dumnezeu, Ziditorul său, și a disprețuit Stânca mântuirii sale.",
    "L-au stârnit la gelozie prin dumnezei străini, L-au mâniat prin urâciuni.",
    "Au adus jertfe demonilor, nu lui Dumnezeu, unor dumnezei pe care nu-i cunoșteau, dumnezei noi, veniți de curând, de care nu se temuseră părinții voștri.",
    "Ai părăsit Stânca ce te-a născut și l-ai uitat pe Dumnezeul Care te-a adus pe lume.",
    "DOMNUL a văzut și S-a scârbit, mâniat pe fiii și fiicele Sale.",
    "El a zis: «Imî voi ascunde fața de ei și voi vedea care le va fi sfârșitul; căci sunt o generație sucită, fii în care nu este credincioșie.",
    "M-au stârnit la gelozie prin ce nu este Dumnezeu, M-au mâniat prin idolii lor deșerți; și Eu îi voi stârni la gelozie prin ce nu este popor, îi voi mânia printr-un neam fără pricepere.",
    "Căci un foc S-a aprins în mânia Mea și va arde până în adâncul locuinței morților; va mistui pământul și rodul lui și va aprinde temeliile munților.",
    "Voi îngrămădi nenorociri peste ei, Îmi voi epuiza săgețile împotriva lor.",
    "Vor fi sleiți de foame, mistuiți de febră și de o molimă amară; voi trimite împotriva lor colții fiarelor și veninul șerpilor ce se târăsc în țărână.",
    "Afară sabia îi va lipsi de copii, iar înăuntru groaza: pe tânăr ca și pe fecioară, pe pruncul de la sân ca și pe moșneag.",
    "Spusesem că îi voi împrăștia și le voi șterge pomenirea dintre oameni,",
    "dar M-am temut de ocara vrăjmașului, ca nu cumva potrivnicii lor să se amăgească și să zică: „Mâna noastră cea înaltă a făcut toate acestea, și nu DOMNUL!”»",
    "Căci ei sunt un neam chibzuit fără judecată și nu este pricepere în ei.",
    "Dacă ar fi fost înțelepți, ar fi priceput lucrul acesta și s-ar fi gândit la sfârșitul lor!",
    "Cum ar putea urmări unul singur o mie, și cum ar pune doi pe fugă zece mii, dacă nu i-ar fi vândut Stânca lor și dacă nu i-ar fi predat DOMNUL?",
    "Căci stânca lor nu este ca Stânca noastră, vrăjmașii noștri însăși fiind judecători.",
    "Căci vița lor este din vița Sodomei și din câmpia Gomorei; strugurii lor sunt struguri otrăvitori, ciorchinii lor sunt amari.",
    "Vinul lor este venin de balauri, otravă cumplită de cobră.",
    "«Nu este oare ascuns lucrul acesta la Mine, sigilat în comorile Mele?",
    "A Mea este răzbunarea și răsplătirea, când le va aluneca piciorul! Căci ziua nenorocirii lor este aproape și lucrurile pregătite pentru ei se grăbesc!»",
    "Căci DOMNUL va judeca pe poporul Său și va avea milă de slujitorii Săi, când va vedea că puterea le este dusă și că nu mai este nici rob, nici slobod.",
    "El va zice: «Unde sunt dumnezeii lor, stânca în care îiși căutau adăpostul,",
    "dumnezeii care mâncau grăsimea jertfelor lor și beau vinul turnărilor lor? Să se ridice să vă ajute și să vă fie adăpost!",
    "Vedeți acum că Eu, Eu sunt El, și nu este alt Dumnezeu afară de Mine! Eu dau moartea și Eu dau viața, Eu rănesc și Eu tămăduiesc, și nimeni nu poate scăpa din mâna Mea!",
    "Căci Îmi ridic mâna spre cer și zic: „Asa cum trăiesc Eu în veci,”",
    "dacă Îmi voi ascuți sabia Mea fulgerătoare și mâna Mea va apuca judecata, Mă voi răzbuna pe potrivnicii Mei și voi răsplăti celor ce Mă urăsc!",
    "Îmi voi îmbăta săgețile de sânge — și sabia Mea va mânca carne — din sângele celor uciși și prinși, din capul căpeteniilor vrăjmașului!»",
    "Bucurați-vă, neamuri, cu poporul Lui, căci El răzbună sângele slujitorilor Săi, Se răzbună pe potrivnicii Săi și curăță țara Sa și poporul Său.”",
    "Moise a venit și a rostit toate cuvintele acestei cântări în urechile poporului, el și Iosua, fiul lui Nun.",
    "După ce a isprăvit Moise de rostit toate aceste cuvinte întregului Israel,",
    "le-a zis: „Puneți-vă în inimă toate cuvintele pe care vi le mărturisesc astăzi, ca să le porunciți fiilor voștri să vegheze să îplinească toate cuvintele acestei Legi.",
    "Căci nu este un cuvânt deșert pentru voi, ci este însăși viața voastră, și prin cuvântul acesta vă veți lungi zilele în țara peste care treceți Iordanul s-o luați în stăpânire.”",
    "În aceeași zi DOMNUL i-a vorbit lui Moise, zicând:",
    "„Suie-te pe muntele acesta Abarim, pe muntele Nebo, care este în țara Moabului, în fața Ierihonului, și privește țara Canaanului pe care o dau în stăpânire fiilor lui Israel.",
    "Tu vei muri pe muntele pe care te vei sui și vei fi adunat la poporul tău, așa cum a murit fratele tău Aaron pe muntele Hor și a fost adunat la poporul lui;",
    "pentru că ați păcătuit împotriva Mea în mijlocul fiilor lui Israel, la apele Meriba-Cadeș, în pustia Ȝin, și pentru că nu M-ați sfințit în mijlocul fiilor lui Israel.",
    "Vei vedea țara din fața ta, dar nu vei intra în țara pe care o dau fiilor lui Israel.”",
  ],
}
