export const DEUTERONOM_TEXT_24: Record<number, readonly string[]> = {
  24: [
    "„Când un om îiși va lua o nevastă și se va căsători cu ea, dacă ea nu va mai găsi trecere în ochii lui pentru că a descoperit la ea ceva neplăcut, să-i scrie o carte de despărțire, să i-o pună în mână și să-i dea drumul din casa lui.",
    "Ea să iasă din casa lui, să plece și să se mărite cu un alt bărbat.",
    "Dacă și acest al doilea bărbat o va urî, îi va scrie o carte de despărțire, i-o va pune în mână și-i va da drumul din casa lui, sau dacă acest al doilea bărbat care a luat-o de nevastă va muri,",
    "fostul ei bărbat, care îi dăduse drumul, nu va putea s-o ia din nou de nevastă după ce a fost spurcată, căci este o urâciune înaintea DOMNULUI, și să nu încarci cu păcat țara pe care ți-o dă DOMNUL, Dumnezeul tău, ca moștenire.",
    "Când un om va fi proaspăt căsătorit, să nu meargă la oaste și să nu i se pună nicio sarcină; să fie slobod în casa lui un an întreg și să înveselească pe nevasta pe care a luat-o.",
    "Să nu se ia ca zălog moara sau piatra de moară de sus, căci s-ar lua ca zălog însăși viața omului.",
    "Dacă se va găsi un om care a furat pe vreunul din frații lui, dintre fiii lui Israel, și l-a folosit ca rob sau l-a vândut, hoțul acela să moară. Astfel să curăți răul din mijlocul tău.",
    "Veghează în boala leprei, ca să păzești cu grijă și să faci potrivit cu tot ce vă vor învăța preoții leviți; cum le-am poruncit eu, așa să vegheatți să faceți.",
    "Adu-ți aminte ce i-a făcut DOMNUL, Dumnezeul tău, Mariei pe drum, la ieșirea voastră din Egipt.",
    "Când vei da împrumut aproapelui tău ceva, să nu intri în casa lui ca să-i iei zălogul;",
    "să stai afară, iar omul căruia îi dai împrumutul să-ți scoată zălogul afară.",
    "Și dacă omul acela este sărac, să nu te culci având zălogul lui la tine;",
    "să-i dai înapoi zălogul la apusul soarelui, ca să se culce în haina lui și să te binecuvânteze; și aceasta îiți va fi socotită ca neprihănire înaintea DOMNULUI, Dumnezeului tău.",
    "Să nu asuprești pe argatul sărac și lipsit, fie că este unul din frații tăi, fie că este unul din străinii care locuiesc în țara ta, în porțile tale.",
    "Să-i dai plata în aceeași zi, înainte de apusul soarelui; căci este sărac și îiși pune nădejdea în ea; ca nu cumva să strige împotriva ta către DOMNUL și să fii încărcat cu un păcat.",
    "Părinții să nu fie puși la moarte pentru copii și copiii să nu fie puși la moarte pentru părinți; fiecare să fie pus la moarte pentru păcatul lui.",
    "Să nu strâmbi judecata străinului, nici a orfanului, și să nu iei ca zălog haina văduvei.",
    "Adu-ți aminte că ai fost rob în Egipt și că DOMNUL, Dumnezeul tău, te-a răscumpărat de acolo; de aceea îiți dau poruncă să faci așa.",
    "Când îiți vei secera ogorul și vei uita un snop pe ogor, să nu te întorci să-l iei: să fie al străinului, al orfanului și al văduvei, pentru ca DOMNUL, Dumnezeul tău, să te binecuvânteze în toată lucrarea mâinilor tale.",
    "Când vei scutura măslinii tăi, să nu cauți din nou roadele rămase pe ramuri: să fie ale străinului, ale orfanului și ale văduvei.",
    "Când vei culege via ta, să nu strângi ciorchinele rămase după tine: să fie ale străinului, ale orfanului și ale văduvei.",
    "Adu-ți aminte că ai fost rob în țara Egiptului; de aceea îiți dau poruncă să faci așa.”",
  ],
}
