export const DEUTERONOM_TEXT_1: Record<number, readonly string[]> = {
  1: [
    "Acestea sunt cuvintele pe care le-a rostit Moise întregului Israel dincolo de Iordan, în pustie, în câmpia Arabah, în fața Suf-ului, între Paran, Tofel, Laban, Haserot și Dizahab.",
    "Sunt unsprezece zile de la Horeb, pe drumul muntelui Seir, până la Cadeș-Barnea.",
    "În anul al patruzecilea, în luna a unsprezecea, în prima zi a lunii, Moise le-a vorbit fiilor lui Israel potrivit cu tot ce-i poruncise DOMNUL pentru ei,",
    "după ce l-a înfrânt pe Sihon, împăratul amoriților, care locuia la Hesbon, și pe Og, împăratul Basanului, care locuia la Aștarot, în Edrei.",
    "Dincolo de Iordan, în țara Moabului, Moise a început să explice această Lege, spunând:",
    "„DOMNUL, Dumnezeul nostru, ne-a vorbit la Horeb, zicând: «Ați locuit destulă vreme la muntele acesta.",
    "Întoarceți-vă, porniți la drum și mergeți în regiunea muntoasă a amoriților și la toți vecinii lor din Arabah, din munți, din șes, din Negeb și de pe țărmul mării, în țara canaaniților și în Liban, până la râul cel mare, râul Eufrat.",
    "Iată, v-am pus țara înainte; intrați și luați în stăpânire țara pe care DOMNUL a jurat părinților voștri, lui Avraam, lui Isaac și lui Iacov, că le-o va da lor și urmașilor lor după ei.»”",
    "În vremea aceea v-am spus: „Eu nu vă pot purta singur.",
    "DOMNUL, Dumnezeul vostru, v-a înmulțit și iată că astăzi sunteți numeroși ca stelele cerului.",
    "DOMNUL, Dumnezeul părinților voștri, să vă înmulțească de o mie de ori pe atât și să vă binecuvânteze, așa cum v-a promis!",
    "Cum aș putea purta eu singur povara voastră, greutatea voastră și neînțelegerile voastre?",
    "Alegeți din semințiile voastre oameni înțelepți, pricepuți și cunoscuți, iar eu îi voi pune căpetenii peste voi.”",
    "Voi mi-ați răspuns și ați zis: „Lucrul pe care ai spus să-l facem este bun.”",
    "Am luat deci căpeteniile semințiilor voastre, oameni înțelepți și cunoscuți, și i-am pus căpetenii peste voi: căpetenii peste mii, căpetenii peste sute, căpetenii peste cincizeci, căpetenii peste zeci și supraveghetori pentru semințiile voastre.",
    "În vremea aceea am dat această poruncă judecătorilor voștri: „Ascultați cauzele dintre frații voștri și judecați cu dreptate între un om și fratele său sau străinul care locuiește cu el.",
    "Să nu căutați la fața oamenilor în judecată; să ascultați pe cel mic ca și pe cel mare. Să nu vă temeți de niciun om, căci judecata este a lui Dumnezeu. Iar cauza care va fi prea grea pentru voi să mi-o aduceți mie și o voi asculta.”",
    "Și v-am poruncit în vremea aceea toate lucrurile pe care trebuia să le faceți.",
    "Apoi am plecat de la Horeb și am străbătut toată acea pustie mare și înfricoșătoare pe care ați văzut-o, pe drumul spre muntele amoriților, așa cum ne poruncise DOMNUL, Dumnezeul nostru, și am ajuns la Cadeș-Barnea.",
    "Atunci v-am spus: „Ați ajuns la muntele amoriților, pe care DOMNUL, Dumnezeul nostru, ni-l dă.",
    "Iată că DOMNUL, Dumnezeul tău, îți pune țara înainte; suie-te și ia-o în stăpânire, așa cum ți-a spus DOMNUL, Dumnezeul părinților tăi. Nu te teme și nu te spăimânta!”",
    "Voi toți v-ați apropiat de mine și ați zis: „Să trimitem niște oameni înaintea noastră, care să iscodească țara și să ne aducă vești despre drumul pe care vom sui și despre cetățile în care vom intra.”",
    "Propunerea mi s-a părut bună și am luat doisprezece oameni dintre voi, câte un om din fiecare seminție.",
    "Ei s-au întors, s-au suit în munte, au ajuns până la valea Eșcol și au iscodit țara.",
    "Au luat în mâini din roadele țării, ni le-au adus și ne-au dat raportul, spunând: „Țara pe care ne-o dă DOMNUL, Dumnezeul nostru, este bună.”",
    "Dar voi n-ați vrut să vă suiți, ci v-ați răzvrătit împotriva poruncii DOMNULUI, Dumnezeul vostru.",
    "Ați cârtit în corturile voastre și ați zis: „Pentru că DOMNUL ne urăște, de aceea ne-a scos din țara Egiptului, ca să ne dea în mâinile amoriților și să ne distrugă.",
    "Unde să ne suim? Frații noștri ne-au tăiat inima, zicând: «Poporul este mai mare și mai înalt decât noi; cetățile sunt mari și fortificate până la cer; ba chiar i-am văzut acolo și pe fiii lui Anac!»”",
    "Eu v-am spus: „Nu vă spăimântați și nu vă temeți de ei!",
    "DOMNUL, Dumnezeul vostru, Care merge înaintea voastră, Se va lupta El Însuși pentru voi, potrivit cu tot ce a făcut pentru voi în Egipt, sub ochii voștri,",
    "și în pustie, unde ai văzut cum DOMNUL, Dumnezeul tău, te-a purtat așa cum își poartă un om fiul, pe tot drumul pe care ați mers până la sosirea voastră în locul acesta.”",
    "Și totuși, cu toate acestea, nu ați avut încredere în DOMNUL, Dumnezeul vostru,",
    "Care mergea înaintea voastră pe drum, ca să vă caute un loc de tabără: noaptea în foc, pentru a vă lumina drumul pe care trebuia să mergeți, iar ziua în nor.",
    "DOMNUL a auzit glasul cuvintelor voastre, S-a mâniat și a jurat, zicând:",
    "„Niciunul dintre oamenii acestei generații rele nu va vedea țara cea bună pe care am jurat că o voi da părinților voștri,",
    "cu excepția lui Caleb, fiul lui Iefune. El o va vedea și lui și fiilor lui le voi da pământul pe care a călcat, pentru că a urmat pe deplin pe DOMNUL.”",
    "DOMNUL S-a mâniat și pe mine din cauza voastră și a zis: „Nici tu nu vei intra acolo.",
    "Iosua, fiul lui Nun, care stă înaintea ta, va intra acolo. Întărește-l, căci el va da țara în stăpânire lui Israel.",
    "Iar pruncii voștri, despre care ați zis că vor fi pradă, și fiii voștri, care nu cunosc astăzi nici binele, nici răul, ei vor intra acolo; lor le voi da țara și ei o vor lua în stăpânire.",
    "Dar voi întoarceți-vă și porniți spre pustie, pe drumul spre Marea Roșie.”",
    "Voi ați răspuns și mi-ați zis: „Am păcătuit împotriva DOMNULUI! Ne vom sui și ne vom lupta, așa cum ne-a poruncit DOMNUL, Dumnezeul nostru.” Și v-ați încins fiecare cu armele de război și v-ați arătat grăbiți să vă suiți în munte.",
    "DOMNUL mi-a zis: „Spune-le: «Nu vă suiți și nu vă luptați, căci Eu nu sunt în mijlocul vostru, ca să nu fiți înfrânți înaintea vrăjmașilor voștri.»”",
    "Eu v-am vorbit, dar nu ați ascultat, ci v-ați răzvrătit împotriva poruncii DOMNULUI și, plini de trufie, v-ați suit în munte.",
    "Atunci amoriții, care locuiau în muntele acela, au ieșit în întâmpinarea voastră, v-au urmărit cum fac albinele și v-au bătut din Seir până la Horma.",
    "La întoarcere ați plâns înaintea DOMNULUI, dar DOMNUL nu a ascultat glasul vostru și nu și-a plecat urechea spre voi.",
    "Astfel ați rămas la Cadeș multă vreme, potrivit cu numărul zilelor cât ați locuit acolo.",
  ],
}
