export const DEUTERONOM_TEXT_28: Record<number, readonly string[]> = {
  28: [
    "„Dacă vei asculta cu credincioșie de glasul DOMNULUI, Dumnezeului tău, păzind și îplinind toate poruncile Lui pe care ți le dau astăzi, DOMNUL, Dumnezeul tău, îiți va da întâietate mai presus de toate popoarele pământului.",
    "Iată toate binecuvântările care vor veni peste tine și te vor ajunge, dacă vei asculta de glasul DOMNULUI, Dumnezeului tău:",
    "Vei fi binecuvântat în cetate și vei fi binecuvântat la câmp.",
    "Binecuvântat va fi rodul pântecelui tău, rodul pământului tău, rodul vitelor tale, fătarea vacilor tale și sporul oilor tale.",
    "Binecuvântat va fi coșul tău și covata ta.",
    "Vei fi binecuvântat la intrarea ta și vei fi binecuvântat la ieșirea ta.",
    "DOMNUL ți-i va da înfrânți pe vrăjmașii tăi care se vor ridica împotriva ta; pe un drum vor ieși împotriva ta și pe șapte drumuri vor fugi dinaintea ta.",
    "DOMNUL va face ca binecuvântarea să fie cu tine în grânarele tale și în toată lucrarea mâinilor tale; El te va binecuvânta în țara pe care ți-o dă DOMNUL, Dumnezeul tău.",
    "DOMNUL te va statornici ca popor sfânt pentru Sine, așa cum ți-a jurat, dacă vei păzi poruncile DOMNULUI, Dumnezeului tău, și vei umbla pe căile Lui.",
    "Toate popoarele pământului vor vedea că tu porți Numele DOMNULUI și se vor teme de tine.",
    "DOMNUL te va face să ai belșug de bunătăți, în rodul pântecelui tău, în rodul vitelor tale și în rodul pământului tău, în țara pe care DOMNUL a jurat părinților tăi că ți-o va da.",
    "DOMNUL îiți va deschide comoara Lui cea bună, cerul, ca să dea țării tale ploaie la vreme și ca să binecuvânteze toată lucrarea mâinilor tale; vei da cu împrumut multor neamuri, dar tu nu vei lua cu împrumut.",
    "DOMNUL te va face să fii cap, nu coadă; întotdeauna vei fi sus și niciodată jos, dacă vei asculta de poruncile DOMNULUI, Dumnezeului tău, pe care ți le dau astăzi ca să le păzești și să le îplinesti,",
    "și dacă nu te vei abate de la niciunul din cuvintele pe care vi le poruncesc astăzi, nici la dreapta, nici la stânga, ca să mergi după alți dumnezei și să le slujești.",
    "Dar dacă nu vei asculta de glasul DOMNULUI, Dumnezeului tău, ca să veghezi să îplinesti toate poruncile și legile Lui pe care ți le dau astăzi, iată toate blestemele care vor veni peste tine și te vor ajunge:",
    "Vei fi blestemat în cetate și vei fi blestemat la câmp.",
    "Blestemat va fi coșul tău și covata ta.",
    "Blestemat va fi rodul pântecelui tău, rodul pământului tău, fătarea vacilor tale și sporul oilor tale.",
    "Vei fi blestemat la intrarea ta și vei fi blestemat la ieșirea ta.",
    "DOMNUL va trimite peste tine blestemul, învălmășeala și primejdia în toată lucrarea mâinilor tale pe care o vei face, până vei fi nimicit și vei pieri degrabă din cauza răutății faptelor tale prin care m-ai părăsit.",
    "DOMNUL va lipi de tine molima, până te va nimici din țara în care intri s-o iei în stăpânire.",
    "DOMNUL te va lovi cu ftizie, cu febră, cu aprindere, cu căldură arzătoare, cu secetă, cu rugină în grâu și cu mucegai, care te vor urmări până vei pieri.",
    "Cerul deasupra capului tău va fi de aramă, și pământul sub tine va fi de fier.",
    "DOMNUL va schimba ploaia țării tale în praf și țărână; din cer va coborî peste tine până vei fi nimicit.",
    "DOMNUL ți-l va da înfrânt dinaintea vrăjmașilor tăi; pe un drum vei ieși împotriva lui și pe șapte drumuri vei fugi dinaintea lui, și vei fi o groază pentru toate împărățiile pământului.",
    "Stârvul tău va fi hrana tuturor păsărilor cerului și fiarelor pământului, și nu va fi nimeni să le sperie.",
    "DOMNUL te va lovi cu bubele Egiptului, cu hemoroizi, cu râie și cu pecingine, de care nu te vei putea vindeca.",
    "DOMNUL te va lovi cu nebunie, cu orbire și cu rătăcirea minții;",
    "vei pipăi la amiază cum pipăie orbul în întuneric, și nu vei izbândi pe căile tale; vei fi asuprit și jefuit în toate zilele, și nu va fi nimeni să te scape.",
    "Te vei logodi cu o femeie și altul se va culca cu ea; vei zidi o casă și nu vei locui în ea; vei sădi o vie și nu vei mânca din ea.",
    "Boul tău va fi înjunghiat sub ochii tăi și nu vei mânca din el; măgarul tău va fi răpit dinaintea ta și nu ți se va da înapoi; oile tale vor fi date vrăjmașilor tăi și nu va fi nimeni să ți le scape.",
    "Fiii tăi și fiicele tale vor fi dați altui popor, ochii tăi vor vedea și vor tânji de dorul lor toată ziua, și mâna ta va fi fără putere.",
    "Un popor pe care nu-l cunoști va mânca rodul pământului tău și toată munca ta, și vei fi asuprit și zdrobit în toate zilele.",
    "Vei fi înnebunit de ceea ce vor vedea ochii tăi.",
    "DOMNUL te va lovi la genunchi și pe picioare cu o bubă rea, de care nu te vei putea vindeca, de la talpa piciorului până la creștetul capului.",
    "DOMNUL te va duce pe tine și pe împăratul tău pe care-l vei fi pus peste tine la un neam pe care nu l-ai cunoscut nici tu, nici părinții tăi; și acolo vei sluji altor dumnezei, de lemn și de piatră.",
    "Și vei fi o groază, un proverb și de batjocură printre toate popoarele unde te va duce DOMNUL.",
    "Vei scoate multă sămânță pe câmp și vei strânge puțină, căci o va mânca lăcustele.",
    "Vei sădi vii și le vei lucra, dar nu vei bea vin și nu vei culege struguri, căci îi vor mânca viermii.",
    "Vei avea măslini în tot hotarul tău, dar nu te vei unge cu ulei, căci măslinele tale vor cădea.",
    "Vei naște fii și fiice, dar nu vor fi ai tăi, căci vor merge în robie.",
    "Toți copacii tăi și rodul pământului tău vor fi prada lăcustelor.",
    "Străinul care este în mijlocul tău se va ridica mai presus de tine tot mai sus, iar tu vei coborî tot mai jos.",
    "El îiți va da cu împrumut, dar tu nu-i vei da cu împrumut; el va fi capul, iar tu vei fi coada.",
    "Toate aceste blesteme vor veni peste tine, te vor urmări și te vor ajunge până vei fi nimicit, pentru că n-ai ascultat de glasul DOMNULUI, Dumnezeului tău, ca să păzești poruncile și legile Lui pe care ți le-a dat.",
    "Ele vor fi semne și minuni pentru tine și pentru urmașii ta pentru totdeauna.",
    "Pentru că n-ai slujit DOMNULUI, Dumnezeului tău, cu bucurie și cu inimă bună în mijlocul belșugului tuturor lucrurilor,",
    "vei sluji vrăjmașilor tăi pe care-i va trimite DOMNUL împotriva ta, în foame, în sete, în goliciune și în lipsă de toate; El va pune un jug de fier pe gâtul tău, până te va nimici.",
    "DOMNUL va aduce împotriva ta de departe, de la marginea pământului, un neam care va zbura ca vulturul, un neam a cărui limbă n-o înțelegi,",
    "un neam cu înfățișare cumplită, care nu va avea niciun respect pentru cel bătrân și nicio milă pentru cel tânăr.",
    "El va mânca rodul vitelor tale și rodul pământului tău, până vei fi nimicit; nu-ți va lăsa nici grâu, nici must, nici ulei, nici fătarea vacilor tale, nici sporul oilor tale, până te va pierde.",
    "Te va împresura în toate cetățile tale, până vor cădea în toată țara ta zidurile tale cele înălte și fortificate în care îiți puserăți încrederea; te va împresura în toate cetățile tale, în toată țara pe care ți-o dă DOMNUL, Dumnezeul tău.",
    "Și vei mânca rodul pântecelui tău, carnea fiilor tăi și fiicelor tale pe care ți i-a dat DOMNUL, Dumnezeul tău, în timpul împresurării și strâmtorării cu care te va strâmtora vrăjmașul tău.",
    "Bărbatul cel mai delicat și mai simțitor din mijlocul tău va privi cu ochi rău pe fratele său, pe nevasta care se odihnește la sânul lui și pe restul fiilor pe care-i va mai avea,",
    "ca să nu dea niciunuia din ei din carnea fiilor săi pe care-i va mânca, fiindcă nu-i va mai rămâne nimic în timpul împresurării și strâmtorării cu care te va strâmtora vrăjmașul tău în toate cetățile tale.",
    "Femeia cea mai delicată și mai simțitoare din mijlocul tău, care din delicatețe și simțire nu încercase să pună talpa piciorului pe pământ, va privi cu ochi rău pe bărbatul care se odihnește la sânul ei, pe fiul ei și pe fiica ei,",
    "placenta ieșită dintre picioarele ei și copiii pe care-i va naște; căci îi va mânca în ascuns, de lipsă de toate, în timpul împresurării și strâmtorării cu care te va strâmtora vrăjmașul tău în cetățile tale.",
    "Dacă nu vei veghea să îplinească toate cuvintele acestei Legi, scrise în cartea aceasta, temandu-te de acest Nume slăvit și înfricoșător: DOMNUL, DUMNEZEUL TĂU,",
    "DOMNUL te va lovi pe tine și urmașii ta cu urgii cumplite și neobișnuite, cu boli mari și îndelungate și cu molime rele și stăruitoare.",
    "Va aduce peste tine toate bolile Egiptului, de care te temeai, și ele se vor lipi de tine.",
    "De asemenea DOMNUL va aduce peste tine orice boală și orice urgie care nu sunt scrise în cartea acestei Legi, până vei fi nimicit.",
    "Și după ce ați fost mulți ca stelele cerului, veți rămâne un mic număr, pentru că n-ai ascultat de glasul DOMNULUI, Dumnezeului tău.",
    "Cum Se bucura DOMNUL să vă facă bine și să vă înmulțească, așa Se va bucura DOMNUL să vă piardă și să vă nimicească; și veți fi smulși din țara în care intri s-o iei în stăpânire.",
    "DOMNUL te va împrăștia printre toate popoarele, de la o margine a pământului până la cealaltă; și acolo vei sluji altor dumnezei pe care nu i-ai cunoscut nici tu, nici părinții tăi, de lemn și de piatră.",
    "Printre aceste neamuri nu vei avea odihnă și nu va fi niciun loc de odihnă pentru talpa piciorului tău; DOMNUL îiți va da acolo o inimă tremurândă, ochi care tânjesc și un suflet mâhnit.",
    "Viața ta va sta ca în suspensie înaintea ta; te vei teme noaptea și ziua și nu vei fi sigur de viața ta.",
    "Dimineața vei zice: «O, de ar fi seară!», și seara vei zice: «O, de ar fi dimineață!», din cauza fricii care-ți va umple inima și din cauza celor ce vor vedea ochii tăi.",
    "Și DOMNUL te va duce înapoi pe corăbii în Egipt, pe drumul despre care îiți spusesem: «Să nu-l mai vezi niciodată!» Acolo vă veți oferi de vânzare vrăjmașilor tăi ca robi și roabe, dar nu va fi nimeni să vă cumpere.”",
  ],
}
