export const DEUTERONOM_TEXT_4: Record<number, readonly string[]> = {
  4: [
    "„Acum, Israele, ascultă legile și poruncile pe care vă învăț să le împliniți, ca să trăiți și să intrați să luați în stăpânire țara pe care v-o dă DOMNUL, Dumnezeul părinților voștri.",
    "Să nu adăugați nimic la ce vă poruncesc eu și să nu scădeți nimic din ea, ci să păziți poruncile DOMNULUI, Dumnezeul vostru, pe care vi le dau.",
    "Ochii voștri au văzut ce a făcut DOMNUL din cauza lui Baal-Peor: DOMNUL, Dumnezeul tău, a nimicit din mijlocul tău pe orice om care a urmat pe Baal-Peor.",
    "Dar voi, care v-ați alipit de DOMNUL, Dumnezeul vostru, sunteți toți vii astăzi.",
    "Iată, v-am învățat legi și porunci, așa cum mi-a poruncit DOMNUL, Dumnezeul meu, ca să le împliniți în țara în care intrați s-o luați în stăpânire.",
    "Păziți-le și împliniți-le, căci aceasta va fi înțelepciunea voastră și priceperea voastră înaintea popoarelor care vor auzi de toate aceste legi și vor zice: «Acest neam mare este cu adevărat un popor înțelept și priceput!»",
    "Căci ce neam mare este acela care să aibă pe dumnezeii lui atât de aproape de el, cum este DOMNUL, Dumnezeul nostru, ori de câte ori Îl chemăm?",
    "Și ce neam mare este acela care să aibă legi și porunci atât de drepte cum este toată Legea aceasta pe care v-o pun înainte astăzi?",
    "Numai veghează asupra ta și păzește-ți sufletul cu luare-aminte, ca nu cumva să uiți lucrurile pe care le-au văzut ochii tăi și să nu ți se depărteze din inimă în toate zilele vieții tale; ci fă-le cunoscute fiilor tăi și fiilor fiilor tăi.",
    "Adu-ți aminte de ziua în care ai stat înaintea DOMNULUI, Dumnezeul tău, la Horeb, când DOMNUL mi-a zis: «Adună poporul la Mine și îi voi face să audă cuvintele Mele, ca să învețe să Se teamă de Mine în toate zilele cât vor trăi pe pământ și să-i învețe și pe fiii lor.»",
    "V-ați apropiat și ați stat la poalele muntelui; iar muntele ardea în foc până la cer, în mijlocul întunericului, al norilor și al beznei.",
    "DOMNUL v-a vorbit din mijlocul focului; i-ați auzit glasul cuvintelor, dar n-ați văzut niciun chip, ci numai un glas ați auzit.",
    "El v-a vestit legământul Său, pe care v-a poruncit să-l împliniți, cele Zece Porunci, și le-a scris pe două table de piatră.",
    "În vremea aceea DOMNUL mi-a poruncit să vă învăț legi și orânduiri, ca să le împliniți în țara în care veți trece s-o luați în stăpânire.",
    "Păziți-vă cu grijă sufletele, fiindcă n-ați văzut niciun chip în ziua când DOMNUL v-a vorbit la Horeb din mijlocul focului,",
    "ca nu cumva să vă stricați și să vă faceți vreun chip cioplit, o înfățișare a vreunei idoli, vreo înfățișare de bărbat sau de femeie,",
    "vreo înfățișare a vreunui animal de pe pământ, vreo înfățișare a vreunei păsări înaripate care zboară în cer,",
    "vreo înfățișare a vreunei vietăți care se târăște pe pământ, sau vreo înfățișare a vreunui pește din apele de sub pământ;",
    "și ca nu cumva, ridicându-ți ochii spre cer și văzând soarele, luna și stelele, toată oștirea cerului, să fii ademenit să te închini înaintea lor și să le slujești, lucruri pe care DOMNUL, Dumnezeul tău, le-a împărțit tuturor popoarelor de sub tot cerul.",
    "Dar pe voi DOMNUL v-a luat și v-a scos din cuptorul de fier, din Egipt, ca să-I fiți un popor de moștenire, cum sunteți astăzi.",
    "DOMNUL S-a mâniat pe mine din cauza cuvintelor voastre și a jurat că nu voi trece Iordanul și nu voi intra în țara cea bună pe care DOMNUL, Dumnezeul tău, ți-o dă ca moștenire.",
    "Căci eu voi muri în țara aceasta și nu voi trece Iordanul; dar voi veți trece și veți lua în stăpânire țara aceea bună.",
    "Vegheați asupra voastră, ca nu cumva să uitați legământul DOMNULUI, Dumnezeul vostru, pe care l-a încheiat cu voi, și să vă faceți vreun chip cioplit, vreo înfățișare a vreunui lucru pe care ți l-a interzis DOMNUL, Dumnezeul tău.",
    "Căci DOMNUL, Dumnezeul tău, este un foc mistuitor, un Dumnezeu gelos.",
    "Când vei avea fii și fiii fiilor tăi și veți fi îmbătrânit în țară, dacă vă veți strica și veți face vreun chip cioplit, o înfățișare a vreunui lucru, făcând ce este rău în ochii DOMNULUI, Dumnezeul tău, ca să-L mâniați,",
    "iau astăzi martori împotriva voastră cerul și pământul că veți pieri degrabă din țara în care treceți peste Iordan s-o luați în stăpânire; nu veți avea zile multe în ea, ci veți fi nimiciți cu desăvârșire.",
    "DOMNUL vă va împrăștia printre popoare și nu veți rămâne decât un mic număr printre neamurile unde vă va duce DOMNUL.",
    "Acolo veți sluji unor dumnezei făcuți de mâini omenești, de lemn și de piatră, care nici nu văd, nici nu aud, nici nu mănâncă, nici nu miros.",
    "Dar dacă de acolo Îl vei căuta pe DOMNUL, Dumnezeul tău, Îl vei găsi, dacă Îl vei căuta din toată inima ta și din tot sufletul tău.",
    "În strâmtorarea ta, când te vor ajunge toate aceste lucruri în zilele din urmă, te vei întoarce la DOMNUL, Dumnezeul tău, și vei asculta de glasul Lui;",
    "căci DOMNUL, Dumnezeul tău, este un Dumnezeu plin de îndurare: El nu te va părăsi, nu te va distruge și nu va uita legământul jurat părinților tăi.",
    "Întreabă de vremurile străvechi care au fost înaintea ta, din ziua în care Dumnezeu l-a creat pe om pe pământ, de la o margine a cerului până la cealaltă: a mai fost vreodată un lucru atât de mare sau s-a mai auzit ceva asemănător?",
    "A auzit vreodată un popor glasul lui Dumnezeu vorbind din mijlocul focului, cum l-ai auzit tu, și să fi rămas viu?",
    "Sau a încercat vreodată vreun dumnezeu să meargă să-și ia un neam din mijlocul altui neam prin încercări, prin semne, prin minuni, prin război, cu mână tare și cu braț întins și prin mari înfricoșări, așa cum a făcut pentru voi DOMNUL, Dumnezeul vostru, în Egipt, sub ochii tăi?",
    "Ție ți s-au arătat aceste lucruri ca să cunoști că DOMNUL este Dumnezeu și că nu este altul afară de El.",
    "Din cer te-a făcut să auzi glasul Lui ca să te învețe, iar pe pământ ți-a arătat focul Său cel mare și ai auzit cuvintele Lui din mijlocul focului.",
    "Pentru că i-a iubit pe părinții tăi, a ales urmașii lor după ei și te-a scos El Însuși din Egipt prin puterea Lui cea mare,",
    "ca să alunge dinaintea ta neamuri mai mari și mai puternice decât tine, ca să te ducă în țara lor și să ți-o dea ca moștenire, așa cum se vede astăzi.",
    "Să știi dar astăzi și să-ți pui în inimă că DOMNUL este Dumnezeu sus în ceruri și jos pe pământ, și că nu este altul.",
    "Păzește legile și poruncile Lui pe care ți le dau astăzi, ca să-ți fie bine ție și fiilor tăi după tine, și ca să ai zile multe în țara pe care ți-o dă DOMNUL, Dumnezeul tău, pentru totdeauna.”",
    "Atunci Moise a pus deoparte trei cetăți dincolo de Iordan, spre răsăritul soarelui,",
    "pentru ca să poată fugi acolo ucigașul care va fi omorât pe aproapele său fără intenție și fără să-l fi urât mai înainte, ca să poată scăpa cu viață fugind într-una din aceste cetăți:",
    "Bețer, în pustie, în țara de câmpie, pentru rubeniți; Ramot, în Galaad, pentru gadiți; și Golan, în Basan, pentru manasiți.",
    "Aceasta este Legea pe care a pus-o Moise înaintea fiilor lui Israel.",
    "Acestea sunt mărturiile, legile și orânduirile pe care le-a rostit Moise fiilor lui Israel după ieșirea lor din Egipt,",
    "dincolo de Iordan, în vale, în fața Bet-Peorului, în țara lui Sihon, împăratul amoriților, care locuia la Hesbon, pe care l-au înfrânt Moise și fiii lui Israel după ieșirea lor din Egipt.",
    "Ei au luat în stăpânire țara lui și țara lui Og, împăratul Basanului, cei doi împărați ai amoriților care erau dincolo de Iordan, spre răsăritul soarelui,",
    "de la Aroer, care este pe marginea pârâului Arnon, până la muntele Sion (care este Hermonul),",
    "și toată câmpia Arabah dincolo de Iordan, spre răsărit, până la marea din Arabah, sub poalele muntelui Pisga.",
  ],
}
