export const DEUTERONOM_TEXT_3: Record<number, readonly string[]> = {
  3: [
    "Ne-am întors și ne-am suit pe drumul spre Basan. Og, împăratul Basanului, a ieșit în întâmpinarea noastră cu tot poporul lui, ca să lupte la Edrei.",
    "DOMNUL mi-a zis: «Nu te teme de el, căci îl dau în mâinile tale pe el, tot poporul lui și țara lui; îi vei face așa cum i-ai făcut lui Sihon, împăratul amoriților, care locuia la Hesbon.»",
    "Și DOMNUL, Dumnezeul nostru, ni l-a dat în mână și pe Og, împăratul Basanului, cu tot poporul lui; l-am bătut până n-a mai rămas din el niciun supraviețuitor.",
    "Am cucerit atunci toate cetățile lui; n-a fost nicio cetate pe care să nu le-o fi luat: șaizeci de cetăți, toată regiunea Argob, împărăția lui Og în Basan.",
    "Toate aceste cetăți erau fortificate cu ziduri înalte, porți și zăvoare, afară de cetățile fără ziduri, care erau foarte numeroase.",
    "Le-am dat spre nimicire, așa cum îi făcuserăm lui Sihon, împăratul Hesbonului, nimicind orice cetate cu bărbați, femei și copii.",
    "Dar toate vitele și prada din cetăți le-am luat pentru noi.",
    "Astfel am luat în vremea aceea din mâna celor doi împărați ai amoriților țara de dincolo de Iordan, de la pârâul Arnon până la muntele Hermon",
    "(sidonienii îl numesc pe Hermon Sirion, iar amoriții îl numesc Senir),",
    "toate cetățile din câmpie, tot Galaadul și tot Basanul până la Salca și Edrei, cetăți din împărăția lui Og în Basan.",
    "(Căci numai Og, împăratul Basanului, mai rămăsese din restul refaimiților. Iată, patul lui de fier este la Raba fiilor lui Amon. Lungimea lui este de douăzeci de coți, iar lățimea de opt coți, după cotul unui om.)",
    "Țara aceasta am luat-o în stăpânire în vremea aceea. De la Aroer, care este pe pârâul Arnon, și jumătate din muntele Galaad cu cetățile lui le-am dat rubeniților și gadiților.",
    "Restul Galaadului și tot Basanul, împărăția lui Og, le-am dat la jumătate din seminția lui Manase: toată regiunea Argob cu tot Basanul, care se numea țara refaimiților.",
    "Iair, fiul lui Manase, a luat toată regiunea Argob până la hotarul geșuriților și maacatiților și a numit Basanul după numele său, Havot-Iair, până în ziua de astăzi.",
    "Lui Machir i-am dat Galaadul.",
    "Iar rubeniților și gadiților le-am dat o parte din Galaad până la pârâul Arnon, mijlocul pârâului slujind ca hotar, și până la pârâul Iaboc, hotarul fiilor lui Amon;",
    "de asemenea Arabah și Iordanul ca hotar, de la Chineret până la marea din Arabah, Marea Sărată, sub poalele muntelui Pisga, spre răsărit.",
    "În vremea aceea v-am dat această poruncă, zicând: «DOMNUL, Dumnezeul vostru, v-a dat țara aceasta ca s-o stăpâniți. Voi toți, oamenii viteji, să treceți înarmați înaintea fraților voștri, fiii lui Israel.",
    "Numai femeile voastre, pruncii voștri și vitele voastre — știu că aveți multe vite — să rămână în cetățile pe care vi le-am dat,",
    "până ce DOMNUL va da odihnă fraților voștri ca și vouă și vor lua și ei în stăpânire țara pe care DOMNUL, Dumnezeul vostru, le-o dă dincolo de Iordan. Apoi vă veți întoarce fiecare la stăpânirea pe care v-am dat-o.»",
    "În vremea aceea i-am dat poruncă lui Iosua, zicând: «Ochii tăi au văzut tot ce a făcut DOMNUL, Dumnezeul vostru, acestor doi împărați; așa va face DOMNUL tuturor împărățiilor în care vei trece.",
    "Nu te teme de ei, căci DOMNUL, Dumnezeul vostru, El Însuși Se va lupta pentru voi!»",
    "În vremea aceea m-am rugat DOMNULUI, zicând:",
    "«Doamne DUMNEZEULE, Tu ai început să-I arăți slujitorului Tău mărimea Ta și mâna Ta cea puternică; căci ce dumnezeu este în cer sau pe pământ care să poată face lucrări ca ale Tale și izbânzi ca ale Tale?",
    "Lasă-mă, te rog, să trec și să văd țara cea bună de dincolo de Iordan, acest munte frumos și Libanul!»",
    "Dar DOMNUL S-a mâniat pe mine din cauza voastră și nu m-a ascultat. DOMNUL mi-a zis: «Destul! Nu-Mi mai vorbi despre lucrul acesta!",
    "Suie-te pe vârful Pisga, ridică-ți ochii spre apus, spre nord, spre sud și spre răsărit și privește cu ochii tăi, căci nu vei trece Iordanul acesta.",
    "Dă porunci lui Iosua, întărește-l și îmbărbătează-l, căci el va trece înaintea acestui popor și el îi va pune în stăpânire țara pe care o vei vedea.»",
    "Și am rămas în vale, în fața Bet-Peorului.",
  ],
}
