export const DEUTERONOM_TEXT_19: Record<number, readonly string[]> = {
  19: [
    "„Când DOMNUL, Dumnezeul tău, va fi nimicit neamurile a căror țară ți-o dă DOMNUL, Dumnezeul tău, și când le vei fi alungat și vei locui în cetățile lor și în casele lor,",
    "să-ți pui deoparte trei cetăți în mijlocul țării pe care ți-o dă DOMNUL, Dumnezeul tău, s-o stăpânești.",
    "Să-ți pregătești drumul și să împarți în trei regiuni hotarul țării tale pe care ți-o dă DOMNUL, Dumnezeul tău, ca moștenire, pentru ca orice ucigăș să poată fugi acolo.",
    "Iată în ce caz va fugi acolo ucigășul ca să-și scape viața: cel ce va fi omorât pe aproapele său fără intenție și fără să-l fi urât mai înainte;",
    "cum este cel ce merge cu aproapele său în pădure să taie lemne, și mâna lui ridică securea să taie copacul, dar fierul sare din coadă și îl lovește pe aproapele său și acesta moare — un astfel de om să fugă într-una din aceste cetăți ca să-și scape viața;",
    "ca nu cumva răzbunătorul sângelui, urmărit de iuțimea mâniei lui, să-l ajungă pe ucigăș dacă drumul va fi prea lung, și să-l lovească mortal, deși el nu era vinovat de moarte, pentru că nu-l urâse mai înainte.",
    "De aceea îti dau această poruncă: «Pune-ți deoparte trei cetăți!»",
    "Și dacă DOMNUL, Dumnezeul tău, îiți va lărgi hotarele, așa cum a jurat părinților tăi, și îiți va da toată țara pe care a făgăduit că o va da părinților tăi,",
    "dacă vei păzi și vei îplini toate aceste porunci pe care ți le dau astăzi, iubindu-L pe DOMNUL, Dumnezeul tău, și umblând neîncetat pe căile Lui, atunci să mai adaugi trei cetăți la aceste trei,",
    "ca să nu fie vărsat sânge nevinovat în mijlocul țării tale pe care ți-o dă DOMNUL, Dumnezeul tău, ca moștenire, și să nu fii încărcat cu vinovăția sângelui.",
    "Dar dacă un om îl urăște pe aproapele său, îl pândește, se ridică împotriva lui, îl lovește mortal și acesta moare, iar ucigășul fuge într-una din aceste cetăți,",
    "bătrânii cetății lui să trimită să-l prindă de acolo și să-l dea în mâinile răzbunătorului sângelui, ca să fie pus la moarte.",
    "Ochiul tău să n-aibă milă de el, ci să curăți din Israel sângele nevinovat, ca să-ți fie bine.",
    "Să nu muți hotarul aproapelui tău, pus de cei de demult în moștenirea pe care o vei primi în țara pe care ți-o dă DOMNUL, Dumnezeul tău, s-o stăpânești.",
    "Un singur martor nu va fi de ajuns împotriva unui om pentru nicio nelegiuire sau pentru vreun păcat pe care l-ar fi săvârșit; orice cauză să se adeverească pe mărturia a doi sau trei martori.",
    "Când se va ridica un martor nedrept împotriva unui om ca să-l învinuiască de o abatere,",
    "cei doi oameni care au neînțelegerea să se înfățișeze înaintea DOMNULUI, înaintea preoților și judecătorilor care vor fi în vremea aceea.",
    "Judecătorii să cerceteze cu de-amănuntul; și dacă se găsește că martorul este un martor mincinos și a făcut o mărturie mincinoasă împotriva fratelui său,",
    "atunci să-i faceți așa cum intenționase el să-i facă fratelui său. Astfel să curăți răul din mijlocul tău.",
    "Ceilalți vor auzi și se vor teme, și nu se va mai face o astfel de faptă rea în mijlocul tău.",
    "Ochiul tău să n-aibă milă: ci viață pentru viață, ochi pentru ochi, dinte pentru dinte, mână pentru mână, picior pentru picior.”",
  ],
}
