export const DEUTERONOM_TEXT_23: Record<number, readonly string[]> = {
  23: [
    "„Cel ce are moșiile zdrobite sau mădularul tăiat să nu intre în adunarea DOMNULUI.",
    "Cel născut din curvie să nu intre în adunarea DOMNULUI; nici chiar la a zecea generație, niciunul din ai lui să nu intre în adunarea DOMNULUI.",
    "Amonitul și moabitul să nu intre în adunarea DOMNULUI; nici chiar la a zecea generație, niciunul din ai lor să nu intre în adunarea DOMNULUI, niciodată,",
    "pentru că nu v-au ieșit în întâmpinare cu pâine și apă pe drum, la ieșirea voastră din Egipt, și pentru că au tocmit împotriva ta pe Balaam, fiul lui Beor, din Petor în Mesopotamia, ca să te blesteme.",
    "Dar DOMNUL, Dumnezeul tău, n-a vrut să-l asculte pe Balaam, și DOMNUL, Dumnezeul tău, a schimbat blestemul în binecuvântare pentru tine, pentru că DOMNUL, Dumnezeul tău, te iubește.",
    "Să nu cauți nici pacea lor, nici bunăstarea lor în toate zilele tale, niciodată.",
    "Să nu-l urăști pe edomit, căci este fratele tău; să nu-l urăști pe egiptean, căci ai fost străin în țara lui.",
    "Fiii care li se vor naște la a treia generație vor putea să intre în adunarea DOMNULUI.",
    "Când vei ieși cu tabăra împotriva vrăjmașilor tăi, să te ferești de orice lucru rău.",
    "Dacă va fi la tine vreun om care nu este curat din cauza vreunei scurgeri de noapte, să iasă afară din tabără și să nu intre în mijlocul taberei.",
    "Spre seară să se spele cu apă, și după apusul soarelui va putea să intre în tabără.",
    "Să ai un loc afară din tabără și acolo să ieși afară.",
    "Să ai printre uneltele tale o lopățică, și când te vei așeza afară, să sapi cu ea și apoi să acoperi murdăria ieșită din tine.",
    "Căci DOMNUL, Dumnezeul tău, umblă în mijlocul taberei tale ca să te scape și să ți-i dea pe vrăjmașii tăi în mână; de aceea tabăra ta să fie sfântă, ca DOMNUL să nu vadă la tine nimic necurat și să nu Se întoarcă de la tine.",
    "Să nu predai stăpânului său pe robul care a fugit la tine de la stăpânul lui.",
    "Să rămână cu tine, în mijlocul tău, în locul pe care-l va alege el într-una din cetățile tale, unde-i va plăcea; să nu-l asuprești.",
    "Nicio fiică a lui Israel să nu fie prostituată de templu și niciun fiu al lui Israel să nu fie prostituat de templu.",
    "Să nu aduci în casa DOMNULUI, Dumnezeului tău, pentru îplinirea vreunei făgăduințe, câștigul unei prostituate, nici prețul unui câine, căci amândouă sunt o urâciune înaintea DOMNULUI, Dumnezeului tău.",
    "Să nu iei dobândă de la fratele tău, nici pentru argint, nici pentru hrană, nici pentru vreun alt lucru care se dă cu dobândă.",
    "De la străin vei putea lua dobândă, dar de la fratele tău să nu iei dobândă, pentru ca DOMNUL, Dumnezeul tău, să te binecuvânteze în tot ce vei pune mâna în țara în care intri s-o iei în stăpânire.",
    "Dacă vei face o făgăduință DOMNULUI, Dumnezeului tău, să nu întârzii s-o îplinesti; căci DOMNUL, Dumnezeul tău, ți-ar cere socoteală de ea și te-ai încărca cu un păcat.",
    "Dacă te vei abține să faci o făgăduință, nu va fi un păcat pentru tine.",
    "Dar ce va ieși din buzele tale să păzești și să îplinesti, potrivit cu făgăduința de bunăvoie pe care ai făcut-o DOMNULUI, Dumnezeului tău, cu gura ta.",
    "Când vei intra în via aproapelui tău, vei putea mânca strugurii după dorința ta, până te vei sătura, dar să nu pui în vasul tău.",
    "Când vei intra în grâul neridicatul al aproapelui tău, vei putea rupe spice cu mâna, dar să nu pui secerea în grâul aproapelui tău.”",
  ],
}
