export const DEUTERONOM_TEXT_5: Record<number, readonly string[]> = {
  5: [
    "Moise a chemat pe tot Israelul și le-a zis: „Ascultă, Israele, legile și poruncile pe care vi le rostesc astăzi în urechi; învățați-le și păziți-le ca să le împliniți.",
    "DOMNUL, Dumnezeul nostru, a încheiat un legământ cu noi la Horeb.",
    "Nu cu părinții noștri a încheiat DOMNUL legământul acesta, ci cu noi, care suntem toți aici vii astăzi.",
    "DOMNUL v-a vorbit față în față pe munte, din mijlocul focului.",
    "Eu stam atunci între DOMNUL și voi, ca să vă vestesc cuvântul DOMNULUI; căci vă temăeați de foc și nu v-ați suit pe munte. El a zis:",
    "«Eu sunt DOMNUL, Dumnezeul tău, Care te-am scos din țara Egiptului, din casa robiei.",
    "Să nu ai alți dumnezei în afară de Mine.",
    "Să nu-ți faci chip cioplit, nici vreo înfățișare a lucrurilor care sunt sus în ceruri, sau jos pe pământ, sau în apele sub pământ.",
    "Să nu te închini înaintea lor și să nu le slujești; căci Eu, DOMNUL, Dumnezeul tău, sunt un Dumnezeu gelos, Care pedepsesc nelegiuirea părinților în fii până la a treia și a patra generație a celor ce Mă urăsc,",
    "și Mă arăt plin de îndurare față de mii de generații ale celor ce Mă iubesc și păzesc poruncile Mele.",
    "Să nu iei în deșert Numele DOMNULUI, Dumnezeul tău; căci DOMNUL nu va lăsa nepedepsit pe cel ce ia în deșert Numele Lui.",
    "Păzește ziua sabatului ca s-o sfințești, așa cum ți-a poruncit DOMNUL, Dumnezeul tău.",
    "Șase zile să lucrezi și să-ți faci toată lucrarea ta,",
    "dar ziua a șaptea este sabatul DOMNULUI, Dumnezeul tău: să nu faci nicio lucrare în ea, nici tu, nici fiul tău, nici fiica ta, nici robul tău, nici roaba ta, nici boul tău, nici măgarul tău, nici vreunul din animalele tale, nici străinul care locuiește în porțile tale, pentru ca robul tău și roaba ta să se odihnească la fel ca tine.",
    "Adu-ți aminte că ai fost rob în țara Egiptului și că DOMNUL, Dumnezeul tău, te-a scos de acolo cu mână tare și cu braț întins; de aceea ți-a poruncit DOMNUL, Dumnezeul tău, să păzești ziua sabatului.",
    "Cinstește pe tatăl tău și pe mama ta, așa cum ți-a poruncit DOMNUL, Dumnezeul tău, ca să ți se lungească zilele și să-ți fie bine în țara pe care ți-o dă DOMNUL, Dumnezeul tău.",
    "Să nu ucizi.",
    "Să nu comiți adulter.",
    "Să nu furi.",
    "Să nu mărturisești strâmb împotriva aproapelui tău.",
    "Să nu poftești nevasta aproapelui tău; să nu poftești casa aproapelui tău, nici ogorul lui, nici robul lui, nici roaba lui, nici boul lui, nici măgarul lui, nici vreun alt lucru care este al aproapelui tău.»",
    "Aceste cuvinte le-a rostit DOMNUL întregii voastre adunări, pe munte, din mijlocul focului, al norilor și al beznei, cu glas puternic, și n-a mai adăugat nimic. Le-a scris pe două table de piatră și mi le-a dat.",
    "Când ați auzit glasul din mijlocul întunericului, în timp ce muntele ardea în foc, v-ați apropiat de mine, toate căpeteniile semințiilor voastre și bătrânii voștri,",
    "și ați zis: «Iată că DOMNUL, Dumnezeul nostru, ne-a arătat slava și mărimea Lui și i-am auzit glasul din mijlocul focului; astăzi am văzut că Dumnezeu poate vorbi unui om și omul să rămână viu.",
    "Acum dar de ce să murim? Căci acest foc mare ne va mistui; dacă vom mai auzi glasul DOMNULUI, Dumnezeul nostru, vom muri.",
    "Căci cine din toată făptura a auzit glasul Dumnezeului celui viu vorbind din mijlocul focului, cum l-am auzit noi, și să fi rămas viu?",
    "Apropie-te tu și ascultă tot ce va spune DOMNUL, Dumnezeul nostru; apoi să ne spui tu tot ce-ți va spune DOMNUL, Dumnezeul nostru, iar noi vom asculta și vom împlini.»",
    "DOMNUL a auzit glasul cuvintelor voastre pe care mi le-ați rostit și DOMNUL mi-a zis: «Am auzit glasul cuvintelor acestui popor pe care ți le-au rostit; tot ce au zis este bine.",
    "O, de ar avea ei întotdeauna o astfel de inimă, ca să Se teamă de Mine și să păzească toate poruncile Mele în toate zilele, ca să le fie bine lor și fiilor lor pentru totdeauna!",
    "Du-te și spune-le: «Întoarceți-vă în corturile voastre!»",
    "Dar tu stai aici cu Mine și îiți voi spune toate poruncile, legile și orânduirile pe care să-i înveți să le împlinească în țara pe care le-o dau în stăpânire.»",
    "Păziți dar și împliniți așa cum v-a poruncit DOMNUL, Dumnezeul vostru; să nu vă abateți nici la dreapta, nici la stânga.",
    "Să umblați pe toată calea pe care v-a poruncit-o DOMNUL, Dumnezeul vostru, ca să trăiți, să vă fie bine și să aveți zile multe în țara pe care o veți lua în stăpânire.”",
  ],
}
