export const DEUTERONOM_TEXT_20: Record<number, readonly string[]> = {
  20: [
    "„Când vei ieși la război împotriva vrăjmașilor tăi și vei vedea cai, care și un popor mai numeros decât tine, să nu te temeți de ei, căci DOMNUL, Dumnezeul tău, Care te-a scos din țara Egiptului, este cu tine.",
    "Când vă veți merge la luptă, preotul să se apropie și să vorbească poporului,",
    "și să le spună: «Ascultă, Israele! Voi mergeți astăzi la luptă împotriva vrăjmașilor voștri. Să nu vi se înmoaie inima, nu vă temeți, nu vă spăimântați și nu vă îngroziți din cauza lor;",
    "căci DOMNUL, Dumnezeul vostru, merge El Însuși cu voi ca să Se lupte pentru voi împotriva vrăjmașilor voștri și să vă mântuiască.»",
    "Apoi supraveghetorii să vorbească poporului, zicând: «Cine a zidit o casă nouă și n-a sfințit-o încă? Să plece și să se întoarcă acasă, ca nu cumva să moară în luptă și să o sfințească altul.",
    "Cine a sădit o vie și n-a mâncat din ea încă? Să plece și să se întoarcă acasă, ca nu cumva să moară în luptă și să mănânce altul din ea.",
    "Cine s-a logodit cu o femeie și n-a luat-o încă? Să plece și să se întoarcă acasă, ca nu cumva să moară în luptă și să o ia altul.»",
    "Supraveghetorii să vorbească mai departe poporului și să zică: «Cine este fricos și slăbit la inimă? Să plece și să se întoarcă acasă, ca să nu înmoaie inima fraților lui cum s-a înmuiat a lui.»",
    "După ce supraveghetorii vor fi terminat de vorbit poporului, să pună căpetenii de oaste în fruntea poporului.",
    "Când te vei apropia de o cetate ca s-o bați, să-i oferi mai întâi pacea.",
    "Dacă îți va răspunde cu pace și îți va deschide porțile, tot poporul care se va afla în ea să-ți fie supus la bir și să-ți slujească.",
    "Dar dacă nu va face pace cu tine și va voi să se lupte cu tine, atunci s-o împresori.",
    "Și când DOMNUL, Dumnezeul tău, ți-o va da în mână, să treci prin ascuțișul sabiei pe toți cei de parte bărbătească.",
    "Numai femeile, pruncii, vitele și tot ce va fi în cetate, toată prada ei, să le iei ca pradă pentru tine; și vei mânca din prada vrăjmașilor tăi pe care ți i-a dat DOMNUL, Dumnezeul tău.",
    "Așa să faci tuturor cetăților care vor fi foarte departe de tine și care nu fac parte din cetățile acestor neamuri.",
    "Dar în cetățile acestor popoare pe care ți le dă DOMNUL, Dumnezeul tău, ca moștenire, să nu lași cu viață nimic din ce suflă;",
    "ci să le dai spre nimicire cu desăvârșire: pe hetiți, pe amoriți, pe canaaniți, pe fereziți, pe heviți și pe iebusiți, așa cum ți-a poruncit DOMNUL, Dumnezeul tău,",
    "ca să nu vă învețe să faceți după toate urâciunile lor pe care le fac ei dumnezeilor lor și să păcătuiți împotriva DOMNULUI, Dumnezeului vostru.",
    "Când vei împresura o cetate multă vreme, făcând război împotriva ei ca s-o cucerești, să nu-i nimicești pomii ridicând securea împotriva lor; să mănânci din ei, dar să nu-i tai. Căci pomul de pe câmp este el oare un om ca să fie împresurat de tine?",
    "Numai pomii despre care vei ști că nu sunt pomi roditori vei putea să-i nimicești și să-i tai, și să faci din ei unelte de împresurare împotriva cetății care face război cu tine, până va cădea.”",
  ],
}
