export const DEUTERONOM_TEXT_27: Record<number, readonly string[]> = {
  27: [
    "Moise și bătrânii lui Israel au dat această poruncă poporului, zicând: „Paziți toate poruncile pe care vi le dau astăzi.",
    "În ziua când veți trece Iordanul ca să intrați în țara pe care ți-o dă DOMNUL, Dumnezeul tău, să-ți ridici niște pietre mari și să le tencuiești cu var.",
    "Să scrii pe ele toate cuvintele acestei Legi, după ce vei fi trecut Iordanul ca să intri în țara pe care ți-o dă DOMNUL, Dumnezeul tău, o țară în care curge lapte și miere, așa cum ți-a spus DOMNUL, Dumnezeul părinților tăi.",
    "După ce veți trece Iordanul, să ridicați pe muntele Ebal pietrele acestea despre care vă dau poruncă astăzi și să le tencuiți cu var.",
    "Acolo să zidești un altar DOMNULUI, Dumnezeului tău, un altar de pietre peste care să nu fi ridicat fierul.",
    "Din pietre necioplite să zidești altarul DOMNULUI, Dumnezeului tău, și pe el să aduci arderi-de-tot DOMNULUI, Dumnezeului tău.",
    "Să jertfești jertfe de mulțumire, să mânci acolo și să te bucuri înaintea DOMNULUI, Dumnezeului tău.",
    "Să scrii pe aceste pietre toate cuvintele acestei Legi, foarte deslușit.”",
    "Moise și preoții leviți au vorbit întregului Israel, zicând: „Taci și ascultă, Israele! Astăzi ai ajuns poporul DOMNULUI, Dumnezeului tău.",
    "Să asculți de glasul DOMNULUI, Dumnezeului tău, și să îplinesti poruncile și rânduielile Lui pe care ți le dau astăzi.”",
    "În ziua aceea Moise a dat această poruncă poporului, zicând:",
    "„Când veți trece Iordanul, Simeon, Levi, Iuda, Isahar, Iosif și Beniamin să stea pe muntele Garizim ca să binecuvânteze poporul;",
    "iar Ruben, Gad, Așer, Zabulon, Dan și Neftali să stea pe muntele Ebal ca să rostească blestemul.",
    "Leviții să ia cuvântul și să spună cu glas tare tuturor bărbaților lui Israel:",
    "«Blestemat să fie omul care va face un chip cioplit sau turnat, urâciune înaintea DOMNULUI, lucrare de mâini de meșter, și care-l va pune într-un loc ascuns!» Și tot poporul să răspundă și să zică: «Amin!»",
    "«Blestemat să fie cel ce va defăima pe tatăl său sau pe mama sa!» Și tot poporul să zică: «Amin!»",
    "«Blestemat să fie cel ce va muta hotarul aproapelui său!» Și tot poporul să zică: «Amin!»",
    "«Blestemat să fie cel ce va rătăci pe un orb pe drum!» Și tot poporul să zică: «Amin!»",
    "«Blestemat să fie cel ce va strâmba judecata străinului, orfanului și văduvei!» Și tot poporul să zică: «Amin!»",
    "«Blestemat să fie cel ce se va culca cu nevasta tatălui său, căci dă la o parte învelitoarea tatălui său!» Și tot poporul să zică: «Amin!»",
    "«Blestemat să fie cel ce se va culca cu vreun animal!» Și tot poporul să zică: «Amin!»",
    "«Blestemat să fie cel ce se va culca cu sora sa, fiica tatălui său sau fiica mamei sale!» Și tot poporul să zică: «Amin!»",
    "«Blestemat să fie cel ce se va culca cu soacra sa!» Și tot poporul să zică: «Amin!»",
    "«Blestemat să fie cel ce va lovi pe aproapele său în ascuns!» Și tot poporul să zică: «Amin!»",
    "«Blestemat să fie cel ce va primi mită ca să ucidă un om nevinovat!» Și tot poporul să zică: «Amin!»",
    "«Blestemat să fie cel ce nu va confirma cuvintele acestei Legi ca să le îplinească!» Și tot poporul să zică: «Amin!»”",
  ],
}
