export const DEUTERONOM_TEXT_30: Record<number, readonly string[]> = {
  30: [
    "„Când vor veni peste tine toate aceste lucruri, binecuvântarea și blestemul pe care le-am pus înaintea ta, dacă le vei primi în inima ta în mijlocul tuturor neamurilor unde te va fi împrăștiat DOMNUL, Dumnezeul tău,",
    "și dacă te vei întoarce la DOMNUL, Dumnezeul tău, și vei asculta de glasul Lui din toată inima ta și din tot sufletul tău, tu și fiii tăi, potrivit cu tot ce-ți poruncesc eu astăzi,",
    "atunci DOMNUL, Dumnezeul tău, va aduce înapoi pe prinșii tăi de război, va avea milă de tine și te va aduna din nou din mijlocul tuturor popoarelor printre care te va fi împrăștiat DOMNUL, Dumnezeul tău.",
    "Chiar dacă ai fi surghiunit la marginea cerului, de acolo te va aduna DOMNUL, Dumnezeul tău, și de acolo te va lua.",
    "DOMNUL, Dumnezeul tău, te va aduce în țara pe care o stăpâneau părinții tăi și o vei stăpâni; El îiți va face bine și te va înmulți mai mult decât pe părinții tăi.",
    "DOMNUL, Dumnezeul tău, îiți va tăia împrejur inima ta și inima urmașilor tăi, ca să-L iubești pe DOMNUL, Dumnezeul tău, din toată inima ta și din tot sufletul tău, ca să trăiești.",
    "DOMNUL, Dumnezeul tău, va pune toate aceste blesteme peste vrăjmașii tăi și peste cei ce te urăsc și te-au prigonit.",
    "Iar tu te vei întoarce, vei asculta de glasul DOMNULUI și vei îplinesti toate poruncile Lui pe care ți le dau astăzi.",
    "DOMNUL, Dumnezeul tău, te va umple de belșug în toată lucrarea mâinilor tale, în rodul pântecelui tău, în rodul vitelor tale și în rodul pământului tău; căci DOMNUL Se va bucura din nou de tine spre binele tău, așa cum Se bucura de părinții tăi,",
    "dacă vei asculta de glasul DOMNULUI, Dumnezeului tău, păzind poruncile și legile Lui scrise în cartea acestei Legi, dacă te vei întoarce la DOMNUL, Dumnezeul tău, din toată inima ta și din tot sufletul tău.",
    "Căci porunca aceasta pe care ți-o dau astăzi nu este prea înăltă pentru tine și nu este departe de tine.",
    "Nu este în cer, ca să zici: «Cine se va sui pentru noi în cer ca să ne-o aducă și să ne-o facă s-o auzim, ca s-o îplinim?»",
    "Nu este nici dincolo de mare, ca să zici: «Cine va trece pentru noi dincolo de mare ca să ne-o aducă și să ne-o facă s-o auzim, ca s-o îplinim?»",
    "Ci cuvântul este foarte aproape de tine, în gura ta și în inima ta, ca să-l îplinesti.",
    "Iată, pun astăzi înaintea ta viața și binele, moartea și răul.",
    "Căci îiți poruncesc astăzi să-L iubești pe DOMNUL, Dumnezeul tău, să umbli pe căile Lui și să păzești poruncile Lui, legile Lui și orânduirile Lui, ca să trăiți și să te înmulțești, și ca DOMNUL, Dumnezeul tău, să te binecuvânteze în țara în care intri s-o iei în stăpânire.",
    "Dar dacă inima ta se va abate, dacă n-asculti și te vei lăsa ademenit să te închini înaintea altor dumnezei și să le slujești,",
    "vă mărturisesc astăzi că veți pieri neapărat și nu veți avea zile multe în țara în care treci peste Iordan s-o iei în stăpânire.",
    "Iau astăzi martori împotriva voastră cerul și pământul că ți-am pus înainte viața și moartea, binecuvântarea și blestemul. Alege viața, ca să trăiești, tu și urmașii ta,",
    "iubindu-L pe DOMNUL, Dumnezeul tău, ascultând de glasul Lui și alipindu-te de El; căci aceasta este viața ta și lungimea zilelor tale, ca să locuiești în țara pe care a jurat DOMNUL părinților tăi, lui Avraam, lui Isaac și lui Iacov, că le-o va da.”",
  ],
}
