export const DEUTERONOM_TEXT_18: Record<number, readonly string[]> = {
  18: [
    "„Preoții leviți, toată seminția lui Levi, să n-aibă parte nici moștenire cu Israel; ei să se hrănească din jertfele mistuite de foc ale DOMNULUI și din moștenirea Lui.",
    "Să n-aibă moștenire în mijlocul fraților lor: DOMNUL este moștenirea lor, așa cum le-a spus El.",
    "Iată care va fi dreptul preoților din partea poporului, din partea celor ce vor jertfi un bou sau o oaie: să i se dea preotului spata, fălcile și pântecele.",
    "Să-i dai cele dintâi roade din grâul tău, din mustul tău și din uleiul tău, și prima tunsă a oilor tale.",
    "Căci pe el l-a ales DOMNUL, Dumnezeul tău, din toate semințiile tale, ca să stea și să slujăească în Numele DOMNULUI, el și fiii lui, pentru totdeauna.",
    "Dacă un levit va veni dintr-una din porțile tale, din tot Israelul unde locuiește, și va veni după toată dorința sufletului său la locul pe care-l va alege DOMNUL,",
    "să slujăească în Numele DOMNULUI, Dumnezeului său, ca toți frații lui leviți care stau acolo înaintea DOMNULUI.",
    "Ei să mânce părți egale, afară de ce va fi vândut din averea părintească.",
    "Când vei intra în țara pe care ți-o dă DOMNUL, Dumnezeul tău, să nu te îveți să faci după urâciunile acelor neamuri.",
    "Să nu se găsească la tine nimeni care să-și treacă pe fiul său sau pe fiica sa prin foc, nimeni care să practice ghicirea, citirea în stele, vrăjitoria, descântecul,",
    "nicio legătură cu duhurile, nimeni care să întrebe pe cei ce cheamă morții sau care să întrebe pe morți.",
    "Căci oricine face aceste lucruri este o urâciune înaintea DOMNULUI; și din cauza acestor urâciuni le alungă DOMNUL, Dumnezeul tău, dinaintea ta.",
    "Tu să fii nesfârșit de curat înaintea DOMNULUI, Dumnezeului tău.",
    "Căci neamurile acestea pe care le vei alunga ascultă de cititorii în stele și de ghicitori; dar ție DOMNUL, Dumnezeul tău, nu ți-a îngăduit așa ceva.",
    "DOMNUL, Dumnezeul tău, îiți va ridica din mijlocul tău, dintre frații tăi, un Proroc ca mine: de el să ascultați!",
    "Așa ai cerut DOMNULUI, Dumnezeului tău, la Horeb, în ziua adunării, când ziceai: «Să nu mai aud glasul DOMNULUI, Dumnezeului meu, și să nu mai văd acest foc mare, ca să nu mor!»",
    "DOMNUL mi-a zis: «Tot ce au zis este bine.",
    "Le voi ridica din mijlocul fraților lor un Proroc ca tine, voi pune cuvintele Mele în gura Lui și El le va spune tot ce-I voi porunci Eu.",
    "Și dacă cineva nu va asculta de cuvintele Mele pe care le va rosti El în Numele Meu, Eu Însumi îi voi cere socoteală.",
    "Dar prorocul care va avea îndrăzneala să spună în Numele Meu un cuvânt pe care nu-i voi fi poruncit să-l spună, sau care va vorbi în numele altor dumnezei, prorocul acela să fie dat la moarte.»",
    "Și dacă vei zice în inima ta: «Cum vom cunoaște cuvântul pe care nu l-a rostit DOMNUL?»,",
    "când ceea ce va spune prorocul în Numele DOMNULUI nu se va întâmpla și nu se va adeveri, va fi un cuvânt pe care nu l-a rostit DOMNUL. Prorocul l-a spus din îndrăzneală: să nu te temei de el.”",
  ],
}
