export const DEUTERONOM_TEXT_31: Record<number, readonly string[]> = {
  31: [
    "Moise s-a dus și a rostit aceste cuvinte întregului Israel.",
    "El le-a zis: „Astăzi eu sunt în vârstă de o sută douăzeci de ani; nu mai pot ieși și intra, și DOMNUL mi-a zis: «Nu vei trece Iordanul acesta.»",
    "DOMNUL, Dumnezeul tău, va trece El Însuși înaintea ta; El va nimici neamurile acestea dinaintea ta și le vei lua în stăpânire. Iosua va trece înaintea ta, așa cum a vorbit DOMNUL.",
    "DOMNUL le va face așa cum le-a făcut lui Sihon și lui Og, împărații amoriților, și țării lor, pe care i-a nimicit.",
    "DOMNUL vi-i va da în mână și le veți face potrivit cu toată porunca pe care vă am dat-o.",
    "Fiți tari și îmbărbătați-vă! Nu vă temeți și nu vă spăimântați din cauza lor, căci DOMNUL, Dumnezeul tău, merge El Însuși cu tine; El nu te va lăsa și nu te va părăsi.”",
    "Moise l-a chemat pe Iosua și i-a zis în fața întregului Israel: „Fii tare și îmbărbătează-te! Căci tu vei intra cu poporul acesta în țara pe care DOMNUL a jurat părinților lor că le-o va da, și tu îi vei pune în stăpânirea ei.",
    "DOMNUL merge El Însuși înaintea ta, El va fi cu tine, nu te va lăsa și nu te va părăsi. Nu te teme și nu te spăimânta!”",
    "Moise a scris această Lege și a dat-o preoților, fiii lui Levi, care purtau chivotul legământului DOMNULUI, și tuturor bătrânilor lui Israel.",
    "Moise le-a dat această poruncă, zicând: „La sfârșitul fiecărui al șaptelea an, la vremea anului iertării, la Sărbătoarea Corturilor,",
    "când tot Israelul va veni să se înfățișeze înaintea DOMNULUI, Dumnezeului tău, în locul pe care-l va alege El, să citești această Lege înaintea întregului Israel, în urechile lor.",
    "Adună poporul, bărbații, femeile, pruncii și străinul care este în porțile tale, ca să audă, ca să învețe să se teamă de DOMNUL, Dumnezeul vostru, și să vegheze să îplinească toate cuvintele acestei Legi;",
    "iar fiii lor, care nu o cunosc, să audă și să învețe să se teamă de DOMNUL, Dumnezeul vostru, în toate zilele cât veți trăi în țara peste care treceți Iordanul s-o luați în stăpânire.”",
    "DOMNUL i-a zis lui Moise: „Iată că se apropie ziua morții tale. Cheamă-l pe Iosua și înfățișați-vă în cortul întâlnirii, ca să-i dau porunci.” Moise și Iosua s-au dus și s-au înfățișat în cortul întâlnirii.",
    "DOMNUL S-a arătat în cort într-un stâlp de nor; și stâlpul de nor a stat la ușa cortului.",
    "DOMNUL i-a zis lui Moise: „Iată, tu te vei culca cu părinții tăi; și poporul acesta se va ridica și va curvi după dumnezeii străini ai țării în care intră; Mă va părăsi și va călca legământul Mău pe care l-am încheiat cu el.",
    "În ziua aceea mânia Mea Se va aprinde împotriva lui; îi voi părăsi, Îmi voi ascunde fața de ei și vor fi mistuiți, și multe nenorociri și strâmtorări îl vor ajunge; încât va zice în ziua aceea: «Nu m-au ajuns oare aceste nenorociri pentru că Dumnezeul meu nu este în mijlocul meu?»",
    "Iar Eu Îmi voi ascunde neapărat fața în ziua aceea din cauza tot răul pe care-l va fi făcut, întorcându-se spre alți dumnezei.",
    "Scrieți-vă dar această cântare, învață pe fiii lui Israel în ea, pune-o în gura lor, ca această cântare să-Mi fie martoră împotriva fiilor lui Israel.",
    "Căci îi voi duce în țara pe care am jurat părinților lor că le-o voi da, o țară în care curge lapte și miere; ei vor mânca, se vor sătura și se vor îngrășa, apoi se vor întoarce spre alți dumnezei și le vor sluji, Mă vor disprețui și vor călca legământul Mău.",
    "Și când îl vor ajunge multe nenorociri și strâmtorări, această cântare va mărturisi împotriva lui ca martoră, căci nu va fi uitată din gura urmașilor lui; căci Eu îi cunosc gândurile pe care le zămislește astăzi, înainte chiar de a-l fi dus în țara pe care am jurat că i-o voi da.”",
    "În ziua aceea Moise a scris această cântare și i-a învățat pe fiii lui Israel în ea.",
    "DOMNUL i-a dat poruncă lui Iosua, fiul lui Nun, și a zis: „Fii tare și îmbărbătează-te! Căci tu vei duce pe fiii lui Israel în țara pe care am jurat că le-o voi da; și Eu voi fi cu tine.”",
    "După ce a isprăvit Moise de scris într-o carte toate cuvintele acestei Legi până la capăt,",
    "Moise a dat această poruncă leviților care purtau chivotul legământului DOMNULUI, zicând:",
    "„Luați această carte a Legii și puneți-o alături de chivotul legământului DOMNULUI, Dumnezeului vostru, și să rămână acolo ca martoră împotriva ta.",
    "Căci eu îiți cunosc răzvrătirea și gâtul tău cel înțepenit. Iată, cât trăiesc eu încă astăzi cu voi, v-ați răzvrătit împotriva DOMNULUI; cu cât mai mult după moartea mea!",
    "Adunați la mine pe toți bătrânii semințiilor voastre și pe supraveghetorii voștri, ca să le rostesc în urechi aceste cuvinte și să iau martori împotriva lor cerul și pământul.",
    "Căci știu că după moartea mea vă veți strica cu desăvârșire și vă veți abate de la calea pe care v-am poruncit-o; și nenorocirea vă va ajunge în zilele din urmă, pentru că veți face ce este rău în ochii DOMNULUI, mânindu-L prin lucrarea mâinilor voastre.”",
    "Moise a rostit în urechile întregii adunări a lui Israel cuvintele acestei cântări până la capăt:",
  ],
}
