/*
 * Textul biblic al cărții Exod, capitolele 1-4.
 * Traducerea: Cornilescu, editia corectata (RCCV), în ortografie modernă.
 * Textul rămâne neatins și integral; explicația Emanus stă în fișierele de capitol.
 */

export const EXOD_TEXT_1_TO_4: Record<number, readonly string[]> = {
  1: [
    "Iată numele fiilor lui Israel, intrați în Egipt; au intrat cu Iacov fiecare cu familia lui:",
    "Ruben, Simeon, Levi, Iuda,",
    "Isahar, Zabulon, Beniamin,",
    "Dan, Neftali, Gad și Așer.",
    "Sufletele ieșite din coapsele lui Iacov erau șaptezeci de toate. Iosif era atunci în Egipt.",
    "Iosif a murit, și toți frații lui, și toată vârsta aceea de oameni.",
    "Fiii lui Israel s-au înmulțit, s-au mărit, au crescut și au ajuns foarte puternici. Și s-a umplut țara de ei.",
    "Peste Egipt s-a ridicat un nou împărat, care nu cunoscuse pe Iosif.",
    "El a zis poporului său: „Iată că poporul copiilor lui Israel este mai mare și mai puternic decât noi.",
    "Veniți să ne arătăm dibaci față de el, ca să nu crească, pentru ca nu cumva, dacă se va întâmpla un război, să se unească și el cu vrăjmașii noștri, să ne bată și să iasă apoi din țară.”",
    "Și au pus peste ei isprăvnicei, ca să-i asuprească prin munci grele. Astfel a zidit el cetățile Pitom și Ramses, ca să slujească de hambare lui Faraon.",
    "Dar cu cât îl asupreau mai mult, cu atât se înmulțea și creștea; și s-au scârbit de copiii lui Israel.",
    "Atunci egiptenii au adus pe copiii lui Israel la o aspră robie.",
    "Le-au făcut viața amară prin lucrări grele de lut și cărămizi, și prin tot felul de lucrări de pe câmp: în toate muncile acestea pe care îi sileau să le facă, erau fără nici un pic de milă.",
    "Împăratul Egiptului a poruncit moașelor evreilor, numite una Șifra, și cealaltă Pua,",
    "și le-a zis: „Când veți împlini slujba de moașe pe lângă femeile evreilor, și le veți vedea pe scaunul de naștere, dacă este băiat, să-l omorâți; iar dacă este fată, s-o lăsați să trăiască.”",
    "Dar moașele s-au temut de Dumnezeu, și n-au făcut ce le poruncise împăratul Egiptului: ci au lăsat pe copiii de parte bărbătească să trăiască.",
    "Împăratul Egiptului a chemat pe moașe, și le-a zis: „Pentru ce ați făcut lucrul acesta, și ați lăsat pe copiii de parte bărbătească să trăiască?”",
    "Moașele au răspuns lui Faraon: „Pentru că femeile evreilor nu sunt ca egiptencele; ele sunt vânjoase și nasc înainte de venirea moașei.”",
    "Dumnezeu a făcut bine moașelor; și poporul s-a înmulțit și a ajuns foarte mare la număr.",
    "Pentru că moașele se temuseră de Dumnezeu, Dumnezeu le-a făcut case.",
    "Atunci Faraon a dat următoarea poruncă la tot poporul lui: „Să aruncați în râu pe orice băiat care se va naște, și să lăsați pe toate fetele să trăiască.”",
  ],
  2: [
    "Un om din casa lui Levi luase de nevastă pe o fată a lui Levi.",
    "Femeia aceasta a rămas însărcinată, și a născut un fiu. A văzut că este frumos, și l-a ascuns trei luni.",
    "Ne mai putând să-l ascundă, a luat un sicriaș de papură, pe care l-a uns cu lut și cu smoală; a pus copilul în el, și l-a așezat între trestii, pe malul râului.",
    "Sora copilului pândea la o depărtare oarecare, ca să vadă ce are să i se întâmple.",
    "Fata lui Faraon s-a pogorât la râu, să se scalde; și fetele care o însoțeau se plimbau pe marginea râului. Ea a zărit sicriașul în mijlocul trestiilor, și a trimis pe roaba ei să-l ia.",
    "L-a deschis și a văzut copilul: era un băiețaș care plângea. I-a fost milă de el, și a zis: „Este un copil de al evreilor!”",
    "Atunci sora copilului a zis fetei lui Faraon: „Să mă duc să-ți chem o doică dintre femeile evreilor, ca să-ți alăpteze copilul?”",
    "„Du-te”, i-a răspuns fata lui Faraon. Și fata s-a dus și a chemat pe mama copilului.",
    "Fata lui Faraon i-a zis: „Ia copilul acesta, alăptează-mi-l, și îți voi plăti.” Femeia a luat copilul, și l-a alăptat.",
    "Copilul a crescut, și ea l-a adus fetei lui Faraon; și el i-a fost fiu. I-a pus numele Moise (Scos); „căci”, a zis ea, „l-am scos din ape.”",
    "În vremea aceea, Moise, crescând mare, a ieșit pe la frații săi, și a fost martor la muncile lor grele. A văzut pe un egiptean, care bătea pe un evreu, unul dintre frații lui.",
    "S-a uitat în toate părțile, și, văzând că nu este nimeni, a omorât pe egiptean și l-a ascuns în nisip.",
    "A ieșit și în ziua următoare; și iată că doi evrei se certau. A zis celui ce n-avea dreptate: „Pentru ce lovești pe semenul tău?”",
    "Și omul acela a răspuns: „Cine te-a pus pe tine mai mare și judecător peste noi? Nu cumva ai de gând să mă omori și pe mine, cum ai omorât pe egipteanul acela?” Moise s-a temut și a zis: „Nu mai încape îndoială că faptul este cunoscut.”",
    "Faraon a aflat ce se petrecuse, și căuta să omoare pe Moise. Dar Moise a fugit dinaintea lui Faraon, și a locuit în țara Madian. A șezut lângă o fântână.",
    "Preotul din Madian avea șapte fete. Ele au venit să scoată apă, și au umplut jgheaburile ca să adape turma tatălui lor.",
    "Dar au venit păstorii, și le-au luat la goană. Atunci Moise s-a sculat, le-a ajutat, și le-a adăpat turma.",
    "Când s-au întors ele la tatăl lor Reuel, el a zis: „Pentru ce vă întoarceți așa de curând azi?”",
    "Ele au răspuns: „Un egiptean ne-a scăpat din mâna păstorilor, și chiar ne-a scos apă, și a adăpat turma.”",
    "Și el a zis fetelor: „Unde este? Pentru ce ați lăsat acolo pe omul acela! Chemați-l să mănânce pâine!”",
    "Moise s-a hotărât să locuiască la omul acela, care i-a dat de nevastă pe fiică-sa Sefora.",
    "Ea a născut un fiu, căruia el i-a pus numele Gherșom (Sunt străin aici); „căci”, a zis el, „locuiesc ca străin într-o țară străină.”",
    "După multă vreme, împăratul Egiptului a murit; și copiii lui Israel gemeau încă din pricina robiei, și scoteau strigăte deznădăjduite. Strigătele acestea, pe care li le smulgea robia, s-au suit până la Dumnezeu.",
    "Dumnezeu a auzit gemetele lor, și Și-a adus aminte de legământul Său făcut cu Avraam, Isaac, și Iacov.",
    "Dumnezeu a privit spre copiii lui Israel, și a luat cunoștință de ei.",
  ],
  3: [
    "Moise păștea turma socrului său Ietro, preotul Madianului. Odată a mânat turma până dincolo de pustie, și a ajuns la muntele lui Dumnezeu, la Horeb.",
    "Îngerul Domnului i S-a arătat într-o flacără de foc, care ieșea din mijlocul unui rug. Moise s-a uitat; și iată că rugul era tot un foc, și rugul nu se mistuia deloc.",
    "Moise a zis: „Am să mă întorc să văd ce este această vedenie minunată, și pentru ce nu se mistuie rugul.”",
    "Domnul a văzut că el se întoarce să vadă; și Dumnezeu l-a chemat din mijlocul rugului, și a zis: „Moise! Moise!” El a răspuns: „Iată-mă!”",
    "Dumnezeu a zis: „Nu te apropia de locul acesta; scoate-ți încălțămintele din picioare, căci locul pe care calci este un pământ sfânt.”",
    "Și a adăugat: „Eu sunt Dumnezeul tatălui tău, Dumnezeul lui Avraam, Dumnezeul lui Isaac și Dumnezeul lui Iacov.” Moise și-a ascuns fața, căci se temea să privească pe Dumnezeu.",
    "Domnul a zis: „Am văzut asuprirea poporului Meu, care este în Egipt, și am auzit strigătele pe care le scoate din pricina asupritorilor lui; căci îi cunosc durerile.",
    "M-am pogorât ca să-l izbăvesc din mâna egiptenilor, și să-l scot din țara aceasta și să-l duc într-o țară bună și întinsă, într-o țară unde curge lapte și miere, și anume, în locurile pe care le locuiesc cananiții, hetiții, amoriții, fereziții, heviții și iebusiții.",
    "Iată că strigătele israeliților au ajuns până la Mine, și am văzut chinul cu care îi chinuiesc egiptenii.",
    "Acum, vino, Eu te voi trimite la Faraon, și vei scoate din Egipt pe poporul Meu, pe copiii lui Israel.”",
    "Moise a zis lui Dumnezeu: „Cine sunt eu, ca să mă duc la Faraon, și să scot din Egipt pe copiii lui Israel?”",
    "Dumnezeu a zis: „Eu voi fi negreșit cu tine; și iată care va fi pentru tine semnul că Eu te-am trimis: după ce vei scoate pe popor din Egipt, veți sluji lui Dumnezeu pe muntele acesta.”",
    "Moise a zis lui Dumnezeu: „Iată, când mă voi duce la copiii lui Israel, și le voi spune: «Dumnezeul părinților voștri m-a trimis la voi»; și mă vor întreba: «Care este Numele Lui?» ce le voi răspunde?”",
    "Dumnezeu a zis lui Moise: „Eu sunt Cel ce sunt.” Și a adăugat: „Vei răspunde copiilor lui Israel astfel: «Cel ce se numește Eu sunt m-a trimis la voi.»”",
    "Dumnezeu a mai zis lui Moise: „Așa să vorbești copiilor lui Israel: «Domnul, Dumnezeul părinților voștri, Dumnezeul lui Avraam, Dumnezeul lui Isaac și Dumnezeul lui Iacov, m-a trimis la voi. Acesta este Numele Meu pentru veșnicie, acesta este Numele Meu din neam în neam.»",
    "Du-te, strânge pe bătrânii lui Israel, și spune-le: «Mi s-a arătat Domnul, Dumnezeul părinților voștri, Dumnezeul lui Avraam, lui Isaac și lui Iacov. El a zis: V-am văzut, și am văzut ce vi se face în Egipt,",
    "și am zis: Vă voi scoate din suferința Egiptului, și vă voi duce în țara cananiților, hetiților, amoriților, fereziților, heviților și iebusiților, într-o țară unde curge lapte și miere.»",
    "Ei vor asculta de glasul tău; și te vei duce, tu și bătrânii lui Israel, la împăratul Egiptului, și îi veți spune: «Domnul, Dumnezeul evreilor, s-a întâlnit cu noi. Dă-ne voie să mergem cale de trei zile în pustie, ca să aducem jertfe Domnului, Dumnezeului nostru.»",
    "Știu că împăratul Egiptului n-are să vă lase să plecați decât silit de o mână puternică.",
    "Eu Îmi voi întinde mâna, și voi lovi Egiptul cu tot felul de minuni, pe care le voi face în mijlocul lui. După aceea, are să vă lase să plecați.",
    "Voi face chiar ca poporul acesta să capete trecere înaintea egiptenilor; și, când veți pleca, nu veți pleca cu mâinile goale.",
    "Fiecare femeie va cere de la vecina ei și de la cea care locuiește în casa ei, vase de argint, vase de aur, și haine, pe care le veți pune pe fiii și fiicele voastre. Și veți jefui astfel pe egipteni.”",
  ],
  4: [
    "Moise a răspuns, și a zis: „Iată că n-au să mă creadă, nici n-au să asculte de glasul meu. Ci vor zice: «Nu ți s-a arătat Domnul!»”",
    "Domnul i-a zis: „Ce ai în mână?” El a răspuns: „Un toiag.”",
    "Domnul a zis: „Aruncă-l la pământ.” El l-a aruncat la pământ, și toiagul s-a prefăcut într-un șarpe. Moise fugea de el.",
    "Domnul a zis lui Moise: „Întinde-ți mâna, și apucă-l de coadă.” El a întins mâna și l-a apucat; și șarpele s-a prefăcut iarăși într-un toiag în mâna lui.",
    "„Iată”, a zis Domnul, „ce vei face, ca să creadă că ți s-a arătat Domnul, Dumnezeul părinților lor: Dumnezeul lui Avraam, Dumnezeul lui Isaac și Dumnezeul lui Iacov.”",
    "Domnul i-a mai zis: „Bagă-ți mâna în sân.” El și-a băgat mâna în sân; apoi a scos-o, și iată că mâna i se acoperise de lepră, și se făcuse albă ca zăpada.",
    "Domnul a zis: „Bagă-ți din nou mâna în sân.” El și-a băgat din nou mâna în sân; apoi a scos-o din sân; și iată că mâna se făcuse iarăși cum era carnea lui.",
    "„Dacă nu te vor crede”, a zis Domnul, „și nu vor asculta de glasul celui dintâi semn, vor crede glasul celui de al doilea semn.",
    "Dacă nu vor crede nici aceste două semne, și nu vor asculta de glasul tău, să iei apă din râu, și s-o torni pe pământ; și apa, pe care o vei lua din râu, se va preface în sânge pe pământ.”",
    "Moise a zis Domnului: „Ah! Doamne, eu nu sunt un om cu vorbirea ușoară; și cusurul acesta nu-i nici de ieri, nici de alaltăieri, nici măcar de când vorbești Tu robului Tău; căci vorba și limba mi-este încurcată.”",
    "Domnul i-a zis: „Cine a făcut gura omului? Și cine face pe om mut sau surd, cu vedere sau orb? Oare nu Eu, Domnul?",
    "Du-te, dar; Eu voi fi cu gura ta, și te voi învăța ce vei avea de spus.”",
    "Moise a zis: „Ah! Doamne, trimite pe cine vei vrea să trimiți.”",
    "Atunci Domnul S-a mâniat pe Moise, și a zis: „Nu-i oare acolo fratele tău Aaron, levitul? Știu că el vorbește ușor. Iată că el însuși vine înaintea ta; și, când te va vedea, se va bucura în inima lui.",
    "Tu îi vei vorbi, și vei pune cuvintele în gura lui; și Eu voi fi cu gura ta și cu gura lui; și vă voi învăța ce veți avea de făcut.",
    "El va vorbi poporului pentru tine, îți va sluji drept gură, și tu vei ține pentru el locul lui Dumnezeu.",
    "Ia în mână toiagul acesta, cu care vei face semnele.”",
    "Moise a plecat; și, când s-a întors la socrul său Ietro, i-a zis: „Lasă-mă, te rog, să plec și să mă întorc la frații mei, care sunt în Egipt, ca să văd dacă mai trăiesc.” Ietro a zis lui Moise: „Du-te în pace!”",
    "Domnul a zis lui Moise, în Madian: „Du-te, întoarce-te în Egipt: căci toți cei ce umblau să-ți ia viața, au murit.”",
    "Moise și-a luat nevasta și copiii, i-a pus călări pe măgari, și s-a întors în țara Egiptului. Și-a luat în mână toiagul lui Dumnezeu.",
    "Domnul a zis lui Moise: „Plecând ca să te întorci în Egipt, vezi, toate minunile pe care ți le pun în mână, să le faci înaintea lui Faraon. Eu îi voi împietri inima, și nu va lăsa pe popor să plece.",
    "Tu vei zice lui Faraon: «Așa vorbește Domnul: Israel este fiul Meu, întâiul Meu născut.",
    "Îți spun: Lasă pe fiul Meu să plece, ca să-Mi slujească; dacă nu vrei să-l lași să plece, voi ucide pe fiul tău, pe întâiul tău născut.»”",
    "În timpul călătoriei, într-un loc unde a rămas Moise peste noapte, l-a întâlnit Domnul, și a vrut să-l omoare.",
    "Sefora a luat o piatră ascuțită, a tăiat prepuțul fiului său, și l-a aruncat la picioarele lui Moise, zicând: „Tu ești un soț de sânge pentru mine.”",
    "Și Domnul l-a lăsat. Atunci a zis ea: „Soț de sânge!” din pricina tăierii împrejur.",
    "Domnul a zis lui Aaron: „Du-te înaintea lui Moise în pustie.” Aaron a plecat: a întâlnit pe Moise la muntele lui Dumnezeu, și l-a sărutat.",
    "Moise a făcut cunoscut lui Aaron toate cuvintele Domnului, care-l trimisese, și toate semnele, pe care-i poruncise să le facă.",
    "Moise și Aaron și-au văzut de drum, și au adunat pe toți bătrânii copiilor lui Israel.",
    "Aaron a istorisit toate cuvintele pe care le spusese Domnul lui Moise; și Moise a făcut semnele înaintea poporului.",
    "Poporul a crezut. Astfel au aflat că Domnul cercetase pe copiii lui Israel, că le văzuse suferința; și s-au plecat și s-au aruncat cu fața la pământ.",
  ],
}
