import type { BibleChapter, BibleUnit } from "./types.js"

const GENEZA_LEGACY_EXPLANATION_SOURCE =
  "Emanus legacy synthesis — Allen/Nolan editorial flow + biblical text/cross-references"
const GENEZA_REVIEW_SOURCE =
  "Emanus canonical exegesis — Genesis + WLC/biblical cross-references; Allen/Nolan editorial flow"
const HEBREW_WORD_SOURCE = "WLC-OSHB"

type GenezaUnitCorrection = {
  teaching: string
  forYourHeart?: string
}

type GenezaChapterCorrection = {
  title?: string
  summary?: string
  literaryContext?: string
  historicalContext?: string
  prayer?: string
  units: Record<string, GenezaUnitCorrection>
}

const GENEZA_REVIEW: Record<number, GenezaChapterCorrection> = {
  24: {
    historicalContext:
      "Juramantul cu mana sub coapsa este un gest solemn atestat in Geneza 24 si din nou in Geneza 47; simbolismul lui exact este discutat, de aceea nu il prezentam drept o formula al carei sens istoric ar fi sigur. Casatoria este negociata in cadrul familiei: Laban si Betuel raspund impreuna in versetul 50, iar mai tarziu fratele si mama cer o amanare; Rebeca insasi este chemata si intrebata daca vrea sa plece. Cele zece camile si darurile arata resursele casei lui Avraam, iar adapatul lor cere o munca reala, dar textul nu da litri, galeti sau durata. La final, Rebeca se acopera cu valul dupa ce afla cine este Isaac; gestul apartine cutumei si modestiei scenei, fara ca naratorul sa-i ofere o explicatie rituala universala.",
    units: {
      "geneza-24-1-9": {
        teaching:
          "Ia aminte cum incepe: DOMNUL il binecuvantase pe Avraam in toate. Si totusi batranul nu traieste ca si cum binecuvantarea ar insemna sa nu mai poarte raspundere pentru viitorul casei lui. Il cheama pe slujitorul cel mai batran, cel care administra tot ce avea, si ii incredinteaza o misiune care priveste direct continuarea fagaduintei prin Isaac.\n\nNumele slujitorului nu este dat in capitol. Multi il identifica cu Eliezer din Geneza 15:2, dar textul nu face identificarea, iar noi nu trebuie s-o transformam in fapt. Tocmai lipsa numelui a facut ca predicatorii crestini sa vada uneori in el o imagine frumoasa a slujitorului care nu se pune pe sine in centru. Asemanarea cu lucrarea Duhului Sfant poate sluji omiletic, dar naratorul nu spune ca slujitorul «este» Duhul Sfant.\n\nJuramantul cu mana sub coapsa este un gest solemn care apare din nou in Geneza 47:29. Exacta lui simbolistica este discutata; nu il numim «cel mai greu juramant» si nu pretindem mai mult decat ne da textul: Avraam cere un angajament solemn inaintea DOMNULUI.\n\nPrima limita este limpede: Isaac sa nu ia sotie dintre canaanitele in mijlocul carora locuieste Avraam. Avraam nu explica aici motivul printr-un discurs despre religia lor, deci nu punem in gura lui ce nu spune. Dar contextul canonic ulterior al legamantului arata ca problema casatoriilor cu popoarele Canaanului este legata de abaterea spre alti dumnezei, nu de o doctrina a puritatii rasiale. Rahav si Rut vor arata tocmai ca o femeie din afara poate intra prin credinta in poporul lui Dumnezeu.\n\nA doua limita este si mai repetata: Isaac sa nu fie dus inapoi in tara din care Avraam iesise. Chiar daca femeia refuza sa vina, slujitorul este dezlegat de juramant; Isaac nu trebuie readus acolo. Avraam tine mai tare de cuvantul lui Dumnezeu despre tara decat de dorinta fireasca de a rezolva casatoria cu orice pret.\n\nApoi vine increderea lui: DOMNUL, care l-a scos si i-a jurat fagaduinta tarii, va trimite ingerul Sau inaintea slujitorului. Credinta lui Avraam nu este optimism vag; argumentul lui este istoria fidelitatii lui Dumnezeu: Cel care m-a chemat si mi-a fagaduit va merge si inaintea acestei misiuni.\n\nSi observa libertatea femeii chiar in formularea juramantului: «daca femeia nu va vrea sa te urmeze». Capitolul nu descrie luarea unei femei cu forta. Mai tarziu, Rebeca va fi chemata si intrebata direct daca vrea sa plece.",
        forYourHeart:
          "Nu rezolva un lucru bun calcand peste o limita pe care Dumnezeu ti-a facut-o limpede. Credinta nu spune doar «Dumnezeu va purta de grija», ci si «nu ma intorc pe drumul din care El m-a scos»."
      },
      "geneza-24-10-14": {
        teaching:
          "Slujitorul ia zece camile, daruri si porneste spre cetatea lui Nahor. Face drumul, ajunge la fantana la vremea cand femeile ies sa scoata apa si apoi se roaga. Rugaciunea nu inlocuieste pasii pe care ii avea de facut, iar pasii nu inlocuiesc rugaciunea.\n\nEl spune: «DOMNUL, Dumnezeul stapanului meu Avraam». Nu numim aceasta o «mica lipsa» de credinta, ca si cum omul L-ar cunoaste numai prin religia altuia. Chiar in aceasta scena el se roaga direct DOMNULUI, cere indurare, iar mai tarziu se pleaca si se inchina. Formula identifica Dumnezeul legamantului cu Avraam si misiunea in care slujitorul se afla; textul nu o critica.\n\nSemnul cerut este foarte concret: fata care nu numai ca ii da lui de baut, ci se ofera sa adape si camilele, sa fie cea randuita pentru Isaac. Este o cerere extraordinara in aceasta povestire, nu o metoda biblica universala pentru alegerea sotului sau sotiei. Nu invatam din Geneza 24 sa-I stabilim lui Dumnezeu parole arbitrare — «daca face exact X, atunci acesta este omul».\n\nIn acelasi timp, semnul cerut nu este gol de continut moral. Raspunsul asteptat ar scoate la lumina disponibilitate, generozitate si harnicie fata de un strain si animalele lui. Textul nu ne spune cate galeti, cati litri sau cate ore ar fi trebuit pentru cele zece camile; nu avem nevoie sa umflam cifrele. Este suficient ce spune naratiunea: Rebeca alearga din nou la fantana si scoate apa pana cand toate camilele termina de baut.\n\n«Pe care ai randuit-o Tu» arata convingerea slujitorului ca aceasta casatorie nu trebuie construita numai prin calcul omenesc. El cere ca providenta lui Dumnezeu sa confirme drumul. Dar chiar el nu transforma primul indiciu intr-un verdict instantaneu: in versetul 21 o priveste in tacere ca sa vada daca DOMNUL ii facuse sau nu calatoria sa izbuteasca.",
        forYourHeart:
          "Roaga-te pentru calauzire, dar nu transforma rugaciunea intr-un joc de semne arbitrare. Cauta caracter, asculta Scriptura si lasa providenta lui Dumnezeu sa se confirme fara sa fortezi rezultatul."
      },
      "geneza-24-15-21": {
        teaching:
          "«Nu sfarsise el inca de vorbit» si Rebeca apare cu vadra pe umar. Naratiunea vrea sa simtim viteza raspunsului. Isaia 65:24 va folosi o formulare asemanatoare despre Dumnezeu care raspunde inainte ca poporul Sau sa termine de vorbit; este o trimitere canonica frumoasa, dar nu o promisiune ca fiecare rugaciune credincioasa va primi un raspuns vizibil inainte de ultimul cuvant.\n\nRebeca este chiar din familia cautata, dar slujitorul nu stie aceasta cand alearga sa-i ceara apa. Inainte sa afle genealogia, vede purtarea ei.\n\nEa nu face lucrul incet sau cu sila: textul repeta graba si alergarea. Ii da strainului sa bea si apoi, din proprie initiativa, se ofera sa scoata apa pentru toate camilele pana cand vor termina de baut. Nu stim volumul exact de apa si nu cronometram munca ei; stim ce vrea naratorul sa vedem — disponibilitatea de a continua pana la capat un serviciu greu pe care nu i-l ceruse nimeni.\n\nNu spunem nici ca «nimeni nu o vedea». Slujitorul o privea, oamenii lui erau in calatorie cu el, iar scena se petrecea la locul unde femeile veneau dupa apa. Aplicatia mai exacta este aceasta: Rebeca nu stia ca tocmai felul in care raspundea unei cereri obisnuite va deveni parte dintr-o schimbare uriasa a vietii ei. Caracterul se arata inainte ca omul sa stie ce usa poate deschide acea zi.\n\nSlujitorul, la randul lui, nu se grabeste sa proclame minunea. O priveste in tacere «ca sa vada daca DOMNUL facuse sa-i izbuteasca sau nu calatoria». Credinta lui nu exclude verificarea. Tocmai dupa o rugaciune cu un semn foarte precis, omul ramane atent la fapte pana cand tabloul se lamureste.",
        forYourHeart:
          "Nu stii ce zi obisnuita va scoate la lumina caracterul tau. Fa lucrul mic cu toata inima — si, cand crezi ca ai primit o calauzire, nu te teme sa o verifici in tacere inainte s-o proclami."
      },
      "geneza-24-22-27": {
        teaching:
          "Dupa ce camilele au terminat de baut, slujitorul ii da Rebecai podoabele si intreaba a cui fiica este si daca exista loc de gazduit. Abia atunci afla ca a ajuns chiar in ramura familiei lui Nahor si Milca. Purtarea pe care o vazuse si genealogia pe care o cauta se intalnesc in acelasi om.\n\nRebeca nu ofera numai gazduire, ci spune ca exista paie si nutret din belsug. Grija ei pentru camile continua, iar slujitorul primeste inca o confirmare ca a ajuns unde trebuia.\n\nReactia lui este imediata: isi pleaca capul si se inchina DOMNULUI. Multumirea nu este amanata pana la intoarcerea in Canaan. Cand omul vede clar o purtare de grija, este sanatos sa se opreasca si sa-L binecuvanteze pe Dumnezeu chiar acolo.\n\nEl Il lauda pe DOMNUL care nu Si-a parasit «hesed» si «emet» fata de Avraam. Hesed vorbeste despre bunatate loiala, iar emet despre adevar, stabilitate si credinciosie. Perechea devine importanta in limbajul Vechiului Testament. Ioan 1:14 spune despre Hristos ca este plin de «har si adevar»; crestinul poate auzi o rezonanta canonica intre aceste teme, dar nu pretindem ca expresia greceasca din Ioan este o traducere lexicala simpla si obligatorie a perechii din Geneza 24.\n\nApoi vine marturisirea: «DOMNUL m-a calauzit pe drum». Aici este una dintre cele mai frumoase lectii ale capitolului. Slujitorul nu primise de la inceput numele fetei, adresa casei si desfasurarea fiecarei ore. A pornit pe baza juramantului si a increderii lui Avraam, s-a rugat pe drum si acum, privind inapoi la pasii facuti, recunoaste calauzirea.\n\nNu facem din aceasta o lege absoluta ca Dumnezeu «aproape intotdeauna» calauzeste numai dupa ce pornesti. Uneori Scriptura spune sa astepti; alteori spune sa mergi. Lectia acestui capitol este mai precisa: cand Dumnezeu ti-a facut deja datoria limpede, nu cere sa vezi fiecare pas viitor inainte sa faci primul pas de ascultare.",
        forYourHeart:
          "Calauzirea nu inseamna sa stii tot drumul dinainte. Cand datoria de azi este limpede, fa pasul de azi; iar cand vezi mana lui Dumnezeu, opreste-te si multumeste-I."
      },
      "geneza-24-28-33": {
        teaching:
          "Rebeca alearga acasa, iar Laban alearga la fantana dupa ce textul spune ca vazuse veriga si bratarile si auzise relatarea surorii sale. Detaliul este deliberat, dar nu ne autorizeaza sa spunem ca aurul a fost singurul lui motiv. Naratorul ne spune ce a vazut; motivatia completa a inimii lui nu este expusa.\n\nTotusi, cititorul care il va intalni pe Laban in capitolele despre Iacov are motive sa tina minte acest prim detaliu. Mai tarziu chiar fiicele lui vor spune ca tatal lor le-a tratat ca pe niste straine si «ne-a vandut», iar Iacov va spune ca Laban i-a schimbat plata de multe ori. Este legitim sa vedem un tipar al interesului material, dar nu este legitim sa transformam fiecare cuvant ospitalier al lui Laban in prefacatorie demonstrata.\n\nSlujitorului i se ofera mancare, dar el spune: «nu mananc pana nu voi spune ce am de spus». Aici explicatia poate ramane taioasa: omul pune misiunea stapanului inaintea confortului imediat. Legatura cu Ioan 4 — «mancarea Mea este sa fac voia Celui ce M-a trimis» — este o aplicatie canonica potrivita, nu o afirmatie ca slujitorul ar fi fost un tip profetic explicit al lui Hristos.\n\nNu stim exact cat de obosit era, cati kilometri facuse in acea zi sau daca el insusi scosese apa. Nu avem nevoie de asemenea decor inventat. Masa este in fata lui si el refuza sa se aseze pana nu isi implineste mai intai sarcina cu care venise.\n\nNici nu spunem ca «a cerut voie ca sa nu strice cinstea gazdelor». Textul ne da pur si simplu hotararea lui: mai intai mesajul, apoi mancarea. Aceasta este destul pentru cercetare.",
        forYourHeart:
          "Poti vorbi despre Dumnezeu si totusi sa iubesti aurul; poti fi obosit si totusi sa pui ascultarea inaintea confortului. Care dintre cele doua linii se vede mai limpede in tine?"
      },
      "geneza-24-34-49": {
        teaching:
          "Slujitorul isi incepe discursul cu identitatea care conteaza pentru misiune: «eu sunt robul lui Avraam». Apoi povesteste binecuvantarea stapanului, nasterea lui Isaac, juramantul, drumul, rugaciunea si intalnirea cu Rebeca.\n\nO mare parte a capitolului este astfel repovestita, dar nu «aproape cuvant cu cuvant» in fiecare amanunt. Naratorul ne lasa chiar sa vedem o diferenta interesanta: in relatarea initiala, versetele 22–23 pun podoabele inaintea intrebarii despre familie; in discursul din versetul 47, slujitorul spune ca a intrebat a cui fiica este si apoi i-a pus podoabele. Aceasta nu este o problema care trebuie ascunsa, ci felul firesc in care o relatare poate reordona amanuntele fara sa schimbe substanta evenimentului.\n\nDe aceea renuntam la predica «nu schimba nimic, nu infrumuseteaza nimic». Textul insusi nu sustine o asemenea afirmatie. Lucrul impresionant este altul: in orice ordine povesteste amanuntele, slujitorul pune providenta DOMNULUI in centru si isi expune deschis mandatul. Familia poate intelege ce i-a cerut Avraam, ce s-a rugat slujitorul si ce s-a intamplat la fantana.\n\nEl mai adauga un amanunt pe care naratiunea anterioara nu-l rostise explicit: rugaciunea fusese «in inima mea». Dumnezeu nu are nevoie ca o rugaciune sa fie auzita de oamenii din jur ca s-o auda El. Ana va sta mai tarziu inaintea DOMNULUI miscandu-si buzele fara glas, iar Dumnezeu ii va cunoaste cererea.\n\nLa sfarsit slujitorul nu manipuleaza familia printr-o poveste misterioasa. Cere raspuns limpede: daca vor sa arate bunatate si credinciosie, sa spuna; daca nu, sa spuna si aceasta, pentru ca el sa stie incotro sa se indrepte.\n\nEste o lectie buna pentru orice lucrare facuta in Numele lui Dumnezeu: providenta nu are nevoie de exagerarea marturiei. Spune ce s-a intamplat, recunoaste mana lui Dumnezeu si nu falsifica amanuntele ca sa fortezi un «da».",
        forYourHeart:
          "Nu infrumuseta marturia ca sa-L faci pe Dumnezeu sa para mai convingator. Adevarul spus limpede este suficient pentru Dumnezeul care a lucrat cu adevarat."
      },
      "geneza-24-50-61": {
        teaching:
          "Laban si Betuel raspund: «de la DOMNUL vine lucrul acesta; noi nu-ti putem spune nici rau, nici bine». Ei recunosc in desfasurarea povestita o providenta pe care nu vor s-o contrazica, iar slujitorul se inchina din nou.\n\nDupa daruri, masa si noapte, slujitorul vrea sa plece imediat. Familia cere ca fata sa mai ramana «zile sau zece» — formularea ebraica permite intelegerea unei scurte perioade, posibil zece zile. Nu trebuie sa dramatizam cu o distanta exacta de o mie de kilometri si nici sa afirmam ca familia stia ca Rebeca «nu se va mai intoarce niciodata». Despartirea era mare chiar fara aceste adaosuri.\n\nApoi vine un detaliu care trebuie pastrat cu toata greutatea lui: o cheama pe Rebeca si o intreaba «vrei sa te duci cu omul acesta?» Iar ea raspunde: «ma voi duce». Capitolul, care spusese deja in versetul 8 ca femeia putea sa nu vrea sa urmeze slujitorul, consemneaza acum consimtamantul ei explicit. Nu avem nevoie de afirmatia antropologica larga ca «in lumea aceea fetele se dadeau, nu se intrebau» ca sa vedem ce face textul aici.\n\nHotararea Rebecai cere credinta si curaj: pleaca din casa ei cu un slujitor spre un barbat pe care nu-l intalnise. Exista o paralela frumoasa cu Avraam, care fusese chemat sa plece din tara si din casa rudeniei lui. Dar nu o numim «a doua persoana din Geneza care pleaca pe baza unui cuvant»; cartea are si alte plecari, iar numerotarea omiletica nu ne ajuta.\n\nBinecuvantarea familiei este insa remarcabil de apropiata de fagaduinta de la Moria: mii de zeci de mii si samanta care stapaneste poarta vrajmasilor. Fie ca rudele intelegeau sau nu intreaga greutate a acestor cuvinte, naratorul le aseaza astfel incat cititorul sa auda ecoul lui Geneza 22:17. Rebeca intra in familia prin care fagaduinta va merge mai departe.\n\nNu transformam insistenta slujitorului de a pleca imediat intr-o porunca universala de a refuza orice «zece zile» cand cineva crede ca Dumnezeu l-a calauzit. In aceasta poveste, drumul lui trebuie dus la capat; in viata noastra, graba trebuie judecata tot prin Scriptura, intelepciune si caracter, nu prin imitarea mecanica a unei scene.",
        forYourHeart:
          "Cand Dumnezeu iti face chemarea limpede, raspunde cu libertate si credinta — dar nu confunda presiunea omeneasca sau graba ta cu vocea Lui."
      },
      "geneza-24-62-67": {
        teaching:
          "Isaac se afla in Negev, in regiunea Beer-Lahai-Roi, fantana legata de intalnirea Agarei cu Dumnezeul care vede. Geneza 25:11 va spune mai tarziu ca Isaac a locuit langa Beer-Lahai-Roi. Este o legatura literara frumoasa, dar textul nu ne spune ca Isaac isi alesese locuinta acolo tocmai fiindca stia istoria Agarei.\n\nVersetul 63 foloseste un verb ebraic rar, lasuach, al carui sens este discutat. Traditia il reda adesea «a medita», iar alte propuneri sunt «a se plimba», «a se ruga» sau chiar «a se tangui». De aceea nu construim o doctrina pe certitudinea ca Isaac era atunci in rugaciune sau in doliu. Stim sigur numai ca iesise pe camp spre seara si atunci a ridicat ochii si a vazut camilele.\n\nContextul ne spune ca pierderea Sarei il apasa inca, pentru ca ultimul verset spune ca prin Rebeca Isaac a fost mangaiat dupa moartea mamei lui. Din datele Genezei rezulta ca trecusera aproximativ trei ani: Sara moare la 127 de ani, Isaac avea 37, iar Geneza 25:20 spune ca Isaac avea 40 cand a luat-o pe Rebeca. Durerea nu este prezentata ca ceva ce trebuia «sa depaseasca» repede.\n\nRebeca il vede, intreaba cine este, iar cand afla ca este stapanul slujitorului isi ia valul si se acopera. Gestul tine de intalnirea lor si de cutuma de modestie, dar naratorul nu explica valul ca pe un «semn universal al miresei» si nu construim de aici o regula vestimentara pentru nunti.\n\nSlujitorul ii povesteste lui Isaac «toate lucrurile pe care le facuse». Aceasta inchide misiunea printr-o dare de seama. Nu stim daca repeta pentru a treia oara fiecare amanunt al fantanii; stim ca nu pastreaza pentru sine povestea calauzirii.\n\nApoi vin cuvintele simple: Isaac o ia pe Rebeca, ea devine sotia lui si el o iubeste. Este prima afirmatie explicita din Geneza ca un sot isi iubeste sotia, iar despre Isaac nu este consemnata o alta sotie sau concubina. Este o casnicie care, spre deosebire de multe altele din istoria patriarhilor, ramane in naratiune intre un singur barbat si o singura femeie.\n\nOrdinea «a luat-o / a fost sotia lui / a iubit-o» ne permite sa observam ca dragostea este marturisita in interiorul casatoriei lor. Nu o transformam insa intr-o regula potrivit careia dragostea romantica trebuie sa apara numai dupa casatorie. Textul descrie povestea lor; nu emite aici o lege universala despre ordinea sentimentelor.\n\nSi ultimul rand este bland: Isaac este mangaiat dupa mama lui. Rebeca nu o inlocuieste pe Sara, iar casatoria nu este un tratament magic pentru doliu. Totusi, Dumnezeu lucreaza in poveste astfel incat, dupa pierdere, in viata lui Isaac intra o relatie reala de iubire si mangaiere.",
        forYourHeart:
          "Nu forta un «semn» si nu transforma fiecare coincidenta intr-o voce. Cauta o calauzire care poate fi spusa in lumina adevarului, verificata prin caracter si primita fara constrangere."
      }
    }
  },
  34: {
    title: "Geneza 34 — Dina, viclesugul si violenta",
    summary:
      "Dina este agresata sexual de Sihem. Hamor si Sihem cauta apoi o casatorie si o alianta intre comunitati, iar fiii lui Iacov raspund printr-o inselaciune care foloseste taierea imprejur drept capcana. In a treia zi Simeon si Levi ucid toti barbatii cetatii, ceilalti fii jefuiesc locul si iau femeile si copiii captivi. Capitolul nu transforma violenta initiala intr-o scuza pentru masacru; iar Iacov va condamna mai tarziu mania si cruzimea lui Simeon si Levi in Geneza 49.",
    literaryContext:
      "Capitolul urmeaza asezarii familiei lui Iacov langa Sihem. Textul nu spune ca agresarea Dinei a fost o pedeapsa pentru locul unde s-a oprit Iacov si nu folosim geografia ca sa invinovatim victima. In familie reapare tema viclesugului, cunoscuta deja din istoria lui Iacov, dar naratiunea nu spune ca pacatul tatalui i-a programat inevitabil pe fii sa faca acelasi rau; fiecare ramane raspunzator pentru alegerea lui. Geneza 49 va reveni explicit asupra lui Simeon si Levi: Iacov numeste sabiile lor unelte de violenta si blestema mania lor. In capitolul urmator Dumnezeu il cheama pe Iacov la Betel, iar casa indeparteaza dumnezeii straini.",
    historicalContext:
      "Poarta cetatii este locul in care Hamor si Sihem isi prezinta propunerea barbatilor comunitatii. Versetul 23 foloseste explicit argumentul economic: turmele, averile si vitele familiei lui Iacov «nu vor fi oare ale noastre?». Aceasta arata felul in care conducatorii vand intelegerea cetatii, fara sa dovedeasca motivul interior al fiecarui barbat care consimte. Taierea imprejur era semnul legamantului dat lui Avraam; textul spune ca in a treia zi barbatii inca sufereau, iar Simeon si Levi aleg tocmai acel moment pentru atac. Nu spunem mai mult decat textul, ca si cum fiecare barbat ar fi fost complet neputincios. Dina este scoasa din casa lui Sihem in versetul 26, ceea ce arata ca se afla acolo la momentul atacului; naratiunea nu ne spune toate conditiile in care fusese tinuta intre agresiune si acel moment.",
    units: {
      "geneza-34-1-4": {
        teaching:
          "Sa ne oprim aici cu multa grija. Dina, fiica Leei si a lui Iacov, iese sa le vada pe fetele tarii. Naratiunea nu o mustra pentru iesirea ei si nu leaga agresiunea de o vina a ei. A spune ca «n-ar fi trebuit sa iasa» inseamna sa mutam asupra victimei o raspundere pe care textul o pune asupra lui Sihem.\n\nVerbele sunt grele: Sihem o ia, se culca cu ea si o «umileste/necinstește». Restul capitolului numeste fapta o «miselie» care nu trebuia facuta. Nu o diluam intr-o poveste de dragoste aparuta prost; inceputul relatiei este o agresiune sexuala.\n\nApoi textul spune ca sufletul lui Sihem se lipeste de Dina, ca o iubeste si ca ii vorbeste inimii. Tocmai juxtapunerea este tulburatoare: afectiunea pe care o declara dupa aceea nu sterge raul pe care l-a facut. Omul poate numi ceva «iubire» si totusi sa fi trecut peste vointa si demnitatea celuilalt.\n\nSihem ii cere tatalui sau s-o ia pe Dina pentru el ca sotie. Naratiunea nu consemneaza niciun cuvant al Dinei in tot capitolul. Este mai exact sa spunem aceasta decat sa afirmam ca stim ca nimeni n-a intrebat-o vreodata in afara scenei relatate. Ceea ce stim este ca cititorului nu i se da vocea ei, in timp ce barbatii vorbesc, negociaza si apoi ucid in jurul ranii ei.\n\nAceasta tacere literara ne obliga sa nu umplem noi golul impotriva ei. Cel ranit nu devine vinovat fiindca altii vorbesc mai tare despre ce i s-a intamplat. Iar o declaratie ulterioara de iubire din partea agresorului nu rescrie consimtamantul care a lipsit la inceput.",
        forYourHeart:
          "Nu muta vina de la cel care a fortat la cel care a fost ranit. Si nu numi «iubire» un sentiment care cere sa uitam raul facut celuilalt."
      },
      "geneza-34-5-12": {
        teaching:
          "Iacov afla si tace pana se intorc fiii de la pasune. Textul ne spune faptul, nu motivul. Nu stim daca tacerea lui a fost prudenta, soc, frica sau neputinta; de aceea nu o transformam nici in virtute, nici in dovada sigura de indiferenta. Ceea ce putem judeca mai tarziu este ceea ce el chiar spune si face.\n\nFiii se intorc, aud si se manie foarte tare, pentru ca Sihem facuse o «miselie in Israel». Mania lor are un obiect real: sora lor fusese agresata. Dar existenta unei nedreptati reale nu va face automat dreapta orice razbunare pe care o vor alege.\n\nHamor incepe negocierea vorbind despre atasamentul fiului sau si propune casatoria, incuscrirea, locuirea si comertul comun. In discursul consemnat nu apare o marturisire a raului si nici o cerere de iertare. Nu pretindem sa stim tot ce simtea Hamor in inima; observam ceea ce naratorul a ales sa ne lase in cuvintele lui.\n\nSihem ofera o zestre si daruri oricat de mari i s-ar cere. Intr-o lume in care casatoriile implicau negocieri intre familii, o asemenea oferta are un cadru social inteligibil. Dar nici o suma nu poate transforma agresiunea deja comisa intr-o fapta care n-a existat. Repararea nu incepe prin a cumpara tacerea sau accesul la persoana ranita.\n\nSihem continua sa ceara: «dati-mi fata de nevasta». Chiar daca textul spune ca o iubeste, dorinta lui nu ii da drept asupra ei. Geneza 24 tocmai consemnase explicit intrebarea adresata Rebecai — «vrei sa te duci?» — iar aici naratiunea nu ne da un asemenea raspuns al Dinei.\n\nAplicatia trebuie tinuta exact: o familie sau o comunitate nu face dreptate cand negociaza numai reputatie, bani si aranjamente, fara sa numeasca raul si fara sa tina cont de persoana ranita.",
        forYourHeart:
          "O invoiala buna nu tine locul adevarului, iar banii nu pot cumpara inapoi consimtamantul care a fost incalcat."
      },
      "geneza-34-13-17": {
        teaching:
          "Naratorul pune verdictul inainte sa auzim planul: fiii lui Iacov raspund «cu viclesug». Durerea lor este reala, dar metoda aleasa este inselaciunea. Scriptura nu ne cere sa alegem intre a condamna agresiunea lui Sihem si a condamna viclesugul fratilor; le condamnam pe amandoua.\n\nUnealta capcanei este taierea imprejur, semnul legamantului dat lui Avraam. Tocmai aceasta face fapta fratilor atat de grava: iau un semn sfant al apartenentei la legamant si il folosesc ca mijloc tactic pentru a face niste barbati vulnerabili atacului. Un adevar religios rostit cu scop de inselare nu devine sfant prin vocabularul lui.\n\nEi spun ca nu-si pot da sora unui netaiat imprejur si propun ca toti barbatii cetatii sa devina ca ei. Familia lui Avraam avea deja o constiinta a distinctiei legamantului — Geneza 24 aratase grija ca Isaac sa nu ia o canaanita — dar aici fiii nu urmaresc o convertire reala si nici fidelitatea legamantului. Naratorul ne-a spus scopul: vorbesc cu viclesug.\n\nPromisiunea «vom fi un singur popor» este parte din capcana. Nu trebuie sa construim aici intreaga doctrina ulterioara a separarii Israelului ca si cum toate legile lui Moise ar fi fost deja rostite. Este suficient sa vedem falsitatea concreta: fratii promit o unire pe care nu intentioneaza s-o respecte.\n\nLa final spun ca, daca barbatii nu accepta circumcizia, «ne vom lua fata si vom pleca». Versetul 26 va arata ca Dina era in casa lui Sihem cand fratii o scot de acolo. Aceasta da planului lor o urgenta reala, dar urgenta nu transforma inselaciunea si masacrul de mai tarziu in dreptate.",
        forYourHeart:
          "Nu imbraca razbunarea in cuvinte de legamant. Un lucru sfant folosit ca unealta pentru minciuna nu sfinteste minciuna — o face mai cumplita."
      },
      "geneza-34-18-24": {
        teaching:
          "Hamor si Sihem duc propunerea la poarta cetatii. Discursul incepe cu pacea, comertul si casatoriile, apoi ajunge la argumentul economic foarte explicit: «turmele lor, averile lor si toate vitele lor nu vor fi oare ale noastre?» Textul ne lasa sa vedem cum avantajul material este folosit pentru a castiga acordul comunitatii.\n\nNu spunem ca stim ca fiecare barbat s-a taiat imprejur numai din lacomie. Naratiunea nu deschide inimile tuturor. Spunem ceea ce putem demonstra: conducatorii vand intelegerea si prin promisiunea castigului, iar barbatii cetatii accepta.\n\nAstfel toti barbatii primesc in trup semnul legamantului lui Avraam fara ca naratiunea sa descrie credinta lui Avraam in ei. Semnul exterior poate fi primit pentru un motiv strain de Dumnezeul semnului. Aceasta este o aplicatie pe care restul Scripturii o va face explicit: circumcizia trupului fara ascultarea inimii nu este tinta legamantului.\n\nDar nici fratii Dinei nu sunt mai curati fiindca ei cunosc sensul semnului. Tocmai ei il folosesc cu intentie ucigasa. De o parte este o comunitate convinsa prin avantaj; de cealalta parte, oameni ai familiei legamantului care exploateaza semnul pentru o capcana. Religia exterioara nu curata nici lacomia, nici razbunarea.\n\nHotararea colectiva nu transforma planul intr-un lucru drept. Multimea poate consimti la o intelegere pentru motive gresite, iar mai grav aici este ca oamenii consimt fara sa stie ca propunerea fusese facuta cu viclesug.",
        forYourHeart:
          "Un semn sfant pe trup nu poate inlocui o inima dreapta. Intreaba-te nu doar ce practica religioasa ai primit, ci pentru ce o porti si cui ii apartine inima ta."
      },
      "geneza-34-25-29": {
        teaching:
          "A treia zi, «pe cand sufereau inca», Simeon si Levi isi iau sabiile si intra in cetatea care se credea in siguranta. Alegerea momentului arata premeditare: ei asteapta slabirea produsa de circumcizie si lovesc atunci. Nu este o izbucnire de o secunda, ci un atac pregatit.\n\nTextul ii numeste «fratii Dinei». Simeon, Levi si Dina sunt toti copiii Leei, deci sunt frati buni, dar naratorul nu ne spune de ce alege aici aceasta eticheta; cel mai sigur este ca ea tine in fata cititorului legatura lor directa cu victima pe care pretind ca o razbuna.\n\nEi ucid toti barbatii, inclusiv pe Hamor si Sihem, si o scot pe Dina din casa lui Sihem. Atacul depaseste astfel cu mult pedepsirea agresorului individual. Barbati carora capitolul nu le atribuie agresiunea lui Sihem mor impreuna cu el.\n\nMai tarziu, in Geneza 49, Iacov va judeca fapta fara ambiguitate: sabiile lui Simeon si Levi sunt «unelte de silnicie», iar mania si furia lor sunt blestemate pentru cruzimea lor. Nu este un citat direct al lui Dumnezeu, dar este verdictul patriarhului pastrat de Scriptura asupra violentei lor.\n\nFaptul ca din Levi va veni ulterior o semintie pusa deoparte pentru slujire nu reabiliteaza masacrul de la Sihem. Mai mult, preotia lui Aaron este randuita in Exod 28 inaintea episodului vitelului de aur din Exod 32. Nu construim deci o teologie in care sabia lui Levi ar transforma retroactiv violenta din Geneza 34 intr-o ravna pe care Dumnezeu o rasplateste.\n\nDupa ucidere, ceilalti fii ai lui Iacov jefuiesc cetatea, iau turmele, bunurile, femeile si copiii. Aceasta creeaza victime noi si extinde violenta asupra unor oameni care nu sunt identificati cu fapta lui Sihem. Nu spunem ca fratilor le-au facut femeilor si copiilor «exact acelasi lucru» care i se facuse Dinei — textul nu spune ca i-au agresat sexual. Spunem lucrul real si destul de grav: razbunarea lor nu s-a oprit la agresor, ci a ajuns la ucidere colectiva, jaf si captivitate.\n\nDina este scoasa din casa lui Sihem, dar rana ei nu poate fi anulata prin numarul mortilor. Dreptatea si razbunarea nu sunt sinonime; o cauza dreapta poate fi folosita pentru o fapta pe care Scriptura o condamna.",
        forYourHeart:
          "Nu lasa o nedreptate reala sa-ti dea impresia ca orice reactie a ta devine dreapta. Mania pentru un rau poate ajunge ea insasi un rau pe care Dumnezeu il va judeca."
      },
      "geneza-34-30-31": {
        teaching:
          "La sfarsit Iacov ii confrunta pe Simeon si Levi, dar cuvintele lui din acest moment se concentreaza pe primejdia creata pentru casa lui: «m-ati facut urat», «ei se vor strange impotriva mea», «voi fi nimicit, eu si casa mea». Este legitim sa observam cat de mult domina frica de consecinte discursul lui imediat.\n\nNu este insa corect sa spunem ca Iacov, in toata viata lui, nu va avea nimic moral de spus despre fapta lor. Geneza 49 arata contrariul: la capatul vietii, el numeste sabiile lor unelte de violenta si blestema mania si cruzimea lor. Capitolul 34 ne arata reactia lui imediata; capitolul 49 ne da evaluarea lui ulterioara si mai profunda.\n\nFiii raspund: «se cuvenea oare sa se poarte cu sora noastra cum se poarta cu o curva?» Intrebarea lor tine in fata raul initial: nu, ceea ce i s-a facut Dinei nu trebuia facut. Durerea lor nu este imaginara. Dar o intrebare dreapta nu face dreapta o razbunare nedreapta. Cele doua adevaruri trebuie tinute impreuna.\n\nCapitolul nu consemneaza nicio rugaciune, niciun altar si nicio consultare a lui Dumnezeu inaintea deciziilor care duc la inselaciune si masacru. Nu numim aceasta «singurul capitol din viata lui Iacov in care nimeni nu Il cauta» fara sa verificam fiecare alta scena si nu spunem simplist ca acesta este unicul motiv pentru care totul se prabuseste. Dar absenta consultarii lui Dumnezeu este un contrast puternic cu capitolul urmator.\n\nPrimul cuvant din Geneza 35 este chemarea lui Dumnezeu: «scoala-te, suie-te la Betel». Iacov isi cheama apoi casa sa scoata dumnezeii straini, sa se curateasca si sa-si schimbe hainele. Dupa un capitol in care familia a actionat din rana, frica, viclesug si manie, drumul inapoi incepe cu intoarcerea la locul altarului si cu curatirea casei.",
        forYourHeart:
          "Poti avea dreptate despre raul care ti s-a facut si totusi sa pacatuiesti in felul in care raspunzi. Du rana la Dumnezeu inainte ca mania sa-ti aleaga sabia."
      }
    },
    prayer:
      "Doamne, da-ne curajul sa numim violenta violenta si sa nu aruncam vina asupra celui ranit. Pazeste-ne, in acelasi timp, sa nu transformam durerea dreapta in viclesug, ura si razbunare. Invata-ne sa cautam dreptatea fara sa facem victime noi, sa nu folosim lucrurile Tale sfinte drept arme pentru planurile noastre si sa ne intoarcem la Tine inainte ca mania sa ne aleaga calea. Amin."
  }
}

function normalizeGenezaUnit(unit: BibleUnit, chapterNumber: number): BibleUnit {
  const correction = GENEZA_REVIEW[chapterNumber]?.units[unit.id]
  return {
    ...unit,
    teaching: correction?.teaching ?? unit.teaching,
    forYourHeart: correction?.forYourHeart ?? unit.forYourHeart,
    explanationKind: unit.explanationKind ?? "exposition",
    explanationSource:
      unit.explanationSource ??
      (GENEZA_REVIEW[chapterNumber] ? GENEZA_REVIEW_SOURCE : GENEZA_LEGACY_EXPLANATION_SOURCE),
    wordSource:
      unit.words && unit.words.length > 0
        ? unit.wordSource ?? HEBREW_WORD_SOURCE
        : unit.wordSource,
  }
}

export function normalizeGenezaChapter(chapter: BibleChapter): BibleChapter {
  const correction = GENEZA_REVIEW[chapter.number]
  return {
    ...chapter,
    title: correction?.title ?? chapter.title,
    summary: correction?.summary ?? chapter.summary,
    literaryContext: correction?.literaryContext ?? chapter.literaryContext,
    historicalContext: correction?.historicalContext ?? chapter.historicalContext,
    prayer: correction?.prayer ?? chapter.prayer,
    units: chapter.units.map((unit) => normalizeGenezaUnit(unit, chapter.number)),
  }
}
