import type { BibleChapter, BibleUnit } from "./types.js"

const REVIEW_SOURCE =
  "Emanus canonical exegesis — Geneza 38 + WLC/biblical cross-references; Allen/Nolan editorial flow"
const HEBREW_WORD_SOURCE = "WLC-OSHB"

type UnitCorrection = {
  teaching: string
  forYourHeart?: string
}

const UNIT_CORRECTIONS: Record<string, UnitCorrection> = {
  "geneza-38-1-11": {
    teaching:
      "Capitolul se deschide spunand ca Iuda «s-a coborat» de la fratii lui si s-a dus spre Adulam. Nu transformam verbul geografic intr-un verdict automat ca fiecare pas fizic in jos inseamna decadere spirituala si nici nu pretindem ca stim ca Iuda a plecat fiindca «nu mai putea sta acasa» dupa vanzarea lui Iosif. Naratiunea nu ne da motivul plecarii lui.\n\nTotusi, contrastul literar cu familia legamantului este real: Iuda se leaga de un adulamit si isi ia o femeie canaanita. Avraam si Isaac avusesera o grija explicita ca sotia fiului fagaduintei sa nu fie luata dintre canaanite. Nu spunem ca Iuda incalca aici o porunca rostita direct lui, dar povestirea il aseaza intr-o directie diferita de grija patriarhilor pentru linia familiei.\n\nDespre Er textul spune numai ca era rau inaintea DOMNULUI si ca DOMNUL l-a omorat. Nu ni se spune pacatul lui si nu il inventam.\n\nLa Onan, naratorul ne spune insa motivul. El stia ca samanta nu avea sa fie socotita a lui si, tocmai ca sa nu ridice urmas fratelui sau, impiedica in mod repetat conceptia cand se culca cu Tamar. De aceea nu folosim episodul ca pe un text generic despre orice act sexual prin care samanta nu ajunge la conceptie; problema declarata este refuzul calculat al datoriei fata de fratele mort si fata de Tamar, in timp ce Onan isi insuseste relatia fara responsabilitatea pentru care fusese chemat.\n\nIuda ii spune apoi Tamarei sa ramana vaduva in casa tatalui ei pana creste Sela. Naratorul ne dezvaluie frica lui: «sa nu moara si el ca fratii lui». Textul nu spune direct ca Iuda o considera pe Tamar vinovata de moartea lor, dar frica lui il face sa o tina departe de Sela. Mai tarziu, cand Sela este mare si Tamar tot nu ii este data, devine limpede ca promisiunea nu a fost implinita.\n\nEste mai exact sa spunem ca Iuda a retinut de la Tamar ceea ce ii fagaduise decat sa pretindem ca stim ca, din prima clipa, el formulase constient o minciuna pe care nu intentiona niciodata s-o tina. Rezultatul pentru Tamar ramane grav: este trimisa inapoi in casa tatalui ei sub statutul de vaduva si asteapta un fiu care ajunge la varsta potrivita fara ca Iuda sa-si indeplineasca angajamentul.\n\nDeuteronom 25 va formula mai tarziu datoria leviratului pentru Israel. Geneza 38 arata ca obiceiul de a ridica samanta fratelui mort exista deja in lumea familiei lui Iuda, dar nu trebuie sa importam retroactiv fiecare detaliu juridic al legii mozaice in aceasta scena.",
    forYourHeart:
      "Nu folosi frica pentru a tine un om slab suspendat intr-o promisiune pe care tu nu o implinesti. Daca ai o datorie, spune adevarul si poarta-ti raspunderea."
  },
  "geneza-38-12-19": {
    teaching:
      "Dupa moartea sotiei lui Iuda si dupa zilele de jale, Iuda urca la Timna pentru tunsul oilor. Tamar afla traseul lui si vede ceea ce naratorul spune explicit: Sela crescuse, iar ea nu ii fusese data de sotie. Acesta este motivul narativ sigur din spatele actiunii ei.\n\nNu trebuie sa-i atribuim Tamarei toate motivele pe care ni le putem imagina — ca singura ei preocupare era painea la batranete, ca nu voia deloc siguranta materiala sau ca era «libera in fapt» sa mearga la orice alt barbat. Statutul ei in familie era tocmai problema. Putem spune ceea ce textul arata: Iuda nu isi implinise angajamentul, iar Tamar actioneaza pentru a obtine urmas in acea linie.\n\nEa isi schimba hainele, isi acopera fata si se aseaza pe drumul spre Timna. Iuda o considera prostituata si initiaza raportul sexual. Faptul ca ea il insala asupra identitatii nu il obliga pe Iuda sa caute o prostituata; aceasta alegere este a lui. Tot asa, faptul ca Iuda pacatuieste nu transforma planul Tamarei intr-o metoda pe care Scriptura o porunceste altora.\n\nDar trebuie sa fim mai atenti decat formula simpla «amandoi au facut la fel de rau». Verdictul lui Iuda din versetul 26 va spune explicit ca Tamar este «mai dreapta / mai in drept» decat el, tocmai fiindca el nu i-o daduse lui Sela. Naratiunea trateaza actiunea ei in lumina nedreptatii facute de Iuda, nu ca pe o aventura sexuala echivalenta moral cu a lui.\n\nZalogul cerut — pecetea, snurul si toiagul — functioneaza ca obiecte personale prin care Iuda va putea fi recunoscut. Pecetile erau folosite pentru marcarea/autentificarea unui act, dar nu le numim simplist «cartea lui de identitate» si nu pretindem ca fiecare dintre cele trei obiecte avea o functie juridica fixa demonstrata aici. Naratiunea are nevoie de un lucru mai simplu: Tamar obtine obiecte pe care Iuda insusi le va recunoaste ca ale lui.\n\nExista si un ecou literar puternic al iedului. In Geneza 27, Iacov fusese implicat intr-o inselare legata de iezi; in Geneza 37, Iuda si fratii lui folosesc sangele unui tap ca sa-l insele pe Iacov cu haina lui Iosif; acum Iuda promite un ied intr-o scena in care el insusi nu recunoaste persoana din fata lui. Putem observa ironia literara fara sa afirmam ca Dumnezeu a orchestrat mecanic fiecare amanunt drept represalie.",
    forYourHeart:
      "Pacatul altuia impotriva ta nu sfinteste automat orice metoda prin care incerci sa-ti faci dreptate. Dar nici nu lasa vina celui puternic sa fie ascunsa in spatele reactiei celui nedreptatit."
  },
  "geneza-38-20-23": {
    teaching:
      "Iuda trimite iedul prin Hira ca sa recupereze zalogul. Textul nu ne spune de ce nu merge el personal, deci nu spunem ca rusinea l-a facut sigur sa-si trimita prietenul.\n\nHira intreaba de «prostituata cultica» de la drum, iar oamenii locului spun ca acolo nu fusese o asemenea femeie. Aceasta nu este dovada ca ei cunosteau identitatea Tamarei sau ca o verificasera pe femeia deghizata; cititorul stie deja cine fusese. Detaliul arata doar ca Hira nu poate gasi persoana pe care Iuda credea ca o intalnise.\n\nApoi Iuda spune sa pastreze femeia zalogul «ca sa nu ne facem de ras» si invoca faptul ca el a trimis iedul. Cuvintele lui arata limpede preocuparea pentru rusinea publica a tranzactiei. Este o cercetare puternica, dar nu ne da voie sa afirmam ca in inima lui nu exista absolut nici o constiinta a pacatului. Judecam ce rosteste, nu fiecare gand pe care nu-l auzim.\n\nContrastul ramane ascutit: Iuda este dispus sa piarda pecetea, snurul si toiagul ca sa nu devina obiect de batjocura. Omul poate ajunge sa se teama mai mult de expunerea pacatului decat de pacatul insusi. Aceasta este o aplicatie canonica sanatoasa, atata vreme cat nu o transformam intr-un raport psihologic complet despre Iuda.\n\nNu spunem nici ca orice pacat ascuns va fi expus public in viata aceasta. Scriptura spune ceva mai sigur si mai grav: nimic nu este ascuns de Dumnezeu, iar judecata Lui va aduce la lumina lucrurile ascunse. In cazul lui Iuda, tocmai obiectele pe care le lasase ca zalog vor face adevarul imposibil de negat.",
    forYourHeart:
      "Temerea de rusine nu este acelasi lucru cu pocainta. Nu intreba numai «cum sa nu se afle?», ci «ce vede deja Dumnezeu si ce trebuie sa marturisesc?»."
  },
  "geneza-38-24-26": {
    teaching:
      "Dupa aproximativ trei luni, Iuda aude ca Tamar este insarcinata si reactioneaza cu o severitate socanta: «scoateti-o afara ca sa fie arsa». Textul nu ne spune pe ce cod juridic precis isi intemeiaza sentinta si nu avem voie sa inventam o lege locala sigura. Stim numai ca Iuda este gata sa ceara o pedeapsa extrema pentru o vina sexuala pe care o condamna la ea, desi el insusi se culcase cu femeia pe care o credea prostituata.\n\nTamar nu raspunde printr-un discurs lung. Trimite obiectele si formula care oglindeste Geneza 37: «recunoaste, te rog, ale cui sunt». Acelasi verb al recunoasterii se intoarce spre Iuda. Nu trebuie sa spunem ca ea ii trimite neaparat dovada «in privat» sau ca nimeni altcineva nu aude; textul spune ca trimite mesajul socrului ei si lasa obiectele sa vorbeasca.\n\nIuda le recunoaste. Aici trebuie corectata chiar nuanta traducerii vechi din campul de text: ebraicul spune tzadqah mimmeni — «ea este mai dreapta decat mine», sau «ea este mai in drept decat mine» — si da imediat motivul: «fiindca nu am dat-o fiului meu Sela». Explicatia nu trebuie sa reduca aceasta la «ea este doar putin mai putin vinovata». Iuda recunoaste ca, in disputa dintre ei, dreptatea Tamarei este mai mare tocmai din cauza neindeplinirii obligatiei lui.\n\nAceasta nu inseamna ca orice forma de inselaciune devine metoda aprobata de Dumnezeu. Inseamna ca naratiunea refuza sa lase barbatul puternic sa se ascunda in spatele moralizarii femeii. Iuda este obligat sa numeasca raul lui de la radacina: n-a dat-o lui Sela.\n\nNu spunem ca aceasta este «prima fapta cinstita din viata lui Iuda»; Geneza nu ne autorizeaza o asemenea biografie absoluta. Dar este fara indoiala un moment major de recunoastere si responsabilitate. Mai tarziu Iuda va iesi in fata pentru Beniamin si se va oferi pe sine in locul fratelui. Este rezonabil sa vedem Geneza 38 ca parte din arcul transformarii lui, fara sa pretindem ca putem demonstra ca toate schimbarile ulterioare au inceput intr-o singura secunda aici.\n\nUltimul detaliu conteaza: «nu s-a mai culcat cu ea». Recunoasterea faptului ca ea a fost mai dreapta nu transforma raportul lor intr-o relatie care continua. Naratiunea separa verdictul moral de repetarea actului sexual.",
    forYourHeart:
      "Pocainta incepe cand nu mai folosesti pacatul altuia ca sa-l ascunzi pe al tau. Iuda nu spune doar «si eu am gresit»; recunoaste exact obligatia pe care n-a implinit-o."
  },
  "geneza-38-27-30": {
    teaching:
      "Tamar naste gemeni. In timpul nasterii, o mana apare mai intai, moasa leaga un fir rosu, mana se retrage, iar celalalt copil iese primul. Naratiunea pastreaza amanuntul pentru a explica numele si ordinea celor doi fii.\n\nExista intr-adevar un ecou cu alte rasturnari ale intaietatii din Geneza — Iacov si Esau, apoi Efraim si Manase. Dar nu transformam fiecare asemenea scena intr-o formula ca Dumnezeu «intotdeauna il alege pe al doilea» sau ca orice semn omenesc al intaietatii va fi rasturnat. Tema mai larga este libertatea lui Dumnezeu de a duce fagaduinta pe cai care nu se supun automat asteptarilor omenesti.\n\nPeret/Perez este legat de ideea de spartura sau izbucnire, nume explicat de exclamarea moasei. Nu il definim suplimentar drept «cel care isi face loc cu forta» ca si cum aceasta ar fi o caracterizare morala a copilului. Zerah este legat de rasarit/stralucire.\n\nGenealogia este una dintre marile ratiuni pentru care episodul conteaza in istoria biblica, dar nu spunem ca este «singurul motiv» pentru care Duhul Sfant a pus capitolul aici. Geneza 38 lucreaza si in povestea lui Iuda, in tema recunoasterii si in contrastul cu Iosif.\n\nRut 4 urmareste linia lui Perez pana la David, iar Matei 1 o duce pana la Isus. Matei o numeste explicit pe Tamar: «Iuda a nascut pe Perez si Zerah din Tamar». Inainte de Maria, genealogia mai numeste Rahav, Rut si «sotia lui Urie». Nu spunem simplist ca toate trei sau toate patru erau straine: Rut este moabita, Rahav este din Ierihon, dar originea etnica a Tamarei nu este declarata in Geneza, iar Batseba nu este numita straina.\n\nFaptul ca asemenea nume apar in genealogia lui Mesia nu declara pacatul bun. Harul lui Dumnezeu nu are nevoie de o genealogie cosmetizata. El duce promisiunea prin oameni reali si istorii reale, iar venirea lui Hristos nu este produsul pacatului lor, ci triumful fidelitatii lui Dumnezeu in ciuda pacatului omenesc.\n\nFirul rosu ramane exact ce spune naratiunea: semnul pus de moasa pe mana lui Zerah. Textul nu il numeste simbol al sangelui lui Hristos. Legatura mesianica sigura a capitolului trece prin Perez si genealogia canonica, nu prin transformarea culorii firului intr-o profetie secreta.",
    forYourHeart:
      "Dumnezeu nu are nevoie sa-ti falsifice trecutul ca sa lucreze prin har. El nu numeste pacatul bun; il biruieste si isi duce fagaduinta mai departe."
  }
}

function normalizeUnit(unit: BibleUnit): BibleUnit {
  const correction = UNIT_CORRECTIONS[unit.id]
  return {
    ...unit,
    teaching: correction?.teaching ?? unit.teaching,
    forYourHeart: correction?.forYourHeart ?? unit.forYourHeart,
    explanationKind: unit.explanationKind ?? "exposition",
    explanationSource: unit.explanationSource ?? REVIEW_SOURCE,
    wordSource:
      unit.words && unit.words.length > 0
        ? unit.wordSource ?? HEBREW_WORD_SOURCE
        : unit.wordSource,
  }
}

export function normalizeGeneza38Chapter(chapter: BibleChapter): BibleChapter {
  if (chapter.number !== 38) return chapter

  return {
    ...chapter,
    summary:
      "Iuda se indeparteaza de fratii lui, isi pierde doi fii si nu isi implineste angajamentul fata de Tamar. Cand Sela creste si ea tot nu ii este data, Tamar actioneaza prin deghizare si ramane insarcinata de Iuda. In clipa in care Iuda este gata s-o condamne, propriile lui obiecte il obliga sa recunoasca: in ebraica, «ea este mai dreapta / mai in drept decat mine, pentru ca n-am dat-o lui Sela». Din Perez, unul dintre gemenii nascuti de Tamar, va continua linia care ajunge la David si, in Matei 1, la Mesia.",
    literaryContext:
      "Geneza 38 intrerupe naratiunea lui Iosif tocmai pentru a urmari familia lui Iuda. Exista un ecou deliberat al recunoasterii: in Geneza 37 fratii ii trimit lui Iacov haina si ii cer s-o «recunoasca»; in Geneza 38 Tamar ii trimite lui Iuda pecetea, snurul si toiagul si ii cere sa «recunoasca» ale cui sunt. Capitolul se afla si in contrast cu Geneza 39: Iuda initiaza un raport sexual cu femeia pe care o crede prostituata, in timp ce Iosif va fugi de propunerea sotiei lui Potifar. Mai tarziu, Iuda va iesi in fata pentru Beniamin si se va oferi in locul lui; Geneza 38 este o parte importanta din arcul lui, fara ca textul sa spuna ca toate schimbarile lui ulterioare provin exclusiv din aceasta scena.",
    historicalContext:
      "Datoria de a ridica urmas fratelui mort exista in povestire inainte ca Deuteronom 25 sa formuleze mai tarziu legea leviratului pentru Israel. Nu importam retroactiv toate detaliile legii mozaice in casa lui Iuda, dar legatura canonica ajuta la intelegerea obligatiei fata de vaduva fara urmas. Pecetea, snurul si toiagul sunt obiecte personale pe care Iuda le recunoaste ca ale lui; nu trebuie transformate intr-o «carte de identitate» antica cu functie standardizata. Iar cand Iuda cere arderea Tamarei, Geneza nu ne spune codul juridic precis pe care se bazeaza; de aceea nu inventam o norma locala sigura. Centrul juridic-moral al capitolului este dat chiar de recunoasterea lui Iuda: el nu i-a dat-o pe Tamar lui Sela.",
    prayer:
      "Doamne, pazeste-ne sa nu folosim slabiciunea altuia ca sa fugim de propria datorie si sa nu judecam la altul cu asprime pacatul pe care il ascundem in noi. Da-ne curajul sa recunoastem concret unde am gresit si sa nu cosmetizam nici nedreptatea, nici raspunsurile noastre strambe la ea. Iti multumim ca fidelitatea Ta poate duce fagaduinta mai departe prin istorii pe care oamenii nu le-ar fi ales si ca harul Tau nu are nevoie sa numeasca pacatul bine ca sa-l biruiasca. Amin.",
    units: chapter.units.map(normalizeUnit),
  }
}
