export const IOSUA_TEXT_13: Record<number, readonly string[]> = {
  13: [
    "Iosua era bătrân și înaintat în vârstă. DOMNUL i-a spus: „Ai îmbătrânit și ești înaintat în vârstă, iar din țară a rămas încă foarte mult de luat în stăpânire.",
    "Iată țara care mai rămâne: toate ținuturile filistenilor și tot ținutul gheșuriților,",
    "de la Șihor, care se află în fața Egiptului, până la hotarul Ecronului, spre nord, teritoriu socotit canaanit; cei cinci conducători ai filistenilor — cel din Gaza, cel din Așdod, cel din Așchelon, cel din Gat și cel din Ecron — precum și aviții,",
    "spre sud; toată țara cananiților și Meara, care aparține sidonienilor, până la Afec și până la hotarul amoriților;",
    "țara ghebaliților și tot Libanul, spre răsărit, de la Baal-Gad, sub muntele Hermon, până la intrarea în Hamat;",
    "toți locuitorii regiunii muntoase de la Liban până la Misrefot-Maim, adică toți sidonienii. Eu îi voi izgoni dinaintea fiilor lui Israel. Tu doar împarte țara prin sorți lui Israel ca moștenire, așa cum ți-am poruncit.",
    "Acum împarte țara aceasta ca moștenire celor nouă seminții și jumătății seminției lui Manase.”",
    "Împreună cu cealaltă jumătate a lui Manase, rubeniții și gadiții îiși primiseră moștenirea pe care le-o dăduse Moise dincolo de Iordan, spre răsărit, așa cum le-o dăduse Moise, slujitorul DOMNULUI:",
    "de la Aroer, aflat pe marginea văii Arnonului, și cetatea din mijlocul văii, împreună cu tot podișul Medeba până la Dibon;",
    "toate cetățile lui Sihon, regele amoriților, care domnea la Hesbon, până la hotarul fiilor lui Amon;",
    "Galaadul, hotarul gheșuriților și al maacatiților, tot muntele Hermon și tot Basanul până la Salca;",
    "tot regatul lui Og din Basan, care domnea la Aștarot și la Edrei și era unul dintre cei rămași dintre refaimi. Moise îl lovise și îl izgonise.",
    "Totuși, fiii lui Israel nu i-au izgonit pe gheșuriți și pe maacatiți; Gheșur și Maaca au locuit în mijlocul lui Israel până în ziua de astăzi.",
    "Numai seminției lui Levi nu i-a dat nicio moștenire. Darurile aduse prin foc DOMNULUI, Dumnezeul lui Israel, sunt moștenirea ei, așa cum îi spusese.",
    "Moise a dat o moștenire seminției fiilor lui Ruben, potrivit familiilor lor.",
    "Hotarul lor pornea de la Aroer, aflat pe marginea văii Arnonului, și de la cetatea din mijlocul văii și cuprindea tot podișul de lângă Medeba;",
    "Hesbonul și toate cetățile lui din podiș: Dibon, Bamot-Baal, Bet-Baal-Meon,",
    "Iahaț, Chedemot, Mefaat,",
    "Chiriataim, Sibma, Țeret-Șahar, pe muntele văii,",
    "Bet-Peor, versanții Pisga și Bet-Ieșimot;",
    "toate cetățile podișului și tot regatul lui Sihon, regele amoriților, care domnea la Hesbon. Moise îl lovise pe el și pe conducătorii Midianului — Evi, Rechem, Țur, Hur și Reba — căpeteniile lui Sihon care locuiau în țară.",
    "Fiii lui Israel l-au omorât cu sabia, printre ceilalți uciși, și pe Balaam, fiul lui Beor, ghicitorul.",
    "Hotarul fiilor lui Ruben era Iordanul și malul lui. Aceasta a fost moștenirea fiilor lui Ruben, potrivit familiilor lor, cu cetățile și satele lor.",
    "Moise a dat o moștenire seminției lui Gad, fiilor lui Gad, potrivit familiilor lor.",
    "Hotarul lor cuprindea Iazerul, toate cetățile Galaadului și jumătate din țara fiilor lui Amon până la Aroer, care este în fața Rabei;",
    "de la Hesbon până la Ramat-Mițpa și Betonim și de la Mahanaim până la hotarul Debirului;",
    "iar în vale: Bet-Haram, Bet-Nimra, Sucot și Țafon, restul regatului lui Sihon, regele Hesbonului; Iordanul și malul lui până la capătul mării Chineret, dincolo de Iordan, spre răsărit.",
    "Aceasta a fost moștenirea fiilor lui Gad, potrivit familiilor lor, cu cetățile și satele lor.",
    "Moise a dat o moștenire și jumătății seminției lui Manase. Ea a revenit jumătății seminției fiilor lui Manase, potrivit familiilor lor.",
    "Hotarul lor pornea de la Mahanaim și cuprindea tot Basanul, tot regatul lui Og, regele Basanului, și toate satele lui Iair din Basan — șaizeci de cetăți.",
    "Jumătate din Galaad, Aștarot și Edrei, cetățile regatului lui Og din Basan, au revenit fiilor lui Machir, fiul lui Manase, adică jumătății fiilor lui Machir, potrivit familiilor lor.",
    "Acestea sunt moștenirile pe care le-a împărțit Moise în câmpiile Moabului, dincolo de Iordan, la răsărit de Ierihon.",
    "Dar seminției lui Levi Moise nu i-a dat nicio moștenire. DOMNUL, Dumnezeul lui Israel, este moștenirea ei, așa cum le spusese.",
  ],
}
