export const IOSUA_TEXT_24: Record<number, readonly string[]> = {
  24: [
    "Iosua a adunat toate semințiile lui Israel la Sihem. I-a chemat pe bătrânii lui Israel, pe căpeteniile lui, pe judecătorii lui și pe supraveghetorii lui, iar ei s-au înfățișat înaintea lui Dumnezeu.",
    "Iosua a spus întregului popor: „Așa vorbește DOMNUL, Dumnezeul lui Israel: «In vechime, părinții voștri locuiau dincolo de Râu: Terah, tatăl lui Avraam și al lui Nahor. Ei slujeau altor dumnezei.",
    "Eu l-am luat pe tatăl vostru Avraam de dincolo de Râu, l-am condus prin toată țara Canaanului, i-am înmulțit urmașii și i l-am dat pe Isaac.",
    "Lui Isaac i i-am dat pe Iacov și pe Esau. Lui Esau i-am dat muntele Seir ca să-l stăpânească, iar Iacov și fiii lui au coborât în Egipt.",
    "Apoi i-am trimis pe Moise și pe Aaron și am lovit Egiptul prin ceea ce am făcut în mijlocul lui. După aceea v-am scos de acolo.",
    "I-am scos pe părinții voștri din Egipt și ați ajuns la mare. Egiptenii i-au urmărit pe părinții voștri cu care și călăreți până la Marea Roșie.",
    "Ei au strigat către DOMNUL, iar El a pus întuneric între voi și egipteni, a adus marea peste ei și i-a acoperit. Ochii voștri au văzut ce am făcut în Egipt. Apoi ați locuit multe zile în pustiu.",
    "V-am adus în țara amoriților care locuiau dincolo de Iordan. Ei au luptat împotriva voastră, dar Eu i-am dat în mâna voastră. Le-ați luat țara în stăpânire, iar Eu i-am nimicit dinaintea voastră.",
    "Balac, fiul lui Țipor, regele Moabului, s-a ridicat și a luptat împotriva lui Israel. El a trimis să-l cheme pe Balaam, fiul lui Beor, ca să vă blesteme.",
    "Dar Eu nu am vrut să-l ascult pe Balaam, așa că el v-a binecuvântat. Astfel v-am scăpat din mâna lui.",
    "Ați trecut Iordanul și ați ajuns la Ierihon. Oamenii Ierihonului au luptat împotriva voastră, precum și amoriții, periziții, canaaniții, hetiții, ghirgasiții, heviții și iebusiții, dar Eu i-am dat în mâna voastră.",
    "Am trimis înaintea voastră viespea, care i-a alungat dinaintea voastră, pe cei doi regi ai amoriților. Nu sabia și nu arcul vostru au făcut aceasta.",
    "V-am dat o țară pentru care nu ați muncit și cetăți pe care nu voi le-ați construit, iar voi locuiți în ele. Mâncați din vii și din livezi de măslini pe care nu voi le-ați plantat.»",
    "Acum, temeți-vă de DOMNUL și slujiți-I cu integritate și credincioșie. Îndepărtați dumnezeii cărora le-au slujit părinții voștri dincolo de Râu și în Egipt și slujiți-I DOMNULUI.",
    "Dacă vi se pare rău să-I slujiți DOMNULUI, alegeți astăzi cui veți sluji: dumnezeilor cărora le-au slujit părinții voștri dincolo de Râu sau dumnezeilor amoriților în a căror țară locuiți. Cât despre mine și casa mea, noi Îi vom sluji DOMNULUI.”",
    "Poporul a răspuns: „Departe de noi să-L părăsim pe DOMNUL ca să slujim altor dumnezei!",
    "Căci DOMNUL, Dumnezeul nostru, este Cel care ne-a scos pe noi și pe părinții noștri din țara Egiptului, din casa sclaviei. El a făcut înaintea ochilor noștri acele semne mari, ne-a păzit pe tot drumul pe care am mers și printre toate popoarele prin mijlocul cărora am trecut.",
    "DOMNUL a alungat dinaintea noastră toate popoarele, inclusiv pe amoriții care locuiau în țară. De aceea și noi Îi vom sluji DOMNULUI, căci El este Dumnezeul nostru.”",
    "Iosua a spus poporului: „Nu veți putea să-I slujiți DOMNULUI, căci El este un Dumnezeu sfânt, un Dumnezeu gelos. El nu vă va ierta răzvrătirile și păcatele.",
    "Dacă Îl părăsiți pe DOMNUL și slujiți dumnezeilor străini, El Se va întoarce împotriva voastră, vă va face rău și vă va nimici, după ce v-a făcut bine.”",
    "Poporul i-a spus lui Iosua: „Nu! Noi Îi vom sluji DOMNULUI.”",
    "Iosua a spus poporului: „Voi sunteți martori împotriva voastră înșivă că L-ați ales pe DOMNUL ca să-I slujiți.” Ei au răspuns: „Suntem martori.”",
    "„Acum, îndepărtați dumnezeii străini care sunt în mijlocul vostru și înclinați-vă inima spre DOMNUL, Dumnezeul lui Israel.”",
    "Poporul i-a spus lui Iosua: „Îi vom sluji DOMNULUI, Dumnezeul nostru, și vom asculta de glasul Lui.”",
    "În ziua aceea, Iosua a încheiat un legământ cu poporul și a stabilit pentru el o poruncă și o hotărâre la Sihem.",
    "Iosua a scris aceste cuvinte în Cartea Legii lui Dumnezeu. A luat o piatră mare și a ridicat-o acolo, sub stejarul care era lângă sanctuarul DOMNULUI.",
    "Iosua a spus întregului popor: „Iată, piatra aceasta va fi martoră împotriva noastră, căci a auzit toate cuvintele pe care ni le-a spus DOMNUL. Ea va fi martoră împotriva voastră, ca să nu-L tăgăduiți pe Dumnezeul vostru.”",
    "Apoi Iosua a trimis poporul, pe fiecare la moștenirea lui.",
    "După aceste lucruri, Iosua, fiul lui Nun, slujitorul DOMNULUI, a murit la vârsta de o sută zece ani.",
    "L-au înmormântat pe teritoriul moștenirii sale, la Timnat-Serah, în regiunea muntoasă a lui Efraim, la nord de muntele Gaaș.",
    "Israel I-a slujit DOMNULUI în toate zilele lui Iosua și în toate zilele bătrânilor care au trăit după Iosua și care cunoșteau toată lucrarea pe care o făcuse DOMNUL pentru Israel.",
    "Au înmormântat la Sihem oasele lui Iosif, pe care fiii lui Israel le aduseseră din Egipt, în partea de ogor pe care Iacov o cumpărase de la fiii lui Hamor, tatăl lui Sihem, cu o sută de chesita. Ea a devenit moștenirea fiilor lui Iosif.",
    "Eleazar, fiul lui Aaron, a murit. L-au înmormântat pe dealul lui Fineas, fiul său, care îi fusese dat în regiunea muntoasă a lui Efraim.",
  ],
}
