export const IOSUA_TEXT_7: Record<number, readonly string[]> = {
  7: [
    "Dar fiii lui Israel au încălcat porunca privitoare la lucrurile date spre nimicire. Acan, fiul lui Carmi, fiul lui Zabdi, fiul lui Zerah, din seminția lui Iuda, a luat din lucrurile date spre nimicire, iar mânia DOMNULUI s-a aprins împotriva fiilor lui Israel.",
    "Iosua a trimis oameni din Ierihon la Ai, care este lângă Bet-Aven, la răsărit de Betel, și le-a spus: „Urcați și cercetați țara.” Oamenii au urcat și au cercetat cetatea Ai.",
    "S-au întors la Iosua și i-au spus: „Să nu urce tot poporul. Să urce numai vreo două sau trei mii de oameni și să lovească cetatea Ai. Nu obosi tot poporul acolo, căci locuitorii ei sunt puțini.”",
    "Au urcat acolo aproximativ trei mii de oameni din popor, dar au fugit dinaintea oamenilor din Ai.",
    "Oamenii din Ai au ucis aproximativ treizeci și șase dintre ei. I-au urmărit de la poarta cetății până la Șebarim și i-au lovit pe coborâș. Inimile poporului s-au topit și au devenit ca apa.",
    "Iosua și-a sfâșiat hainele și a căzut cu fața la pământ înaintea chivotului DOMNULUI până seara, el și bătrânii lui Israel, și și-au presărat țărână pe cap.",
    "Iosua a spus: „Ah, Stăpâne DOAMNE, de ce ai trecut poporul acesta peste Iordan? Ca să ne dai în mâna amoriților și să ne nimicești? Mai bine ne-am fi mulțumit să rămânem dincolo de Iordan!",
    "Te rog, Stăpâne, ce să mai spun după ce Israel a fugit dinaintea dușmanilor săi?",
    "Cananiții și toți locuitorii țării vor auzi, ne vor înconjura și ne vor șterge numele de pe pământ. Atunci ce vei face pentru Numele Tău cel mare?”",
    "DOMNUL i-a spus lui Iosua: „Ridică-te! De ce stai căzut cu fața la pământ?",
    "Israel a păcătuit. Ei au încălcat legământul Meu, pe care li l-am poruncit. Au luat din lucrurile date spre nimicire, au furat, au ascuns și le-au pus printre lucrurile lor.",
    "De aceea fiii lui Israel nu pot sta înaintea dușmanilor lor. Ei fug dinaintea dușmanilor, pentru că au ajuns ei însuși vrednici de nimicire. Nu voi mai fi cu voi dacă nu îndepărtați din mijlocul vostru lucrul dat spre nimicire.",
    "Ridică-te! Sfințește poporul și spune: «Sfințiți-vă pentru mâine, căci așa vorbește DOMNUL, Dumnezeul lui Israel: Este un lucru dat spre nimicire în mijlocul tău, Israel. Nu vei putea sta înaintea dușmanilor tăi până nu-l vei îndepărta din mijlocul vostru.",
    "Dimineață să vă apropiați pe seminții. Seminția pe care o va arăta DOMNUL să se apropie pe clanuri; clanul pe care îl va arăta DOMNUL să se apropie pe familii; iar familia pe care o va arăta DOMNUL să se apropie om cu om.",
    "Cel care va fi arătat cu lucrul dat spre nimicire să fie ars în foc, el și tot ce are, pentru că a încălcat legământul DOMNULUI și a făcut o faptă rușinoasă în Israel.»”",
    "Iosua s-a sculat dis-de-dimineață și a adus Israelul aproape, seminție după seminție. A fost arătată seminția lui Iuda.",
    "A adus aproape clanurile lui Iuda și a fost arătat clanul zerahiților. A adus aproape clanul zerahiților, om cu om, și a fost arătat Zabdi.",
    "A adus aproape familia lui, om cu om, și a fost arătat Acan, fiul lui Carmi, fiul lui Zabdi, fiul lui Zerah, din seminția lui Iuda.",
    "Iosua i-a spus lui Acan: „Fiul meu, dă-I, te rog, glorie DOMNULUI, Dumnezeul lui Israel, și mărturisește înaintea Lui. Spune-mi acum ce ai făcut și nu ascunde nimic de mine.”",
    "Acan i-a răspuns lui Iosua: „Este adevărat, am păcătuit împotriva DOMNULUI, Dumnezeul lui Israel. Iată ce am făcut:",
    "Am văzut printre prăzi o mantie frumoasă din Șinear, două sute de șecheli de argint și un lingou de aur în greutate de cincizeci de șecheli. Le-am poftit și le-am luat. Iată, sunt ascunse în pământ, în mijlocul cortului meu, iar argintul este dedesubt.”",
    "Iosua a trimis mesageri, iar ei au alergat la cort. Lucrurile erau ascunse în cortul lui, cu argintul dedesubt.",
    "Le-au luat din mijlocul cortului, le-au adus la Iosua și la toți fiii lui Israel și le-au pus înaintea DOMNULUI.",
    "Iosua și tot Israelul împreună cu el l-au luat pe Acan, fiul lui Zerah, argintul, mantia, lingoul de aur, fiii și fiicele lui, boii, măgarii și oile lui, cortul și tot ce avea, și i-au dus în valea Acor.",
    "Iosua a spus: „De ce ne-ai tulburat? DOMNUL te va tulbura astăzi.” Tot Israelul l-a lovit cu pietre; apoi i-au ars în foc și au aruncat pietre peste ei.",
    "Au ridicat peste el o movilă mare de pietre, care a rămas până în ziua de astăzi. Atunci DOMNUL S-a întors din aprinderea mâniei Sale. De aceea locul acela a fost numit Valea Acor până în ziua de astăzi.",
  ],
}
