export const IOSUA_TEXT_9: Record<number, readonly string[]> = {
  9: [
    "Când au auzit toți regii de dincolo de Iordan, din regiunea muntoasă, din zona deluroasă joasă și de pe tot țărmul Mării celei Mari, până în dreptul Libanului — hitiții, amoriții, cananiii, periziții, hiviții și iebusiții —",
    "s-au adunat cu toții ca să lupte împotriva lui Iosua și a lui Israel într-un singur gând.",
    "Dar locuitorii Gabaonului au auzit ce făcuse Iosua Ierihonului și cetății Ai.",
    "Au recurs și ei la viclenie: au mers și s-au dat drept trimiși. Au luat saci vechi pe măgari, burdufuri vechi de vin, crăpate și legate,",
    "sandale vechi și peticite în picioare și haine vechi pe ei. Toată pâinea lor pentru drum era uscată și fărâmițată.",
    "Au venit la Iosua în tabăra de la Ghilgal și i-au spus lui și bărbaților lui Israel: „Venim dintr-o țară îndepărtată. Încheiați acum un legământ cu noi.”",
    "Bărbații lui Israel le-au spus hiviților: „Poate că locuiți în mijlocul nostru. Cum am putea încheia un legământ cu voi?”",
    "Ei i-au spus lui Iosua: „Suntem slujitorii tăi.” Iosua i-a întrebat: „Cine sunteți și de unde veniți?”",
    "Ei i-au răspuns: „Slujitorii tăi au venit dintr-o țară foarte îndepărtată, datorită Numelui DOMNULUI, Dumnezeul tău, căci am auzit faima Lui și tot ce a făcut în Egipt,",
    "precum și tot ce le-a făcut celor doi regi ai amoriților de dincolo de Iordan: lui Sihon, regele Hesbonului, și lui Og, regele Basanului, care locuia la Aștarot.",
    "Bătrânii noștri și toți locuitorii țării noastre ne-au spus: «Luați provizii pentru drum, mergeți să-i întâlniți și spuneți-le: Suntem slujitorii voștri; încheiați acum un legământ cu noi.»",
    "Iată pâinea noastră. Era caldă când am luat-o din case în ziua în care am pornit spre voi, iar acum este uscată și fărâmițată.",
    "Aceste burdufuri de vin erau noi când le-am umplut, iar acum sunt crăpate. Hainele și sandalele noastre s-au învechit din cauza drumului foarte lung.”",
    "Bărbații lui Israel au luat din proviziile lor, dar nu au cerut sfat din gura DOMNULUI.",
    "Iosua a făcut pace cu ei și a încheiat un legământ prin care îi lăsa în viață, iar conducătorii adunării le-au jurat.",
    "La trei zile după ce încheiaseră legământul cu ei, au auzit că erau vecinii lor și că locuiau în mijlocul lor.",
    "Fiii lui Israel au pornit și au ajuns la cetățile lor în ziua a treia. Cetățile lor erau Gabaon, Chefira, Beerot și Chiriat-Iearim.",
    "Fiii lui Israel nu i-au lovit, pentru că liderii adunării le juraseră pe DOMNUL, Dumnezeul lui Israel. Atunci întreaga adunare a murmurat împotriva conducătorilor.",
    "Toți conducătorii au spus întregii adunări: „Le-am jurat pe DOMNUL, Dumnezeul lui Israel, de aceea nu ne putem atinge de ei.",
    "Iată ce le vom face: îi vom lăsa în viață, ca să nu vină mânia asupra noastră din cauza jurământului pe care li l-am făcut.”",
    "Conducătorii au spus despre ei: „Să trăiască!” Astfel au ajuns tăietori de lemne și cărători de apă pentru întreaga adunare, după cum le spuseseră conducătorii.",
    "Iosua i-a chemat și le-a spus: „De ce ne-ați înșelat spunând: «Locuim foarte departe de voi», când de fapt locuiți în mijlocul nostru?",
    "Acum sunteți blesteễmați și nu veți înceta niciodată să fiți sclavi: tăietori de lemne și cărători de apă pentru Casa Dumnezeului meu.”",
    "Ei i-au răspuns lui Iosua: „Slujitorilor tăi li s-a spus limpede că DOMNUL, Dumnezeul tău, i-a poruncit slujitorului Său Moise să vă dea toată țara și să-i nimicească dinaintea voastră pe toți locuitorii ei. Ne-am temut foarte mult pentru viețile noastre din cauza voastră și de aceea am făcut lucrul acesta.",
    "Acum suntem în mâna ta. Fă-ne ce ți se pare bun și drept.”",
    "Iosua le-a făcut așa și i-a scăpat din mâna fiilor lui Israel, ca să nu-i omoare.",
    "În ziua aceea, Iosua i-a pus tăietori de lemne și cărători de apă pentru adunare și pentru altarul DOMNULUI, până în ziua de astăzi, în locul pe care avea să-l aleagă.",
  ],
}
