export const IOSUA_TEXT_4: Record<number, readonly string[]> = {
  4: [
    "După ce întregul popor a terminat de trecut Iordanul, DOMNUL i-a spus lui Iosua:",
    "„Luați doisprezece bărbați din popor, câte unul din fiecare seminție,",
    "și porunciți-le: «Luați de aici, din mijlocul Iordanului, din locul unde au stat neclintite picioarele preoților, douăsprezece pietre. Duceți-le cu voi și așezați-le în locul unde veți înnopta.»”",
    "Iosua i-a chemat pe cei doisprezece bărbați pe care îi pregătise dintre fiii lui Israel, câte unul din fiecare seminție,",
    "și le-a spus: „Treceți înaintea chivotului DOMNULUI, Dumnezeul vostru, în mijlocul Iordanului. Fiecare să ridice pe umăr câte o piatră, după numărul semințiilor fiilor lui Israel.",
    "Ele să fie un semn în mijlocul vostru. Când copiii voștri vă vor întreba în viitor: «Ce înseamnă pentru voi pietrele acestea?»,",
    "să le spuneți: «Apele Iordanului au fost oprite înaintea chivotului legământului DOMNULUI. Când chivotul a trecut Iordanul, apele Iordanului au fost oprite.» Pietrele acestea vor fi pentru totdeauna o aducere-aminte pentru fiii lui Israel.”",
    "Fiii lui Israel au făcut așa cum le poruncise Iosua. Au luat douăsprezece pietre din mijlocul Iordanului, așa cum îi spusese DOMNUL lui Iosua, după numărul semințiilor fiilor lui Israel. Le-au dus cu ei până la locul unde au înnoptat și le-au așezat acolo.",
    "Iosua a ridicat douăsprezece pietre în mijlocul Iordanului, în locul unde stătuseră picioarele preoților care purtau chivotul legământului. Ele sunt acolo până în ziua de astăzi.",
    "Preoții care purtau chivotul au rămas în mijlocul Iordanului până s-a împlinit tot ce îi poruncise DOMNUL lui Iosua să spună poporului, potrivit cu tot ce îi poruncise Moise lui Iosua. Poporul s-a grăbit să treacă.",
    "După ce întregul popor a terminat de trecut, chivotul DOMNULUI și preoții au trecut sub privirile poporului.",
    "Fiii lui Ruben, fiii lui Gad și jumătatea seminției lui Manase au trecut înarmați înaintea fiilor lui Israel, așa cum le spusese Moise.",
    "Aproape patruzeci de mii de oameni înarmați pentru luptă au trecut înaintea DOMNULUI spre câmpiile Ierihonului, pregătiți de război.",
    "În ziua aceea, DOMNUL l-a înălțat pe Iosua în ochii întregului Israel. Ei s-au temut de el în toate zilele vieții lui, așa cum se temuseră de Moise.",
    "DOMNUL i-a spus lui Iosua:",
    "„Poruncește-le preoților care poartă chivotul mărturiei să iasă din Iordan.”",
    "Iosua le-a poruncit preoților: „Ieșiți din Iordan!”",
    "Când preoții care purtau chivotul legământului DOMNULUI au ieșit din mijlocul Iordanului și tălpile picioarelor lor au atins uscatul, apele Iordanului s-au întors la locul lor și s-au revărsat peste toate malurile lui, ca mai înainte.",
    "Poporul a ieșit din Iordan în ziua a zecea a lunii întâi și și-a așezat tabăra la Ghilgal, la marginea de răsărit a Ierihonului.",
    "Iosua a ridicat la Ghilgal cele douăsprezece pietre pe care le luaseră din Iordan.",
    "El le-a spus fiilor lui Israel: „Când copiii voștri îi vor întreba în viitor pe părinții lor: «Ce înseamnă pietrele acestea?»,",
    "să le faceți cunoscut copiilor voștri: «Israel a trecut Iordanul acesta pe uscat.»",
    "Căci DOMNUL, Dumnezeul vostru, a secat apele Iordanului dinaintea voastră până ați trecut, așa cum DOMNUL, Dumnezeul vostru, a făcut cu Marea Roșie, pe care a secat-o dinaintea noastră până am trecut,",
    "pentru ca toate popoarele pământului să cunoască faptul că mâna DOMNULUI este puternică și ca voi să vă temeți întotdeauna de DOMNUL, Dumnezeul vostru.”",
  ],
}
