export const IOSUA_TEXT_2: Record<number, readonly string[]> = {
  2: [
    "Iosua, fiul lui Nun, a trimis în ascuns din Șitim doi bărbați ca iscoade, spunând: „Mergeți și cercetați țara, mai ales Ierihonul.” Ei au plecat și au intrat în casa unei prostituate pe nume Rahav și au rămas acolo.",
    "Regelui Ierihonului i s-a spus: „Iată, niște bărbați dintre fiii lui Israel au venit aici în noaptea aceasta ca să cerceteze țara.”",
    "Regele Ierihonului a trimis vorbă Rahavei: „Scoate-i pe bărbații care au venit la tine și au intrat în casa ta, fiindcă au venit să cerceteze toată țara.”",
    "Femeia i-a luat pe cei doi bărbați și i-a ascuns. Apoi a spus: „Da, bărbații au venit la mine, dar nu știam de unde erau.",
    "Pe când urma să se închidă poarta, la căderea întunericului, bărbații au ieșit. Nu știu unde s-au dus. Urmăriți-i repede și îi veți ajunge.”",
    "Dar ea îi urcase pe acoperiș și îi ascunsese sub tulpinile de in pe care le așezase pe acoperiș.",
    "Oamenii i-au urmărit pe drumul spre vadurile Iordanului, iar poarta s-a închis îndată ce urmăritorii au ieșit.",
    "Înainte ca iscoadele să se culce, Rahav s-a urcat la ele pe acoperiș",
    "și le-a spus: „Știu că DOMNUL v-a dat țara și că groaza de voi a căzut peste noi, iar toți locuitorii țării și-au pierdut curajul înaintea voastră.",
    "Căci am auzit cum DOMNUL a secat înaintea voastră apele Mării Roșii, când ați ieșit din Egipt, și ce le-ați făcut celor doi regi ai amoriților de dincolo de Iordan, lui Sihon și lui Og, pe care i-ați dat nimicirii.",
    "Când am auzit, ni s-au topit inimile și nimănui nu i-a mai rămas curaj din cauza voastră, căci DOMNUL, Dumnezeul vostru, este Dumnezeu sus în ceruri și jos pe pământ.",
    "Acum, vă rog, jurați-mi pe DOMNUL că, așa cum eu m-am purtat cu bunătate statornică față de voi, vă veți purta și voi cu bunătate statornică față de casa tatălui meu. Dați-mi un semn de încredere",
    "că îi veți lăsa în viață pe tatăl meu, pe mama mea, pe frații mei, pe surorile mele și pe toți ai lor și că ne veți scăpa viața de la moarte.”",
    "Bărbații i-au răspuns: „Viața noastră pentru viața voastră, dacă nu dezvăluiți această înțelegere a noastră. Când DOMNUL ne va da țara, ne vom purta față de tine cu bunătate statornică și credincioșie.”",
    "Ea i-a coborât cu o frânghie pe fereastră, căci casa ei era lipită de zidul cetății; locuia chiar în zid.",
    "Ea le-a spus: „Mergeți spre munte, ca să nu vă întâlnească urmăritorii. Ascundeți-vă acolo trei zile, până se vor întoarce urmăritorii; apoi vă veți putea continua drumul.”",
    "Bărbații i-au spus: „Vom fi nevinovați față de jurământul acesta pe care ne-ai pus să-l facem,",
    "dacă, atunci când vom intra în țară, nu vei lega la fereastra prin care ne-ai coborât această funie din fir stacojiu și nu-i vei strânge în casa ta pe tatăl tău, pe mama ta, pe frații tăi și toată casa tatălui tău.",
    "Oricine va ieși pe ușile casei tale în stradă va răspunde cu sângele său, iar noi vom fi nevinovați. Dar dacă va pune cineva mâna pe vreunul dintre cei care vor fi cu tine în casă, sângele lui va fi asupra capului nostru.",
    "Dacă însă vei dezvălui această înțelegere a noastră, vom fi dezlegați de jurământul pe care ne-ai pus să-l facem.”",
    "Ea a răspuns: „Să fie după cuvintele voastre.” Apoi i-a lăsat să plece, iar ei au plecat. Ea a legat funia stacojie la fereastră.",
    "Ei au mers la munte și au rămas acolo trei zile, până s-au întors urmăritorii. Urmăritorii i-au căutat pe tot drumul, dar nu i-au găsit.",
    "Cei doi bărbați s-au întors, au coborât de pe munte, au trecut Iordanul și au venit la Iosua, fiul lui Nun. I-au povestit tot ce li se întâmplase.",
    "Ei i-au spus lui Iosua: „Cu adevărat, DOMNUL a dat toată țara în mâinile noastre; toți locuitorii țării și-au pierdut curajul înaintea noastră.”",
  ],
}
