export const IOSUA_TEXT_19: Record<number, readonly string[]> = {
  19: [
    "Al doilea sorț a ieșit pentru Simeon, pentru seminția fiilor lui Simeon, potrivit familiilor lor. Moștenirea lor se afla în mijlocul moștenirii fiilor lui Iuda.",
    "În moștenirea lor se aflau Beer-Șeba, sau Șeba, Molada,",
    "Hațar-Șual, Bala, Ețem,",
    "Eltolad, Betul, Horma,",
    "Țiclag, Bet-Marcabot, Hațar-Susa,",
    "Bet-Lebaot și Șaruhen: treisprezece cetăți, împreună cu satele lor;",
    "Ain, Rimon, Eter și Așan: patru cetăți, împreună cu satele lor;",
    "și toate satele din jurul acestor cetăți până la Baalat-Beer, Rama din Neghev. Aceasta era moștenirea seminției fiilor lui Simeon, potrivit familiilor lor.",
    "Moștenirea fiilor lui Simeon a fost luată din partea fiilor lui Iuda, fiindcă partea fiilor lui Iuda era prea mare pentru ei. De aceea fiii lui Simeon și-au primit moștenirea în mijlocul moștenirii lor.",
    "Al treilea sorț a ieșit pentru fiii lui Zabulon, potrivit familiilor lor. Hotarul moștenirii lor ajungea până la Sarid.",
    "Hotarul lor urca spre apus, la Marala, ajungea la Dabeșet și apoi la pârâul aflat în fața Iocneamului.",
    "De la Sarid se întorcea spre răsărit, către răsăritul soarelui, până la hotarul Chislot-Taborului, ieșea la Daberat și urca la Iafia.",
    "De acolo trecea spre răsărit, către răsăritul soarelui, la Gat-Hefer și Et-Cațin, apoi ieșea la Rimon și cotea spre Nea.",
    "Hotarul se întorcea în jurul lui, spre nord, la Hanaton și se termina în valea Iftah-El.",
    "Mai erau Catat, Nahalal, Șimron, Idala și Betleem: douăsprezece cetăți, împreună cu satele lor.",
    "Aceasta era moștenirea fiilor lui Zabulon, potrivit familiilor lor: cetățile acestea cu satele lor.",
    "Al patrulea sorț a ieșit pentru Isahar, pentru fiii lui Isahar, potrivit familiilor lor.",
    "Hotarul lor cuprindea Izreel, Chesulot, Șunem,",
    "Hafaraim, Șion, Anaharat,",
    "Rabit, Chișion, Ebeț,",
    "Remet, En-Ganim, En-Hada și Bet-Pațeț.",
    "Hotarul ajungea la Tabor, Șahațuma și Bet-Șemeș și se termina la Iordan: șaisprezece cetăți, împreună cu satele lor.",
    "Aceasta era moștenirea seminției fiilor lui Isahar, potrivit familiilor lor: cetățile cu satele lor.",
    "Al cincilea sorț a ieșit pentru seminția fiilor lui Așer, potrivit familiilor lor.",
    "Hotarul lor cuprindea Helcat, Hali, Beten, Acșaf,",
    "Alamelec, Amad și Mișal. Ajungea spre apus la Carmel și la Șihor-Libnat.",
    "Apoi se întorcea spre răsărit la Bet-Dagon, ajungea la Zabulon și la valea Iftah-El, spre nord, la Bet-Emec și Neiel, și ieșea la Cabul, spre nord.",
    "Apoi mergea la Ebron, Rehob, Hamon și Cana, până la Sidonul cel Mare.",
    "Hotarul se întorcea spre Rama și spre cetatea fortificată Tir; apoi se întorcea spre Hosa și se termina la mare, în regiunea Aczib.",
    "Mai erau Uma, Afec și Rehob: douăzeci și două de cetăți, împreună cu satele lor.",
    "Aceasta era moștenirea seminției fiilor lui Așer, potrivit familiilor lor: cetățile acestea cu satele lor.",
    "Al șaselea sorț a ieșit pentru fiii lui Neftali, pentru fiii lui Neftali, potrivit familiilor lor.",
    "Hotarul lor pornea de la Helef, de la stejarul din Țaananim, trecea prin Adami-Necheb și Iabneel până la Lacum și se termina la Iordan.",
    "Hotarul se întorcea spre apus la Aznot-Tabor și ieșea de acolo la Hucoc. Ajungea la Zabulon în sud, la Așer în apus și la Iuda, lângă Iordan, spre răsărit.",
    "Cetățile fortificate erau: Țidim, Țer, Hamat, Racat, Chineret,",
    "Adama, Rama, Hațor,",
    "Chedeș, Edrei, En-Hațor,",
    "Iron, Migdal-El, Horem, Bet-Anat și Bet-Șemeș: nouăsprezece cetăți, împreună cu satele lor.",
    "Aceasta era moștenirea seminției fiilor lui Neftali, potrivit familiilor lor: cetățile cu satele lor.",
    "Al șaptelea sorț a ieșit pentru seminția fiilor lui Dan, potrivit familiilor lor.",
    "Hotarul moștenirii lor cuprindea Țorea, Eștaol, Ir-Șemeș,",
    "Șaalabin, Aialon, Itla,",
    "Elon, Timna, Ecron,",
    "Elteche, Ghibeton, Baalat,",
    "Iehud, Bene-Berac, Gat-Rimon,",
    "Me-Iarcon și Racon, împreună cu hotarul din fața Iafo.",
    "Teritoriul fiilor lui Dan nu le-a fost de ajuns. De aceea fiii lui Dan au urcat și au luptat împotriva Leșemului, l-au cucerit, l-au trecut prin ascuțișul sabiei, l-au luat în stăpânire și au locuit în el. Au numit Leșemul Dan, după numele tatălui lor Dan.",
    "Aceasta era moștenirea seminției fiilor lui Dan, potrivit familiilor lor: cetățile acestea cu satele lor.",
    "După ce au terminat de împărțit țara ca moștenire, potrivit hotarelor ei, fiii lui Israel i-au dat și lui Iosua, fiul lui Nun, o moștenire în mijlocul lor.",
    "Potrivit poruncii DOMNULUI, i-au dat cetatea pe care a cerut-o, Timnat-Serah, în regiunea muntoasă a lui Efraim. El a reconstruit cetatea și a locuit în ea.",
    "Acestea sunt moștenirile pe care preotul Eleazar, Iosua, fiul lui Nun, și căpeteniile familiilor semințiilor fiilor lui Israel le-au împărțit prin sorți la Șilo, înaintea DOMNULUI, la intrarea Cortului Întâlnirii. Astfel au terminat de împărțit țara.",
  ],
}
