export const IOSUA_TEXT_12: Record<number, readonly string[]> = {
  12: [
    "Aceștia sunt regii țării pe care fiii lui Israel i-au lovit și a căror țară au luat-o în stăpânire dincolo de Iordan, spre răsărit, de la pârâul Arnon până la muntele Hermon, împreună cu toată Araba de la răsărit:",
    "Sihon, regele amoriților, care locuia la Hesbon și stăpânea de la Aroer, aflat pe marginea văii Arnonului, de la mijlocul văii și peste jumătate din Galaad, până la pârâul Iaboc, hotarul fiilor lui Amon;",
    "peste Araba până la marea Chineret, spre răsărit, și până la marea Arabei, Marea Sărată, spre răsărit, pe drumul spre Bet-Ieșimot, iar spre sud până sub versanții Pisga;",
    "și Og, regele Basanului, unul dintre cei rămași dintre refaimi, care locuia la Aștarot și la Edrei.",
    "El stăpânea peste muntele Hermon, Salca, tot Basanul până la hotarul gheșuriților și maacatiților și peste jumătate din Galaad, până la hotarul lui Sihon, regele Hesbonului.",
    "Moise, slujitorul DOMNULUI, și fiii lui Israel i-au lovit, iar Moise, slujitorul DOMNULUI, le-a dat țara lor ca moștenire rubeniților, gadiților și jumătății seminției lui Manase.",
    "Aceștia sunt regii țării pe care Iosua și fiii lui Israel i-au lovit dincolo de Iordan, spre apus, de la Baal-Gad, în valea Libanului, până la muntele Halac, care urcă spre Seir. Iosua a dat țara semințiilor lui Israel ca moștenire, după împărțirile lor:",
    "în regiunea muntoasă, în zona deluroasă joasă, în Araba, pe versanți, în pustie și în Neghev, țara hitiților, amoriților, cananiților, periziților, hiviților și iebusiților.",
    "Regele Ierihonului — unul; regele cetății Ai, de lângă Betel — unul;",
    "regele Ierusalimului — unul; regele Hebronului — unul;",
    "regele Iarmutului — unul; regele Lachișului — unul;",
    "regele Eglonului — unul; regele Ghezerului — unul;",
    "regele Debirului — unul; regele Ghederului — unul;",
    "regele Hormei — unul; regele Aradului — unul;",
    "regele Libnei — unul; regele Adulamului — unul;",
    "regele Machedei — unul; regele Betelului — unul;",
    "regele Tapuahului — unul; regele Heferului — unul;",
    "regele Afecului — unul; regele Lașaronului — unul;",
    "regele Madonului — unul; regele Hațorului — unul;",
    "regele Șimron-Meronului — unul; regele Acșafului — unul;",
    "regele Taanacului — unul; regele Meghidoului — unul;",
    "regele Chedeșului — unul; regele Iocneamului din Carmel — unul;",
    "regele Dorului, din ținutul Nafat-Dor — unul; regele Goiimului din Ghilgal — unul;",
    "regele Tirței — unul. În total, treizeci și unu de regi.",
  ],
}
