export const IOSUA_TEXT_11: Record<number, readonly string[]> = {
  11: [
    "Când Iabin, regele Hațorului, a auzit aceste lucruri, a trimis soli la Iobab, regele Madonului, la regele Șimronului și la regele Acșafului,",
    "precum și la regii din nord, din regiunea muntoasă, din Araba, la sud de Chineret, din zona deluroasă joasă și de pe înălțimile Dorului, spre apus;",
    "la cananiții de la răsărit și de la apus, la amoriți, hitiți, periziți, iebusiții din regiunea muntoasă și hiviții de sub Hermon, din ținutul Mițpa.",
    "Ei au ieșit împreună cu toate armatele lor, un popor atât de numeros ca nisipul de pe țărmul mării, cu foarte mulți cai și care.",
    "Toți acești regi s-au întâlnit, au venit și și-au așezat tabăra împreună la apele Meromului, ca să lupte împotriva lui Israel.",
    "DOMNUL i-a spus lui Iosua: „Nu te teme de ei, căci mâine, pe vremea aceasta, îi voi da pe toți uciși înaintea lui Israel. Să tai tendoanele cailor lor și să le arzi carele.”",
    "Iosua a venit pe neașteptate împotriva lor la apele Meromului, împreună cu toți oamenii de război, și i-a atacat.",
    "DOMNUL i-a dat în mâna lui Israel. Ei i-au lovit și i-au urmărit până la Sidonul cel Mare, până la Misrefot-Maim și până în valea Mițpa, spre răsărit. I-au lovit până când nu le-a mai rămas niciun supraviețuitor.",
    "Iosua le-a făcut așa cum îi spusese DOMNUL: a tăiat tendoanele cailor lor și le-a ars carele.",
    "În vremea aceea, Iosua s-a întors, a cucerit Hațorul și l-a lovit cu sabia pe regele lui, căci Hațorul fusese mai înainte căpetenia tuturor acestor regate.",
    "Au trecut prin ascuțișul sabiei fiecare persoană care se afla în el, dând totul spre nimicire. Nu a rămas nimic care respira, iar Hațorul a fost ars.",
    "Iosua a cucerit toate cetățile acestor regi și pe toți regii lor. I-a trecut prin ascuțișul sabiei și i-a dat spre nimicire, așa cum poruncise Moise, slujitorul DOMNULUI.",
    "Dar Israel nu a ars niciuna dintre cetățile care se aflau încă pe movilele lor, în afară de Hațor, pe care Iosua l-a ars.",
    "Fiii lui Israel au luat pentru ei toată prada acestor cetăți și animalele. Însă pe toți oamenii i-au trecut prin ascuțișul sabiei până i-au nimicit, fără să lase nimic care respira.",
    "Așa cum DOMNUL îi poruncise lui Moise, slujitorul Său, iar Moise îi poruncise lui Iosua, tot așa a făcut Iosua. Nu a lăsat neîmplinit nimic din tot ce-i poruncise DOMNUL lui Moise.",
    "Iosua a cucerit astfel toată țara aceea: regiunea muntoasă, tot Neghevul, tot ținutul Goșenului, zona deluroasă joasă, Araba, regiunea muntoasă a lui Israel și zona ei deluroasă joasă,",
    "de la muntele Halac, care urcă spre Seir, până la Baal-Gad, în valea Libanului, sub muntele Hermon. I-a prins pe toți regii lor, i-a lovit și i-a omorât.",
    "Iosua a purtat război multă vreme cu toți acești regi.",
    "Nicio cetate nu a făcut pace cu fiii lui Israel, în afară de hiviții care locuiau în Gabaon. Pe toate celelalte le-au cucerit prin luptă.",
    "Căci DOMNUL le-a întărit inima, ca să iasă la luptă împotriva lui Israel, pentru ca Israel să-i dea spre nimicire, fără ca ei să primească îndurare, ci să fie nimiciți, așa cum îi poruncise DOMNUL lui Moise.",
    "În vremea aceea, Iosua a venit și i-a nimicit pe anachimi din regiunea muntoasă: din Hebron, Debir, Anab, din toată regiunea muntoasă a lui Iuda și din toată regiunea muntoasă a lui Israel. Iosua i-a dat spre nimicire împreună cu cetățile lor.",
    "Nu au mai rămas anachimi în țara fiilor lui Israel; au mai rămas numai în Gaza, Gat și Așdod.",
    "Astfel, Iosua a cucerit întreaga țară, potrivit cu tot ce-i spusese DOMNUL lui Moise. Iosua a dat-o ca moștenire lui Israel, după împărțirile lor, potrivit semințiilor. Apoi țara a avut odihnă de război.",
  ],
}
