export const IOSUA_TEXT_22: Record<number, readonly string[]> = {
  22: [
    "Atunci Iosua i-a chemat pe rubeniți, pe gadiți și jumătatea seminției lui Manase",
    "și le-a spus: „Ați păzit tot ce v-a poruncit Moise, slujitorul DOMNULUI, și ați ascultat de glasul meu în tot ce v-am poruncit.",
    "Nu i-ați părăsit pe frații voștri în toate aceste zile, până astăzi, ci ați împlinit îndatorirea poruncii DOMNULUI, Dumnezeul vostru.",
    "Acum, DOMNUL, Dumnezeul vostru, le-a dat odihnă fraților voștri, așa cum le spusese. Întoarceți-vă deci la corturile voastre, în țara moștenirii voastre, pe care v-a dat-o Moise, slujitorul DOMNULUI, dincolo de Iordan.",
    "Numai să aveți mare grijă să împliniți porunca și Legea pe care v-a dat-o Moise, slujitorul DOMNULUI: să-L iubiți pe DOMNUL, Dumnezeul vostru, să umblați în toate căile Lui, să păziți poruncile Lui, să vă alipiți de El și să-I slujiți din toată inima și din tot sufletul vostru.”",
    "Iosua i-a binecuvântat și le-a dat drumul, iar ei s-au dus la corturile lor.",
    "Uneia dintre jumătățile seminției lui Manase, Moise îi dăduse moștenirea în Bașan, iar celeilalte jumătăți Iosua îi dăduse moștenirea împreună cu frații ei, la apus de Iordan. Când Iosua le-a dat drumul la corturile lor, i-a binecuvântat",
    "și le-a spus: „Întoarceți-vă la corturile voastre cu multe bogății, cu foarte multe vite, cu argint, aur, bronz, fier și foarte multe haine. Împărțiți cu frații voștri prada luată de la dușmani.”",
    "Fiii lui Ruben, fiii lui Gad și jumătatea seminției lui Manase s-au întors și au plecat de la fiii lui Israel, din Șilo, care este în țara Canaanului, ca să meargă în țara Galaadului, țara moștenirii lor, pe care o primiseră potrivit poruncii DOMNULUI prin Moise.",
    "Când au ajuns în ținuturile Iordanului, în țara Canaanului, fiii lui Ruben, fiii lui Gad și jumătatea seminției lui Manase au construit acolo, lângă Iordan, un altar mare și impunător.",
    "Fiii lui Israel au auzit spunându-se: „Iată, fiii lui Ruben, fiii lui Gad și jumătatea seminției lui Manase au construit un altar în fața țării Canaanului, în ținutul Iordanului, pe partea fiilor lui Israel.”",
    "Când fiii lui Israel au auzit lucrul acesta, întreaga adunare a fiilor lui Israel s-a strâns la Șilo ca să urce împotriva lor la război.",
    "Fiii lui Israel l-au trimis la fiii lui Ruben, la fiii lui Gad și la jumătatea seminției lui Manase, în țara Galaadului, pe Fineas, fiul preotului Eleazar.",
    "Împreună cu el au trimis zece căpetenii, câte o căpetenie a unei familii părintești din fiecare seminție a lui Israel. Fiecare era capul familiei sale părintești între miile lui Israel.",
    "Ei au venit la fiii lui Ruben, la fiii lui Gad și la jumătatea seminției lui Manase, în țara Galaadului, și le-au spus:",
    "„Așa vorbește întreaga adunare a DOMNULUI: «Ce necredincioșie este aceasta pe care ați săvârșit-o împotriva Dumnezeului lui Israel, întorcându-vă astăzi de la urmarea DOMNULUI și construindu-vă un altar, ca să vă răzvrătiți astăzi împotriva DOMNULUI?",
    "Nu ne este de ajuns vina de la Peor, de care nu ne-am curățit până în ziua aceasta, deși urgia a venit peste adunarea DOMNULUI?",
    "Voi vă întoarceți astăzi de la urmarea DOMNULUI! Dacă vă răzvrătiți astăzi împotriva DOMNULUI, mâine El Se va mânia pe întreaga adunare a lui Israel.",
    "Dacă țara moștenirii voastre este necurată, treceți în țara moștenirii DOMNULUI, unde locuiește Cortul DOMNULUI, și luați-vă moștenire printre noi. Dar nu vă răzvrătiți împotriva DOMNULUI și nici împotriva noastră, construindu-vă un altar în afară de altarul DOMNULUI, Dumnezeul nostru.",
    "Oare Acan, fiul lui Zerah, nu a săvârșit o necredincioșie cu lucrul dat spre nimicire, iar mânia a căzut peste întreaga adunare a lui Israel? El nu a pierit singur pentru vina lui.»”",
    "Atunci fiii lui Ruben, fiii lui Gad și jumătatea seminției lui Manase au răspuns și le-au vorbit căpeteniilor miilor lui Israel:",
    "„Cel Puternic, Dumnezeu, DOMNUL! Cel Puternic, Dumnezeu, DOMNUL! El știe, iar Israel să știe: dacă am făcut aceasta din răzvrătire sau din necredincioșie față de DOMNUL, să nu ne cruțe astăzi!",
    "Dacă ne-am construit altarul ca să ne întoarcem de la urmarea DOMNULUI, ca să aducem pe el arderi-de-tot, daruri de mâncare sau jertfe de pace, DOMNUL Însăși să ne ceară socoteală.",
    "Dar am făcut lucrul acesta din teamă, pentru un motiv anume. Ne-am spus: «In viitor, copiii voștri ar putea să le spună copiilor noștri: 'Ce legătură aveți voi cu DOMNUL, Dumnezeul lui Israel?",
    "DOMNUL a pus Iordanul ca hotar între noi și voi, fiii lui Ruben și fiii lui Gad. Voi nu aveți parte în DOMNUL.' Astfel, copiii voștri i-ar putea face pe copiii noștri să nu se mai teamă de DOMNUL.»",
    "De aceea ne-am spus: «Să ne pregătim să construim un altar, nu pentru arderi-de-tot și nici pentru jertfe,",
    "ci ca să fie martor între noi și voi și între generațiile noastre după noi, că vom împlini slujirea DOMNULUI înaintea Lui prin arderile-de-tot, jertfele și jertfele noastre de pace. Astfel, copiii voștri nu le vor putea spune în viitor copiilor noștri: 'Nu aveți parte în DOMNUL.'»",
    "Ne-am mai spus: «Dacă ne vor vorbi astfel nouă sau generațiilor noastre în viitor, vom spune: 'Priviți copia altarului DOMNULUI, pe care au făcut-o părinții noștri, nu pentru arderi-de-tot și nici pentru jertfe, ci ca martor între noi și voi.'»",
    "Departe de noi să ne răzvrătim împotriva DOMNULUI și să ne întoarcem astăzi de la urmarea DOMNULUI, construind un altar pentru arderi-de-tot, daruri de mâncare sau jertfe, în afară de altarul DOMNULUI, Dumnezeul nostru, care este înaintea Cortului Său!”",
    "Când preotul Fineas, căpeteniile adunării și capii miilor lui Israel care erau cu el au auzit cuvintele fiilor lui Ruben, ale fiilor lui Gad și ale fiilor lui Manase, au fost mulțumiți.",
    "Fineas, fiul preotului Eleazar, le-a spus fiilor lui Ruben, fiilor lui Gad și fiilor lui Manase: „Astăzi știm că DOMNUL este în mijlocul nostru, pentru că nu ați săvârșit această necredincioșie împotriva DOMNULUI. Acum i-ați scăpat pe fiii lui Israel din mâna DOMNULUI.”",
    "Fineas, fiul preotului Eleazar, și căpeteniile s-au întors de la fiii lui Ruben și de la fiii lui Gad, din țara Galaadului în țara Canaanului, la fiii lui Israel, și le-au adus răspunsul.",
    "Lucrul acesta le-a plăcut fiilor lui Israel. Fiii lui Israel L-au binecuvântat pe Dumnezeu și nu au mai vorbit să urce împotriva lor la război ca să distrugă țara în care locuiau fiii lui Ruben și fiii lui Gad.",
    "Fiii lui Ruben și fiii lui Gad au numit altarul „Martor”, căci au spus: „El este martor între noi că DOMNUL este Dumnezeu.”",
  ],
}
