export const IOSUA_TEXT_6: Record<number, readonly string[]> = {
  6: [
    "Ierihonul era închis și bine păzit din cauza fiilor lui Israel. Nimeni nu ieșea și nimeni nu intra.",
    "DOMNUL i-a spus lui Iosua: „Iată, am dat în mâna ta Ierihonul, împreună cu regele lui și cu războinicii lui viteji.",
    "Toți oamenii de război să înconjoare cetatea, dându-i ocol o dată. Așa să faci timp de șase zile.",
    "Șapte preoți să poarte înaintea chivotului șapte trâmbițe din coarne de berbec. În ziua a șaptea să înconjurați cetatea de șapte ori, iar preoții să sune din trâmbițe.",
    "Când vor suna prelung din cornul de berbec și veți auzi sunetul trâmbiței, tot poporul să scoată un strigăt puternic. Atunci zidul cetății se va prăbuși la locul lui, iar poporul va urca, fiecare drept înainte.”",
    "Iosua, fiul lui Nun, i-a chemat pe preoți și le-a spus: „Ridicați chivotul legământului, iar șapte preoți să poarte șapte trâmbițe din coarne de berbec înaintea chivotului DOMNULUI.”",
    "Apoi i-a spus poporului: „Porniți și înconjurați cetatea, iar oamenii înarmați să treacă înaintea chivotului DOMNULUI.”",
    "După ce Iosua a vorbit poporului, cei șapte preoți care purtau cele șapte trâmbițe din coarne de berbec înaintea DOMNULUI au pornit, sunând din trâmbițe, iar chivotul legământului DOMNULUI venea în urma lor.",
    "Oamenii înarmați mergeau înaintea preoților care sunau din trâmbițe, iar ariergarda venea în urma chivotului. Trâmbițele sunau în timp ce mergeau.",
    "Iosua poruncise poporului: „Să nu strigați, să nu vi se audă glasul și să nu vă iasă niciun cuvânt din gură până în ziua când vă voi spune: «Strigați!» Atunci să strigați.”",
    "Chivotul DOMNULUI a înconjurat cetatea, dându-i ocol o dată. Apoi au intrat în tabără și au rămas acolo peste noapte.",
    "Iosua s-a sculat dis-de-dimineață, iar preoții au ridicat chivotul DOMNULUI.",
    "Cei șapte preoți care purtau cele șapte trâmbițe din coarne de berbec înaintea chivotului DOMNULUI mergeau fără oprire și sunau din trâmbițe. Oamenii înarmați mergeau înaintea lor, iar ariergarda venea după chivotul DOMNULUI. Trâmbițele sunau în timp ce mergeau.",
    "În ziua a doua au înconjurat cetatea o dată și s-au întors în tabără. Așa au făcut timp de șase zile.",
    "În ziua a șaptea s-au sculat în zorii zilei și au înconjurat cetatea în același fel de șapte ori. Numai în ziua aceea au înconjurat cetatea de șapte ori.",
    "A șaptea oară, când preoții au sunat din trâmbițe, Iosua a spus poporului: „Strigați, căci DOMNUL v-a dat cetatea!",
    "Cetatea și tot ce este în ea să fie date DOMNULUI spre nimicire. Numai prostituata Rahav să rămână în viață, ea și toți cei care sunt cu ea în casă, pentru că i-a ascuns pe mesagerii pe care i-am trimis.",
    "Dar voi să vă păziți de lucrurile date spre nimicire, ca nu cumva, după ce le-ați pus deoparte pentru nimicire, să luați ceva din ele și astfel să faceți tabăra lui Israel vrednică de nimicire și s-o tulburați.",
    "Tot argintul, aurul și obiectele din bronz și fier sunt sfinte pentru DOMNUL; ele să intre în vistieria DOMNULUI.”",
    "Poporul a strigat, iar preoții au sunat din trâmbițe. Când poporul a auzit sunetul trâmbiței, a scos un strigăt puternic, iar zidul s-a prăbușit la locul lui. Poporul a urcat în cetate, fiecare drept înainte, și au cucerit cetatea.",
    "Au dat spre nimicire tot ce era în cetate, trecând prin ascuțișul sabiei bărbat și femeie, tânăr și bătrân, bou, oaie și măgar.",
    "Iosua le-a spus celor doi bărbați care cercetaseră țara: „Intrați în casa prostituatei și scoateți de acolo femeia și tot ce-i aparține, așa cum i-ați jurat.”",
    "Tinerii care fuseseră iscoade au intrat și au scos-o pe Rahav, pe tatăl ei, pe mama ei, pe frații ei și tot ce-i aparținea. Au scos întregul ei clan și i-au așezat în afara taberei lui Israel.",
    "Au ars cetatea și tot ce era în ea. Numai argintul, aurul și obiectele din bronz și fier le-au pus în vistieria Casei DOMNULUI.",
    "Iosua a lăsat-o în viață pe prostituata Rahav, împreună cu familia tatălui ei și cu tot ce-i aparținea. Ea a locuit în mijlocul lui Israel până în ziua de astăzi, pentru că i-a ascuns pe mesagerii trimiși de Iosua să cerceteze Ierihonul.",
    "În vremea aceea, Iosua a rostit un jurământ: „Blestemat înaintea DOMNULUI să fie omul care se va ridica să reconstruiască cetatea aceasta, Ierihonul! Cu prețul întâiului său născut îi va pune temeliile și cu prețul fiului său cel mai tânăr îi va așeza porțile.”",
    "DOMNUL a fost cu Iosua, iar faima lui s-a răspândit în toată țara.",
  ],
}
