export const IOSUA_TEXT_15: Record<number, readonly string[]> = {
  15: [
    "Sorțul pentru seminția fiilor lui Iuda, potrivit familiilor lor, s-a întins până la hotarul Edomului și până la pustia Țin, spre sud, la capătul cel mai îndepărtat al Neghevului.",
    "Hotarul lor de sud pornea de la capătul Mării Sărate, de la golful care privește spre sud.",
    "De acolo ieșea la sud de urcușul Acrabim, trecea spre Țin, urca pe la sud de Cadeș-Barnea, trecea prin Hețron, urca spre Adar și se întorcea spre Carca.",
    "Trecea apoi prin Ațmon, ieșea la pârâul Egiptului, iar capătul hotarului era la mare. Acesta să fie hotarul vostru de sud.",
    "Hotarul de răsărit era Marea Sărată până la capătul Iordanului. Hotarul laturii de nord pornea de la golful mării, de la capătul Iordanului.",
    "Hotarul urca spre Bet-Hogla, trecea pe la nord de Bet-Araba și urca până la piatra lui Bohan, fiul lui Ruben.",
    "Hotarul urca spre Debir din Valea Acorului și se întorcea spre nord, către Ghilgal, aflat în fața urcușului Adumim, la sud de pârâu. Hotarul trecea pe la apele En-Șemeș și se termina la En-Roghel.",
    "Hotarul urca prin valea fiului lui Hinom până la versantul sudic al cetății iebusiților, adică Ierusalimul, apoi urca până la vârful muntelui aflat la apus de valea lui Hinom, la marginea de nord a văii refaimilor.",
    "De la vârful muntelui, hotarul se întindea spre izvorul apelor Neftoah, ieșea spre cetățile muntelui Efron și continua spre Baala, adică Chiriat-Iearim.",
    "De la Baala, hotarul se întorcea spre apus, către muntele Seir, trecea pe la versantul nordic al muntelui Iearim, adică Chesalon, cobora la Bet-Șemeș și trecea prin Timna.",
    "Hotarul ieșea spre versantul nordic al Ecronului, continua spre Șicheron, trecea pe la muntele Baala, ieșea la Iabneel și se termina la mare.",
    "Hotarul de apus era țărmul Mării celei Mari. Acesta era hotarul fiilor lui Iuda de jur împrejur, potrivit familiilor lor.",
    "Lui Caleb, fiul lui Iefune, i s-a dat o parte în mijlocul fiilor lui Iuda, potrivit poruncii DOMNULUI către Iosua: Chiriat-Arba, numit după tatăl lui Anac, adică Hebronul.",
    "Caleb i-a izgonit de acolo pe cei trei fii ai lui Anac: Șeșai, Ahiman și Talmai, urmașii lui Anac.",
    "De acolo a urcat împotriva locuitorilor Debirului. Numele Debirului fusese mai înainte Chiriat-Sefer.",
    "Caleb a spus: „Celui care va lovi Chiriat-Seferul și îl va cuceri îi voi da de soție pe fiica mea Acsa.”",
    "Otniel, fiul lui Chenaz, fratele lui Caleb, a cucerit cetatea, iar Caleb i-a dat-o de soție pe fiica sa Acsa.",
    "Când a venit, ea l-a îndemnat pe Otniel să-i ceară tatălui ei un ogor. Apoi a coborât de pe măgar, iar Caleb a întrebat-o: „Ce dorești?”",
    "Ea a răspuns: „Dă-mi o binecuvântare! Fiindcă mi-ai dat țara Neghevului, dă-mi și izvoare de apă.” Atunci el i-a dat izvoarele de sus și izvoarele de jos.",
    "Aceasta a fost moștenirea seminției fiilor lui Iuda, potrivit familiilor lor.",
    "Cetățile de la marginea moștenirii seminției fiilor lui Iuda, spre hotarul Edomului, în Neghev, erau: Cabțeel, Eder, Iagur,",
    "China, Dimona, Adada,",
    "Chedeș, Hațor, Itnan,",
    "Zif, Telem, Bealot,",
    "Hațor-Hadata, Cheriot-Hețron, adică Hațor,",
    "Amam, Șema, Molada,",
    "Hațar-Gada, Heșmon, Bet-Pelet,",
    "Hațar-Șual, Beer-Șeba, Biziotia,",
    "Baala, Iim, Ețem,",
    "Eltolad, Chesil, Horma,",
    "Țiclag, Madmana, Sansana,",
    "Lebaot, Șilhim, Ain și Rimon. În total, douăzeci și nouă de cetăți, împreună cu satele lor.",
    "În zona deluroasă joasă: Eștaol, Țorea, Așna,",
    "Zanoah, En-Ganim, Tapuah, Enam,",
    "Iarmut, Adulam, Soco, Azeca,",
    "Șaaraim, Aditaim, Ghedera și Ghederotaim: paisprezece cetăți, împreună cu satele lor.",
    "Țenan, Hadașa, Migdal-Gad,",
    "Dilean, Mițpa, Iocteel,",
    "Lachiș, Boțcat, Eglon,",
    "Cabon, Lahmam, Chitliș,",
    "Ghederot, Bet-Dagon, Naama și Macheda: șaisprezece cetăți, împreună cu satele lor.",
    "Libna, Eter, Așan,",
    "Iftah, Așna, Nețib,",
    "Cheila, Aczib și Mareșa: nouă cetăți, împreună cu satele lor.",
    "Ecronul, cu cetățile și satele lui;",
    "de la Ecron până la mare, toate cetățile din apropierea Așdodului, împreună cu satele lor;",
    "Așdodul, cu cetățile și satele lui; Gaza, cu cetățile și satele ei; până la pârâul Egiptului, Marea cea Mare și țărmul ei.",
    "În regiunea muntoasă: Șamir, Iatir, Soco,",
    "Dana, Chiriat-Sana, adică Debir,",
    "Anab, Eștemo, Anim,",
    "Goșen, Holon și Ghilo: unsprezece cetăți, împreună cu satele lor.",
    "Arab, Duma, Eșan,",
    "Ianim, Bet-Tapuah, Afeca,",
    "Humta, Chiriat-Arba, adică Hebron, și Țior: nouă cetăți, împreună cu satele lor.",
    "Maon, Carmel, Zif, Iuta,",
    "Izreel, Iocdeam, Zanoah,",
    "Cain, Ghibea și Timna: zece cetăți, împreună cu satele lor.",
    "Halhul, Bet-Țur, Ghedor,",
    "Maarat, Bet-Anot și Eltecon: șase cetăți, împreună cu satele lor.",
    "Chiriat-Baal, adică Chiriat-Iearim, și Raba: două cetăți, împreună cu satele lor.",
    "În pustie: Bet-Araba, Midin, Secaca,",
    "Nibșan, Cetatea Sării și En-Ghedi: șase cetăți, împreună cu satele lor.",
    "Fiii lui Iuda nu au putut să-i izgonească pe iebusiții care locuiau în Ierusalim. Iebusiții au locuit împreună cu fiii lui Iuda la Ierusalim până în ziua de astăzi.",
  ],
}
