export const IOSUA_TEXT_18: Record<number, readonly string[]> = {
  18: [
    "Toată adunarea fiilor lui Israel s-a strâns la Șilo și a așezat acolo Cortul Întâlnirii. Țara era supusă înaintea lor.",
    "Mai rămâneau printre fiii lui Israel șapte seminții care nu-și împărțiseră încă moștenirea.",
    "Iosua le-a spus fiilor lui Israel: „Până când veți întârzia să mergeți și să luați în stăpânire țara pe care v-a dat-o DOMNUL, Dumnezeul părinților voștri?",
    "Alegeți câte trei bărbați din fiecare seminție. Îi voi trimite, iar ei se vor ridica, vor străbate țara și o vor descrie potrivit moștenirilor ei, apoi se vor întoarce la mine.",
    "S-o împartă în șapte părți. Iuda să rămână în hotarul său la sud, iar casa lui Iosif să rămână în hotarul ei la nord.",
    "Voi să descrieți țara în șapte părți și să-mi aduceți descrierea aici. Atunci voi arunca sorții pentru voi aici, înaintea DOMNULUI, Dumnezeul nostru.",
    "Leviții nu au parte în mijlocul vostru, fiindcă preoția DOMNULUI este moștenirea lor. Gad, Ruben și jumătatea seminției lui Manase și-au primit moștenirea dincolo de Iordan, spre răsărit, moștenire pe care le-a dat-o Moise, slujitorul DOMNULUI.”",
    "Bărbații s-au ridicat și au plecat. Iosua le-a poruncit celor care mergeau să descrie țara: „Mergeți, străbateți țara, descrieți-o și întoarceți-vă la mine. Voi arunca sorții pentru voi aici, înaintea DOMNULUI, la Șilo.”",
    "Bărbații au mers, au străbătut țara și au descris-o, cetate cu cetate, în șapte părți, într-o carte. Apoi s-au întors la Iosua, în tabăra de la Șilo.",
    "Iosua a aruncat sorții pentru ei la Șilo, înaintea DOMNULUI. Acolo Iosua a împărțit țara fiilor lui Israel, potrivit împărțirilor lor.",
    "Sorțul seminției fiilor lui Beniamin a ieșit potrivit familiilor lor. Hotarul părții lor a trecut între fiii lui Iuda și fiii lui Iosif.",
    "Hotarul lor dinspre nord pornea de la Iordan, urca pe latura nordică a Ierihonului, urca prin regiunea muntoasă spre apus și se termina în pustia Bet-Aven.",
    "De acolo hotarul trecea spre Luz, pe latura sudică a Luzului, adică Betel, apoi cobora la Atarot-Adar, lângă muntele aflat la sud de Bet-Horonul de Jos.",
    "Hotarul se întorcea și cotea pe partea de apus spre sud, de la muntele aflat în fața Bet-Horonului, spre sud, și se termina la Chiriat-Baal, adică Chiriat-Iearim, cetate a fiilor lui Iuda. Aceasta era latura de apus.",
    "Latura de sud pornea de la marginea Chiriat-Iearimului. Hotarul ieșea spre apus și ajungea la izvorul apelor Neftoah.",
    "Hotarul cobora la marginea muntelui aflat în fața văii fiului lui Hinom, în partea de nord a văii refaimilor. Apoi cobora prin valea lui Hinom, pe latura sudică a cetății iebusiților, și cobora la En-Roghel.",
    "De acolo se întorcea spre nord, ieșea la En-Șemeș, continua spre Ghelilot, aflat în fața urcușului Adumim, și cobora la piatra lui Bohan, fiul lui Ruben.",
    "Trecea apoi pe lângă versantul aflat în fața Arabei, spre nord, și cobora în Araba.",
    "Hotarul trecea pe latura nordică a Bet-Hoglei și se termina la golful nordic al Mării Sărate, la capătul sudic al Iordanului. Acesta era hotarul de sud.",
    "Iordanul era hotarul de răsărit. Aceasta era moștenirea fiilor lui Beniamin, după hotarele ei de jur împrejur, potrivit familiilor lor.",
    "Cetățile seminției fiilor lui Beniamin, potrivit familiilor lor, erau: Ierihon, Bet-Hogla, Emec-Chețiț,",
    "Bet-Araba, Țemaraim, Betel,",
    "Avim, Para, Ofra,",
    "Chefar-Amoni, Ofni și Gheba: douăsprezece cetăți, împreună cu satele lor.",
    "Gabaon, Rama, Beerot,",
    "Mițpe, Chefira, Moța,",
    "Rechem, Irpeel, Tarala,",
    "Țela, Elef, cetatea iebusiților, adică Ierusalimul, Ghibeat și Chiriat: paisprezece cetăți, împreună cu satele lor. Aceasta era moștenirea fiilor lui Beniamin, potrivit familiilor lor.",
  ],
}
