export const IOSUA_TEXT_8: Record<number, readonly string[]> = {
  8: [
    "DOMNUL i-a spus lui Iosua: „Nu te teme și nu te descuraja. Ia cu tine tot poporul de război, ridică-te și urcă la Ai. Iată, am dat în mâna ta regele din Ai, poporul lui, cetatea lui și țara lui.",
    "Să faci cetății Ai și regelui ei cum ai făcut Ierihonului și regelui lui, numai că prada și animalele ei le puteți lua pentru voi. Pune o ambuscadă în spatele cetății.”",
    "Iosua s-a ridicat împreună cu tot poporul de război ca să urce la Ai. Iosua a ales treizeci de mii de războinici viteji și i-a trimis noaptea.",
    "Le-a poruncit: „Iată, să stați la pândă în spatele cetății. Să nu vă îndepărtați prea mult de cetate și să fiți cu toții gata.",
    "Eu și tot poporul care este cu mine ne vom apropia de cetate. Când vor ieși împotriva noastră, ca prima dată, vom fugi dinaintea lor.",
    "Ei vor ieși după noi până îi vom atrage departe de cetate, căci vor spune: «Fug dinaintea noastră ca prima dată!» Noi vom fugi dinaintea lor.",
    "Atunci voi să vă ridicați din ambuscadă și să luați cetatea, căci DOMNUL, Dumnezeul vostru, o va da în mâna voastră.",
    "După ce veți cuceri cetatea, să-i dați foc. Să faceți după cuvântul DOMNULUI. Iată, v-am poruncit.”",
    "Iosua i-a trimis, iar ei au mers la locul ambuscadei și au rămas între Betel și Ai, la apus de Ai. Iosua a rămas în noaptea aceea în mijlocul poporului.",
    "Iosua s-a sculat dis-de-dimineață, a numărat poporul și a urcat, el și bătrânii lui Israel, în fruntea poporului spre Ai.",
    "Tot poporul de război care era cu el a urcat, s-a apropiat și a ajuns în fața cetății. Și-au așezat tabăra la nord de Ai, având valea între ei și Ai.",
    "Iosua a luat aproximativ cinci mii de oameni și i-a pus în ambuscadă între Betel și Ai, la apus de cetate.",
    "Au așezat poporul, toată tabăra de la nordul cetății și ariergarda la apusul cetății. Iosua a mers în noaptea aceea în mijlocul văii.",
    "Când regele din Ai a văzut aceasta, el și oamenii cetății s-au grăbit și s-au sculat dis-de-dimineață. Au ieșit la timpul hotărât ca să lupte împotriva lui Israel, în fața Arabei, fără să știe că în spatele cetății era o ambuscadă.",
    "Iosua și tot Israelul s-au prefacut învinși înaintea lor și au fugit pe drumul spre pustie.",
    "Tot poporul din cetate a fost chemat să-i urmărească. L-au urmărit pe Iosua și au fost atrași departe de cetate.",
    "Nu a rămas niciun bărbat în Ai sau în Betel care să nu fi ieșit după Israel. Au lăsat cetatea deschisă și au urmărit Israelul.",
    "DOMNUL i-a spus lui Iosua: „Întinde sulița pe care o ai în mână spre Ai, căci o voi da în mâna ta.” Iosua a întins sulița din mâna lui spre cetate.",
    "Oamenii din ambuscadă s-au ridicat repede din locul lor. De îndată ce el și-a întins mâna, au alergat, au intrat în cetate, au cucerit-o și s-au grăbit să-i dea foc.",
    "Când oamenii din Ai s-au uitat înapoi, au văzut fumul cetății ridicându-se spre cer. Nu mai aveau nicio cale de scăpare, nici într-o parte, nici în alta, iar poporul care fugise spre pustie s-a întors împotriva urmăritorilor.",
    "Când Iosua și tot Israelul au văzut că ambuscada cucerise cetatea și că fumul cetății se ridica, s-au întors și i-au lovit pe oamenii din Ai.",
    "Ceilalți au ieșit din cetate împotriva lor, astfel că oamenii din Ai au fost prinși în mijlocul lui Israel, unii de o parte și alții de cealaltă. Israel i-a lovit fără să lase vreun supraviețuitor sau fugar.",
    "Pe regele din Ai l-au prins viu și l-au adus la Iosua.",
    "După ce Israel a terminat de ucis toți locuitorii din Ai aflați pe câmp și în pustia unde îi urmăriseră, și după ce toți au căzut sub ascuțișul sabiei până au fost nimiciți, tot Israelul s-a întors la Ai și a trecut cetatea prin ascuțișul sabiei.",
    "Toți cei care au căzut în ziua aceea, bărbați și femei, au fost douăsprezece mii, toți locuitorii din Ai.",
    "Iosua nu și-a retras mâna cu care întinsese sulița până nu i-a dat spre nimicire pe toți locuitorii din Ai.",
    "Israel a luat pentru sine numai animalele și prada cetății, după cuvântul pe care DOMNUL i-l poruncise lui Iosua.",
    "Iosua a ars cetatea Ai și a făcut-o pentru totdeauna un morman de ruine, o pustietate până în ziua de astăzi.",
    "L-a spânzurat pe regele din Ai de un copac până seara. La apusul soarelui, Iosua a poruncit să-i coboare trupul de pe copac. L-au aruncat la intrarea porții cetății și au ridicat peste el o movilă mare de pietre, care a rămas până în ziua de astăzi.",
    "Atunci Iosua a construit pe muntele Ebal un altar pentru DOMNUL, Dumnezeul lui Israel,",
    "așa cum Moise, slujitorul DOMNULUI, le poruncise fiilor lui Israel și cum este scris în Cartea Legii lui Moise: un altar din pietre întregi, peste care nu fusese ridicată nicio unealtă de fier. Au adus pe el arderi-de-tot DOMNULUI și au jertfit jertfe de pace.",
    "Acolo, pe pietre, Iosua a scris o copie a Legii lui Moise, pe care a scris-o în prezența fiilor lui Israel.",
    "Tot Israelul, bătrânii, conducătorii și judecătorii lui, stăteau de o parte și de alta a chivotului, înaintea preoților leviți care purtau chivotul legământului DOMNULUI, atât străinul, cât și băștinașul. Jumătate stăteau în fața muntelui Garizim și jumătate în fața muntelui Ebal, așa cum poruncise mai înainte Moise, slujitorul DOMNULUI, ca poporul lui Israel să fie binecuvântat.",
    "După aceea, Iosua a citit toate cuvintele Legii, binecuvântarea și blestemul, după tot ce este scris în Cartea Legii.",
    "Nu a fost niciun cuvânt din tot ce poruncise Moise pe care Iosua să nu-l citească înaintea întregii adunări a lui Israel, inclusiv femeile, copiii și străinii care locuiau în mijlocul lor.",
  ],
}
