export const IOSUA_TEXT_21: Record<number, readonly string[]> = {
  21: [
    "Căpeteniile familiilor părintești ale leviților s-au apropiat de preotul Eleazar, de Iosua, fiul lui Nun, și de căpeteniile familiilor părintești ale semințiilor fiilor lui Israel.",
    "Le-au vorbit la Șilo, în țara Canaanului, și au spus: „DOMNUL a poruncit prin Moise să ni se dea cetăți în care să locuim și terenuri de pășunat în jurul lor pentru vitele noastre.”",
    "Atunci fiii lui Israel le-au dat leviților, din moștenirea lor, următoarele cetăți cu terenurile lor de pășunat, potrivit poruncii DOMNULUI.",
    "Sorțul a ieșit pentru familiile chehatiților. Fiii preotului Aaron, dintre leviți, au primit prin sorți treisprezece cetăți din seminția lui Iuda, din seminția lui Simeon și din seminția lui Beniamin.",
    "Ceilalți fii ai lui Chehat au primit prin sorți zece cetăți din familiile seminției lui Efraim, din seminția lui Dan și din jumătatea seminției lui Manase.",
    "Fiii lui Gherșon au primit prin sorți treisprezece cetăți din familiile seminției lui Isahar, din seminția lui Așer, din seminția lui Neftali și din jumătatea seminției lui Manase din Bașan.",
    "Fiii lui Merari, potrivit familiilor lor, au primit douăsprezece cetăți din seminția lui Ruben, din seminția lui Gad și din seminția lui Zabulon.",
    "Fiii lui Israel le-au dat leviților prin sorți aceste cetăți cu terenurile lor de pășunat, așa cum poruncise DOMNUL prin Moise.",
    "Din seminția fiilor lui Iuda și din seminția fiilor lui Simeon au dat următoarele cetăți, menționate pe nume.",
    "Ele le-au revenit fiilor lui Aaron, dintre familiile chehatiților, dintre fiii lui Levi, pentru că primul sorț a fost al lor.",
    "Le-au dat Chiriat-Arba, numită după tatăl lui Anac, adică Hebronul, în regiunea muntoasă a lui Iuda, împreună cu terenurile de pășunat din jurul ei.",
    "Dar câmpurile cetății și satele ei i le-au dat lui Caleb, fiul lui Iefune, ca proprietate.",
    "Fiilor preotului Aaron le-au dat Hebronul, cetatea de refugiu pentru cel care ucide, cu terenurile de pășunat din jur, și Libna cu terenurile ei de pășunat;",
    "Iatir cu terenurile lui de pășunat, Eștemoa cu terenurile ei de pășunat,",
    "Holon cu terenurile lui de pășunat, Debir cu terenurile lui de pășunat,",
    "Ain cu terenurile lui de pășunat, Iuta cu terenurile ei de pășunat și Bet-Șemeș cu terenurile lui de pășunat: nouă cetăți din aceste două seminții.",
    "Din seminția lui Beniamin le-au dat Gabaonul cu terenurile lui de pășunat și Gheba cu terenurile ei de pășunat,",
    "Anatotul cu terenurile lui de pășunat și Almonul cu terenurile lui de pășunat: patru cetăți.",
    "Toate cetățile fiilor lui Aaron, preoții, au fost treisprezece cetăți cu terenurile lor de pășunat.",
    "Familiile celorlalți fii ai lui Chehat, dintre leviți, au primit prin sorți cetăți din seminția lui Efraim.",
    "Le-au dat Sihemul, cetatea de refugiu pentru cel care ucide, cu terenurile de pășunat din jur, în regiunea muntoasă a lui Efraim, și Ghezerul cu terenurile lui de pășunat,",
    "Chibțaimul cu terenurile lui de pășunat și Bet-Horonul cu terenurile lui de pășunat: patru cetăți.",
    "Din seminția lui Dan le-au dat Elteche cu terenurile ei de pășunat și Ghibetonul cu terenurile lui de pășunat,",
    "Aialonul cu terenurile lui de pășunat și Gat-Rimonul cu terenurile lui de pășunat: patru cetăți.",
    "Din jumătatea seminției lui Manase le-au dat Taanacul cu terenurile lui de pășunat și Gat-Rimonul cu terenurile lui de pășunat: două cetăți.",
    "Toate cetățile familiilor celorlalți fii ai lui Chehat au fost zece, cu terenurile lor de pășunat.",
    "Fiilor lui Gherșon, dintre familiile leviților, le-au dat din jumătatea seminției lui Manase Golanul din Bașan, cetatea de refugiu pentru cel care ucide, cu terenurile lui de pășunat, și Be-Eștera cu terenurile ei de pășunat: două cetăți.",
    "Din seminția lui Isahar le-au dat Chișionul cu terenurile lui de pășunat și Dabratul cu terenurile lui de pășunat,",
    "Iarmutul cu terenurile lui de pășunat și En-Ganimul cu terenurile lui de pășunat: patru cetăți.",
    "Din seminția lui Așer le-au dat Mișalul cu terenurile lui de pășunat și Abdonul cu terenurile lui de pășunat,",
    "Helcatul cu terenurile lui de pășunat și Rehobul cu terenurile lui de pășunat: patru cetăți.",
    "Din seminția lui Neftali le-au dat Chedeșul din Galileea, cetatea de refugiu pentru cel care ucide, cu terenurile lui de pășunat, Hamot-Dorul cu terenurile lui de pășunat și Cartanul cu terenurile lui de pășunat: trei cetăți.",
    "Toate cetățile gherșoniților, potrivit familiilor lor, au fost treisprezece cetăți cu terenurile lor de pășunat.",
    "Familiilor fiilor lui Merari, ceilalți leviți, le-au dat din seminția lui Zabulon Iocneamul cu terenurile lui de pășunat și Carta cu terenurile ei de pășunat,",
    "Dimna cu terenurile ei de pășunat și Nahalalul cu terenurile lui de pășunat: patru cetăți.",
    "Din seminția lui Ruben le-au dat Bețerul cu terenurile lui de pășunat și Iahațul cu terenurile lui de pășunat,",
    "Chedemotul cu terenurile lui de pășunat și Mefaatul cu terenurile lui de pășunat: patru cetăți.",
    "Din seminția lui Gad le-au dat Ramotul din Galaad, cetatea de refugiu pentru cel care ucide, cu terenurile lui de pășunat, și Mahanaimul cu terenurile lui de pășunat,",
    "Heșbonul cu terenurile lui de pășunat și Iazerul cu terenurile lui de pășunat: în total patru cetăți.",
    "Toate acestea au fost cetățile fiilor lui Merari, potrivit familiilor lor, adică ale celorlalte familii ale leviților. Sorțul lor a fost de douăsprezece cetăți.",
    "Toate cetățile leviților din mijlocul proprietății fiilor lui Israel au fost patruzeci și opt de cetăți cu terenurile lor de pășunat.",
    "Fiecare dintre aceste cetăți avea terenuri de pășunat în jurul ei. Așa era cu toate cetățile acestea.",
    "DOMNUL i-a dat lui Israel toată țara pe care jurase că o va da părinților lor. Ei au luat-o în stăpânire și au locuit în ea.",
    "DOMNUL le-a dat odihnă de jur împrejur, potrivit cu tot ce jurase părinților lor. Niciunul dintre dușmanii lor nu le-a putut sta împotrivă; DOMNUL i-a dat pe toți dușmanii lor în mâna lor.",
    "Niciunul dintre toate lucrurile bune pe care DOMNUL le spusese casei lui Israel nu a rămas neîmplinit. Toate s-au împlinit.",
  ],
}
