export const IOSUA_TEXT_10: Record<number, readonly string[]> = {
  10: [
    "Când Adoni-Țedek, regele Ierusalimului, a auzit că Iosua cucerise cetatea Ai și o dăduse spre nimicire, făcând cetății Ai și regelui ei cum făcuse Ierihonului și regelui lui, și că locuitorii Gabaonului făcuseră pace cu Israel și rămăseseră în mijlocul lor,",
    "el și oamenii lui s-au temut foarte mult, pentru că Gabaon era o cetate mare, asemenea uneia dintre cetățile regale, mai mare decât Ai, iar toți bărbații ei erau viteji.",
    "Adoni-Țedek, regele Ierusalimului, le-a trimis vorbă lui Hoham, regele Hebronului, lui Piram, regele Iarmutului, lui Iafia, regele Lachișului, și lui Debir, regele Eglonului:",
    "„Urcați la mine și ajutați-mă! Să lovim Gabaonul, căci a făcut pace cu Iosua și cu fiii lui Israel.”",
    "Cei cinci regi ai amoriților — regele Ierusalimului, regele Hebronului, regele Iarmutului, regele Lachișului și regele Eglonului — s-au adunat și au urcat cu toate armatele lor. Și-au așezat tabăra împotriva Gabaonului și au pornit război împotriva lui.",
    "Oamenii din Gabaon au trimis la Iosua, în tabăra de la Ghilgal, spunând: „Nu-ți părăsi slujitorii! Urcă repede la noi, salvează-ne și ajută-ne, căci toți regii amoriților care locuiesc în regiunea muntoasă s-au adunat împotriva noastră.”",
    "Iosua a urcat de la Ghilgal, el și tot poporul de război împreună cu el, inclusiv toți războinicii viteji.",
    "DOMNUL i-a spus lui Iosua: „Nu te teme de ei, căci i-am dat în mâna ta. Niciunul dintre ei nu va putea sta înaintea ta.”",
    "Iosua a venit asupra lor pe neașteptate, după ce urcase toată noaptea de la Ghilgal.",
    "DOMNUL i-a aruncat în panică înaintea lui Israel, iar Israel i-a lovit cu o mare înfrângere la Gabaon, i-a urmărit pe drumul care urcă la Bet-Horon și i-a lovit până la Azeca și Macheda.",
    "Pe când fugeau dinaintea lui Israel și coborâau de la Bet-Horon, DOMNUL a aruncat peste ei din cer pietre mari, până la Azeca, și au murit. Au murit mai mulți din cauza grindinei decât au ucis fiii lui Israel cu sabia.",
    "Atunci Iosua I-a vorbit DOMNULUI, în ziua când DOMNUL i-a dat pe amoriți înaintea fiilor lui Israel, și a spus în fața lui Israel: „Soare, oprește-te deasupra Gabaonului, iar tu, lună, deasupra văii Aialonului!”",
    "Soarele s-a oprit și luna a stat până când națiunea s-a răzbunat pe dușmanii ei. Nu este scris lucrul acesta în Cartea celui Drept? Soarele a stat în mijlocul cerului și nu s-a grăbit să apună aproape o zi întreagă.",
    "Nu a mai fost nicio zi ca aceea, nici înainte, nici după ea, când DOMNUL să asculte astfel glasul unui om, căci DOMNUL lupta pentru Israel.",
    "Iosua și tot Israelul împreună cu el s-au întors în tabăra de la Ghilgal.",
    "Cei cinci regi au fugit și s-au ascuns în peștera de la Macheda.",
    "Lui Iosua i s-a spus: „Cei cinci regi au fost găsiți ascunși în peștera de la Macheda.”",
    "Iosua a spus: „Rostogoliți pietre mari la intrarea peșterii și puneți oameni să-i păzească.",
    "Dar voi să nu vă opriți. Urmăriți-vă dușmanii și loviți-i din urmă. Nu-i lăsați să intre în cetățile lor, căci DOMNUL, Dumnezeul vostru, i-a dat în mâna voastră.”",
    "După ce Iosua și fiii lui Israel au terminat de-i lovit cu o înfrângere foarte mare, până aproape i-au nimicit, cei care au supraviețuit au intrat în cetățile fortificate.",
    "Tot poporul s-a întors în pace la Iosua, în tabăra de la Macheda. Nimeni n-a îndrăznit să spună vreun cuvânt împotriva vreunuia dintre fiii lui Israel.",
    "Atunci Iosua a spus: „Deschideți intrarea peșterii și aduceți-i la mine pe cei cinci regi din peșteră.”",
    "Au făcut așa și i-au adus din peșteră pe cei cinci regi: regele Ierusalimului, regele Hebronului, regele Iarmutului, regele Lachișului și regele Eglonului.",
    "După ce i-au adus pe acești regi la Iosua, Iosua i-a chemat pe toți bărbații lui Israel și le-a spus comandanților oamenilor de război care merseseră cu el: „Apropiați-vă și puneți-vă picioarele pe grumazurile acestor regi.” Ei s-au apropiat și și-au pus picioarele pe grumazurile lor.",
    "Iosua le-a spus: „Nu vă temeti și nu vă descurajați. Fiți tari și curajoși, căci așa va face DOMNUL tuturor dușmanilor împotriva cărora veți lupta.”",
    "După aceea, Iosua i-a lovit și i-a omorât, apoi i-a spânzurat pe cinci copaci. Au rămas spânzurați pe copaci până seara.",
    "La apusul soarelui, Iosua a poruncit să fie coborâți de pe copaci și aruncați în peștera unde se ascunseseră. Au pus pietre mari la intrarea peșterii, care au rămas până în ziua de astăzi.",
    "În ziua aceea, Iosua a cucerit Macheda și a trecut-o prin ascuțișul sabiei, împreună cu regele ei. A dat spre nimicire cetatea și fiecare persoană din ea, fără să lase vreun supraviețuitor. I-a făcut regelui din Macheda cum îi făcuse regelui Ierihonului.",
    "Iosua a trecut de la Macheda la Libna, împreună cu tot Israelul, și a luptat împotriva Libnei.",
    "DOMNUL a dat-o și pe ea, împreună cu regele ei, în mâna lui Israel. Iosua a trecut-o prin ascuțișul sabiei, împreună cu fiecare persoană din ea, fără să lase vreun supraviețuitor. I-a făcut regelui ei cum îi făcuse regelui Ierihonului.",
    "Iosua a trecut de la Libna la Lachiș, împreună cu tot Israelul. Și-a așezat tabăra împotriva ei și a luptat împotriva ei.",
    "DOMNUL a dat Lachișul în mâna lui Israel. Iosua l-a cucerit în ziua a doua și l-a trecut prin ascuțișul sabiei, împreună cu fiecare persoană din el, așa cum făcuse Libnei.",
    "Atunci Horam, regele Ghezerului, a urcat ca să ajute Lachișul, dar Iosua l-a lovit împreună cu poporul lui, fără să-i lase vreun supraviețuitor.",
    "Iosua a trecut de la Lachiș la Eglon, împreună cu tot Israelul. Și-au așezat tabăra împotriva lui și au luptat împotriva lui.",
    "În ziua aceea l-au cucerit și l-au trecut prin ascuțișul sabiei. Iosua a dat spre nimicire fiecare persoană din el în ziua aceea, așa cum făcuse Lachișului.",
    "Iosua a urcat de la Eglon la Hebron, împreună cu tot Israelul, și au luptat împotriva lui.",
    "L-au cucerit și l-au trecut prin ascuțișul sabiei, împreună cu regele lui, toate cetățile lui și fiecare persoană din ele. Nu a lăsat vreun supraviețuitor, așa cum făcuse Eglonului, ci l-a dat spre nimicire, împreună cu fiecare persoană din el.",
    "Iosua s-a întors la Debir, împreună cu tot Israelul, și a luptat împotriva lui.",
    "L-a cucerit împreună cu regele și toate cetățile lui. I-au trecut prin ascuțișul sabiei și au dat spre nimicire fiecare persoană din ele, fără să lase vreun supraviețuitor. Cum făcuse Hebronului, așa a făcut Debirului și regelui lui, cum făcuse și Libnei și regelui ei.",
    "Iosua a lovit toată țara: regiunea muntoasă, Neghevul, zona deluroasă joasă, versanții și pe toți regii lor. Nu a lăsat vreun supraviețuitor, ci a dat spre nimicire tot ce respira, așa cum poruncise DOMNUL, Dumnezeul lui Israel.",
    "Iosua i-a lovit de la Cadeș-Barnea până la Gaza și tot ținutul Goșenului până la Gabaon.",
    "Iosua i-a cucerit pe toți acești regi și țările lor dintr-o singură campanie, pentru că DOMNUL, Dumnezeul lui Israel, lupta pentru Israel.",
    "Apoi Iosua și tot Israelul împreună cu el s-au întors în tabăra de la Ghilgal.",
  ],
}
