export const JUDECATORI_TEXT_1: Record<number, readonly string[]> = {
  1: [
    "După moartea lui Iosua, copiii lui Israel au întrebat pe DOMNUL și au zis: «Cine dintre noi să se suie întâi împotriva canaaniților ca să pornească lupta cu ei?»",
    "DOMNUL a răspuns: «Iuda să se suie; iată că am dat țara în mâinile lui.»",
    "Și Iuda a zis fratelui său Simeon: «Suie-te împreună cu mine în țara care mi-a căzut la sorți și să luptăm împotriva canaaniților; și voi merge și eu cu tine în țara care ți-a căzut la sorți.» Și Simeon s-a dus cu el.",
    "Iuda s-a suit, și DOMNUL a dat pe canaaniți și pe fereziți în mâinile lor; au ucis zece mii de oameni la Bezec.",
    "Au găsit pe Adoni-Bezec la Bezec; au pornit lupta împotriva lui și au bătut pe canaaniți și pe fereziți.",
    "Adoni-Bezec a luat fuga; dar ei l-au urmărit și l-au prins și i-au tăiat degetele cele mari de la mâini și de la picioare.",
    "Adoni-Bezec a zis: «Șaptezeci de împărați, cu degetele cele mari de la mâini și de la picioare tăiate, strângeau mâncare sub masa mea; Dumnezeu îmi răsplătește și mie cum am făcut.» L-au dus la Ierusalim și a murit acolo.",
    "Fiii lui Iuda au pornit lupta împotriva Ierusalimului și l-au luat; l-au trecut prin ascuțișul sabiei și au dat foc cetății.",
    "Fiii lui Iuda s-au coborât apoi ca să bată pe canaaniții care locuiau muntele, ținutul de miazăzi și câmpia.",
    "Iuda a pornit împotriva canaaniților care locuiau la Hebron, numit mai înainte Chiriat-Arba; și a bătut pe Șeșai, pe Ahiman și pe Talmai.",
    "De acolo a pornit împotriva locuitorilor Debirului: Debirul se numea mai înainte Chiriat-Sefer.",
    "Caleb a zis: «Voi da pe fiica mea, Acsa, de nevastă cui va bate Chiriat-Seferul și-l va lua.»",
    "Otniel, fiul lui Chenaz, fratele cel mai mic al lui Caleb, a pus mâna pe cetate; și Caleb i-a dat de nevastă pe fiica sa Acsa.",
    "Când a intrat ea la Otniel, l-a îndemnat să ceară un ogor de la tatăl ei. Ea s-a coborât de pe măgar; și Caleb i-a zis: «Ce vrei?»",
    "Ea i-a răspuns: «Dă-mi un dar, căci mi-ai dat un pământ secetos; dă-mi și izvoare de apă.» Și Caleb i-a dat izvoarele de sus și izvoarele de jos.",
    "Fiii chenitului, socrul lui Moise, s-au suit din Cetatea Finicilor, împreună cu fiii lui Iuda, în pustiul lui Iuda, la miazăzi de Arad, și s-au dus de s-au așezat între popor.",
    "Iuda a pornit cu fratele său Simeon și au bătut pe canaaniții care locuiau la Țefat; au nimicit cetatea cu desăvârșire și au numit-o Horma.",
    "Iuda a mai pus mâna pe Gaza și pe ținutul ei, pe Ascalon și pe ținutul lui și pe Ecron și pe ținutul lui.",
    "DOMNUL a fost cu Iuda; și Iuda a pus stăpânire pe munte, dar n-a putut să izgonească pe locuitorii din câmpie, pentru că aveau care de fier.",
    "Au dat Hebronul lui Caleb, cum spusese Moise; și el a izgonit de-acolo pe cei trei fii ai lui Anac.",
    "Fiii lui Beniamin n-au izgonit pe iebusiții care locuiau la Ierusalim; și iebusiții au locuit în Ierusalim cu fiii lui Beniamin până în ziua de azi.",
    "Casa lui Iosif s-a suit și ea împotriva Betelului, și DOMNUL a fost cu ei.",
    "Cei din casa lui Iosif au iscodit Betelul, care mai înainte se chema Luz.",
    "Străjerii au văzut pe un om ieșind din cetate și i-au zis: «Arată-ne pe unde putem intra în cetate, și vom avea milă de tine.»",
    "El le-a arătat pe unde ar putea să intre în cetate. Și au trecut cetatea prin ascuțișul sabiei; dar pe omul acela l-au lăsat să plece cu toată familia lui.",
    "Omul acela s-a dus în țara hetiților; a zidit o cetate și i-a pus numele Luz, nume pe care l-a purtat până în ziua de azi.",
    "Manase n-a izgonit nici el pe locuitorii din Bet-Șean și din satele dimprejurul lui, din Taanac și satele lui, din Dor și satele dimprejurul lui, din Iibleam și satele dimprejurul lui, din Meghido și satele dimprejurul lui; așa încât canaaniții au izbutit să rămână în țara aceasta.",
    "Când Israel a fost destul de tare, a supus pe canaaniți la un bir, dar nu i-a izgonit.",
    "Efraim n-a izgonit pe canaaniții care locuiau la Ghezer, și canaaniții au locuit în mijlocul lui Efraim la Ghezer.",
    "Zabulon n-a izgonit nici el pe locuitorii din Chitron, nici pe locuitorii din Nahalol; și canaaniții au locuit în mijlocul lui Zabulon, dar au fost supuși la un bir.",
    "Nici Așer n-a izgonit pe locuitorii din Aco, nici pe locuitorii din Sidon, nici pe cei din Ahlab, din Aczib, din Helba, din Afic și din Rehob;",
    "și așeriții au locuit în mijlocul canaaniților, locuitorii țării, căci nu i-au izgonit.",
    "Neftali n-a izgonit pe locuitorii din Bet-Șemeș, nici pe locuitorii din Bet-Anat și a locuit în mijlocul canaaniților, locuitorii țării; dar locuitorii din Bet-Șemeș și din Bet-Anat au fost supuși la un bir.",
    "Amoriții au dat înapoi pe munte pe fiii lui Dan și nu i-au lăsat să se coboare în câmpie.",
    "Amoriții au izbutit să rămână la Har-Heres, la Aialon și la Șaalbim; dar mâna casei lui Iosif a apăsat asupra lor și au fost supuși la un bir.",
    "Ținutul amoriților se întindea de la suișul Acrabim, de la Sela și în sus.",
  ],
}
