/*
 * Textul biblic al cărții Levitic, capitolul 11.
 *
 * Sursa: Biblia Emanus (BE), docs/data/biblia-emanus/LEV.11.json.
 * Capitol cu status "published", auditat verset cu verset din WLC-OSHB,
 * cu WEBU ca bază public-domain. 47 de versete.
 */

export const LEVITIC_TEXT_11: Record<number, readonly string[]> = {
  11: [
    "DOMNUL le-a vorbit lui Moise și lui Aaron, spunându-le:",
    "„Vorbiți fiilor lui Israel și spune-le: Iată viețuitoarele pe care le veți putea mânca dintre toate animalele de pe pământ:",
    "Orice animal care are copita despicată, adică despărțită în două gheare, și care rumegă printre animale, pe acela îl veți mânca.",
    "Dar din cele ce numai rumegă sau numai au copita despicată să nu mâncați: cămila, pentru că rumegă, dar nu are copita despicată; ea este necurată pentru voi;",
    "iepurele de stâncă, pentru că rumegă, dar nu are copita despicată; este necurat pentru voi;",
    "iepurele de câmp, pentru că rumegă, dar nu are copita despicată; este necurat pentru voi;",
    "și porcul, pentru că are copita despicată și despicată în două, dar nu rumegă; este necurat pentru voi.",
    "Din carnea lor să nu mâncați și de stârvurile lor să nu vă atingeți; sunt necurate pentru voi.",
    "Iată ce veți mânca din tot ce este în ape: tot ce are înotătoare și solzi în ape, în mări și în râuri, pe acelea le veți mânca.",
    "Dar tot ce nu are înotătoare și solzi în mări și în râuri, dintre toate vietățile care mișună în ape și dintre toate ființele vii din ape, să fie o urâciune pentru voi.",
    "Ele vor fi o urâciune pentru voi; din carnea lor să nu mâncați și stârvurile lor să le priviți ca pe o urâciune.",
    "Tot ce nu are înotătoare și solzi în ape va fi o urâciune pentru voi.",
    "Dintre păsări, iată pe cele pe care le veți privi ca pe o urâciune și care nu se vor mânca, fiind o urâciune: vulturul, zăganul și vulturul de mare,",
    "gaia, șoimul după soiurile lui,",
    "toate soiurile de corbi,",
    "struțul, cucuveaua, pescărușul și uliul după soiurile lui,",
    "cucuveaua de stâncă, corbul de apă și bufnița,",
    "lebăda, pelicanul și vulturul pleșuv,",
    "barza, stârcul după soiurile lui, pupăza și liliacul.",
    "Orice insectă înaripată care umblă pe patru picioare să fie o urâciune pentru voi.",
    "Dar din toate insectele înaripate care umblă pe patru picioare le veți putea mânca pe cele care au picioare lungi deasupra labelor, cu care să sară pe pământ.",
    "Iată pe care le veți mânca dintre ele: lăcusta după soiurile ei, lăcusta solam după soiurile ei, lăcusta hargol după soiurile ei și lăcusta hagav după soiurile ei.",
    "Dar orice altă insectă înaripată care are patru picioare să fie o urâciune pentru voi.",
    "Prin acestea vă veți întina; oricine se va atinge de stârvurile lor va fi necurat până seara,",
    "iar oricine va purta ceva din stârvul lor să-și spele hainele și va fi necurat până seara.",
    "Orice animal care are copita despicată, dar nu copita despărțită în două gheare și care nu rumegă, este necurat pentru voi; oricine se va atinge de ele va fi necurat.",
    "Toate animalele care umblă pe labe dintre toate cele pe patru picioare sunt necurate pentru voi; oricine se va atinge de stârvul lor va fi necurat până seara.",
    "Iar cine va purta stârvul lor să-și spele hainele și va fi necurat până seara; ele sunt necurate pentru voi.",
    "Iată ce va fi necurat pentru voi dintre vietățile care mișună pe pământ: nevăstuica, șoarecele și șopârla mare, după soiurile lor,",
    "gecko, șopârla de zid, șopârla de nisip, șopârla și cameleonul.",
    "Acestea sunt necurate pentru voi dintre toate vietățile care mișună; oricine se va atinge de ele când sunt moarte va fi necurat până seara.",
    "Orice lucru peste care va cădea vreuna din ele când este moartă va fi necurat, fie vas de lemn, fie haină, fie piele, fie sac, orice vas folosit la vreo muncă; să fie pus în apă și va fi necurat până seara, apoi va fi curat.",
    "Dacă va cădea într-un vas de lut, tot ce este în el va fi necurat și vasul îl veți sparge.",
    "Orice hrană care se mănâncă, peste care va cădea apă dintr-un astfel de vas, va fi necurată; și orice băutură care se bea dintr-un astfel de vas va fi necurată.",
    "Orice lucru peste care va cădea vreo parte din stârvul lor va fi necurat; cuptorul sau plita să fie dărâmate, căci sunt necurate și vor fi necurate pentru voi.",
    "Numai un izvor sau o fântână în care se adună apă vor rămâne curate, dar cine se va atinge de stârvul lor va fi necurat.",
    "Dacă va cădea o parte din stârvul lor pe vreo sămânță de semănat, ea va rămâne curată;",
    "dar dacă s-a pus apă pe sămânță și va cădea pe ea o parte din stârvul lor, ea va fi necurată pentru voi.",
    "Dacă moare un animal din cele pe care le puteți mânca, cine se va atinge de stârvul lui va fi necurat până seara.",
    "Cine va mânca din stârvul lui să-și spele hainele și va fi necurat până seara; și cine va purta stârvul lui să-și spele hainele și va fi necurat până seara.",
    "Orice vietate care se târăște pe pământ este o urâciune; să nu se mănânce.",
    "Tot ce se târăște pe pântece, tot ce umblă pe patru picioare sau are multe picioare, dintre toate vietățile care mișună pe pământ, să nu le mâncați, căci sunt o urâciune.",
    "Să nu vă faceți urâcioși prin nicio vietate care se târăște și să nu vă întinați prin ele, ca să nu deveniți necurați prin ele.",
    "Căci Eu sunt DOMNUL Dumnezeul vostru. Sfințiți-vă și fiți sfinți, căci Eu sunt sfânt! Să nu vă întinați sufletele prin nicio vietate care se târăște pe pământ.",
    "Căci Eu sunt DOMNUL, Care v-am scos din țara Egiptului ca să vă fiu Dumnezeu. Fiți dar sfinți, căci Eu sunt sfânt!",
    "Aceasta este legea privitoare la animale, la păsări, la toate ființele vii care se mișcă în ape și la toate vietățile care mișună pe pământ,",
    "ca să deosebiți între ce este necurat și ce este curat, între vietățile care se pot mânca și vietățile care nu se pot mânca.”",
  ],
}
