import { marcuChapter, teaching } from "./marcuHelpers.js"

export const MARCU_15 = marcuChapter({
  number: 15,
  title: "Marcu 15 — Împăratul răstignit",
  summary: "Isus este predat lui Pilat, iar mulțimea îl alege pe Baraba. Batjocorit ca Împărat, El este răstignit la Golgota, moare în întuneric și deschide drumul spre Dumnezeu când perdeaua Templului se rupe. Iosif din Arimateea Îi așază trupul în mormânt.",
  literaryContext: "Mărturisirea lui Isus dinaintea Sinedriului ajunge în fața puterii romane. Titlul «Împăratul iudeilor» este folosit ca acuzație și batjocură, dar Marcu arată că tocmai pe cruce Împăratul Își dă viața răscumpărare pentru mulți.",
  historicalContext: "Pilat era prefectul roman al Iudeii. Flagelarea preceda de obicei răstignirea, pedeapsă publică rezervată robilor și răzvrătiților. Golgota înseamnă «Locul căpățânii». Perdeaua despărțea Locul Preasfânt, iar ruperea ei de sus în jos arată inițiativa lui Dumnezeu.",
  units: [
    { verses: [1, 15], heading: "Pe Baraba l-a slobozit", teaching: teaching("Conducătorii Îl predau lui Pilat, iar Isus răspunde adevărului fără să Se apere prin spectacol. Pilat vede pizma lor, dar preferă să mulțumească mulțimea și îl eliberează pe Baraba.", "Cel vinovat pleacă liber, iar Cel nevinovat ia locul condamnatului. Baraba devine o imagine vie a Evangheliei: noi eram sub sentință, iar Împăratul a primit pedeapsa."), crossRefs: ["Isaia 53:4-6", "Matei 27:11-26", "2 Corinteni 5:21"], forYourHeart: "Privește locul gol al lui Baraba și crucea ocupată de Isus. Acolo vezi cât de concret a luat El locul tău." },
    { verses: [16, 32], heading: "Împăratul iudeilor", teaching: teaching("Ostașii Îl îmbracă în purpură, Îi pun cununa de spini și Îl salută în batjocură. Fără să știe, rostesc adevărul: Cel umilit este Împăratul. Simon din Cirena este silit să-I poarte crucea până la Golgota.", "Isus refuză vinul amorțitor și este răstignit între tâlhari. Trecătorii Îi cer să Se salveze coborând de pe cruce, dar tocmai rămânând pe cruce îi mântuiește pe alții. Puterea iubirii Lui se arată nu în evitarea suferinței, ci în ducerea ei până la capăt."), crossRefs: ["Psalmul 22:7-18", "Isaia 53:12", "Filipeni 2:8-11"], forYourHeart: "Nu confunda puterea cu fuga de durere. Împăratul tău a rămas pe cruce fiindcă dragostea Lui pentru tine nu s-a retras." },
    { verses: [33, 41], heading: "Cu adevărat, Omul acesta era Fiul lui Dumnezeu", teaching: teaching("Întunericul acoperă țara, iar Isus strigă cu cuvintele Psalmului 22: «Dumnezeul Meu, Dumnezeul Meu, pentru ce M-ai părăsit?». El intră în adâncul judecății și singurătății, purtând păcatul, fără să înceteze a Se adresa Tatălui.", "Când Își dă duhul, perdeaua Templului se rupe de sus până jos. Drumul spre Dumnezeu este deschis prin trupul Lui. Un sutaș păgân, privind felul în care moare, mărturisește: «Cu adevărat, Omul acesta era Fiul lui Dumnezeu!». Femeile care Îl urmaseră rămân martore când alții au fugit."), crossRefs: ["Psalmul 22:1", "Evrei 10:19-22", "Galateni 3:13"], forYourHeart: "Când te simți părăsit, strigă cu El, nu departe de El. Perdeaua este ruptă: ai cale deschisă spre Tatăl." },
    { verses: [42, 47], heading: "Iosif a îndrăznit să ceară trupul", teaching: teaching("Iosif din Arimateea, sfetnic care aștepta Împărăția, îndrăznește să meargă la Pilat. După confirmarea morții, coboară trupul, îl înfășoară și îl pune într-un mormânt săpat în stâncă.", "Moartea lui Isus nu a fost aparență: sutașul o confirmă, trupul este îngropat, iar femeile văd locul. Tăcerea mormântului pregătește vestea învierii și cheamă credința să rămână chiar atunci când nu vede încă dimineața."), crossRefs: ["Isaia 53:9", "Ioan 19:38-42", "1 Corinteni 15:3-4"], forYourHeart: "Există un timp când credința nu vede decât piatra. Rămâi aproape și ține minte cuvântul Lui: mormântul nu este sfârșitul." },
  ],
  prayer: "Împărate răstignit, Îți mulțumim că ai luat locul vinovatului și ai rămas pe cruce pentru noi. Prin sângele Tău, perdeaua s-a rupt și avem intrare la Tatăl. Dă-ne curajul lui Iosif și statornicia femeilor, ca să rămânem lângă Tine și în întuneric. Amin.",
})
