import { marcuChapter, teaching } from "./marcuHelpers.js"

export const MARCU_13 = marcuChapter({
  number: 13,
  title: "Marcu 13 — Vegheați până la sfârșit",
  summary: "Isus vestește dărâmarea Templului, necazuri, prigonire și venirea Fiului omului. El nu dă un calendar pentru curiozitate, ci pregătește ucenici statornici, care mărturisesc prin Duhul Sfânt și veghează.",
  literaryContext: "După judecata nerodirii Templului, Isus părăsește clădirea și vorbește de pe Muntele Măslinilor despre căderea ei și despre sfârșit. Profeția apropie evenimentele din anul 70 de împlinirea finală, chemând fiecare generație la discernământ.",
  historicalContext: "Templul lui Irod era renumit pentru pietrele uriașe și frumusețea lui, dar romanii l-au distrus în anul 70. «Urâciunea pustiirii» preia limbajul lui Daniel. Acoperișurile plate și fuga iarna sau în Sabat arătau urgența unei crize reale în Iudeea.",
  units: [
    { verses: [1, 13], heading: "Să nu vă înșele cineva", teaching: teaching("Ucenicii admiră pietrele Templului, iar Isus spune că nu va rămâne piatră pe piatră. Ce pare de neclintit în lumea religioasă poate cădea; numai cuvântul Lui rămâne.", "Semnele timpurii — hristoși mincinoși, războaie, cutremure și foamete — sunt începutul durerilor, nu un calendar care permite calcule. Ucenicul nu aleargă după panică și senzațional, ci se păzește de înșelare.", "Prigonirea devine prilej de mărturie. Duhul Sfânt va da cuvântul necesar, iar cel ce va răbda până la sfârșit va fi mântuit. Statornicia nu înseamnă lipsa fricii, ci fidelitate în mijlocul ei."), crossRefs: ["Daniel 9:26", "Fapte 4:8-12", "2 Timotei 3:12"], forYourHeart: "Nu-ți sprijini credința pe clădiri, instituții sau liniștea vremurilor. Ține-te de cuvântul Lui și fii gata să mărturisești." },
    { verses: [14, 27], heading: "Fiul omului venind cu mare putere", teaching: teaching("Isus descrie o fugă urgentă și un necaz greu. Avertismentul a avut o apropiată împlinire în căderea Ierusalimului, dar limbajul privește și spre confruntarea finală. Chemarea nu este la eroism nechibzuit, ci la ascultare trează.", "Hristoșii mincinoși și semnele înșelătoare cer discernământ. Domnul nu va veni ascuns într-un colț pe care doar inițiații îl cunosc: Fiul omului va fi văzut cu putere și slavă, iar îngerii vor aduna pe aleșii Lui.", "Creștinii înțeleg detaliile cronologiei în moduri diferite. Emanus nu fixează o schemă disputată; centrul sigur este Persoana care vine și porunca de a rămâne credincios."), crossRefs: ["Daniel 7:13-14", "Matei 24:15-31", "1 Tesaloniceni 4:16-18"], forYourHeart: "Nu căuta secretele fricii; privește spre Fiul omului. Cel care vine în slavă este Același care Și-a dat viața pentru tine." },
    { verses: [28, 37], heading: "Ce vă zic vouă, zic tuturor: Vegheați", teaching: teaching("Smochinul îi învață să recunoască apropierea vremii, iar cuvintele lui Isus sunt mai trainice decât cerul și pământul. Totuși, ziua și ceasul nu sunt date ucenicilor pentru calcul.", "Pilda stăpânului plecat mută atenția de la dată la datorie. Fiecărui slujitor i-a fost încredințată o lucrare, iar portarului veghea. A veghea înseamnă să fii găsit făcând astăzi ceea ce ți-a încredințat Domnul, nu consumându-ți viața ghicind mâine."), crossRefs: ["Matei 24:32-51", "Fapte 1:6-8", "1 Petru 4:7-10"], forYourHeart: "Pregătirea pentru venirea Lui nu este un tabel, ci o viață credincioasă. Fă astăzi lucrarea pusă în mâna ta." },
  ],
  prayer: "Doamne Isuse, păzește-ne de înșelare, panică și curiozitate fără ascultare. Dă-ne cuvânt prin Duhul Sfânt când trebuie să mărturisim, statornicie în necaz și ochi ațintiți spre venirea Ta. Găsește-ne veghetori și credincioși în lucrarea încredințată. Amin.",
})
