import { marcuChapter, teaching } from "./marcuHelpers.js"

export const MARCU_10 = marcuChapter({
  number: 10,
  title: "Marcu 10 — Ce a unit Dumnezeu și calea slujitorului",
  summary: "Isus vorbește despre legământul căsătoriei, primește copiii, îl cheamă pe omul bogat să lase stăpânirea averii și vestește a treia oară crucea. Ambiția lui Iacov și Ioan este răspunsă prin modelul Fiului omului, iar Bartimeu Îl urmează după ce primește vederea.",
  literaryContext: "Capitolul continuă lecția despre măreție. Copilul, omul bogat, cei doi fii ai lui Zebedei și cerșetorul orb arată patru feluri de a veni la Isus. Drumul urcă spre Ierusalim, iar crucea devine măsura căsătoriei, averii, conducerii și uceniciei.",
  historicalContext: "Dezbaterea despre divorț pornea de la interpretări diferite ale lui Deuteronom 24. Copiii erau lipsiți de statut, bogăția era adesea privită ca semn sigur al favorii divine, iar Bartimeu depindea de mila trecătorilor la ieșirea din Ierihon.",
  units: [
    { verses: [1, 12], heading: "Ce a împreunat Dumnezeu", teaching: teaching("Fariseii întreabă despre divorț ca să-L ispitească. Isus îi duce dincolo de concesia dată din pricina împietririi inimii, înapoi la creație: Dumnezeu a făcut bărbat și femeie, iar cei doi devin un singur trup. Căsătoria este legământ, nu obiect de consum.", "Cuvintele sunt ferme, dar nu dau voie nimănui să țină o persoană în primejdie. În caz de abuz, siguranța vine întâi și este nevoie de ajutor pastoral, juridic și profesional. Creștinii aplică unele situații de divorț și recăsătorire diferit; Emanus nu înlocuiește biserica locală și discernământul matur."), crossRefs: ["Geneza 2:24", "Matei 19:1-12", "1 Corinteni 7:10-16"], forYourHeart: "Nu întreba cât de puțin poți păstra din legământ, ci cum poți iubi cu credincioșia Celui care nu te părăsește." },
    { verses: [13, 31], heading: "Primește Împărăția ca un copilaș", teaching: teaching("Isus îi mustră pe ucenicii care opresc copiii: Împărăția se primește, nu se câștigă prin rang. Copilul vine cu mâinile goale și depinde de cel care îl primește.", "Omul bogat vine moral, sincer și alergând, iar Isus îl iubește. Totuși, un lucru îi lipsește: averea îi stăpânește inima. Chemarea de a vinde totul a fost adresată lui ca să descopere idolul; nu este o formulă identică pentru fiecare, dar este o întrebare pentru toți: ce nu pot pune în mâna lui Isus?", "Ceea ce este imposibil la oameni este posibil la Dumnezeu. Cine lasă pentru Hristos primește o familie nouă și viața veșnică, împreună cu prigoniri; Evanghelia nu promite prosperitate, ci pe Hristos."), crossRefs: ["Matei 19:13-30", "Luca 18:15-30", "1 Timotei 6:17-19"], forYourHeart: "Vino cu mâinile copilului și lasă-L să numească lucrul care te ține. Privirea Lui nu este dispreț, ci iubire care te cheamă liber." },
    { verses: [32, 45], heading: "Fiul omului a venit să slujească", teaching: teaching("Pe drumul spre Ierusalim, Isus spune limpede că va fi batjocorit, biciuit, omorât și va învia. Iacov și Ioan cer locurile de cinste; chiar lângă vestirea crucii, firea caută tronul.", "Paharul și botezul vorbesc despre suferința Lui, dar locurile nu se împart prin favoritism. Conducătorii lumii stăpânesc peste oameni; între ucenici, cel mare este slujitor. Isus Însuși este măsura: Fiul omului n-a venit să I se slujească, ci să slujească și să-Și dea viața răscumpărare pentru mulți."), words: [{ original: "λύτρον", transliteration: "lytron", language: "greaca", meaning: "preț de răscumpărare plătit pentru eliberarea unui rob sau captiv." }], crossRefs: ["Isaia 53:10-12", "Filipeni 2:5-8", "1 Petru 1:18-19"], forYourHeart: "Nu căuta locul de lângă tron; caută ligheanul și prosopul. Împărăția Îl recunoaște pe Hristos în cel care slujește." },
    { verses: [46, 52], heading: "Rabuni, să capăt vederea", teaching: teaching("Bartimeu aude că trece Isus din Nazaret și strigă: «Fiul lui David, ai milă de mine!». Mulțimea îl ceartă, dar el strigă mai tare. Credința nu lasă rușinea impusă de oameni să-i închidă gura.", "Isus Se oprește și îl cheamă. Orbul își aruncă haina, spune limpede ce dorește și primește vederea. Apoi nu pleacă în altă direcție, ci Îl urmează pe Isus pe drum — drumul care duce la Ierusalim și la cruce."), crossRefs: ["Matei 20:29-34", "Luca 18:35-43", "Psalmul 146:8"], forYourHeart: "Strigă-I nevoia pe nume și, când îți deschide ochii, urmează-L pe drum, nu doar până la minune." },
  ],
  prayer: "Doamne Isuse, păzește legămintele noastre, eliberează-ne de idolii pe care nu-i putem lăsa și dă-ne mâinile goale ale copilului. Vindecă ambiția din noi și fă-ne slujitori după chipul Tău. Deschide-ne ochii ca lui Bartimeu și ține-ne pe urmele Tale până la cruce și înviere. Amin.",
})
