import { marcuChapter, teaching } from "./marcuHelpers.js"

export const MARCU_9 = marcuChapter({
  number: 9,
  title: "Marcu 9 — Slava, credința și calea smereniei",
  summary: "Isus Se schimbă la față înaintea a trei ucenici, eliberează un copil pe care ei nu-l putuseră ajuta și vestește din nou crucea. Apoi răstoarnă ambiția lor, așezând în mijloc un copil, și îi cheamă la o luptă fără compromis cu păcatul.",
  literaryContext: "Mărturisirea lui Petru și întâia vestire a crucii sunt urmate de o vedere a slavei. Coborârea de pe munte duce însă direct la suferință, necredință și slujire. Marcu arată că slava lui Hristos nu ocolește crucea, iar puterea nu poate fi despărțită de rugăciune și smerenie.",
  historicalContext: "Muntele schimbării la față nu este numit. Moise reprezintă Legea, iar Ilie prorocii; glasul Tatălui Îl așază pe Fiul deasupra amândurora. Copiii nu aveau rang social, iar moara trasă de animale și gheena din valea Hinom ofereau imagini puternice pentru avertismentele Domnului.",
  units: [
    { verses: [1, 13], heading: "Pe El să-L ascultați", teaching: teaching("Isus spune că unii vor vedea Împărăția venită cu putere, apoi îi ia pe Petru, Iacov și Ioan pe munte. Chipul și hainele Lui strălucesc, iar Moise și Ilie vorbesc cu El. Slava nu este produsul rafinării omenești, ci descoperirea a ceea ce este Fiul.", "Petru propune trei colibe, punându-i pe toți pe același plan. Glasul Tatălui îl corectează: «Acesta este Fiul Meu preaiubit: de El să ascultați!». Când norul trece, rămâne Isus singur. În Noul Legământ nu avem nevoie de alt mijlocitor; Legea și prorocii duc la Fiul.", "Coborând, Isus vorbește iar despre înviere și suferință. Slava adevărată nu ne scutește de cruce; ea ne întărește să mergem pe calea ei."), crossRefs: ["Matei 17:1-13", "Luca 9:28-36", "Evrei 1:1-3"], forYourHeart: "Nu-L așeza pe Isus lângă niciun om, oricât de mare. Ascultă-L direct și urmează-L de pe munte până la cruce." },
    { verses: [14, 29], heading: "Cred; ajută necredinței mele", teaching: teaching("La poalele muntelui, ucenicii sunt învinși înaintea unui copil chinuit. Autoritatea primită nu lucrează mecanic; necredința și lipsa rugăciunii pot lăsa nefolosit ceea ce Domnul a dăruit.", "Tatăl spune: «Dacă poți face ceva», iar Isus întoarce întrebarea spre credință. Răspunsul sincer — «Cred, Doamne! Ajută necredinței mele» — nu ascunde slăbiciunea, ci o aduce la El. Isus eliberează copilul și îl ridică de mână: răul trântește, Domnul ridică.", "În casă, Isus spune că acest soi iese prin rugăciune. Nu este o formulă, ci viața dependentă de Dumnezeu, în care puterea vine din părtășie, nu din reputația slujitorului."), crossRefs: ["Matei 17:14-21", "Luca 9:37-43", "Evrei 11:6"], forYourHeart: "Nu te preface că ai o credință pe care n-o ai. Adu-I și credința, și necredința; El primește adevărul și ridică." },
    { verses: [30, 37], heading: "Cel dintâi să fie slujitorul tuturor", teaching: teaching("Isus vestește din nou moartea și învierea, dar ucenicii se tem să întrebe. Pe drum discută cine este mai mare. Crucea și ambiția merg în direcții opuse: El vorbește despre dăruirea vieții, ei despre rang.", "Domnul așază un copil în mijloc și spune că primul trebuie să fie ultimul și slujitorul tuturor. În Împărăție, măreția nu este capacitatea de a-i pune pe alții sub tine, ci disponibilitatea de a primi pe cel fără rang și de a depinde de Tatăl ca un copil."), crossRefs: ["Matei 18:1-5", "Marcu 10:42-45", "Filipeni 2:5-8"], forYourHeart: "Dumnezeu nu caută cât de mare pari, ci cât de disponibil ești. Primește locul slujitorului și nu te teme să depinzi de El." },
    { verses: [38, 50], heading: "Aveți sare în voi înșivă", teaching: teaching("Ioan vrea să oprească un om care lucra în Numele lui Isus fiindcă nu mergea cu grupul lor. Domnul taie duhul de partidă: cine nu este împotriva Lui este pentru El, iar până și un pahar cu apă dat pentru Hristos nu rămâne nerăsplătit.", "Apoi vine avertismentul: să faci pe un om slab să cadă este atât de grav încât ar fi mai bine să fii aruncat în mare. Mâna, piciorul și ochiul nu sunt chemate la mutilare, ci la o despărțire radicală de orice prilej de păcat. Veșnicia valorează mai mult decât orice lucru folositor care ne trage departe de Dumnezeu.", "Sarea păstrează curăția și pacea. Râvna împotriva păcatului nu trebuie să devină asprime împotriva fraților; ucenicul păzește și sfințenia, și pacea."), crossRefs: ["Numeri 11:26-29", "1 Corinteni 8:9-13", "Coloseni 4:6"], forYourHeart: "Nu întreba doar dacă un lucru îți este permis; întreabă dacă zidește și dacă poate răni pe cineva mai slab." },
  ],
  prayer: "Doamne Isuse, deschide-ne ochii spre slava Ta și ține-ne pe calea crucii. Ajută necredinței noastre, fă-ne oameni ai rugăciunii și eliberează-ne de ambiția de a fi cei dintâi. Dă-ne hotărâre împotriva păcatului, blândețe față de oameni și sare în noi înșine, ca să trăim în curăție și pace. Amin.",
})
