import { marcuChapter, teaching } from "./marcuHelpers.js"

export const MARCU_2 = marcuChapter({
  number: 2,
  title: "Marcu 2 — Iertarea, chemarea și vinul cel nou",
  summary: "Isus iartă și vindecă slăbănogul, îl cheamă pe Levi și stă la masă cu păcătoșii. Prin întrebările despre post și Sabat, El arată că nu a venit să peticească viața veche, ci să aducă viața nouă sub autoritatea Fiului omului.",
  literaryContext: "După autoritatea arătată prin minuni în capitolul 1, Marcu prezintă patru confruntări cu liderii religioși. Fiecare întrebare ajunge la identitatea lui Isus: Cel care iartă păcatele, cheamă păcătoșii, este Mirele și Domnul Sabatului.",
  historicalContext: "Acoperișurile caselor puteau fi desfăcute pentru a coborî un pat. Vameșii lucrau pentru puterea romană și erau socotiți trădători. Fariseii adăugaseră poruncii Sabatului numeroase reguli, deși Legea îngăduia călătorului să smulgă spice cu mâna.",
  units: [
    { verses: [1, 12], heading: "Păcatele îți sunt iertate", teaching: teaching("Patru oameni nu se opresc la ușa blocată, ci desfac acoperișul și își coboară prietenul înaintea lui Isus. Domnul vede credința lor și atinge întâi nevoia cea mai adâncă: «Fiule, păcatele îți sunt iertate».", "Cărturarii înțeleg că numai Dumnezeu poate ierta, dar nu recunosc cine este înaintea lor. Isus vindecă omul ca să arate că Fiul omului are putere să ierte. Vindecarea trupească rămâne în voia Lui; iertarea este făgăduită oricui vine cu pocăință și credință."), crossRefs: ["Matei 9:1-8", "Luca 5:17-26", "Isaia 43:25"], forYourHeart: "Nu aștepta să fii întreg ca să vii. Slăbănogul a primit iertarea înainte să se ridice." },
    { verses: [13, 17], heading: "Nu cei sănătoși au nevoie de doctor", teaching: teaching("Isus îl vede pe Levi la vamă și îi spune «Vino după Mine». Levi se ridică și deschide masa pentru alți vameși și păcătoși. Harul primit devine ușă pentru cei care se credeau prea departe.", "Isus nu aprobă păcatul, ci vine ca Doctor pentru cei care își recunosc boala. Primejdia cea mai mare este să te crezi sănătos și să nu mai ceri ajutor."), crossRefs: ["Matei 9:9-13", "Luca 5:27-32", "Luca 15:1-2"], forYourHeart: "Doctorul a venit tocmai pentru cei bolnavi. Recunoaște-ți starea și ia loc la masa harului." },
    { verses: [18, 22], heading: "Vinul nou în burdufuri noi", teaching: teaching("Isus Se numește Mirele. Postul nu este spectacol religios, ci căutarea lui Dumnezeu; cât timp Mirele era cu ei, ucenicii trăiau bucuria prezenței Lui, iar după plecarea Lui aveau să postească.", "Peticul nou rupe haina veche, iar vinul nou sparge burdufurile vechi. Isus nu adaugă o îmbunătățire peste viața condusă de sine; El dă viață nouă, care cere inimă și ascultare noi."), crossRefs: ["Matei 9:14-17", "Luca 5:33-39", "2 Corinteni 5:17"], forYourHeart: "Nu petici viața veche cu puțină religie. Lasă-L să-ți dea și vinul, și vasul nou." },
    { verses: [23, 28], heading: "Domn și al Sabatului", teaching: teaching("Ucenicii smulg spice, iar fariseii transformă nevoia lor într-o acuzație. Isus amintește de David și arată că porunca nu a fost dată ca să zdrobească omul.", "Sabatul a fost făcut pentru om, nu omul pentru Sabat, iar Fiul omului este Domn și al Sabatului. Creștinii înțeleg aplicarea zilei de odihnă în moduri diferite; adevărul central este că odihna este dar, iar autoritatea aparține lui Isus."), crossRefs: ["1 Samuel 21:1-6", "Deuteronom 23:25", "Matei 12:1-8"], forYourHeart: "Nu transforma darul lui Dumnezeu într-un jug pentru tine sau pentru altul. Vino la Domnul odihnei." },
  ],
  prayer: "Doamne Isuse, Îți mulțumim că ierți, chemi și vindeci. Dă-ne credința care trece de acoperiș, smerenia bolnavului care cere Doctorul și curajul de a lăsa viața veche. Păzește-ne de reguli fără inimă și odihnește-ne sub domnia Ta. Amin.",
})
