import { marcuChapter, teaching } from "./marcuHelpers.js"

export const MARCU_14 = marcuChapter({
  number: 14,
  title: "Marcu 14 — Trupul dat, paharul și noaptea încercării",
  summary: "O femeie Îl unge pe Isus pentru îngropare, Iuda pregătește vânzarea, iar Domnul așază Cina Legământului. În Ghetsimani El primește voia Tatălui, apoi este prins, judecat și mărturisește că este Hristosul, în timp ce Petru se leapădă și plânge.",
  literaryContext: "După chemarea la veghere, ucenicii intră chiar în noaptea în care nu reușesc să vegheze. Marcu împletește devotamentul femeii cu trădarea lui Iuda, ascultarea Fiului cu fuga ucenicilor și mărturisirea lui Isus cu lepădarea lui Petru.",
  historicalContext: "Paștele amintea eliberarea din Egipt, iar pâinea și paharul primesc acum sensul trupului și sângelui Legământului. Ghetsimani înseamnă «teasc de untdelemn». Sinedriul căuta mărturii împotriva lui Isus, iar ruperea hainelor de către marele preot semnala acuzația de hulă.",
  units: [
    { verses: [1, 11], heading: "Ea a făcut un lucru frumos", teaching: teaching("În timp ce conducătorii caută să-L omoare, o femeie sparge un vas cu mir scump și îl toarnă peste Isus. Ceilalți numesc gestul risipă; El îl numește lucru frumos. Dragostea vede o ocazie pe care socoteala rece o pierde.", "Grija pentru săraci rămâne o poruncă, nu un pretext împotriva închinării. Femeia a făcut ce a putut și a uns trupul Lui pentru îngropare. În contrast, Iuda merge să-L vândă pentru bani."), crossRefs: ["Ioan 12:1-8", "Deuteronom 15:11", "Marcu 12:41-44"], forYourHeart: "Nu amâna gestul de dragoste pe care îl poți face acum. Domnul nu măsoară doar prețul, ci inima care Îl recunoaște." },
    { verses: [12, 31], heading: "Acesta este sângele Legământului", teaching: teaching("Isus pregătește Paștele și arată că trădarea nu-L surprinde. La masă, pâinea devine semnul trupului dat, iar paharul semnul sângelui Legământului vărsat pentru mulți. El merge la cruce ca Miel care Se dăruiește, nu ca victimă fără voie.", "Toți se vor poticni, iar Petru promite mai mult decât își cunoaște puterea. Încrederea în sine poate vorbi sincer și totuși să cadă repede. Isus vede căderea înainte de a veni și privește deja dincolo de ea, spre întâlnirea din Galileea."), crossRefs: ["Exod 12:1-14", "Ieremia 31:31-34", "1 Corinteni 11:23-26"], forYourHeart: "Primește pâinea și paharul ca veste că El S-a dat pentru tine. Nu te sprijini pe promisiunea ta, ci pe credincioșia Lui." },
    { verses: [32, 52], heading: "Nu ce voiesc Eu, ci ce voiești Tu", teaching: teaching("În Ghetsimani, Isus este cuprins de întristare până la moarte și cere ca paharul să treacă, dacă este posibil. Rugăciunea Lui nu ascunde durerea: «Ava, Tată» și «nu ce voiesc Eu, ci ce voiești Tu» stau împreună. Supunerea nu înseamnă absența luptei, ci predarea voii în mijlocul ei.", "Ucenicii dorm, deși duhul este plin de râvnă și trupul neputincios. Iuda vine cu sărutul trădării, iar ceilalți fug. Isus nu este luat fiindcă Îi lipsește puterea, ci pentru că primește ceasul și Scriptura."), crossRefs: ["Psalmul 42:5", "Evrei 5:7-9", "Filipeni 2:8"], forYourHeart: "Poți spune Tatălui exact cât doare și totuși să-I predai voia. Rugăciunea adevărată nu joacă teatru; rămâne în mâna Lui." },
    { verses: [53, 72], heading: "Eu sunt", teaching: teaching("Mărturiile împotriva lui Isus nu se potrivesc. Când marele preot Îl întreabă dacă este Hristosul, Fiul Celui binecuvântat, El răspunde «Da, sunt» și vestește pe Fiul omului la dreapta puterii. Condamnat ca hulitor, El spune adevărul pentru care va muri.", "În curte, Petru neagă de trei ori că-L cunoaște. Cântatul cocoșului îi trezește amintirea cuvântului Domnului și el plânge. Lacrimile nu șterg singure vina, dar arată începutul întoarcerii; după înviere, harul îl va căuta pe nume."), crossRefs: ["Daniel 7:13-14", "Psalmul 110:1", "Marcu 16:7", "Ioan 21:15-19"], forYourHeart: "Când ai căzut, lasă cuvântul Lui să te trezească și plângi înaintea harului, nu departe de el. El știa și tot te-a chemat." },
  ],
  prayer: "Doamne Isuse, primește dragostea noastră și păzește-ne de iubirea banilor și de încrederea în sine. Îți mulțumim pentru trupul dat și sângele Legământului. Învață-ne rugăciunea din Ghetsimani și caută-ne prin har când ne lepădăm. Fă-ne să mărturisim adevărul lângă Tine. Amin.",
})
