/*
 * Textul Evangheliei după Marcu, Cornilescu, editia corectata (RCCV).
 * Sursa de colationare: https://github.com/seven1m/open-bibles (ron-rccv.usfx.xml)
 *
 * Indicele zero al fiecărui capitol rămâne gol, astfel încât numărul
 * versetului să fie și indicele lui. Comentariul nu intră în acest fișier.
 */

const MARCU_TEXT: readonly (readonly string[])[] = [

  [],
  [
    "",
    "Începutul Evangheliei lui Isus Hristos, Fiul lui Dumnezeu.",
    "După cum este scris în prorocul Isaia: „Iată, trimit înaintea Ta pe solul Meu, care Îţi va pregăti calea…",
    "glasul celui ce strigă în pustiu: „Pregătiţi calea Domnului, neteziţi-I cărările”,",
    "a venit Ioan care boteza în pustiu, propovăduind botezul pocăinţei spre iertarea păcatelor.",
    "Tot ţinutul Iudeii şi toţi locuitorii Ierusalimului au început să iasă la el; şi, mărturisindu-şi păcatele, erau botezaţi de el în râul Iordan.",
    "Ioan era îmbrăcat cu o haină de păr de cămilă, şi împrejurul mijlocului era încins cu un brâu de curea. El se hrănea cu lăcuste şi miere sălbatică.",
    "Ioan propovăduia şi zicea: „După mine vine Cel ce este mai puternic decât mine, căruia eu nu sunt vrednic să mă plec să-I dezleg curelele încălţămintei.",
    "Eu, da, v-am botezat cu apă; dar El vă va boteza cu Duhul Sfânt.”",
    "În vremea aceea, a venit Isus din Nazaretul Galileii şi a fost botezat de Ioan în Iordan.",
    "Şi îndată, când ieşea Isus din apă, el a văzut cerurile deschise şi Duhul coborându-Se peste El ca un porumbel.",
    "Şi din ceruri s-a auzit un glas care zicea: „Tu eşti Fiul Meu preaiubit, în Tine Îmi găsesc toată plăcerea Mea.”",
    "Îndată Duhul a mânat pe Isus în pustiu,",
    "unde a stat patruzeci de zile, fiind ispitit de Satana. Acolo stătea împreună cu fiarele sălbatice, şi-I slujeau îngerii.",
    "După ce a fost închis Ioan, Isus a venit în Galileea şi propovăduia Evanghelia lui Dumnezeu.",
    "El zicea: „S-a împlinit vremea, şi Împărăţia lui Dumnezeu este aproape. Pocăiţi-vă şi credeţi în Evanghelie.”",
    "Pe când trecea Isus pe lângă Marea Galileii, a văzut pe Simon şi pe Andrei, fratele lui Simon, aruncând o mreajă în mare, căci erau pescari.",
    "Isus le-a zis: „Veniţi după Mine, şi vă voi face pescari de oameni.”",
    "Îndată, ei şi-au lăsat mrejele şi au mers după El.",
    "A mers puţin mai departe şi a văzut pe Iacov, fiul lui Zebedei, şi pe Ioan, fratele lui, care, şi ei, erau într-o corabie şi îşi dregeau mrejele.",
    "Îndată i-a chemat; şi ei au lăsat pe tatăl lor, Zebedei, în corabie cu cei ce lucrau pe plată şi au mers după El.",
    "S-au dus la Capernaum. Şi, în ziua Sabatului, Isus a intrat îndată în sinagogă şi a început să înveţe pe norod.",
    "Oamenii erau uimiţi de învăţătura Lui; căci îi învăţa ca unul care are putere, nu cum îi învăţau cărturarii.",
    "În sinagoga lor era un om care avea un duh necurat. El a început să strige:",
    "„Ce avem noi a face cu Tine, Isuse din Nazaret? Ai venit să ne pierzi? Te ştiu cine eşti: eşti Sfântul lui Dumnezeu!”",
    "Isus l-a certat şi i-a zis: „Taci şi ieşi afară din omul acesta!”",
    "Şi duhul necurat a ieşit din el, scuturându-l cu putere şi scoţând un strigăt mare.",
    "Toţi au rămas înmărmuriţi, aşa că se întrebau unii pe alţii: „Ce este aceasta? O învăţătură nouă! El porunceşte ca un stăpân chiar şi duhurilor necurate, şi ele Îl ascultă!”",
    "Şi îndată I s-a dus vestea în toate împrejurimile Galileii.",
    "După ce a ieşit din sinagogă, a intrat împreună cu Iacov şi Ioan în casa lui Simon şi a lui Andrei.",
    "Soacra lui Simon zăcea în pat prinsă de friguri; şi îndată au vorbit lui Isus despre ea.",
    "El a venit, a apucat-o de mână, a ridicat-o în sus, şi au lăsat-o frigurile. Apoi ea a început să le slujească.",
    "Seara, după asfinţitul soarelui, au adus la El pe toţi bolnavii şi îndrăciţii.",
    "Şi toată cetatea era adunată la uşă.",
    "El a vindecat pe mulţi care pătimeau de felurite boli; de asemenea, a scos mulţi draci şi nu lăsa pe draci să vorbească, pentru că-L cunoşteau.",
    "A doua zi dimineaţa, pe când era încă întuneric de tot, Isus S-a sculat, a ieşit şi S-a dus într-un loc pustiu. Şi Se ruga acolo.",
    "Simon şi ceilalţi care erau cu El s-au dus să-L caute;",
    "şi, când L-au găsit, I-au zis: „Toţi Te caută.”",
    "El le-a răspuns: „Haidem să mergem în altă parte, prin târgurile şi satele vecine, ca să propovăduiesc şi acolo; căci pentru aceasta am ieşit.”",
    "Şi S-a dus să propovăduiască în sinagogi, prin toată Galileea; şi scotea dracii.",
    "A venit la El un lepros, care s-a aruncat în genunchi înaintea Lui, Îl ruga şi-I zicea: „Dacă vrei, poţi să mă cureţi.”",
    "Lui Isus I s-a făcut milă de el, a întins mâna, S-a atins de el şi i-a zis: „Da, voiesc, fii curăţat!”",
    "Îndată l-a lăsat lepra, şi s-a curăţat.",
    "Isus i-a poruncit cu tot dinadinsul, i-a spus să plece numaidecât",
    "şi i-a zis: „Vezi să nu spui nimănui nimic; ci du-te de te arată preotului şi adu pentru curăţarea ta ce a poruncit Moise, ca mărturie pentru ei.”",
    "Dar omul acela, după ce a plecat, a început să vestească şi să spună în gura mare lucrul acesta, aşa că Isus nu mai putea să intre pe faţă în nicio cetate; ci stătea afară, în locuri pustii, şi veneau la El din toate părţile.",
  ],
  [
    "",
    "După câteva zile, Isus S-a întors în Capernaum. S-a auzit că este în casă",
    "şi s-au adunat îndată aşa de mulţi, că nu putea să-i mai încapă locul dinaintea uşii. El le vestea Cuvântul.",
    "Au venit la El nişte oameni care I-au adus un slăbănog, purtat de patru inşi.",
    "Fiindcă nu puteau să ajungă până la El, din pricina norodului, au desfăcut acoperişul casei unde era Isus şi, după ce l-au spart, au coborât pe acolo patul în care zăcea slăbănogul.",
    "Când le-a văzut Isus credinţa, a zis slăbănogului: „Fiule, păcatele îţi sunt iertate!”",
    "Unii din cărturari, care erau de faţă, se gândeau în inimile lor:",
    "„Cum vorbeşte Omul acesta astfel? Huleşte! Cine poate să ierte păcatele decât numai Dumnezeu?”",
    "Îndată, Isus a cunoscut, prin duhul Său, că ei gândeau astfel în ei şi le-a zis: „Pentru ce aveţi astfel de gânduri în inimile voastre?",
    "Ce este mai lesne: a zice slăbănogului: „Păcatele îţi sunt iertate”, ori a zice: „Scoală-te, ridică-ţi patul şi umblă”?",
    "Dar, ca să ştiţi că Fiul omului are putere pe pământ să ierte păcatele,",
    "„Ţie îţi poruncesc”, a zis El slăbănogului, „scoală-te, ridică-ţi patul şi du-te acasă.”",
    "Şi îndată, slăbănogul s-a sculat, şi-a ridicat patul şi a ieşit afară în faţa tuturor; aşa că toţi au rămas uimiţi şi slăveau pe Dumnezeu şi ziceau: „Niciodată n-am văzut aşa ceva!”",
    "Isus a ieşit iarăşi la mare. Toată mulţimea venea la El; şi El învăţa pe toţi.",
    "Când trecea pe acolo, a văzut pe Levi, fiul lui Alfeu, şezând la vamă. Şi i-a zis: „Vino după Mine!” Levi s-a sculat şi a mers după El.",
    "Pe când şedea Isus la masă în casa lui Levi, mulţi vameşi şi păcătoşi au şezut şi ei la masă cu El şi cu ucenicii Lui; căci erau mulţi care mergeau de obicei după El.",
    "Cărturarii şi fariseii, când L-au văzut mâncând cu vameşii şi cu păcătoşii, au zis ucenicilor Lui: „De ce mănâncă El şi bea cu vameşii şi cu păcătoşii?”",
    "Isus, când a auzit acest lucru, le-a zis: „Nu cei sănătoşi au trebuinţă de doctor, ci cei bolnavi. Eu am venit să chem la pocăinţă nu pe cei neprihăniţi, ci pe cei păcătoşi.”",
    "Ucenicii lui Ioan şi fariseii obişnuiau să postească. Ei au venit şi au zis lui Isus: „Pentru ce ucenicii lui Ioan şi ai fariseilor postesc, iar ucenicii Tăi nu postesc?”",
    "Isus le-a răspuns: „Oare pot posti nuntaşii câtă vreme este mirele cu ei? Câtă vreme au pe mire cu ei, nu pot posti.",
    "Vor veni zile când va fi luat mirele de la ei, şi atunci vor posti în ziua aceea.",
    "Nimeni nu coase un petic de postav nou la o haină veche; altfel, peticul de postav nou rupe o parte din cel vechi, şi mai rea ruptură se face.",
    "Şi nimeni nu pune vin nou în burdufuri vechi; altfel, vinul cel nou sparge burdufurile, şi vinul se varsă, iar burdufurile se prăpădesc; ci vinul nou este pus în burdufuri noi.”",
    "S-a întâmplat că într-o zi de Sabat, Isus trecea prin lanurile de grâu. Ucenicii Lui, pe când mergeau, au început să smulgă spice de grâu.",
    "Fariseii I-au zis: „Vezi, de ce fac ei ce nu este îngăduit să facă în ziua Sabatului?”",
    "Isus le-a răspuns: „Oare n-aţi citit niciodată ce a făcut David, când a fost în nevoie şi când a flămânzit el şi cei ce erau împreună cu el?",
    "Cum a intrat în casa lui Dumnezeu, în zilele marelui preot Abiatar, şi a mâncat pâinile pentru punerea înaintea Domnului, pe care nu este îngăduit să le mănânce decât preoţii? Şi cum a dat din ele chiar şi celor ce erau cu el?”",
    "Apoi le-a zis: „Sabatul a fost făcut pentru om, iar nu omul pentru Sabat;",
    "aşa că Fiul omului este Domn chiar şi al Sabatului.”",
  ],
  [
    "",
    "Isus a intrat din nou în sinagogă. Acolo se afla un om cu mâna uscată.",
    "Ei pândeau pe Isus să vadă dacă-l va vindeca în ziua Sabatului, ca să-L poată învinui.",
    "Şi Isus a zis omului care avea mâna uscată: „Scoală-te şi stai la mijloc!”",
    "Apoi le-a zis: „Este îngăduit în ziua Sabatului să faci bine sau să faci rău? Să scapi viaţa cuiva sau s-o pierzi?” Dar ei tăceau.",
    "Atunci, rotindu-Şi privirile cu mânie peste ei şi mâhnit de împietrirea inimii lor, a zis omului: „Întinde-ţi mâna!” El a întins-o, şi mâna i s-a făcut sănătoasă.",
    "Fariseii au ieşit afară şi s-au sfătuit îndată cu irodienii cum să-L piardă.",
    "Isus S-a dus cu ucenicii Săi la mare. După El a mers o mare mulţime de oameni din Galileea; şi o mare mulţime de oameni din Iudeea,",
    "din Ierusalim, din Idumeea, de dincolo de Iordan şi dimprejurul Tirului şi Sidonului, când a auzit tot ce făcea, a venit la El.",
    "Isus a poruncit ucenicilor să-I ţină la îndemână o corăbioară, ca să nu fie îmbulzit de norod.",
    "Căci El vindeca pe mulţi şi de aceea toţi cei ce aveau boli se înghesuiau spre El ca să se atingă de El.",
    "Duhurile necurate, când Îl vedeau, cădeau la pământ înaintea Lui şi strigau: „Tu eşti Fiul lui Dumnezeu.”",
    "Dar El le poruncea îndată cu tot dinadinsul să nu-L facă cunoscut.",
    "În urmă, Isus S-a suit pe munte; a chemat la El pe cine a vrut, şi ei au venit la El.",
    "A rânduit dintre ei doisprezece, ca să-i aibă cu Sine şi să-i trimită să propovăduiască.",
    "Le-a dat şi putere să vindece bolile şi să scoată dracii.",
    "Iată cei doisprezece pe care i-a rânduit: Simon, căruia i-a pus numele Petru;",
    "Iacov, fiul lui Zebedei, şi Ioan, fratele lui Iacov, cărora le-a pus numele Boanerghes, care tălmăcit înseamnă: „Fiii tunetului”;",
    "Andrei; Filip; Bartolomeu; Matei; Toma; Iacov, fiul lui Alfeu; Tadeu; Simon, canaanitul,",
    "şi Iuda Iscarioteanul, care L-a şi vândut.",
    "Au venit în casă şi s-a adunat din nou norodul, aşa că nu puteau nici măcar să prânzească.",
    "Rudele lui Isus, când au auzit cele ce se petreceau, au venit să pună mâna pe El. Căci ziceau: „Şi-a ieşit din minţi.”",
    "Şi cărturarii care se coborâseră din Ierusalim ziceau: „Este stăpânit de Beelzebul; scoate dracii cu ajutorul domnului dracilor.”",
    "Isus i-a chemat la El şi le-a zis, în pilde: „Cum poate Satana să scoată afară pe Satana?",
    "Dacă o împărăţie este dezbinată împotriva ei înseşi, împărăţia aceea nu poate dăinui.",
    "Şi dacă o casă este dezbinată împotriva ei înseşi, casa aceea nu poate dăinui.",
    "Tot astfel, dacă Satana se răscoală împotriva lui însuşi este dezbinat şi nu poate dăinui, ci s-a isprăvit cu el.",
    "Nimeni nu poate să intre în casa unui om tare şi să-i jefuiască gospodăria decât dacă a legat mai întâi pe omul acela tare; numai atunci îi va jefui casa.",
    "Adevărat vă spun că toate păcatele şi toate hulele pe care le vor rosti oamenii li se vor ierta;",
    "dar oricine va huli împotriva Duhului Sfânt nu va căpăta iertare în veac: ci este vinovat de un păcat veşnic.”",
    "Aceasta pentru că ei ziceau: „Are un duh necurat.”",
    "Atunci au venit mama şi fraţii Lui şi, stând afară, au trimis să-L cheme.",
    "Mulţimea şedea în jurul Lui, când I-au spus: „Iată că mama Ta şi fraţii Tăi sunt afară şi Te caută.”",
    "El a răspuns: „Cine este mama Mea şi fraţii Mei?”",
    "Apoi, aruncându-Şi privirile peste cei ce şedeau împrejurul Lui: „Iată”, a zis El, „mama Mea şi fraţii Mei!",
    "Căci oricine face voia lui Dumnezeu, acela Îmi este frate, soră şi mamă.”",
  ],
  [
    "",
    "Isus a început iarăşi să înveţe pe norod lângă mare. Fiindcă se adunase foarte mult norod la El, S-a suit şi a şezut într-o corabie, pe mare; iar tot norodul stătea pe ţărm lângă mare.",
    "Apoi a început să-i înveţe multe lucruri în pilde; şi, în învăţătura pe care le-o dădea, le spunea:",
    "„Ascultaţi! Iată, semănătorul a ieşit să semene.",
    "Pe când semăna, o parte din sămânţă a căzut lângă drum: au venit păsările şi au mâncat-o.",
    "O altă parte a căzut pe un loc stâncos, unde n-avea mult pământ: a răsărit îndată, pentru că n-a dat de un pământ adânc;",
    "dar, când a răsărit soarele, s-a pălit; şi, pentru că n-avea rădăcină, s-a uscat.",
    "O altă parte a căzut între spini; spinii au crescut, au înecat-o şi n-a dat rod.",
    "O altă parte a căzut în pământ bun: a dat rod, care se înălţa şi creştea; şi a adus: una treizeci, alta şaizeci, şi alta o sută.”",
    "Apoi a zis: „Cine are urechi de auzit să audă.”",
    "Când a fost singur, cei ce erau în jurul Lui împreună cu cei doisprezece L-au întrebat despre pilde.",
    "„Vouă”, le-a zis El, „v-a fost dat să cunoaşteţi taina Împărăţiei lui Dumnezeu; dar pentru cei ce sunt afară din numărul vostru, toate lucrurile sunt înfăţişate în pilde;",
    "pentru ca, „măcar că privesc, să privească şi să nu vadă, şi măcar că aud, să audă şi să nu înţeleagă, ca nu cumva să se întoarcă la Dumnezeu şi să li se ierte păcatele.”",
    "El le-a mai zis: „Nu înţelegeţi pilda aceasta? Cum veţi înţelege atunci toate celelalte pilde?",
    "Semănătorul seamănă Cuvântul.",
    "Cei înfăţişaţi prin sămânţa căzută lângă drum sunt aceia în care este semănat Cuvântul; dar după ce l-au auzit, vine Satana îndată şi ia Cuvântul semănat în ei.",
    "Tot aşa, cei înfăţişaţi prin sămânţa căzută în locurile stâncoase sunt aceia care, când aud Cuvântul, îl primesc îndată cu bucurie;",
    "dar n-au rădăcină în ei, ci ţin până la o vreme; şi cum vine un necaz sau o prigonire din pricina Cuvântului, se leapădă îndată de el.",
    "Alţii sunt cei înfăţişaţi prin sămânţa căzută între spini; aceştia sunt cei ce aud Cuvântul;",
    "dar năvălesc în ei grijile lumii, înşelăciunea bogăţiilor şi poftele altor lucruri, care îneacă Cuvântul şi-l fac astfel neroditor.",
    "Alţii apoi sunt înfăţişaţi prin sămânţa căzută în pământ bun. Aceştia sunt cei ce aud Cuvântul, îl primesc şi fac rod: unul treizeci, altul şaizeci şi altul o sută.”",
    "El le-a mai zis: „Oare lumina este adusă ca să fie pusă sub baniţă sau sub pat? Nu este adusă ca să fie pusă în sfeşnic?",
    "Căci nu este nimic ascuns care nu va fi descoperit şi nimic tăinuit care nu va ieşi la lumină.",
    "Dacă are cineva urechi de auzit, să audă.”",
    "El le-a mai zis: „Luaţi seama la ce auziţi. Cu ce măsură veţi măsura, vi se va măsura: şi vi se va da şi mai mult.",
    "Căci celui ce are i se va da; dar de la cel ce n-are se va lua şi ce are.”",
    "El a mai zis: „Cu Împărăţia lui Dumnezeu este ca atunci când aruncă un om sămânţa în pământ;",
    "fie că doarme noaptea, fie că stă treaz ziua, sămânţa încolţeşte şi creşte fără să ştie el cum.",
    "Pământul rodeşte singur: întâi un fir verde, apoi spic, după aceea grâu deplin în spic;",
    "şi când este copt rodul, pune îndată secera în el, pentru că a venit secerişul.”",
    "El a mai zis: „Cu ce vom asemăna Împărăţia lui Dumnezeu sau prin ce pildă o vom înfăţişa?",
    "Se aseamănă cu un grăunte de muştar care, când este semănat în pământ, este cea mai mică dintre toate seminţele de pe pământ;",
    "dar, după ce a fost semănat, creşte şi se face mai mare decât toate zarzavaturile şi face ramuri mari, aşa că păsările cerului îşi pot face cuiburi la umbra lui.”",
    "Isus le vestea Cuvântul prin multe pilde de felul acesta, după cum erau ei în stare să-l priceapă.",
    "Nu le vorbea deloc fără pildă; dar, când era singur la o parte, lămurea ucenicilor Săi toate lucrurile.",
    "În aceeaşi zi, seara, Isus le-a zis: „Să trecem în partea cealaltă.”",
    "După ce au dat drumul norodului, ucenicii L-au luat în corabia în care se afla şi aşa cum era. Împreună cu El mai erau şi alte corăbii.",
    "S-a stârnit o mare furtună de vânt care arunca valurile în corabie, aşa că mai că se umplea corabia.",
    "Şi El dormea la cârmă pe căpătâi. Ucenicii L-au deşteptat şi I-au zis: „Învăţătorule, nu-Ţi pasă că pierim?”",
    "El S-a sculat, a certat vântul şi a zis mării: „Taci! Fără gură!” Vântul a stat şi s-a făcut o linişte mare.",
    "Apoi le-a zis: „Pentru ce sunteţi aşa de fricoşi? Tot n-aveţi credinţă?”",
    "I-a apucat o mare frică şi ziceau unii către alţii: „Cine este Acesta de Îl ascultă chiar şi vântul şi marea?”",
  ],
  [
    "",
    "Au ajuns pe celălalt ţărm al mării, în ţinutul gadarenilor.",
    "Când a ieşit Isus din corabie, L-a întâmpinat îndată un om care ieşea din morminte, stăpânit de un duh necurat.",
    "Omul acesta îşi avea locuinţa în morminte, şi nimeni nu mai putea să-l ţină legat, nici chiar cu un lanţ.",
    "Căci de multe ori fusese legat cu picioarele în obezi şi cu cătuşe la mâini, dar rupsese cătuşele şi sfărâmase obezile, şi nimeni nu-l putea domoli.",
    "Totdeauna, zi şi noapte, stătea în morminte şi pe munţi, ţipând şi tăindu-se cu pietre.",
    "Când a văzut pe Isus de departe, a alergat, I s-a închinat",
    "şi a strigat cu glas tare: „Ce am eu a face cu Tine, Isuse, Fiul Dumnezeului celui Preaînalt? Te jur în Numele lui Dumnezeu, să nu mă chinuieşti!”",
    "Căci Isus îi zicea: „Duh necurat, ieşi afară din omul acesta!”",
    "„Care-ţi este numele?”, l-a întrebat Isus. „Numele meu este „legiune”, a răspuns el, „pentru că suntem mulţi.”",
    "Şi Îl ruga stăruitor să nu-i trimită afară din ţinutul acela.",
    "Acolo, lângă munte, era o turmă mare de porci care păşteau.",
    "Şi dracii L-au rugat şi au zis: „Trimite-ne în porcii aceia, ca să intrăm în ei.”",
    "Isus le-a dat voie. Şi duhurile necurate au ieşit şi au intrat în porci; şi turma s-a repezit de pe râpă în mare: erau aproape două mii, şi s-au înecat în mare.",
    "Porcarii au fugit şi au dat de ştire în cetate şi prin satele vecine. Oamenii au ieşit să vadă ce s-a întâmplat.",
    "Au venit la Isus, şi iată pe cel ce fusese îndrăcit şi avusese legiunea de draci, şezând jos îmbrăcat şi întreg la minte; şi s-au înspăimântat.",
    "Cei ce văzuseră cele întâmplate le-au povestit tot ce se petrecuse cu cel îndrăcit şi cu porcii.",
    "Atunci au început să roage pe Isus să plece din ţinutul lor.",
    "Pe când Se suia El în corabie, omul care fusese îndrăcit Îl ruga să-l lase să rămână cu El.",
    "Isus nu i-a dat voie, ci i-a zis: „Du-te acasă la ai tăi şi povesteşte-le tot ce ţi-a făcut Domnul şi cum a avut milă de tine.”",
    "El a plecat şi a început să vestească prin Decapole tot ce-i făcuse Isus. Şi toţi se minunau.",
    "După ce a trecut Isus iarăşi de cealaltă parte cu corabia, s-a adunat mult norod în jurul Lui. El stătea lângă mare.",
    "Atunci a venit unul din fruntaşii sinagogii, numit Iair. Cum L-a văzut, fruntaşul s-a aruncat la picioarele Lui",
    "şi I-a făcut următoarea rugăminte stăruitoare: „Fetiţa mea trage să moară; rogu-Te, vino de-Ţi pune mâinile peste ea, ca să se facă sănătoasă şi să trăiască.”",
    "Isus a plecat împreună cu el. Şi după El mergea mult norod şi-L îmbulzea.",
    "Şi era o femeie care de doisprezece ani avea o scurgere de sânge.",
    "Ea suferise mult de la mulţi doctori; cheltuise tot ce avea, şi nu simţise nicio uşurare; ba încă îi era mai rău.",
    "A auzit vorbindu-se despre Isus, a venit pe dinapoi prin mulţime şi s-a atins de haina Lui.",
    "Căci îşi zicea ea: „Dacă aş putea doar să mă ating de haina Lui, mă voi tămădui.”",
    "Şi îndată a secat izvorul sângelui ei. Şi a simţit în tot trupul ei că s-a tămăduit de boală.",
    "Isus a cunoscut îndată că o putere ieşise din El; şi, întorcându-Se spre mulţime, a zis: „Cine s-a atins de hainele Mele?”",
    "Ucenicii I-au zis: „Vezi că mulţimea Te îmbulzeşte şi mai zici: „Cine s-a atins de Mine?”",
    "El Se uita de jur împrejur să vadă pe cea care făcuse lucrul acesta.",
    "Femeia, înfricoşată şi tremurând, căci ştia ce se petrecuse în ea, a venit de s-a aruncat la picioarele Lui şi I-a spus tot adevărul.",
    "Dar Isus i-a zis: „Fiică, credinţa ta te-a mântuit; du-te în pace şi fii tămăduită de boala ta.”",
    "Pe când vorbea El încă, iată că vin nişte oameni de la fruntaşul sinagogii care-i spun: „Fiica ta a murit; pentru ce mai superi pe Învăţătorul?”",
    "Dar Isus, fără să ţină seamă de cuvintele acestea, a zis fruntaşului sinagogii: „Nu te teme, crede numai!”",
    "Şi n-a îngăduit nimănui să-L însoţească, afară de Petru, Iacov şi Ioan, fratele lui Iacov.",
    "Au ajuns la casa fruntaşului sinagogii. Acolo Isus a văzut o zarvă, şi pe unii care plângeau şi se tânguiau mult.",
    "A intrat înăuntru şi le-a zis: „Pentru ce faceţi atâta zarvă şi pentru ce plângeţi? Copila n-a murit, ci doarme.”",
    "Ei îşi băteau joc de El. Atunci, după ce i-a scos afară pe toţi, a luat cu El pe tatăl copilei, pe mama ei şi pe cei ce-L însoţiseră şi a intrat acolo unde zăcea copila.",
    "A apucat-o de mână şi i-a zis: „Talita, cumi”, care tălmăcit înseamnă: „Fetiţo, scoală-te îţi zic!”",
    "Îndată fetiţa s-a sculat şi a început să umble; căci era de doisprezece ani. Ei au rămas încremeniţi.",
    "Isus le-a poruncit cu tărie să nu ştie nimeni lucrul acesta; şi a zis să dea de mâncare fetiţei.",
  ],
  [
    "",
    "Isus a plecat de acolo şi S-a dus în patria Lui. Ucenicii Lui au mers după El.",
    "Când a venit ziua Sabatului, a început să înveţe pe norod în sinagogă. Mulţi, când Îl auzeau, se mirau şi ziceau: „De unde are El aceste lucruri? Ce fel de înţelepciune este aceasta care I-a fost dată? Şi cum se fac astfel de minuni prin mâinile Lui?",
    "Nu este Acesta tâmplarul, feciorul Mariei, fratele lui Iacov, al lui Iose, al lui Iuda şi al lui Simon? Şi nu sunt surorile Lui aici între noi?” Şi găseau o pricină de poticnire în El.",
    "Dar Isus le-a zis: „Un proroc nu este dispreţuit decât în patria Lui, între rudele Lui şi în casa Lui.”",
    "N-a putut să facă nicio minune acolo, ci doar Şi-a pus mâinile peste câţiva bolnavi şi i-a vindecat.",
    "Şi Se mira de necredinţa lor. Isus străbătea satele dimprejur şi învăţa pe norod.",
    "Atunci a chemat la Sine pe cei doisprezece şi a început să-i trimită doi câte doi, dându-le putere asupra duhurilor necurate.",
    "Le-a poruncit să nu ia nimic cu ei pe drum decât un toiag; să n-aibă nici pâine, nici traistă, nici bani de aramă la brâu;",
    "să se încalţe cu sandale şi să nu se îmbrace cu două haine.",
    "Apoi le-a zis: „În orice casă veţi intra să rămâneţi acolo până veţi pleca din locul acela.",
    "Şi, dacă în vreun loc nu vă vor primi şi nu vă vor asculta, să plecaţi de acolo şi să scuturaţi îndată praful de sub picioarele voastre, ca mărturie pentru ei. Adevărat vă spun că, în ziua judecăţii, va fi mai uşor pentru pământul Sodomei şi Gomorei decât pentru cetatea aceea.”",
    "Ucenicii au plecat şi au propovăduit pocăinţa.",
    "Scoteau mulţi draci şi ungeau cu untdelemn pe mulţi bolnavi şi-i vindecau.",
    "Împăratul Irod a auzit vorbindu-se despre Isus, al cărui Nume ajunsese vestit; şi a zis: „Ioan Botezătorul a înviat din morţi, şi de aceea lucrează aceste puteri prin El.”",
    "Alţii ziceau: „Este Ilie.” Iar alţii ziceau: „Este un proroc ca unul din proroci.”",
    "Dar Irod, când a auzit lucrul acesta, zicea: „Ioan acela, căruia i-am tăiat capul, a înviat din morţi.”",
    "Căci Irod însuşi trimisese să prindă pe Ioan şi-l legase în temniţă, din pricina Irodiadei, nevasta fratelui său Filip, pentru că o luase de nevastă.",
    "Şi Ioan zicea lui Irod: „Nu-ţi este îngăduit să ţii pe nevasta fratelui tău!”",
    "Irodiada avea necaz pe Ioan şi voia să-l omoare. Dar nu putea,",
    "căci Irod se temea de Ioan, fiindcă îl ştia om neprihănit şi sfânt; îl ocrotea şi, când îl auzea, de multe ori stătea în cumpănă, neştiind ce să facă; şi-l asculta cu plăcere.",
    "Totuşi a venit o zi cu bun prilej, când Irod îşi prăznuia ziua naşterii şi a dat un ospăţ boierilor săi, mai marilor oştii şi fruntaşilor Galileii.",
    "Fata Irodiadei a intrat la ospăţ, a jucat şi a plăcut lui Irod şi oaspeţilor lui. Împăratul a zis fetei: „Cere-mi orice vrei, şi-ţi voi da.”",
    "Apoi a adăugat cu jurământ: „Orice-mi vei cere, îţi voi da, fie şi jumătate din împărăţia mea.”",
    "Fata a ieşit afară şi a zis mamei sale: „Ce să cer?” Şi mama sa i-a răspuns: „Capul lui Ioan Botezătorul.”",
    "Ea s-a grăbit să vină îndată la împărat şi i-a făcut următoarea cerere: „Vreau să-mi dai îndată, într-o farfurie, capul lui Ioan Botezătorul.”",
    "Împăratul s-a întristat foarte mult; dar, din pricina jurămintelor sale şi din pricina oaspeţilor, n-a vrut să zică nu.",
    "A trimis îndată un ostaş de pază, cu porunca de a aduce capul lui Ioan Botezătorul. Ostaşul de pază s-a dus şi a tăiat capul lui Ioan în temniţă,",
    "l-a adus pe o farfurie, l-a dat fetei, şi fata l-a dat mamei sale.",
    "Ucenicii lui Ioan, când au auzit acest lucru, au venit de i-au ridicat trupul şi l-au pus într-un mormânt.",
    "Apostolii s-au adunat la Isus şi I-au spus tot ce făcuseră şi tot ce învăţaseră pe oameni.",
    "Isus le-a zis: „Veniţi singuri la o parte, într-un loc pustiu, şi odihniţi-vă puţin.” Căci erau mulţi care veneau şi se duceau, şi ei n-aveau vreme nici să mănânce.",
    "Au plecat, dar, cu corabia, ca să se ducă într-un loc pustiu, la o parte.",
    "Oamenii i-au văzut plecând şi i-au cunoscut; au alergat pe jos din toate cetăţile şi au venit înaintea lor în locul în care se duceau ei.",
    "Când a ieşit din corabie, Isus a văzut mult norod; şi I s-a făcut milă de ei, pentru că erau ca nişte oi care n-aveau păstor; şi a început să-i înveţe multe lucruri.",
    "Fiindcă ziua era pe sfârşite, ucenicii s-au apropiat de El şi I-au zis: „Locul acesta este pustiu, şi ziua este pe sfârşite.",
    "Dă-le drumul să se ducă în cătunele şi satele dimprejur ca să-şi cumpere pâine, fiindcă n-au ce mânca.”",
    "„Daţi-le voi să mănânce”, le-a răspuns Isus. Dar ei I-au zis: „Oare să ne ducem să cumpărăm pâini de două sute de lei şi să le dăm să mănânce?”",
    "Şi El i-a întrebat: „Câte pâini aveţi? Duceţi-vă de vedeţi.” S-au dus de au văzut câte pâini au şi au răspuns: „Cinci şi doi peşti.”",
    "Atunci le-a poruncit să-i aşeze pe toţi, cete-cete, pe iarba verde.",
    "Şi au şezut jos în cete de câte o sută şi de câte cincizeci.",
    "El a luat cele cinci pâini şi cei doi peşti. Şi-a ridicat ochii spre cer şi a rostit binecuvântarea. Apoi a frânt pâinile şi le-a dat ucenicilor, ca ei să le împartă norodului. Asemenea şi cei doi peşti i-a împărţit la toţi.",
    "Au mâncat toţi şi s-au săturat;",
    "şi au ridicat douăsprezece coşuri pline cu firimituri de pâine şi cu ce mai rămăsese din peşti.",
    "Cei ce mâncaseră pâinile erau cinci mii de bărbaţi.",
    "Îndată, Isus a silit pe ucenicii Săi să intre în corabie şi să treacă înaintea Lui de cealaltă parte, spre Betsaida. În timpul acesta, El avea să dea drumul norodului.",
    "După ce Şi-a luat rămas bun de la norod, S-a dus pe munte ca să Se roage.",
    "Când s-a înserat, corabia era în mijlocul mării, iar Isus era singur pe ţărm.",
    "A văzut pe ucenici că se necăjesc cu vâslirea, căci vântul le era împotrivă. Şi, într-a patra strajă din noapte, a mers la ei, umblând pe mare, şi voia să treacă pe lângă ei.",
    "Când L-au văzut ei umblând pe mare, li s-a părut că este o nălucă, şi au ţipat;",
    "pentru că toţi L-au văzut şi s-au înspăimântat. Isus a vorbit îndată cu ei şi le-a zis: „Îndrăzniţi, Eu sunt, nu vă temeţi!”",
    "Apoi S-a suit la ei în corabie, şi a stat vântul. Ei au rămas uimiţi şi înmărmuriţi,",
    "căci nu înţeleseseră minunea cu pâinile, fiindcă le era inima împietrită.",
    "După ce au trecut marea, au venit în ţinutul Ghenezaretului şi au tras la mal.",
    "Când au ieşit din corabie, oamenii au cunoscut îndată pe Isus,",
    "au alergat prin toate împrejurimile şi au început să aducă pe bolnavi în paturi, pretutindeni pe unde se auzea că era El.",
    "Oriunde intra El, în sate, în cetăţi sau în cătune, puneau pe bolnavi pe pieţe şi-L rugau să le dea voie doar să se atingă de poalele hainei Lui. Şi toţi câţi se atingeau de El erau tămăduiţi.",
  ],
  [
    "",
    "Fariseii şi câţiva cărturari, veniţi din Ierusalim, s-au adunat la Isus.",
    "Ei au văzut pe unii din ucenicii Lui prânzind cu mâinile necurate, adică nespălate. –",
    "Fariseii însă şi toţi iudeii nu mănâncă fără să-şi spele cu mare băgare de seamă mâinile, după datina bătrânilor.",
    "Şi când se întorc din piaţă, nu mănâncă decât după ce s-au scăldat. Sunt multe alte obiceiuri pe care au apucat ei să le ţină, precum: spălarea paharelor, a ulcioarelor, a căldărilor şi a paturilor. –",
    "Şi fariseii şi cărturarii L-au întrebat: „Pentru ce nu se ţin ucenicii Tăi de datina bătrânilor, ci prânzesc cu mâinile nespălate?”",
    "Isus le-a răspuns: „Făţarnicilor, bine a prorocit Isaia despre voi, după cum este scris: „Norodul acesta Mă cinsteşte cu buzele, dar inima lui este departe de Mine.",
    "Degeaba Mă cinstesc ei, dând învăţături care nu sunt decât nişte porunci omeneşti.”",
    "Voi lăsaţi porunca lui Dumnezeu şi ţineţi datina aşezată de oameni, precum: spălarea ulcioarelor şi a paharelor, şi faceţi multe alte lucruri de acestea.”",
    "El le-a mai zis: „Aţi desfiinţat frumos porunca lui Dumnezeu, ca să ţineţi datina voastră.",
    "Căci Moise a zis: „Să cinsteşti pe tatăl tău şi pe mama ta”; şi: „Cine va grăi de rău pe tatăl său sau pe mama sa să fie pedepsit cu moartea.”",
    "Voi, dimpotrivă, ziceţi: „Dacă un om va spune tatălui său sau mamei sale: „Ori cu ce te-aş putea ajuta este „Corban”, adică dat lui Dumnezeu, face bine”;",
    "şi nu-l mai lăsaţi să facă nimic pentru tatăl sau pentru mama sa.",
    "Şi aşa, aţi desfiinţat Cuvântul lui Dumnezeu, prin datina voastră. Şi faceţi multe alte lucruri de felul acesta!”",
    "În urmă, a chemat din nou noroadele la Sine şi le-a zis: „Ascultaţi-Mă toţi şi înţelegeţi.",
    "Afară din om nu este nimic care, intrând în el, să-l poată spurca; dar ce iese din om aceea-l spurcă.",
    "Dacă are cineva urechi de auzit, să audă.”",
    "După ce a intrat în casă, pe când era departe de norod, ucenicii Lui L-au întrebat despre pilda aceasta.",
    "El le-a zis: „Şi voi sunteţi aşa de nepricepuţi? Nu înţelegeţi că nimic din ce intră în om de afară nu-l poate spurca?",
    "Fiindcă nu intră în inima lui, ci în pântece, şi apoi este dat afară în hazna.” A zis astfel, făcând toate bucatele curate.",
    "El le-a mai zis: „Ce iese din om aceea spurcă pe om.",
    "Căci dinăuntru, din inima oamenilor, ies gândurile rele, preacurviile, curviile, uciderile,",
    "furtişagurile, lăcomiile, vicleşugurile, înşelăciunile, faptele de ruşine, ochiul rău, hula, trufia, nebunia.",
    "Toate aceste lucruri rele ies dinăuntru şi spurcă pe om.”",
    "Isus a plecat de acolo şi S-a dus în ţinutul Tirului şi al Sidonului. A intrat într-o casă, dorind să nu ştie nimeni că este acolo; dar n-a putut să rămână ascuns.",
    "Căci îndată, o femeie, a cărei fetiţă era stăpânită de un duh necurat, a auzit vorbindu-se despre El şi a venit de s-a aruncat la picioarele Lui.",
    "Femeia aceasta era o grecoaică, de obârşie siro-feniciană. Ea Îl ruga să scoată pe dracul din fiica ei.",
    "Isus i-a zis: „Lasă să se sature mai întâi copiii; căci nu este bine să iei pâinea copiilor şi s-o arunci la căţei.”",
    "„Da, Doamne”, I-a răspuns ea, „dar şi căţeii de sub masă mănâncă din firimiturile copiilor.”",
    "Atunci Isus i-a zis: „Pentru vorba aceasta, du-te; a ieşit dracul din fiica ta.”",
    "Şi când a intrat femeia în casa ei, a găsit pe copilă culcată în pat; şi ieşise dracul din ea.",
    "Isus a părăsit ţinutul Tirului şi a venit iarăşi prin Sidon la Marea Galileii, trecând prin ţinutul Decapole.",
    "I-au adus un surd care vorbea cu anevoie şi L-au rugat să-Şi pună mâinile peste el.",
    "El l-a luat la o parte din norod, i-a pus degetele în urechi şi i-a atins limba cu scuipatul Lui.",
    "Apoi, Şi-a ridicat ochii spre cer, a suspinat şi a zis: „Efata”, adică: „Deschide-te!”",
    "Îndată i s-au deschis urechile, i s-a dezlegat limba şi a vorbit foarte desluşit.",
    "Isus le-a poruncit să nu spună nimănui; dar cu cât le poruncea mai mult, cu atât Îl vesteau mai mult.",
    "Ei erau uimiţi peste măsură de mult şi ziceau: „Toate le face de minune; chiar şi pe surzi îi face să audă, şi pe muţi să vorbească.”",
  ],
  [
    "",
    "În zilele acelea, fiindcă se strânsese din nou mult norod şi n-avea ce mânca, Isus a chemat pe ucenicii Săi şi le-a zis:",
    "„Mi-e milă de norodul acesta; căci iată că de trei zile stau lângă Mine şi n-au ce mânca.",
    "Dacă le voi da drumul acasă flămânzi, au să leşine de foame pe drum, fiindcă unii din ei au venit de departe.”",
    "Ucenicii I-au răspuns: „Cum ar putea cineva să sature cu pâine pe oamenii aceştia, aici într-un loc pustiu?”",
    "„Câte pâini aveţi?”, i-a întrebat Isus. „Şapte”, I-au răspuns ei.",
    "Atunci a poruncit norodului să şadă pe pământ; a luat cele şapte pâini; şi, după ce a mulţumit lui Dumnezeu, le-a frânt şi le-a dat ucenicilor Săi ca să le împartă; şi ei le-au împărţit norodului.",
    "Mai aveau şi câţiva peştişori: şi Isus, după ce i-a binecuvântat, a poruncit să-i împartă şi pe aceia.",
    "Au mâncat şi s-au săturat; şi au ridicat şapte coşniţe pline cu rămăşiţele de firimituri.",
    "Erau aproape patru mii de inşi. În urmă, Isus le-a dat drumul.",
    "Isus a intrat îndată în corabie cu ucenicii Săi şi a venit în părţile Dalmanutei.",
    "Fariseii au venit deodată şi au început o ceartă de vorbe cu Isus; şi, ca să-L pună la încercare, I-au cerut un semn din cer.",
    "Isus a suspinat adânc în duhul Său şi a zis: „Pentru ce cere neamul acesta un semn? Adevărat vă spun că neamului acestuia nu i se va da deloc un semn.”",
    "Apoi i-a lăsat şi a intrat iarăşi în corabie, ca să treacă de cealaltă parte.",
    "Ucenicii uitaseră să ia pâini; cu ei în corabie n-aveau decât o pâine.",
    "Isus le dădea în grijă şi le zicea: „Luaţi seama, să vă păziţi bine de aluatul fariseilor şi de aluatul lui Irod!”",
    "Ucenicii se gândeau şi ziceau între ei: „Fiindcă n-avem pâini.”",
    "Isus a înţeles lucrul acesta şi le-a zis: „Pentru ce vă gândiţi că n-aveţi pâini? Tot nu pricepeţi şi tot nu înţelegeţi? Aveţi inima împietrită?",
    "Aveţi ochi, şi nu vedeţi? Aveţi urechi, şi nu auziţi? Şi nu vă aduceţi aminte deloc?",
    "Când am frânt cele cinci pâini la cei cinci mii de bărbaţi, câte coşuri pline cu firimituri aţi ridicat?” „Douăsprezece”, I-au răspuns ei.",
    "„Şi, când am frânt cele şapte pâini la cei patru mii de bărbaţi, câte coşniţe pline cu firimituri aţi ridicat?” „Şapte”, I-au răspuns ei.",
    "Şi El le-a zis: „Tot nu înţelegeţi?”",
    "Au venit la Betsaida; au adus la Isus un orb şi L-au rugat să Se atingă de el.",
    "Isus a luat pe orb de mână şi l-a scos afară din sat; apoi i-a pus scuipat pe ochi, Şi-a pus mâinile peste el şi l-a întrebat: „Vezi ceva?”",
    "El s-a uitat şi a zis: „Văd nişte oameni umblând, dar mi se par ca nişte copaci.”",
    "Isus i-a pus din nou mâinile pe ochi; i-a spus să se uite ţintă; şi, când s-a uitat, a fost tămăduit şi a văzut toate lucrurile desluşit.",
    "Atunci Isus l-a trimis acasă şi i-a zis: „Să nu intri în sat şi nici să nu spui cuiva în sat.”",
    "Isus a plecat cu ucenicii Săi în satele Cezareii lui Filip. Pe drum le-a pus următoarea întrebare: „Cine zic oamenii că sunt Eu?”",
    "Ei I-au răspuns: „Ioan Botezătorul; alţii: Ilie; alţii: unul din proroci.”",
    "„Dar voi”, i-a întrebat El, „cine ziceţi că sunt Eu?” „Tu eşti Hristosul!”, I-a răspuns Petru.",
    "Isus le-a poruncit cu tărie să nu spună nimănui lucrul acesta despre El.",
    "Atunci a început să-i înveţe că Fiul omului trebuie să pătimească mult, să fie tăgăduit de bătrâni, de preoţii cei mai de seamă şi de cărturari, să fie omorât, şi după trei zile să învie.",
    "Le spunea lucrurile acestea pe faţă. Petru însă L-a luat deoparte şi a început să-L mustre.",
    "Dar Isus S-a întors şi S-a uitat la ucenicii Săi, a mustrat pe Petru şi i-a zis: „Înapoia Mea, Satano! Fiindcă tu nu te gândeşti la lucrurile lui Dumnezeu, ci la lucrurile oamenilor.”",
    "Apoi a chemat la El norodul împreună cu ucenicii Săi şi le-a zis: „Dacă voieşte cineva să vină după Mine, să se lepede de sine însuşi, să-şi ia crucea şi să Mă urmeze.",
    "Căci oricine va vrea să-şi scape viaţa, o va pierde; dar oricine îşi va pierde viaţa din pricina Mea şi din pricina Evangheliei, o va mântui.",
    "Şi ce foloseşte unui om să câştige toată lumea, dacă îşi pierde sufletul?",
    "Sau ce va da un om în schimb pentru sufletul său?",
    "Pentru că de oricine se va ruşina de Mine şi de cuvintele Mele, în acest neam preacurvar şi păcătos, Se va ruşina şi Fiul omului, când va veni în slava Tatălui Său împreună cu sfinţii îngeri.”",
  ],
  [
    "",
    "El le-a mai zis: „Adevărat vă spun că sunt unii din cei ce stau aici care nu vor muri până nu vor vedea Împărăţia lui Dumnezeu venind cu putere.”",
    "După şase zile, Isus a luat cu El pe Petru, pe Iacov şi pe Ioan şi i-a dus singuri deoparte pe un munte înalt. Acolo S-a schimbat la faţă înaintea lor.",
    "Hainele Lui s-au făcut strălucitoare şi foarte albe, de o albeaţă pe care niciun înălbitor de pe pământ n-o poate da.",
    "Ilie li s-a arătat împreună cu Moise şi stătea de vorbă cu Isus.",
    "Petru a luat cuvântul şi a zis lui Isus: „Învăţătorule, este bine să stăm aici; să facem trei colibe: una pentru Tine, una pentru Moise, şi una pentru Ilie.”",
    "Căci nu ştia ce să zică, atât de mare spaimă îi apucase.",
    "A venit un nor şi i-a acoperit cu umbra lui; şi din nor s-a auzit un glas care zicea: „Acesta este Fiul Meu preaiubit: de El să ascultaţi!”",
    "Îndată ucenicii s-au uitat împrejur, şi n-au mai văzut pe nimeni decât pe Isus singur cu ei.",
    "Pe când se coborau de pe munte, Isus le-a poruncit să nu spună nimănui ce au văzut, până va învia Fiul omului dintre cei morţi.",
    "Ei au păstrat în ei lucrul acesta şi se întrebau între ei ce să însemne învierea aceea dintre cei morţi.",
    "Ucenicii I-au pus următoarea întrebare: „Pentru ce zic cărturarii că trebuie să vină întâi Ilie?”",
    "El le-a răspuns: „Ilie va veni întâi; şi va aşeza din nou toate lucrurile; tot aşa după cum este scris despre Fiul omului că trebuie să pătimească mult şi să fie defăimat.",
    "Dar Eu vă spun că Ilie a şi venit, şi ei i-au făcut ce au vrut, după cum este scris despre el.”",
    "Când au ajuns la ucenici, au văzut mult norod împrejurul lor, şi pe cărturari întrebându-se cu ei.",
    "De îndată ce a văzut norodul pe Isus, s-a mirat şi a alergat la El să I se închine.",
    "El i-a întrebat: „Despre ce vă întrebaţi cu ei?”",
    "Şi un om din norod I-a răspuns: „Învăţătorule, am adus la Tine pe fiul meu care este stăpânit de un duh mut.",
    "Oriunde îl apucă, îl trânteşte la pământ. Copilul face spumă la gură, scrâşneşte din dinţi şi rămâne ţeapăn. M-am rugat de ucenicii Tăi să scoată duhul, şi n-au putut.”",
    "„O, neam necredincios!”, le-a zis Isus. „Până când voi fi cu voi? Până când vă voi suferi? Aduceţi-l la Mine.”",
    "L-au adus la El. Şi, cum a văzut copilul pe Isus, duhul l-a scuturat cu putere; copilul a căzut la pământ şi se zvârcolea făcând spumă la gură.",
    "Isus a întrebat pe tatăl lui: „Câtă vreme este de când îi vine aşa?” „Din copilărie”, a răspuns el.",
    "„Şi de multe ori duhul l-a aruncat când în foc, când în apă, ca să-l omoare. Dar dacă poţi face ceva, fie-Ţi milă de noi şi ajută-ne.”",
    "Isus a răspuns: „Tu zici: „Dacă poţi!”… Toate lucrurile sunt cu putinţă celui ce crede!”",
    "Îndată tatăl copilului a strigat cu lacrimi: „Cred, Doamne! Ajută necredinţei mele!”",
    "Când a văzut Isus că norodul vine în fuga mare spre El, a mustrat duhul necurat şi i-a zis: „Duh mut şi surd, îţi poruncesc să ieşi afară din copilul acesta şi să nu mai intri în el.”",
    "Şi duhul a ieşit, ţipând şi scuturându-l cu mare putere. Copilul a rămas ca mort, aşa că mulţi ziceau: „A murit!”",
    "Dar Isus l-a apucat de mână şi l-a ridicat. Şi el s-a sculat în picioare.",
    "Când a intrat Isus în casă, ucenicii Lui L-au întrebat deoparte: „Noi de ce n-am putut să scoatem duhul acesta?”",
    "„Acest soi de draci”, le-a zis El, „nu poate ieşi decât prin rugăciune şi post.”",
    "Au plecat de acolo şi au trecut prin Galileea. Isus nu voia să ştie nimeni că trece.",
    "Căci învăţa pe ucenicii Săi şi zicea: „Fiul omului va fi dat în mâinile oamenilor; ei Îl vor omorî, şi a treia zi după ce-L vor omorî, va învia.”",
    "Dar ucenicii nu înţelegeau cuvintele acestea şi se temeau să-L întrebe.",
    "Apoi au venit la Capernaum. Când era în casă, Isus i-a întrebat: „Despre ce vorbeaţi unul cu altul pe drum?”",
    "Dar ei tăceau, pentru că pe drum se certaseră între ei, ca să ştie cine este cel mai mare.",
    "Atunci Isus a şezut jos, a chemat pe cei doisprezece şi le-a zis: „Dacă vrea cineva să fie cel dintâi, trebuie să fie cel mai de pe urmă din toţi şi slujitorul tuturor!”",
    "Şi a luat un copilaş şi l-a aşezat în mijlocul lor; apoi l-a luat în braţe şi le-a zis:",
    "„Oricine primeşte pe unul din aceşti copilaşi, în Numele Meu, Mă primeşte pe Mine; şi oricine Mă primeşte pe Mine, nu Mă primeşte pe Mine, ci pe Cel ce M-a trimis pe Mine.”",
    "Ioan I-a zis: „Învăţătorule, noi am văzut pe un om scoţând draci în Numele Tău; şi l-am oprit, pentru că nu venea după noi.”",
    "„Nu-l opriţi”, a răspuns Isus, „căci nu este nimeni care să facă minuni în Numele Meu, şi să Mă poată grăi de rău îndată după aceea.",
    "Cine nu este împotriva noastră este pentru noi.",
    "Şi oricine vă va da de băut un pahar cu apă, în Numele Meu, pentru că sunteţi ucenici ai lui Hristos, adevărat vă spun că nu-şi va pierde răsplata.",
    "Dar, dacă va face cineva să păcătuiască pe unul din aceşti micuţi care cred în Mine, ar fi mai bine pentru el să i se lege de gât o piatră mare de moară şi să fie aruncat în mare.",
    "Dacă mâna ta te face să cazi în păcat, taie-o; este mai bine pentru tine să intri ciung în viaţă, decât să ai două mâini, şi să mergi în gheenă, în focul care nu se stinge,",
    "unde viermele lor nu moare, şi focul nu se stinge.",
    "Dacă piciorul tău te face să cazi în păcat, taie-l; este mai bine pentru tine să intri în viaţă şchiop, decât să ai două picioare, şi să fii aruncat în gheenă, în focul care nu se stinge,",
    "unde viermele lor nu moare, şi focul nu se stinge.",
    "Şi dacă ochiul tău te face să cazi în păcat, scoate-l; este mai bine pentru tine să intri în Împărăţia lui Dumnezeu numai cu un ochi, decât să ai doi ochi, şi să fii aruncat în focul gheenei,",
    "unde viermele lor nu moare, şi focul nu se stinge.",
    "Pentru că fiecare om va fi sărat cu foc, şi orice jertfă va fi sărată cu sare.",
    "Sarea este bună; dar dacă sarea îşi pierde puterea de a săra, cu ce îi veţi da înapoi puterea aceasta? Să aveţi sare în voi înşivă şi să trăiţi în pace unii cu alţii.”",
  ],
  [
    "",
    "Isus a plecat de acolo şi a venit în ţinutul Iudeii, dincolo de Iordan. Gloatele s-au adunat din nou la El; şi, după obiceiul Său, a început iarăşi să-i înveţe.",
    "Au venit la El fariseii; şi, ca să-L ispitească, L-au întrebat dacă este îngăduit unui bărbat să-şi lase nevasta.",
    "Drept răspuns, El le-a zis: „Ce v-a poruncit Moise?”",
    "„Moise”, au zis ei, „a dat voie ca bărbatul să scrie o carte de despărţire şi s-o lase.”",
    "Isus le-a zis: „Din pricina împietririi inimii voastre v-a scris Moise porunca aceasta.",
    "Dar de la începutul lumii „Dumnezeu i-a făcut parte bărbătească şi parte femeiască.",
    "De aceea va lăsa omul pe tatăl său şi pe mama sa şi se va lipi de nevasta sa.",
    "Şi cei doi vor fi un singur trup.” Aşa că nu mai sunt doi, ci sunt un singur trup.",
    "Deci, ce a împreunat Dumnezeu, omul să nu despartă.”",
    "În casă, ucenicii L-au întrebat iarăşi asupra celor de mai sus.",
    "El le-a zis: „Oricine îşi lasă nevasta şi ia pe alta de nevastă preacurveşte faţă de ea;",
    "şi dacă o nevastă îşi lasă bărbatul şi ia pe altul de bărbat preacurveşte.”",
    "I-au adus nişte copilaşi ca să Se atingă de ei. Dar ucenicii au certat pe cei ce îi aduceau.",
    "Când a văzut Isus acest lucru, S-a mâniat şi le-a zis: „Lăsaţi copilaşii să vină la Mine şi nu-i opriţi; căci Împărăţia lui Dumnezeu este a celor ca ei.",
    "Adevărat vă spun că oricine nu va primi Împărăţia lui Dumnezeu ca un copilaş, cu niciun chip nu va intra în ea!”",
    "Apoi i-a luat în braţe şi i-a binecuvântat, punându-Şi mâinile peste ei.",
    "Tocmai când era gata să pornească la drum, a alergat la El un om, care a îngenuncheat înaintea Lui şi L-a întrebat: „Bunule Învăţător, ce să fac ca să moştenesc viaţa veşnică?”",
    "„Pentru ce Mă numeşti bun?”, i-a zis Isus. „Nimeni nu este bun decât Unul singur: Dumnezeu.",
    "Cunoşti poruncile: „Să nu preacurveşti; să nu ucizi; să nu furi; să nu faci o mărturisire mincinoasă; să nu înşeli; să cinsteşti pe tatăl tău şi pe mama ta.”",
    "El I-a răspuns: „Învăţătorule, toate aceste lucruri le-am păzit cu grijă din tinereţea mea.”",
    "Isus S-a uitat ţintă la el, l-a iubit şi i-a zis: „Îţi lipseşte un lucru; du-te de vinde tot ce ai, dă la săraci, şi vei avea o comoară în cer. Apoi vino, ia-ţi crucea şi urmează-Mă.”",
    "Mâhnit de aceste cuvinte, omul acesta a plecat întristat de tot; căci avea multe avuţii.",
    "Isus S-a uitat împrejurul Lui şi a zis ucenicilor Săi: „Cât de anevoie vor intra în Împărăţia lui Dumnezeu cei ce au avuţii!”",
    "Ucenicii au rămas uimiţi de cuvintele Lui. Isus a luat din nou cuvântul şi le-a zis: „Fiilor, cât de anevoie este pentru cei ce se încred în bogăţii să intre în Împărăţia lui Dumnezeu!",
    "Mai lesne este să treacă o cămilă prin urechea unui ac, decât să intre un om bogat în Împărăţia lui Dumnezeu!”",
    "Ucenicii au rămas şi mai uimiţi şi au zis unii către alţii: „Cine poate atunci să fie mântuit?”",
    "Isus S-a uitat ţintă la ei şi le-a zis: „Lucrul acesta este cu neputinţă la oameni, dar nu la Dumnezeu; pentru că toate lucrurile sunt cu putinţă la Dumnezeu.”",
    "Petru a început să-I zică: „Iată că noi am lăsat totul şi Te-am urmat.”",
    "Isus a răspuns: „Adevărat vă spun că nu este nimeni care să fi lăsat casă, sau fraţi, sau surori, sau tată, sau mamă, sau nevastă, sau copii, sau holde pentru Mine şi pentru Evanghelie",
    "şi să nu primească acum, în veacul acesta, de o sută de ori mai mult: case, fraţi, surori, mame, copii şi holde, împreună cu prigoniri; iar în veacul viitor, viaţa veşnică.",
    "Mulţi din cei dintâi vor fi cei de pe urmă, şi mulţi din cei de pe urmă vor fi cei dintâi.”",
    "Ei erau pe drum şi se suiau la Ierusalim; şi Isus mergea înaintea lor. Ucenicii erau tulburaţi şi mergeau îngroziţi după El. Isus a luat iarăşi la El pe cei doisprezece şi a început să le vorbească despre lucrurile care aveau să I se întâmple.",
    "„Iată”, a zis El, „ne suim la Ierusalim şi Fiul omului va fi dat în mâinile preoţilor celor mai de seamă şi cărturarilor. Ei Îl vor osândi la moarte şi-L vor da în mâinile Neamurilor,",
    "care îşi vor bate joc de El, Îl vor bate cu nuiele, Îl vor scuipa şi-L vor omorî; dar, după trei zile, va învia.”",
    "Fiii lui Zebedei, Iacov şi Ioan, au venit la Isus şi I-au zis: „Învăţătorule, am vrea să ne faci ce-Ţi vom cere.”",
    "El le-a zis: „Ce voiţi să vă fac?”",
    "„Dă-ne”, I-au zis ei, „să şedem unul la dreapta Ta, şi altul la stânga Ta, când vei fi îmbrăcat în slava Ta.”",
    "Isus le-a răspuns: „Nu ştiţi ce cereţi. Puteţi voi să beţi paharul pe care am să-l beau Eu sau să fiţi botezaţi cu botezul cu care am să fiu botezat Eu?”",
    "„Putem”, au zis ei. Şi Isus le-a răspuns: „Este adevărat că paharul pe care-l voi bea Eu îl veţi bea, şi cu botezul cu care voi fi botezat Eu veţi fi botezaţi;",
    "dar cinstea de a şedea la dreapta sau la stânga Mea nu atârnă de Mine s-o dau, ci ea este numai pentru aceia pentru care a fost pregătită.”",
    "Cei zece, când au auzit lucrul acesta, au început să se mânie pe Iacov şi pe Ioan.",
    "Isus i-a chemat la El şi le-a zis: „Ştiţi că cei priviţi drept cârmuitori ai Neamurilor, domnesc peste ele, şi mai marii lor le poruncesc cu stăpânire.",
    "Dar între voi să nu fie aşa. Ci oricare va vrea să fie mare între voi să fie slujitorul vostru;",
    "şi oricare va vrea să fie cel dintâi între voi să fie robul tuturor.",
    "Căci Fiul omului n-a venit să I se slujească, ci El să slujească şi să-Şi dea viaţa răscumpărare pentru mulţi!”",
    "Au ajuns la Ierihon. Şi pe când ieşea Isus din Ierihon cu ucenicii Săi şi cu o mare mulţime de oameni, fiul lui Timeu, Bartimeu, un cerşetor orb, şedea jos lângă drum şi cerea de milă.",
    "El a auzit că trece Isus din Nazaret şi a început să strige: „Isuse, Fiul lui David, ai milă de mine!”",
    "Mulţi îl certau să tacă; dar el şi mai tare striga: „Fiul lui David, ai milă de mine!”",
    "Isus S-a oprit şi a zis: „Chemaţi-l!” Au chemat pe orb şi i-au zis: „Îndrăzneşte, scoală-te, căci te cheamă.”",
    "Orbul şi-a aruncat haina; a sărit şi a venit la Isus.",
    "Isus a luat cuvântul şi i-a zis: „Ce vrei să-ţi fac?” „Rabuni”, I-a răspuns orbul, „să capăt vederea.”",
    "Şi Isus i-a zis: „Du-te, credinţa ta te-a mântuit.” Îndată orbul şi-a căpătat vederea şi a mers pe drum după Isus.",
  ],
  [
    "",
    "Când s-au apropiat de Ierusalim şi au fost lângă Betfaghe şi Betania, înspre Muntele Măslinilor, Isus a trimis pe doi din ucenicii Săi",
    "şi le-a zis: „Duceţi-vă în satul dinaintea voastră: îndată ce veţi intra în el, veţi găsi un măgăruş legat, pe care n-a încălecat încă niciun om; dezlegaţi-l şi aduceţi-Mi-l.",
    "Dacă vă va întreba cineva: „Pentru ce faceţi lucrul acesta?”, să răspundeţi: „Domnul are trebuinţă de el.” Şi îndată îl va trimite înapoi aici.”",
    "Ucenicii s-au dus, au găsit măgăruşul legat afară lângă o uşă, la cotitura drumului, şi l-au dezlegat.",
    "Unii din cei ce stăteau acolo le-au zis: „Ce faceţi? De ce dezlegaţi măgăruşul acesta?”",
    "Ei au răspuns cum le poruncise Isus. Şi i-au lăsat să plece.",
    "Au adus măgăruşul la Isus, şi-au aruncat hainele pe el, şi Isus a încălecat pe el.",
    "Mulţi oameni îşi aşterneau hainele pe drum, iar alţii presărau ramuri pe care le tăiaseră de pe câmp.",
    "Cei ce mergeau înainte şi cei ce veneau după Isus strigau: „Osana! Binecuvântat este Cel ce vine în Numele Domnului!",
    "Binecuvântată este Împărăţia care vine, Împărăţia părintelui nostru David! Osana în cerurile preaînalte!”",
    "Isus a intrat în Ierusalim şi S-a dus în Templu. După ce S-a uitat la toate lucrurile de jur împrejur, fiindcă era pe înserate, a plecat la Betania cu cei doisprezece.",
    "A doua zi, după ce au ieşit din Betania, Isus a flămânzit.",
    "A zărit de departe un smochin care avea frunze şi a venit să vadă poate va găsi ceva în el. S-a apropiat de smochin, dar n-a găsit decât frunze, căci nu era încă vremea smochinelor.",
    "Atunci a luat cuvântul şi a zis smochinului: „În veac să nu mai mănânce nimeni rod din tine!” Şi ucenicii au auzit aceste vorbe.",
    "Au ajuns în Ierusalim; şi Isus a intrat în Templu. A început să scoată afară pe cei ce vindeau şi cumpărau în Templu; a răsturnat mesele schimbătorilor de bani şi scaunele celor ce vindeau porumbei.",
    "Şi nu lăsa pe nimeni să poarte vreun vas prin Templu.",
    "Şi-i învăţa şi zicea: „Oare nu este scris: „Casa Mea se va chema o casă de rugăciune pentru toate neamurile”? Dar voi aţi făcut din ea o peşteră de tâlhari.”",
    "Preoţii cei mai de seamă şi cărturarii, când au auzit cuvintele acestea, căutau cum să-L omoare; căci se temeau de El, pentru că tot norodul era uimit de învăţătura Lui.",
    "Ori de câte ori se însera, Isus ieşea afară din cetate.",
    "Dimineaţa, când treceau pe lângă smochin, ucenicii l-au văzut uscat din rădăcini.",
    "Petru şi-a adus aminte de cele petrecute şi a zis lui Isus: „Învăţătorule, uite că smochinul pe care l-ai blestemat s-a uscat.”",
    "Isus a luat cuvântul şi le-a zis: „Aveţi credinţă în Dumnezeu!",
    "Adevărat vă spun că, dacă va zice cineva muntelui acestuia: „Ridică-te şi aruncă-te în mare”, şi dacă nu se va îndoi în inima lui, ci va crede că ce zice se va face, va avea lucrul cerut.",
    "De aceea vă spun că orice lucru veţi cere, când vă rugaţi, să credeţi că l-aţi şi primit, şi-l veţi avea.",
    "Şi, când staţi în picioare de vă rugaţi, să iertaţi orice aveţi împotriva cuiva, pentru ca şi Tatăl vostru care este în ceruri să vă ierte greşelile voastre.",
    "Dar, dacă nu iertaţi, nici Tatăl vostru care este în ceruri nu vă va ierta greşelile voastre.”",
    "S-au dus din nou în Ierusalim. Şi, pe când Se plimba Isus prin Templu, au venit la El preoţii cei mai de seamă, cărturarii şi bătrânii",
    "şi I-au zis: „Cu ce putere faci Tu aceste lucruri? Şi cine Ţi-a dat puterea aceasta ca să le faci?”",
    "Isus le-a răspuns: „Am să vă pun şi Eu o întrebare; răspundeţi-Mi la ea, şi apoi vă voi spune şi Eu cu ce putere fac aceste lucruri.",
    "Botezul lui Ioan venea din cer ori de la oameni? Răspundeţi-Mi!”",
    "Ei însă vorbeau astfel între ei: „Dacă răspundem: „Din cer”, va zice: „Dar de ce nu l-aţi crezut?”",
    "Şi dacă vom răspunde: „De la oameni…” se temeau de norod, căci toţi socoteau că Ioan a fost în adevăr un proroc.",
    "Atunci au răspuns lui Isus: „Nu ştim.” Şi Isus le-a zis: „Nici Eu n-am să vă spun cu ce putere fac aceste lucruri.”",
  ],
  [
    "",
    "Isus a început pe urmă să le vorbească în pilde. „Un om a sădit o vie. A împrejmuit-o cu un gard, a săpat un teasc în ea şi a zidit un turn; apoi a arendat-o unor vieri şi a plecat din ţară.",
    "La vremea roadelor, a trimis la vieri un rob, ca să ia de la ei din roadele viei.",
    "Vierii au pus mâna pe el, l-au bătut şi l-au trimis înapoi cu mâinile goale.",
    "A trimis iarăşi la ei un alt rob; ei l-au rănit la cap şi l-au batjocorit.",
    "A mai trimis un altul pe care l-au omorât; apoi a trimis mulţi alţii, dintre care, pe unii i-au bătut, iar pe alţii i-au omorât.",
    "Mai avea un singur fiu preaiubit; la urmă, l-a trimis şi pe el la ei. „Vor primi cu cinste pe fiul meu!”, zicea el.",
    "Dar vierii aceia au zis între ei: „Iată moştenitorul; veniţi să-l omorâm, şi moştenirea va fi a noastră.”",
    "Şi au pus mâna pe el, l-au omorât şi i-au aruncat trupul afară din vie.",
    "Acum, ce va face stăpânul viei? Va veni, va nimici pe vierii aceia, şi via o va da altora.",
    "Oare n-aţi citit locul acesta din Scriptură: „Piatra pe care au lepădat-o zidarii a ajuns să fie pusă în capul unghiului;",
    "Domnul a făcut acest lucru şi este minunat în ochii noştri”?”",
    "Ei căutau să-L prindă, dar se temeau de norod. Pricepuseră că împotriva lor spusese Isus pilda aceasta. Şi L-au lăsat şi au plecat.",
    "Apoi au trimis la Isus pe unii din farisei şi din irodieni, ca să-L prindă cu vorba.",
    "Aceştia au venit şi I-au zis: „Învăţătorule, ştim că spui adevărul şi nu-Ţi pasă de nimeni; căci nu cauţi la faţa oamenilor şi înveţi pe oameni calea lui Dumnezeu în adevăr. Se cade să plătim bir cezarului sau nu?",
    "Să plătim sau să nu plătim?” Isus le-a cunoscut făţărnicia şi le-a răspuns: „Pentru ce Mă ispitiţi? Aduceţi-Mi un ban ca să-l văd.”",
    "I-au adus un ban; şi Isus i-a întrebat: „Chipul acesta şi slovele scrise pe el, ale cui sunt?” „Ale cezarului”, I-au răspuns ei.",
    "Atunci Isus le-a zis: „Daţi, dar, cezarului ce este al cezarului, şi lui Dumnezeu ce este al lui Dumnezeu.” Şi se mirau foarte mult de El.",
    "Saducheii, care zic că nu este înviere, au venit la Isus şi I-au pus următoarea întrebare:",
    "„Învăţătorule, iată ce ne-a scris Moise: „Dacă moare fratele cuiva şi-i rămâne nevasta fără să aibă copii, fratele său să ia pe nevasta lui şi să ridice urmaş fratelui său.”",
    "Erau, dar, şapte fraţi. Cel dintâi s-a însurat şi a murit fără să lase urmaş.",
    "Al doilea a luat de nevastă pe văduvă şi a murit fără să lase urmaş. Tot aşa şi al treilea.",
    "Şi niciunul din cei şapte n-a lăsat urmaş. După ei toţi, a murit şi femeia.",
    "La înviere, nevasta căruia dintre ei va fi ea? Căci toţi şapte au avut-o de nevastă.”",
    "Drept răspuns, Isus le-a zis: „Oare nu vă rătăciţi voi, din pricină că nu pricepeţi nici Scripturile, nici puterea lui Dumnezeu?",
    "Căci după ce vor învia din morţi, nici nu se vor însura, nici nu se vor mărita, ci vor fi ca îngerii în ceruri.",
    "În ce priveşte învierea morţilor, oare n-aţi citit în cartea lui Moise, în locul unde se vorbeşte despre „Rug”, ce i-a spus Dumnezeu, când a zis: „Eu sunt Dumnezeul lui Avraam, Dumnezeul lui Isaac şi Dumnezeul lui Iacov”?",
    "Dumnezeu nu este un Dumnezeu al celor morţi, ci al celor vii. Tare vă mai rătăciţi!”",
    "Unul din cărturari, care-i auzise vorbind, fiindcă ştia că Isus răspunsese bine saducheilor, a venit la El şi L-a întrebat: „Care este cea dintâi dintre toate poruncile?”",
    "Isus i-a răspuns: „Cea dintâi este aceasta: „Ascultă Israele! Domnul Dumnezeul nostru este un singur Domn”;",
    "şi: „Să iubeşti pe Domnul Dumnezeul tău cu toată inima ta, cu tot sufletul tău, cu tot cugetul tău şi cu toată puterea ta”; iată porunca dintâi.",
    "Iar a doua este următoarea: „Să iubeşti pe aproapele tău ca pe tine însuţi.” Nu este altă poruncă mai mare decât acestea.”",
    "Cărturarul I-a zis: „Bine, Învăţătorule. Adevărat ai zis că Dumnezeu este unul singur, că nu este altul afară de El",
    "şi că a-L iubi cu toată inima, cu tot cugetul, cu tot sufletul şi cu toată puterea şi a iubi pe aproapele ca pe sine este mai mult decât toate arderile de tot şi decât toate jertfele.”",
    "Isus a văzut că a răspuns cu pricepere şi i-a zis: „Tu nu eşti departe de Împărăţia lui Dumnezeu.” Şi nimeni nu îndrăznea să-I mai pună întrebări.",
    "Pe când învăţa pe norod în Templu, Isus a zis: „Cum zic cărturarii că Hristosul este fiul lui David?",
    "Însuşi David, fiind insuflat de Duhul Sfânt, a zis: „Domnul a zis Domnului meu: „Şezi la dreapta Mea, până voi pune pe vrăjmaşii Tăi sub picioarele Tale.”",
    "Deci chiar David Îl numeşte Domn; atunci cum este El fiul lui?” Şi gloata cea mare Îl asculta cu plăcere.",
    "În învăţătura pe care le-o dădea, Isus le zicea: „Păziţi-vă de cărturari, cărora le place să umble în haine lungi şi să le facă lumea plecăciuni prin pieţe.",
    "Ei umblă după scaunele dintâi în sinagogi şi după locurile dintâi la ospeţe;",
    "casele văduvelor le mănâncă şi fac rugăciuni lungi de ochii lumii. O mai mare osândă va veni peste ei.”",
    "Isus şedea jos în faţa vistieriei Templului şi Se uita cum arunca norodul bani în vistierie. Mulţi, care erau bogaţi, aruncau mult.",
    "A venit şi o văduvă săracă şi a aruncat doi bănuţi, care fac un gologan.",
    "Atunci Isus a chemat pe ucenicii Săi şi le-a zis: „Adevărat vă spun că această văduvă săracă a dat mai mult decât toţi cei ce au aruncat în vistierie;",
    "căci toţi ceilalţi au aruncat din prisosul lor, dar ea, din sărăcia ei, a aruncat tot ce avea, tot ce-i mai rămăsese ca să trăiască.”",
  ],
  [
    "",
    "Când a ieşit Isus din Templu, unul din ucenicii Lui I-a zis: „Învăţătorule, uită-Te ce pietre şi ce zidiri!”",
    "Isus i-a răspuns: „Vezi tu aceste zidiri mari? Nu va rămâne aici piatră pe piatră care să nu fie dărâmată.”",
    "Apoi a şezut pe Muntele Măslinilor în faţa Templului. Şi Petru, Iacov, Ioan şi Andrei L-au întrebat deoparte:",
    "„Spune-ne când se vor întâmpla aceste lucruri şi care va fi semnul când se vor împlini toate aceste lucruri?”",
    "Isus a început atunci să le spună: „Băgaţi de seamă să nu vă înşele cineva.",
    "Fiindcă vor veni mulţi în Numele Meu şi vor zice: „Eu sunt Hristosul!” Şi vor înşela pe mulţi.",
    "Când veţi auzi despre războaie şi veşti de războaie, să nu vă înspăimântaţi, căci lucrurile acestea trebuie să se întâmple. Dar încă nu va fi sfârşitul.",
    "Un neam se va scula împotriva altui neam, şi o împărăţie împotriva altei împărăţii; pe alocuri vor fi cutremure de pământ, foamete şi tulburări. Aceste lucruri vor fi începutul durerilor.",
    "Luaţi seama la voi înşivă. Au să vă dea pe mâna soboarelor judecătoreşti şi veţi fi bătuţi în sinagogi; din pricina Mea veţi fi duşi înaintea dregătorilor şi înaintea împăraţilor, pentru ca să le slujiţi de mărturie.",
    "Mai întâi trebuie ca Evanghelia să fie propovăduită tuturor neamurilor.",
    "Când vă vor duce să vă dea în mâinile lor, să nu vă îngrijoraţi mai dinainte cu privire la cele ce veţi vorbi, ci să vorbiţi orice vi se va da să vorbiţi în ceasul acela; căci nu voi veţi vorbi, ci Duhul Sfânt.",
    "Fratele va da la moarte pe fratele său, şi tatăl pe copilul lui; copiii se vor scula împotriva părinţilor lor şi-i vor omorî.",
    "Veţi fi urâţi de toţi pentru Numele Meu; dar cine va răbda până la sfârşit va fi mântuit.",
    "Când veţi vedea „urâciunea pustiirii” stând acolo unde nu se cade să fie – cine citeşte să înţeleagă – atunci cei ce vor fi în Iudeea să fugă la munţi.",
    "Cine va fi pe acoperişul casei să nu se coboare şi să nu intre în casă ca să-şi ia ceva din ea.",
    "Şi cine va fi la câmp să nu se întoarcă înapoi ca să-şi ia haina.",
    "Vai de femeile care vor fi însărcinate şi de cele ce vor da ţâţă în zilele acelea!",
    "Rugaţi-vă ca lucrurile acestea să nu se întâmple iarna.",
    "Pentru că în zilele acelea va fi un necaz aşa de mare cum n-a fost de la începutul lumii pe care a făcut-o Dumnezeu până azi, şi cum nici nu va mai fi vreodată.",
    "Şi dacă n-ar fi scurtat Domnul zilele acelea, nimeni n-ar scăpa; dar le-a scurtat din pricina celor aleşi.",
    "Dacă vă va zice cineva atunci: „Iată, Hristosul este aici” sau: „Iată-L acolo”, să nu-l credeţi.",
    "Căci se vor scula hristoşi mincinoşi şi proroci mincinoşi. Ei vor face semne şi minuni, ca să înşele, dacă ar fi cu putinţă, şi pe cei aleşi.",
    "Păziţi-vă, iată că vi le-am spus toate dinainte.",
    "Dar, în zilele acelea, după necazul acesta, soarele se va întuneca, luna nu-şi va mai da lumina ei,",
    "stelele vor cădea din cer şi puterile care sunt în ceruri vor fi clătinate.",
    "Atunci se va vedea Fiul omului venind pe nori cu mare putere şi cu slavă.",
    "Atunci va trimite pe îngerii Săi şi va aduna pe cei aleşi din cele patru vânturi, de la marginea pământului până la marginea cerului.",
    "Luaţi învăţătură de la smochin prin pilda lui. Când mlădiţa lui se face fragedă şi înfrunzeşte, ştiţi că vara este aproape.",
    "Tot aşa, când veţi vedea aceste lucruri împlinindu-se, să ştiţi că Fiul omului este aproape, este chiar la uşi.",
    "Adevărat vă spun că nu va trece neamul acesta până nu se vor împlini toate aceste lucruri.",
    "Cerul şi pământul vor trece, dar cuvintele Mele nu vor trece.",
    "Cât despre ziua aceea sau ceasul acela, nu ştie nimeni, nici îngerii din ceruri, nici Fiul, ci numai Tatăl.",
    "Luaţi seama, vegheaţi şi rugaţi-vă; căci nu ştiţi când va veni vremea aceea.",
    "Se va întâmpla ca şi cu un om plecat în altă ţară, care îşi lasă casa, dă robilor săi putere, arată fiecăruia care este datoria lui şi porunceşte portarului să vegheze.",
    "Vegheaţi, dar, pentru că nu ştiţi când va veni stăpânul casei: sau seara, sau la miezul nopţii, sau la cântarea cocoşilor, sau dimineaţa.",
    "Temeţi-vă ca nu cumva, venind fără veste, să vă găsească dormind.",
    "Ce vă zic vouă, zic tuturor: Vegheaţi!”",
  ],
  [
    "",
    "După două zile era praznicul Paştilor şi al Azimelor. Preoţii cei mai de seamă şi cărturarii căutau cum să prindă pe Isus cu vicleşug şi să-L omoare.",
    "Căci ziceau: „Nu în timpul praznicului, ca nu cumva să se facă tulburare în norod.”",
    "Pe când şedea Isus la masă, în Betania, în casa lui Simon, leprosul, a venit o femeie care avea un vas de alabastru cu mir de nard curat, foarte scump; şi, după ce a spart vasul, a turnat mirul pe capul lui Isus.",
    "Unora dintre ei le-a fost necaz şi ziceau: „Ce rost are risipa aceasta de mir?",
    "Mirul acesta s-ar fi putut vinde cu mai mult de trei sute de lei şi să se dea săracilor.” Şi le era foarte necaz pe femeia aceea.",
    "Dar Isus le-a zis: „Lăsaţi-o în pace; de ce-i faceţi supărare? Ea a făcut un lucru frumos faţă de Mine;",
    "căci pe săraci îi aveţi totdeauna cu voi şi le puteţi face bine oricând voiţi, dar pe Mine nu Mă aveţi totdeauna.",
    "Ea a făcut ce a putut; Mi-a uns trupul mai dinainte, pentru îngropare.",
    "Adevărat vă spun că, oriunde va fi propovăduită Evanghelia aceasta, în toată lumea, se va istorisi şi ce a făcut femeia aceasta, spre pomenirea ei.”",
    "Iuda Iscarioteanul, unul din cei doisprezece, s-a dus la preoţii cei mai de seamă ca să le vândă pe Isus.",
    "Când au auzit ei lucrul acesta, s-au bucurat şi i-au făgăduit bani. Şi Iuda căuta un prilej nimerit ca să-L dea în mâinile lor.",
    "În ziua dintâi a praznicului Azimelor, când jertfeau paştile, ucenicii lui Isus I-au zis: „Unde voieşti să ne ducem să-Ţi pregătim ca să mănânci paştile?”",
    "El a trimis pe doi din ucenicii Săi şi le-a zis: „Duceţi-vă în cetate; acolo aveţi să întâlniţi un om ducând un ulcior cu apă: mergeţi după el.",
    "Unde va intra el, spuneţi stăpânului casei: „Învăţătorul zice: „Unde este odaia pentru oaspeţi, în care să mănânc paştile cu ucenicii Mei?”",
    "Şi are să vă arate o odaie mare de sus, aşternută gata: acolo să pregătiţi pentru noi.”",
    "Ucenicii au plecat, au ajuns în cetate şi au găsit aşa cum le spusese El; şi au pregătit paştile.",
    "Seara, Isus a venit cu cei doisprezece.",
    "Pe când şedeau la masă şi mâncau, Isus a zis: „Adevărat vă spun că unul din voi, care mănâncă cu Mine, Mă va vinde.”",
    "Ei au început să se întristeze şi să-I zică unul după altul: „Nu cumva sunt eu?”",
    "„Este unul din cei doisprezece”, le-a răspuns El, „şi anume, cel ce întinde mâna cu Mine în blid.",
    "Fiul omului, negreşit, Se duce după cum este scris despre El. Dar vai de omul acela prin care este vândut Fiul omului! Mai bine ar fi fost pentru el să nu se fi născut.”",
    "Pe când mâncau, Isus a luat o pâine; şi, după ce a binecuvântat, a frânt-o şi le-a dat, zicând: „Luaţi, mâncaţi, acesta este trupul Meu.”",
    "Apoi a luat un pahar şi, după ce a mulţumit lui Dumnezeu, li l-a dat, şi au băut toţi din el.",
    "Şi le-a zis: „Acesta este sângele Meu, sângele legământului celui nou, care se varsă pentru mulţi.",
    "Adevărat vă spun că, de acum încolo, nu voi mai bea din rodul viţei, până în ziua când îl voi bea nou în Împărăţia lui Dumnezeu.”",
    "După ce au cântat cântările de laudă, au ieşit pe Muntele Măslinilor.",
    "Isus le-a zis: „În noaptea aceasta toţi veţi avea un prilej de poticnire; pentru că este scris: „Voi bate Păstorul, şi oile vor fi risipite.”",
    "Dar, după ce voi învia, voi merge înaintea voastră în Galileea.”",
    "Petru I-a zis: „Chiar dacă toţi ar avea un prilej de poticnire, eu nu voi avea.”",
    "Şi Isus i-a zis: „Adevărat îţi spun că astăzi, chiar în noaptea aceasta, înainte ca să cânte cocoşul de două ori, te vei lepăda de Mine de trei ori.”",
    "Dar Petru I-a zis cu şi mai multă tărie: „Chiar dacă ar trebui să mor împreună cu Tine, tot nu mă voi lepăda de Tine.” Şi toţi ceilalţi au spus acelaşi lucru.",
    "S-au dus apoi într-un loc îngrădit, numit Ghetsimani. Şi Isus a zis ucenicilor Săi: „Şedeţi aici până Mă voi ruga.”",
    "A luat cu El pe Petru, pe Iacov şi pe Ioan şi a început să Se înspăimânte şi să Se mâhnească foarte tare.",
    "El le-a zis: „Sufletul Meu este cuprins de o întristare de moarte; rămâneţi aici şi vegheaţi!”",
    "Apoi a mers puţin mai înainte, S-a aruncat la pământ şi Se ruga ca, dacă este cu putinţă, să treacă de la El ceasul acela.",
    "El zicea: „Ava – adică: Tată – Ţie toate lucrurile Îţi sunt cu putinţă; depărtează de la Mine paharul acesta! Totuşi, facă-se nu ce voiesc Eu, ci ce voieşti Tu.”",
    "Şi a venit la ucenici, pe care i-a găsit dormind. Şi a zis lui Petru: „Simone, tu dormi? Un ceas n-ai fost în stare să veghezi?",
    "Vegheaţi şi rugaţi-vă, ca să nu cădeţi în ispită; duhul este plin de râvnă, dar trupul este neputincios.”",
    "S-a dus iarăşi şi S-a rugat, zicând aceleaşi cuvinte.",
    "Apoi S-a întors din nou şi i-a găsit dormind; pentru că li se îngreuiaseră ochii de somn. Ei nu ştiau ce să-I răspundă.",
    "În sfârşit, a venit a treia oară şi le-a zis: „Dormiţi de acum şi odihniţi-vă! Destul! A venit ceasul! Iată că Fiul omului este dat în mâinile păcătoşilor.",
    "Sculaţi-vă; haidem să mergem; iată că se apropie vânzătorul!”",
    "Şi îndată, pe când vorbea El încă, a venit Iuda, unul din cei doisprezece, şi împreună cu el a venit o mulţime de oameni cu săbii şi cu ciomege, trimişi de preoţii cei mai de seamă, de cărturari şi de bătrâni.",
    "Vânzătorul le dăduse semnul acesta: „Pe care-L voi săruta, Acela este; să-L prindeţi şi să-L duceţi sub pază.”",
    "Când a venit Iuda, s-a apropiat îndată de Isus şi I-a zis: „Învăţătorule!” Şi L-a sărutat mult.",
    "Atunci oamenii aceia au pus mâna pe Isus şi L-au prins.",
    "Unul din cei ce stăteau lângă El a scos sabia, a lovit pe robul marelui preot şi i-a tăiat urechea.",
    "Isus a luat cuvântul şi le-a zis: „Aţi ieşit ca după un tâlhar, cu săbii şi cu ciomege, ca să Mă prindeţi.",
    "În toate zilele am fost la voi şi învăţam pe oameni în Templu, şi nu M-aţi prins. Dar toate aceste lucruri s-au întâmplat ca să se împlinească Scripturile.”",
    "Atunci toţi ucenicii L-au părăsit şi au fugit.",
    "După El mergea un tânăr care n-avea pe trup decât o învelitoare de pânză de in. Au pus mâna pe el;",
    "dar el şi-a lăsat învelitoarea şi a fugit în pielea goală.",
    "Pe Isus L-au dus la marele preot, unde s-au adunat toţi preoţii cei mai de seamă, bătrânii şi cărturarii.",
    "Petru L-a urmat de departe până în curtea marelui preot; a şezut jos împreună cu aprozii şi se încălzea la para focului.",
    "Preoţii cei mai de seamă şi tot soborul căutau vreo mărturie împotriva lui Isus, ca să-L omoare; dar nu găseau niciuna.",
    "Pentru că mulţi făceau mărturisiri mincinoase împotriva Lui, dar mărturisirile lor nu se potriveau.",
    "Unii s-au sculat şi au făcut o mărturisire mincinoasă împotriva Lui şi au zis:",
    "„Noi L-am auzit zicând: „Eu voi strica Templul acesta, făcut de mâini omeneşti, şi în trei zile voi ridica un altul, care nu va fi făcut de mâini omeneşti.”",
    "Nici chiar în privinţa aceasta nu se potrivea mărturisirea lor.",
    "Atunci marele preot s-a sculat în picioare în mijlocul adunării, a întrebat pe Isus şi I-a zis: „Nu răspunzi nimic? Ce mărturisesc oamenii aceştia împotriva Ta?”",
    "Isus tăcea şi nu răspundea nimic. Marele preot L-a întrebat iarăşi şi I-a zis: „Eşti Tu, Hristosul, Fiul Celui binecuvântat?”",
    "„Da, sunt”, i-a răspuns Isus. „Şi veţi vedea pe Fiul omului şezând la dreapta puterii şi venind pe norii cerului.”",
    "Atunci marele preot şi-a rupt hainele şi a zis: „Ce nevoie mai avem de martori?",
    "Aţi auzit hula. Ce vi se pare?” Toţi L-au osândit să fie pedepsit cu moartea.",
    "Şi unii au început să-L scuipe, să-I acopere faţa, să-L bată cu pumnii şi să-I zică: „Proroceşte!” Iar aprozii L-au primit în palme.",
    "Pe când stătea Petru jos în curte, a venit una din slujnicele marelui preot.",
    "Când a văzut pe Petru încălzindu-se, s-a uitat ţintă la el şi i-a zis: „Şi tu erai cu Isus din Nazaret!”",
    "El s-a lepădat şi a zis: „Nu ştiu, nici nu înţeleg ce vrei să zici.” Apoi a ieşit în pridvor. Şi a cântat cocoşul.",
    "Când l-a văzut slujnica, a început iarăşi să spună celor ce stăteau acolo: „Acesta este unul dintre oamenii aceia.”",
    "Şi el s-a lepădat din nou. După puţină vreme, cei ce stăteau acolo, au zis iarăşi lui Petru: „Nu mai încape îndoială că eşti unul din oamenii aceia; căci eşti galileean, şi graiul tău seamănă cu al lor.”",
    "Atunci el a început să se blesteme şi să se jure: „Nu cunosc pe Omul acesta despre care vorbiţi!”",
    "Îndată a cântat cocoşul a doua oară. Şi Petru şi-a adus aminte de vorba pe care i-o spusese Isus: „Înainte ca să cânte cocoşul de două ori, te vei lepăda de Mine de trei ori.” Şi gândindu-se la acest lucru, a început să plângă.",
  ],
  [
    "",
    "Dimineaţa, preoţii cei mai de seamă au făcut îndată sfat cu bătrânii, cărturarii şi tot soborul. După ce au legat pe Isus, L-au dus şi L-au dat în mâinile lui Pilat.",
    "Pilat L-a întrebat: „Eşti Tu Împăratul iudeilor?” „Da, sunt”, i-a răspuns Isus.",
    "Preoţii cei mai de seamă Îl învinuiau de multe lucruri.",
    "Pilat L-a întrebat din nou: „Nu răspunzi nimic? Uite de câte lucruri Te învinuiesc ei!”",
    "Isus n-a mai dat niciun răspuns, lucru care a mirat pe Pilat.",
    "La fiecare praznic al Paştilor, Pilat le slobozea un întemniţat pe care-l cereau ei.",
    "În temniţă era unul numit Baraba, închis împreună cu tovarăşii lui din pricina unui omor pe care-l săvârşiseră într-o răscoală.",
    "Norodul s-a suit şi a început să ceară lui Pilat să le dea ce avea obicei să le dea întotdeauna.",
    "Pilat le-a răspuns: „Voiţi să vă slobod pe Împăratul iudeilor?”",
    "Căci pricepuse că preoţii cei mai de seamă din pizmă Îl dăduseră în mâna lui.",
    "Dar preoţii cei mai de seamă au aţâţat norodul să ceară lui Pilat să le sloboadă mai bine pe Baraba.",
    "Pilat a luat din nou cuvântul şi le-a zis: „Dar ce voiţi să fac cu Acela pe care-L numiţi Împăratul iudeilor?”",
    "Ei au strigat din nou: „Răstigneşte-L!”",
    "„Dar ce rău a făcut?”, le-a zis Pilat. Însă ei au început să strige şi mai tare: „Răstigneşte-L!”",
    "Pilat a vrut să facă pe placul norodului, şi le-a slobozit pe Baraba; iar pe Isus, după ce a pus să-L bată cu nuiele, L-a dat să fie răstignit.",
    "Ostaşii au adus pe Isus în curte, adică în palat, şi au adunat toată ceata ostaşilor.",
    "L-au îmbrăcat într-o haină de purpură, au împletit o cunună de spini şi I-au pus-o pe cap.",
    "Apoi au început să-I ureze şi să zică: „Plecăciune, Împăratul iudeilor!”",
    "Şi-L loveau în cap cu o trestie, Îl scuipau, îngenuncheau şi I se închinau.",
    "După ce şi-au bătut astfel joc de El, L-au dezbrăcat de haina de purpură, L-au îmbrăcat în hainele Lui şi L-au dus să-L răstignească.",
    "Au silit să ducă crucea lui Isus pe un trecător care se întorcea de la câmp, numit Simon din Cirena, tatăl lui Alexandru şi al lui Ruf.",
    "Şi au adus pe Isus la locul numit Golgota, care tălmăcit înseamnă: „Locul căpăţânii”.",
    "I-au dat să bea vin amestecat cu smirnă, dar El nu l-a luat.",
    "După ce L-au răstignit, I-au împărţit hainele între ei trăgând la sorţi, ca să ştie ce să ia fiecare.",
    "Când L-au răstignit, era ceasul al treilea.",
    "Deasupra Lui era scrisă vina Lui: „Împăratul iudeilor.”",
    "Împreună cu El au răstignit doi tâlhari, unul la dreapta, şi altul la stânga Lui.",
    "Astfel s-a împlinit Scriptura care zice: „A fost pus în numărul celor fărădelege.”",
    "Trecătorii îşi băteau joc de El, dădeau din cap şi ziceau: „Uă! Tu, care strici Templul şi-l zideşti la loc în trei zile,",
    "mântuieşte-Te pe Tine însuţi şi coboară-Te de pe cruce!”",
    "Tot astfel şi preoţii cei mai de seamă, împreună cu cărturarii, îşi băteau joc de El între ei şi ziceau: „Pe alţii i-a mântuit, şi pe Sine însuşi nu Se poate mântui!",
    "Hristosul, Împăratul lui Israel, să Se coboare acum de pe cruce, ca să vedem şi să credem!” Cei răstigniţi împreună cu El, de asemenea, îşi băteau joc de El.",
    "La ceasul al şaselea, s-a făcut întuneric peste toată ţara, până la ceasul al nouălea.",
    "Şi, în ceasul al nouălea, Isus a strigat cu glas tare: „Eloi, Eloi, lama sabactani”, care tălmăcit înseamnă: „Dumnezeul Meu, Dumnezeul Meu, pentru ce M-ai părăsit?”",
    "Unii din cei ce stăteau acolo, când L-au auzit, ziceau: „Iată, cheamă pe Ilie!”",
    "Şi unul din ei a alergat de a umplut un burete cu oţet, l-a pus într-o trestie şi I-a dat să bea, zicând: „Lăsaţi să vedem dacă va veni Ilie să-L coboare de pe cruce!”",
    "Dar Isus a scos un strigăt tare şi Şi-a dat duhul.",
    "Perdeaua dinăuntrul Templului s-a rupt în două, de sus până jos.",
    "Sutaşul care stătea în faţa lui Isus, când a văzut că Şi-a dat astfel duhul, a zis: „Cu adevărat, Omul acesta era Fiul lui Dumnezeu!”",
    "Acolo erau şi nişte femei care priveau de departe. Printre ele erau Maria Magdalena, Maria, mama lui Iacov cel mic şi a lui Iose, şi Salome,",
    "care, pe când era El în Galileea, mergeau după El şi-I slujeau; şi multe alte femei care se suiseră împreună cu El în Ierusalim.",
    "Când s-a înserat – fiindcă era ziua Pregătirii, adică ziua dinaintea Sabatului –",
    "a venit Iosif din Arimateea, un sfetnic cu vază al soborului, care şi el aştepta Împărăţia lui Dumnezeu. El a îndrăznit să se ducă la Pilat ca să ceară trupul lui Isus.",
    "Pilat s-a mirat că murise aşa de curând; a chemat pe sutaş şi l-a întrebat dacă a murit de mult.",
    "După ce s-a încredinţat de la sutaş că a murit, a dăruit lui Iosif trupul.",
    "Şi Iosif a cumpărat o pânză subţire de in, a dat jos pe Isus de pe cruce, L-a înfăşurat în pânza de in şi L-a pus într-un mormânt săpat în stâncă. Apoi a prăvălit o piatră la uşa mormântului.",
    "Maria Magdalena şi Maria, mama lui Iose, se uitau unde-L puneau.",
  ],
  [
    "",
    "După ce a trecut ziua Sabatului, Maria Magdalena, Maria, mama lui Iacov, şi Salome au cumpărat miresme ca să se ducă să ungă trupul lui Isus.",
    "În ziua dintâi a săptămânii, s-au dus la mormânt dis-de-dimineaţă, pe când răsărea soarele.",
    "Femeile ziceau una către alta: „Cine ne va prăvăli piatra de la uşa mormântului?”",
    "Şi, când şi-au ridicat ochii, au văzut că piatra, care era foarte mare, fusese prăvălită.",
    "Au intrat în mormânt, au văzut pe un tinerel şezând la dreapta, îmbrăcat într-un veşmânt alb, şi s-au înspăimântat.",
    "El le-a zis: „Nu vă înspăimântaţi! Căutaţi pe Isus din Nazaret care a fost răstignit: a înviat, nu este aici; iată locul unde Îl puseseră.",
    "Dar duceţi-vă de spuneţi ucenicilor Lui şi lui Petru, că merge înaintea voastră în Galileea: acolo Îl veţi vedea, cum v-a spus.”",
    "Ele au ieşit afară din mormânt şi au luat-o la fugă, pentru că erau cuprinse de cutremur şi de spaimă. Şi n-au spus nimănui nimic, căci se temeau.",
    "(Isus, după ce a înviat, în dimineaţa zilei dintâi a săptămânii, S-a arătat mai întâi Mariei Magdalena, din care scosese şapte draci.",
    "Ea s-a dus şi a dat de ştire celor ce fuseseră împreună cu El, care plângeau şi se tânguiau.",
    "Când au auzit ei că este viu şi că a fost văzut de ea, n-au crezut-o.",
    "După aceea S-a arătat, în alt chip, la doi dintre ei, pe drum, când se duceau la ţară.",
    "Aceştia s-au dus de au spus lucrul acesta celorlalţi, dar nici pe ei nu i-au crezut.",
    "În sfârşit, S-a arătat celor unsprezece, când şedeau la masă; şi i-a mustrat pentru necredinţa şi împietrirea inimii lor, pentru că nu crezuseră pe cei ce-L văzuseră înviat.",
    "Apoi le-a zis: „Duceţi-vă în toată lumea şi propovăduiţi Evanghelia la orice făptură.",
    "Cine va crede şi se va boteza va fi mântuit; dar cine nu va crede va fi osândit.",
    "Iată semnele care vor însoţi pe cei ce vor crede: în Numele Meu vor scoate draci; vor vorbi în limbi noi;",
    "vor lua în mână şerpi; dacă vor bea ceva de moarte, nu-i va vătăma; îşi vor pune mâinile peste bolnavi, şi bolnavii se vor însănătoşi.”",
    "Domnul Isus, după ce a vorbit cu ei, S-a înălţat la cer şi a şezut la dreapta lui Dumnezeu.",
    "Iar ei au plecat şi au propovăduit pretutindeni. Domnul lucra împreună cu ei şi întărea Cuvântul prin semnele care-l însoţeau. Amin.)",
  ],
]

export function marcuVerseCount(chapter: number): number {
  const verses = MARCU_TEXT[chapter]
  if (!verses) throw new Error(`[Marcu] capitol necunoscut: ${chapter}.`)
  return verses.length - 1
}

export function marcuPassage(chapter: number, from: number, to: number): string {
  const verses = MARCU_TEXT[chapter]
  if (!verses || from < 1 || to < from || to >= verses.length) {
    throw new Error(`[Marcu ${chapter}] pasaj invalid: ${from}-${to}.`)
  }
  return verses.slice(from, to + 1).join(" ")
}
