import { marcuChapter, teaching } from "./marcuHelpers.js"

export const MARCU_12 = marcuChapter({
  number: 12,
  title: "Marcu 12 — Piatra din capul unghiului și dragostea întreagă",
  summary: "Pilda vierilor arată respingerea Fiului, iar Isus răspunde încercărilor despre bir, înviere și cea mai mare poruncă. El demască religia care caută cinste și laudă dărnicia văduvei care pune în vistierie tot ce avea.",
  literaryContext: "După întrebarea despre autoritate, Isus spune o pildă care numește vina conducătorilor. Urmează trei întrebări menite să-L prindă și un răspuns care concentrează Legea în dragoste. Capitolul se încheie cu contrastul dintre cărturarii vizibili și văduva nevăzută.",
  historicalContext: "Via și vierii evocau Israelul din Isaia 5. Dinarul purta chipul cezarului. Saducheii negau învierea și acceptau cu precădere autoritatea celor cinci cărți ale lui Moise. Vistieria Templului avea cutii pentru daruri, iar doi bănuți reprezentau aproape nimic economic.",
  units: [
    { verses: [1, 12], heading: "Piatra lepădată de zidari", teaching: teaching("Stăpânul viei trimite slujitori după rod, dar vierii îi bat și îi omoară. În cele din urmă trimite pe fiul preaiubit, iar ei îl ucid ca să ia moștenirea. Pilda arată răbdarea lui Dumnezeu și gravitatea respingerii Fiului.", "Piatra lepădată de zidari ajunge în capul unghiului. Crucea, care pare victoria conducătorilor, devine lucrarea minunată prin care Dumnezeu Îl înalță pe Fiul și zidește poporul Său."), crossRefs: ["Isaia 5:1-7", "Psalmul 118:22-23", "1 Petru 2:4-7"], forYourHeart: "Nu încerca să păstrezi via pentru tine. Dă-I Stăpânului rodul și zidește pe Piatra pe care oamenii au lepădat-o." },
    { verses: [13, 27], heading: "Dați lui Dumnezeu ce este al lui Dumnezeu", teaching: teaching("Întrebarea despre bir este o capcană politică. Isus cere moneda și arată chipul cezarului: ceea ce poartă chipul lui poate fi dat lui, dar omul poartă chipul lui Dumnezeu și Îi aparține întreg.", "Saducheii ridiculizează învierea printr-o poveste despre șapte frați. Isus spune că nu cunosc nici Scripturile, nici puterea lui Dumnezeu. Învierea nu este simpla continuare a rânduielilor de acum; Dumnezeu este Dumnezeul celor vii, iar legământul Lui cu Avraam, Isaac și Iacov nu este învins de mormânt."), crossRefs: ["Geneza 1:27", "Romani 13:1-7", "Exod 3:6", "1 Corinteni 15:42-49"], forYourHeart: "Poartă responsabil ceea ce aparține cetății, dar nu uita cui aparține chipul din tine: dă-I lui Dumnezeu întreaga viață." },
    { verses: [28, 34], heading: "Să iubești pe Domnul și pe aproapele", teaching: teaching("Un cărturar întreabă care este întâia poruncă. Isus unește Deuteronom 6 cu Levitic 19: Dumnezeu este unul și trebuie iubit cu toată inima, sufletul, mintea și puterea; aproapele trebuie iubit ca noi înșine.", "Dragostea este mai mult decât toate jertfele. Cărturarul înțelege și nu este departe de Împărăție, dar apropierea intelectuală nu este încă intrare: adevărul trebuie primit și trăit sub domnia Regelui."), crossRefs: ["Deuteronom 6:4-5", "Levitic 19:18", "Romani 13:8-10"], forYourHeart: "Nu-I da lui Dumnezeu un colț religios. Iubește-L cu omul întreg și lasă iubirea aceasta să ajungă la aproapele concret." },
    { verses: [35, 44], heading: "Tot ce mai avea ca să trăiască", teaching: teaching("Isus arată că Mesia este și fiul lui David, și Domnul lui David. Apoi avertizează împotriva cărturarilor care iubesc hainele, saluturile și locurile dintâi, dar mistuie casele văduvelor. Religia care caută cinste și exploatează pe cei slabi va primi o osândă mai mare.", "În fața vistieriei, bogații dau mult din prisos, iar o văduvă pune doi bănuți — tot ce avea. Isus măsoară nu suma, ci ce a costat-o darul. Textul laudă încrederea ei și, lângă avertismentul despre casele văduvelor, mustră un sistem religios care primește de la vulnerabili fără să-i ocrotească."), crossRefs: ["Psalmul 110:1", "Luca 20:45-21:4", "2 Corinteni 8:12"], forYourHeart: "Dumnezeu vede darul pe care nimeni nu-l observă și vede și povara lui. Dă-I cu încredere, dar nu folosi niciodată credința ca să apeși pe cel vulnerabil." },
  ],
  prayer: "Doamne Isuse, Piatra din capul unghiului, primește rodul vieții noastre. Ajută-ne să-Ți dăm ceea ce poartă chipul Tău, să credem puterea învierii și să Te iubim cu omul întreg. Curăță-ne de dorința de cinste și dă-ne inima văduvei, împreună cu grija Ta pentru cei slabi. Amin.",
})
