/*
 * Textul Evangheliei după Marcu, Cornilescu, editia corectata (RCCV).
 * Sursa de colationare: https://github.com/seven1m/open-bibles (ron-rccv.usfx.xml)
 *
 * Indicele zero al fiecărui capitol rămâne gol, astfel încât numărul
 * versetului să fie și indicele lui. Comentariul nu intră în acest fișier.
 */

const MARCU_TEXT: readonly (readonly string[])[] = [

  [],
  [
    "",
    "Începutul Evangheliei lui Isus Hristos, Fiul lui Dumnezeu.",
    "După cum este scris în prorocul Isaia: „Iată, trimit înaintea Ta pe solul Meu, care Îți va pregăti calea…",
    "glasul celui ce strigă în pustiu: „Pregătiți calea Domnului, neteziți-I cărările”,",
    "a venit Ioan care boteza în pustiu, propovăduind botezul pocăinței spre iertarea păcatelor.",
    "Tot ținutul Iudeii și toți locuitorii Ierusalimului au început să iasă la el; și, mărturisindu-și păcatele, erau botezați de el în râul Iordan.",
    "Ioan era îmbrăcat cu o haină de păr de cămilă, și împrejurul mijlocului era încins cu un brâu de curea. El se hrănea cu lăcuste și miere sălbatică.",
    "Ioan propovăduia și zicea: „După mine vine Cel ce este mai puternic decât mine, căruia eu nu sunt vrednic să mă plec să-I dezleg curelele încălțămintei.",
    "Eu, da, v-am botezat cu apă; dar El vă va boteza cu Duhul Sfânt.”",
    "În vremea aceea, a venit Isus din Nazaretul Galileii și a fost botezat de Ioan în Iordan.",
    "Şi îndată, când ieșea Isus din apă, el a văzut cerurile deschise și Duhul coborându-Se peste El ca un porumbel.",
    "Şi din ceruri s-a auzit un glas care zicea: „Tu ești Fiul Meu preaiubit, în Tine Îmi găsesc toată plăcerea Mea.”",
    "Îndată Duhul a mânat pe Isus în pustiu,",
    "unde a stat patruzeci de zile, fiind ispitit de Satana. Acolo stătea împreună cu fiarele sălbatice, și-I slujeau îngerii.",
    "După ce a fost închis Ioan, Isus a venit în Galileea și propovăduia Evanghelia lui Dumnezeu.",
    "El zicea: „S-a împlinit vremea, și Împărăția lui Dumnezeu este aproape. Pocăiți-vă și credeți în Evanghelie.”",
    "Pe când trecea Isus pe lângă Marea Galileii, a văzut pe Simon și pe Andrei, fratele lui Simon, aruncând o mreajă în mare, căci erau pescari.",
    "Isus le-a zis: „Veniți după Mine, și vă voi face pescari de oameni.”",
    "Îndată, ei și-au lăsat mrejele și au mers după El.",
    "A mers puțin mai departe și a văzut pe Iacov, fiul lui Zebedei, și pe Ioan, fratele lui, care, și ei, erau într-o corabie și își dregeau mrejele.",
    "Îndată i-a chemat; și ei au lăsat pe tatăl lor, Zebedei, în corabie cu cei ce lucrau pe plată și au mers după El.",
    "S-au dus la Capernaum. Şi, în ziua Sabatului, Isus a intrat îndată în sinagogă și a început să învețe pe norod.",
    "Oamenii erau uimiți de învățătura Lui; căci îi învăța ca unul care are putere, nu cum îi învățau cărturarii.",
    "În sinagoga lor era un om care avea un duh necurat. El a început să strige:",
    "„Ce avem noi a face cu Tine, Isuse din Nazaret? Ai venit să ne pierzi? Te știu cine ești: ești Sfântul lui Dumnezeu!”",
    "Isus l-a certat și i-a zis: „Taci și ieși afară din omul acesta!”",
    "Şi duhul necurat a ieșit din el, scuturându-l cu putere și scoțând un strigăt mare.",
    "Toți au rămas înmărmuriți, așa că se întrebau unii pe alții: „Ce este aceasta? O învățătură nouă! El poruncește ca un stăpân chiar și duhurilor necurate, și ele Îl ascultă!”",
    "Şi îndată I s-a dus vestea în toate împrejurimile Galileii.",
    "După ce a ieșit din sinagogă, a intrat împreună cu Iacov și Ioan în casa lui Simon și a lui Andrei.",
    "Soacra lui Simon zăcea în pat prinsă de friguri; și îndată au vorbit lui Isus despre ea.",
    "El a venit, a apucat-o de mână, a ridicat-o în sus, și au lăsat-o frigurile. Apoi ea a început să le slujească.",
    "Seara, după asfințitul soarelui, au adus la El pe toți bolnavii și îndrăciții.",
    "Şi toată cetatea era adunată la ușă.",
    "El a vindecat pe mulți care pătimeau de felurite boli; de asemenea, a scos mulți draci și nu lăsa pe draci să vorbească, pentru că-L cunoșteau.",
    "A doua zi dimineața, pe când era încă întuneric de tot, Isus S-a sculat, a ieșit și S-a dus într-un loc pustiu. Şi Se ruga acolo.",
    "Simon și ceilalți care erau cu El s-au dus să-L caute;",
    "și, când L-au găsit, I-au zis: „Toți Te caută.”",
    "El le-a răspuns: „Haidem să mergem în altă parte, prin târgurile și satele vecine, ca să propovăduiesc și acolo; căci pentru aceasta am ieșit.”",
    "Şi S-a dus să propovăduiască în sinagogi, prin toată Galileea; și scotea dracii.",
    "A venit la El un lepros, care s-a aruncat în genunchi înaintea Lui, Îl ruga și-I zicea: „Dacă vrei, poți să mă cureți.”",
    "Lui Isus I s-a făcut milă de el, a întins mâna, S-a atins de el și i-a zis: „Da, voiesc, fii curățat!”",
    "Îndată l-a lăsat lepra, și s-a curățat.",
    "Isus i-a poruncit cu tot dinadinsul, i-a spus să plece numaidecât",
    "și i-a zis: „Vezi să nu spui nimănui nimic; ci du-te de te arată preotului și adu pentru curățarea ta ce a poruncit Moise, ca mărturie pentru ei.”",
    "Dar omul acela, după ce a plecat, a început să vestească și să spună în gura mare lucrul acesta, așa că Isus nu mai putea să intre pe față în nicio cetate; ci stătea afară, în locuri pustii, și veneau la El din toate părțile.",
  ],
  [
    "",
    "După câteva zile, Isus S-a întors în Capernaum. S-a auzit că este în casă",
    "și s-au adunat îndată așa de mulți, că nu putea să-i mai încapă locul dinaintea ușii. El le vestea Cuvântul.",
    "Au venit la El niște oameni care I-au adus un slăbănog, purtat de patru inși.",
    "Fiindcă nu puteau să ajungă până la El, din pricina norodului, au desfăcut acoperișul casei unde era Isus și, după ce l-au spart, au coborât pe acolo patul în care zăcea slăbănogul.",
    "Când le-a văzut Isus credința, a zis slăbănogului: „Fiule, păcatele îți sunt iertate!”",
    "Unii din cărturari, care erau de față, se gândeau în inimile lor:",
    "„Cum vorbește Omul acesta astfel? Hulește! Cine poate să ierte păcatele decât numai Dumnezeu?”",
    "Îndată, Isus a cunoscut, prin duhul Său, că ei gândeau astfel în ei și le-a zis: „Pentru ce aveți astfel de gânduri în inimile voastre?",
    "Ce este mai lesne: a zice slăbănogului: „Păcatele îți sunt iertate”, ori a zice: „Scoală-te, ridică-ți patul și umblă”?",
    "Dar, ca să știți că Fiul omului are putere pe pământ să ierte păcatele,",
    "„Ţie îți poruncesc”, a zis El slăbănogului, „scoală-te, ridică-ți patul și du-te acasă.”",
    "Şi îndată, slăbănogul s-a sculat, și-a ridicat patul și a ieșit afară în fața tuturor; așa că toți au rămas uimiți și slăveau pe Dumnezeu și ziceau: „Niciodată n-am văzut așa ceva!”",
    "Isus a ieșit iarăși la mare. Toată mulțimea venea la El; și El învăța pe toți.",
    "Când trecea pe acolo, a văzut pe Levi, fiul lui Alfeu, șezând la vamă. Şi i-a zis: „Vino după Mine!” Levi s-a sculat și a mers după El.",
    "Pe când ședea Isus la masă în casa lui Levi, mulți vameși și păcătoși au șezut și ei la masă cu El și cu ucenicii Lui; căci erau mulți care mergeau de obicei după El.",
    "Cărturarii și fariseii, când L-au văzut mâncând cu vameșii și cu păcătoșii, au zis ucenicilor Lui: „De ce mănâncă El și bea cu vameșii și cu păcătoșii?”",
    "Isus, când a auzit acest lucru, le-a zis: „Nu cei sănătoși au trebuință de doctor, ci cei bolnavi. Eu am venit să chem la pocăință nu pe cei neprihăniți, ci pe cei păcătoși.”",
    "Ucenicii lui Ioan și fariseii obișnuiau să postească. Ei au venit și au zis lui Isus: „Pentru ce ucenicii lui Ioan și ai fariseilor postesc, iar ucenicii Tăi nu postesc?”",
    "Isus le-a răspuns: „Oare pot posti nuntașii câtă vreme este mirele cu ei? Câtă vreme au pe mire cu ei, nu pot posti.",
    "Vor veni zile când va fi luat mirele de la ei, și atunci vor posti în ziua aceea.",
    "Nimeni nu coase un petic de postav nou la o haină veche; altfel, peticul de postav nou rupe o parte din cel vechi, și mai rea ruptură se face.",
    "Şi nimeni nu pune vin nou în burdufuri vechi; altfel, vinul cel nou sparge burdufurile, și vinul se varsă, iar burdufurile se prăpădesc; ci vinul nou este pus în burdufuri noi.”",
    "S-a întâmplat că într-o zi de Sabat, Isus trecea prin lanurile de grâu. Ucenicii Lui, pe când mergeau, au început să smulgă spice de grâu.",
    "Fariseii I-au zis: „Vezi, de ce fac ei ce nu este îngăduit să facă în ziua Sabatului?”",
    "Isus le-a răspuns: „Oare n-ați citit niciodată ce a făcut David, când a fost în nevoie și când a flămânzit el și cei ce erau împreună cu el?",
    "Cum a intrat în casa lui Dumnezeu, în zilele marelui preot Abiatar, și a mâncat pâinile pentru punerea înaintea Domnului, pe care nu este îngăduit să le mănânce decât preoții? Şi cum a dat din ele chiar și celor ce erau cu el?”",
    "Apoi le-a zis: „Sabatul a fost făcut pentru om, iar nu omul pentru Sabat;",
    "așa că Fiul omului este Domn chiar și al Sabatului.”",
  ],
  [
    "",
    "Isus a intrat din nou în sinagogă. Acolo se afla un om cu mâna uscată.",
    "Ei pândeau pe Isus să vadă dacă-l va vindeca în ziua Sabatului, ca să-L poată învinui.",
    "Şi Isus a zis omului care avea mâna uscată: „Scoală-te și stai la mijloc!”",
    "Apoi le-a zis: „Este îngăduit în ziua Sabatului să faci bine sau să faci rău? Să scapi viața cuiva sau s-o pierzi?” Dar ei tăceau.",
    "Atunci, rotindu-Şi privirile cu mânie peste ei și mâhnit de împietrirea inimii lor, a zis omului: „Întinde-ți mâna!” El a întins-o, și mâna i s-a făcut sănătoasă.",
    "Fariseii au ieșit afară și s-au sfătuit îndată cu irodienii cum să-L piardă.",
    "Isus S-a dus cu ucenicii Săi la mare. După El a mers o mare mulțime de oameni din Galileea; și o mare mulțime de oameni din Iudeea,",
    "din Ierusalim, din Idumeea, de dincolo de Iordan și dimprejurul Tirului și Sidonului, când a auzit tot ce făcea, a venit la El.",
    "Isus a poruncit ucenicilor să-I țină la îndemână o corăbioară, ca să nu fie îmbulzit de norod.",
    "Căci El vindeca pe mulți și de aceea toți cei ce aveau boli se înghesuiau spre El ca să se atingă de El.",
    "Duhurile necurate, când Îl vedeau, cădeau la pământ înaintea Lui și strigau: „Tu ești Fiul lui Dumnezeu.”",
    "Dar El le poruncea îndată cu tot dinadinsul să nu-L facă cunoscut.",
    "În urmă, Isus S-a suit pe munte; a chemat la El pe cine a vrut, și ei au venit la El.",
    "A rânduit dintre ei doisprezece, ca să-i aibă cu Sine și să-i trimită să propovăduiască.",
    "Le-a dat și putere să vindece bolile și să scoată dracii.",
    "Iată cei doisprezece pe care i-a rânduit: Simon, căruia i-a pus numele Petru;",
    "Iacov, fiul lui Zebedei, și Ioan, fratele lui Iacov, cărora le-a pus numele Boanerghes, care tălmăcit înseamnă: „Fiii tunetului”;",
    "Andrei; Filip; Bartolomeu; Matei; Toma; Iacov, fiul lui Alfeu; Tadeu; Simon, canaanitul,",
    "și Iuda Iscarioteanul, care L-a și vândut.",
    "Au venit în casă și s-a adunat din nou norodul, așa că nu puteau nici măcar să prânzească.",
    "Rudele lui Isus, când au auzit cele ce se petreceau, au venit să pună mâna pe El. Căci ziceau: „Şi-a ieșit din minți.”",
    "Şi cărturarii care se coborâseră din Ierusalim ziceau: „Este stăpânit de Beelzebul; scoate dracii cu ajutorul domnului dracilor.”",
    "Isus i-a chemat la El și le-a zis, în pilde: „Cum poate Satana să scoată afară pe Satana?",
    "Dacă o împărăție este dezbinată împotriva ei înseși, împărăția aceea nu poate dăinui.",
    "Şi dacă o casă este dezbinată împotriva ei înseși, casa aceea nu poate dăinui.",
    "Tot astfel, dacă Satana se răscoală împotriva lui însuși este dezbinat și nu poate dăinui, ci s-a isprăvit cu el.",
    "Nimeni nu poate să intre în casa unui om tare și să-i jefuiască gospodăria decât dacă a legat mai întâi pe omul acela tare; numai atunci îi va jefui casa.",
    "Adevărat vă spun că toate păcatele și toate hulele pe care le vor rosti oamenii li se vor ierta;",
    "dar oricine va huli împotriva Duhului Sfânt nu va căpăta iertare în veac: ci este vinovat de un păcat veșnic.”",
    "Aceasta pentru că ei ziceau: „Are un duh necurat.”",
    "Atunci au venit mama și frații Lui și, stând afară, au trimis să-L cheme.",
    "Mulțimea ședea în jurul Lui, când I-au spus: „Iată că mama Ta și frații Tăi sunt afară și Te caută.”",
    "El a răspuns: „Cine este mama Mea și frații Mei?”",
    "Apoi, aruncându-Şi privirile peste cei ce ședeau împrejurul Lui: „Iată”, a zis El, „mama Mea și frații Mei!",
    "Căci oricine face voia lui Dumnezeu, acela Îmi este frate, soră și mamă.”",
  ],
  [
    "",
    "Isus a început iarăși să învețe pe norod lângă mare. Fiindcă se adunase foarte mult norod la El, S-a suit și a șezut într-o corabie, pe mare; iar tot norodul stătea pe țărm lângă mare.",
    "Apoi a început să-i învețe multe lucruri în pilde; și, în învățătura pe care le-o dădea, le spunea:",
    "„Ascultați! Iată, semănătorul a ieșit să semene.",
    "Pe când semăna, o parte din sămânță a căzut lângă drum: au venit păsările și au mâncat-o.",
    "O altă parte a căzut pe un loc stâncos, unde n-avea mult pământ: a răsărit îndată, pentru că n-a dat de un pământ adânc;",
    "dar, când a răsărit soarele, s-a pălit; și, pentru că n-avea rădăcină, s-a uscat.",
    "O altă parte a căzut între spini; spinii au crescut, au înecat-o și n-a dat rod.",
    "O altă parte a căzut în pământ bun: a dat rod, care se înălța și creștea; și a adus: una treizeci, alta șaizeci, și alta o sută.”",
    "Apoi a zis: „Cine are urechi de auzit să audă.”",
    "Când a fost singur, cei ce erau în jurul Lui împreună cu cei doisprezece L-au întrebat despre pilde.",
    "„Vouă”, le-a zis El, „v-a fost dat să cunoașteți taina Împărăției lui Dumnezeu; dar pentru cei ce sunt afară din numărul vostru, toate lucrurile sunt înfățișate în pilde;",
    "pentru ca, „măcar că privesc, să privească și să nu vadă, și măcar că aud, să audă și să nu înțeleagă, ca nu cumva să se întoarcă la Dumnezeu și să li se ierte păcatele.”",
    "El le-a mai zis: „Nu înțelegeți pilda aceasta? Cum veți înțelege atunci toate celelalte pilde?",
    "Semănătorul seamănă Cuvântul.",
    "Cei înfățișați prin sămânța căzută lângă drum sunt aceia în care este semănat Cuvântul; dar după ce l-au auzit, vine Satana îndată și ia Cuvântul semănat în ei.",
    "Tot așa, cei înfățișați prin sămânța căzută în locurile stâncoase sunt aceia care, când aud Cuvântul, îl primesc îndată cu bucurie;",
    "dar n-au rădăcină în ei, ci țin până la o vreme; și cum vine un necaz sau o prigonire din pricina Cuvântului, se leapădă îndată de el.",
    "Alții sunt cei înfățișați prin sămânța căzută între spini; aceștia sunt cei ce aud Cuvântul;",
    "dar năvălesc în ei grijile lumii, înșelăciunea bogățiilor și poftele altor lucruri, care îneacă Cuvântul și-l fac astfel neroditor.",
    "Alții apoi sunt înfățișați prin sămânța căzută în pământ bun. Aceștia sunt cei ce aud Cuvântul, îl primesc și fac rod: unul treizeci, altul șaizeci și altul o sută.”",
    "El le-a mai zis: „Oare lumina este adusă ca să fie pusă sub baniță sau sub pat? Nu este adusă ca să fie pusă în sfeșnic?",
    "Căci nu este nimic ascuns care nu va fi descoperit și nimic tăinuit care nu va ieși la lumină.",
    "Dacă are cineva urechi de auzit, să audă.”",
    "El le-a mai zis: „Luați seama la ce auziți. Cu ce măsură veți măsura, vi se va măsura: și vi se va da și mai mult.",
    "Căci celui ce are i se va da; dar de la cel ce n-are se va lua și ce are.”",
    "El a mai zis: „Cu Împărăția lui Dumnezeu este ca atunci când aruncă un om sămânța în pământ;",
    "fie că doarme noaptea, fie că stă treaz ziua, sămânța încolțește și crește fără să știe el cum.",
    "Pământul rodește singur: întâi un fir verde, apoi spic, după aceea grâu deplin în spic;",
    "și când este copt rodul, pune îndată secera în el, pentru că a venit secerișul.”",
    "El a mai zis: „Cu ce vom asemăna Împărăția lui Dumnezeu sau prin ce pildă o vom înfățișa?",
    "Se aseamănă cu un grăunte de muștar care, când este semănat în pământ, este cea mai mică dintre toate semințele de pe pământ;",
    "dar, după ce a fost semănat, crește și se face mai mare decât toate zarzavaturile și face ramuri mari, așa că păsările cerului își pot face cuiburi la umbra lui.”",
    "Isus le vestea Cuvântul prin multe pilde de felul acesta, după cum erau ei în stare să-l priceapă.",
    "Nu le vorbea deloc fără pildă; dar, când era singur la o parte, lămurea ucenicilor Săi toate lucrurile.",
    "În aceeași zi, seara, Isus le-a zis: „Să trecem în partea cealaltă.”",
    "După ce au dat drumul norodului, ucenicii L-au luat în corabia în care se afla și așa cum era. Împreună cu El mai erau și alte corăbii.",
    "S-a stârnit o mare furtună de vânt care arunca valurile în corabie, așa că mai că se umplea corabia.",
    "Şi El dormea la cârmă pe căpătâi. Ucenicii L-au deșteptat și I-au zis: „Învățătorule, nu-Ţi pasă că pierim?”",
    "El S-a sculat, a certat vântul și a zis mării: „Taci! Fără gură!” Vântul a stat și s-a făcut o liniște mare.",
    "Apoi le-a zis: „Pentru ce sunteți așa de fricoși? Tot n-aveți credință?”",
    "I-a apucat o mare frică și ziceau unii către alții: „Cine este Acesta de Îl ascultă chiar și vântul și marea?”",
  ],
  [
    "",
    "Au ajuns pe celălalt țărm al mării, în ținutul gadarenilor.",
    "Când a ieșit Isus din corabie, L-a întâmpinat îndată un om care ieșea din morminte, stăpânit de un duh necurat.",
    "Omul acesta își avea locuința în morminte, și nimeni nu mai putea să-l țină legat, nici chiar cu un lanț.",
    "Căci de multe ori fusese legat cu picioarele în obezi și cu cătușe la mâini, dar rupsese cătușele și sfărâmase obezile, și nimeni nu-l putea domoli.",
    "Totdeauna, zi și noapte, stătea în morminte și pe munți, țipând și tăindu-se cu pietre.",
    "Când a văzut pe Isus de departe, a alergat, I s-a închinat",
    "și a strigat cu glas tare: „Ce am eu a face cu Tine, Isuse, Fiul Dumnezeului celui Preaînalt? Te jur în Numele lui Dumnezeu, să nu mă chinuiești!”",
    "Căci Isus îi zicea: „Duh necurat, ieși afară din omul acesta!”",
    "„Care-ți este numele?”, l-a întrebat Isus. „Numele meu este „legiune”, a răspuns el, „pentru că suntem mulți.”",
    "Şi Îl ruga stăruitor să nu-i trimită afară din ținutul acela.",
    "Acolo, lângă munte, era o turmă mare de porci care pășteau.",
    "Şi dracii L-au rugat și au zis: „Trimite-ne în porcii aceia, ca să intrăm în ei.”",
    "Isus le-a dat voie. Şi duhurile necurate au ieșit și au intrat în porci; și turma s-a repezit de pe râpă în mare: erau aproape două mii, și s-au înecat în mare.",
    "Porcarii au fugit și au dat de știre în cetate și prin satele vecine. Oamenii au ieșit să vadă ce s-a întâmplat.",
    "Au venit la Isus, și iată pe cel ce fusese îndrăcit și avusese legiunea de draci, șezând jos îmbrăcat și întreg la minte; și s-au înspăimântat.",
    "Cei ce văzuseră cele întâmplate le-au povestit tot ce se petrecuse cu cel îndrăcit și cu porcii.",
    "Atunci au început să roage pe Isus să plece din ținutul lor.",
    "Pe când Se suia El în corabie, omul care fusese îndrăcit Îl ruga să-l lase să rămână cu El.",
    "Isus nu i-a dat voie, ci i-a zis: „Du-te acasă la ai tăi și povestește-le tot ce ți-a făcut Domnul și cum a avut milă de tine.”",
    "El a plecat și a început să vestească prin Decapole tot ce-i făcuse Isus. Şi toți se minunau.",
    "După ce a trecut Isus iarăși de cealaltă parte cu corabia, s-a adunat mult norod în jurul Lui. El stătea lângă mare.",
    "Atunci a venit unul din fruntașii sinagogii, numit Iair. Cum L-a văzut, fruntașul s-a aruncat la picioarele Lui",
    "și I-a făcut următoarea rugăminte stăruitoare: „Fetița mea trage să moară; rogu-Te, vino de-Ţi pune mâinile peste ea, ca să se facă sănătoasă și să trăiască.”",
    "Isus a plecat împreună cu el. Şi după El mergea mult norod și-L îmbulzea.",
    "Şi era o femeie care de doisprezece ani avea o scurgere de sânge.",
    "Ea suferise mult de la mulți doctori; cheltuise tot ce avea, și nu simțise nicio ușurare; ba încă îi era mai rău.",
    "A auzit vorbindu-se despre Isus, a venit pe dinapoi prin mulțime și s-a atins de haina Lui.",
    "Căci își zicea ea: „Dacă aș putea doar să mă ating de haina Lui, mă voi tămădui.”",
    "Şi îndată a secat izvorul sângelui ei. Şi a simțit în tot trupul ei că s-a tămăduit de boală.",
    "Isus a cunoscut îndată că o putere ieșise din El; și, întorcându-Se spre mulțime, a zis: „Cine s-a atins de hainele Mele?”",
    "Ucenicii I-au zis: „Vezi că mulțimea Te îmbulzește și mai zici: „Cine s-a atins de Mine?”",
    "El Se uita de jur împrejur să vadă pe cea care făcuse lucrul acesta.",
    "Femeia, înfricoșată și tremurând, căci știa ce se petrecuse în ea, a venit de s-a aruncat la picioarele Lui și I-a spus tot adevărul.",
    "Dar Isus i-a zis: „Fiică, credința ta te-a mântuit; du-te în pace și fii tămăduită de boala ta.”",
    "Pe când vorbea El încă, iată că vin niște oameni de la fruntașul sinagogii care-i spun: „Fiica ta a murit; pentru ce mai superi pe Învățătorul?”",
    "Dar Isus, fără să țină seamă de cuvintele acestea, a zis fruntașului sinagogii: „Nu te teme, crede numai!”",
    "Şi n-a îngăduit nimănui să-L însoțească, afară de Petru, Iacov și Ioan, fratele lui Iacov.",
    "Au ajuns la casa fruntașului sinagogii. Acolo Isus a văzut o zarvă, și pe unii care plângeau și se tânguiau mult.",
    "A intrat înăuntru și le-a zis: „Pentru ce faceți atâta zarvă și pentru ce plângeți? Copila n-a murit, ci doarme.”",
    "Ei își băteau joc de El. Atunci, după ce i-a scos afară pe toți, a luat cu El pe tatăl copilei, pe mama ei și pe cei ce-L însoțiseră și a intrat acolo unde zăcea copila.",
    "A apucat-o de mână și i-a zis: „Talita, cumi”, care tălmăcit înseamnă: „Fetițo, scoală-te îți zic!”",
    "Îndată fetița s-a sculat și a început să umble; căci era de doisprezece ani. Ei au rămas încremeniți.",
    "Isus le-a poruncit cu tărie să nu știe nimeni lucrul acesta; și a zis să dea de mâncare fetiței.",
  ],
  [
    "",
    "Isus a plecat de acolo și S-a dus în patria Lui. Ucenicii Lui au mers după El.",
    "Când a venit ziua Sabatului, a început să învețe pe norod în sinagogă. Mulți, când Îl auzeau, se mirau și ziceau: „De unde are El aceste lucruri? Ce fel de înțelepciune este aceasta care I-a fost dată? Şi cum se fac astfel de minuni prin mâinile Lui?",
    "Nu este Acesta tâmplarul, feciorul Mariei, fratele lui Iacov, al lui Iose, al lui Iuda și al lui Simon? Şi nu sunt surorile Lui aici între noi?” Şi găseau o pricină de poticnire în El.",
    "Dar Isus le-a zis: „Un proroc nu este disprețuit decât în patria Lui, între rudele Lui și în casa Lui.”",
    "N-a putut să facă nicio minune acolo, ci doar Şi-a pus mâinile peste câțiva bolnavi și i-a vindecat.",
    "Şi Se mira de necredința lor. Isus străbătea satele dimprejur și învăța pe norod.",
    "Atunci a chemat la Sine pe cei doisprezece și a început să-i trimită doi câte doi, dându-le putere asupra duhurilor necurate.",
    "Le-a poruncit să nu ia nimic cu ei pe drum decât un toiag; să n-aibă nici pâine, nici traistă, nici bani de aramă la brâu;",
    "să se încalțe cu sandale și să nu se îmbrace cu două haine.",
    "Apoi le-a zis: „În orice casă veți intra să rămâneți acolo până veți pleca din locul acela.",
    "Şi, dacă în vreun loc nu vă vor primi și nu vă vor asculta, să plecați de acolo și să scuturați îndată praful de sub picioarele voastre, ca mărturie pentru ei. Adevărat vă spun că, în ziua judecății, va fi mai ușor pentru pământul Sodomei și Gomorei decât pentru cetatea aceea.”",
    "Ucenicii au plecat și au propovăduit pocăința.",
    "Scoteau mulți draci și ungeau cu untdelemn pe mulți bolnavi și-i vindecau.",
    "Împăratul Irod a auzit vorbindu-se despre Isus, al cărui Nume ajunsese vestit; și a zis: „Ioan Botezătorul a înviat din morți, și de aceea lucrează aceste puteri prin El.”",
    "Alții ziceau: „Este Ilie.” Iar alții ziceau: „Este un proroc ca unul din proroci.”",
    "Dar Irod, când a auzit lucrul acesta, zicea: „Ioan acela, căruia i-am tăiat capul, a înviat din morți.”",
    "Căci Irod însuși trimisese să prindă pe Ioan și-l legase în temniță, din pricina Irodiadei, nevasta fratelui său Filip, pentru că o luase de nevastă.",
    "Şi Ioan zicea lui Irod: „Nu-ți este îngăduit să ții pe nevasta fratelui tău!”",
    "Irodiada avea necaz pe Ioan și voia să-l omoare. Dar nu putea,",
    "căci Irod se temea de Ioan, fiindcă îl știa om neprihănit și sfânt; îl ocrotea și, când îl auzea, de multe ori stătea în cumpănă, neștiind ce să facă; și-l asculta cu plăcere.",
    "Totuși a venit o zi cu bun prilej, când Irod își prăznuia ziua nașterii și a dat un ospăț boierilor săi, mai marilor oștii și fruntașilor Galileii.",
    "Fata Irodiadei a intrat la ospăț, a jucat și a plăcut lui Irod și oaspeților lui. Împăratul a zis fetei: „Cere-mi orice vrei, și-ți voi da.”",
    "Apoi a adăugat cu jurământ: „Orice-mi vei cere, îți voi da, fie și jumătate din împărăția mea.”",
    "Fata a ieșit afară și a zis mamei sale: „Ce să cer?” Şi mama sa i-a răspuns: „Capul lui Ioan Botezătorul.”",
    "Ea s-a grăbit să vină îndată la împărat și i-a făcut următoarea cerere: „Vreau să-mi dai îndată, într-o farfurie, capul lui Ioan Botezătorul.”",
    "Împăratul s-a întristat foarte mult; dar, din pricina jurămintelor sale și din pricina oaspeților, n-a vrut să zică nu.",
    "A trimis îndată un ostaș de pază, cu porunca de a aduce capul lui Ioan Botezătorul. Ostașul de pază s-a dus și a tăiat capul lui Ioan în temniță,",
    "l-a adus pe o farfurie, l-a dat fetei, și fata l-a dat mamei sale.",
    "Ucenicii lui Ioan, când au auzit acest lucru, au venit de i-au ridicat trupul și l-au pus într-un mormânt.",
    "Apostolii s-au adunat la Isus și I-au spus tot ce făcuseră și tot ce învățaseră pe oameni.",
    "Isus le-a zis: „Veniți singuri la o parte, într-un loc pustiu, și odihniți-vă puțin.” Căci erau mulți care veneau și se duceau, și ei n-aveau vreme nici să mănânce.",
    "Au plecat, dar, cu corabia, ca să se ducă într-un loc pustiu, la o parte.",
    "Oamenii i-au văzut plecând și i-au cunoscut; au alergat pe jos din toate cetățile și au venit înaintea lor în locul în care se duceau ei.",
    "Când a ieșit din corabie, Isus a văzut mult norod; și I s-a făcut milă de ei, pentru că erau ca niște oi care n-aveau păstor; și a început să-i învețe multe lucruri.",
    "Fiindcă ziua era pe sfârșite, ucenicii s-au apropiat de El și I-au zis: „Locul acesta este pustiu, și ziua este pe sfârșite.",
    "Dă-le drumul să se ducă în cătunele și satele dimprejur ca să-și cumpere pâine, fiindcă n-au ce mânca.”",
    "„Dați-le voi să mănânce”, le-a răspuns Isus. Dar ei I-au zis: „Oare să ne ducem să cumpărăm pâini de două sute de lei și să le dăm să mănânce?”",
    "Şi El i-a întrebat: „Câte pâini aveți? Duceți-vă de vedeți.” S-au dus de au văzut câte pâini au și au răspuns: „Cinci și doi pești.”",
    "Atunci le-a poruncit să-i așeze pe toți, cete-cete, pe iarba verde.",
    "Şi au șezut jos în cete de câte o sută și de câte cincizeci.",
    "El a luat cele cinci pâini și cei doi pești. Şi-a ridicat ochii spre cer și a rostit binecuvântarea. Apoi a frânt pâinile și le-a dat ucenicilor, ca ei să le împartă norodului. Asemenea și cei doi pești i-a împărțit la toți.",
    "Au mâncat toți și s-au săturat;",
    "și au ridicat douăsprezece coșuri pline cu firimituri de pâine și cu ce mai rămăsese din pești.",
    "Cei ce mâncaseră pâinile erau cinci mii de bărbați.",
    "Îndată, Isus a silit pe ucenicii Săi să intre în corabie și să treacă înaintea Lui de cealaltă parte, spre Betsaida. În timpul acesta, El avea să dea drumul norodului.",
    "După ce Şi-a luat rămas bun de la norod, S-a dus pe munte ca să Se roage.",
    "Când s-a înserat, corabia era în mijlocul mării, iar Isus era singur pe țărm.",
    "A văzut pe ucenici că se necăjesc cu vâslirea, căci vântul le era împotrivă. Şi, într-a patra strajă din noapte, a mers la ei, umblând pe mare, și voia să treacă pe lângă ei.",
    "Când L-au văzut ei umblând pe mare, li s-a părut că este o nălucă, și au țipat;",
    "pentru că toți L-au văzut și s-au înspăimântat. Isus a vorbit îndată cu ei și le-a zis: „Îndrăzniți, Eu sunt, nu vă temeți!”",
    "Apoi S-a suit la ei în corabie, și a stat vântul. Ei au rămas uimiți și înmărmuriți,",
    "căci nu înțeleseseră minunea cu pâinile, fiindcă le era inima împietrită.",
    "După ce au trecut marea, au venit în ținutul Ghenezaretului și au tras la mal.",
    "Când au ieșit din corabie, oamenii au cunoscut îndată pe Isus,",
    "au alergat prin toate împrejurimile și au început să aducă pe bolnavi în paturi, pretutindeni pe unde se auzea că era El.",
    "Oriunde intra El, în sate, în cetăți sau în cătune, puneau pe bolnavi pe piețe și-L rugau să le dea voie doar să se atingă de poalele hainei Lui. Şi toți câți se atingeau de El erau tămăduiți.",
  ],
  [
    "",
    "Fariseii și câțiva cărturari, veniți din Ierusalim, s-au adunat la Isus.",
    "Ei au văzut pe unii din ucenicii Lui prânzind cu mâinile necurate, adică nespălate. –",
    "Fariseii însă și toți iudeii nu mănâncă fără să-și spele cu mare băgare de seamă mâinile, după datina bătrânilor.",
    "Şi când se întorc din piață, nu mănâncă decât după ce s-au scăldat. Sunt multe alte obiceiuri pe care au apucat ei să le țină, precum: spălarea paharelor, a ulcioarelor, a căldărilor și a paturilor. –",
    "Şi fariseii și cărturarii L-au întrebat: „Pentru ce nu se țin ucenicii Tăi de datina bătrânilor, ci prânzesc cu mâinile nespălate?”",
    "Isus le-a răspuns: „Fățarnicilor, bine a prorocit Isaia despre voi, după cum este scris: „Norodul acesta Mă cinstește cu buzele, dar inima lui este departe de Mine.",
    "Degeaba Mă cinstesc ei, dând învățături care nu sunt decât niște porunci omenești.”",
    "Voi lăsați porunca lui Dumnezeu și țineți datina așezată de oameni, precum: spălarea ulcioarelor și a paharelor, și faceți multe alte lucruri de acestea.”",
    "El le-a mai zis: „Ați desființat frumos porunca lui Dumnezeu, ca să țineți datina voastră.",
    "Căci Moise a zis: „Să cinstești pe tatăl tău și pe mama ta”; și: „Cine va grăi de rău pe tatăl său sau pe mama sa să fie pedepsit cu moartea.”",
    "Voi, dimpotrivă, ziceți: „Dacă un om va spune tatălui său sau mamei sale: „Ori cu ce te-aș putea ajuta este „Corban”, adică dat lui Dumnezeu, face bine”;",
    "și nu-l mai lăsați să facă nimic pentru tatăl sau pentru mama sa.",
    "Şi așa, ați desființat Cuvântul lui Dumnezeu, prin datina voastră. Şi faceți multe alte lucruri de felul acesta!”",
    "În urmă, a chemat din nou noroadele la Sine și le-a zis: „Ascultați-Mă toți și înțelegeți.",
    "Afară din om nu este nimic care, intrând în el, să-l poată spurca; dar ce iese din om aceea-l spurcă.",
    "Dacă are cineva urechi de auzit, să audă.”",
    "După ce a intrat în casă, pe când era departe de norod, ucenicii Lui L-au întrebat despre pilda aceasta.",
    "El le-a zis: „Şi voi sunteți așa de nepricepuți? Nu înțelegeți că nimic din ce intră în om de afară nu-l poate spurca?",
    "Fiindcă nu intră în inima lui, ci în pântece, și apoi este dat afară în hazna.” A zis astfel, făcând toate bucatele curate.",
    "El le-a mai zis: „Ce iese din om aceea spurcă pe om.",
    "Căci dinăuntru, din inima oamenilor, ies gândurile rele, preacurviile, curviile, uciderile,",
    "furtișagurile, lăcomiile, vicleșugurile, înșelăciunile, faptele de rușine, ochiul rău, hula, trufia, nebunia.",
    "Toate aceste lucruri rele ies dinăuntru și spurcă pe om.”",
    "Isus a plecat de acolo și S-a dus în ținutul Tirului și al Sidonului. A intrat într-o casă, dorind să nu știe nimeni că este acolo; dar n-a putut să rămână ascuns.",
    "Căci îndată, o femeie, a cărei fetiță era stăpânită de un duh necurat, a auzit vorbindu-se despre El și a venit de s-a aruncat la picioarele Lui.",
    "Femeia aceasta era o grecoaică, de obârșie siro-feniciană. Ea Îl ruga să scoată pe dracul din fiica ei.",
    "Isus i-a zis: „Lasă să se sature mai întâi copiii; căci nu este bine să iei pâinea copiilor și s-o arunci la căței.”",
    "„Da, Doamne”, I-a răspuns ea, „dar și cățeii de sub masă mănâncă din firimiturile copiilor.”",
    "Atunci Isus i-a zis: „Pentru vorba aceasta, du-te; a ieșit dracul din fiica ta.”",
    "Şi când a intrat femeia în casa ei, a găsit pe copilă culcată în pat; și ieșise dracul din ea.",
    "Isus a părăsit ținutul Tirului și a venit iarăși prin Sidon la Marea Galileii, trecând prin ținutul Decapole.",
    "I-au adus un surd care vorbea cu anevoie și L-au rugat să-Şi pună mâinile peste el.",
    "El l-a luat la o parte din norod, i-a pus degetele în urechi și i-a atins limba cu scuipatul Lui.",
    "Apoi, Şi-a ridicat ochii spre cer, a suspinat și a zis: „Efata”, adică: „Deschide-te!”",
    "Îndată i s-au deschis urechile, i s-a dezlegat limba și a vorbit foarte deslușit.",
    "Isus le-a poruncit să nu spună nimănui; dar cu cât le poruncea mai mult, cu atât Îl vesteau mai mult.",
    "Ei erau uimiți peste măsură de mult și ziceau: „Toate le face de minune; chiar și pe surzi îi face să audă, și pe muți să vorbească.”",
  ],
  [
    "",
    "În zilele acelea, fiindcă se strânsese din nou mult norod și n-avea ce mânca, Isus a chemat pe ucenicii Săi și le-a zis:",
    "„Mi-e milă de norodul acesta; căci iată că de trei zile stau lângă Mine și n-au ce mânca.",
    "Dacă le voi da drumul acasă flămânzi, au să leșine de foame pe drum, fiindcă unii din ei au venit de departe.”",
    "Ucenicii I-au răspuns: „Cum ar putea cineva să sature cu pâine pe oamenii aceștia, aici într-un loc pustiu?”",
    "„Câte pâini aveți?”, i-a întrebat Isus. „Şapte”, I-au răspuns ei.",
    "Atunci a poruncit norodului să șadă pe pământ; a luat cele șapte pâini; și, după ce a mulțumit lui Dumnezeu, le-a frânt și le-a dat ucenicilor Săi ca să le împartă; și ei le-au împărțit norodului.",
    "Mai aveau și câțiva peștișori: și Isus, după ce i-a binecuvântat, a poruncit să-i împartă și pe aceia.",
    "Au mâncat și s-au săturat; și au ridicat șapte coșnițe pline cu rămășițele de firimituri.",
    "Erau aproape patru mii de inși. În urmă, Isus le-a dat drumul.",
    "Isus a intrat îndată în corabie cu ucenicii Săi și a venit în părțile Dalmanutei.",
    "Fariseii au venit deodată și au început o ceartă de vorbe cu Isus; și, ca să-L pună la încercare, I-au cerut un semn din cer.",
    "Isus a suspinat adânc în duhul Său și a zis: „Pentru ce cere neamul acesta un semn? Adevărat vă spun că neamului acestuia nu i se va da deloc un semn.”",
    "Apoi i-a lăsat și a intrat iarăși în corabie, ca să treacă de cealaltă parte.",
    "Ucenicii uitaseră să ia pâini; cu ei în corabie n-aveau decât o pâine.",
    "Isus le dădea în grijă și le zicea: „Luați seama, să vă păziți bine de aluatul fariseilor și de aluatul lui Irod!”",
    "Ucenicii se gândeau și ziceau între ei: „Fiindcă n-avem pâini.”",
    "Isus a înțeles lucrul acesta și le-a zis: „Pentru ce vă gândiți că n-aveți pâini? Tot nu pricepeți și tot nu înțelegeți? Aveți inima împietrită?",
    "Aveți ochi, și nu vedeți? Aveți urechi, și nu auziți? Şi nu vă aduceți aminte deloc?",
    "Când am frânt cele cinci pâini la cei cinci mii de bărbați, câte coșuri pline cu firimituri ați ridicat?” „Douăsprezece”, I-au răspuns ei.",
    "„Şi, când am frânt cele șapte pâini la cei patru mii de bărbați, câte coșnițe pline cu firimituri ați ridicat?” „Şapte”, I-au răspuns ei.",
    "Şi El le-a zis: „Tot nu înțelegeți?”",
    "Au venit la Betsaida; au adus la Isus un orb și L-au rugat să Se atingă de el.",
    "Isus a luat pe orb de mână și l-a scos afară din sat; apoi i-a pus scuipat pe ochi, Şi-a pus mâinile peste el și l-a întrebat: „Vezi ceva?”",
    "El s-a uitat și a zis: „Văd niște oameni umblând, dar mi se par ca niște copaci.”",
    "Isus i-a pus din nou mâinile pe ochi; i-a spus să se uite țintă; și, când s-a uitat, a fost tămăduit și a văzut toate lucrurile deslușit.",
    "Atunci Isus l-a trimis acasă și i-a zis: „Să nu intri în sat și nici să nu spui cuiva în sat.”",
    "Isus a plecat cu ucenicii Săi în satele Cezareii lui Filip. Pe drum le-a pus următoarea întrebare: „Cine zic oamenii că sunt Eu?”",
    "Ei I-au răspuns: „Ioan Botezătorul; alții: Ilie; alții: unul din proroci.”",
    "„Dar voi”, i-a întrebat El, „cine ziceți că sunt Eu?” „Tu ești Hristosul!”, I-a răspuns Petru.",
    "Isus le-a poruncit cu tărie să nu spună nimănui lucrul acesta despre El.",
    "Atunci a început să-i învețe că Fiul omului trebuie să pătimească mult, să fie tăgăduit de bătrâni, de preoții cei mai de seamă și de cărturari, să fie omorât, și după trei zile să învie.",
    "Le spunea lucrurile acestea pe față. Petru însă L-a luat deoparte și a început să-L mustre.",
    "Dar Isus S-a întors și S-a uitat la ucenicii Săi, a mustrat pe Petru și i-a zis: „Înapoia Mea, Satano! Fiindcă tu nu te gândești la lucrurile lui Dumnezeu, ci la lucrurile oamenilor.”",
    "Apoi a chemat la El norodul împreună cu ucenicii Săi și le-a zis: „Dacă voiește cineva să vină după Mine, să se lepede de sine însuși, să-și ia crucea și să Mă urmeze.",
    "Căci oricine va vrea să-și scape viața, o va pierde; dar oricine își va pierde viața din pricina Mea și din pricina Evangheliei, o va mântui.",
    "Şi ce folosește unui om să câștige toată lumea, dacă își pierde sufletul?",
    "Sau ce va da un om în schimb pentru sufletul său?",
    "Pentru că de oricine se va rușina de Mine și de cuvintele Mele, în acest neam preacurvar și păcătos, Se va rușina și Fiul omului, când va veni în slava Tatălui Său împreună cu sfinții îngeri.”",
  ],
  [
    "",
    "El le-a mai zis: „Adevărat vă spun că sunt unii din cei ce stau aici care nu vor muri până nu vor vedea Împărăția lui Dumnezeu venind cu putere.”",
    "După șase zile, Isus a luat cu El pe Petru, pe Iacov și pe Ioan și i-a dus singuri deoparte pe un munte înalt. Acolo S-a schimbat la față înaintea lor.",
    "Hainele Lui s-au făcut strălucitoare și foarte albe, de o albeață pe care niciun înălbitor de pe pământ n-o poate da.",
    "Ilie li s-a arătat împreună cu Moise și stătea de vorbă cu Isus.",
    "Petru a luat cuvântul și a zis lui Isus: „Învățătorule, este bine să stăm aici; să facem trei colibe: una pentru Tine, una pentru Moise, și una pentru Ilie.”",
    "Căci nu știa ce să zică, atât de mare spaimă îi apucase.",
    "A venit un nor și i-a acoperit cu umbra lui; și din nor s-a auzit un glas care zicea: „Acesta este Fiul Meu preaiubit: de El să ascultați!”",
    "Îndată ucenicii s-au uitat împrejur, și n-au mai văzut pe nimeni decât pe Isus singur cu ei.",
    "Pe când se coborau de pe munte, Isus le-a poruncit să nu spună nimănui ce au văzut, până va învia Fiul omului dintre cei morți.",
    "Ei au păstrat în ei lucrul acesta și se întrebau între ei ce să însemne învierea aceea dintre cei morți.",
    "Ucenicii I-au pus următoarea întrebare: „Pentru ce zic cărturarii că trebuie să vină întâi Ilie?”",
    "El le-a răspuns: „Ilie va veni întâi; și va așeza din nou toate lucrurile; tot așa după cum este scris despre Fiul omului că trebuie să pătimească mult și să fie defăimat.",
    "Dar Eu vă spun că Ilie a și venit, și ei i-au făcut ce au vrut, după cum este scris despre el.”",
    "Când au ajuns la ucenici, au văzut mult norod împrejurul lor, și pe cărturari întrebându-se cu ei.",
    "De îndată ce a văzut norodul pe Isus, s-a mirat și a alergat la El să I se închine.",
    "El i-a întrebat: „Despre ce vă întrebați cu ei?”",
    "Şi un om din norod I-a răspuns: „Învățătorule, am adus la Tine pe fiul meu care este stăpânit de un duh mut.",
    "Oriunde îl apucă, îl trântește la pământ. Copilul face spumă la gură, scrâșnește din dinți și rămâne țeapăn. M-am rugat de ucenicii Tăi să scoată duhul, și n-au putut.”",
    "„O, neam necredincios!”, le-a zis Isus. „Până când voi fi cu voi? Până când vă voi suferi? Aduceți-l la Mine.”",
    "L-au adus la El. Şi, cum a văzut copilul pe Isus, duhul l-a scuturat cu putere; copilul a căzut la pământ și se zvârcolea făcând spumă la gură.",
    "Isus a întrebat pe tatăl lui: „Câtă vreme este de când îi vine așa?” „Din copilărie”, a răspuns el.",
    "„Şi de multe ori duhul l-a aruncat când în foc, când în apă, ca să-l omoare. Dar dacă poți face ceva, fie-Ţi milă de noi și ajută-ne.”",
    "Isus a răspuns: „Tu zici: „Dacă poți!”… Toate lucrurile sunt cu putință celui ce crede!”",
    "Îndată tatăl copilului a strigat cu lacrimi: „Cred, Doamne! Ajută necredinței mele!”",
    "Când a văzut Isus că norodul vine în fuga mare spre El, a mustrat duhul necurat și i-a zis: „Duh mut și surd, îți poruncesc să ieși afară din copilul acesta și să nu mai intri în el.”",
    "Şi duhul a ieșit, țipând și scuturându-l cu mare putere. Copilul a rămas ca mort, așa că mulți ziceau: „A murit!”",
    "Dar Isus l-a apucat de mână și l-a ridicat. Şi el s-a sculat în picioare.",
    "Când a intrat Isus în casă, ucenicii Lui L-au întrebat deoparte: „Noi de ce n-am putut să scoatem duhul acesta?”",
    "„Acest soi de draci”, le-a zis El, „nu poate ieși decât prin rugăciune și post.”",
    "Au plecat de acolo și au trecut prin Galileea. Isus nu voia să știe nimeni că trece.",
    "Căci învăța pe ucenicii Săi și zicea: „Fiul omului va fi dat în mâinile oamenilor; ei Îl vor omorî, și a treia zi după ce-L vor omorî, va învia.”",
    "Dar ucenicii nu înțelegeau cuvintele acestea și se temeau să-L întrebe.",
    "Apoi au venit la Capernaum. Când era în casă, Isus i-a întrebat: „Despre ce vorbeați unul cu altul pe drum?”",
    "Dar ei tăceau, pentru că pe drum se certaseră între ei, ca să știe cine este cel mai mare.",
    "Atunci Isus a șezut jos, a chemat pe cei doisprezece și le-a zis: „Dacă vrea cineva să fie cel dintâi, trebuie să fie cel mai de pe urmă din toți și slujitorul tuturor!”",
    "Şi a luat un copilaș și l-a așezat în mijlocul lor; apoi l-a luat în brațe și le-a zis:",
    "„Oricine primește pe unul din acești copilași, în Numele Meu, Mă primește pe Mine; și oricine Mă primește pe Mine, nu Mă primește pe Mine, ci pe Cel ce M-a trimis pe Mine.”",
    "Ioan I-a zis: „Învățătorule, noi am văzut pe un om scoțând draci în Numele Tău; și l-am oprit, pentru că nu venea după noi.”",
    "„Nu-l opriți”, a răspuns Isus, „căci nu este nimeni care să facă minuni în Numele Meu, și să Mă poată grăi de rău îndată după aceea.",
    "Cine nu este împotriva noastră este pentru noi.",
    "Şi oricine vă va da de băut un pahar cu apă, în Numele Meu, pentru că sunteți ucenici ai lui Hristos, adevărat vă spun că nu-și va pierde răsplata.",
    "Dar, dacă va face cineva să păcătuiască pe unul din acești micuți care cred în Mine, ar fi mai bine pentru el să i se lege de gât o piatră mare de moară și să fie aruncat în mare.",
    "Dacă mâna ta te face să cazi în păcat, taie-o; este mai bine pentru tine să intri ciung în viață, decât să ai două mâini, și să mergi în gheenă, în focul care nu se stinge,",
    "unde viermele lor nu moare, și focul nu se stinge.",
    "Dacă piciorul tău te face să cazi în păcat, taie-l; este mai bine pentru tine să intri în viață șchiop, decât să ai două picioare, și să fii aruncat în gheenă, în focul care nu se stinge,",
    "unde viermele lor nu moare, și focul nu se stinge.",
    "Şi dacă ochiul tău te face să cazi în păcat, scoate-l; este mai bine pentru tine să intri în Împărăția lui Dumnezeu numai cu un ochi, decât să ai doi ochi, și să fii aruncat în focul gheenei,",
    "unde viermele lor nu moare, și focul nu se stinge.",
    "Pentru că fiecare om va fi sărat cu foc, și orice jertfă va fi sărată cu sare.",
    "Sarea este bună; dar dacă sarea își pierde puterea de a săra, cu ce îi veți da înapoi puterea aceasta? Să aveți sare în voi înșivă și să trăiți în pace unii cu alții.”",
  ],
  [
    "",
    "Isus a plecat de acolo și a venit în ținutul Iudeii, dincolo de Iordan. Gloatele s-au adunat din nou la El; și, după obiceiul Său, a început iarăși să-i învețe.",
    "Au venit la El fariseii; și, ca să-L ispitească, L-au întrebat dacă este îngăduit unui bărbat să-și lase nevasta.",
    "Drept răspuns, El le-a zis: „Ce v-a poruncit Moise?”",
    "„Moise”, au zis ei, „a dat voie ca bărbatul să scrie o carte de despărțire și s-o lase.”",
    "Isus le-a zis: „Din pricina împietririi inimii voastre v-a scris Moise porunca aceasta.",
    "Dar de la începutul lumii „Dumnezeu i-a făcut parte bărbătească și parte femeiască.",
    "De aceea va lăsa omul pe tatăl său și pe mama sa și se va lipi de nevasta sa.",
    "Şi cei doi vor fi un singur trup.” Așa că nu mai sunt doi, ci sunt un singur trup.",
    "Deci, ce a împreunat Dumnezeu, omul să nu despartă.”",
    "În casă, ucenicii L-au întrebat iarăși asupra celor de mai sus.",
    "El le-a zis: „Oricine își lasă nevasta și ia pe alta de nevastă preacurvește față de ea;",
    "și dacă o nevastă își lasă bărbatul și ia pe altul de bărbat preacurvește.”",
    "I-au adus niște copilași ca să Se atingă de ei. Dar ucenicii au certat pe cei ce îi aduceau.",
    "Când a văzut Isus acest lucru, S-a mâniat și le-a zis: „Lăsați copilașii să vină la Mine și nu-i opriți; căci Împărăția lui Dumnezeu este a celor ca ei.",
    "Adevărat vă spun că oricine nu va primi Împărăția lui Dumnezeu ca un copilaș, cu niciun chip nu va intra în ea!”",
    "Apoi i-a luat în brațe și i-a binecuvântat, punându-Şi mâinile peste ei.",
    "Tocmai când era gata să pornească la drum, a alergat la El un om, care a îngenuncheat înaintea Lui și L-a întrebat: „Bunule Învățător, ce să fac ca să moștenesc viața veșnică?”",
    "„Pentru ce Mă numești bun?”, i-a zis Isus. „Nimeni nu este bun decât Unul singur: Dumnezeu.",
    "Cunoști poruncile: „Să nu preacurvești; să nu ucizi; să nu furi; să nu faci o mărturisire mincinoasă; să nu înșeli; să cinstești pe tatăl tău și pe mama ta.”",
    "El I-a răspuns: „Învățătorule, toate aceste lucruri le-am păzit cu grijă din tinerețea mea.”",
    "Isus S-a uitat țintă la el, l-a iubit și i-a zis: „Îți lipsește un lucru; du-te de vinde tot ce ai, dă la săraci, și vei avea o comoară în cer. Apoi vino, ia-ți crucea și urmează-Mă.”",
    "Mâhnit de aceste cuvinte, omul acesta a plecat întristat de tot; căci avea multe avuții.",
    "Isus S-a uitat împrejurul Lui și a zis ucenicilor Săi: „Cât de anevoie vor intra în Împărăția lui Dumnezeu cei ce au avuții!”",
    "Ucenicii au rămas uimiți de cuvintele Lui. Isus a luat din nou cuvântul și le-a zis: „Fiilor, cât de anevoie este pentru cei ce se încred în bogății să intre în Împărăția lui Dumnezeu!",
    "Mai lesne este să treacă o cămilă prin urechea unui ac, decât să intre un om bogat în Împărăția lui Dumnezeu!”",
    "Ucenicii au rămas și mai uimiți și au zis unii către alții: „Cine poate atunci să fie mântuit?”",
    "Isus S-a uitat țintă la ei și le-a zis: „Lucrul acesta este cu neputință la oameni, dar nu la Dumnezeu; pentru că toate lucrurile sunt cu putință la Dumnezeu.”",
    "Petru a început să-I zică: „Iată că noi am lăsat totul și Te-am urmat.”",
    "Isus a răspuns: „Adevărat vă spun că nu este nimeni care să fi lăsat casă, sau frați, sau surori, sau tată, sau mamă, sau nevastă, sau copii, sau holde pentru Mine și pentru Evanghelie",
    "și să nu primească acum, în veacul acesta, de o sută de ori mai mult: case, frați, surori, mame, copii și holde, împreună cu prigoniri; iar în veacul viitor, viața veșnică.",
    "Mulți din cei dintâi vor fi cei de pe urmă, și mulți din cei de pe urmă vor fi cei dintâi.”",
    "Ei erau pe drum și se suiau la Ierusalim; și Isus mergea înaintea lor. Ucenicii erau tulburați și mergeau îngroziți după El. Isus a luat iarăși la El pe cei doisprezece și a început să le vorbească despre lucrurile care aveau să I se întâmple.",
    "„Iată”, a zis El, „ne suim la Ierusalim și Fiul omului va fi dat în mâinile preoților celor mai de seamă și cărturarilor. Ei Îl vor osândi la moarte și-L vor da în mâinile Neamurilor,",
    "care își vor bate joc de El, Îl vor bate cu nuiele, Îl vor scuipa și-L vor omorî; dar, după trei zile, va învia.”",
    "Fiii lui Zebedei, Iacov și Ioan, au venit la Isus și I-au zis: „Învățătorule, am vrea să ne faci ce-Ţi vom cere.”",
    "El le-a zis: „Ce voiți să vă fac?”",
    "„Dă-ne”, I-au zis ei, „să ședem unul la dreapta Ta, și altul la stânga Ta, când vei fi îmbrăcat în slava Ta.”",
    "Isus le-a răspuns: „Nu știți ce cereți. Puteți voi să beți paharul pe care am să-l beau Eu sau să fiți botezați cu botezul cu care am să fiu botezat Eu?”",
    "„Putem”, au zis ei. Şi Isus le-a răspuns: „Este adevărat că paharul pe care-l voi bea Eu îl veți bea, și cu botezul cu care voi fi botezat Eu veți fi botezați;",
    "dar cinstea de a ședea la dreapta sau la stânga Mea nu atârnă de Mine s-o dau, ci ea este numai pentru aceia pentru care a fost pregătită.”",
    "Cei zece, când au auzit lucrul acesta, au început să se mânie pe Iacov și pe Ioan.",
    "Isus i-a chemat la El și le-a zis: „Ştiți că cei priviți drept cârmuitori ai Neamurilor, domnesc peste ele, și mai marii lor le poruncesc cu stăpânire.",
    "Dar între voi să nu fie așa. Ci oricare va vrea să fie mare între voi să fie slujitorul vostru;",
    "și oricare va vrea să fie cel dintâi între voi să fie robul tuturor.",
    "Căci Fiul omului n-a venit să I se slujească, ci El să slujească și să-Şi dea viața răscumpărare pentru mulți!”",
    "Au ajuns la Ierihon. Şi pe când ieșea Isus din Ierihon cu ucenicii Săi și cu o mare mulțime de oameni, fiul lui Timeu, Bartimeu, un cerșetor orb, ședea jos lângă drum și cerea de milă.",
    "El a auzit că trece Isus din Nazaret și a început să strige: „Isuse, Fiul lui David, ai milă de mine!”",
    "Mulți îl certau să tacă; dar el și mai tare striga: „Fiul lui David, ai milă de mine!”",
    "Isus S-a oprit și a zis: „Chemați-l!” Au chemat pe orb și i-au zis: „Îndrăznește, scoală-te, căci te cheamă.”",
    "Orbul și-a aruncat haina; a sărit și a venit la Isus.",
    "Isus a luat cuvântul și i-a zis: „Ce vrei să-ți fac?” „Rabuni”, I-a răspuns orbul, „să capăt vederea.”",
    "Şi Isus i-a zis: „Du-te, credința ta te-a mântuit.” Îndată orbul și-a căpătat vederea și a mers pe drum după Isus.",
  ],
  [
    "",
    "Când s-au apropiat de Ierusalim și au fost lângă Betfaghe și Betania, înspre Muntele Măslinilor, Isus a trimis pe doi din ucenicii Săi",
    "și le-a zis: „Duceți-vă în satul dinaintea voastră: îndată ce veți intra în el, veți găsi un măgăruș legat, pe care n-a încălecat încă niciun om; dezlegați-l și aduceți-Mi-l.",
    "Dacă vă va întreba cineva: „Pentru ce faceți lucrul acesta?”, să răspundeți: „Domnul are trebuință de el.” Şi îndată îl va trimite înapoi aici.”",
    "Ucenicii s-au dus, au găsit măgărușul legat afară lângă o ușă, la cotitura drumului, și l-au dezlegat.",
    "Unii din cei ce stăteau acolo le-au zis: „Ce faceți? De ce dezlegați măgărușul acesta?”",
    "Ei au răspuns cum le poruncise Isus. Şi i-au lăsat să plece.",
    "Au adus măgărușul la Isus, și-au aruncat hainele pe el, și Isus a încălecat pe el.",
    "Mulți oameni își așterneau hainele pe drum, iar alții presărau ramuri pe care le tăiaseră de pe câmp.",
    "Cei ce mergeau înainte și cei ce veneau după Isus strigau: „Osana! Binecuvântat este Cel ce vine în Numele Domnului!",
    "Binecuvântată este Împărăția care vine, Împărăția părintelui nostru David! Osana în cerurile preaînalte!”",
    "Isus a intrat în Ierusalim și S-a dus în Templu. După ce S-a uitat la toate lucrurile de jur împrejur, fiindcă era pe înserate, a plecat la Betania cu cei doisprezece.",
    "A doua zi, după ce au ieșit din Betania, Isus a flămânzit.",
    "A zărit de departe un smochin care avea frunze și a venit să vadă poate va găsi ceva în el. S-a apropiat de smochin, dar n-a găsit decât frunze, căci nu era încă vremea smochinelor.",
    "Atunci a luat cuvântul și a zis smochinului: „În veac să nu mai mănânce nimeni rod din tine!” Şi ucenicii au auzit aceste vorbe.",
    "Au ajuns în Ierusalim; și Isus a intrat în Templu. A început să scoată afară pe cei ce vindeau și cumpărau în Templu; a răsturnat mesele schimbătorilor de bani și scaunele celor ce vindeau porumbei.",
    "Şi nu lăsa pe nimeni să poarte vreun vas prin Templu.",
    "Şi-i învăța și zicea: „Oare nu este scris: „Casa Mea se va chema o casă de rugăciune pentru toate neamurile”? Dar voi ați făcut din ea o peșteră de tâlhari.”",
    "Preoții cei mai de seamă și cărturarii, când au auzit cuvintele acestea, căutau cum să-L omoare; căci se temeau de El, pentru că tot norodul era uimit de învățătura Lui.",
    "Ori de câte ori se însera, Isus ieșea afară din cetate.",
    "Dimineața, când treceau pe lângă smochin, ucenicii l-au văzut uscat din rădăcini.",
    "Petru și-a adus aminte de cele petrecute și a zis lui Isus: „Învățătorule, uite că smochinul pe care l-ai blestemat s-a uscat.”",
    "Isus a luat cuvântul și le-a zis: „Aveți credință în Dumnezeu!",
    "Adevărat vă spun că, dacă va zice cineva muntelui acestuia: „Ridică-te și aruncă-te în mare”, și dacă nu se va îndoi în inima lui, ci va crede că ce zice se va face, va avea lucrul cerut.",
    "De aceea vă spun că orice lucru veți cere, când vă rugați, să credeți că l-ați și primit, și-l veți avea.",
    "Şi, când stați în picioare de vă rugați, să iertați orice aveți împotriva cuiva, pentru ca și Tatăl vostru care este în ceruri să vă ierte greșelile voastre.",
    "Dar, dacă nu iertați, nici Tatăl vostru care este în ceruri nu vă va ierta greșelile voastre.”",
    "S-au dus din nou în Ierusalim. Şi, pe când Se plimba Isus prin Templu, au venit la El preoții cei mai de seamă, cărturarii și bătrânii",
    "și I-au zis: „Cu ce putere faci Tu aceste lucruri? Şi cine Ţi-a dat puterea aceasta ca să le faci?”",
    "Isus le-a răspuns: „Am să vă pun și Eu o întrebare; răspundeți-Mi la ea, și apoi vă voi spune și Eu cu ce putere fac aceste lucruri.",
    "Botezul lui Ioan venea din cer ori de la oameni? Răspundeți-Mi!”",
    "Ei însă vorbeau astfel între ei: „Dacă răspundem: „Din cer”, va zice: „Dar de ce nu l-ați crezut?”",
    "Şi dacă vom răspunde: „De la oameni…” se temeau de norod, căci toți socoteau că Ioan a fost în adevăr un proroc.",
    "Atunci au răspuns lui Isus: „Nu știm.” Şi Isus le-a zis: „Nici Eu n-am să vă spun cu ce putere fac aceste lucruri.”",
  ],
  [
    "",
    "Isus a început pe urmă să le vorbească în pilde. „Un om a sădit o vie. A împrejmuit-o cu un gard, a săpat un teasc în ea și a zidit un turn; apoi a arendat-o unor vieri și a plecat din țară.",
    "La vremea roadelor, a trimis la vieri un rob, ca să ia de la ei din roadele viei.",
    "Vierii au pus mâna pe el, l-au bătut și l-au trimis înapoi cu mâinile goale.",
    "A trimis iarăși la ei un alt rob; ei l-au rănit la cap și l-au batjocorit.",
    "A mai trimis un altul pe care l-au omorât; apoi a trimis mulți alții, dintre care, pe unii i-au bătut, iar pe alții i-au omorât.",
    "Mai avea un singur fiu preaiubit; la urmă, l-a trimis și pe el la ei. „Vor primi cu cinste pe fiul meu!”, zicea el.",
    "Dar vierii aceia au zis între ei: „Iată moștenitorul; veniți să-l omorâm, și moștenirea va fi a noastră.”",
    "Şi au pus mâna pe el, l-au omorât și i-au aruncat trupul afară din vie.",
    "Acum, ce va face stăpânul viei? Va veni, va nimici pe vierii aceia, și via o va da altora.",
    "Oare n-ați citit locul acesta din Scriptură: „Piatra pe care au lepădat-o zidarii a ajuns să fie pusă în capul unghiului;",
    "Domnul a făcut acest lucru și este minunat în ochii noștri”?”",
    "Ei căutau să-L prindă, dar se temeau de norod. Pricepuseră că împotriva lor spusese Isus pilda aceasta. Şi L-au lăsat și au plecat.",
    "Apoi au trimis la Isus pe unii din farisei și din irodieni, ca să-L prindă cu vorba.",
    "Aceștia au venit și I-au zis: „Învățătorule, știm că spui adevărul și nu-Ţi pasă de nimeni; căci nu cauți la fața oamenilor și înveți pe oameni calea lui Dumnezeu în adevăr. Se cade să plătim bir cezarului sau nu?",
    "Să plătim sau să nu plătim?” Isus le-a cunoscut fățărnicia și le-a răspuns: „Pentru ce Mă ispitiți? Aduceți-Mi un ban ca să-l văd.”",
    "I-au adus un ban; și Isus i-a întrebat: „Chipul acesta și slovele scrise pe el, ale cui sunt?” „Ale cezarului”, I-au răspuns ei.",
    "Atunci Isus le-a zis: „Dați, dar, cezarului ce este al cezarului, și lui Dumnezeu ce este al lui Dumnezeu.” Şi se mirau foarte mult de El.",
    "Saducheii, care zic că nu este înviere, au venit la Isus și I-au pus următoarea întrebare:",
    "„Învățătorule, iată ce ne-a scris Moise: „Dacă moare fratele cuiva și-i rămâne nevasta fără să aibă copii, fratele său să ia pe nevasta lui și să ridice urmaș fratelui său.”",
    "Erau, dar, șapte frați. Cel dintâi s-a însurat și a murit fără să lase urmaș.",
    "Al doilea a luat de nevastă pe văduvă și a murit fără să lase urmaș. Tot așa și al treilea.",
    "Şi niciunul din cei șapte n-a lăsat urmaș. După ei toți, a murit și femeia.",
    "La înviere, nevasta căruia dintre ei va fi ea? Căci toți șapte au avut-o de nevastă.”",
    "Drept răspuns, Isus le-a zis: „Oare nu vă rătăciți voi, din pricină că nu pricepeți nici Scripturile, nici puterea lui Dumnezeu?",
    "Căci după ce vor învia din morți, nici nu se vor însura, nici nu se vor mărita, ci vor fi ca îngerii în ceruri.",
    "În ce privește învierea morților, oare n-ați citit în cartea lui Moise, în locul unde se vorbește despre „Rug”, ce i-a spus Dumnezeu, când a zis: „Eu sunt Dumnezeul lui Avraam, Dumnezeul lui Isaac și Dumnezeul lui Iacov”?",
    "Dumnezeu nu este un Dumnezeu al celor morți, ci al celor vii. Tare vă mai rătăciți!”",
    "Unul din cărturari, care-i auzise vorbind, fiindcă știa că Isus răspunsese bine saducheilor, a venit la El și L-a întrebat: „Care este cea dintâi dintre toate poruncile?”",
    "Isus i-a răspuns: „Cea dintâi este aceasta: „Ascultă Israele! Domnul Dumnezeul nostru este un singur Domn”;",
    "și: „Să iubești pe Domnul Dumnezeul tău cu toată inima ta, cu tot sufletul tău, cu tot cugetul tău și cu toată puterea ta”; iată porunca dintâi.",
    "Iar a doua este următoarea: „Să iubești pe aproapele tău ca pe tine însuți.” Nu este altă poruncă mai mare decât acestea.”",
    "Cărturarul I-a zis: „Bine, Învățătorule. Adevărat ai zis că Dumnezeu este unul singur, că nu este altul afară de El",
    "și că a-L iubi cu toată inima, cu tot cugetul, cu tot sufletul și cu toată puterea și a iubi pe aproapele ca pe sine este mai mult decât toate arderile de tot și decât toate jertfele.”",
    "Isus a văzut că a răspuns cu pricepere și i-a zis: „Tu nu ești departe de Împărăția lui Dumnezeu.” Şi nimeni nu îndrăznea să-I mai pună întrebări.",
    "Pe când învăța pe norod în Templu, Isus a zis: „Cum zic cărturarii că Hristosul este fiul lui David?",
    "Însuși David, fiind insuflat de Duhul Sfânt, a zis: „Domnul a zis Domnului meu: „Şezi la dreapta Mea, până voi pune pe vrăjmașii Tăi sub picioarele Tale.”",
    "Deci chiar David Îl numește Domn; atunci cum este El fiul lui?” Şi gloata cea mare Îl asculta cu plăcere.",
    "În învățătura pe care le-o dădea, Isus le zicea: „Păziți-vă de cărturari, cărora le place să umble în haine lungi și să le facă lumea plecăciuni prin piețe.",
    "Ei umblă după scaunele dintâi în sinagogi și după locurile dintâi la ospețe;",
    "casele văduvelor le mănâncă și fac rugăciuni lungi de ochii lumii. O mai mare osândă va veni peste ei.”",
    "Isus ședea jos în fața vistieriei Templului și Se uita cum arunca norodul bani în vistierie. Mulți, care erau bogați, aruncau mult.",
    "A venit și o văduvă săracă și a aruncat doi bănuți, care fac un gologan.",
    "Atunci Isus a chemat pe ucenicii Săi și le-a zis: „Adevărat vă spun că această văduvă săracă a dat mai mult decât toți cei ce au aruncat în vistierie;",
    "căci toți ceilalți au aruncat din prisosul lor, dar ea, din sărăcia ei, a aruncat tot ce avea, tot ce-i mai rămăsese ca să trăiască.”",
  ],
  [
    "",
    "Când a ieșit Isus din Templu, unul din ucenicii Lui I-a zis: „Învățătorule, uită-Te ce pietre și ce zidiri!”",
    "Isus i-a răspuns: „Vezi tu aceste zidiri mari? Nu va rămâne aici piatră pe piatră care să nu fie dărâmată.”",
    "Apoi a șezut pe Muntele Măslinilor în fața Templului. Şi Petru, Iacov, Ioan și Andrei L-au întrebat deoparte:",
    "„Spune-ne când se vor întâmpla aceste lucruri și care va fi semnul când se vor împlini toate aceste lucruri?”",
    "Isus a început atunci să le spună: „Băgați de seamă să nu vă înșele cineva.",
    "Fiindcă vor veni mulți în Numele Meu și vor zice: „Eu sunt Hristosul!” Şi vor înșela pe mulți.",
    "Când veți auzi despre războaie și vești de războaie, să nu vă înspăimântați, căci lucrurile acestea trebuie să se întâmple. Dar încă nu va fi sfârșitul.",
    "Un neam se va scula împotriva altui neam, și o împărăție împotriva altei împărății; pe alocuri vor fi cutremure de pământ, foamete și tulburări. Aceste lucruri vor fi începutul durerilor.",
    "Luați seama la voi înșivă. Au să vă dea pe mâna soboarelor judecătorești și veți fi bătuți în sinagogi; din pricina Mea veți fi duși înaintea dregătorilor și înaintea împăraților, pentru ca să le slujiți de mărturie.",
    "Mai întâi trebuie ca Evanghelia să fie propovăduită tuturor neamurilor.",
    "Când vă vor duce să vă dea în mâinile lor, să nu vă îngrijorați mai dinainte cu privire la cele ce veți vorbi, ci să vorbiți orice vi se va da să vorbiți în ceasul acela; căci nu voi veți vorbi, ci Duhul Sfânt.",
    "Fratele va da la moarte pe fratele său, și tatăl pe copilul lui; copiii se vor scula împotriva părinților lor și-i vor omorî.",
    "Veți fi urâți de toți pentru Numele Meu; dar cine va răbda până la sfârșit va fi mântuit.",
    "Când veți vedea „urâciunea pustiirii” stând acolo unde nu se cade să fie – cine citește să înțeleagă – atunci cei ce vor fi în Iudeea să fugă la munți.",
    "Cine va fi pe acoperișul casei să nu se coboare și să nu intre în casă ca să-și ia ceva din ea.",
    "Şi cine va fi la câmp să nu se întoarcă înapoi ca să-și ia haina.",
    "Vai de femeile care vor fi însărcinate și de cele ce vor da țâță în zilele acelea!",
    "Rugați-vă ca lucrurile acestea să nu se întâmple iarna.",
    "Pentru că în zilele acelea va fi un necaz așa de mare cum n-a fost de la începutul lumii pe care a făcut-o Dumnezeu până azi, și cum nici nu va mai fi vreodată.",
    "Şi dacă n-ar fi scurtat Domnul zilele acelea, nimeni n-ar scăpa; dar le-a scurtat din pricina celor aleși.",
    "Dacă vă va zice cineva atunci: „Iată, Hristosul este aici” sau: „Iată-L acolo”, să nu-l credeți.",
    "Căci se vor scula hristoși mincinoși și proroci mincinoși. Ei vor face semne și minuni, ca să înșele, dacă ar fi cu putință, și pe cei aleși.",
    "Păziți-vă, iată că vi le-am spus toate dinainte.",
    "Dar, în zilele acelea, după necazul acesta, soarele se va întuneca, luna nu-și va mai da lumina ei,",
    "stelele vor cădea din cer și puterile care sunt în ceruri vor fi clătinate.",
    "Atunci se va vedea Fiul omului venind pe nori cu mare putere și cu slavă.",
    "Atunci va trimite pe îngerii Săi și va aduna pe cei aleși din cele patru vânturi, de la marginea pământului până la marginea cerului.",
    "Luați învățătură de la smochin prin pilda lui. Când mlădița lui se face fragedă și înfrunzește, știți că vara este aproape.",
    "Tot așa, când veți vedea aceste lucruri împlinindu-se, să știți că Fiul omului este aproape, este chiar la uși.",
    "Adevărat vă spun că nu va trece neamul acesta până nu se vor împlini toate aceste lucruri.",
    "Cerul și pământul vor trece, dar cuvintele Mele nu vor trece.",
    "Cât despre ziua aceea sau ceasul acela, nu știe nimeni, nici îngerii din ceruri, nici Fiul, ci numai Tatăl.",
    "Luați seama, vegheați și rugați-vă; căci nu știți când va veni vremea aceea.",
    "Se va întâmpla ca și cu un om plecat în altă țară, care își lasă casa, dă robilor săi putere, arată fiecăruia care este datoria lui și poruncește portarului să vegheze.",
    "Vegheați, dar, pentru că nu știți când va veni stăpânul casei: sau seara, sau la miezul nopții, sau la cântarea cocoșilor, sau dimineața.",
    "Temeți-vă ca nu cumva, venind fără veste, să vă găsească dormind.",
    "Ce vă zic vouă, zic tuturor: Vegheați!”",
  ],
  [
    "",
    "După două zile era praznicul Paștilor și al Azimelor. Preoții cei mai de seamă și cărturarii căutau cum să prindă pe Isus cu vicleșug și să-L omoare.",
    "Căci ziceau: „Nu în timpul praznicului, ca nu cumva să se facă tulburare în norod.”",
    "Pe când ședea Isus la masă, în Betania, în casa lui Simon, leprosul, a venit o femeie care avea un vas de alabastru cu mir de nard curat, foarte scump; și, după ce a spart vasul, a turnat mirul pe capul lui Isus.",
    "Unora dintre ei le-a fost necaz și ziceau: „Ce rost are risipa aceasta de mir?",
    "Mirul acesta s-ar fi putut vinde cu mai mult de trei sute de lei și să se dea săracilor.” Şi le era foarte necaz pe femeia aceea.",
    "Dar Isus le-a zis: „Lăsați-o în pace; de ce-i faceți supărare? Ea a făcut un lucru frumos față de Mine;",
    "căci pe săraci îi aveți totdeauna cu voi și le puteți face bine oricând voiți, dar pe Mine nu Mă aveți totdeauna.",
    "Ea a făcut ce a putut; Mi-a uns trupul mai dinainte, pentru îngropare.",
    "Adevărat vă spun că, oriunde va fi propovăduită Evanghelia aceasta, în toată lumea, se va istorisi și ce a făcut femeia aceasta, spre pomenirea ei.”",
    "Iuda Iscarioteanul, unul din cei doisprezece, s-a dus la preoții cei mai de seamă ca să le vândă pe Isus.",
    "Când au auzit ei lucrul acesta, s-au bucurat și i-au făgăduit bani. Şi Iuda căuta un prilej nimerit ca să-L dea în mâinile lor.",
    "În ziua dintâi a praznicului Azimelor, când jertfeau paștile, ucenicii lui Isus I-au zis: „Unde voiești să ne ducem să-Ţi pregătim ca să mănânci paștile?”",
    "El a trimis pe doi din ucenicii Săi și le-a zis: „Duceți-vă în cetate; acolo aveți să întâlniți un om ducând un ulcior cu apă: mergeți după el.",
    "Unde va intra el, spuneți stăpânului casei: „Învățătorul zice: „Unde este odaia pentru oaspeți, în care să mănânc paștile cu ucenicii Mei?”",
    "Şi are să vă arate o odaie mare de sus, așternută gata: acolo să pregătiți pentru noi.”",
    "Ucenicii au plecat, au ajuns în cetate și au găsit așa cum le spusese El; și au pregătit paștile.",
    "Seara, Isus a venit cu cei doisprezece.",
    "Pe când ședeau la masă și mâncau, Isus a zis: „Adevărat vă spun că unul din voi, care mănâncă cu Mine, Mă va vinde.”",
    "Ei au început să se întristeze și să-I zică unul după altul: „Nu cumva sunt eu?”",
    "„Este unul din cei doisprezece”, le-a răspuns El, „și anume, cel ce întinde mâna cu Mine în blid.",
    "Fiul omului, negreșit, Se duce după cum este scris despre El. Dar vai de omul acela prin care este vândut Fiul omului! Mai bine ar fi fost pentru el să nu se fi născut.”",
    "Pe când mâncau, Isus a luat o pâine; și, după ce a binecuvântat, a frânt-o și le-a dat, zicând: „Luați, mâncați, acesta este trupul Meu.”",
    "Apoi a luat un pahar și, după ce a mulțumit lui Dumnezeu, li l-a dat, și au băut toți din el.",
    "Şi le-a zis: „Acesta este sângele Meu, sângele legământului celui nou, care se varsă pentru mulți.",
    "Adevărat vă spun că, de acum încolo, nu voi mai bea din rodul viței, până în ziua când îl voi bea nou în Împărăția lui Dumnezeu.”",
    "După ce au cântat cântările de laudă, au ieșit pe Muntele Măslinilor.",
    "Isus le-a zis: „În noaptea aceasta toți veți avea un prilej de poticnire; pentru că este scris: „Voi bate Păstorul, și oile vor fi risipite.”",
    "Dar, după ce voi învia, voi merge înaintea voastră în Galileea.”",
    "Petru I-a zis: „Chiar dacă toți ar avea un prilej de poticnire, eu nu voi avea.”",
    "Şi Isus i-a zis: „Adevărat îți spun că astăzi, chiar în noaptea aceasta, înainte ca să cânte cocoșul de două ori, te vei lepăda de Mine de trei ori.”",
    "Dar Petru I-a zis cu și mai multă tărie: „Chiar dacă ar trebui să mor împreună cu Tine, tot nu mă voi lepăda de Tine.” Şi toți ceilalți au spus același lucru.",
    "S-au dus apoi într-un loc îngrădit, numit Ghetsimani. Şi Isus a zis ucenicilor Săi: „Şedeți aici până Mă voi ruga.”",
    "A luat cu El pe Petru, pe Iacov și pe Ioan și a început să Se înspăimânte și să Se mâhnească foarte tare.",
    "El le-a zis: „Sufletul Meu este cuprins de o întristare de moarte; rămâneți aici și vegheați!”",
    "Apoi a mers puțin mai înainte, S-a aruncat la pământ și Se ruga ca, dacă este cu putință, să treacă de la El ceasul acela.",
    "El zicea: „Ava – adică: Tată – Ţie toate lucrurile Îți sunt cu putință; depărtează de la Mine paharul acesta! Totuși, facă-se nu ce voiesc Eu, ci ce voiești Tu.”",
    "Şi a venit la ucenici, pe care i-a găsit dormind. Şi a zis lui Petru: „Simone, tu dormi? Un ceas n-ai fost în stare să veghezi?",
    "Vegheați și rugați-vă, ca să nu cădeți în ispită; duhul este plin de râvnă, dar trupul este neputincios.”",
    "S-a dus iarăși și S-a rugat, zicând aceleași cuvinte.",
    "Apoi S-a întors din nou și i-a găsit dormind; pentru că li se îngreuiaseră ochii de somn. Ei nu știau ce să-I răspundă.",
    "În sfârșit, a venit a treia oară și le-a zis: „Dormiți de acum și odihniți-vă! Destul! A venit ceasul! Iată că Fiul omului este dat în mâinile păcătoșilor.",
    "Sculați-vă; haidem să mergem; iată că se apropie vânzătorul!”",
    "Şi îndată, pe când vorbea El încă, a venit Iuda, unul din cei doisprezece, și împreună cu el a venit o mulțime de oameni cu săbii și cu ciomege, trimiși de preoții cei mai de seamă, de cărturari și de bătrâni.",
    "Vânzătorul le dăduse semnul acesta: „Pe care-L voi săruta, Acela este; să-L prindeți și să-L duceți sub pază.”",
    "Când a venit Iuda, s-a apropiat îndată de Isus și I-a zis: „Învățătorule!” Şi L-a sărutat mult.",
    "Atunci oamenii aceia au pus mâna pe Isus și L-au prins.",
    "Unul din cei ce stăteau lângă El a scos sabia, a lovit pe robul marelui preot și i-a tăiat urechea.",
    "Isus a luat cuvântul și le-a zis: „Ați ieșit ca după un tâlhar, cu săbii și cu ciomege, ca să Mă prindeți.",
    "În toate zilele am fost la voi și învățam pe oameni în Templu, și nu M-ați prins. Dar toate aceste lucruri s-au întâmplat ca să se împlinească Scripturile.”",
    "Atunci toți ucenicii L-au părăsit și au fugit.",
    "După El mergea un tânăr care n-avea pe trup decât o învelitoare de pânză de in. Au pus mâna pe el;",
    "dar el și-a lăsat învelitoarea și a fugit în pielea goală.",
    "Pe Isus L-au dus la marele preot, unde s-au adunat toți preoții cei mai de seamă, bătrânii și cărturarii.",
    "Petru L-a urmat de departe până în curtea marelui preot; a șezut jos împreună cu aprozii și se încălzea la para focului.",
    "Preoții cei mai de seamă și tot soborul căutau vreo mărturie împotriva lui Isus, ca să-L omoare; dar nu găseau niciuna.",
    "Pentru că mulți făceau mărturisiri mincinoase împotriva Lui, dar mărturisirile lor nu se potriveau.",
    "Unii s-au sculat și au făcut o mărturisire mincinoasă împotriva Lui și au zis:",
    "„Noi L-am auzit zicând: „Eu voi strica Templul acesta, făcut de mâini omenești, și în trei zile voi ridica un altul, care nu va fi făcut de mâini omenești.”",
    "Nici chiar în privința aceasta nu se potrivea mărturisirea lor.",
    "Atunci marele preot s-a sculat în picioare în mijlocul adunării, a întrebat pe Isus și I-a zis: „Nu răspunzi nimic? Ce mărturisesc oamenii aceștia împotriva Ta?”",
    "Isus tăcea și nu răspundea nimic. Marele preot L-a întrebat iarăși și I-a zis: „Ești Tu, Hristosul, Fiul Celui binecuvântat?”",
    "„Da, sunt”, i-a răspuns Isus. „Şi veți vedea pe Fiul omului șezând la dreapta puterii și venind pe norii cerului.”",
    "Atunci marele preot și-a rupt hainele și a zis: „Ce nevoie mai avem de martori?",
    "Ați auzit hula. Ce vi se pare?” Toți L-au osândit să fie pedepsit cu moartea.",
    "Şi unii au început să-L scuipe, să-I acopere fața, să-L bată cu pumnii și să-I zică: „Prorocește!” Iar aprozii L-au primit în palme.",
    "Pe când stătea Petru jos în curte, a venit una din slujnicele marelui preot.",
    "Când a văzut pe Petru încălzindu-se, s-a uitat țintă la el și i-a zis: „Şi tu erai cu Isus din Nazaret!”",
    "El s-a lepădat și a zis: „Nu știu, nici nu înțeleg ce vrei să zici.” Apoi a ieșit în pridvor. Şi a cântat cocoșul.",
    "Când l-a văzut slujnica, a început iarăși să spună celor ce stăteau acolo: „Acesta este unul dintre oamenii aceia.”",
    "Şi el s-a lepădat din nou. După puțină vreme, cei ce stăteau acolo, au zis iarăși lui Petru: „Nu mai încape îndoială că ești unul din oamenii aceia; căci ești galileean, și graiul tău seamănă cu al lor.”",
    "Atunci el a început să se blesteme și să se jure: „Nu cunosc pe Omul acesta despre care vorbiți!”",
    "Îndată a cântat cocoșul a doua oară. Şi Petru și-a adus aminte de vorba pe care i-o spusese Isus: „Înainte ca să cânte cocoșul de două ori, te vei lepăda de Mine de trei ori.” Şi gândindu-se la acest lucru, a început să plângă.",
  ],
  [
    "",
    "Dimineața, preoții cei mai de seamă au făcut îndată sfat cu bătrânii, cărturarii și tot soborul. După ce au legat pe Isus, L-au dus și L-au dat în mâinile lui Pilat.",
    "Pilat L-a întrebat: „Ești Tu Împăratul iudeilor?” „Da, sunt”, i-a răspuns Isus.",
    "Preoții cei mai de seamă Îl învinuiau de multe lucruri.",
    "Pilat L-a întrebat din nou: „Nu răspunzi nimic? Uite de câte lucruri Te învinuiesc ei!”",
    "Isus n-a mai dat niciun răspuns, lucru care a mirat pe Pilat.",
    "La fiecare praznic al Paștilor, Pilat le slobozea un întemnițat pe care-l cereau ei.",
    "În temniță era unul numit Baraba, închis împreună cu tovarășii lui din pricina unui omor pe care-l săvârșiseră într-o răscoală.",
    "Norodul s-a suit și a început să ceară lui Pilat să le dea ce avea obicei să le dea întotdeauna.",
    "Pilat le-a răspuns: „Voiți să vă slobod pe Împăratul iudeilor?”",
    "Căci pricepuse că preoții cei mai de seamă din pizmă Îl dăduseră în mâna lui.",
    "Dar preoții cei mai de seamă au ațâțat norodul să ceară lui Pilat să le sloboadă mai bine pe Baraba.",
    "Pilat a luat din nou cuvântul și le-a zis: „Dar ce voiți să fac cu Acela pe care-L numiți Împăratul iudeilor?”",
    "Ei au strigat din nou: „Răstignește-L!”",
    "„Dar ce rău a făcut?”, le-a zis Pilat. Însă ei au început să strige și mai tare: „Răstignește-L!”",
    "Pilat a vrut să facă pe placul norodului, și le-a slobozit pe Baraba; iar pe Isus, după ce a pus să-L bată cu nuiele, L-a dat să fie răstignit.",
    "Ostașii au adus pe Isus în curte, adică în palat, și au adunat toată ceata ostașilor.",
    "L-au îmbrăcat într-o haină de purpură, au împletit o cunună de spini și I-au pus-o pe cap.",
    "Apoi au început să-I ureze și să zică: „Plecăciune, Împăratul iudeilor!”",
    "Şi-L loveau în cap cu o trestie, Îl scuipau, îngenuncheau și I se închinau.",
    "După ce și-au bătut astfel joc de El, L-au dezbrăcat de haina de purpură, L-au îmbrăcat în hainele Lui și L-au dus să-L răstignească.",
    "Au silit să ducă crucea lui Isus pe un trecător care se întorcea de la câmp, numit Simon din Cirena, tatăl lui Alexandru și al lui Ruf.",
    "Şi au adus pe Isus la locul numit Golgota, care tălmăcit înseamnă: „Locul căpățânii”.",
    "I-au dat să bea vin amestecat cu smirnă, dar El nu l-a luat.",
    "După ce L-au răstignit, I-au împărțit hainele între ei trăgând la sorți, ca să știe ce să ia fiecare.",
    "Când L-au răstignit, era ceasul al treilea.",
    "Deasupra Lui era scrisă vina Lui: „Împăratul iudeilor.”",
    "Împreună cu El au răstignit doi tâlhari, unul la dreapta, și altul la stânga Lui.",
    "Astfel s-a împlinit Scriptura care zice: „A fost pus în numărul celor fărădelege.”",
    "Trecătorii își băteau joc de El, dădeau din cap și ziceau: „Uă! Tu, care strici Templul și-l zidești la loc în trei zile,",
    "mântuiește-Te pe Tine însuți și coboară-Te de pe cruce!”",
    "Tot astfel și preoții cei mai de seamă, împreună cu cărturarii, își băteau joc de El între ei și ziceau: „Pe alții i-a mântuit, și pe Sine însuși nu Se poate mântui!",
    "Hristosul, Împăratul lui Israel, să Se coboare acum de pe cruce, ca să vedem și să credem!” Cei răstigniți împreună cu El, de asemenea, își băteau joc de El.",
    "La ceasul al șaselea, s-a făcut întuneric peste toată țara, până la ceasul al nouălea.",
    "Şi, în ceasul al nouălea, Isus a strigat cu glas tare: „Eloi, Eloi, lama sabactani”, care tălmăcit înseamnă: „Dumnezeul Meu, Dumnezeul Meu, pentru ce M-ai părăsit?”",
    "Unii din cei ce stăteau acolo, când L-au auzit, ziceau: „Iată, cheamă pe Ilie!”",
    "Şi unul din ei a alergat de a umplut un burete cu oțet, l-a pus într-o trestie și I-a dat să bea, zicând: „Lăsați să vedem dacă va veni Ilie să-L coboare de pe cruce!”",
    "Dar Isus a scos un strigăt tare și Şi-a dat duhul.",
    "Perdeaua dinăuntrul Templului s-a rupt în două, de sus până jos.",
    "Sutașul care stătea în fața lui Isus, când a văzut că Şi-a dat astfel duhul, a zis: „Cu adevărat, Omul acesta era Fiul lui Dumnezeu!”",
    "Acolo erau și niște femei care priveau de departe. Printre ele erau Maria Magdalena, Maria, mama lui Iacov cel mic și a lui Iose, și Salome,",
    "care, pe când era El în Galileea, mergeau după El și-I slujeau; și multe alte femei care se suiseră împreună cu El în Ierusalim.",
    "Când s-a înserat – fiindcă era ziua Pregătirii, adică ziua dinaintea Sabatului –",
    "a venit Iosif din Arimateea, un sfetnic cu vază al soborului, care și el aștepta Împărăția lui Dumnezeu. El a îndrăznit să se ducă la Pilat ca să ceară trupul lui Isus.",
    "Pilat s-a mirat că murise așa de curând; a chemat pe sutaș și l-a întrebat dacă a murit de mult.",
    "După ce s-a încredințat de la sutaș că a murit, a dăruit lui Iosif trupul.",
    "Şi Iosif a cumpărat o pânză subțire de in, a dat jos pe Isus de pe cruce, L-a înfășurat în pânza de in și L-a pus într-un mormânt săpat în stâncă. Apoi a prăvălit o piatră la ușa mormântului.",
    "Maria Magdalena și Maria, mama lui Iose, se uitau unde-L puneau.",
  ],
  [
    "",
    "După ce a trecut ziua Sabatului, Maria Magdalena, Maria, mama lui Iacov, și Salome au cumpărat miresme ca să se ducă să ungă trupul lui Isus.",
    "În ziua dintâi a săptămânii, s-au dus la mormânt dis-de-dimineață, pe când răsărea soarele.",
    "Femeile ziceau una către alta: „Cine ne va prăvăli piatra de la ușa mormântului?”",
    "Şi, când și-au ridicat ochii, au văzut că piatra, care era foarte mare, fusese prăvălită.",
    "Au intrat în mormânt, au văzut pe un tinerel șezând la dreapta, îmbrăcat într-un veșmânt alb, și s-au înspăimântat.",
    "El le-a zis: „Nu vă înspăimântați! Căutați pe Isus din Nazaret care a fost răstignit: a înviat, nu este aici; iată locul unde Îl puseseră.",
    "Dar duceți-vă de spuneți ucenicilor Lui și lui Petru, că merge înaintea voastră în Galileea: acolo Îl veți vedea, cum v-a spus.”",
    "Ele au ieșit afară din mormânt și au luat-o la fugă, pentru că erau cuprinse de cutremur și de spaimă. Şi n-au spus nimănui nimic, căci se temeau.",
    "(Isus, după ce a înviat, în dimineața zilei dintâi a săptămânii, S-a arătat mai întâi Mariei Magdalena, din care scosese șapte draci.",
    "Ea s-a dus și a dat de știre celor ce fuseseră împreună cu El, care plângeau și se tânguiau.",
    "Când au auzit ei că este viu și că a fost văzut de ea, n-au crezut-o.",
    "După aceea S-a arătat, în alt chip, la doi dintre ei, pe drum, când se duceau la țară.",
    "Aceștia s-au dus de au spus lucrul acesta celorlalți, dar nici pe ei nu i-au crezut.",
    "În sfârșit, S-a arătat celor unsprezece, când ședeau la masă; și i-a mustrat pentru necredința și împietrirea inimii lor, pentru că nu crezuseră pe cei ce-L văzuseră înviat.",
    "Apoi le-a zis: „Duceți-vă în toată lumea și propovăduiți Evanghelia la orice făptură.",
    "Cine va crede și se va boteza va fi mântuit; dar cine nu va crede va fi osândit.",
    "Iată semnele care vor însoți pe cei ce vor crede: în Numele Meu vor scoate draci; vor vorbi în limbi noi;",
    "vor lua în mână șerpi; dacă vor bea ceva de moarte, nu-i va vătăma; își vor pune mâinile peste bolnavi, și bolnavii se vor însănătoși.”",
    "Domnul Isus, după ce a vorbit cu ei, S-a înălțat la cer și a șezut la dreapta lui Dumnezeu.",
    "Iar ei au plecat și au propovăduit pretutindeni. Domnul lucra împreună cu ei și întărea Cuvântul prin semnele care-l însoțeau. Amin.)",
  ],
]

export function marcuVerseCount(chapter: number): number {
  const verses = MARCU_TEXT[chapter]
  if (!verses) throw new Error(`[Marcu] capitol necunoscut: ${chapter}.`)
  return verses.length - 1
}

export function marcuPassage(chapter: number, from: number, to: number): string {
  const verses = MARCU_TEXT[chapter]
  if (!verses || from < 1 || to < from || to >= verses.length) {
    throw new Error(`[Marcu ${chapter}] pasaj invalid: ${from}-${to}.`)
  }
  return verses.slice(from, to + 1).join(" ")
}
