import { marcuChapter, teaching } from "./marcuHelpers.js"

export const MARCU_7 = marcuChapter({
  number: 7,
  title: "Marcu 7 — Inima curată și credința smerită",
  summary: "Isus demască tradiția care anulează porunca lui Dumnezeu și arată că întinarea pornește din inimă. O femeie dintre neamuri primește eliberarea fiicei ei, iar în Decapole Domnul deschide urechile unui surd și îi dezleagă limba.",
  literaryContext: "După vindecările din capitolul 6, conducătorii se preocupă de mâinile nespălate. Isus mută privirea de la curățirea exterioară la inimă, apoi merge în ținuturi neevreiești, arătând că harul nu este ținut în granițele tradiției.",
  historicalContext: "Spălările rituale proveneau din tradiția bătrânilor. «Corban» desemna un dar declarat pentru Dumnezeu și putea fi folosit ca scuză pentru neglijarea părinților. «Efata» este aramaicul pentru «Deschide-te».",
  units: [
    { verses: [1, 13], heading: "Porunca lui Dumnezeu și tradiția oamenilor", teaching: teaching("O deprindere poate fi bună, dar devine primejdioasă când este ridicată la rang de poruncă și impusă altora ca măsură a sfințeniei. Standardul este Cuvântul lui Dumnezeu, nu regula făcută de noi.", "Isus citează din Isaia: buzele Îl cinstesc, dar inima este departe. Rădăcina rătăcirii este fățărnicia, nu lipsa de informație.", "Prin «Corban», un om putea pretinde că dă lui Dumnezeu și totuși să refuze ajutorul datorat părinților. Orice tradiție trebuie cercetată: mă ajută să ascult sau îmi oferă o scuză să evit ascultarea?"), crossRefs: ["Isaia 29:13", "Exod 20:12", "1 Timotei 5:4-8"], forYourHeart: "Dumnezeu nu caută buze corecte peste o inimă departe, ci adevăr în omul dinăuntru." },
    { verses: [14, 23], heading: "Din inimă ies lucrurile care întinează", teaching: teaching("Isus nu disprețuiește igiena, ci așază lucrurile în ordinea lor: hrana intră în stomac, dar păcatul primit în inimă corupe omul lăuntric. Astfel declară curate toate bucatele.", "Gândurile rele, lăcomia, înșelăciunea, trufia și celelalte păcate ies dinăuntru. Fapta începe ca un gând căruia i se deschide ușa; de aceea inima trebuie păzită și întărită prin har."), crossRefs: ["Fapte 10:9-16", "Romani 14:14", "Iacov 1:14-15"], forYourHeart: "Păzește-ți inima mai atent decât masa. Ispita poate bate, dar nu trebuie primită și hrănită." },
    { verses: [24, 30], heading: "Chiar și cățeii mănâncă firimiturile", teaching: teaching("Femeia siro-feniciană cade la picioarele lui Isus pentru fiica ei. Cuvintele despre copii și căței arată ordinea istorică — întâi Israel — și scot la lumină o credință fără pretenții.", "Ea nu se supără și nu cere merit: se încrede în belșugul Domnului. Pentru acest răspuns, fiica ei este eliberată. Credința și smerenia merg împreună, iar o firimitură din mâna Lui este mai puternică decât întunericul."), crossRefs: ["Matei 15:21-28", "Romani 1:16", "Efeseni 2:11-18"], forYourHeart: "Nu veni pretinzând că meriți; vino încrezându-te că El este bun." },
    { verses: [31, 37], heading: "Efata — Deschide-te", teaching: teaching("Isus îl ia deoparte pe omul surd care vorbea cu anevoie. Nu îl tratează ca spectacol, ci ca persoană, atingându-i urechile și limba într-un fel pe care îl putea înțelege.", "La porunca «Efata», urechile se deschid și limba se dezleagă. Puterea nu este într-o formulă, ci în Persoana lui Isus. El poate deschide și urechea inimii, apoi limba mărturiei.", "Oamenii spun că toate le face bine. Credința matură poate spune aceasta și când suferința rămâne, fiindcă bunătatea Lui nu este măsurată numai prin vindecarea de acum."), crossRefs: ["Isaia 35:5-6", "Matei 11:4-5", "Marcu 8:22-26"], forYourHeart: "Cere-I să-ți deschidă urechea înainte să-ți dezlege limba." },
  ],
  prayer: "Doamne Isuse, curăță-ne de fățărnicie și de tradiția care ocolește ascultarea. Întărește-ne inima prin har, dă-ne smerenia femeii care s-a încrezut în bunătatea Ta și spune peste noi «Efata»: deschide-ne urechile și dezleagă-ne limba pentru adevăr. Amin.",
})
