import { marcuChapter, teaching } from "./marcuHelpers.js"

export const MARCU_16 = marcuChapter({
  number: 16,
  title: "Marcu 16 — A înviat, nu este aici",
  summary: "Femeile găsesc piatra răsturnată și aud vestea învierii, împreună cu chemarea adresată ucenicilor și lui Petru. În încheierea lungă, Isus Se arată martorilor, trimite Evanghelia în toată lumea și Se înalță, iar ucenicii pleacă să propovăduiască.",
  literaryContext: "Piatra capitolului 15 nu poate ține închisă viața. Frica și necredința martorilor sunt întâmpinate de veste, mustrare și trimitere. Evanghelia începută în 1:1 nu se încheie la mormânt, ci continuă prin martorii însoțiți de Domnul.",
  historicalContext: "Femeile au venit după Sabat cu miresme pentru ungerea trupului. Manuscrisele vechi nu sunt toate la fel în privința versetelor 9-20: cele mai timpurii martore se opresc la versetul 8, iar altele păstrează încheierea lungă. Emanus afișează textul RCCV și semnalează onest această situație, fără să construiască practici primejdioase pe pasajul disputat.",
  units: [
    { verses: [1, 8], heading: "Duceți-vă de spuneți ucenicilor Lui și lui Petru", teaching: teaching("Femeile pornesc spre mormânt întrebând cine va răsturna piatra. Când ridică ochii, problema care le depășea este deja rezolvată. Înăuntru nu găsesc trupul, ci vestea: «Isus din Nazaret, care a fost răstignit, a înviat; nu este aici».", "Mesajul îi numește pe ucenici și, în mod deosebit, pe Petru. Cel care se lepădase nu este șters din chemare; harul învierii îl caută personal. Isus merge înaintea lor în Galileea, în locul începuturilor.", "Femeile fug cu cutremur și teamă. Marcu nu cosmetizează slăbiciunea primilor martori: vestea este mai mare decât puterea lor de a o purta, dar adevărul învierii nu depinde de curajul perfect al mesagerului."), crossRefs: ["Matei 28:1-10", "Luca 24:1-12", "1 Corinteni 15:3-8"], forYourHeart: "Piatra de care te temi poate fi deja răsturnată. Ridică ochii și auzi-ți numele în harul care îi cheamă din nou pe cei căzuți." },
    { verses: [9, 14], heading: "Nu i-au crezut", teaching: teaching("Încheierea lungă istorisește arătarea către Maria Magdalena, către doi ucenici și apoi către cei unsprezece. De fiecare dată, mărturia întâlnește necredință. Domnul nu ascunde împietrirea lor, ci îi mustră și totuși îi păstrează ca martori.", "Credința creștină nu s-a născut din ucenici gata să creadă orice, ci din oameni biruiți de întâlnirea cu Cel viu. Mustrarea Lui nu este lepădare; pregătește trimiterea."), crossRefs: ["Ioan 20:11-29", "Luca 24:13-43", "1 Corinteni 15:5-8"], forYourHeart: "Adu-I îndoiala fără să o transformi în stăpân. Cel înviat poate mustra necredința și, în aceeași întâlnire, poate reda chemarea." },
    { verses: [15, 20], heading: "Propovăduiți Evanghelia la orice făptură", teaching: teaching("Isus îi trimite în toată lumea. Centrul este Evanghelia și răspunsul credinței; botezul este mărturia unirii cu El, nu o faptă magică. Semnele au însoțit vestirea apostolică și au arătat puterea Domnului.", "Referirea la șerpi și otravă nu autorizează testarea lui Dumnezeu sau ritualuri primejdioase. Niciun ucenic nu trebuie să manipuleze șerpi ori să bea otravă ca probă a credinței. Dumnezeu poate păzi în primejdii nealese, dar Isus a refuzat ispita de a Se arunca de pe Templu.", "Domnul Se înalță și șade la dreapta lui Dumnezeu. Ucenicii pleacă, iar El lucrează împreună cu ei și întărește Cuvântul. Evanghelia se încheie deschizând drumul Bisericii: Isus domnește, trimite și rămâne lucrător cu ai Săi."), crossRefs: ["Matei 28:18-20", "Fapte 1:8-11", "Fapte 28:3-6", "Evrei 2:3-4"], forYourHeart: "Nu aștepta să fii un martor fără slăbiciune. Mergi cu vestea adevărată; Domnul înviat lucrează împreună cu cei pe care îi trimite." },
  ],
  prayer: "Doamne Isuse, Cel răstignit și înviat, Îți mulțumim că piatra nu Te-a putut ține și că harul Tău îi cheamă pe nume pe cei căzuți. Biruie necredința noastră, păzește-ne de încercarea nechibzuită a lui Dumnezeu și trimite-ne cu Evanghelia. Lucrează împreună cu noi până când orice făptură va auzi. Amin.",
})
