import { marcuChapter, teaching } from "./marcuHelpers.js"

export const MARCU_11 = marcuChapter({
  number: 11,
  title: "Marcu 11 — Împăratul, Templul și credința care iartă",
  summary: "Isus intră în Ierusalim ca Împărat smerit, judecă nerodirea smochinului și curăță Templul transformat în piață. Ucenicii sunt chemați la credință, rugăciune și iertare, iar conducătorii Îi contestă autoritatea.",
  literaryContext: "Drumul început după mărturisirea lui Petru ajunge la Ierusalim. Smochinul și Templul se interpretează unul pe altul: frunze multe, activitate religioasă multă, dar lipsă de rod și rugăciune. Conflictul cu autoritățile intră în etapa finală.",
  historicalContext: "Intrarea pe măgăruș împlinea Zaharia 9:9, iar strigătul «Osana» însemna «mântuiește acum». Schimbătorii de bani și vânzătorii de animale ocupaseră curtea destinată neamurilor. Templul trebuia să fie casă de rugăciune pentru toate popoarele.",
  units: [
    { verses: [1, 11], heading: "Binecuvântat este Cel ce vine", teaching: teaching("Isus pregătește intrarea cu autoritate liniștită și Se așază pe un măgăruș, nu pe cal de război. Mulțimea așterne haine și ramuri și strigă «Osana», primind pe Împăratul promis.", "El intră în Templu și privește toate lucrurile. Nu Se lasă purtat de entuziasmul mulțimii; cercetează casa Tatălui și Se retrage până a doua zi. Împăratul smerit este și Judecătorul care vede."), crossRefs: ["Zaharia 9:9", "Psalmul 118:25-26", "Ioan 12:12-19"], forYourHeart: "Primește-L nu doar cu strigătul unei zile, ci cu cheia casei. Împăratul blând vede toate lucrurile și vrea să domnească în ele." },
    { verses: [12, 26], heading: "Casa Mea se va chema o casă de rugăciune", teaching: teaching("Smochinul are frunze, dar nu rod; Templul are activitate, dar nu rugăciune. Isus răstoarnă mesele și oprește folosirea curții ca scurtătură comercială. Zelul Lui apără locul în care toate neamurile trebuiau să-L caute pe Dumnezeu.", "Smochinul uscat arată judecata nerodirii. Isus îi cheamă însă pe ucenici nu la spectacole, ci la încredere în Dumnezeu: rugăciunea crede că El poate muta ceea ce pare imposibil. Credința nu-L obligă pe Dumnezeu să împlinească orice dorință; ea cere în acord cu El și primește din mâna Lui.", "Rugăciunea este legată de iertare. Nu putem cere har ținând pe altul dator în inima noastră. Iertarea nu numește răul bine și nu anulează limitele sau dreptatea, dar renunță la răzbunare și pune cazul în mâna Tatălui."), crossRefs: ["Isaia 56:7", "Ieremia 7:11", "1 Ioan 5:14", "Efeseni 4:32"], forYourHeart: "Lasă-L să răstoarne masa care a luat locul rugăciunii. Cere-I rod, credință și puterea de a ierta." },
    { verses: [27, 33], heading: "Cu ce putere faci aceste lucruri?", teaching: teaching("Preoții și cărturarii nu cercetează adevărul, ci sursa autorității Lui. Isus îi întreabă despre botezul lui Ioan. Ei calculează reacția oamenilor și răspund «Nu știm», deși problema lor nu era lipsa de dovezi, ci refuzul de a se supune.", "Cine respinge lumina primită nu primește o demonstrație nouă pentru curiozitate. Autoritatea lui Isus se vede în cuvânt, în rod și în curățirea casei Tatălui; întrebarea este dacă ne plecăm înaintea ei."), crossRefs: ["Matei 21:23-27", "Luca 20:1-8", "Marcu 1:22"], forYourHeart: "Nu folosi întrebările ca adăpost împotriva ascultării. Răspunde luminii pe care ai primit-o deja." },
  ],
  prayer: "Împărate Isuse, intră în toate încăperile vieții noastre și curăță ce a luat locul rugăciunii. Fă-ne roditori, învață-ne credința supusă voii Tale și eliberează-ne de neiertare. Păzește-ne să nu ascundem neascultarea sub întrebări și fă din noi o casă în care Tatăl este căutat. Amin.",
})
