/*
 * Textul biblic al cărții Numeri, capitolul 4.
 *
 * Sursa: Biblia Emanus (BE), docs/data/biblia-emanus/NUM.4.json.
 * Capitol cu status "published", auditat verset cu verset din WLC-OSHB,
 * cu WEBU ca bază public-domain. 49 de versete.
 */

export const NUMERI_TEXT_4: Record<number, readonly string[]> = {
  4: [
    "DOMNUL le-a vorbit lui Moise și lui Aaron, spunând:",
    "„Faceți numărătoarea fiilor lui Chehat din mijlocul fiilor lui Levi, după familiile lor, după casele părinților lor,",
    "de la vârsta de treizeci de ani în sus până la cincizeci de ani, toți cei ce intră în slujbă ca să facă lucrare în Cortul Întâlnirii.",
    "Aceasta va fi slujba fiilor lui Chehat în Cortul Întâlnirii: lucrurile preasfânte.",
    "Când tabăra va porni, Aaron și fiii lui să intre, să dea jos perdeaua de despărțire și să acopere chivotul mărturiei cu ea.",
    "Să pună peste ea o învelitoare de piele de vițel de mare, să întindă deasupra o învelitoare realizată în întregime din țesătură albastră și să-i pună drugii.",
    "Peste masa pâinilor prezentării să întindă o pânză albastră și să pună pe ea farfuriile, cănițele, potirele și ulcioarele pentru turnare; pâinea perpetuă va rămâne pe ea.",
    "Să întindă peste ele o pânză stacojie, să o acopere cu o învelitoare de piele de vițel de mare și să-i pună drugii.",
    "Să ia o pânză albastră și să acopere sfeşnicul pentru lumină, candelele lui, cleştele lui, tăvițele lui și toate vasele pentru ulei folosite la slujba lui.",
    "Să le pună pe el și toate uneltele lui într-o învelitoare de piele de vițel de mare și să le pună pe o targă.",
    "Peste altarul de aur să întindă o pânză albastră, să-l acopere cu o învelitoare de piele de vițel de mare și să-i pună drugii.",
    "Să ia toate uneltele slujbei cu care se slujeşte în Sfântul Lăcaş, să le pună într-o pânză albastră, să le acopere cu o învelitoare de piele de vițel de mare și să le pună pe o targă.",
    "Să curețe cenuşa de pe altar și să întindă peste el o pânză purpurie.",
    "Să pună pe el toate uneltele lui cu care se slujeşte la el: tăvițele pentru cărbuni, furculicele, lopețile, potirele și toate uneltele altarului; să întindă peste el o învelitoare de piele de vițel de mare și să-i pună drugii.",
    "Când Aaron și fiii lui vor termina de acoperit Sfântul Lăcaş și toate uneltele Sfântului Lăcaş, la pornirea taberei, fiii lui Chehat să vină ca să le poarte; dar să nu se atingă de lucrurile sfinte, ca să nu moară. Acestea sunt lucrurile din Cortul Întâlnirii pe care le vor purta fiii lui Chehat.",
    "În paza lui Eleazar, fiul preotului Aaron, va fi uleiul pentru lumină, tămâia mirositoare, ofranda de mâncare perpetuă și uleiul pentru ungere, supravegherea întregului Cort și a tot ce este în el, în Sfântul Lăcaş și în uneltele lui.”",
    "DOMNUL i-a vorbit lui Moise și lui Aaron, spunând:",
    "„Nu lăsați ca seminția familiilor chehat iților să fie nimicită din mijlocul leviților;",
    "ci faceți aşa pentru ei, ca să trăiască și să nu moară când se vor apropia de lucrurile preasfânte: Aaron și fiii lui să intre și să-i rânduiască pe fiecare la slujba lui și la sarcina lui.",
    "Dar ei să nu intre să privească lucrurile sfinte nici măcar o clipă, ca să nu moară.”",
    "DOMNUL i-a vorbit lui Moise, spunând:",
    "„Fa numărătoarea fiilor lui Gherşon, și a lor, după casele părinților lor, după familiile lor;",
    "de la vârsta de treizeci de ani în sus până la cincizeci de ani să-i numări, pe toți cei ce intră în slujbă ca să facă lucrare în Cortul Întâlnirii.",
    "Aceasta va fi slujba familiilor gherşoniților, la slujire și la purtarea sarcinilor:",
    "ei vor purta covoarele Cortului, Cortul Întâlnirii, învelitoarea lui, învelitoarea de piele de vițel de mare care este deasupra lui, perdeaua de la intrarea Cortului Întâlnirii,",
    "pânzele curții, perdeaua de la intrarea porții curții care este împrejurul Cortului și al altarului, frânghiile lor și toate uneltele pentru slujba lor; vor face tot ce trebuie făcut cu privire la ele.",
    "Toată slujba fiilor gherşoniților va fi sub porunca lui Aaron și a fiilor lui, pentru toate sarcinile lor și pentru toată slujba lor; și le veți da în grijă tot ce au de purtat.",
    "Aceasta este slujba familiilor fiilor gherşoniților în Cortul Întâlnirii; iar însărcinarea lor va fi sub supravegherea lui Itamar, fiul preotului Aaron.",
    "Pe fiii lui Merari să-i numări după familiile lor, după casele părinților lor;",
    "de la vârsta de treizeci de ani în sus până la cincizeci de ani să-i numări, pe toți cei ce intră în slujbă ca să facă lucrarea Cortului Întâlnirii.",
    "Aceasta este paza sarcinii lor, pentru toată slujba lor în Cortul Întâlnirii: scândurile Cortului, drugii lui, stâlpii lui, picioarele lui,",
    "stâlpii curții de jur împrejur, picioarele lor, țăruşii lor, frânghiile lor, cu toate uneltele lor și cu toată slujba lor; și veți rândui pe nume uneltele pe care le au de purtat.",
    "Aceasta este slujba familiilor fiilor lui Merari, pentru toată slujba lor în Cortul Întâlnirii, sub supravegherea lui Itamar, fiul preotului Aaron.”",
    "Moise, Aaron și căpeteniile adunării i-au numărat pe fiii chehat iților după familiile lor și după casele părinților lor,",
    "de la vârsta de treizeci de ani în sus până la cincizeci de ani, pe toți cei ce intrau în slujbă ca să facă lucrare în Cortul Întâlnirii.",
    "Cei numărați din ei, după familiile lor, au fost două mii șapte sute cincizeci.",
    "Aceștia sunt cei numărați din familiile chehat iților, toți cei ce slujeau în Cortul Întâlnirii, pe care i-au numărat Moise și Aaron după porunca DOMNULUI dată prin Moise.",
    "Cei numărați din fiii lui Gherşon, după familiile lor și după casele părinților lor,",
    "de la vârsta de treizeci de ani în sus până la cincizeci de ani, toți cei ce intrau în slujbă ca să facă lucrare în Cortul Întâlnirii,",
    "cei numărați din ei, după familiile lor, după casele părinților lor, au fost două mii șase sute treizeci.",
    "Aceștia sunt cei numărați din familiile fiilor lui Gherşon, toți cei ce slujeau în Cortul Întâlnirii, pe care i-au numărat Moise și Aaron după porunca DOMNULUI.",
    "Cei numărați din familiile fiilor lui Merari, după familiile lor, după casele părinților lor,",
    "de la vârsta de treizeci de ani în sus până la cincizeci de ani, toți cei ce intrau în slujbă ca să facă lucrare în Cortul Întâlnirii,",
    "cei numărați din ei, după familiile lor, au fost trei mii două sute.",
    "Aceștia sunt cei numărați din familiile fiilor lui Merari, pe care i-au numărat Moise și Aaron după porunca DOMNULUI dată prin Moise.",
    "Toți cei numărați dintre leviți, pe care Moise, Aaron și căpeteniile lui Israel i-au numărat după familiile lor și după casele părinților lor,",
    "de la vârsta de treizeci de ani în sus până la cincizeci de ani, toți cei ce intrau ca să facă lucrarea de slujire și lucrarea de purtare a sarcinilor în Cortul Întâlnirii,",
    "cei numărați din ei au fost opt mii cinci sute optzeci.",
    "După porunca DOMNULUI dată prin Moise, au fost numărați fiecare la slujba lui și la sarcina lui; aşa au fost numărați, cum îi poruncise DOMNUL lui Moise.",
  ],
}
