/*
 * Textul biblic al cărții Numeri, capitolul 26.
 *
 * Sursa: Biblia Emanus (BE), docs/data/biblia-emanus/NUM.26.json.
 * Capitol cu status "published", auditat verset cu verset din WLC-OSHB,
 * cu WEBU ca bază public-domain. 65 de versete.
 */

export const NUMERI_TEXT_26: Record<number, readonly string[]> = {
  26: [
    "După urgie, DOMNUL le-a vorbit lui Moise și lui Eleazar, fiul preotului Aaron, spunând:",
    "„F aceți numărătoarea întregii adunări a fiilor lui Israel, de la vârsta de douăzeci de ani în sus, după casele părinților lor, toți cei din Israel buni de mers la război.”",
    "Moise și preotul Eleazar le-au vorbit în câmpiile Moabului, lângă Iordan, în fața Ierihonului, zicând:",
    "„De la vârsta de douăzeci de ani în sus să-i numeri, cum îi poruncise DOMNUL lui Moise și fiilor lui Israel care ieşiseră din țara Egiptului.”",
    "Ruben, întâiul născut al lui Israel. Fiii lui Ruben: din Enoh, familia enohiiților; din Palu, familia paluiților;",
    "din Hețron, familia hețroniiților; din Carmi, familia carmiiților.",
    "Acestea sunt familiile rubeniților: cei numărați din ele au fost patruzeci și trei de mii șapte sute treizeci.",
    "Fiul lui Palu a fost Eliab.",
    "Fiii lui Eliab: Nemuel, Datan și Abiram. Aceşti Datan și Abiram erau fruntaşii adunării care s-au răzvrătit împotriva lui Moise și a lui Aaron în ceta lui Core, când s-au răzvrătit împotriva DOMNULUI;",
    "iar pământul și-a deschis gura și i-a înghițit împreună cu Core, când a murit ceta aceea și când focul i-a mistuit pe cei două sute cincizeci de bărbați; și au slujit ca pildă.",
    "Totuşi fiii lui Core nu au murit.",
    "Fiii lui Simeon, după familiile lor: din Nemuel, familia nemueliiților; din Iamin, familia iaminiiților; din Iachin, familia iachiniiților;",
    "din Zerah, familia zerahiiților; din Shaul, familia shauliiților.",
    "Acestea sunt familiile simiioniiților: douăzeci și două de mii două sute.",
    "Fiii lui Gad, după familiile lor: din Ţefon, familia țiefroniiților; din Hagi, familia hagiiților; din Şuni, familia şuniiților;",
    "din Ozni, familia ozniiților; din Eri, familia eriiților;",
    "din Arod, familia arodiiților; din Areli, familia areliiților.",
    "Acestea sunt familiile fiilor lui Gad, după cei numărați din ele: patruzeci de mii cinci sute.",
    "Fiii lui Iuda: Er și Onan; dar Er și Onan au murit în țara Canaan.",
    "Fiii lui Iuda, după familiile lor, au fost: din Şela, familia şelaiiților; din Pereț, familia perețiiților; din Zerah, familia zerahiiților.",
    "Fiii lui Pereț au fost: din Hețron, familia hețroniiților; din Hamul, familia hamuliiților.",
    "Acestea sunt familiile lui Iuda, după cei numărați din ele: şaptezeci și şase de mii cinci sute.",
    "Fiii lui Isahar, după familiile lor: din Tola, familia tolaiiților; din Puva, familia puvaiiților;",
    "din Iaşub, familia iaşubiiților; din Şimron, familia şimroniiților.",
    "Acestea sunt familiile lui Isahar, după cei numărați din ele: şaizeci și patru de mii trei sute.",
    "Fiii lui Zabulon, după familiile lor: din Sered, familia serediiților; din Elon, familia eloniiților; din Iahleel, familia iahleeliilor.",
    "Acestea sunt familiile zabuloniiților, după cei numărați din ele: şaizeci de mii cinci sute.",
    "Fiii lui Iosif, după familiile lor: Manase și Efraim.",
    "Fiii lui Manase: din Machir, familia machiriiților; Machir a fost tatăl lui Galaad; din Galaad, familia galaadiiților.",
    "Aceştia sunt fiii lui Galaad: din Iezer, familia iezeriiților; din Helec, familia heleciiților;",
    "din Asriel, familia asrieliiților; din Şehem, familia şehemiiților;",
    "din Şemida, familia şemidaiiților; din Hefer, familia heferiiților.",
    "Ţelofhad, fiul lui Hefer, nu a avut fii, ci numai fiice; iar numele fiicelor lui Ţelofhad erau Mahla, Noa, Hogla, Milca și Ţirța.",
    "Acestea sunt familiile lui Manase; cei numărați din ele au fost cincizeci și două de mii şapte sute.",
    "Aceştia sunt fiii lui Efraim, după familiile lor: din Şutelah, familia şutelahiiților; din Becher, familia becheriiților; din Tahan, familia tahanaiiților.",
    "Iar acesta este fiul lui Şutelah: din Eran, familia eraniiților.",
    "Acestea sunt familiile fiilor lui Efraim, după cei numărați din ele: treizeci și două de mii cinci sute. Aceştia sunt fiii lui Iosif, după familiile lor.",
    "Fiii lui Beniamin, după familiile lor: din Bela, familia belaiiților; din Aşbel, familia aşbeliiților; din Ahiram, familia ahiramiiților;",
    "din Şefufam, familia şefufamiiților; din Hufam, familia hufamiiților.",
    "Fiii lui Bela au fost Ard și Naaman: din Ard, familia ardiiților; din Naaman, familia naamanaiiților.",
    "Aceştia sunt fiii lui Beniamin, după familiile lor; cei numărați din ele au fost patruzeci și cinci de mii şase sute.",
    "Aceştia sunt fiii lui Dan, după familiile lor: din Şuham, familia şuhamiiților. Acestea sunt familiile lui Dan, după familiile lor.",
    "Toate familiile şuhamiiților, după cei numărați din ele, au fost şaizeci și patru de mii patru sute.",
    "Fiii lui Aşer, după familiile lor: din Iimna, familia iimnaiiților; din Iişvi, familia iişviiților; din Beria, familia beriaaiiților.",
    "Din fiii lui Beria: din Heber, familia heberiiților; din Malchiel, familia malchieliiților.",
    "Iar numele fiicei lui Aşer era Serah.",
    "Acestea sunt familiile fiilor lui Aşer, după cei numărați din ele: cincizeci și trei de mii patru sute.",
    "Fiii lui Neftali, după familiile lor: din Iaheel, familia iaheeliilor; din Guni, familia guniiților;",
    "din Iețer, familia iețeriiților; din Şillem, familia şilllemiiților.",
    "Acestea sunt familiile lui Neftali, după familiile lor; cei numărați din ele au fost patruzeci și cinci de mii patru sute.",
    "Aceştia sunt cei numărați dintre fiii lui Israel: şase sute una de mii şapte sute treizeci.",
    "DOMNUL i-a vorbit lui Moise, spunând:",
    "„Ţara să se împartă ca moştenire între aceştia, după numărul numelor.",
    "Celor mai numeroşi să le dai o moştenire mai mare, iar celor mai puțini să le dai o moştenire mai mică; fiecăruia i se va da moştenirea după numărul celor numărați din el.",
    "Dar țara se va împarți prin sorți; ei o vor moşteni după numele semințiilor părinților lor.",
    "Îmapărțirea moştenirii se va face prin sorți între cei mai numeroşi și cei mai puțini.”",
    "Aceştia sunt leviiții numărați, după familiile lor: din Gherşon, familia gherşoniiților; din Chehat, familia chehatiiților; din Merari, familia merariiților.",
    "Acestea sunt familiile lui Levi: familia libniiților, familia hebroniiților, familia mahliiților, familia muşiiților și familia coreiiților. Chehat a fost tatăl lui Amram.",
    "Numele soției lui Amram era Iochebed, fiica lui Levi, care i se născuse lui Levi în Egipt; ea i-a născut lui Amram pe Aaron, pe Moise și pe Maria, sora lor.",
    "Lui Aaron i s-au născut Nadab, Abihu, Eleazar și Itamar.",
    "Dar Nadab și Abihu au murit când au adus foc străin înaintea DOMNULUI.",
    "Cei numărați din ei au fost douăzeci și trei de mii, toți bărbații de la vârsta de o lună în sus; căci ei nu au fost numărați în mijlocul fiilor lui Israel, pentru că nu li s-a dat nicio moştenire în mijlocul fiilor lui Israel.",
    "Aceştia sunt cei numărați de Moise și de preotul Eleazar, care i-au numărat pe fiii lui Israel în câmpiile Moabului, lângă Iordan, în fața Ierihonului.",
    "Printre aceştia nu a fost niciunul din bărbații numărați de Moise și de preotul Aaron când i-au numărat pe fiii lui Israel în pustia Sinai.",
    "Căci DOMNUL zisese despre ei: „Vor muri neapărat în pustie.” Şi nu a rămas niciunul din ei, afară de Caleb, fiul lui Iefune, și Iosua, fiul lui Nun.",
  ],
}
