/*
 * Textul biblic al cărții Numeri, capitolul 3.
 *
 * Sursa: Biblia Emanus (BE), docs/data/biblia-emanus/NUM.3.json.
 * Capitol cu status "published", auditat verset cu verset din WLC-OSHB,
 * cu WEBU ca bază public-domain. 51 de versete.
 */

export const NUMERI_TEXT_3: Record<number, readonly string[]> = {
  3: [
    "Acestea sunt spițele de neam ale lui Aaron și ale lui Moise din ziua în care DOMNUL i-a vorbit lui Moise pe muntele Sinai.",
    "Acestea sunt numele fiilor lui Aaron: Nadab, întâiul născut, Abihu, Eleazar și Itamar.",
    "Acestea sunt numele fiilor lui Aaron, preoții unși, care au fost înveștiți ca să slujească ca preoți.",
    "Nadab și Abihu au murit înaintea DOMNULUI când au adus foc străin înaintea DOMNULUI în pustia Sinai și nu au avut fii. Eleazar și Itamar au slujit ca preoți în fața tatălui lor, Aaron.",
    "DOMNUL i-a vorbit lui Moise, spunând:",
    "„Apropiee seminția lui Levi și pune-o înaintea preotului Aaron, ca să-i slujească.",
    "Ei vor îndeplini slujba pentru el și slujba pentru toată adunarea înaintea Cortului Întâlnirii, ca să facă slujba Lăcaşului.",
    "Ei vor păzi toate uneltele Cortului Întâlnirii și vor îndeplini slujba pentru fiii lui Israel, făcând slujba Lăcaşului.",
    "Să-i dai pe leviți lui Aaron și fiilor lui; ei îi sunt dați cu totul din mijlocul fiilor lui Israel.",
    "Pe Aaron și pe fiii lui să-i rânduieşti ca să-și păzească slujba preoțească; iar străinul care se va apropia să fie dat la moarte.”",
    "DOMNUL i-a vorbit lui Moise, spunând:",
    "„Iată, Eu i-am luat pe leviți din mijlocul fiilor lui Israel în locul tuturor întâilor născuți care deschid pântecele printre fiii lui Israel; leviții vor fi ai Mei,",
    "căci toți întâii născuți sunt ai Mei. În ziua în care i-am lovit pe toți întâii născuți în țara Egiptului, Mi-am sfințit toți întâii născuți din Israel, de la om până la animal. Ei vor fi ai Mei: Eu sunt DOMNUL.”",
    "DOMNUL i-a vorbit lui Moise în pustia Sinai, spunând:",
    "„Numără-i pe fiii lui Levi după casele părinților lor, după familiile lor; să numări toți bărbații de la vârsta de o lună în sus.”",
    "Moise i-a numărat după cuvântul DOMNULUI, aşa cum i se poruncise.",
    "Aceștia au fost fiii lui Levi, după numele lor: Gherşon, Chehat și Merari.",
    "Acestea sunt numele fiilor lui Gherşon, după familiile lor: Libni și Şimei.",
    "Fiii lui Chehat, după familiile lor: Amram, Ițhar, Hebron și Uziel.",
    "Fiii lui Merari, după familiile lor: Mahli și Muşi. Acestea sunt familiile leviților, după casele părinților lor.",
    "Din Gherşon este familia libniților și familia şimeiților; acestea sunt familiile gherşoniților.",
    "Cei numărați din ele, numărând toți bărbații de la vârsta de o lună în sus, cei numărați au fost șapte mii cinci sute.",
    "Familiile gherşoniților vor tăbărî în spatele Cortului, spre apus.",
    "Căpetenia casei părinteşti a gherşoniților va fi Eliasaf, fiul lui Lael.",
    "Slujba fiilor lui Gherşon în Cortul Întâlnirii va fi Cortul și Lăcaşul, învelitoarea lui, perdeaua de la intrarea Cortului Întâlnirii,",
    "pânzele curții, perdeaua de la intrarea curții care este împrejurul Cortului și al altarului, și frânghiile lui pentru toată slujba lui.",
    "Din Chehat este familia amramiților, familia ițhariților, familia hebroniților și familia uzieliților; acestea sunt familiile chehat iților.",
    "Numărând toți bărbații de la vârsta de o lună în sus, au fost opt mii șase sute, care îndeplineau slujba Sfântului Lăcaş.",
    "Familiile fiilor lui Chehat vor tăbărî pe partea de sud a Cortului.",
    "Căpetenia casei părinteşti a familiilor chehat iților va fi Elițafan, fiul lui Uziel.",
    "În paza lor vor fi chivotul, masa, sfeşnicul, altarele, uneltele Sfântului Lăcaş cu care se slujeşte, perdeaua și toată slujba privitoare la ele.",
    "Eleazar, fiul preotului Aaron, va fi căpetenia căpeteniilor leviților și va supraveghea pe cei ce îndeplinesc slujba Sfântului Lăcaş.",
    "Din Merari este familia mahliților și familia muşiților; acestea sunt familiile lui Merari.",
    "Cei numărați din ele, numărând toți bărbații de la vârsta de o lună în sus, au fost șase mii două sute.",
    "Căpetenia casei părinteşti a familiilor lui Merari va fi Ţuriel, fiul lui Abihail. Ei vor tăbărî pe partea de nord a Cortului.",
    "În paza fiilor lui Merari vor fi scândurile Cortului, drugii lui, stâlpii lui, picioarele lui, toate uneltele lui și toată slujba privitoare la ele,",
    "stâlpii curții de jur împrejur, picioarele lor, țăruşii lor și frânghiile lor.",
    "Cei ce vor tăbărî în fața Cortului spre răsărit, în fața Cortului Întâlnirii spre răsăritul soarelui, vor fi Moise, Aaron și fiii lui, îndeplinind slujba Sfântului Lăcaş pentru fiii lui Israel. Iar străinul care se va apropia să fie dat la moarte.",
    "Toți cei numărați dintre leviți, pe care Moise și Aaron i-au numărat după familiile lor, la porunca DOMNULUI, toți bărbații de la o lună în sus, au fost douăzeci și două de mii.",
    "DOMNUL i-a spus lui Moise: „Numără-i pe toți întâii născuți de sex masculin dintre fiii lui Israel, de la vârsta de o lună în sus, și ia numărul numelor lor.",
    "Să-i iei pe leviți pentru Mine — Eu sunt DOMNUL — în locul tuturor întâilor născuți dintre fiii lui Israel, și vitele leviților în locul tuturor întâilor născuți dintre vitele fiilor lui Israel.”",
    "Moise i-a numărat pe toți întâii născuți dintre fiii lui Israel, aşa cum îi poruncise DOMNUL.",
    "Toți întâii născuți de sex masculin, după numărul numelor, de la vârsta de o lună în sus, cei numărați au fost douăzeci și două de mii două sute șaptezeci și trei.",
    "DOMNUL i-a vorbit lui Moise, spunând:",
    "„Ia-i pe leviți în locul tuturor întâilor născuți dintre fiii lui Israel, și vitele leviților în locul vitelor lor; leviții vor fi ai Mei: Eu sunt DOMNUL.",
    "Iar pentru răscumpărarea celor două sute șaptezeci și trei dintre întâii născuți ai fiilor lui Israel, care depăşesc numărul leviților,",
    "să iei câte cinci şecheli de cap, după şechelul Sfântului Lăcaş (un şechel are douăzeci de ghera).",
    "Să-i dai banii lui Aaron și fiilor lui, ca răscumpărare pentru cei ce depăşesc numărul.”",
    "Moise a luat banii de răscumpărare de la cei ce depăşeau numărul celor răscumpărați de leviți.",
    "A luat banii de la întâii născuți ai fiilor lui Israel: mie trei sute șaizeci și cinci de şecheli, după şechelul Sfântului Lăcaş.",
    "Şi Moise i-a dat banii de răscumpărare lui Aaron și fiilor lui, după cuvântul DOMNULUI, aşa cum îi poruncise DOMNUL lui Moise.",
  ],
}
