/*
 * Textul biblic al cărții Numeri, capitolul 16.
 *
 * Sursa: Biblia Emanus (BE), docs/data/biblia-emanus/NUM.16.json.
 * Capitol cu status "published", auditat verset cu verset din WLC-OSHB,
 * cu WEBU ca bază public-domain. 50 de versete.
 */

export const NUMERI_TEXT_16: Record<number, readonly string[]> = {
  16: [
    "Core, fiul lui Ițhar, fiul lui Chehat, fiul lui Levi, împreună cu Datan și Abiram, fiii lui Eliab, și On, fiul lui Pelet, fiii lui Ruben, au luat oameni",
    "și s-au ridicat împotriva lui Moise, împreună cu două sute cincizeci de bărbați dintre fiii lui Israel, fruntași ai adunării, chemați la sfat, bărbați cu nume.",
    "S-au strâns împotriva lui Moise și a lui Aaron și le-au zis: „Destul! Căci toată adunarea, toți sunt sfinți și DOMNUL este în mijlocul lor. De ce vă ridicați voi mai presus de adunarea DOMNULUI?”",
    "Când a auzit Moise, a căzut cu fața la pământ.",
    "Și i-a vorbit lui Core și întregii lui cete, zicând: „Mâine dimineață DOMNUL va arăta cine este al Lui și cine este sfânt, și-l va lăsa să Se apropie de El; pe cel pe care-l va alege îl va lăsa să Se apropie de El.",
    "Faceți aceasta: luați cădelnițe, Core și toată ceta ta;",
    "mâine puneți foc în ele și puneți tămâie pe ele înaintea DOMNULUI; și omul pe care-l va alege DOMNUL, acela va fi sfânt. Destul, fiii lui Levi!”",
    "Moise i-a spus lui Core: „Ascultați, vă rog, fiii lui Levi!",
    "Este oare puțin lucru pentru voi că Dumnezeul lui Israel v-a ales din adunarea lui Israel, ca să vă lase să vă apropiați de El, ca să faceți slujba Cortului DOMNULUI și să stați înaintea adunării ca să-i slujiți?",
    "Te-a lăsat să te apropii de El, pe tine și pe toți frații tăi, fiii lui Levi, împreună cu tine; și voi căutați și preoția?",
    "De aceea tu și toată ceta ta v-ați strâns împotriva DOMNULUI; căci cine este Aaron, ca să cârtiți împotriva lui?”",
    "Moise a trimis să-i cheme pe Datan și pe Abiram, fiii lui Eliab; dar ei au zis: „Nu ne suim!",
    "Este puțin lucru că ne-ai scos dintr-o țară în care curge lapte și miere ca să ne faci să murim în pustie, de vrei să te faci și stăpân peste noi?",
    "Nici nu ne-ai dus într-o țară în care curge lapte și miere și nici nu ne-ai dat o moștenire de ogoare și de vii! Crezi că poți scoate ochii oamenilor acestora? Nu ne suim!”",
    "Moise s-a mâniat foarte tare și I-a zis DOMNULUI: „Nu primi ofranda lor! Nu le-am luat nici măcar un măgar și nu i-am făcut niciunuia dintre ei vreun rău.”",
    "Moise i-a spus lui Core: „Tu și toată ceta ta să fiți mâine înaintea DOMNULUI, tu, ei și Aaron.",
    "Fiecare să-și ia cădelnița, să pună tămâie pe ea și să-și aducă fiecare cădelnița înaintea DOMNULUI, două sute cincizeci de cădelnițe; tu și Aaron, fiecare cu cădelnița lui.”",
    "Și-au luat fiecare cădelnița, au pus foc în ele, au pus tămâie pe ele și au stat la intrarea Cortului Întâlnirii, împreună cu Moise și Aaron.",
    "Core a strâns toată adunarea împotriva lor la intrarea Cortului Întâlnirii. Atunci slava DOMNULUI S-a arătat întregii adunări.",
    "DOMNUL le-a vorbit lui Moise și lui Aaron, spunând:",
    "„Despărțiți-vă din mijlocul acestei adunări și-i voi mistui într-o clipă!”",
    "Ei au căzut cu fața la pământ și au zis: „O, Dumnezeule, Dumnezeul duhurilor oricărui trup! Un singur om a păcătuit și Te-ai mâniat pe toată adunarea?”",
    "DOMNUL i-a vorbit lui Moise, spunând:",
    "„Vorbește adunării și spune-i: «Depărtați-vă de jur împrejurul locuinței lui Core, Datan și Abiram!»”",
    "Moise s-a sculat și s-a dus la Datan și Abiram; și bătrânii lui Israel l-au urmat.",
    "A vorbit adunării, zicând: „Depărtați-vă, vă rog, de corturile acestor oameni răi și nu vă atingeți de nimic din ce este al lor, ca să nu pieriți din cauza tuturor păcatelor lor!”",
    "Ei s-au depărtat din toate părțile de locuința lui Core, Datan și Abiram. Datan și Abiram au ieșit și au stat la intrarea corturilor lor, cu soțiile lor, cu fiii lor și cu pruncii lor.",
    "Moise a zis: „Prin aceasta veți cunoaște că DOMNUL m-a trimis să fac toate aceste lucrări și că nu am lucrat de la mine:",
    "dacă oamenii aceștia vor muri cum mor toți oamenii și dacă vor avea soarta tuturor oamenilor, nu m-a trimis DOMNUL;",
    "dar dacă DOMNUL va face o lucrare neobișnuită, dacă pământul își va deschide gura și-i va înghiți cu tot ce este al lor, și se vor coborî vii în Locuința Morților, atunci veți ști că oamenii aceștia L-au disprețuit pe DOMNUL.”",
    "Cum a isprăvit de rostit toate aceste cuvinte, pământul s-a despicat sub ei.",
    "Pământul și-a deschis gura și i-a înghițit pe ei, casele lor, pe toți oamenii lui Core și toate averile lor.",
    "Au coborât vii în Locuința Morților, ei și tot ce aveau; pământul i-a acoperit și au pierit din mijlocul adunării.",
    "Tot Israelul care era în jurul lor a fugit la strigătul lor, căci ziceau: „Să nu ne înghită și pe noi pământul!”",
    "Un foc a ieșit de la DOMNUL și i-a mistuit pe cei două sute cincizeci de bărbați care aduceau tămâia.",
    "DOMNUL i-a vorbit lui Moise, spunând:",
    "„Spune-i lui Eleazar, fiul preotului Aaron, să ia cădelnițele din mijlocul arsurii și să împrăștie focul departe, căci ele sunt sfințite.",
    "Cădelnițele acestor oameni care au păcătuit cu prețul vieții lor să fie făcute foițe bătute pentru îmbrăcarea altarului, pentru că au fost aduse înaintea DOMNULUI și au devenit sfinte; ele vor fi un semn pentru fiii lui Israel.”",
    "Preotul Eleazar a luat cădelnițele de aramă pe care le aduseseră cei ce fuseseră arși și le-a bătut în foițe pentru îmbrăcarea altarului,",
    "ca aducere aminte pentru fiii lui Israel, ca niciun străin care nu este din neamul lui Aaron să nu se apropie să ardă tămâie înaintea DOMNULUI, ca să nu ajungă ca Core și ca ceta lui, cum îi spusese DOMNUL prin Moise.",
    "A doua zi toată adunarea fiilor lui Israel a cârtit împotriva lui Moise și împotriva lui Aaron, zicând: „Voi ați omorât poporul DOMNULUI!”",
    "Pe când se strângea adunarea împotriva lui Moise și a lui Aaron, s-au întors spre Cortul Întâlnirii; și iată că norul l-a acoperit și slava DOMNULUI S-a arătat.",
    "Moise și Aaron au venit în fața Cortului Întâlnirii.",
    "Și DOMNUL i-a vorbit lui Moise, spunând:",
    "„Depărtați-vă din mijlocul acestei adunări și-i voi mistui într-o clipă!” Ei au căzut cu fața la pământ.",
    "Moise i-a spus lui Aaron: „Ia cădelnița, pune foc în ea de pe altar, pune tămâie pe ea și du-te repede la adunare și fă ispășire pentru ei; căci mânia a ieșit de la DOMNUL, urgia a început!”",
    "Aaron a luat cădelnița, cum îi spusese Moise, și a alergat în mijlocul adunării; și iată că urgia începuse printre popor. A pus tămâia și a făcut ispășire pentru popor.",
    "A stat între cei morți și cei vii, și urgia s-a oprit.",
    "Cei ce au murit de urgie au fost paisprezece mii șapte sute, afară de cei ce muriseră din pricina lui Core.",
    "Aaron s-a întors la Moise la intrarea Cortului Întâlnirii. Urgia se oprise.",
  ],
}
