/*
 * Textul biblic al cărții Numeri, capitolul 31.
 *
 * Sursa: Biblia Emanus (BE), docs/data/biblia-emanus/NUM.31.json.
 * Capitol cu status "published", auditat verset cu verset din WLC-OSHB,
 * cu WEBU ca bază public-domain. 54 de versete.
 */

export const NUMERI_TEXT_31: Record<number, readonly string[]> = {
  31: [
    "DOMNUL i-a vorbit lui Moise, spunând:",
    "„Răzbună pe fiii lui Israel împotriva madianiților; după aceea vei fi adăugat la poporul tău.”",
    "Moise i-a vorbit poporului, zicând: „Înarmați dintre voi bărbați pentru război, ca să meargă împotriva Madianului și să împlinească răzbunarea DOMNULUI împotriva Madianului.",
    "Câte o mie de bărbați din fiecare seminție, din toate semințiile lui Israel, să trimiteți la război.”",
    "Au fost aleși din miile lui Israel câte o mie de fiecare seminție, adică douăsprezece mii de bărbați înarmați pentru război.",
    "Moise i-a trimis la război, câte o mie de fiecare seminție, pe ei și pe Fineas, fiul preotului Eleazar, care avea în mână uneltele Sfântului Lăcaș și trâmbițele de alarmă.",
    "Au luptat împotriva Madianului, cum îi poruncise DOMNUL lui Moise, și i-au ucis pe toți bărbații.",
    "I-au ucis pe împărații Madianului, pe lângă cei uciși de ei: pe Evi, pe Rekem, pe Țur, pe Hur și pe Reba, cei cinci împărați ai Madianului; l-au ucis cu sabia și pe Balaam, fiul lui Beor.",
    "Fiii lui Israel au luat captive pe femeile Madianului și pe copiii lor, și au luat ca pradă toate vitele lor, toate turmele lor și toate averile lor.",
    "Au ars cu foc toate cetățile în care locuiau și toate taberele lor.",
    "Au luat toată prada și tot dobândul, atât oameni, cât și animale;",
    "și i-au adus lui Moise, preotului Eleazar și întregii adunări a fiilor lui Israel pe prinși, prada și dobândul, în tabăra din câmpiile Moabului, care sunt lângă Iordan, în fața Ierihonului.",
    "Moise, preotul Eleazar și toate căpeteniile adunării le-au ieșit în întâmpinare afară din tabără.",
    "Dar Moise s-a mâniat pe fruntașii oștirii, pe căpeteniile miilor și pe căpeteniile sutelor care se întorceau de la război.",
    "Moise le-a zis: „Ați lăsat vii pe toate femeile?",
    "Iată că ele au fost cele care, la sfatul lui Balaam, i-au făcut pe fiii lui Israel să săvârșească o abatere împotriva DOMNULUI în lucrul lui Peor, și a urmat urgia în adunarea DOMNULUI.",
    "Acum ucideți pe orice băiat dintre copii și ucideți pe orice femeie care a cunoscut un bărbat culcându-se cu el.",
    "Dar pe toate fetele tinere care nu au cunoscut împreunarea cu bărbat lăsați-le vii pentru voi.",
    "Iar voi rămâneți șapte zile afară din tabără; oricine a ucis un om și oricine s-a atins de un mort să se curățească în ziua a treia și în ziua a șaptea, voi și prinșii voștri.",
    "Să curățiți de asemenea orice haină, orice unealtă de piele, orice lucrare de păr de capră și orice vas de lemn.”",
    "Preotul Eleazar le-a spus bărbaților din oștire care merseseră la război: „Aceasta este orânduiala legii pe care a poruncit-o DOMNUL lui Moise:",
    "aurul, argintul, arama, fierul, cositorul și plumbul,",
    "tot ce poate îndura focul să le treceți prin foc și vor fi curate; totuși să fie curățite și cu apa de curățire; iar tot ce nu poate îndura focul să-l treceți prin apă.",
    "Să vă spălați hainele în ziua a șaptea și veți fi curați; după aceea veți putea intra în tabără.”",
    "DOMNUL i-a vorbit lui Moise, spunând:",
    "„Fă numărătoarea prăzii luate, atât oameni, cât și animale, tu, preotul Eleazar și capetele caselor părintești ale adunării.",
    "Și împarte prada în două între luptătorii care au mers la război și toată adunarea.",
    "Să iei ca dregătorie pentru DOMNUL de la oamenii de război care au mers la luptă: câte un suflet din cinci sute, atât din oameni, cât și din boi, din măgari și din oi;",
    "să le iei din jumătatea lor și să le dai preotului Eleazar ca prinos ridicat pentru DOMNUL.",
    "Iar din jumătatea fiilor lui Israel să iei câte una din cincizeci, atât din oameni, cât și din boi, din măgari, din oi și din toate animalele, și să le dai leviților care păzesc Cortul DOMNULUI.”",
    "Moise și preotul Eleazar au făcut cum îi poruncise DOMNUL lui Moise.",
    "Prada, adică restul prăzii pe care o luaseră oamenii de război, a fost de: șase sute șaptezeci și cinci de mii de oi,",
    "șaptezeci și două de mii de taurini,",
    "șaizeci și una de mii de măgari,",
    "și treizeci și două de mii de suflete omenești, adică femei care nu cunoscuseră împreunarea cu bărbat.",
    "Jumătatea cuvenită celor ce merseseră la război a fost de: trei sute treizeci și șapte de mii cinci sute de oi,",
    "dintre care datoria pentru DOMNUL a fost de șase sute șaptezeci și cinci de oi;",
    "treizeci și șase de mii de taurini, dintre care datoria pentru DOMNUL a fost de șaptezeci și doi;",
    "treizeci de mii cinci sute de măgari, dintre care datoria pentru DOMNUL a fost de șaizeci și unul;",
    "și șaisprezece mii de suflete omenești, dintre care datoria pentru DOMNUL a fost de treizeci și două de suflete.",
    "Moise i-a dat preotului Eleazar datoria prinosului ridicat pentru DOMNUL, așa cum îi poruncise DOMNUL lui Moise.",
    "Jumătatea fiilor lui Israel, pe care o despărțise Moise de a oamenilor de război,",
    "jumătatea cuvenită adunării a fost de: trei sute treizeci și șapte de mii cinci sute de oi,",
    "treizeci și șase de mii de taurini,",
    "treizeci de mii cinci sute de măgari,",
    "și șaisprezece mii de suflete omenești.",
    "Din jumătatea fiilor lui Israel Moise a luat câte una din cincizeci, atât din oameni, cât și din animale, și le-a dat leviților care păzeau Cortul DOMNULUI, așa cum îi poruncise DOMNUL lui Moise.",
    "Fruntașii care erau peste miile oștirii, căpeteniile miilor și căpeteniile sutelor s-au apropiat de Moise",
    "și i-au zis lui Moise: „Robii tăi au făcut numărătoarea oamenilor de război care erau sub porunca noastră și nu lipsește niciun om dintre noi.",
    "De aceea aducem ca ofrandă DOMNULUI ce a găsit fiecare din noi în obiecte de aur: lanțuri de picioare, brățări, inele, cercei și salbe, ca să se facă ispășire pentru sufletele noastre înaintea DOMNULUI.”",
    "Moise și preotul Eleazar au luat de la ei aurul, toate obiectele lucrate.",
    "Tot aurul prinosului ridicat pe care l-au adus DOMNULUI căpeteniile miilor și căpeteniile sutelor a fost de șaisprezece mii șapte sute cincizeci de șecheli.",
    "Oamenii din oștire luaseră fiecare pradă pentru sine.",
    "Moise și preotul Eleazar au luat aurul de la căpeteniile miilor și ale sutelor și l-au dus în Cortul Întâlnirii, ca aducere aminte pentru fiii lui Israel înaintea DOMNULUI.",
  ],
}
