/*
 * Textul biblic al cărții Numeri, capitolul 1.
 *
 * Sursa: Biblia Emanus (BE), docs/data/biblia-emanus/NUM.1.json.
 * Capitol cu status "published", auditat verset cu verset din WLC-OSHB,
 * cu WEBU ca bază public-domain. 54 de versete.
 */

export const NUMERI_TEXT_1: Record<number, readonly string[]> = {
  1: [
    "DOMNUL i-a vorbit lui Moise în pustia Sinai, în Cortul Întâlnirii, în prima zi a lunii a doua, în al doilea an după ieșirea lor din țara Egiptului, spunând:",
    "„Faceți recensământul întregii adunări a fiilor lui Israel, după familiile lor, după casele părinților lor, numărând pe capete toate persoanele de sex masculin, unul câte unul,",
    "de la vârsta de douăzeci de ani în sus, toți cei din Israel buni de mers la război. Tu și Aaron să-i numărați după oștirile lor.",
    "Cu voi să fie câte un bărbat din fiecare seminție, fiecare fiind cap al casei părinților săi.",
    "Acestea sunt numele bărbaților care vor sta cu voi: Din Ruben: Elizur, fiul lui Şedeur;",
    "din Simeon: Şelumiel, fiul lui Ţurişadai;",
    "din Iuda: Nahşon, fiul lui Amminadab;",
    "din Isahar: Netanel, fiul lui Ţuar;",
    "din Zabulon: Eliab, fiul lui Helon;",
    "din fiii lui Iosif: din Efraim: Elişama, fiul lui Ammihud; din Manase: Gamaliel, fiul lui Pedațur;",
    "din Beniamin: Abidan, fiul lui Gideoni;",
    "din Dan: Ahiezer, fiul lui Ammişadai;",
    "din Aşer: Paghiel, fiul lui Ocran;",
    "din Gad: Eliasaf, fiul lui Deuel;",
    "din Neftali: Ahira, fiul lui Enan.”",
    "Aceștia sunt cei chemați din adunare, fruntașii semințiilor părinților lor, căpeteniile miilor lui Israel.",
    "Moise și Aaron i-au luat pe acești bărbați care fuseseră desemnați pe nume",
    "și au strâns toată adunarea în prima zi a lunii a doua. Ei și-au declarat originea după familiile lor, după casele părinților lor, numărând numele de la douăzeci de ani în sus, pe capete,",
    "așa cum îi poruncise DOMNUL lui Moise. Şi i-a numărat în pustia Sinai.",
    "Fiii lui Ruben, întâiul născut al lui Israel, urmașii lor după familiile lor, după casele părinților lor, numărând numele pe capete, toți bărbații de la douăzeci de ani în sus, buni de mers la război:",
    "cei numărați din seminția lui Ruben au fost patruzeci și șase de mii cinci sute.",
    "Din fiii lui Simeon, urmașii lor după familiile lor, după casele părinților lor, cei numărați pe capete, toți bărbații de la douăzeci de ani în sus, buni de mers la război:",
    "cei numărați din seminția lui Simeon au fost cincizeci și nouă de mii trei sute.",
    "Din fiii lui Gad, urmașii lor după familiile lor, după casele părinților lor, numărând numele de la douăzeci de ani în sus, toți buni de mers la război:",
    "cei numărați din seminția lui Gad au fost patruzeci și cinci de mii șase sute cincizeci.",
    "Din fiii lui Iuda, urmașii lor după familiile lor, după casele părinților lor, numărând numele de la douăzeci de ani în sus, toți buni de mers la război:",
    "cei numărați din seminția lui Iuda au fost șaptezeci și patru de mii șase sute.",
    "Din fiii lui Isahar, urmașii lor după familiile lor, după casele părinților lor, numărând numele de la douăzeci de ani în sus, toți buni de mers la război:",
    "cei numărați din seminția lui Isahar au fost cincizeci și patru de mii patru sute.",
    "Din fiii lui Zabulon, urmașii lor după familiile lor, după casele părinților lor, numărând numele de la douăzeci de ani în sus, toți buni de mers la război:",
    "cei numărați din seminția lui Zabulon au fost cincizeci și șapte de mii patru sute.",
    "Din fiii lui Iosif: din fiii lui Efraim, urmașii lor după familiile lor, după casele părinților lor, numărând numele de la douăzeci de ani în sus, toți buni de mers la război:",
    "cei numărați din seminția lui Efraim au fost patruzeci de mii cinci sute.",
    "Din fiii lui Manase, urmașii lor după familiile lor, după casele părinților lor, numărând numele de la douăzeci de ani în sus, toți buni de mers la război:",
    "cei numărați din seminția lui Manase au fost treizeci și două de mii două sute.",
    "Din fiii lui Beniamin, urmașii lor după familiile lor, după casele părinților lor, numărând numele de la douăzeci de ani în sus, toți buni de mers la război:",
    "cei numărați din seminția lui Beniamin au fost treizeci și cinci de mii patru sute.",
    "Din fiii lui Dan, urmașii lor după familiile lor, după casele părinților lor, numărând numele de la douăzeci de ani în sus, toți buni de mers la război:",
    "cei numărați din seminția lui Dan au fost șaizeci și două de mii șapte sute.",
    "Din fiii lui Aşer, urmașii lor după familiile lor, după casele părinților lor, numărând numele de la douăzeci de ani în sus, toți buni de mers la război:",
    "cei numărați din seminția lui Aşer au fost patruzeci și una de mii cinci sute.",
    "Din fiii lui Neftali, urmașii lor după familiile lor, după casele părinților lor, numărând numele de la douăzeci de ani în sus, toți buni de mers la război:",
    "cei numărați din seminția lui Neftali au fost cincizeci și trei de mii patru sute.",
    "Aceștia sunt cei numărați pe care i-au numărat Moise, Aaron și cele douăsprezece căpetenii ale lui Israel, fiecare fiind cap al casei părinților săi.",
    "Astfel, toți cei numărați dintre fiii lui Israel, după casele părinților lor, de la douăzeci de ani în sus, toți cei din Israel buni de mers la război,",
    "toți cei numărați au fost șase sute trei mii cinci sute cincizeci.",
    "Dar leviții, după seminția părinților lor, nu au fost numărați împreună cu ei.",
    "Căci DOMNUL îi vorbise lui Moise, spunând:",
    "„Să nu faci recensământul seminției lui Levi și să nu le numări capetele în mijlocul fiilor lui Israel;",
    "ci rânduieşte-i pe leviți peste Cortul Mărturiei, peste toate uneltele lui și peste tot ce aparține de el. Ei vor purta Cortul și toate uneltele lui, vor sluji în el și vor tăbărî în jurul Cortului.",
    "Când Cortul va trebui să pornească, leviții să-l strângă; iar când Cortul va trebui să fie aşezat, leviții să-l ridice. Străinul care se va apropia să fie dat la moarte.",
    "Fiii lui Israel își vor aşeza corturile fiecare în tabăra lui și fiecare lângă steagul lui, după oștirile lor.",
    "Dar leviții să tăbărască în jurul Cortului Mărturiei, ca să nu vină mânia peste adunarea fiilor lui Israel. Leviții vor avea paza Cortului Mărturiei.”",
    "Fiii lui Israel au făcut întocmai; au făcut după tot ce-i poruncise DOMNUL lui Moise.",
  ],
}
