/*
 * Textul biblic al cărții Numeri, capitolul 7.
 *
 * Sursa: Biblia Emanus (BE), docs/data/biblia-emanus/NUM.7.json.
 * Capitol cu status "published", auditat verset cu verset din WLC-OSHB,
 * cu WEBU ca bază public-domain. 89 de versete.
 */

export const NUMERI_TEXT_7: Record<number, readonly string[]> = {
  7: [
    "În ziua în care Moise a ispărăvit de ridicat Cortul, l-a uns și l-a sfințit împreună cu toate uneltele lui, și altarul cu toate uneltele lui, după ce le-a uns și le-a sfințit,",
    "fruntaşii lui Israel, căpeteniile caselor părinților lor — care erau căpeteniile semințiilor și stăteau în fruntea celor numărați — au adus ofrande.",
    "Ei și-au adus ofranda înaintea DOMNULUI: șase cărucioare acoperite și doisprezece boi, câte un cărucior de la două căpetenii și câte un bou de la fiecare căpetenie; și le-au adus înaintea Cortului.",
    "DOMNUL i-a vorbit lui Moise, spunând:",
    "„Ia-le de la ei ca să fie folosite la slujba Cortului Întâlnirii; să le dai leviților, fiecăruia după slujba lui.”",
    "Moise a luat căruciorele și boii și i-a dat leviților.",
    "Două cărucioare și patru boi i-a dat fiilor lui Gherşon, după slujba lor.",
    "Patru cărucioare și opt boi i-a dat fiilor lui Merari, după slujba lor, sub supravegherea lui Itamar, fiul preotului Aaron.",
    "Dar fiilor lui Chehat nu le-a dat niciunul, pentru că slujba Sfântului Lăcaş care le revenea era să poarte lucrurile sfinte pe umeri.",
    "Căpeteniile au adus ofranda pentru sfințirea altarului în ziua în care a fost uns; căpeteniile și-au adus ofranda înaintea altarului.",
    "DOMNUL i-a spus lui Moise: „Câte o căpetenie pe zi să-și aducă ofranda pentru sfințirea altarului.”",
    "Cel ce și-a adus ofranda în prima zi a fost Nahşon, fiul lui Amminadab, din seminția lui Iuda.",
    "Ofranda lui a fost: un potir de argint în greutate de o sută treizeci de şecheli, un potir de stropit de argint de șaptezeci de şecheli, după şechelul Sfântului Lăcaş, ambele pline cu făină aleasă frământată cu ulei pentru un dar de cereale;",
    "o lingură de aur de zece şecheli, plină cu tămâie;",
    "un taur tânăr, un berbec, un miel de un an pentru arderea-de-tot;",
    "un țap pentru jertfa de păcat;",
    "iar pentru jertfa de pace: doi boi, cinci berbeci, cinci țapi, cinci miei de un an. Aceasta a fost ofranda lui Nahşon, fiul lui Amminadab.",
    "În ziua a doua a adus ofrandă Netanel, fiul lui Ţuar, căpetenia lui Isahar.",
    "A adus ca ofrandă: un potir de argint în greutate de o sută treizeci de şecheli, un potir de stropit de argint de șaptezeci de şecheli, după şechelul Sfântului Lăcaş, ambele pline cu făină aleasă frământată cu ulei pentru un dar de cereale;",
    "o lingură de aur de zece şecheli, plină cu tămâie;",
    "un taur tânăr, un berbec, un miel de un an pentru arderea-de-tot;",
    "un țap pentru jertfa de păcat;",
    "iar pentru jertfa de pace: doi boi, cinci berbeci, cinci țapi, cinci miei de un an. Aceasta a fost ofranda lui Netanel, fiul lui Ţuar.",
    "În ziua a treia, căpetenia fiilor lui Zabulon, Eliab, fiul lui Helon.",
    "Ofranda lui a fost: un potir de argint de o sută treizeci de şecheli, un potir de stropit de argint de șaptezeci de şecheli, după şechelul Sfântului Lăcaş, ambele pline cu făină aleasă frământată cu ulei pentru un dar de cereale;",
    "o lingură de aur de zece şecheli, plină cu tămâie;",
    "un taur tânăr, un berbec, un miel de un an pentru arderea-de-tot;",
    "un țap pentru jertfa de păcat;",
    "iar pentru jertfa de pace: doi boi, cinci berbeci, cinci țapi, cinci miei de un an. Aceasta a fost ofranda lui Eliab, fiul lui Helon.",
    "În ziua a patra, căpetenia fiilor lui Ruben, Elizur, fiul lui Şedeur.",
    "Ofranda lui a fost: un potir de argint de o sută treizeci de şecheli, un potir de stropit de argint de șaptezeci de şecheli, după şechelul Sfântului Lăcaş, ambele pline cu făină aleasă frământată cu ulei pentru un dar de cereale;",
    "o lingură de aur de zece şecheli, plină cu tămâie;",
    "un taur tânăr, un berbec, un miel de un an pentru arderea-de-tot;",
    "un țap pentru jertfa de păcat;",
    "iar pentru jertfa de pace: doi boi, cinci berbeci, cinci țapi, cinci miei de un an. Aceasta a fost ofranda lui Elizur, fiul lui Şedeur.",
    "În ziua a cincea, căpetenia fiilor lui Simeon, Şelumiel, fiul lui Ţurişadai.",
    "Ofranda lui a fost: un potir de argint de o sută treizeci de şecheli, un potir de stropit de argint de șaptezeci de şecheli, după şechelul Sfântului Lăcaş, ambele pline cu făină aleasă frământată cu ulei pentru un dar de cereale;",
    "o lingură de aur de zece şecheli, plină cu tămâie;",
    "un taur tânăr, un berbec, un miel de un an pentru arderea-de-tot;",
    "un țap pentru jertfa de păcat;",
    "iar pentru jertfa de pace: doi boi, cinci berbeci, cinci țapi, cinci miei de un an. Aceasta a fost ofranda lui Şelumiel, fiul lui Ţurişadai.",
    "În ziua a șasea, căpetenia fiilor lui Gad, Eliasaf, fiul lui Deuel.",
    "Ofranda lui a fost: un potir de argint de o sută treizeci de şecheli, un potir de stropit de argint de șaptezeci de şecheli, după şechelul Sfântului Lăcaş, ambele pline cu făină aleasă frământată cu ulei pentru un dar de cereale;",
    "o lingură de aur de zece şecheli, plină cu tămâie;",
    "un taur tânăr, un berbec, un miel de un an pentru arderea-de-tot;",
    "un țap pentru jertfa de păcat;",
    "iar pentru jertfa de pace: doi boi, cinci berbeci, cinci țapi, cinci miei de un an. Aceasta a fost ofranda lui Eliasaf, fiul lui Deuel.",
    "În ziua a șaptea, căpetenia fiilor lui Efraim, Elişama, fiul lui Ammihud.",
    "Ofranda lui a fost: un potir de argint de o sută treizeci de şecheli, un potir de stropit de argint de șaptezeci de şecheli, după şechelul Sfântului Lăcaş, ambele pline cu făină aleasă frământată cu ulei pentru un dar de cereale;",
    "o lingură de aur de zece şecheli, plină cu tămâie;",
    "un taur tânăr, un berbec, un miel de un an pentru arderea-de-tot;",
    "un țap pentru jertfa de păcat;",
    "iar pentru jertfa de pace: doi boi, cinci berbeci, cinci țapi, cinci miei de un an. Aceasta a fost ofranda lui Elişama, fiul lui Ammihud.",
    "În ziua a opta, căpetenia fiilor lui Manase, Gamaliel, fiul lui Pedațur.",
    "Ofranda lui a fost: un potir de argint de o sută treizeci de şecheli, un potir de stropit de argint de șaptezeci de şecheli, după şechelul Sfântului Lăcaş, ambele pline cu făină aleasă frământată cu ulei pentru un dar de cereale;",
    "o lingură de aur de zece şecheli, plină cu tămâie;",
    "un taur tânăr, un berbec, un miel de un an pentru arderea-de-tot;",
    "un țap pentru jertfa de păcat;",
    "iar pentru jertfa de pace: doi boi, cinci berbeci, cinci țapi, cinci miei de un an. Aceasta a fost ofranda lui Gamaliel, fiul lui Pedațur.",
    "În ziua a noua, căpetenia fiilor lui Beniamin, Abidan, fiul lui Gideoni.",
    "Ofranda lui a fost: un potir de argint de o sută treizeci de şecheli, un potir de stropit de argint de șaptezeci de şecheli, după şechelul Sfântului Lăcaş, ambele pline cu făină aleasă frământată cu ulei pentru un dar de cereale;",
    "o lingură de aur de zece şecheli, plină cu tămâie;",
    "un taur tânăr, un berbec, un miel de un an pentru arderea-de-tot;",
    "un țap pentru jertfa de păcat;",
    "iar pentru jertfa de pace: doi boi, cinci berbeci, cinci țapi, cinci miei de un an. Aceasta a fost ofranda lui Abidan, fiul lui Gideoni.",
    "În ziua a zecea, căpetenia fiilor lui Dan, Ahiezer, fiul lui Ammişadai.",
    "Ofranda lui a fost: un potir de argint de o sută treizeci de şecheli, un potir de stropit de argint de șaptezeci de şecheli, după şechelul Sfântului Lăcaş, ambele pline cu făină aleasă frământată cu ulei pentru un dar de cereale;",
    "o lingură de aur de zece şecheli, plină cu tămâie;",
    "un taur tânăr, un berbec, un miel de un an pentru arderea-de-tot;",
    "un țap pentru jertfa de păcat;",
    "iar pentru jertfa de pace: doi boi, cinci berbeci, cinci țapi, cinci miei de un an. Aceasta a fost ofranda lui Ahiezer, fiul lui Ammişadai.",
    "În ziua a unsprezecea, căpetenia fiilor lui Aşer, Paghiel, fiul lui Ocran.",
    "Ofranda lui a fost: un potir de argint de o sută treizeci de şecheli, un potir de stropit de argint de șaptezeci de şecheli, după şechelul Sfântului Lăcaş, ambele pline cu făină aleasă frământată cu ulei pentru un dar de cereale;",
    "o lingură de aur de zece şecheli, plină cu tămâie;",
    "un taur tânăr, un berbec, un miel de un an pentru arderea-de-tot;",
    "un țap pentru jertfa de păcat;",
    "iar pentru jertfa de pace: doi boi, cinci berbeci, cinci țapi, cinci miei de un an. Aceasta a fost ofranda lui Paghiel, fiul lui Ocran.",
    "În ziua a douăsprezecea, căpetenia fiilor lui Neftali, Ahira, fiul lui Enan.",
    "Ofranda lui a fost: un potir de argint de o sută treizeci de şecheli, un potir de stropit de argint de șaptezeci de şecheli, după şechelul Sfântului Lăcaş, ambele pline cu făină aleasă frământată cu ulei pentru un dar de cereale;",
    "o lingură de aur de zece şecheli, plină cu tămâie;",
    "un taur tânăr, un berbec, un miel de un an pentru arderea-de-tot;",
    "un țap pentru jertfa de păcat;",
    "iar pentru jertfa de pace: doi boi, cinci berbeci, cinci țapi, cinci miei de un an. Aceasta a fost ofranda lui Ahira, fiul lui Enan.",
    "Aceasta a fost darul de sfințire a altarului din partea căpeteniilor lui Israel în ziua în care a fost uns: douăsprezece potire de argint, douăsprezece potire de stropit de argint, douăsprezece linguri de aur;",
    "fiecare potir de argint cântărea o sută treizeci de şecheli, și fiecare potir de stropit șaptezeci de şecheli; tot argintul vaselor a fost de două mii patru sute de şecheli, după şechelul Sfântului Lăcaş;",
    "cele douăsprezece linguri de aur pline cu tămâie cântăreau zece şecheli fiecare, după şechelul Sfântului Lăcaş; tot aurul lingurilor a fost de o sută douăzeci de şecheli;",
    "toți boii pentru arderea-de-tot au fost douăsprezece tauri, berbecii douăsprezece, mieii de un an douăsprezece, împreună cu ofranda lor de mâncare; iar țapii pentru jertfa de păcat, douăsprezece;",
    "iar toți boii pentru jertfa de pace au fost douăzeci și patru de taurini, berbecii șaizeci, țapii șaizeci, mieii de un an șaizeci. Aceasta a fost ofranda de sfințire a altarului după ce a fost uns.",
    "Când Moise intra în Cortul Întâlnirii ca să vorbească cu DOMNUL, auzea Glasul vorbindu-i de pe capacul ispăşirii care era peste chivotul mărturiei, dintre cei doi heruvimi; și vorbea cu El.",
  ],
}
