/*
 * Textul biblic al cărții Numeri, capitolul 33.
 *
 * Sursa: Biblia Emanus (BE), docs/data/biblia-emanus/NUM.33.json.
 * Capitol cu status "published", auditat verset cu verset din WLC-OSHB,
 * cu WEBU ca bază public-domain. 56 de versete.
 */

export const NUMERI_TEXT_33: Record<number, readonly string[]> = {
  33: [
    "Acestea sunt popasurile fiilor lui Israel care au ieșit din țara Egiptului după oștirile lor, sub conducerea lui Moise și a lui Aaron.",
    "Moise a scris locurile lor de plecare, popas după popas, după porunca DOMNULUI; și acestea sunt popasurile lor după plecările lor:",
    "Au pornit din Rameses în luna întâi, în ziua a cincisprezecea a lunii întâi. În ziua de după Paște fiii lui Israel au ieșit cu mână înaltă, sub ochii tuturor egiptenilor,",
    "pe când egiptenii îi îngropau pe toți întâii lor născuți pe care-i lovise DOMNUL; DOMNUL executase judecăți și împotriva zeilor lor.",
    "Fiii lui Israel au pornit din Rameses și au tăbărât la Sucot.",
    "Au pornit din Sucot și au tăbărât la Etam, care este la marginea pustiei.",
    "Au pornit din Etam, s-au întors spre Pi-Hahirot, care este în fața Baal-Țefonului, și au tăbărât în fața Migdolului.",
    "Au pornit din fața Hahirotului, au trecut prin mijlocul mării spre pustie, au mers cale de trei zile în pustia Etam și au tăbărât la Mara.",
    "Au pornit din Mara și au ajuns la Elim: la Elim erau douăsprezece izvoare de apă și șaptezeci de curmali; și au tăbărât acolo.",
    "Au pornit din Elim și au tăbărât lângă Marea Roșie.",
    "Au pornit de la Marea Roșie și au tăbărât în pustia Sin.",
    "Au pornit din pustia Sin și au tăbărât la Dofca.",
    "Au pornit din Dofca și au tăbărât la Aluș.",
    "Au pornit din Aluș și au tăbărât la Refidim, unde poporul nu a avut apă de băut.",
    "Au pornit din Refidim și au tăbărât în pustia Sinai.",
    "Au pornit din pustia Sinai și au tăbărât la Chibrot-Hataava.",
    "Au pornit din Chibrot-Hataava și au tăbărât la Hațerot.",
    "Au pornit din Hațerot și au tăbărât la Ritma.",
    "Au pornit din Ritma și au tăbărât la Rimon-Pereț.",
    "Au pornit din Rimon-Pereț și au tăbărât la Libna.",
    "Au pornit din Libna și au tăbărât la Risa.",
    "Au pornit din Risa și au tăbărât la Kehelata.",
    "Au pornit din Kehelata și au tăbărât la muntele Șefer.",
    "Au pornit de la muntele Șefer și au tăbărât la Harada.",
    "Au pornit din Harada și au tăbărât la Machilot.",
    "Au pornit din Machilot și au tăbărât la Tahat.",
    "Au pornit din Tahat și au tăbărât la Terah.",
    "Au pornit din Terah și au tăbărât la Mitca.",
    "Au pornit din Mitca și au tăbărât la Hașmona.",
    "Au pornit din Hașmona și au tăbărât la Moserot.",
    "Au pornit din Moserot și au tăbărât la Bene-Iaacan.",
    "Au pornit din Bene-Iaacan și au tăbărât la Hor-Hagidgad.",
    "Au pornit din Hor-Hagidgad și au tăbărât la Iotbata.",
    "Au pornit din Iotbata și au tăbărât la Abrona.",
    "Au pornit din Abrona și au tăbărât la Ețion-Geber.",
    "Au pornit din Ețion-Geber și au tăbărât în pustia Țin, adică la Cadeș.",
    "Au pornit din Cadeș și au tăbărât la muntele Hor, la marginea țării Edomului.",
    "Preotul Aaron s-a suit pe muntele Hor la porunca DOMNULUI și a murit acolo în al patruzecilea an de la ieșirea fiilor lui Israel din țara Egiptului, în luna a cincea, în prima zi a lunii.",
    "Aaron era de o sută douăzeci și trei de ani când a murit pe muntele Hor.",
    "Canaanitul, împăratul Aradului, care locuia în Negev, în țara Canaanului, a auzit de sosirea fiilor lui Israel.",
    "Au pornit de la muntele Hor și au tăbărât la Țalmona.",
    "Au pornit din Țalmona și au tăbărât la Punon.",
    "Au pornit din Punon și au tăbărât la Obot.",
    "Au pornit din Obot și au tăbărât la Iie-Abarim, la hotarul Moabului.",
    "Au pornit din Iim și au tăbărât la Dibon-Gad.",
    "Au pornit din Dibon-Gad și au tăbărât la Almon-Diblataim.",
    "Au pornit din Almon-Diblataim și au tăbărât în munții Abarim, în fața Neboului.",
    "Au pornit din munții Abarim și au tăbărât în câmpiile Moabului, lângă Iordan, în fața Ierihonului.",
    "Au tăbărât lângă Iordan, de la Bet-Ieșimot până la Abel-Șitim, în câmpiile Moabului.",
    "DOMNUL i-a vorbit lui Moise în câmpiile Moabului, lângă Iordan, în fața Ierihonului, spunând:",
    "„Spune-le fiilor lui Israel și vorbește-le: Când veți trece Iordanul în țara Canaanului,",
    "să-i izgoniți dinaintea voastră pe toți locuitorii țării, să le nimiciți toate icoanele de piatră, să le nimiciți toate chipurile turnate și să le dărâmați toate înălțimile.",
    "Să luați țara în stăpânire și să locuiți în ea, căci vouă v-am dat țara ca să o moșteniți.",
    "Să împărțiți țara prin sorți ca moștenire după familiile voastre: celor mai numeroși să le dați o moștenire mai mare, iar celor mai puțini o moștenire mai mică. Fiecăruia unde-i va cădea sorțul, aceea va fi a lui; o veți moșteni după semințiile părinților voștri.",
    "Dar dacă nu-i veți izgoni pe locuitorii țării dinaintea voastră, cei ce veți lăsa dintre ei vă vor fi ca niște spini în ochi și ca niște ghimpi în coaste și vă vor hărțui în țara în care veți locui.",
    "Și cum gândisem să le fac lor, așa vă voi face vouă.”",
  ],
}
