export const VT_MINOR_PROPHETS_FULL = {
  osea:{verseCounts:{1:11,2:23,3:5,4:19,5:15,6:11,7:16,8:14,9:17,10:15,11:12,12:14,13:16,14:9},narratives:{
    1:{title:"Căsătoria lui Osea și numele copiilor ca semne",summary:"Osea primește o căsătorie care devine semn viu al infidelității lui Israel. Copiii primesc nume profetice — Izreel, Lo-Ruhama și Lo-Ami — care anunță judecată, lipsa milei și ruptura relației, dar finalul capitolului deschide deja perspectiva restaurării."},
    2:{title:"Infidelitate, disciplină și o nouă logodnă",summary:"Israel este confruntat pentru că a atribuit amanților săi darurile primite de la Dumnezeu și a folosit belșugul pentru Baal. Dumnezeu spune că îi va bloca drumurile, dar apoi o va atrage din nou în pustiu și va vorbi inimii ei, promițând o nouă logodnă în dreptate, bunătate și credincioșie."},
    3:{title:"Osea cumpără din nou femeia iubită",summary:"Prorocul primește porunca să iubească din nou o femeie iubită de altul și o cumpără pentru a o readuce într-o relație de fidelitate. Gestul este explicat ca imagine a lui Israel care va trece printr-o perioadă fără rege și cult, apoi se va întoarce spre DOMNUL."},
    4:{title:"Lipsa cunoașterii lui Dumnezeu și vina preoților",summary:"Dumnezeu are un proces cu țara pentru că nu mai există adevăr, bunătate și cunoaștere de Dumnezeu, iar violența și adulterul se înmulțesc. Preoții, chemați să păstreze cunoașterea, sunt acuzați că au respins-o și că se hrănesc din păcatul poporului."},
    5:{title:"Judecata asupra conducătorilor și retragerea lui Dumnezeu",summary:"Preoții, casa regală și Israel sunt chemați să audă verdictul asupra idolatriei și mândriei lor. Alianțele politice nu pot vindeca rana, iar Dumnezeu spune că Se va retrage până când poporul își va recunoaște vina și Îl va căuta."},
    6:{title:"Întoarcere superficială și bunătatea pe care Dumnezeu o dorește",summary:"Poporul vorbește despre întoarcere și vindecare, dar bunătatea lui este ca norul dimineții care dispare repede. Dumnezeu declară că dorește bunătate statornică și cunoașterea Lui mai mult decât simple jertfe, în timp ce preoții și cetățile continuă violența."},
    7:{title:"O inimă ca un cuptor și o politică fără întoarcere",summary:"În timp ce Dumnezeu ar vrea să vindece Israelul, fărădelegea iese din nou la suprafață. Regele și conducătorii sunt prinși în intrigi, poporul caută Egiptul și Asiria ca un porumbel fără pricepere și îmbătrânește spiritual fără să se întoarcă spre Dumnezeu."},
    8:{title:"Au semănat vânt și vor secera furtună",summary:"Israel a pus regi fără Dumnezeu, a făcut idoli din argint și aur și a transformat vițelul Samariei într-un centru de închinare. Încrederea în alianțe și altare se întoarce împotriva poporului, iar Legea este tratată ca ceva străin."},
    9:{title:"Bucuria se stinge în exil",summary:"Israel nu mai este chemat să se bucure ca popoarele, pentru că a părăsit pe Dumnezeu și a iubit plata idolatriei. Osea amintește episoadele de la Ghibea și Baal-Peor și descrie pierderea rodului și împrăștierea care vine."},
    10:{title:"Vița roditoare folosește rodul pentru altare",summary:"Cu cât Israel a avut mai mult rod, cu atât și-a înmulțit altarele și stâlpii, iar inima împărțită este găsită vinovată. Vițelul Samariei va fi dus, iar poporul este chemat să semene dreptate și să caute pe DOMNUL înainte să vină judecata."},
    11:{title:"Când Israel era copil, l-am iubit",summary:"Dumnezeu își amintește chemarea lui Israel din Egipt și grija părintească prin care l-a învățat să umble, dar poporul a fugit spre Baali. În mijlocul verdictului, inima lui Dumnezeu este descrisă ca întorcându-se înăuntrul Lui și mila biruind impulsul distrugerii totale."},
    12:{title:"Iacov, balanțele false și chemarea la întoarcere",summary:"Istoria lui Iacov este folosită pentru a chema urmașii lui să se întoarcă, păstrând bunătatea și dreptatea și așteptând pe Dumnezeu. Efraim este asemănat cu un negustor cu balanțe false care se laudă că s-a îmbogățit fără vină."},
    13:{title:"De la Baal la moarte, dar puterea răscumpărării rămâne",summary:"Efraim a avut cândva greutate, dar idolatria îl face să dispară ca roua și pleava. Dumnezeu amintește că El l-a cunoscut în pustiu, iar prosperitatea a dus la uitare; în mijlocul judecății apare întrebarea despre răscumpărarea din puterea mormântului."},
    14:{title:"Întoarce-te, Israele",summary:"Ultimul capitol oferă chiar cuvintele pocăinței: renunțarea la încrederea în Asiria, cai și idoli și cererea de iertare. Dumnezeu răspunde că va vindeca rătăcirea, va iubi de bunăvoie și va face Israelul să înflorească, iar cartea se încheie chemând pe cel înțelept să priceapă căile DOMNULUI."}
  }},
  ioel:{verseCounts:{1:20,2:32,3:21},narratives:{
    1:{title:"Invazia lăcustelor și chemarea la plâns",summary:"O calamitate nemaivăzută distruge viile, smochinii, grânele și pășunile, iar generațiile sunt chemate să povestească evenimentul mai departe. Preoții, agricultorii și întregul popor sunt chemați la doliu și post, pentru că Ziua DOMNULUI este aproape."},
    2:{title:"Ziua DOMNULUI, întoarcerea inimii și revărsarea Duhului",summary:"O armată devastatoare face țara să tremure, dar în mijlocul avertismentului Dumnezeu cheamă poporul să se întoarcă la El cu toată inima, rupând inima, nu doar hainele. După restaurarea recoltei, Dumnezeu promite să-Și toarne Duhul peste orice făptură și să ofere salvare celor ce cheamă Numele Lui."},
    3:{title:"Judecata națiunilor și restaurarea Sionului",summary:"Națiunile sunt chemate în valea judecății pentru felul în care au tratat poporul și țara lui Dumnezeu. Mulțimi se află în valea hotărârii, DOMNUL răcnește din Sion, iar finalul descrie Ierusalimul locuit și un izvor ieșind din Casa DOMNULUI."}
  }},
  amos:{verseCounts:{1:15,2:16,3:15,4:13,5:27,6:14,7:17,8:14,9:15},narratives:{
    1:{title:"Judecata începe cu națiunile din jur",summary:"Amos rostește oracole împotriva Damascului, Gazei, Tirului, Edomului și Amonului, repetând formula că pentru nelegiuiri repetate judecata nu va fi retrasă. Cruzimea în război, comerțul cu oameni și ura persistentă sunt între motivele enumerate."},
    2:{title:"Moab, Iuda și mai ales Israel",summary:"Judecata ajunge la Moab și Iuda, apoi se oprește mult mai amplu asupra Israelului. Vânzarea celui drept pentru bani, zdrobirea săracului, abuzul sexual și profanarea lucrurilor sfinte sunt puse în contrast cu harul exodului și al darului prorocilor."},
    3:{title:"Privilegiul legământului aduce răspundere",summary:"«Numai pe voi v-am cunoscut» este urmat nu de imunitate, ci de judecarea fărădelegilor. O serie de întrebări arată că efectul are o cauză, iar glasul prorocului vine pentru că DOMNUL a vorbit; Samaria este chemată să-și vadă violența și palatele pline de pradă."},
    4:{title:"Avertismente repetate fără întoarcere",summary:"Femeile bogate din Samaria sunt mustrate pentru asuprirea săracilor, iar închinarea de la Betel și Ghilgal este ironizată. Foametea, seceta, mana, lăcustele și alte lovituri sunt repetate cu refrenul că Israel tot nu s-a întors, culminând cu chemarea de a se pregăti să-L întâlnească pe Dumnezeu."},
    5:{title:"Căutați-Mă și veți trăi",summary:"Amos cântă o plângere asupra Israelului și îl cheamă să-L caute pe DOMNUL, nu sanctuarele devenite false refugii. Dumnezeu urăște sărbătorile și cântările lipsite de dreptate și cere ca judecata să curgă ca apa și dreptatea ca un râu."},
    6:{title:"Vai celor nepăsători din Sion și Samaria",summary:"Cei care se simt în siguranță, trăiesc în lux și nu se întristează de ruina lui Iosif sunt avertizați că vor merge în fruntea exilaților. Mândria și transformarea dreptății în otravă pregătesc ridicarea unei națiuni împotriva Israelului."},
    7:{title:"Lăcuste, foc, firul cu plumb și conflictul cu Amația",summary:"Amos vede lăcuste și foc și mijlocește, iar Dumnezeu oprește aceste două judecăți. A treia vedenie, firul cu plumb, anunță că măsurarea a ajuns; la Betel, preotul Amația îi cere lui Amos să plece, dar prorocul explică faptul că Dumnezeu l-a chemat de la turmă."},
    8:{title:"Coșul cu fructe coapte și foamete după Cuvânt",summary:"Un coș cu fructe de vară simbolizează faptul că sfârșitul a ajuns pentru Israel. Negustorii sunt acuzați că așteaptă sfârșitul sărbătorilor ca să înșele și să exploateze săracii, iar judecata include o foamete nu de pâine, ci de auzire a cuvintelor DOMNULUI."},
    9:{title:"Nimeni nu se ascunde, dar cortul lui David va fi ridicat",summary:"Dumnezeu este văzut lângă altar și declară că nimeni nu poate scăpa de privirea și judecata Lui, oriunde s-ar ascunde. Totuși casa lui Iacov nu este nimicită complet; finalul promite ridicarea cortului căzut al lui David și restaurarea țării."}
  }},
  obadia:{verseCounts:{1:21},narratives:{1:{title:"Mândria Edomului și ziua DOMNULUI",summary:"Edom se simte sigur în fortărețele sale și se laudă că nimeni nu-l poate coborî, dar Dumnezeu îi anunță că îl va da jos. Vina lui este legată și de felul în care a privit și a profitat de nenorocirea fratelui său Iacov; finalul proclamă că împărăția va fi a DOMNULUI."}}},
  iona:{verseCounts:{1:17,2:10,3:10,4:11},narratives:{
    1:{title:"Iona fuge de chemare",summary:"Dumnezeu îl trimite la Ninive, dar Iona coboară spre Iafo și se îmbarcă în direcția opusă. Furtuna îl expune, marinarii află de fuga lui, iar Iona este aruncat în mare; marea se liniștește și un pește mare îl înghite."},
    2:{title:"Rugăciunea din adânc",summary:"Din pântecele peștelui, Iona își descrie coborârea în ape și spre adâncuri, dar spune că și-a amintit de DOMNUL și rugăciunea lui a ajuns la templu. El contrastează idolii deșerți cu bunătatea lui Dumnezeu și mărturisește că mântuirea este a DOMNULUI."},
    3:{title:"A doua chemare și pocăința Ninivei",summary:"Cuvântul vine a doua oară, iar Iona merge la Ninive și proclamă apropiata răsturnare a cetății. De la oameni la rege, cetatea răspunde prin post, schimbarea comportamentului și speranță în mila lui Dumnezeu, iar judecata anunțată este oprită."},
    4:{title:"Iona se mânie pentru mila lui Dumnezeu",summary:"Prorocul recunoaște că tocmai caracterul milos al lui Dumnezeu fusese motivul pentru care fugise și se supără că Ninive a fost cruțată. Planta, viermele și vântul devin lecția prin care Dumnezeu îl confruntă: Iona are milă de plantă, dar nu de o cetate plină de oameni."}
  }},
  mica:{verseCounts:{1:16,2:13,3:12,4:13,5:15,6:16,7:20},narratives:{
    1:{title:"DOMNUL coboară, iar Samaria și Iuda sunt chemate la răspundere",summary:"Mica vede pe Dumnezeu coborând în judecată, munții topindu-se înaintea Lui. Samaria este numită direct pentru idolatrie, iar rana ajunge până la porțile Ierusalimului; prorocul plânge în timp ce enumeră cetăți afectate."},
    2:{title:"Cei care plănuiesc nedreptatea și promisiunea adunării",summary:"Vaiul cade asupra celor care noaptea planifică răul și dimineața îl execută pentru că au puterea, luând ogoare și case. Prorocii care vor mesaje plăcute sunt criticați, dar finalul promite că rămășița lui Iacov va fi adunată ca o turmă."},
    3:{title:"Conducători, preoți și proroci care exploatează",summary:"Liderii care ar trebui să cunoască dreptatea sunt descriși ca devorând poporul, iar prorocii își schimbă mesajul după ce primesc sau nu hrană. Mica se distinge prin putere, Duh și dreptate pentru a spune păcatul, iar Sionul este avertizat că poate ajunge un ogor arat."},
    4:{title:"Muntele DOMNULUI și pacea viitoare",summary:"În zilele de pe urmă, popoarele urcă spre muntele DOMNULUI pentru a învăța căile Lui, iar săbiile devin fiare de plug. Fiecare stă sub vița și smochinul său fără teamă, iar Dumnezeu adună pe cea șchioapă și alungată; apoi apar din nou durerile și conflictul prezent."},
    5:{title:"Conducătorul din Betleem",summary:"Din Betleem, mic între familiile lui Iuda, este promis un conducător ale cărui origini sunt din vechime și care va păstori în puterea DOMNULUI. Rămășița lui Iacov este descrisă atât ca rouă, cât și ca leu, iar Dumnezeu promite curățirea armelor, vrăjitoriei și idolilor."},
    6:{title:"Procesul lui Dumnezeu și ce cere El omului",summary:"DOMNUL își cheamă poporul la proces și întreabă ce i-a făcut, amintind exodul și conducerea dată. În fața întrebării despre jertfe tot mai mari, răspunsul este concentrarea pe dreptate, bunătate și umblare smerită cu Dumnezeu; cetatea este apoi mustrată pentru înșelăciune și violență."},
    7:{title:"Plângere, așteptare și Dumnezeul care iartă",summary:"Mica se simte ca după cules, fără rod bun în societate, unde violența și neîncrederea au pătruns chiar în familie. Totuși el spune că va privi spre DOMNUL și va aștepta mântuirea, iar finalul laudă pe Dumnezeul care iartă, nu ține mânia pentru totdeauna și aruncă păcatele în adâncul mării."}
  }},
  naum:{verseCounts:{1:15,2:13,3:19},narratives:{
    1:{title:"Dumnezeu este gelos, drept și totodată refugiu",summary:"Naum deschide cu caracterul lui Dumnezeu: încet la mânie, mare în putere și hotărât să nu lase răul nepedepsit. Creația tremură înaintea Lui, dar în aceeași scenă DOMNUL este bun și cetățuie în ziua necazului pentru cei care se refugiază în El."},
    2:{title:"Căderea Ninivei este descrisă ca o cetate luată cu asalt",summary:"Apărătorilor li se spune să se pregătească, dar carele, porțile râului și palatul intră în haos. Cetatea care fusese ca un bazin plin se golește, iar comoara este jefuită; vizuina leilor care hrănise puterea imperială este făcută pustie."},
    3:{title:"Cetatea sângelui și motivul ruinei",summary:"Ninive este numită cetate plină de minciună, jaf și sânge, iar imaginea luptei descrie mulțimea victimelor. Cruzimea și seducția imperială sunt expuse, iar exemple precum No-Amon arată că nicio cetate nu este prea puternică pentru judecată; rana Ninivei este declarată fără vindecare."}
  }},
  habacuc:{verseCounts:{1:17,2:20,3:19},narratives:{
    1:{title:"De ce tolerezi nedreptatea?",summary:"Habacuc începe întrebând cât timp va striga despre violență, conflict și Lege paralizată fără răspuns. Dumnezeu anunță ridicarea caldeenilor, iar prorocul formulează o a doua problemă: cum poate Dumnezeul sfânt folosi o națiune și mai violentă pentru judecată?"},
    2:{title:"Cel drept va trăi prin credincioșia lui",summary:"Prorocul se așază la strajă pentru răspuns, iar vedenia trebuie scrisă și așteptată chiar dacă pare să întârzie. Cel îngâmfat este pus în contrast cu cel drept, apoi cinci vaiuri denunță jaf, câștig nedrept, violență, umilirea altora și idolatria; finalul cere tăcere înaintea DOMNULUI în templul Lui."},
    3:{title:"De la teamă la bucurie fără recolte",summary:"Habacuc răspunde printr-o rugăciune poetică ce își amintește venirea puternică a lui Dumnezeu și intervențiile Sale în istorie. Deși trupul îi tremură la perspectiva invaziei, finalul declară că, chiar fără smochine, struguri, măsline, grâne, oi și vite, se va bucura în Dumnezeul mântuirii sale."}
  }},
  tefania:{verseCounts:{1:18,2:15,3:20},narratives:{
    1:{title:"Ziua DOMNULUI împotriva idolatriei și nepăsării",summary:"O judecată amplă este anunțată asupra lui Iuda pentru Baal, închinarea la astre, jurămintele amestecate și cei care s-au întors de la DOMNUL. Ziua DOMNULUI este aproape și este descrisă ca zi de mânie, întuneric și strâmtorare, iar argintul și aurul nu pot salva."},
    2:{title:"Căutați pe DOMNUL, voi cei smeriți",summary:"Înainte de împlinirea decretului, cei smeriți sunt chemați să caute pe DOMNUL, dreptatea și smerenia. Urmează oracole împotriva Filistiei, Moabului, Amonului, Cușului și Asiriei, iar Ninive cea sigură pe sine devine pustie."},
    3:{title:"Cetatea răzvrătită și poporul smerit restaurat",summary:"Ierusalimul este mustrat pentru conducători violenți, judecători lacomi, proroci ușuratici și preoți care profanează Legea. După judecata națiunilor, Dumnezeu promite buze curate, o rămășiță smerită și o scenă finală în care Se bucură cu cântare peste poporul restaurat."}
  }},
  hagai:{verseCounts:{1:15,2:23},narratives:{
    1:{title:"Este timpul să zidiți Casa",summary:"Poporul spune că vremea templului nu a venit, deși propriile case sunt finisate, iar Hagai îi cheamă să-și cerceteze căile. Lipsa rodului este legată de prioritățile lor, iar Zorobabel, Iosua și rămășița ascultă și încep lucrul."},
    2:{title:"Slava viitoare, curățirea și promisiunea pentru Zorobabel",summary:"Cei care își amintesc vechiul templu sunt încurajați să fie tari, pentru că Dumnezeu este cu ei și promite o slavă viitoare mai mare. O discuție cu preoții arată că necurăția se transmite mai ușor decât sfințenia, iar de la ziua reașezării temeliei este promisă binecuvântare; finalul îl numește pe Zorobabel ca pe un inel de pecete."}
  }},
  zaharia:{verseCounts:{1:21,2:13,3:10,4:14,5:11,6:15,7:14,8:23,9:17,10:12,11:17,12:14,13:9,14:21},narratives:{
    1:{title:"Întoarceți-vă la Mine și vedenia călăreților",summary:"Cartea începe cu chemarea de a nu repeta încăpățânarea părinților, ci de a se întoarce la DOMNUL. Apoi Zaharia vede călăreții care raportează liniștea pământului, iar Dumnezeu promite din nou milă pentru Ierusalim; vedenia coarnelor și meșterilor arată puterile care au risipit Iuda și răspunsul împotriva lor."},
    2:{title:"Omul cu funia de măsurat",summary:"Ierusalimul este măsurat, dar cetatea viitoare este descrisă atât de întinsă încât zidurile nu o pot cuprinde, iar Dumnezeu însuși va fi zid de foc și slavă în mijlocul ei. Exilații sunt chemați să iasă din Babilon, iar multe națiuni se vor alipi DOMNULUI."},
    3:{title:"Iosua, hainele murdare și Odrasla",summary:"Marele preot Iosua stă înaintea îngerului cu haine murdare, în timp ce acuzatorul este mustrat. Hainele sunt schimbate cu unele curate, iar Iosua primește o chemare la ascultare și un semn legat de Robul numit Odrasla și de îndepărtarea nelegiuirii într-o singură zi."},
    4:{title:"Sfeșnicul, măslinii și «nu prin putere»",summary:"Zaharia vede un sfeșnic de aur alimentat de doi măslini și primește mesajul pentru Zorobabel că lucrarea nu se face prin putere sau tărie omenească, ci prin Duhul lui Dumnezeu. Mâinile care au pus temelia vor termina Casa, iar ziua lucrurilor mici nu trebuie disprețuită."},
    5:{title:"Sulul zburător și femeia din efă",summary:"Un sul zburător poartă blestemul împotriva furtului și jurământului fals și intră în casele vinovaților. A doua vedenie arată nelegiuirea personificată într-o efă, închisă și transportată spre Șinear, unde i se construiește o casă."},
    6:{title:"Cele patru care și coroana lui Iosua",summary:"Patru care ies dintre doi munți de bronz și sunt trimise în cele patru direcții ale pământului, ca duhuri ale cerului. Apoi argintul și aurul exilaților sunt folosite pentru o coroană pusă pe capul lui Iosua, semn legat de omul numit Odrasla care va zidi templul și va uni rolurile de rege și preot."},
    7:{title:"Postul fără dreptate este pus sub semnul întrebării",summary:"O delegație întreabă dacă postul de comemorare mai trebuie ținut, iar Dumnezeu răspunde întrebând pentru cine au postit cu adevărat. Mesajul se întoarce la cuvintele vechilor proroci: dreptate adevărată, bunătate, milă și refuzul de a asupri pe cel vulnerabil."},
    8:{title:"Ierusalimul restaurat și posturile transformate în sărbători",summary:"Dumnezeu promite să Se întoarcă în Sion, unde bătrânii și copiii vor umple din nou străzile, iar poporul va primi rod și pace. Ei sunt chemați să vorbească adevărul și să iubească pacea, iar vechile posturi devin zile de bucurie; națiunile vor veni să-L caute pe DOMNUL."},
    9:{title:"Judecata vecinilor și Împăratul smerit",summary:"Oracolul trece prin Siria, Tir, Sidon și cetățile filistene, anunțând schimbări de putere și protecția Ierusalimului. În centru apare Împăratul drept și mântuitor venind smerit pe măgar, iar domnia Lui aduce pace până la marginile pământului."},
    10:{title:"Păstorul adevărat și întoarcerea poporului",summary:"Poporul este chemat să ceară ploaie de la DOMNUL în locul idolilor și ghicitorilor care dau mângâiere falsă. Mânia este împotriva păstorilor, dar Dumnezeu își cercetează turma, întărește Iuda și Iosif și îi aduce înapoi din împrăștiere."},
    11:{title:"Păstorul respins și cei treizeci de arginți",summary:"După imagini de păduri și păstori care plâng, prorocul joacă rolul unui păstor al turmei destinate tăierii, folosind două toiege numite Bunătate și Legături. Când slujirea este evaluată la treizeci de arginți, suma este aruncată în Casa DOMNULUI, iar finalul descrie un păstor nebun care nu îngrijește turma."},
    12:{title:"Ierusalimul asediat și duhul de har",summary:"Ierusalimul devine o piatră grea pentru națiunile care se adună împotriva lui, iar Dumnezeu promite să apere locuitorii. Punctul de cotitură este turnarea unui duh de har și rugăciune, urmată de privirea spre Cel străpuns și de un doliu profund al întregii țări."},
    13:{title:"Izvor pentru curățire și păstorul lovit",summary:"Un izvor este deschis pentru curățirea de păcat și necurăție, iar idolii și prorocia falsă sunt îndepărtate. Apoi sabia este chemată împotriva păstorului, turma se împrăștie și o rămășiță trece prin foc, fiind curățită și recunoscută ca popor al lui Dumnezeu."},
    14:{title:"Ziua DOMNULUI și Împărat peste tot pământul",summary:"Națiunile se adună împotriva Ierusalimului, cetatea trece prin suferință, iar DOMNUL intervine și picioarele Lui stau pe Muntele Măslinilor. Ape vii ies din Ierusalim, DOMNUL devine Împărat peste tot pământul, iar finalul extinde sfințenia chiar asupra obiectelor obișnuite din cetate."}
  }},
  maleahi:{verseCounts:{1:14,2:17,3:18,4:6},narratives:{
    1:{title:"«V-am iubit» și jertfele aduse fără onoare",summary:"Cartea începe cu declarația iubirii lui Dumnezeu, pusă sub semnul întrebării de popor, și cu contrastul dintre Iacov și Edom. Preoții sunt apoi mustrați pentru că aduc animale oarbe, bolnave și șchioape, oferind lui Dumnezeu ceea ce nu ar îndrăzni să ofere unui guvernator."},
    2:{title:"Preoți care au stricat legământul și infidelitate în căsătorie",summary:"Preoții sunt avertizați că au părăsit modelul lui Levi, care trebuia să păstreze cunoașterea și să întoarcă pe mulți de la fărădelege. A doua parte confruntă infidelitatea față de soția legământului și violența care acoperă haina, cerând păzirea duhului."},
    3:{title:"Solul, curățirea, darurile și cartea de aducere aminte",summary:"Un sol pregătește calea înaintea venirii Domnului în templu, care curăță pe fiii lui Levi ca focul topitorului. Poporul este confruntat pentru reținerea darurilor și pentru cuvintele amare împotriva slujirii lui Dumnezeu, dar cei care se tem de DOMNUL vorbesc unii cu alții și sunt înscriși într-o carte de aducere aminte."},
    4:{title:"Ziua care arde și soarele dreptății",summary:"Ziua viitoare este descrisă ca un cuptor pentru cei mândri și răi, dar pentru cei ce se tem de Numele lui Dumnezeu răsare soarele dreptății cu vindecare. Ultimele versete cheamă la amintirea Legii lui Moise și anunță venirea lui Ilie înaintea zilei DOMNULUI, pentru întoarcerea inimilor între generații."}
  }}
} as const
